import YangMills.RG.BalabanCMP99SourceScaledStratification

/-!
PRE-VALIDATION: source is present in scratch only; no `.olean` has been
materialized and no compiler or axiom-oracle verdict exists for this module.

# CMP99 p. 396: physical regular cubes

The printed cube is not represented by a free finite carrier.  It is generated
as a periodic axis cube of `geometryFactor * M` big blocks on the dependent
scale lattice selected by its unique index.  Its fine carrier is then the
literal `biUnion` of the scaled stratification's `fineBlock` map.

The p. 396 adjacent-stratum formula mentions `Lambda_(j+1)` also at maximal
`j`.  CMP99 p. 393 supplies only `Lambda_0,...,Lambda_k` and the terminal
`Omega_(k+1)=empty`.  `cmp99SourceExtendedFineStratum` records the canonical
terminal-empty completion; it is derived data, not a caller-provided stratum.
-/

namespace YangMills.RG

noncomputable section

universe u

/-- Periodic translation of an offset in an axis cube of scale sites. -/
def cmp99SourcePeriodicAxisCubePoint
    {N side : ℕ} (hN : 0 < N) (base : FinBox 4 N)
    (offset : Fin 4 → Fin side) : FinBox 4 N :=
  fun mu =>
    ⟨((base mu).val + (offset mu).val) % N, Nat.mod_lt _ hN⟩

/-- The literal periodic axis cube with `side` big blocks per coordinate. -/
noncomputable def cmp99SourcePeriodicAxisCube
    {N : ℕ} (hN : 0 < N) (base : FinBox 4 N) (side : ℕ) :
    Finset (FinBox 4 N) :=
  (Finset.univ : Finset (Fin 4 → Fin side)).image
    (cmp99SourcePeriodicAxisCubePoint (side := side) hN base)

@[simp] theorem mem_cmp99SourcePeriodicAxisCube_iff
    {N : ℕ} (hN : 0 < N) (base : FinBox 4 N) (side : ℕ)
    (block : FinBox 4 N) :
    block ∈ cmp99SourcePeriodicAxisCube hN base side ↔
      ∃ offset : Fin 4 → Fin side,
        cmp99SourcePeriodicAxisCubePoint hN base offset = block := by
  simp [cmp99SourcePeriodicAxisCube]

/-- Fine-lattice completion of the source strata by one terminal empty value.

Below the terminal index this is definitionally the printed lifted stratum.
At the last index it is the literal terminal region `Omega_n`; its emptiness
is then a theorem from `global.final_empty`, rather than a programmed empty
branch or an additional caller-provided `Lambda`. -/
def cmp99SourceExtendedFineStratum
    {FineSite : Type u} [DecidableEq FineSite]
    {n : ℕ} {scaleExtent : Fin n → ℕ}
    (S : CMP99SourceScaledStratification FineSite n
      (fun r => FinBox 4 (scaleExtent r)))
    (r : Fin (n + 1)) : Finset FineSite :=
  if hr : r.val < n then S.global.stratum ⟨r.val, hr⟩
  else S.global.regions (Fin.last n)

@[simp] theorem cmp99SourceExtendedFineStratum_castSucc
    {FineSite : Type u} [DecidableEq FineSite]
    {n : ℕ} {scaleExtent : Fin n → ℕ}
    (S : CMP99SourceScaledStratification FineSite n
      (fun r => FinBox 4 (scaleExtent r)))
    (r : Fin n) :
    cmp99SourceExtendedFineStratum S r.castSucc = S.global.stratum r := by
  simp [cmp99SourceExtendedFineStratum, r.isLt]

@[simp] theorem cmp99SourceExtendedFineStratum_last
    {FineSite : Type u} [DecidableEq FineSite]
    {n : ℕ} {scaleExtent : Fin n → ℕ}
    (S : CMP99SourceScaledStratification FineSite n
      (fun r => FinBox 4 (scaleExtent r))) :
    cmp99SourceExtendedFineStratum S (Fin.last n) = ∅ := by
  simp [cmp99SourceExtendedFineStratum, S.global.final_empty]

/-- Before applying terminal emptiness, the completed last stratum is exactly
the terminal region stored in the source stratification. -/
theorem cmp99SourceExtendedFineStratum_last_eq_terminalRegion
    {FineSite : Type u} [DecidableEq FineSite]
    {n : ℕ} {scaleExtent : Fin n → ℕ}
    (S : CMP99SourceScaledStratification FineSite n
      (fun r => FinBox 4 (scaleExtent r))) :
    cmp99SourceExtendedFineStratum S (Fin.last n) =
      S.global.regions (Fin.last n) := by
  simp [cmp99SourceExtendedFineStratum]

/-- The big-block carrier generated by the p. 396 cube data at its unique
scale.  The printed convention is `geometryFactor >= 10`; the side in scale
sites is `geometryFactor * M`. -/
noncomputable def cmp99SourceRegularCubeBigBlocks
    {n M : ℕ} {scaleExtent : Fin n → ℕ}
    (scaleExtent_pos : ∀ r, 0 < scaleExtent r)
    (scaleIndex : Fin n) (base : FinBox 4 (scaleExtent scaleIndex))
    (geometryFactor : ℕ) : Finset (FinBox 4 (scaleExtent scaleIndex)) :=
  cmp99SourcePeriodicAxisCube (scaleExtent_pos scaleIndex) base
    (geometryFactor * M)

/-- The corresponding literal fine carrier, obtained from the existing
dependent `fineBlock` realization and not supplied independently. -/
noncomputable def cmp99SourceRegularCubeFineCarrier
    {FineSite : Type u} [DecidableEq FineSite]
    {n M : ℕ} {scaleExtent : Fin n → ℕ}
    (S : CMP99SourceScaledStratification FineSite n
      (fun r => FinBox 4 (scaleExtent r)))
    (scaleExtent_pos : ∀ r, 0 < scaleExtent r)
    (scaleIndex : Fin n) (base : FinBox 4 (scaleExtent scaleIndex))
    (geometryFactor : ℕ) : Finset FineSite :=
  (cmp99SourceRegularCubeBigBlocks (M := M) scaleExtent_pos scaleIndex base
      geometryFactor).biUnion (S.fineBlock scaleIndex)

/-- Source-facing regular cube from CMP99 p. 396.

The carrier and its block decomposition are generated internally.  The two
stored laws are exactly the printed adjacent-stratum containment and the
nonempty intersection with the order-`j` stratum. -/
structure CMP99SourceRegularCube
    (FineSite : Type u) [DecidableEq FineSite]
    (n M : ℕ) [NeZero M] (scaleExtent : Fin n → ℕ)
    (S : CMP99SourceScaledStratification FineSite n
      (fun r => FinBox 4 (scaleExtent r)))
    (scaleExtent_pos : ∀ r, 0 < scaleExtent r) where
  scaleIndex : Fin n
  base : FinBox 4 (scaleExtent scaleIndex)
  geometryFactor : ℕ
  geometryFactor_ge_ten : 10 ≤ geometryFactor
  carrier_subset_adjacent_strata :
    cmp99SourceRegularCubeFineCarrier (M := M) S scaleExtent_pos scaleIndex
        base geometryFactor ⊆
      cmp99SourceExtendedFineStratum S scaleIndex.castSucc ∪
        cmp99SourceExtendedFineStratum S scaleIndex.succ
  carrier_meets_own_stratum :
    (cmp99SourceRegularCubeFineCarrier (M := M) S scaleExtent_pos scaleIndex
        base geometryFactor ∩ S.global.stratum scaleIndex).Nonempty
  scaleIndex_unique : ∀ r : Fin n,
    cmp99SourceRegularCubeFineCarrier (M := M) S scaleExtent_pos scaleIndex
        base geometryFactor ⊆
      cmp99SourceExtendedFineStratum S r.castSucc ∪
        cmp99SourceExtendedFineStratum S r.succ →
    (cmp99SourceRegularCubeFineCarrier (M := M) S scaleExtent_pos scaleIndex
        base geometryFactor ∩ S.global.stratum r).Nonempty →
    r = scaleIndex

namespace CMP99SourceRegularCube

variable {FineSite : Type u} [DecidableEq FineSite]
variable {n M : ℕ} {scaleExtent : Fin n → ℕ}
variable [NeZero M]
variable {S : CMP99SourceScaledStratification FineSite n
  (fun r => FinBox 4 (scaleExtent r))}
variable {scaleExtent_pos : ∀ r, 0 < scaleExtent r}

/-- The cube's big-block carrier is constructional, not a structure field. -/
noncomputable def bigBlocks
    (C : CMP99SourceRegularCube FineSite n M scaleExtent S scaleExtent_pos) :
    Finset (FinBox 4 (scaleExtent C.scaleIndex)) :=
  cmp99SourceRegularCubeBigBlocks (M := M) scaleExtent_pos C.scaleIndex C.base
    C.geometryFactor

/-- The cube's fine carrier is constructional, not a structure field. -/
noncomputable def carrier
    (C : CMP99SourceRegularCube FineSite n M scaleExtent S scaleExtent_pos) :
    Finset FineSite :=
  cmp99SourceRegularCubeFineCarrier (M := M) S scaleExtent_pos C.scaleIndex
    C.base C.geometryFactor

@[simp] theorem carrier_eq_biUnion_bigBlocks
    (C : CMP99SourceRegularCube FineSite n M scaleExtent S scaleExtent_pos) :
    C.carrier = C.bigBlocks.biUnion (S.fineBlock C.scaleIndex) :=
  rfl

/-- The printed intersection clause makes every regular cube nonempty. -/
theorem carrier_nonempty
    (C : CMP99SourceRegularCube FineSite n M scaleExtent S scaleExtent_pos) :
    C.carrier.Nonempty := by
  obtain ⟨x, hx⟩ := C.carrier_meets_own_stratum
  exact ⟨x, (Finset.mem_inter.mp hx).1⟩

/-- The index stored by a regular cube is the unique index satisfying the two
printed p. 396 stratum clauses. -/
theorem eq_scaleIndex_of_stratum_clauses
    (C : CMP99SourceRegularCube FineSite n M scaleExtent S scaleExtent_pos)
    (r : Fin n)
    (hsubset : C.carrier ⊆
      cmp99SourceExtendedFineStratum S r.castSucc ∪
        cmp99SourceExtendedFineStratum S r.succ)
    (hmeets : (C.carrier ∩ S.global.stratum r).Nonempty) :
    r = C.scaleIndex :=
  C.scaleIndex_unique r hsubset hmeets

end CMP99SourceRegularCube

end

end YangMills.RG
