import tmp.BalabanCMP99Eq360C6dSourceFixedInput.draft

/-!
PRE-VALIDATION: scratch source. This file has no materialized `.olean` and
no compiler or axiom-oracle verdict.

# Source-fixed positive-depth coercivity for the literal C6d baseline

The generic source-region coercivity theorem is applied to the canonical
union extension that simultaneously preserves the regional Laplacian and the
retained terminal `Qprime`.  The printed Eq. (3.24)/(3.60) coefficient is
constructed internally and transported by proved equalities; no operator,
coercivity witness, or coefficient identity is caller data.

Depth zero remains a separate exact base case.  This module only treats the
positive-depth Poincare branch.
-/

namespace YangMills.RG

noncomputable section

open YangMills Matrix
open scoped Matrix.Norms.L2Operator RealInnerProductSpace

variable {L N' M Mlarge Nc n depth : ℕ}
variable [NeZero L] [NeZero N'] [NeZero M] [NeZero Mlarge] [NeZero Nc]
variable {scaleExtent : Fin n → ℕ}
variable {S : CMP99SourceScaledStratification (FinBox 4 (L * N')) n
  (fun r => FinBox 4 (scaleExtent r))}
variable {scaleExtent_pos : ∀ r, 0 < scaleExtent r}
variable {U : PhysicalGaugeBackground 4 (L * N') Nc}
variable {eta alpha0 alpha1 : ℝ}
variable (R : CMP99Eq335PhysicalRegularityClass
  (L := L) (N' := N') (Mlarge := Mlarge) (Nc := Nc) (n := n)
  (scaleExtent := scaleExtent) (S := S)
  (scaleExtent_pos := scaleExtent_pos) U eta alpha0)
variable (C : CMP99SourceRegularCube (FinBox 4 (L * N')) n Mlarge
  scaleExtent S scaleExtent_pos)
variable (hscale : (C.geometryFactor : ℝ) * (Mlarge : ℝ) * alpha0 ≤ alpha1)
variable {Omega OmegaPrime0 : ActiveGaugeRegion 4 (L * N')}
variable (regions : CMP99SourceActiveRegionChain 4 M (L * N') Omega depth)
variable (D : CMP99Eq335Corollary36SourceRegionDictionary Omega OmegaPrime0 C)
variable (hM : 2 ≤ M) (halpha1 : alpha1 ≤ 1 / 2)
variable (baselineRadiusBudget : CMP99SourceUbarClosedBudget 4 M Nc depth
  (cmp99Eq335PhysicalRetainedNearIdentityRadius alpha1))

/-- The literal positive-depth floor generated by the Laplacian-aware source
tower.  Its coefficient is the source recurrence, not a free parameter. -/
noncomputable def cmp99Eq360C6dSourceBaselinePhysicalCoercivity : ℝ :=
  cmp99SourceActiveRegionTerminalPhysicalCoercivity
    (cmp99Eq360C6dSourceLaplacianRetainedPhysicalTower
      R C hscale regions D hM halpha1 baselineRadiusBudget)
    M depth (cmp99Eq335PhysicalRetainedNearIdentityRadius alpha1)

/-- The source-fixed C6d floor is positive whenever the absorbed Poincare
error is strictly below one. -/
theorem cmp99Eq360C6dSourceBaselinePhysicalCoercivity_pos
    (hdepth : 0 < depth) (heta : 0 < eta)
    (hsmall :
      cmp99SourcePoincareErrorCoeff 4 M depth eta
        (cmp99Eq335PhysicalRetainedNearIdentityRadius alpha1) < 1) :
    0 < cmp99Eq360C6dSourceBaselinePhysicalCoercivity
      R C hscale regions D hM halpha1 baselineRadiusBudget := by
  unfold cmp99Eq360C6dSourceBaselinePhysicalCoercivity
  exact cmp99SourceActiveRegionTerminalPhysicalCoercivity_pos
    regions (by norm_num : 2 ≤ 4) hM hdepth heta
    (cmp99Eq360C6dSourceLaplacianRetainedExtension
      R C hscale regions D hM halpha1 baselineRadiusBudget)
    baselineRadiusBudget.toRadiusChain
    (norm_cmp99Eq360C6dSourceLaplacianRetainedExtension_sub_one_le
      R C hscale regions D hM halpha1 baselineRadiusBudget)
    hsmall

/-- The literal source C6d baseline precision is coercive with the internally
generated floor.  The proof first uses the union-extension source theorem and
then transports back through the exact Laplacian and terminal-`Qprime`
identities. -/
theorem isCoerciveCLM_cmp99Eq360C6dSourceBaselinePrecision
    (hdepth : 0 < depth) (heta : 0 < eta)
    (hsmall :
      cmp99SourcePoincareErrorCoeff 4 M depth eta
        (cmp99Eq335PhysicalRetainedNearIdentityRadius alpha1) < 1) :
    let W := R.toCubeWitness C alpha1 hscale
    let T := cmp99Eq360C6dSourceBaselineRetainedPhysicalTower
      R C hscale regions D hM halpha1 baselineRadiusBudget
    let b := cmp99Eq360C6dSourcePhysicalCountingCoefficient
      R C hscale regions D hM halpha1 baselineRadiusBudget
    IsCoerciveCLM
      (cmp99SourceGaugePrecision
        (cmp99ActiveRegionSourceCovariantLaplacian Omega
          (matrixSUNAdjointModel Nc) W.transformedBackground eta)
        T.Qprime b)
      (cmp99Eq360C6dSourceBaselinePhysicalCoercivity
        R C hscale regions D hM halpha1 baselineRadiusBudget) := by
  dsimp only
  rw [cmp99Eq360C6dSourceBaselinePrecision_eq_laplacianRetainedPrecision
    R C hscale regions D hM halpha1 baselineRadiusBudget]
  rw [cmp99Eq360C6dSourcePhysicalCountingCoefficient_eq_laplacianRetained
    R C hscale regions D hM halpha1 baselineRadiusBudget]
  unfold cmp99Eq360C6dSourceBaselinePhysicalCoercivity
  simpa only [cmp99Eq360C6dSourceLaplacianRetainedPhysicalTower] using
    (isCoerciveCLM_cmp99SourceActiveRegionTerminalPhysicalPrecision
      regions (by norm_num : 2 ≤ 4) hM hdepth heta
      (cmp99Eq360C6dSourceLaplacianRetainedExtension
        R C hscale regions D hM halpha1 baselineRadiusBudget)
      baselineRadiusBudget.toRadiusChain
      (norm_cmp99Eq360C6dSourceLaplacianRetainedExtension_sub_one_le
        R C hscale regions D hM halpha1 baselineRadiusBudget)
      hsmall)

/-- The actual source-facing C6d input inherits the constructed baseline
coercivity.  Its perturbing data do not enter the baseline operator; unfolding
the constructor exposes exactly the source-fixed tower and coefficient above.
No equality is requested from the caller. -/
theorem isCoerciveCLM_cmp99Eq360C6dLocalizedRetainedSourceInput_baselinePhysicalPrecision
    (hdepth : 0 < depth)
    (hsmall :
      cmp99SourcePoincareErrorCoeff 4 M depth eta
        (cmp99Eq335PhysicalRetainedNearIdentityRadius alpha1) < 1)
    (A : PhysicalGaugeOneCochain 4 (L * N') Nc)
    (z rA Rmax : ℝ) (hrA : 0 ≤ rA)
    (hretained : ∀ b : PhysicalBond 4 (L * N'),
      ‖regions.retainedFineComplexOneCochain A b‖ ≤ rA)
    (hperturbation : |z| *
      (cmp99SUNLieComplexCoordMatrixNormBudget Nc * rA) ≤ 1 / 2)
    (perturbationRadiusBudget :
      letI : NeZero (4 * (M - 1)) :=
        cmp99Eq360C6dRadiusDimensionNeZero hM
      CMP99ComplexClosedRadiusBudget (4 * (M - 1)) M depth
        (cmp99Eq337PhysicalComplexPerturbedLinkRadius Nc
          (cmp99Eq335PhysicalRetainedNearIdentityRadius alpha1) z rA)
        Rmax (cmp99UbarNoWindingThreshold Nc)) :
    let I := cmp99Eq360C6dLocalizedRetainedSourceInput
      R C hscale regions D hM halpha1 baselineRadiusBudget
      A z rA Rmax hrA hretained hperturbation perturbationRadiusBudget
    IsCoerciveCLM I.baselinePhysicalPrecision
      (cmp99Eq360C6dSourceBaselinePhysicalCoercivity
        R C hscale regions D hM halpha1 baselineRadiusBudget) := by
  dsimp only
  let I := cmp99Eq360C6dLocalizedRetainedSourceInput
    R C hscale regions D hM halpha1 baselineRadiusBudget
    A z rA Rmax hrA hretained hperturbation perturbationRadiusBudget
  change IsCoerciveCLM I.baselinePhysicalPrecision _
  rw [I.baselinePhysicalPrecision_eq_generated]
  change IsCoerciveCLM
    (cmp99SourceGaugePrecision
      (cmp99ActiveRegionSourceCovariantLaplacian Omega
        (matrixSUNAdjointModel Nc)
        (R.toCubeWitness C alpha1 hscale).transformedBackground eta)
      (cmp99Eq360C6dSourceBaselineRetainedPhysicalTower
        R C hscale regions D hM halpha1 baselineRadiusBudget).Qprime
      (cmp99Eq360C6dSourcePhysicalCountingCoefficient
        R C hscale regions D hM halpha1 baselineRadiusBudget))
    _
  exact isCoerciveCLM_cmp99Eq360C6dSourceBaselinePrecision
    R C hscale regions D hM halpha1 baselineRadiusBudget
    hdepth R.eta_pos hsmall

end

end YangMills.RG
