"""Verbatim minimal extraction: interval proofs plus exact rectangle definitions.

Only imports, headers and audit commands are excluded; proof bodies are copied.
No generated bytes constitute compiler evidence. This has no network or writes.
"""
import re

DRAFT = 'tmp/NeumannImageRectangleCoverageDraft.lean'
INTERVAL = 'YangMills/RG/NeumannImageIntervalCoverage.lean'
ORBIT = 'YangMills/RG/BalabanCMP89NeumannReflectionOrbitAlgebra.lean'
BRANCH = 'YangMills/RG/BalabanCMP89NeumannReflectionBranchSum.lean'
SCALE = 'YangMills/RG/BalabanCMP89NeumannReflectionScaleDictionary.lean'
REPRESENTATION = 'YangMills/RG/BalabanCMP89NeumannReflectionRepresentation.lean'
INPUTS = [DRAFT, INTERVAL, ORBIT, BRANCH, SCALE, REPRESENTATION]
NAMES = [
    'neumannImageRectangleCoordinateEquiv',
    'neumannImageRectangleIndexEquiv_apply',
    'neumannImageRectangleFamilyEquiv_apply',
    'neumannImageRectangleFamily_bijective',
    'neumannImageRectangle_fixedPoint_injective',
]

def fragment(text, start, end):
    assert text.count(start) == 1, 'AMBIGUOUS_START=' + start
    a = text.index(start)
    return text[a:text.index(end, a)].rstrip() + '\n'

def make_repro(files):
    t = {p: files[p].decode('utf-8') for p in INPUTS}
    interval = t[INTERVAL]
    project_import = 'import YangMills.RG.BalabanCMP89NeumannReflectionOrbitAlgebra\n'
    assert interval.startswith(project_import)
    interval = interval[len(project_import):]
    namespace = 'namespace YangMills.RG\n'
    assert interval.count(namespace) == 1
    orbit = fragment(t[ORBIT], 'def cmp89NeumannReflectionOrbit ',
        '/-- The lower reflection exchanges')
    interval = interval.replace(namespace, namespace + '\n' + orbit, 1)
    assert '#print axioms' not in interval
    branch = fragment(t[BRANCH], 'abbrev CMP89NeumannReflectionBranch ',
        '/-- A branch carries')
    image = fragment(t[ORBIT], 'def cmp89NeumannReflectionImage ',
        'end YangMills.RG')
    rectangle = fragment(t[SCALE], 'def cmp89SourceNeumannBlockIntegerRectangle ',
        'theorem mem_cmp89SourceNeumannBlockIntegerRectangle_iff')
    point = fragment(t[REPRESENTATION], 'abbrev CMP89SourceNeumannIntegerRectanglePoint ',
        '/-- The source-shaped multiple-reflection series')
    draft = t[DRAFT]
    imports = ('import YangMills.RG.NeumannImageIntervalCoverage\n'
        'import YangMills.RG.BalabanCMP89NeumannReflectionRepresentation\n'
        'import Mathlib.Logic.Equiv.Prod\n')
    assert draft.startswith(imports)
    draft = draft[len(imports):]
    prelude = ('\nnamespace YangMills.RG\nvariable {d : ℕ}\n' +
        '\n'.join([branch, image, rectangle, point]) + '\nend YangMills.RG\n')
    result = 'import Mathlib.Logic.Equiv.Prod\n' + interval + prelude + draft
    assert 'import YangMills.' not in result
    actual = [line.removeprefix('#print axioms YangMills.RG.')
        for line in result.splitlines() if line.startswith('#print axioms ')]
    assert actual == NAMES
    return result.encode('utf-8')
