/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import Mathlib.Analysis.Analytic.ChangeOrigin
import Mathlib.Analysis.Analytic.IteratedFDeriv

/-!
# Third derivatives from a changed-origin analytic coefficient

For an analytic Banach-space map, the full third Fréchet derivative at an
interior point is the sum of the six permutations of the third coefficient
of the power series recentered at that point.  This file records the
corresponding operator-norm estimate.
-/

namespace YangMills.RG

open scoped ENNReal

noncomputable section

variable {E F : Type*}
variable [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [CompleteSpace F]

/-- Explicit majorant for the third changed-origin coefficient on the
closed radius-`r` ball.  Its summands are the literal coefficients of
`p`, with the exact change-of-origin multiplicity. -/
def thirdDerivativeChangeOriginBallBudget
    (p : FormalMultilinearSeries ℝ E F) (r : NNReal) : ℝ :=
  6 * (∑' s :
      Σ l : ℕ, {s : Finset (Fin (3 + l)) // s.card = l},
      ‖p (3 + s.1)‖₊ * r ^ s.1 : NNReal)

omit [CompleteSpace F] in
theorem thirdDerivativeChangeOriginBallBudget_nonneg
    (p : FormalMultilinearSeries ℝ E F) (r : NNReal) :
    0 ≤ thirdDerivativeChangeOriginBallBudget p r := by
  unfold thirdDerivativeChangeOriginBallBudget
  positivity

omit [CompleteSpace F] in
/-- The actual changed-origin coefficient is uniformly bounded by the
literal coefficient majorant on every strict sub-ball of convergence. -/
theorem six_mul_norm_changeOrigin_three_le_ballBudget
    (p : FormalMultilinearSeries ℝ E F) (r : NNReal)
    (hr : (r : ℝ≥0∞) < p.radius)
    {x : E} (hx : ‖x‖₊ ≤ r) :
    6 * ‖p.changeOrigin x 3‖ ≤
      thirdDerivativeChangeOriginBallBudget p r := by
  have hxrad : (‖x‖₊ : ℝ≥0∞) < p.radius :=
    (ENNReal.coe_le_coe.mpr hx).trans_lt hr
  have hsumX :=
    p.changeOriginSeries_summable_aux₂ hxrad 3
  have hsumR :=
    p.changeOriginSeries_summable_aux₂ hr 3
  have hcoeff :
      ‖p.changeOrigin x 3‖₊ ≤
        ∑' s :
          Σ l : ℕ, {s : Finset (Fin (3 + l)) // s.card = l},
          ‖p (3 + s.1)‖₊ * r ^ s.1 := by
    refine (p.nnnorm_changeOrigin_le 3 hxrad).trans ?_
    exact hsumX.tsum_le_tsum
      (fun s => by
        gcongr)
      hsumR
  unfold thirdDerivativeChangeOriginBallBudget
  exact mul_le_mul_of_nonneg_left (by exact_mod_cast hcoeff) (by norm_num)

/-- The third derivative is bounded by six times the norm of the actual
third changed-origin coefficient.  The coefficient is generated by the
given formal power series; it is not supplied as an independent jet. -/
theorem norm_iteratedFDeriv_three_le_six_mul_changeOrigin
    (f : E → F) (p : FormalMultilinearSeries ℝ E F)
    {r : ℝ≥0∞} (h : HasFPowerSeriesOnBall f p 0 r)
    (x : E) (hx : (‖x‖₊ : ℝ≥0∞) < r) :
    ‖iteratedFDeriv ℝ 3 f x‖ ≤
      6 * ‖p.changeOrigin x 3‖ := by
  have hchange :
      HasFPowerSeriesOnBall f (p.changeOrigin x) x (r - ‖x‖₊) := by
    simpa using h.changeOrigin hx
  have hC : 0 ≤ 6 * ‖p.changeOrigin x 3‖ := by positivity
  apply ContinuousMultilinearMap.opNorm_le_bound hC
  intro v
  rw [hchange.iteratedFDeriv_eq_sum_of_completeSpace v]
  calc
    ‖∑ σ : Equiv.Perm (Fin 3),
          p.changeOrigin x 3 (fun i => v (σ i))‖
        ≤ ∑ σ : Equiv.Perm (Fin 3),
            ‖p.changeOrigin x 3 (fun i => v (σ i))‖ :=
      norm_sum_le _ _
    _ ≤ ∑ _σ : Equiv.Perm (Fin 3),
          ‖p.changeOrigin x 3‖ * ∏ i, ‖v i‖ := by
      gcongr with σ
      calc
        ‖p.changeOrigin x 3 (fun i => v (σ i))‖
            ≤ ‖p.changeOrigin x 3‖ * ∏ i, ‖v (σ i)‖ :=
          ContinuousMultilinearMap.le_opNorm _ _
        _ = ‖p.changeOrigin x 3‖ * ∏ i, ‖v i‖ := by
          congr 1
          simpa only [Function.comp_apply] using
            Equiv.prod_comp σ (fun i => ‖v i‖)
    _ = (6 * ‖p.changeOrigin x 3‖) * ∏ i, ‖v i‖ := by
      simp [Fintype.card_perm, Nat.factorial]
      ring

/-- Uniform third-jet bound on a strict sub-ball, expressed entirely in
the coefficients of the source power series. -/
theorem norm_iteratedFDeriv_three_le_changeOriginBallBudget
    (f : E → F) (p : FormalMultilinearSeries ℝ E F)
    {R : ℝ≥0∞} (h : HasFPowerSeriesOnBall f p 0 R)
    (r : NNReal) (hr : (r : ℝ≥0∞) < p.radius)
    (hR : p.radius ≤ R)
    {x : E} (hx : ‖x‖₊ ≤ r) :
    ‖iteratedFDeriv ℝ 3 f x‖ ≤
      thirdDerivativeChangeOriginBallBudget p r := by
  have hxR : (‖x‖₊ : ℝ≥0∞) < R :=
    (ENNReal.coe_le_coe.mpr hx).trans_lt (hr.trans_le hR)
  exact
    (norm_iteratedFDeriv_three_le_six_mul_changeOrigin
      f p h x hxR).trans
      (six_mul_norm_changeOrigin_three_le_ballBudget p r hr hx)

end

end YangMills.RG
