/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/
import Mathlib
import YangMills.RG.AveragingL2

/-!
# The adjoint mass `Q†Q` of the linear RG averaging operator

This file packages the Hilbert-space algebra behind the deterministic part of
the gauge-RG small-field operator.  The already-verified operator
`linAvgCLM` is the linear averaging map `Q`; here we keep an explicit scalar
normalization `s` and form the positive operator

`qMass = (sQ)† (sQ)`.

This is the abstract `Q*Q` coercivity/mass term that appears in Balaban-style
Gaussian block kernels.  The scalar `s` is deliberately explicit: the correct
physical normalization belongs to the RG Hessian/source layer, not to the bare
linear averaging definition.

Honest scope: this proves only the Hilbert-space identities and operator norm
bound for `Q†Q`.  It does not prove gauge Hessian coercivity, finite-range
kernel support, or the Yang-Mills activity estimate.

Oracle target: `[propext, Classical.choice, Quot.sound]`. No sorry, no axioms.
-/

namespace YangMills.RG

open scoped RealInnerProductSpace

variable {d : ℕ} {V : Type*}
variable [NormedAddCommGroup V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]

/-- Fine additive bond fields at one RG step, with the finite-dimensional
`ℓ²`/Hilbert norm.  The plain function space already carries a sup norm in
Mathlib, so the adjoint theory must use `PiLp 2`. -/
abbrev FineBondHilbert (d L N' : ℕ) (V : Type*) :=
  PiLp 2 (fun _ : ConcreteEdge d (L * N') => V)

/-- Coarse additive bond fields at one RG step, with the finite-dimensional
`ℓ²`/Hilbert norm. -/
abbrev CoarseBondHilbert (d N' : ℕ) (V : Type*) :=
  PiLp 2 (fun _ : ConcreteEdge d N' => V)

/-- The linear averaging operator with an explicit scalar normalization.

Keeping `s` visible avoids baking a physical rescaling convention into the bare
operator. -/
noncomputable def scaledLinAvgCLM (s : ℝ) (L N' : ℕ) [NeZero L] [NeZero N']
    [Fintype (ConcreteEdge d (L * N'))] [Fintype (ConcreteEdge d N')] :
    FineBondHilbert d L N' V →L[ℝ] CoarseBondHilbert d N' V :=
  LinearMap.toContinuousLinearMap
    { toFun := fun A =>
        WithLp.toLp 2 (s • linAvg L N' (fun e => A e))
      map_add' := fun A B => by
        ext c
        change s • linAvg L N' (fun e => A e + B e) c
          = (s • linAvg L N' (fun e => A e)) c
            + (s • linAvg L N' (fun e => B e)) c
        rw [show (fun e => A e + B e)
            = (fun e => A e) + (fun e => B e) from rfl,
          linAvg_add, smul_add]
        rfl
      map_smul' := fun r A => by
        ext c
        change s • linAvg L N' (fun e => r • A e) c
          = r • (s • linAvg L N' (fun e => A e)) c
        rw [show (fun e => r • A e) = r • (fun e => A e) from rfl,
          linAvg_smul]
        rw [smul_comm]
        rfl }

@[simp] theorem scaledLinAvgCLM_apply (s : ℝ) (L N' : ℕ) [NeZero L] [NeZero N']
    [Fintype (ConcreteEdge d (L * N'))] [Fintype (ConcreteEdge d N')]
    (A : FineBondHilbert d L N' V) (c : ConcreteEdge d N') :
    scaledLinAvgCLM (d := d) (V := V) s L N' A c
      = s • linAvg L N' (fun e => A e) c := by
  rfl

/-- The positive `Q†Q` mass generated by the scaled averaging operator. -/
noncomputable def qMassCLM (s : ℝ) (L N' : ℕ) [NeZero L] [NeZero N']
    [Fintype (ConcreteEdge d (L * N'))] [Fintype (ConcreteEdge d N')] :
    FineBondHilbert d L N' V →L[ℝ] FineBondHilbert d L N' V :=
  let Q : FineBondHilbert d L N' V →L[ℝ] CoarseBondHilbert d N' V :=
    scaledLinAvgCLM (d := d) (V := V) s L N'
  Q.adjoint.comp Q

/-- **Energy identity for `Q†Q`.**  Pairing a field with the adjoint mass equals
the squared norm of the scaled average: `⟪A, Q†Q A⟫ = ‖Q A‖²`. -/
theorem inner_qMassCLM_self (s : ℝ) (L N' : ℕ) [NeZero L] [NeZero N']
    [Fintype (ConcreteEdge d (L * N'))] [Fintype (ConcreteEdge d N')]
    (A : FineBondHilbert d L N' V) :
    inner ℝ A (qMassCLM (d := d) (V := V) s L N' A)
      = ‖scaledLinAvgCLM (d := d) (V := V) s L N' A‖ ^ 2 := by
  dsimp [qMassCLM]
  rw [ContinuousLinearMap.adjoint_inner_right, real_inner_self_eq_norm_sq]

/-- **Positivity of the adjoint mass.**  The operator `Q†Q` is positive
semidefinite. -/
theorem qMassCLM_psd (s : ℝ) (L N' : ℕ) [NeZero L] [NeZero N']
    [Fintype (ConcreteEdge d (L * N'))] [Fintype (ConcreteEdge d N')]
    (A : FineBondHilbert d L N' V) :
    0 ≤ inner ℝ A (qMassCLM (d := d) (V := V) s L N' A) := by
  rw [inner_qMassCLM_self]
  positivity

/-- **Operator-norm control for `Q†Q`.**  The adjoint mass has norm bounded by
the square of the scaled averaging operator norm.  In fact Mathlib proves
equality for `A†A`; the inequality form is the one consumed by coercivity and
perturbative estimates. -/
theorem qMassCLM_opNorm_le (s : ℝ) (L N' : ℕ) [NeZero L] [NeZero N']
    [Fintype (ConcreteEdge d (L * N'))] [Fintype (ConcreteEdge d N')] :
    ‖qMassCLM (d := d) (V := V) s L N'‖
      ≤ ‖scaledLinAvgCLM (d := d) (V := V) s L N'‖ ^ 2 := by
  rw [qMassCLM, ContinuousLinearMap.norm_adjoint_comp_self, pow_two]

end YangMills.RG
