import YangMills.RG.BalabanCMP99SourceEq395AtomSourceSupport

open YangMills.RG

#print axioms cmp99Eq395SourceRelevantLabels
#print axioms mem_cmp99Eq395SourceRelevantLabels_iff
#print axioms fst_eq_sourceBaseCellOwner_of_mem_cmp99Eq395SourceRelevantLabels
#print axioms card_cmp99Eq395SourceRelevantLabels_le_three
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalRAtom_apply_single_eq_zero_of_source
#print axioms CMP99SourceDependentOmegaGeometry.sum_cmp99Eq395PhysicalRAtom_apply_single_eq_sum_relevant
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrection_apply_single_eq_sum_relevant
