import YangMills.RG.BalabanCMP116SourceRestrictedCoordinatePivotTsumTrace

#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_sub_one_eq_tsum_layers
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_sub_one_trace_mul_pow_eq_tsum_layers
#print axioms YangMills.RG.trace_cmp116SourcePi4FullComplexRelativeCovarianceDefect_pow_succ_eq_tsum_layers
