import YangMills.RG.BalabanCMP109LocalizedActionExpansion

#print axioms YangMills.RG.CMP109LocalizedActionExpansion
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.positiveBondField
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.changedPositiveBonds
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.positiveBondField_eq_of_not_mem_changedPositiveBonds
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.globalEval
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.energyDifference
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.affectedDomains
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.activity_globalEval_eq_of_disjoint_changed
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.energyDifference_eq_sum_affectedDomains
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.norm_energyDifference_le_sum_affectedDomains
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.energyDifference_eq_sum_changedPositiveBonds
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.norm_energyDifference_le_sum_changedPositiveBonds
#print axioms YangMills.RG.CMP109LocalizedActionExpansion.affectedDomain_has_changed_bond
