import YangMills.RG.BalabanCMP102PhysicalIntrinsicFixedPointFirstJet

#print axioms YangMills.RG.cmp102SourceIntrinsicPhysicalBackgroundCorrectionMapDerivativeLipschitzBudget_nonneg
#print axioms YangMills.RG.norm_fderiv_cmp102IntrinsicPhysicalBackgroundCorrectionMapUncurry_apply_le
#print axioms YangMills.RG.norm_iteratedFDeriv_one_cmp102IntrinsicPhysicalBackgroundCorrectionMapUncurry_le
