/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80SourcePi4DomainEnumeration
import YangMills.RG.BalabanCMP109Lemma1CoarsenedResidualFamily

/-!
# A common centered region for the direct and CMP109 Lemma-1 sectors

The terminal CMP116 source uses one block region `Z₀` for every residual
index.  The direct equation-(80) family already has a canonical centered
region.  A generic CMP109 localized-action expansion does not imply that its
coarsened native supports lie in that direct region.  This module therefore
constructs the least localization core generated by both finite support
families and proves the two required inclusions.

This is an explicit enlargement of `Z₀`, not a restriction or a discarded
boundary sector.  Consequently it closes the geometric shape of
`domain_subset`, while the cardinality cost of the enlarged region remains a
visible input to the later `volume_budget`.  No bound on that cost and no
`CMP116Eq226PhysicalContourTermSource` are claimed here.
-/

namespace YangMills.RG

noncomputable section

/-- Enlarging either the domain family or the distinguished bond set can
only enlarge the canonical localization core.  This lemma lives at the
consumer layer so that adjoining it does not invalidate the lower geometric
object cache. -/
theorem cmp116LocalizationCore_mono_for_combinedRegion {d M N' : ℕ}
    [NeZero M] [NeZero N']
    {D D' : Finset (Finset (FinBox d N'))}
    {P P' : Finset (PhysicalBond d (M * N'))}
    (hDD' : D ⊆ D') (hPP' : P ⊆ P') :
    cmp116LocalizationCore D P ⊆ cmp116LocalizationCore D' P' := by
  classical
  intro c hc
  rw [mem_cmp116LocalizationCore_iff] at hc ⊢
  rcases hc with hc | ⟨e, heP, hce⟩
  · exact Or.inl (cmp116LocalizationSeed_mono hDD' hPP' hc)
  · exact Or.inr ⟨e, hPP' heP, hce⟩

/-- The finite family of all distinct coarsened supports carried by native
CMP109 Lemma-1 indices.  Coincident supports may be merged here because this
family is used only to generate `Z₀`; the residual ledger itself keeps the
native indices distinct. -/
noncomputable def cmp109Lemma1NativeCoarsenedSupportFamily
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc) :
    Finset (Finset (FinBox 4 (2 * Q))) :=
  (cmp109Lemma1NativeDomainFamily E).image cmp109Lemma1CoarsenedBlocks

/-- Every literal native terminal index contributes its coarsened support to
the common support family. -/
theorem cmp109Lemma1NativeIndexedDomainSupport_mem_supportFamily
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (i : Fin (CMP109Lemma1NativeDomainCount E)) :
    cmp109Lemma1NativeIndexedDomainSupport E i ∈
      cmp109Lemma1NativeCoarsenedSupportFamily E := by
  classical
  apply Finset.mem_image.mpr
  exact ⟨cmp109Lemma1NativeDomainAt E i,
    cmp109Lemma1NativeDomainAt_mem E i, rfl⟩

/-- Literal union of the direct equation-(80) block domains and all
coarsened native Lemma-1 supports. -/
noncomputable def cmp116Eq80Lemma1CombinedBlockDomainFamily
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc) :
    Finset (Finset (FinBox 4 (2 * Q))) :=
  cmp102Eq80SourcePi4BlockDomainFamily anchor D ∪
    cmp109Lemma1NativeCoarsenedSupportFamily E

/-- Canonical common `Z₀`.  Its bond argument is exactly the one already used
by the direct centered region; only the finite block-domain family is
enlarged. -/
noncomputable def cmp116Eq80Lemma1CombinedCenteredRegion
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q)))) :
    Finset (FinBox 4 (2 * Q)) :=
  cmp116LocalizationCore
    (cmp116Eq80Lemma1CombinedBlockDomainFamily anchor D E)
    (P ∪ cmp102Eq80SourcePi4PhysicalY0 (M := M) anchor D)

/-- The old direct centered region embeds monotonically into the common
region.  Hence every already-proved direct interior statement transports
without changing its physical bond set. -/
theorem cmp102Eq80SourcePi4CenteredRegion_subset_combinedCenteredRegion
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q)))) :
    cmp102Eq80SourcePi4CenteredRegion anchor D P ⊆
      cmp116Eq80Lemma1CombinedCenteredRegion anchor D E P := by
  apply cmp116LocalizationCore_mono_for_combinedRegion
  · exact Finset.subset_union_left
  · exact fun _ h => h

/-- Every coarsened native support is contained in the common `Z₀`.  This is
the native-sector contribution to the terminal `domain_subset` field. -/
theorem cmp109Lemma1NativeIndexedDomainSupport_subset_combinedCenteredRegion
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (i : Fin (CMP109Lemma1NativeDomainCount E)) :
    cmp109Lemma1NativeIndexedDomainSupport E i ⊆
      cmp116Eq80Lemma1CombinedCenteredRegion anchor D E P := by
  intro c hc
  apply cmp116LocalizationSeed_subset_core
  apply cmp116Eq23Y0_subset_localizationSeed
  apply mem_cmp116Eq23Y0_iff.mpr
  exact ⟨cmp109Lemma1NativeIndexedDomainSupport E i,
    Finset.mem_union_right _
      (cmp109Lemma1NativeIndexedDomainSupport_mem_supportFamily E i), hc⟩

/-- Direct source-domain bonds remain bilaterally interior after adjoining
the native Lemma-1 supports. -/
theorem cmp102Eq80SourcePi4IndexedLocalizationDomain_bondSupport_subset_combinedRegionInterior
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (i : Fin (CMP102Eq80SourcePi4DomainCount anchor D)) :
    (cmp102Eq80SourcePi4IndexedLocalizationDomain
        (M := M) anchor D i).bondSupport ⊆
      PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds
        (cmp116Eq80Lemma1CombinedCenteredRegion anchor D E P) := by
  intro bond hbond
  have hold :=
    cmp102Eq80SourcePi4IndexedLocalizationDomain_bondSupport_subset_centeredRegionInterior
      anchor D P i hbond
  rw [PhysicalGaugeCMP116Dictionary.mem_cmp116Eq223PhysicalInteriorBonds_iff]
    at hold ⊢
  rw [cmp116BondInterior_iff_blocks_subset] at hold ⊢
  intro c hc
  exact cmp102Eq80SourcePi4CenteredRegion_subset_combinedCenteredRegion
    anchor D E P (hold hc)

/-- Projecting first to the combined centered region and then to a direct
source domain is exactly the direct source-domain projection.  This is a
geometric identity; it does not depend on any proposed cutoff carrier. -/
theorem physicalBondProjection_indexedSourceDomain_combinedCenteredRegion
    {Index : Type*} {M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    [NeZero Nc] [NeZero (Nc ^ 2 - 1)] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (i : Fin (CMP102Eq80SourcePi4DomainCount anchor D))
    (A : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc) :
    let Y := cmp102Eq80SourcePi4IndexedLocalizationDomain
      (M := M) anchor D i
    let Z0 := cmp116Eq80Lemma1CombinedCenteredRegion anchor D E P
    physicalBondProjection Y.bondSupport
        (physicalBondProjection
          (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
          A) =
      physicalBondProjection Y.bondSupport A := by
  dsimp only
  apply PiLp.ext
  intro bond
  by_cases hbond : bond ∈
      (cmp102Eq80SourcePi4IndexedLocalizationDomain
        (M := M) anchor D i).bondSupport
  · have hinterior :
        bond ∈
          PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds
            (cmp116Eq80Lemma1CombinedCenteredRegion anchor D E P) :=
      cmp102Eq80SourcePi4IndexedLocalizationDomain_bondSupport_subset_combinedRegionInterior
        anchor D E P i hbond
    simp [physicalBondProjection_apply_mem, hbond, hinterior]
  · simp [physicalBondProjection_apply_not_mem, hbond]

end

end YangMills.RG
