/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP98UbarPhysicalLinearization

/-!
# Source-shaped contour split of CMP98 equation (124)

The first term printed in CMP98 (124) is generated by differentiating the
middle straight contour `[x,x']`.  At the raw ordered-product level, the
remaining derivative is generated by the entrance contour, the exit contour,
and the adjoint coarse transport.  This file makes that four-factor derivative
split exact before the further algebraic regrouping with `g(ad)` and
`g(ad)⁻¹` used in the printed four-term formula.

The three raw contour corrections below are therefore not asserted to be
term-by-term identical to the three correction lines printed in (124).  The
distinguished middle-contour term is also not yet identified here with the
Lie-coordinate operator `Q₀` of (125).  That subsequent dictionary must
account for the adjoint transports, the extra inverse block length, and the
source's conventional `1/i` normalization.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped BigOperators Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp98Eq124MatrixL2NormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- The ordered contribution produced by differentiating one of the four
literal contour factors while leaving the other three fixed. -/
def cmp98UbarContourVariationTerm
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    Fin 4 → Matrix (Fin Nc) (Fin Nc) ℂ :=
  ![((cmp98UbarContourFactorVariations U A b x 0 t *
        cmp98UbarContourFactors U A b x 1 t) *
      cmp98UbarContourFactors U A b x 2 t) *
        cmp98UbarContourFactors U A b x 3 t,
    ((cmp98UbarContourFactors U A b x 0 t *
        cmp98UbarContourFactorVariations U A b x 1 t) *
      cmp98UbarContourFactors U A b x 2 t) *
        cmp98UbarContourFactors U A b x 3 t,
    ((cmp98UbarContourFactors U A b x 0 t *
        cmp98UbarContourFactors U A b x 1 t) *
      cmp98UbarContourFactorVariations U A b x 2 t) *
        cmp98UbarContourFactors U A b x 3 t,
    ((cmp98UbarContourFactors U A b x 0 t *
        cmp98UbarContourFactors U A b x 1 t) *
      cmp98UbarContourFactors U A b x 2 t) *
        cmp98UbarContourFactorVariations U A b x 3 t]

/-- The noncommutative product rule is exactly the sum of the four ordered
single-factor variations. -/
theorem cmp98UbarDeviationFirstVariation_eq_sum_contourTerms
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    cmp98UbarDeviationFirstVariation U A b x t =
      ∑ i : Fin 4, cmp98UbarContourVariationTerm U A b x t i := by
  rw [Fin.sum_univ_four]
  simp only [cmp98UbarDeviationFirstVariation, fourFactorFirst,
    cmp98UbarContourVariationTerm, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.cons_val_two, Matrix.cons_val_three]
  noncomm_ring

/-- The distinguished middle-contour contribution, corresponding to the
first line of the right-hand side of CMP98 (124). -/
def cmp98UbarMiddleContourVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    Matrix (Fin Nc) (Fin Nc) ℂ :=
  cmp98UbarContourVariationTerm U A b x t 1

/-- Sum of the raw entrance, exit, and inverse-coarse-transport derivatives. -/
def cmp98UbarThreeContourCorrections
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    Matrix (Fin Nc) (Fin Nc) ℂ :=
  cmp98UbarContourVariationTerm U A b x t 0 +
    cmp98UbarContourVariationTerm U A b x t 2 +
    cmp98UbarContourVariationTerm U A b x t 3

/-- Exact local split into the middle-contour main contribution and the
three remaining contour corrections. -/
theorem cmp98UbarDeviationFirstVariation_eq_middle_add_corrections
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    cmp98UbarDeviationFirstVariation U A b x t =
      cmp98UbarMiddleContourVariation U A b x t +
        cmp98UbarThreeContourCorrections U A b x t := by
  rw [cmp98UbarDeviationFirstVariation_eq_sum_contourTerms,
    Fin.sum_univ_four]
  simp only [cmp98UbarMiddleContourVariation,
    cmp98UbarThreeContourCorrections, Matrix.cons_val_zero,
    Matrix.cons_val_one, Matrix.cons_val_two, Matrix.cons_val_three]
  abel

/-- Contribution of the middle contour after applying the complete local
Mercator derivative and averaging over the source block. -/
def cmp98Eq124MiddleLogVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') : Matrix (Fin Nc) (Fin Nc) ℂ :=
  ((M : ℝ) ^ d)⁻¹ •
    ∑ x ∈ blockOf M N' b.1,
      (∑' n : ℕ,
        nearLogTermFDeriv
          (cmp98UbarAmbientDeviationMatrix U b x 0) n)
        (cmp98UbarMiddleContourVariation U A b x 0)

/-- The three raw contour-derivative contributions after applying the same
local Mercator derivative and block average.  A later source dictionary must
regroup these with the middle term into the three algebraic correction lines
printed in CMP98 (124). -/
def cmp98Eq124CorrectionLogVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') : Matrix (Fin Nc) (Fin Nc) ℂ :=
  ((M : ℝ) ^ d)⁻¹ •
    ∑ x ∈ blockOf M N' b.1,
      (∑' n : ℕ,
        nearLogTermFDeriv
          (cmp98UbarAmbientDeviationMatrix U b x 0) n)
        (cmp98UbarThreeContourCorrections U A b x 0)

/-- Exact block-level split of the physical logarithmic derivative into the
middle contour and the three noncommutative corrections of (124). -/
theorem cmp98UbarLogAveragePhysicalVariation_eq_middle_add_corrections
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') :
    cmp98UbarLogAveragePhysicalVariation U A b =
      cmp98Eq124MiddleLogVariation U A b +
        cmp98Eq124CorrectionLogVariation U A b := by
  unfold cmp98UbarLogAveragePhysicalVariation
    cmp98Eq124MiddleLogVariation cmp98Eq124CorrectionLogVariation
  calc
    _ = ((M : ℝ) ^ d)⁻¹ •
        ((∑ x ∈ blockOf M N' b.1,
            (∑' n : ℕ, nearLogTermFDeriv
              (cmp98UbarAmbientDeviationMatrix U b x 0) n)
              (cmp98UbarMiddleContourVariation U A b x 0)) +
          (∑ x ∈ blockOf M N' b.1,
            (∑' n : ℕ, nearLogTermFDeriv
              (cmp98UbarAmbientDeviationMatrix U b x 0) n)
              (cmp98UbarThreeContourCorrections U A b x 0))) := by
      apply congrArg (((M : ℝ) ^ d)⁻¹ • ·)
      rw [← Finset.sum_add_distrib]
      apply Finset.sum_congr rfl
      intro x hx
      rw [← map_add,
        ← cmp98UbarDeviationFirstVariation_eq_middle_add_corrections]
    _ = _ := by
      let X : Matrix (Fin Nc) (Fin Nc) ℂ :=
        ∑ x ∈ blockOf M N' b.1,
          (∑' n : ℕ, nearLogTermFDeriv
            (cmp98UbarAmbientDeviationMatrix U b x 0) n)
            (cmp98UbarMiddleContourVariation U A b x 0)
      let Y : Matrix (Fin Nc) (Fin Nc) ℂ :=
        ∑ x ∈ blockOf M N' b.1,
          (∑' n : ℕ, nearLogTermFDeriv
            (cmp98UbarAmbientDeviationMatrix U b x 0) n)
            (cmp98UbarThreeContourCorrections U A b x 0)
      change ((M : ℝ) ^ d)⁻¹ • (X + Y) =
        ((M : ℝ) ^ d)⁻¹ • X + ((M : ℝ) ^ d)⁻¹ • Y
      ext i j
      simp [Pi.smul_apply, mul_add]

end

end YangMills.RG
