import YangMills.RG.BalabanCMP99SourceSelectedNextBackgroundLocality


#print axioms YangMills.RG.cmp99SourcePhysicalUbarBlockOfDeviationBudget
#print axioms YangMills.RG.cmp99SourcePhysicalUbarBlockOfDeviationBudget_coe_eq_Ubar
#print axioms YangMills.RG.cmp99PhysicalUbarBlockOfDeviationBudgetPinned
#print axioms YangMills.RG.cmp99PhysicalUbarBlockOfDeviationBudget_eq_of_eqOn_selectedReadBonds
#print axioms YangMills.RG.cmp99SourceRegionalNextBackgroundOfDeviationBudget
#print axioms YangMills.RG.cmp99SourceRegionalScaleDataOfDeviationBudget_nextBackground_apply_pos_eq
#print axioms YangMills.RG.cmp99SourceNormalizedRegionalScaleOfFineSmall_nextBackground_apply_pos_eq
