import YangMills.RG.BalabanCMP116SourcePi4MixedDerivativeDomainSeries

#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainPrefactor
#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainLayerAmplitude_eq_prefactor_mul
#print axioms YangMills.RG.hasSum_cmp116SourcePi4MixedDerivativeDomainLayerAmplitude
#print axioms YangMills.RG.summable_cmp116SourcePi4MixedDerivativeDomainLayerCoefficient
#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainCoefficient
#print axioms YangMills.RG.tendsto_cmp116SourcePi4MixedDerivativeDomainPartial
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrixMixedDerivative_eq_sum_domainCoefficient
