import YangMills.RG.BalabanCMP99SourceEq395LocalizedAtomSupport

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalRAtom_second_apply_single_eq_zero_of_target
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalRAtom_third_apply_single_eq_zero_of_target
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalRAtom_apply_single_eq_zero_of_target_of_ne_first
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalRAtom_apply_single_eq_zero_of_endpoint_of_ne_first
