import YangMills.RG.BalabanCMP102Eq80PhysicalCorrectionDerivativeBound

#print axioms
  YangMills.RG.norm_fderiv_cmp102Eq80PhysicalBackgroundCorrection_sup_le
#print axioms
  YangMills.RG.norm_iteratedFDeriv_one_cmp102Eq80PhysicalBackgroundCorrection_sup_le
#print axioms
  YangMills.RG.norm_iteratedFDeriv_one_cmp102Eq80PhysicalBackgroundCorrection_le_sourceBudget
