import YangMills.RG.BalabanCMP116SourceRestrictedPhysicalOuterResidualBoundary

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_sourcePi4PhysicalOuterResidual
