/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99PatchedWalkTerminalCoreSupport
import YangMills.RG.BalabanCMP99PatchedParametrixCollar

/-!
# First-hit factorization through one contour-active physical core

A restricted weakening contour changes a walk only when one of its ordered
domains activates a contour cube.  This file selects the first such occurrence
and inserts one common physical projection: the union of the cores of every
domain which meets the contour carrier.

Only source support is used.  No claim is made that the range of the complete
walk lies in the localized carrier.
-/

namespace YangMills.RG

noncomputable section

universe u w

private abbrev PhysicalEndomorphism (d N Nc : ℕ) [NeZero N] :=
  PhysicalGaugeOneCochain d N Nc →L[ℝ]
    PhysicalGaugeOneCochain d N Nc

/-- A physical patched head is unchanged after restricting its input again
to its own core. -/
theorem cmp99PhysicalPatchHead_comp_coreProjection
    {ι : Type u} [DecidableEq ι]
    {d N Nc : ℕ} [NeZero N]
    (charts : Finset ι)
    (K : PhysicalEndomorphism d N Nc)
    (enlarged core : ι → Finset (PhysicalBond d N))
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c) (i : ↥charts) :
    (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK i).comp
        (physicalBondProjection (core i)) =
      cmp99PhysicalPatchHead charts K enlarged core hc hmass hK i := by
  rw [cmp99PhysicalPatchHead, ContinuousLinearMap.comp_assoc,
    physicalBondProjection_comp_self]

/-- A physical patched continuation is unchanged after restricting its input
again to its own core. -/
theorem cmp99PhysicalPatchContinuation_comp_coreProjection
    {ι : Type u} [DecidableEq ι]
    {d N Nc : ℕ} [NeZero N]
    (charts : Finset ι)
    (K : PhysicalEndomorphism d N Nc)
    (enlarged core : ι → Finset (PhysicalBond d N))
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c) (i : ↥charts) :
    (cmp99PhysicalPatchContinuation
        charts K enlarged core hc hmass hK i).comp
        (physicalBondProjection (core i)) =
      cmp99PhysicalPatchContinuation
        charts K enlarged core hc hmass hK i := by
  rw [cmp99PhysicalPatchContinuation, ContinuousLinearMap.neg_comp]
  congr 1
  rw [ContinuousLinearMap.comp_assoc, ContinuousLinearMap.comp_assoc,
    physicalBondProjection_comp_self]

/-- The first factor which activates a contour cube reads only the single
common core generated by every contour-relevant chart. -/
theorem cmp99PhysicalPatchWalk_firstActiveFactor_comp_contourActiveCore
    {ι : Type u} [DecidableEq ι]
    {Cube : Type w} [DecidableEq Cube]
    {d N Nc : ℕ} [NeZero N]
    (charts : Finset ι)
    (K : PhysicalEndomorphism d N Nc)
    (enlarged core : ι → Finset (PhysicalBond d N))
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (domainActive : ↥charts → Finset Cube)
    (carrier : Finset Cube)
    (walk : CMP99GeneralizedWalk Unit ↥charts)
    (cube : Cube) (hactive : cube ∈ walk.active domainActive)
    (hcarrier : cube ∈ carrier) :
    (walk.firstActiveFactor domainActive
        (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
        (fun _ => cmp99PhysicalPatchContinuation
          charts K enlarged core hc hmass hK)
        cube hactive).comp
        (physicalBondProjection
          (CMP99GeneralizedWalk.contourActiveCore
            (fun i : ↥charts => core i) domainActive carrier)) =
      walk.firstActiveFactor domainActive
        (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
        (fun _ => cmp99PhysicalPatchContinuation
          charts K enlarged core hc hmass hK)
        cube hactive := by
  let index := walk.firstActiveDomainIndex domainActive cube hactive
  let X := walk.domains.get index
  let factor := walk.firstActiveFactor domainActive
    (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
    (fun _ => cmp99PhysicalPatchContinuation
      charts K enlarged core hc hmass hK)
    cube hactive
  have hfactor :
      factor.comp (physicalBondProjection (core X)) = factor := by
    exact walk.factorAt_property
      (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation
        charts K enlarged core hc hmass hK)
      (fun Y T => T.comp (physicalBondProjection (core Y)) = T)
      (cmp99PhysicalPatchHead_comp_coreProjection
        charts K enlarged core hc hmass hK)
      (fun _ =>
        cmp99PhysicalPatchContinuation_comp_coreProjection
          charts K enlarged core hc hmass hK)
      index
  have hXactive : cube ∈ domainActive X := by
    exact walk.mem_domainActive_get_firstActiveDomainIndex
      domainActive cube hactive
  have hsub :
      core X ⊆ CMP99GeneralizedWalk.contourActiveCore
        (fun i : ↥charts => core i) domainActive carrier :=
    CMP99GeneralizedWalk.core_subset_contourActiveCore_of_mem
      (fun i : ↥charts => core i) domainActive carrier X cube
      hXactive hcarrier
  change factor.comp
      (physicalBondProjection
        (CMP99GeneralizedWalk.contourActiveCore
          (fun i : ↥charts => core i) domainActive carrier)) = factor
  rw [← hfactor, ContinuousLinearMap.comp_assoc,
    physicalBondProjection_comp_of_subset_right hsub]

/-- Exact first-hit insertion of the common contour-active projection into
the ordered physical walk.  This is a factorization through an intermediate
input space, not a bilateral range-support statement. -/
theorem cmp99PhysicalPatchWalk_term_eq_firstHit_contourActiveCore
    {ι : Type u} [DecidableEq ι]
    {Cube : Type w} [DecidableEq Cube]
    {d N Nc : ℕ} [NeZero N]
    (charts : Finset ι)
    (K : PhysicalEndomorphism d N Nc)
    (enlarged core : ι → Finset (PhysicalBond d N))
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (domainActive : ↥charts → Finset Cube)
    (carrier : Finset Cube)
    (walk : CMP99GeneralizedWalk Unit ↥charts)
    (cube : Cube) (hactive : cube ∈ walk.active domainActive)
    (hcarrier : cube ∈ carrier) :
    walk.term
        (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
        (fun _ => cmp99PhysicalPatchContinuation
          charts K enlarged core hc hmass hK) =
      (((walk.factors
          (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
          (fun _ => cmp99PhysicalPatchContinuation
            charts K enlarged core hc hmass hK)).take
          (walk.firstActiveDomainIndex domainActive cube hactive)).prod *
        walk.firstActiveFactor domainActive
          (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
          (fun _ => cmp99PhysicalPatchContinuation
            charts K enlarged core hc hmass hK)
          cube hactive) *
        physicalBondProjection
          (CMP99GeneralizedWalk.contourActiveCore
            (fun i : ↥charts => core i) domainActive carrier) *
        ((walk.factors
          (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
          (fun _ => cmp99PhysicalPatchContinuation
            charts K enlarged core hc hmass hK)).drop
          (walk.firstActiveDomainIndex domainActive cube hactive + 1)).prod := by
  have hsplit :=
    walk.term_eq_prefix_mul_firstActiveFactor_mul_suffix domainActive
      (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation
        charts K enlarged core hc hmass hK)
      cube hactive
  have hpivot :=
    cmp99PhysicalPatchWalk_firstActiveFactor_comp_contourActiveCore
      charts K enlarged core hc hmass hK domainActive carrier walk
      cube hactive hcarrier
  rw [hsplit]
  simp only [ContinuousLinearMap.mul_def, ContinuousLinearMap.comp_assoc,
    hpivot]

end

end YangMills.RG
