-- Promotion import:
import YangMills.RG.BalabanCMP89SignedLatticeL1TotalSum


-- SEALED AXIOM SURFACE: intended axiom surface for Step 8b.23/Unit E.16.

#print axioms YangMills.RG.cmp89SignedLatticeL1ExponentialWeight_nonneg
#print axioms YangMills.RG.summable_cmp89SignedLatticeL1ExponentialWeight
#print axioms YangMills.RG.tsum_cmp89SignedLatticeL1ExponentialWeight
#print axioms YangMills.RG.cmp89SignedLatticeResidueAffineMap
#print axioms YangMills.RG.cmp89SignedLatticeResidueAffineMap_injective
#print axioms YangMills.RG.cmp89Eq251LatticeL1Length_intScale
#print axioms YangMills.RG.cmp89SignedLatticeResidueAffineMap_ownerLength_le
#print axioms YangMills.RG.cmp89SignedLatticeL1ExponentialWeight_physicalResidue_le
#print axioms YangMills.RG.summable_cmp89SignedLatticeL1ExponentialWeight_physicalResidue
#print axioms YangMills.RG.tsum_cmp89SignedLatticeL1ExponentialWeight_physicalResidue_le
#print axioms YangMills.RG.exp_physicalResidue_prefactor_le_of_centered
#print axioms YangMills.RG.tsum_cmp89SignedLatticeL1ExponentialWeight_physicalResidue_four_le
#print axioms YangMills.RG.tsum_cmp89SignedLatticeL1ExponentialWeight_residue_le_geometric_pow
