import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothCommutatorFactor

open YangMills.RG

#print axioms cmp99SourceGeneratedSmoothGreenCommutatorNormBound
#print axioms cmp99SourceGeneratedSmoothSectionCMiddleNormBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorMiddle
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorMiddleCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalSmoothSectionCCommutatorMiddle_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalSmoothSectionCCommutatorMiddleCoordinates_le
