import YangMills.RG.BalabanCMP89SourceNeumannPhysicalDerivativeFeedback

/-!
# Axiom audit: literal physical CMP89 Neumann derivative feedback
-/

namespace YangMills.RG

#print axioms cmp89SourceNeumannPhysicalDerivativeFeedbackCoefficient_nonneg
#print axioms cmp89SourceNeumannPhysicalFieldFeedbackCoefficient_nonneg
#print axioms cmp89SourceNeumannPhysicalTwoScaleFeedbackGate_d4_M4_q10_eq
#print axioms cmp89SourceNeumannPhysicalTwoScaleFeedbackGate_d4_M4_q10_lt_one
#print axioms cmp89SourceNeumannPhysicalFieldFeedbackCoefficient_mono
#print axioms cmp89SourceNeumannPhysicalTwoScaleFeedbackGate_lt_one_of_le_d4_M4_q10
#print axioms cmp89SourceNeumannPhysicalTwoScaleFeedbackGate_lt_one_of_radius_bounds_d4_M4
#print axioms exists_pos_cmp89SourceNeumann_twoScale_physical_feedback_radius
#print axioms norm_cmp89SourceNeumannRegionalCovariantD0CLM_oneScaleAverage_sq_le_raw_feedback
#print axioms norm_cmp89SourceNeumannRegionalCovariantD0CLM_oneScaleAverage_sq_le_physical_feedback
#print axioms cmp89SourceNeumann_twoScale_quantitativePoincare_of_physical_feedback

end YangMills.RG
