/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80CutoffRadialResidual
import YangMills.RG.BalabanCMP102Eq80CouplingScaledThirdJet
import YangMills.RG.BalabanCMP116SourcePhysicalContourPotential
import YangMills.RG.BalabanCMP116RadialResidualQuadraticBudget

/-!
# A cutoff-supported CMP102 domain residual in the CMP116 centered energy

The physical cubic Taylor remainder for one literal equation-(80) domain is
available only on the support of the literal CMP116 cutoff.  This file converts
that estimate into the exact quadratic-energy shape consumed by the centered
CMP116 contour theorem.

The only geometric input is the source-faithful inclusion of the selected
domain bond support in the physical interior of `Z0`.  No ambient-volume norm
comparison or coordinate condition number is introduced.

This is a one-domain result.  It does not manufacture the enumeration of
physical source domains by `Fin nY`, identify the domain FTC contribution with
the final `residual` family, or claim equation (1.36).

Oracle target: `[propext, Classical.choice, Quot.sound]`. No placeholders or
local axioms.
-/

open Set
open scoped BigOperators RealInnerProductSpace

namespace YangMills.RG

noncomputable section

/-- If a source localization domain is contained in the physical interior of
`Z0`, the squared norm of its projected physical field is bounded by the
canonical scalar `Z0` energy with constant one. -/
theorem norm_sq_cmp116LocalizationDomainProjection_sourceCoordinate_le_localizedEnergy
    {M N' Nc L lieDim : ℕ}
    [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero (Nc ^ 2 - 1)] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary 4 (M * N') Nc 4 L lieDim)
    (Y : CMP116LocalizationDomain M N')
    (Z0 : Finset (FinBox 4 N'))
    (hYZ0 :
      Y.bondSupport ⊆
        PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
    (b : CMP116Eq214GaussianCoordinate
      (PhysicalBond 4 (M * N')) (Nc ^ 2 - 1)) :
    ‖physicalBondProjection Y.bondSupport
        (cmp116SourcePhysicalCoordinateCochain b)‖ ^ 2 ≤
      ∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0, b ba ^ 2 := by
  classical
  let A := cmp116SourcePhysicalCoordinateCochain b
  have hprojection :
      ‖physicalBondProjection Y.bondSupport A‖ ^ 2 =
        ∑ bond ∈ Y.bondSupport, ‖A bond‖ ^ 2 := by
    rw [PiLp.norm_sq_eq_of_L2]
    calc
      (∑ bond : PhysicalBond 4 (M * N'),
          ‖physicalBondProjection Y.bondSupport A bond‖ ^ 2) =
          ∑ bond : PhysicalBond 4 (M * N'),
            if bond ∈ Y.bondSupport then ‖A bond‖ ^ 2 else 0 := by
              apply Finset.sum_congr rfl
              intro bond _hbond
              by_cases hbondY : bond ∈ Y.bondSupport
              · rw [physicalBondProjection_apply_mem Y.bondSupport hbondY]
                simp [hbondY]
              · rw [physicalBondProjection_apply_not_mem Y.bondSupport hbondY]
                simp [hbondY]
      _ = ∑ bond ∈ Y.bondSupport, ‖A bond‖ ^ 2 := by
        simp
  rw [hprojection]
  calc
    (∑ bond ∈ Y.bondSupport, ‖A bond‖ ^ 2) ≤
        ∑ bond ∈
          PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0,
          ‖A bond‖ ^ 2 := by
      exact Finset.sum_le_sum_of_subset_of_nonneg hYZ0 (by
        intro bond _hbond _hnot
        positivity)
    _ = ∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
          b ba ^ 2 := by
      simpa [A] using
        sum_norm_sq_cmp116SourcePhysicalCoordinateCochain Dict Z0 b

/-- One physical equation-(80) domain supplies the exact centered quadratic
residual shape required downstream.  The rate is explicit:

`residualRate = Λ * (sqrt (4 M^4 |Y|) * threshold) / 3`.

The third-jet hypothesis is required only on the literal source small-field
ball and every radial-segment premise is generated by the cutoff. -/
theorem abs_half_inner_cmp116RadialTaylorResidualOperator_eq80DomainProjection_le_centeredEnergy_of_cutoff
    {M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero (M * (2 * Q))]
    [NeZero Nc] [NeZero (Nc ^ 2 - 1)] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (W : CMP102Eq80SourcePi4PhysicalDomainLabel anchor)
    (hW : W ∈ D)
    (Z0 : Finset (FinBox 4 (2 * Q)))
    (hWZ0 :
      (cmp102Eq80SourcePi4LocalizationDomain
          (M := M) anchor W).bondSupport ⊆
        PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (threshold : ℝ)
    (b : CMP116Eq214GaussianCoordinate
      (PhysicalBond 4 (M * (2 * Q))) (Nc ^ 2 - 1))
    (hthreshold : 0 ≤ threshold)
    (hcutoff :
      (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff
            (cmp102Eq80SourcePi4PhysicalY0 (M := M) anchor D)
            threshold (cmp116SourcePhysicalCoordinateCochain b) *
          cmp116LargeFieldCutoff P threshold
            (cmp116SourcePhysicalCoordinateCochain b) ≠ 0)
    (f : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ)
    (hf : ContDiff ℝ 3 f)
    (Λ : ℝ) (hΛ : 0 ≤ Λ)
    (hthird : ∀ X,
      cmp98SourceFieldSupNorm X ≤ threshold →
        ‖iteratedFDeriv ℝ 3 f X‖ ≤ Λ) :
    let Y := cmp102Eq80SourcePi4LocalizationDomain (M := M) anchor W
    let B := physicalBondProjection Y.bondSupport
      (cmp116SourcePhysicalCoordinateCochain b)
    |(1 / 2 : ℝ) * inner ℝ B
        (cmp116RadialTaylorResidualOperator
          f B (hf.of_le (by norm_num)) B)| ≤
      (Λ *
          (Real.sqrt (((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ) *
            threshold) / 3) / 2 *
        (∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
          b ba ^ 2) := by
  dsimp only
  let Y := cmp102Eq80SourcePi4LocalizationDomain (M := M) anchor W
  let A := cmp116SourcePhysicalCoordinateCochain b
  let B := physicalBondProjection Y.bondSupport A
  let localThreshold :=
    Real.sqrt (((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ) * threshold
  have hcubic :
      |(1 / 2 : ℝ) * inner ℝ B
          (cmp116RadialTaylorResidualOperator
            f B (hf.of_le (by norm_num)) B)| ≤
        (Λ / 6) * ‖B‖ ^ 3 := by
    simpa [Y, A, B] using
      abs_half_inner_cmp116RadialTaylorResidualOperator_eq80DomainProjection_le_of_cutoff
        anchor D W hW P threshold b hthreshold hcutoff f hf Λ hthird
  have hsup :
      cmp98SourceFieldSupNorm B ≤ threshold := by
    simpa [Y, A, B] using
      cmp98SourceFieldSupNorm_eq80DomainProjection_le_threshold_of_cutoffFactor_ne_zero
        anchor D W hW P threshold b hthreshold hcutoff
  have hBnorm : ‖B‖ ≤ localThreshold := by
    simpa [Y, A, B, localThreshold] using
      norm_cmp116LocalizationDomainProjection_le_explicitBlockCard_mul_threshold
        Y A threshold hthreshold hsup
  have hBenergy :
      ‖B‖ ^ 2 ≤
        ∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
          b ba ^ 2 := by
    simpa [Y, A, B] using
      norm_sq_cmp116LocalizationDomainProjection_sourceCoordinate_le_localizedEnergy
        Dict Y Z0 hWZ0 b
  have hquad :
      (Λ / 6) * ‖B‖ ^ 3 ≤
        (Λ / 6) * localThreshold * ‖B‖ ^ 2 :=
    cubic_le_threshold_mul_sq B (div_nonneg hΛ (by norm_num)) hBnorm
  calc
    |(1 / 2 : ℝ) * inner ℝ B
        (cmp116RadialTaylorResidualOperator
          f B (hf.of_le (by norm_num)) B)| ≤
        (Λ / 6) * ‖B‖ ^ 3 := hcubic
    _ ≤ (Λ / 6) * localThreshold * ‖B‖ ^ 2 := hquad
    _ ≤ (Λ / 6) * localThreshold *
          (∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
            b ba ^ 2) := by
      exact mul_le_mul_of_nonneg_left hBenergy
        (mul_nonneg (div_nonneg hΛ (by norm_num)) (by positivity))
    _ = (Λ * localThreshold / 3) / 2 *
          (∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
            b ba ^ 2) := by ring
    _ = (Λ *
          (Real.sqrt (((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ) *
            threshold) / 3) / 2 *
          (∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
            b ba ^ 2) := by rfl

/-- Source-facing coupling specialization.  The third-jet majorant belongs to
the unscaled literal domain potential, while the radial residual is formed
after the physical substitution `B ↦ g_k C B`.  Consequently the centered
rate exposes the exact cubic coupling/constraint factor instead of burying it
in a free constant. -/
theorem abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_centeredEnergy_of_cutoff
    {M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero (M * (2 * Q))]
    [NeZero Nc] [NeZero (Nc ^ 2 - 1)] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (W : CMP102Eq80SourcePi4PhysicalDomainLabel anchor)
    (hW : W ∈ D)
    (Z0 : Finset (FinBox 4 (2 * Q)))
    (hWZ0 :
      (cmp102Eq80SourcePi4LocalizationDomain
          (M := M) anchor W).bondSupport ⊆
        PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (threshold gk : ℝ)
    (b : CMP116Eq214GaussianCoordinate
      (PhysicalBond 4 (M * (2 * Q))) (Nc ^ 2 - 1))
    (hthreshold : 0 ≤ threshold)
    (hcutoff :
      (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff
            (cmp102Eq80SourcePi4PhysicalY0 (M := M) anchor D)
            threshold (cmp116SourcePhysicalCoordinateCochain b) *
          cmp116LargeFieldCutoff P threshold
            (cmp116SourcePhysicalCoordinateCochain b) ≠ 0)
    (f : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ)
    (hf : ContDiff ℝ 3 f)
    (sourceMajorant : ℝ) (hsourceMajorant : 0 ≤ sourceMajorant)
    (hsource : ∀ X,
      cmp98SourceFieldSupNorm X ≤ threshold →
        ‖iteratedFDeriv ℝ 3 f
          (cmp109ConstrainedLinearFluctuation (L := M) gk X)‖ ≤
            sourceMajorant) :
    let Y := cmp102Eq80SourcePi4LocalizationDomain (M := M) anchor W
    let B := physicalBondProjection Y.bondSupport
      (cmp116SourcePhysicalCoordinateCochain b)
    |(1 / 2 : ℝ) * inner ℝ B
        (cmp116RadialTaylorResidualOperator
          (cmp102Eq80CouplingScaledPotential gk f) B
          ((hf.comp
            (cmp109ConstrainedLinearFluctuationCLM
              (M := M) (Q := Q) (Nc := Nc) gk).contDiff).of_le
                (by norm_num)) B)| ≤
      (sourceMajorant * (|gk| * (1 + (M : ℝ) ^ 3)) ^ 3 *
          (Real.sqrt (((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ) *
            threshold) / 3) / 2 *
        (∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
          b ba ^ 2) := by
  dsimp only
  let fscaled :=
    cmp102Eq80CouplingScaledPotential
      (M := M) (Q := Q) (Nc := Nc) gk f
  have hfscaled : ContDiff ℝ 3 fscaled := by
    simpa [fscaled, cmp102Eq80CouplingScaledPotential] using
      hf.comp
        (cmp109ConstrainedLinearFluctuationCLM
          (M := M) (Q := Q) (Nc := Nc) gk).contDiff
  have hthirdScaled : ∀ X,
      cmp98SourceFieldSupNorm X ≤ threshold →
        ‖iteratedFDeriv ℝ 3 fscaled X‖ ≤
          sourceMajorant * (|gk| * (1 + (M : ℝ) ^ 3)) ^ 3 := by
    intro X hX
    simpa [fscaled] using
      norm_iteratedFDeriv_three_cmp102Eq80CouplingScaledPotential_le_of_source
        gk f hf X sourceMajorant (hsource X hX)
  have hscaledMajorant :
      0 ≤ sourceMajorant * (|gk| * (1 + (M : ℝ) ^ 3)) ^ 3 := by
    positivity
  simpa [fscaled, hfscaled] using
    abs_half_inner_cmp116RadialTaylorResidualOperator_eq80DomainProjection_le_centeredEnergy_of_cutoff
      Dict anchor D W hW Z0 hWZ0 P threshold b hthreshold hcutoff
      fscaled hfscaled
      (sourceMajorant * (|gk| * (1 + (M : ℝ) ^ 3)) ^ 3)
      hscaledMajorant hthirdScaled

/-- Printed small-field specialization.  With
`threshold = epsilon1 / gk` and `gk > 0`, the cubic coupling factor cancels
one inverse power from the cutoff radius.  The resulting centered rate carries
the favorable factor `gk^2 * epsilon1` explicitly. -/
theorem abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_centeredEnergy_of_printedCutoff
    {M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero (M * (2 * Q))]
    [NeZero Nc] [NeZero (Nc ^ 2 - 1)] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (W : CMP102Eq80SourcePi4PhysicalDomainLabel anchor)
    (hW : W ∈ D)
    (Z0 : Finset (FinBox 4 (2 * Q)))
    (hWZ0 :
      (cmp102Eq80SourcePi4LocalizationDomain
          (M := M) anchor W).bondSupport ⊆
        PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (epsilon1 gk : ℝ)
    (b : CMP116Eq214GaussianCoordinate
      (PhysicalBond 4 (M * (2 * Q))) (Nc ^ 2 - 1))
    (hepsilon1 : 0 ≤ epsilon1) (hgk : 0 < gk)
    (hcutoff :
      (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff
            (cmp102Eq80SourcePi4PhysicalY0 (M := M) anchor D)
            (epsilon1 / gk) (cmp116SourcePhysicalCoordinateCochain b) *
          cmp116LargeFieldCutoff P (epsilon1 / gk)
            (cmp116SourcePhysicalCoordinateCochain b) ≠ 0)
    (f : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ)
    (hf : ContDiff ℝ 3 f)
    (sourceMajorant : ℝ) (hsourceMajorant : 0 ≤ sourceMajorant)
    (hsource : ∀ X,
      cmp98SourceFieldSupNorm X ≤ epsilon1 / gk →
        ‖iteratedFDeriv ℝ 3 f
          (cmp109ConstrainedLinearFluctuation (L := M) gk X)‖ ≤
            sourceMajorant) :
    let Y := cmp102Eq80SourcePi4LocalizationDomain (M := M) anchor W
    let B := physicalBondProjection Y.bondSupport
      (cmp116SourcePhysicalCoordinateCochain b)
    |(1 / 2 : ℝ) * inner ℝ B
        (cmp116RadialTaylorResidualOperator
          (cmp102Eq80CouplingScaledPotential gk f) B
          ((hf.comp
            (cmp109ConstrainedLinearFluctuationCLM
              (M := M) (Q := Q) (Nc := Nc) gk).contDiff).of_le
                (by norm_num)) B)| ≤
      (sourceMajorant *
          (gk ^ 2 * (1 + (M : ℝ) ^ 3) ^ 3) *
          (Real.sqrt (((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ) *
            epsilon1) / 3) / 2 *
        (∑ ba ∈ cmp116SourcePhysicalLocalizedCoordinates Dict Z0,
          b ba ^ 2) := by
  dsimp only
  have hthreshold : 0 ≤ epsilon1 / gk :=
    div_nonneg hepsilon1 hgk.le
  have hraw :=
    abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_centeredEnergy_of_cutoff
      Dict anchor D W hW Z0 hWZ0 P (epsilon1 / gk) gk b
      hthreshold hcutoff f hf sourceMajorant hsourceMajorant hsource
  rw [abs_of_pos hgk] at hraw
  convert hraw using 1
  field_simp [ne_of_gt hgk]

end

end YangMills.RG
