/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP89Eq251FineLatticePhasePeriodicity
import YangMills.RG.BalabanCMP99SourceFlatQprimeEndpointPhase
import YangMills.RG.BalabanCMP99SourceFlatQprimePhysicalAliasPrecisionMatrix
import YangMills.RG.BalabanCMP99SourceFlatQprimeSignedAliasMomentumDictionary

/-!
# Physical endpoint phase on the signed CMP89 alias carrier

Compiler-verified at exact source checkpoint
`afad237929739252cf850f55f0c273a71bf5a524` by cold GitHub Actions run
`31914703879`.  Restoration and saving of `.lake/build` were skipped.  The
focal completed 8,542 jobs, the audit exited zero, and all five audited
declarations use exactly `[propext, Classical.choice, Quot.sound]`.

The sealed physical momentum dictionary determines the fine amplitude
momentum only up to coordinatewise integer multiples of the exact alias
period `2*pi*M`.  At the physical fine displacement `M^-1 u`, those periods
produce the literal integer phase `2*pi*<w,u>` and therefore disappear after
exponentiation.  This file proves that cancellation and transports the sealed
fine-to-coarse endpoint phase to the signed CMP89 alias momentum.

This is a phase dictionary only.  It does not identify the transposed
solution's row amplitude with the column amplitude in the CMP89 Green
numerator, reindex the finite synthesis through Fourier negation, construct a
Brillouin integral or regional `B0`, attain window 15, discharge a terminal
field, or inhabit `TermSource`.
-/

namespace YangMills.RG

open YangMills

noncomputable section

/-- Integer pairing generated by a vector of full alias periods and one fine
lattice endpoint displacement. -/
def cmp99SourceFlatQprimeEndpointAliasPeriodPairing {d : ℕ}
    (w u : Fin d → ℤ) : ℤ :=
  ∑ mu, w mu * u mu

/-- Adding arbitrary coordinatewise multiples of `2*pi*N` changes the phase
at `N^-1 u` by the explicit integer multiple `2*pi*<w,u>`. -/
theorem cmp89Eq251EntirePhase_add_int_aliasPeriods_physicalFine
    {d N : ℕ} [NeZero N] (z : Fin d → ℂ) (w u : Fin d → ℤ) :
    cmp89Eq251EntirePhase
        (fun mu => z mu + (w mu : ℂ) *
          (((2 * Real.pi * (N : ℝ) : ℝ) : ℂ)))
        (cmp89Eq249PhysicalFineLatticeDisplacement ((N : ℝ)⁻¹) u) =
      cmp89Eq251EntirePhase z
          (cmp89Eq249PhysicalFineLatticeDisplacement ((N : ℝ)⁻¹) u) +
        (((2 * Real.pi : ℝ) : ℂ) *
          (cmp99SourceFlatQprimeEndpointAliasPeriodPairing w u : ℂ)) := by
  unfold cmp89Eq251EntirePhase
    cmp89Eq249PhysicalFineLatticeDisplacement
    cmp99SourceFlatQprimeEndpointAliasPeriodPairing
  simp only [add_mul, Finset.sum_add_distrib]
  congr 1
  push_cast
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro mu _
  have hN : (N : ℂ) ≠ 0 := by
    exact_mod_cast (NeZero.ne N)
  field_simp [hN]

/-- The exponentiated endpoint phase is invariant under every vector of full
physical alias periods. -/
theorem exp_I_cmp89Eq251EntirePhase_add_int_aliasPeriods_physicalFine
    {d N : ℕ} [NeZero N] (z : Fin d → ℂ) (w u : Fin d → ℤ) :
    Complex.exp (Complex.I * cmp89Eq251EntirePhase
        (fun mu => z mu + (w mu : ℂ) *
          (((2 * Real.pi * (N : ℝ) : ℝ) : ℂ)))
        (cmp89Eq249PhysicalFineLatticeDisplacement ((N : ℝ)⁻¹) u)) =
      Complex.exp (Complex.I * cmp89Eq251EntirePhase z
        (cmp89Eq249PhysicalFineLatticeDisplacement ((N : ℝ)⁻¹) u)) := by
  rw [cmp89Eq251EntirePhase_add_int_aliasPeriods_physicalFine,
    mul_add, Complex.exp_add]
  have hcycle :
      Complex.exp (Complex.I * (((2 * Real.pi : ℝ) : ℂ) *
        (cmp99SourceFlatQprimeEndpointAliasPeriodPairing w u : ℂ))) = 1 := by
    rw [show
      Complex.I * (((2 * Real.pi : ℝ) : ℂ) *
          (cmp99SourceFlatQprimeEndpointAliasPeriodPairing w u : ℂ)) =
        ((cmp99SourceFlatQprimeEndpointAliasPeriodPairing w u : ℤ) : ℂ) *
          (2 * (Real.pi : ℂ) * Complex.I) by
      push_cast
      ring]
    exact Complex.exp_int_mul_two_pi_mul_I
      (cmp99SourceFlatQprimeEndpointAliasPeriodPairing w u)
  rw [hcycle, mul_one]

/-- The physical amplitude momentum and its signed CMP89 alias representative
have exactly the same phase on a physical fine-lattice displacement. -/
theorem cmp99SourceFlatQprimeAmplitudeMomentum_endpointPhase_eq_entireAlias
    {d M N' : ℕ} [NeZero M] [NeZero N']
    (ell : FinBox d N')
    (k : CMP99SourceFlatQprimeFixedCoarseFibre d M N' ell)
    (u : Fin d → ℤ) :
    Complex.exp (Complex.I * cmp89Eq251EntirePhase
        (cmp99SourceFlatQprimeAmplitudeMomentum k.1)
        (cmp89Eq249PhysicalFineLatticeDisplacement ((M : ℝ)⁻¹) u)) =
      Complex.exp (Complex.I * cmp89Eq251EntirePhase
        (cmp89Eq248EntireAliasMomentum
          (cmp99SourceFlatQprimeCoarseAmplitudeBaseMomentum ell)
          (cmp99SourceFlatQprimeFixedCoarseSignedAliasIndexEquiv
            d M N' ell k).1)
        (cmp89Eq249PhysicalFineLatticeDisplacement ((M : ℝ)⁻¹) u)) := by
  rcases cmp99SourceFlatQprimeAmplitudeMomentum_eq_alias_add_period ell k with
    ⟨w, hw⟩
  rw [hw]
  exact
    exp_I_cmp89Eq251EntirePhase_add_int_aliasPeriods_physicalFine
      (cmp89Eq248EntireAliasMomentum
        (cmp99SourceFlatQprimeCoarseAmplitudeBaseMomentum ell)
        (cmp99SourceFlatQprimeFixedCoarseSignedAliasIndexEquiv
          d M N' ell k).1) w u

/-- The endpoint quotient of a fine Fourier mode is the literal phase of its
signed CMP89 reciprocal alias.  Both the `M^-1` displacement scale and the
fixed-coarse-fibre proof remain visible. -/
theorem cmp99FlatFourierMode_div_coarseMode_eq_exp_entireAlias_endpoint
    {d M N' : ℕ} [NeZero M] [NeZero N']
    (ell : FinBox d N')
    (k : CMP99SourceFlatQprimeFixedCoarseFibre d M N' ell)
    (x : FinBox d (M * N')) (y : FinBox d N') :
    cmp99FlatFourierMode k.1 x *
        (cmp99FlatFourierMode ell y)⁻¹ =
      Complex.exp (Complex.I * cmp89Eq251EntirePhase
        (cmp89Eq248EntireAliasMomentum
          (cmp99SourceFlatQprimeCoarseAmplitudeBaseMomentum ell)
          (cmp99SourceFlatQprimeFixedCoarseSignedAliasIndexEquiv
            d M N' ell k).1)
        (cmp89Eq249PhysicalFineLatticeDisplacement ((M : ℝ)⁻¹)
          (cmp99SourceFlatQprimeFineToCoarseEndpointDisplacement M x y))) := by
  calc
    cmp99FlatFourierMode k.1 x * (cmp99FlatFourierMode ell y)⁻¹ =
        Complex.exp (Complex.I * cmp89Eq251EntirePhase
          (cmp99SourceFlatQprimeAmplitudeMomentum k.1)
          (cmp89Eq249PhysicalFineLatticeDisplacement ((M : ℝ)⁻¹)
            (cmp99SourceFlatQprimeFineToCoarseEndpointDisplacement
              M x y))) := by
      simpa only [k.property] using
        (cmp99FlatFourierMode_div_coarseMode_eq_exp_amplitudeMomentum_endpoint
          k.1 x y)
    _ = _ :=
      cmp99SourceFlatQprimeAmplitudeMomentum_endpointPhase_eq_entireAlias
        ell k (cmp99SourceFlatQprimeFineToCoarseEndpointDisplacement M x y)

end

end YangMills.RG
