import YangMills.RG.BalabanCMP89SourceNeumannTwoScalePhysicalAbsorption
import YangMills.RG.BalabanCMP99SourceRetainedPhysicalTower

/-!
# Generated two-scale CMP89 Neumann absorption

PRE-VALIDATION: source is present, its `.olean` has not been materialized,
and no declaration below is compiler-verified.

This adapter specializes the two-scale physical absorption theorem to the
literal source lift and the literal first `Ubar` background generated by a
two-step radius chain. The two deviation coefficients are defined from the
source radii and the physical lattice spacings; no independently chosen
coarse background or active region occurs in the public statement.

It remains a depth-two theorem. It does not establish a depth-uniform
Poincare constant, CMP89 (2.42), or window 15.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N] [NeZero Nc]

/-- The literal two-scale source lift has no nonzero field in the joint kernel
once its explicit physical one-step gate contracts. -/
theorem eq_zero_of_cmp89SourceNeumann_generatedTwoScale_physical_absorption
    (hd : 2 ≤ d) (hM : 2 ≤ M)
    (Omega : ActiveGaugeRegion d N)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (chain : CMP99SourceUbarRadiusChain d M Nc 2 epsilon)
    (background :
      PhysicalGaugeBackground d (cmp99RegionalLatticeSize M N 2) Nc)
    (fineSmall : ∀ e : ConcreteEdge d (cmp99RegionalLatticeSize M N 2),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hnext : |(M : ℝ) * spacing| ≤ 1)
    (phi : ActiveGaugeZeroCochain
      (cmp99IteratedLiftActiveRegion (M := M) Omega 2) (SUNLieCoord Nc))
    (hD : cmp89SourceNeumannRegionalCovariantD0CLM
      (cmp99IteratedLiftActiveRegion (M := M) Omega 2)
      (matrixSUNAdjointModel Nc) background spacing phi = 0)
    (hQ :
      let Omega2 := cmp99IteratedLiftActiveRegion (M := M) Omega 2
      let Scale : CMP99SourceNormalizedRegionalScale Omega2 background :=
        CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM Omega2 background
          (cmp99IteratedLiftActiveRegion_blockSaturated Omega 1)
          epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
      cmp99SourceTransportedBlockAverageCLM
          (cmp99ActiveCoarseRegion (M := M) (N' := M * N) Omega2)
          (cmp99SourceWeightedPhysicalTransport (matrixSUNAdjointModel Nc)
            Scale.toSourceScale.data.nextBackground)
          (cmp99SourceTransportedBlockAverageCLM Omega2
            (cmp99SourceWeightedPhysicalTransport (matrixSUNAdjointModel Nc)
              background) phi) = 0)
    (hsmall :
      cmp99OneScaleBlockPoincareConstant d M *
          cmp89SourceNeumannPhysicalOneStepDefectCoefficient d M
            (epsilon / spacing)
            (cmp99SourceUbarNextFineRadius d M epsilon /
              ((M : ℝ) * spacing)) < 1) :
    phi = 0 := by
  let Omega2 := cmp99IteratedLiftActiveRegion (M := M) Omega 2
  let Scale : CMP99SourceNormalizedRegionalScale Omega2 background :=
    CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM Omega2 background
      (cmp99IteratedLiftActiveRegion_blockSaturated Omega 1)
      epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
  let nextBackground := Scale.toSourceScale.data.nextBackground
  have hM0 : (M : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne M)
  have hspacing0 : spacing ≠ 0 := ne_of_gt hspacing
  have hnextSpacing0 : (M : ℝ) * spacing ≠ 0 :=
    mul_ne_zero hM0 hspacing0
  have hOmega2 : Omega2.BlockSaturated := by
    exact cmp99IteratedLiftActiveRegion_blockSaturated Omega 1
  have hOmega1 :
      (cmp99ActiveCoarseRegion (M := M) (N' := M * N) Omega2).BlockSaturated := by
    rw [show cmp99ActiveCoarseRegion (M := M) (N' := M * N) Omega2 =
      cmp99IteratedLiftActiveRegion (M := M) Omega 1 by
        exact cmp99ActiveCoarseRegion_iteratedLift_succ_eq (M := M) Omega 1]
    exact cmp99IteratedLiftActiveRegion_blockSaturated Omega 0
  have nextSmall : ∀ e : ConcreteEdge d (M * N),
      ‖(nextBackground e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤
        cmp99SourceUbarNextFineRadius d M epsilon := by
    intro e
    simpa [nextBackground, Scale,
      CMP99SourceNormalizedRegionalScale.ofFineSmall,
      CMP99SourceRegionalScale.ofFineSmall] using
      norm_cmp99SourceRegionalScaleDataOfFineSmall_nextBackground_sub_one_le
        hd hM Omega2 background (cmp99SourceBlockAverageWeight M d) epsilon
        chain.epsilon_nonneg chain.head_noWinding chain.head_logSmall fineSmall e
  have hfineRadius : spacing * (epsilon / spacing) = epsilon := by
    field_simp
  have hcoarseRadius :
      ((M : ℝ) * spacing) *
          (cmp99SourceUbarNextFineRadius d M epsilon /
            ((M : ℝ) * spacing)) =
        cmp99SourceUbarNextFineRadius d M epsilon := by
    field_simp
  have hfineNonneg : 0 ≤ epsilon / spacing :=
    div_nonneg chain.epsilon_nonneg hspacing.le
  have hcoarseNonneg : 0 ≤
      cmp99SourceUbarNextFineRadius d M epsilon /
        ((M : ℝ) * spacing) := by
    exact div_nonneg chain.tail.epsilon_nonneg
      (mul_nonneg (Nat.cast_nonneg M) hspacing.le)
  apply eq_zero_of_cmp89SourceNeumann_twoScale_physical_absorption
    Omega2 hOmega2 hOmega1 background nextBackground hspacing
    (epsilon / spacing)
    (cmp99SourceUbarNextFineRadius d M epsilon / ((M : ℝ) * spacing))
    hfineNonneg hcoarseNonneg hnext phi hD
  · simpa [Omega2, Scale, nextBackground] using hQ
  · intro e
    simpa [hfineRadius] using fineSmall e
  · intro e
    simpa [hcoarseRadius] using nextSmall (positiveEdgeOfPhysicalBond e)
  · exact hsmall

end

end YangMills.RG
