import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedFlatPhysicalLocalizedFieldB0

#print axioms YangMills.RG.finitePiLp_of_supportedInIdentityOwner_eq_flatComplexFibrePointSource
#print axioms YangMills.RG.norm_cmp99SourceSeparatedGeneratedFlatPhysicalGreenQprimeStar_localizedField_apply_siteEquiv_le_pointSourceB0
