import YangMills.RG.BalabanCMP116Eq226CenteredConditionedPhysicalTermSource

#print axioms YangMills.RG.CMP116Eq226CenteredConditionedPhysicalTermSource.norm_term_le_termWeight
#print axioms YangMills.RG.not_nonempty_cmp116Eq226CenteredConditionedPhysicalTermSource_empty_Z0
