import YangMills.RG.BalabanCMP99ComplexFineHeadTailWordExpansion

#print axioms YangMills.RG.cmp99SourcePi4CoarseFineWalkChoiceActive
#print axioms YangMills.RG.mem_cmp99SourcePi4CoarseFineWalkChoiceActive_iff
#print axioms YangMills.RG.cmp99SourcePi4FineHeadTailActive
#print axioms YangMills.RG.mem_cmp99SourcePi4FineHeadTailActive_iff
#print axioms YangMills.RG.cmp99SourcePi4ComplexBackgroundMinimizerChoiceWordTerm
#print axioms YangMills.RG.cmp99SourcePi4ComplexFineHeadTailWordTerm
#print axioms YangMills.RG.cmp99SourcePi4ComplexBackgroundMinimizerWordTerm_eq_sum_fineWalkChoices
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_eq_tsum_layers_of_source
#print axioms YangMills.RG.cmp99SourcePi4ComplexBackgroundMinimizerChoiceWordTerm_eq_tsum_headWalks_of_source
#print axioms YangMills.RG.cmp99SourcePi4ComplexBackgroundMinimizerWordTerm_eq_sum_tsum_fineWalks_of_source
#print axioms YangMills.RG.cmp99SourcePi4FullComplexBackgroundMinimizerMatrix_eq_literalFineWalkSeries_of_source
