import YangMills.RG.BalabanCMP89Eq246FinePointSourceHolomorphy

/-!
# PRE-VALIDATION: audit of CMP89 (2.46) fine-point holomorphy and inverse transform

Source is present, its `.olean` has not yet been materialized, and the result
has not yet been verified by the compiler.
-/

#print axioms YangMills.RG.differentiable_cmp89Eq246FinePointSourceAliasVector_component
#print axioms YangMills.RG.differentiableAt_cmp89Eq246StabilizedAliasNoncentralPointSourceMoment
#print axioms YangMills.RG.cmp89Eq246StabilizedFinePointSourceSolutionMoment
#print axioms YangMills.RG.differentiableAt_cmp89Eq246StabilizedFinePointSourceSolutionMoment
#print axioms YangMills.RG.differentiableAt_cmp89Eq246StabilizedFinePointSourceSolution_component
#print axioms YangMills.RG.differentiableAt_cmp89Eq246StabilizedFineToFineGreenIntegrand
#print axioms YangMills.RG.differentiableAt_cmp89Eq246StabilizedFineToFineGreenIntegrand_of_commonRadius
#print axioms YangMills.RG.integrable_cmp89Eq246PhysicalFineToFineGreenIntegrand_real
#print axioms YangMills.RG.integral_cmp89Eq246FinePointSourceFibreEquation_of_commonRadius
#print axioms YangMills.RG.cmp89Eq246NormalizedPhysicalFineToFineGreen
#print axioms YangMills.RG.cmp89Eq246NormalizedPhysicalFineToFineGreen_eq
