import YangMills.RG.BalabanCMP102Eq80SourcePi4CarrierAnchoredLocalizationBound

#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredTerminalDomainLayer_eq_zero_of_not_mem_core
#print axioms YangMills.RG.sum_cmp102Eq80SourcePi4CarrierAnchoredTerminalDomainLayer
#print axioms YangMills.RG.norm_cmp102Eq80SourcePi4CarrierAnchoredTerminalDomainLayer_le
#print axioms YangMills.RG.norm_cmp102Eq80SourcePi4CarrierAnchoredDomainLayerCoefficient_le
