/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceRetainedPhysicalTower
import YangMills.RG.BalabanCMP99SourceStratumTowerCovariance
import YangMills.RG.BalabanCMP99SourceMassWeights

/-!
# The CMP99 stratified mass from one retained physical `Ubar` tower

This adapter removes the remaining possibility of supplying unrelated
operators `Q'_r` to the mass in CMP99 (3.24).  Every scale operator is the
corresponding prefix retained from one recursively generated physical tower.
The only dictionary is an isometric identification of its terminal carrier
with the source lattice on which `Lambda_r` lives.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped BigOperators Matrix.Norms.L2Operator RealInnerProductSpace

noncomputable section

universe u v

variable {d M N Nc depth : ℕ}
variable [NeZero d] [NeZero M] [NeZero N] [NeZero Nc]
variable {rho : SUNAdjointModel Nc}
variable {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
variable {background : GaugeConfig d N (SUN Nc)}

/-- Isometric source-lattice dictionaries for all prefixes of one retained
physical tower.  The operators themselves are not fields of this object. -/
structure CMP99SourceRetainedPhysicalScaleIdentification
    {FineSite : Type u} [DecidableEq FineSite]
    {ScaleSite : Fin (depth + 1) → Type v}
    [∀ r, DecidableEq (ScaleSite r)] [∀ r, Fintype (ScaleSite r)]
    (T : CMP99SourceRetainedPhysicalTower rho Omega M spacing background depth)
    (S : CMP99SourceScaledStratification FineSite (depth + 1) ScaleSite) where
  levelEquiv : ∀ r : Fin (depth + 1),
    (T.towerAt r).TerminalSpace.carrier ≃ₗᵢ[ℝ]
      CMP99SourceScaledStratification.ScaleField
        (ScaleSite := ScaleSite) (SUNLieCoord Nc) r

namespace CMP99SourceRetainedPhysicalScaleIdentification

variable {FineSite : Type u} [DecidableEq FineSite]
variable {ScaleSite : Fin (depth + 1) → Type v}
variable [∀ r, DecidableEq (ScaleSite r)] [∀ r, Fintype (ScaleSite r)]
variable {T : CMP99SourceRetainedPhysicalTower
  rho Omega M spacing background depth}
variable {S : CMP99SourceScaledStratification
  FineSite (depth + 1) ScaleSite}

/-- The literal order-`r` average from the retained physical `Ubar` chain. -/
noncomputable def Qprime
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      CMP99SourceScaledStratification.ScaleField
        (ScaleSite := ScaleSite) (SUNLieCoord Nc) r :=
  (I.levelEquiv r).toContinuousLinearMap.comp (T.towerAt r).Qprime

/-- The complete precision in CMP99 (3.23)--(3.24), with every mass average
generated by the same physical background chain. -/
noncomputable def gaugePrecision
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  cmp99SourceScaledGaugePrecision S covariantLaplacian I.Qprime d a L eta

/-- The physical retained precision inherits coercivity from its covariant
Laplacian; all printed mass weights are nonnegative. -/
theorem gaugePrecision_isCoercive
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    IsCoerciveCLM (I.gaugePrecision covariantLaplacian a L eta) c := by
  exact isCoerciveCLM_cmp99SourceStratifiedGaugePrecision
    (fun r => CMP99SourceScaledStratification.ScaleField
      (ScaleSite := ScaleSite) (SUNLieCoord Nc) r)
    (fun r => S.StratumField (SUNLieCoord Nc) r)
    covariantLaplacian I.Qprime (fun r => S.restrictStratumCLM r)
    (fun r => le_of_lt
      (cmp99SourceCountingStratumWeight_pos d ha hL heta r)) hDelta

/-- Symmetry of the complete retained precision. -/
theorem gaugePrecision_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) (hDelta : covariantLaplacian.IsSymmetric) :
    (I.gaugePrecision covariantLaplacian a L eta).IsSymmetric := by
  exact cmp99SourceStratifiedGaugePrecision_isSymmetric
    (fun r => CMP99SourceScaledStratification.ScaleField
      (ScaleSite := ScaleSite) (SUNLieCoord Nc) r)
    (fun r => S.StratumField (SUNLieCoord Nc) r)
    covariantLaplacian I.Qprime (fun r => S.restrictStratumCLM r)
    (cmp99SourceCountingStratumWeight d a L eta) hDelta

/-- Green operator generated from the complete retained precision. -/
noncomputable def green
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  covarianceOfIsCoerciveCLM
    (I.gaugePrecision covariantLaplacian a L eta) hc
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)

/-- Exact right Green identity. -/
theorem gaugePrecision_comp_green
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    (I.gaugePrecision covariantLaplacian a L eta).comp
        (I.green covariantLaplacian ha hL heta hc hDelta) =
      ContinuousLinearMap.id ℝ
        (ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) := by
  exact precision_comp_covarianceOfIsCoerciveCLM _ hc _

/-- Exact left Green identity. -/
theorem green_comp_gaugePrecision
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    (I.green covariantLaplacian ha hL heta hc hDelta).comp
        (I.gaugePrecision covariantLaplacian a L eta) =
      ContinuousLinearMap.id ℝ
        (ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) := by
  exact covarianceOfIsCoerciveCLM_comp_precision _ hc _

/-- Symmetry of the generated full Green. -/
theorem green_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric) :
    (I.green covariantLaplacian ha hL heta hc hDelta).IsSymmetric := by
  exact covarianceOfIsCoerciveCLM_isSymmetric _ hc
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)

/-- The actual source average restricted to `Lambda_r`. -/
noncomputable def stratumAverage
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  (T.towerAt r).stratumAverage S r (I.levelEquiv r)

/-- Its exact source-weighted adjoint. -/
noncomputable def stratumWeightedAdjoint
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  (T.towerAt r).stratumWeightedAdjoint S r (I.levelEquiv r)

/-- Coisometry of every physically retained restricted average. -/
theorem stratumAverage_comp_stratumWeightedAdjoint
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    (I.stratumAverage r).comp (I.stratumWeightedAdjoint r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) :=
  (T.towerAt r).stratumAverage_comp_stratumWeightedAdjoint
    S r (I.levelEquiv r)

/-- The exact terminal spacing of the retained prefix is positive, derived
from the physical scale and the initial spacing. -/
theorem towerAt_terminalSpacing_pos
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing) :
    0 < (T.towerAt r).terminalSpacing := by
  rw [T.towerAt_terminalSpacing]
  exact mul_pos (pow_pos hM r.val) hspacing

/-- The middle operator `Q'_r (G')^2 (Q'_r)^dagger` on the literal stratum. -/
noncomputable def stratumCoarseCovarianceMiddle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  (T.towerAt r).stratumCoarseCovarianceMiddle S r (I.levelEquiv r)
    (I.green covariantLaplacian ha hL heta hc hDelta)

/-- B5 for one source stratum: a uniform upper bound on the complete
precision yields the printed lower bound on the generated middle operator.
No adjoint lower bound, surjectivity, or terminal-spacing premise is free. -/
theorem isCoerciveCLM_stratumCoarseCovarianceMiddle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    IsCoerciveCLM
      (I.stratumCoarseCovarianceMiddle covariantLaplacian
        ha hL heta hc hDelta r) (Lambda ^ 2)⁻¹ := by
  exact (T.towerAt r).isCoerciveCLM_stratumCoarseCovarianceMiddle
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- The generated printed covariance on the physical stratum. -/
noncomputable def stratumCoarseCovariance
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  (T.towerAt r).stratumCoarseCovariance S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- Exact left inverse equation for the generated physical stratum
covariance. -/
theorem stratumCoarseCovariance_comp_middle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM hspacing
      hLambdaPos hDelta hDeltaSymm hLambda r).comp
        (I.stratumCoarseCovarianceMiddle covariantLaplacian
          ha hL heta hc hDelta r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) := by
  exact (T.towerAt r).stratumCoarseCovariance_comp_middle
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- Exact right inverse equation for the generated physical stratum
covariance. -/
theorem stratumCoarseCovariance_middle_comp
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovarianceMiddle covariantLaplacian
      ha hL heta hc hDelta r).comp
        (I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM
          hspacing hLambdaPos hDelta hDeltaSymm hLambda r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) := by
  exact (T.towerAt r).stratumCoarseCovariance_middle_comp
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- Symmetry of the generated physical stratum covariance. -/
theorem stratumCoarseCovariance_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM hspacing
      hLambdaPos hDelta hDeltaSymm hLambda r).IsSymmetric := by
  exact (T.towerAt r).stratumCoarseCovariance_isSymmetric
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

@[simp] theorem Qprime_apply
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    I.Qprime r phi = I.levelEquiv r ((T.towerAt r).Qprime phi) := rfl

end CMP99SourceRetainedPhysicalScaleIdentification

end

end YangMills.RG
