import YangMills.RG.BalabanCMP116SourcePi4FullComplexR1PhysicalTraceMultiplier

#print axioms YangMills.RG.cmp116SourcePi4PhysicalComplexR1TraceMultiplierBound
#print axioms YangMills.RG.cmp116SourcePi4FullComplexR1TraceMultiplierBudget_le_physical
