import YangMills.RG.BalabanCMP99Eq335PhysicalRegularityClassLocalizedRetainedTower


#print axioms YangMills.RG.CMP99Eq335PhysicalRegularityClass.localizedRetainedTowerOfSourceRegion
#print axioms YangMills.RG.CMP99Eq335PhysicalRegularityClass.localizedRetainedTerminalQprime_eq_ofSourceRegion
