import YangMills.RG.BalabanCMP99SourceGeneratedTerminalRepresentativeDistance

open YangMills.RG

#print axioms cmp99GeneratedTerminalBlockBasepoint_zero
#print axioms blockBasepoint_cmp99GeneratedTerminalBlockBasepoint
#print axioms cmp99GeneratedTerminalBlockBasepoint_cast_eq_blockBasepoint
#print axioms finBoxDist_cmp99GeneratedTerminalBlockBasepoint_eq_mul
#print axioms CMP99SourceActiveRegionChain.terminalRepresentative_cast_val
#print axioms CMP99SourceActiveRegionChain.terminalRepresentative_congr_val
#print axioms cast_cancel_of_opposite_equalities
#print axioms cmp99SourceIteratedLift_terminalRepresentative_eq_basepoint
#print axioms cmp99SourceIteratedLift_terminalRepresentative_finBoxDist
#print axioms cmp99SourceIteratedLiftPhysicalTerminalDist
#print axioms cmp99SourceIteratedLiftPhysicalTerminalDist_le_representative
