/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80PhysicalDomainFTCThirdFieldSourceMetricBound
import YangMills.RG.BalabanCMP102Eq80CutoffRadialResidual
import YangMills.RG.BalabanCMP102Eq80CouplingScaledThirdJet
import YangMills.RG.BalabanCMP116DomainCardinalityAbsorption
import YangMills.RG.BalabanCMP116Eq136To220

/-!
# Match the physical cubic residual to equation (1.36)

The literal equation-(80) third jet already carries independent exponential
decay in the domain cardinality and tree metric.  The cutoff conversion from
the source sup norm to the physical `L²` norm costs the cube of the square
root of the domain cardinality.  This file absorbs that polynomial cost into
the cardinality exponential and matches the untouched tree-metric exponential
with the rate printed in equation (1.36).

The remaining hypothesis is a scalar, domain-independent producer budget.  It
does not assume equation (1.36) pointwise, and it contains neither a residual
nor a localization domain.

This is the residual branch leading to equations (1.36) and (2.20), not the
quadratic-kernel branch leading from equation (1.43) to equation (2.19).

Oracle target: `[propext, Classical.choice, Quot.sound]`. No placeholders or
local axioms.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

private abbrev Eq136CoarseField (Q Nc : ℕ) [NeZero (2 * Q)] :=
  CoarsePhysicalOneCochain 4 (2 * Q) Nc

/-- Tree-metric rate printed in equation (1.36). -/
def cmp102Eq80Eq136ResidualMetricRate (delta kappa : ℝ) : ℝ :=
  (1 - 2 * delta) * kappa

/-- Producer-only prefactor of the physical third-jet source-metric
majorant, after removing both localization-domain exponentials. -/
noncomputable def cmp102Eq80Eq136ThirdJetProducerPrefactor
    {M Q Nc n : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (baseCoarseCovariance :
      Eq136CoarseField Q Nc →L[ℝ] Eq136CoarseField Q Nc)
    (sourceJetBound κcard delta kappa summationRatio : ℝ)
    (layerWord : Fin n → ℕ)
    (Δ : ℕ) : ℝ :=
  sourceJetBound *
    ContinuousLinearMap.opNorm (𝕜 := ℝ)
      (cmp99PhysicalRectangularOfComplexMatrixContinuousLinearMap
        (d := 4) (N₁ := 2 * Q) (N₂ := M * (2 * Q)) (Nc := Nc)) *
    ((cmp99SourcePi4Charts :
      Finset (CMP99SourcePi4Chart Unit Q)).card : ℝ) *
    cmp102Eq80PhysicalFineHeadTailEndpointMajorant
      (M := M) baseCoarseCovariance *
    Real.exp (κcard * 10000) *
    Real.exp
      (cmp102Eq80Eq136ResidualMetricRate delta kappa * 10000) *
    summationRatio ^ (1 + ∑ i : Fin n, (layerWord i + 1)) *
    (1 -
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
        summationRatio)⁻¹

/-- Uniform scalar comparison left after the cubic cutoff cost has been
absorbed.  The factor `16 M⁶ / κcard²` is generated by the proved
domain-cardinality absorption theorem; the factor `1/6` is the exact radial
Taylor constant. -/
def CMP102Eq80Eq136ThirdJetProducerBudget
    {M Q Nc n : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (baseCoarseCovariance :
      Eq136CoarseField Q Nc →L[ℝ] Eq136CoarseField Q Nc)
    (sourceJetBound κcard delta kappa summationRatio : ℝ)
    (layerWord : Fin n → ℕ) (Δ q : ℕ)
    (E0 C1 C2 kappa1 : ℝ) : Prop :=
  cmp102Eq80Eq136ThirdJetProducerPrefactor
      (M := M) baseCoarseCovariance sourceJetBound κcard
      delta kappa summationRatio layerWord Δ *
      (1 + (M : ℝ) ^ 3) ^ 3 *
      (16 * (M : ℝ) ^ 6 / κcard ^ 2) / 6 ≤
    E0 * C1 * (M : ℝ) ^ q * Real.exp (C2 * kappa1)

/-- The physical source-metric third-jet majorant, the exact cubic cutoff
cost, and the uniform cardinality absorption together satisfy the printed
equation-(1.36) majorant.

The small-field assumption `epsilon1 ≤ 1` is used only in the favorable
direction `epsilon1³ ≤ epsilon1`. -/
theorem
    cmp102Eq80PhysicalDomainFTCThirdFieldCubicCutoffMajorant_le_eq136
    {M Q Nc n : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (baseCoarseCovariance :
      Eq136CoarseField Q Nc →L[ℝ] Eq136CoarseField Q Nc)
    (sourceJetBound κcard delta kappa summationRatio : ℝ)
    (layerWord : Fin n → ℕ)
    (Y : CMP116LocalizationDomain M (2 * Q))
    (Δ q : ℕ) (E0 epsilon1 C1 C2 kappa1 : ℝ)
    (hsourceJetBound : 0 ≤ sourceJetBound)
    (hκcard : 0 < κcard)
    (hsummation : 0 ≤ summationRatio)
    (hsmall :
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
        summationRatio < 1)
    (hepsilon1 : 0 ≤ epsilon1)
    (hepsilon1_one : epsilon1 ≤ 1)
    (hbudget : CMP102Eq80Eq136ThirdJetProducerBudget
      (M := M) baseCoarseCovariance sourceJetBound κcard
      delta kappa summationRatio layerWord Δ q E0 C1 C2 kappa1) :
    cmp102Eq80PhysicalDomainFTCThirdFieldSourceMetricMajorant
        baseCoarseCovariance sourceJetBound κcard
        (cmp102Eq80Eq136ResidualMetricRate delta kappa)
        summationRatio layerWord Y Δ *
        (1 + (M : ℝ) ^ 3) ^ 3 *
        Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
        epsilon1 ^ 3 / 6 ≤
      cmp116Eq136ResidualMajorant E0 epsilon1 C1 M q
        C2 kappa1 delta kappa
          (cmp116CubeEdgeTreeMetric Y : ℝ) := by
  let producer :=
    cmp102Eq80Eq136ThirdJetProducerPrefactor
      (M := M) baseCoarseCovariance sourceJetBound κcard
      delta kappa summationRatio layerWord Δ
  let metricDecay :=
    Real.exp (-(cmp102Eq80Eq136ResidualMetricRate delta kappa *
      (cmp116CubeEdgeTreeMetric Y : ℝ)))
  have hinv :
      0 ≤ (1 -
        ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
          summationRatio)⁻¹ :=
    inv_nonneg.mpr (sub_nonneg.mpr hsmall.le)
  have hopNorm :
      0 ≤ ContinuousLinearMap.opNorm (𝕜 := ℝ)
        (cmp99PhysicalRectangularOfComplexMatrixContinuousLinearMap
          (d := 4) (N₁ := 2 * Q) (N₂ := M * (2 * Q)) (Nc := Nc)) :=
    ContinuousLinearMap.opNorm_nonneg _
  have hchartCard :
      0 ≤ (((cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q)).card : ℕ) : ℝ) :=
    Nat.cast_nonneg _
  have hendpoint :
      0 ≤ cmp102Eq80PhysicalFineHeadTailEndpointMajorant
        (M := M) baseCoarseCovariance := by
    unfold cmp102Eq80PhysicalFineHeadTailEndpointMajorant
    exact mul_nonneg (norm_nonneg _) (norm_nonneg _)
  have hratioPow :
      0 ≤ summationRatio ^
        (1 + ∑ i : Fin n, (layerWord i + 1)) :=
    pow_nonneg hsummation _
  have hproducer : 0 ≤ producer := by
    dsimp [producer, cmp102Eq80Eq136ThirdJetProducerPrefactor]
    exact mul_nonneg
      (mul_nonneg
        (mul_nonneg
          (mul_nonneg
            (mul_nonneg
              (mul_nonneg
                (mul_nonneg hsourceJetBound hopNorm)
                  hchartCard)
                hendpoint)
              (Real.exp_nonneg _))
            (Real.exp_nonneg _))
          hratioPow)
        hinv
  have hbudget' :
      producer *
          (1 + (M : ℝ) ^ 3) ^ 3 *
          (16 * (M : ℝ) ^ 6 / κcard ^ 2) / 6 ≤
        E0 * C1 * (M : ℝ) ^ q * Real.exp (C2 * kappa1) := by
    simpa [producer] using hbudget
  have hmetricDecay : 0 ≤ metricDecay := Real.exp_nonneg _
  have habsorb :=
    sqrt_explicitBlockCard_pow_three_mul_exp_neg_le
      M Y.blocks.card hκcard
  have hepsilonCube : epsilon1 ^ 3 ≤ epsilon1 := by
    have hsq_gap :
        0 ≤ epsilon1 ^ 2 * (1 - epsilon1) :=
      mul_nonneg (sq_nonneg epsilon1) (sub_nonneg.mpr hepsilon1_one)
    have hlinear_gap :
        0 ≤ epsilon1 * (1 - epsilon1) :=
      mul_nonneg hepsilon1 (sub_nonneg.mpr hepsilon1_one)
    nlinarith
  have hsourceFactor :
      cmp102Eq80PhysicalDomainFTCThirdFieldSourceMetricMajorant
          baseCoarseCovariance sourceJetBound κcard
          (cmp102Eq80Eq136ResidualMetricRate delta kappa)
          summationRatio layerWord Y Δ =
        producer *
          Real.exp (-(κcard * (Y.blocks.card : ℝ))) *
          metricDecay := by
    dsimp [producer, metricDecay]
    unfold
      cmp102Eq80PhysicalDomainFTCThirdFieldSourceMetricMajorant
      cmp102Eq80PhysicalFineHeadTailSourceMetricDecayPrefactor
      cmp102Eq80Eq136ThirdJetProducerPrefactor
    ring
  rw [hsourceFactor]
  calc
    producer * Real.exp (-(κcard * (Y.blocks.card : ℝ))) *
          metricDecay *
          (1 + (M : ℝ) ^ 3) ^ 3 *
          Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
          epsilon1 ^ 3 / 6 =
        (producer * (1 + (M : ℝ) ^ 3) ^ 3 *
          epsilon1 ^ 3 / 6) *
          (Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
            Real.exp (-(κcard * (Y.blocks.card : ℝ)))) *
          metricDecay := by ring
    _ ≤
        (producer * (1 + (M : ℝ) ^ 3) ^ 3 *
          epsilon1 ^ 3 / 6) *
          (16 * (M : ℝ) ^ 6 / κcard ^ 2) *
          metricDecay := by
      apply mul_le_mul_of_nonneg_right _ hmetricDecay
      apply mul_le_mul_of_nonneg_left habsorb
      positivity
    _ =
        (producer * (1 + (M : ℝ) ^ 3) ^ 3 *
          (16 * (M : ℝ) ^ 6 / κcard ^ 2) / 6) *
          epsilon1 ^ 3 * metricDecay := by ring
    _ ≤
        (producer * (1 + (M : ℝ) ^ 3) ^ 3 *
          (16 * (M : ℝ) ^ 6 / κcard ^ 2) / 6) *
          epsilon1 * metricDecay := by
      apply mul_le_mul_of_nonneg_right _ hmetricDecay
      apply mul_le_mul_of_nonneg_left hepsilonCube
      positivity
    _ ≤
        (E0 * C1 * (M : ℝ) ^ q * Real.exp (C2 * kappa1)) *
          epsilon1 * metricDecay := by
      simpa only [mul_assoc] using
        (mul_le_mul_of_nonneg_right hbudget'
          (mul_nonneg hepsilon1 hmetricDecay))
    _ =
      cmp116Eq136ResidualMajorant E0 epsilon1 C1 M q
        C2 kappa1 delta kappa
          (cmp116CubeEdgeTreeMetric Y : ℝ) := by
      unfold cmp116Eq136ResidualMajorant
      dsimp [metricDecay, cmp102Eq80Eq136ResidualMetricRate]
      ring

/-- The source small-field third jet and the scalar equation-(1.36)
comparison control the literal radial Taylor residual after the physical
substitution `B ↦ g_k C B`.

The proof uses the cutoff to bound the complete radial segment, and the
factor `g_k³` from the third derivative cancels the cube of the printed
cutoff radius `epsilon1 / gk` exactly. -/
theorem
    abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_eq136_of_source
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (M * (2 * Q))]
    [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (W : CMP102Eq80SourcePi4PhysicalDomainLabel anchor)
    (hW : W ∈ D)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (epsilon1 gk : ℝ)
    (b : CMP116Eq214GaussianCoordinate
      (PhysicalBond 4 (M * (2 * Q))) (Nc ^ 2 - 1))
    (hepsilon1 : 0 ≤ epsilon1) (hgk : 0 < gk)
    (hcutoff :
      (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff
            (cmp102Eq80SourcePi4PhysicalY0 (M := M) anchor D)
            (epsilon1 / gk) (cmp116SourcePhysicalCoordinateCochain b) *
          cmp116LargeFieldCutoff P (epsilon1 / gk)
            (cmp116SourcePhysicalCoordinateCochain b) ≠ 0)
    (f : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ)
    (hf : ContDiff ℝ 3 f)
    (sourceMajorant : ℝ) (hsourceMajorant : 0 ≤ sourceMajorant)
    (hsource : ∀ X,
      cmp98SourceFieldSupNorm X ≤ epsilon1 / gk →
        ‖iteratedFDeriv ℝ 3 f
          (cmp109ConstrainedLinearFluctuation (L := M) gk X)‖ ≤
            sourceMajorant)
    (E0 C1 : ℝ) (q : ℕ) (C2 kappa1 delta kappa : ℝ)
    (hprinted :
      sourceMajorant * (1 + (M : ℝ) ^ 3) ^ 3 *
          Real.sqrt
            ((((M ^ 4 *
              (cmp102Eq80SourcePi4LocalizationDomain
                (M := M) anchor W).blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
          epsilon1 ^ 3 / 6 ≤
        cmp116Eq136ResidualMajorant E0 epsilon1 C1 M q
          C2 kappa1 delta kappa
            (cmp116CubeEdgeTreeMetric
              (cmp102Eq80SourcePi4LocalizationDomain
                (M := M) anchor W) : ℝ)) :
    let Y := cmp102Eq80SourcePi4LocalizationDomain (M := M) anchor W
    let B := physicalBondProjection Y.bondSupport
      (cmp116SourcePhysicalCoordinateCochain b)
    |(1 / 2 : ℝ) * inner ℝ B
        (cmp116RadialTaylorResidualOperator
          (cmp102Eq80CouplingScaledPotential gk f) B
          ((hf.comp
            (cmp109ConstrainedLinearFluctuationCLM
              (M := M) (Q := Q) (Nc := Nc) gk).contDiff).of_le
                (by norm_num)) B)| ≤
      cmp116Eq136ResidualMajorant E0 epsilon1 C1 M q
        C2 kappa1 delta kappa
          (cmp116CubeEdgeTreeMetric Y : ℝ) := by
  dsimp only
  let Y := cmp102Eq80SourcePi4LocalizationDomain (M := M) anchor W
  let A := cmp116SourcePhysicalCoordinateCochain b
  let B := physicalBondProjection Y.bondSupport A
  let constraintCost := 1 + (M : ℝ) ^ 3
  let localThreshold :=
    Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) *
      (epsilon1 / gk)
  let fscaled :=
    cmp102Eq80CouplingScaledPotential
      (M := M) (Q := Q) (Nc := Nc) gk f
  have hthreshold : 0 ≤ epsilon1 / gk :=
    div_nonneg hepsilon1 hgk.le
  have hfscaled : ContDiff ℝ 3 fscaled := by
    simpa [fscaled, cmp102Eq80CouplingScaledPotential] using
      hf.comp
        (cmp109ConstrainedLinearFluctuationCLM
          (M := M) (Q := Q) (Nc := Nc) gk).contDiff
  have hthirdScaled : ∀ X,
      cmp98SourceFieldSupNorm X ≤ epsilon1 / gk →
        ‖iteratedFDeriv ℝ 3 fscaled X‖ ≤
          sourceMajorant * (|gk| * constraintCost) ^ 3 := by
    intro X hX
    simpa [fscaled, constraintCost] using
      norm_iteratedFDeriv_three_cmp102Eq80CouplingScaledPotential_le_of_source
        gk f hf X sourceMajorant (hsource X hX)
  have hscaledMajorant :
      0 ≤ sourceMajorant * (|gk| * constraintCost) ^ 3 :=
    mul_nonneg hsourceMajorant (pow_nonneg (mul_nonneg (abs_nonneg _) (by
      dsimp [constraintCost]
      positivity)) _)
  have hcubic :
      |(1 / 2 : ℝ) * inner ℝ B
          (cmp116RadialTaylorResidualOperator
            fscaled B (hfscaled.of_le (by norm_num)) B)| ≤
        (sourceMajorant * (|gk| * constraintCost) ^ 3 / 6) *
          ‖B‖ ^ 3 := by
    simpa [Y, A, B, fscaled] using
      abs_half_inner_cmp116RadialTaylorResidualOperator_eq80DomainProjection_le_of_cutoff
        anchor D W hW P (epsilon1 / gk) b hthreshold hcutoff
        fscaled hfscaled
        (sourceMajorant * (|gk| * constraintCost) ^ 3)
        hthirdScaled
  have hsup :
      cmp98SourceFieldSupNorm B ≤ epsilon1 / gk := by
    simpa [Y, A, B] using
      cmp98SourceFieldSupNorm_eq80DomainProjection_le_threshold_of_cutoffFactor_ne_zero
        anchor D W hW P (epsilon1 / gk) b hthreshold hcutoff
  have hBnorm : ‖B‖ ≤ localThreshold := by
    simpa [Y, A, B, localThreshold] using
      norm_cmp116LocalizationDomainProjection_le_explicitBlockCard_mul_threshold
        Y A (epsilon1 / gk) hthreshold hsup
  have hBcube : ‖B‖ ^ 3 ≤ localThreshold ^ 3 :=
    pow_le_pow_left₀ (norm_nonneg _) hBnorm 3
  calc
    |(1 / 2 : ℝ) * inner ℝ B
        (cmp116RadialTaylorResidualOperator
          (cmp102Eq80CouplingScaledPotential gk f) B
          ((hf.comp
            (cmp109ConstrainedLinearFluctuationCLM
              (M := M) (Q := Q) (Nc := Nc) gk).contDiff).of_le
                (by norm_num)) B)|
        ≤ (sourceMajorant * (|gk| * constraintCost) ^ 3 / 6) *
            ‖B‖ ^ 3 := by
          simpa [fscaled, hfscaled] using hcubic
    _ ≤ (sourceMajorant * (|gk| * constraintCost) ^ 3 / 6) *
          localThreshold ^ 3 :=
      mul_le_mul_of_nonneg_left hBcube
        (div_nonneg hscaledMajorant (by norm_num))
    _ =
        sourceMajorant * constraintCost ^ 3 *
          Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
          epsilon1 ^ 3 / 6 := by
      rw [show localThreshold =
        Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) *
          (epsilon1 / gk) by rfl]
      calc
        (sourceMajorant * (|gk| * constraintCost) ^ 3 / 6) *
              (Real.sqrt ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) *
                (epsilon1 / gk)) ^ 3 =
            sourceMajorant / 6 *
              Real.sqrt
                ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
              ((|gk| * constraintCost) ^ 3 *
                (epsilon1 / gk) ^ 3) := by ring
        _ =
            sourceMajorant / 6 *
              Real.sqrt
                ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
              (constraintCost ^ 3 * epsilon1 ^ 3) := by
          rw [coupling_cube_mul_threshold_cube
            gk epsilon1 constraintCost hgk]
        _ =
            sourceMajorant * constraintCost ^ 3 *
              Real.sqrt
                ((((M ^ 4 * Y.blocks.card) * 4 : ℕ) : ℝ)) ^ 3 *
              epsilon1 ^ 3 / 6 := by ring
    _ ≤
        cmp116Eq136ResidualMajorant E0 epsilon1 C1 M q
          C2 kappa1 delta kappa
            (cmp116CubeEdgeTreeMetric Y : ℝ) := by
      simpa [Y, constraintCost] using hprinted

end

end YangMills.RG
