import YangMills.RG.BalabanCMP99SourceEq395GlobalRegionalMiddleAmbientBridge

#print axioms YangMills.RG.extendZero_comp_nestedActiveRegionExtension
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectOnSource_eq_transport
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectOnSource_eq_directTransport
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectOnSource_eq_physicalDifference
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefect_adjoint_ambient
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalPi4Projector_comp_smoothMultiplier
