import YangMills.RG.BalabanCMP99ActiveGaugeRegionReindex


#print axioms YangMills.RG.finitePiLpTypedKernelReindex_symm_reindex
#print axioms YangMills.RG.cmp99ActiveGaugeRegionReindex
#print axioms YangMills.RG.mem_cmp99ActiveGaugeRegionReindex_iff
#print axioms YangMills.RG.cmp99ActiveGaugeRegionSiteReindexEquiv
#print axioms YangMills.RG.cmp99ActiveGaugeRegionReindex_symm_reindex_eq
#print axioms YangMills.RG.cmp99GaugeZeroCochainReindex_extendZero
#print axioms YangMills.RG.cmp99ActiveGaugeZeroCochainReindex_restrictZero
#print axioms YangMills.RG.cmp99GaugeZeroCochainReindex_symm_extendZero
#print axioms YangMills.RG.finitePiLpTypedKernelReindex_sourceAmbientDirichletPrecision
#print axioms YangMills.RG.finitePiLpTypedKernelReindex_symm_sourceAmbientDirichletPrecision
