/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102AmbientOrientedEdgeFDerivBound
import YangMills.RG.BalabanCMP98UbarLogAverageFDeriv

/-!
# Quantitative ambient derivatives of literal Wilson lines

This module lifts the audited single-edge exponential budgets through the
literal noncommutative ordered product.  It first derives the missing value
and value-Lipschitz estimates for either edge orientation, then constructs
the exact recursive Fréchet derivative of an arbitrary finite contour.

No contour-level value, derivative, or Lipschitz constant is supplied by the
caller.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102AmbientWilsonLineMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- Value budget for one oriented link on the ambient radius-`r` ball. -/
def cmp102AmbientEdgeValueBudget (r : ℝ) : ℝ :=
  1 + expSecondDerivativeBudget r * r ^ 2 +
    expDerivativeBudget r * r

/-- Value-Lipschitz budget for one oriented link on the radius-`r` ball. -/
def cmp102AmbientEdgeValueLipschitzBudget (r : ℝ) : ℝ :=
  2 * r * expSecondDerivativeBudget r + expDerivativeBudget r

theorem cmp102AmbientEdgeValueBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    0 ≤ cmp102AmbientEdgeValueBudget r := by
  unfold cmp102AmbientEdgeValueBudget
  have hB₂ : 0 ≤ expSecondDerivativeBudget r :=
    expSecondDerivativeBudget_nonneg r hr
  have hB₁ : 0 ≤ expDerivativeBudget r :=
    expDerivativeBudget_nonneg r hr
  positivity

theorem cmp102AmbientEdgeValueLipschitzBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    0 ≤ cmp102AmbientEdgeValueLipschitzBudget r := by
  unfold cmp102AmbientEdgeValueLipschitzBudget
  have hB₂ : 0 ≤ expSecondDerivativeBudget r :=
    expSecondDerivativeBudget_nonneg r hr
  have hB₁ : 0 ≤ expDerivativeBudget r :=
    expDerivativeBudget_nonneg r hr
  positivity

/-- The value of either oriented edge is generated by the exponential
budget; reverse orientation costs nothing because conjugate transpose is
an isometry for the matrix operator norm. -/
theorem norm_ambientOrientedEdgeMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (e : ConcreteEdge d (M * N')) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖ambientOrientedEdgeMatrix U Z e‖ ≤
      cmp102AmbientEdgeValueBudget r := by
  have hExp :
      ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ ≤
        cmp102AmbientEdgeValueBudget r := by
    simpa only [cmp102AmbientEdgeValueBudget] using
      (norm_exp_le_derivativeBudgets hr hZ)
  cases h : e.sign
  · rw [ambientOrientedEdgeMatrix, h]
    simp only [Bool.false_eq_true, if_false,
      Matrix.l2_opNorm_conjTranspose]
    unfold ambientPositiveBondMatrix physicalMatrixExp
    calc
      ‖NormedSpace.exp (Z (physicalBondOfEdge e)) *
          (U (positiveEdgeOfPhysicalBond
            (physicalBondOfEdge e))).val‖
          ≤ ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ *
              ‖orientedWilsonPositiveBase U e‖ := norm_mul_le _ _
      _ = ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ := by
        rw [norm_orientedWilsonPositiveBase, mul_one]
      _ ≤ cmp102AmbientEdgeValueBudget r := hExp
  · rw [ambientOrientedEdgeMatrix, h]
    simp only [if_true]
    unfold ambientPositiveBondMatrix physicalMatrixExp
    calc
      ‖NormedSpace.exp (Z (physicalBondOfEdge e)) *
          (U (positiveEdgeOfPhysicalBond
            (physicalBondOfEdge e))).val‖
          ≤ ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ *
              ‖orientedWilsonPositiveBase U e‖ := norm_mul_le _ _
      _ = ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ := by
        rw [norm_orientedWilsonPositiveBase, mul_one]
      _ ≤ cmp102AmbientEdgeValueBudget r := hExp

/-- The displacement of either oriented edge is Lipschitz in the global
ambient product norm.  The quadratic Taylor remainder is linearized only
after using the two radius-`r` hypotheses. -/
theorem norm_ambientOrientedEdgeMatrix_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (e : ConcreteEdge d (M * N')) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ‖Z (physicalBondOfEdge e)‖ ≤ r)
    (hW : ‖W (physicalBondOfEdge e)‖ ≤ r) :
    ‖ambientOrientedEdgeMatrix U Z e -
        ambientOrientedEdgeMatrix U W e‖ ≤
      cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := by
  let b := physicalBondOfEdge e
  let δ := ‖Z b - W b‖
  have hδ0 : 0 ≤ δ := norm_nonneg _
  have hδr : δ ≤ 2 * r := by
    dsimp only [δ]
    calc
      ‖Z b - W b‖ ≤ ‖Z b‖ + ‖W b‖ := norm_sub_le _ _
      _ ≤ r + r := add_le_add hZ hW
      _ = 2 * r := by ring
  have hδglobal : δ ≤ ‖Z - W‖ := by
    dsimp only [δ]
    simpa only [Pi.sub_apply] using
      (norm_physicalAmbientMatrixTangent_apply_le (Z - W) b)
  have hB₂ : 0 ≤ expSecondDerivativeBudget r :=
    expSecondDerivativeBudget_nonneg r hr
  have hB₁ : 0 ≤ expDerivativeBudget r :=
    expDerivativeBudget_nonneg r hr
  have hTaylor :
      ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖ ≤
        cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := by
    calc
      ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖
          ≤ expSecondDerivativeBudget r * δ ^ 2 +
              expDerivativeBudget r * δ := by
        simpa only [δ] using
          (norm_exp_sub_exp_le_derivativeBudgets hr hZ hW)
      _ ≤ expSecondDerivativeBudget r * ((2 * r) * δ) +
              expDerivativeBudget r * δ := by
        gcongr
        nlinarith
      _ = cmp102AmbientEdgeValueLipschitzBudget r * δ := by
        unfold cmp102AmbientEdgeValueLipschitzBudget
        ring
      _ ≤ cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ :=
        mul_le_mul_of_nonneg_left hδglobal
          (cmp102AmbientEdgeValueLipschitzBudget_nonneg hr)
  have hPositive :
      ‖ambientPositiveBondMatrix U Z b -
          ambientPositiveBondMatrix U W b‖ ≤
        cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := by
    have hfactor :
        ambientPositiveBondMatrix U Z b -
            ambientPositiveBondMatrix U W b =
          (NormedSpace.exp (Z b) - NormedSpace.exp (W b)) *
            (U (positiveEdgeOfPhysicalBond b)).val := by
      unfold ambientPositiveBondMatrix physicalMatrixExp
      noncomm_ring
    rw [hfactor]
    calc
      ‖(NormedSpace.exp (Z b) - NormedSpace.exp (W b)) *
          (U (positiveEdgeOfPhysicalBond b)).val‖
          ≤ ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖ *
              ‖orientedWilsonPositiveBase U e‖ := norm_mul_le _ _
      _ = ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖ := by
        rw [norm_orientedWilsonPositiveBase, mul_one]
      _ ≤ cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := hTaylor
  cases h : e.sign
  · rw [ambientOrientedEdgeMatrix, ambientOrientedEdgeMatrix, h]
    simp only [Bool.false_eq_true, if_false, ← Matrix.conjTranspose_sub,
      Matrix.l2_opNorm_conjTranspose]
    exact hPositive
  · rw [ambientOrientedEdgeMatrix, ambientOrientedEdgeMatrix, h]
    simp only [if_true]
    exact hPositive

/-- Exact recursive Fréchet derivative of a literal ordered Wilson line. -/
def cmp98AmbientWilsonLineDerivative
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z H : PhysicalAmbientMatrixTangent d (M * N') Nc) :
    List (ConcreteEdge d (M * N')) → Matrix (Fin Nc) (Fin Nc) ℂ
  | [] => 0
  | e :: es =>
      cmp102AmbientOrientedEdgeDerivative U Z H e *
          cmp98AmbientWilsonLineMatrix U Z es +
        ambientOrientedEdgeMatrix U Z e *
          cmp98AmbientWilsonLineDerivative U Z H es

/-- The recursive ordered expression is the literal ambient Fréchet
derivative, with no commutation of edge factors. -/
theorem fderiv_cmp98AmbientWilsonLineMatrix_apply
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z H : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) :
    fderiv ℝ (fun W => cmp98AmbientWilsonLineMatrix U W es) Z H =
      cmp98AmbientWilsonLineDerivative U Z H es := by
  induction es with
  | nil =>
      have hconst :
          HasFDerivAt
            (fun _ : PhysicalAmbientMatrixTangent d (M * N') Nc =>
              (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) 0 Z :=
        hasFDerivAt_const (𝕜 := ℝ) (x := Z) (c := (1 :
          Matrix (Fin Nc) (Fin Nc) ℂ))
      have hApply := congrArg
        (fun L : PhysicalAmbientMatrixTangent d (M * N') Nc →L[ℝ]
          Matrix (Fin Nc) (Fin Nc) ℂ => L H) hconst.fderiv
      simpa only [cmp98AmbientWilsonLineMatrix_nil,
        cmp98AmbientWilsonLineDerivative, ContinuousLinearMap.zero_apply]
        using hApply
  | cons e es ih =>
      have hHead :=
        (analyticAt_ambientOrientedEdgeMatrix U Z e).differentiableAt.hasFDerivAt
      have hTail :=
        (analyticAt_cmp98AmbientWilsonLineMatrix U Z es).differentiableAt.hasFDerivAt
      have hEq := (hHead.mul' hTail).fderiv
      have hApply := congrArg
        (fun L : PhysicalAmbientMatrixTangent d (M * N') Nc →L[ℝ]
          Matrix (Fin Nc) (Fin Nc) ℂ => L H) hEq
      change
        fderiv ℝ
            (fun W =>
              ambientOrientedEdgeMatrix U W e *
                cmp98AmbientWilsonLineMatrix U W es) Z H =
          ambientOrientedEdgeMatrix U Z e *
              fderiv ℝ
                (fun W => cmp98AmbientWilsonLineMatrix U W es) Z H +
            fderiv ℝ
                (fun W => ambientOrientedEdgeMatrix U W e) Z H *
              cmp98AmbientWilsonLineMatrix U Z es at hApply
      rw [ih, fderiv_ambientOrientedEdgeMatrix_apply U Z H e] at hApply
      simpa only [cmp98AmbientWilsonLineMatrix_cons,
        cmp98AmbientWilsonLineDerivative, add_comm] using hApply

/-- Recursive value budget for a contour of a given length. -/
def cmp98AmbientWilsonLineValueBudget (r : ℝ) : ℕ → ℝ
  | 0 => 1
  | n + 1 =>
      cmp102AmbientEdgeValueBudget r *
        cmp98AmbientWilsonLineValueBudget r n

/-- The literal contour value is bounded solely from its edge radius. -/
theorem norm_cmp98AmbientWilsonLineMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ∀ e ∈ es, ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖cmp98AmbientWilsonLineMatrix U Z es‖ ≤
      cmp98AmbientWilsonLineValueBudget r es.length := by
  induction es with
  | nil =>
      simp only [cmp98AmbientWilsonLineMatrix_nil, List.length_nil,
        cmp98AmbientWilsonLineValueBudget, norm_one, le_refl]
  | cons e es ih =>
      rw [cmp98AmbientWilsonLineMatrix_cons]
      calc
        ‖ambientOrientedEdgeMatrix U Z e *
            cmp98AmbientWilsonLineMatrix U Z es‖
            ≤ ‖ambientOrientedEdgeMatrix U Z e‖ *
                ‖cmp98AmbientWilsonLineMatrix U Z es‖ := norm_mul_le _ _
        _ ≤ cmp102AmbientEdgeValueBudget r *
              ‖cmp98AmbientWilsonLineMatrix U Z es‖ := by
          exact mul_le_mul_of_nonneg_right
            (norm_ambientOrientedEdgeMatrix_le U Z e hr
              (hZ e (by simp))) (norm_nonneg _)
        _ ≤ cmp102AmbientEdgeValueBudget r *
              cmp98AmbientWilsonLineValueBudget r es.length := by
          exact mul_le_mul_of_nonneg_left
            (ih (fun e he => hZ e (by simp [he])))
            (cmp102AmbientEdgeValueBudget_nonneg hr)
        _ = cmp98AmbientWilsonLineValueBudget r (e :: es).length := by
          simp only [List.length_cons, cmp98AmbientWilsonLineValueBudget]

end

end YangMills.RG
