import YangMills.RG.BalabanCMP102AmbientExpAverageThirdJetBound

#print axioms YangMills.RG.cmp102SourceLogAverageNNRadius
#print axioms YangMills.RG.cmp102SourceExpOrderThreeOuterBudget
#print axioms YangMills.RG.norm_iteratedFDeriv_exp_le_orderThreeOuterBudget
#print axioms YangMills.RG.cmp102SourceLogAverageCompositionRadius
#print axioms YangMills.RG.cmp102SourceExpAverageThirdJetBudget
#print axioms YangMills.RG.norm_iteratedFDeriv_cmp98UbarExpAverage_le_sourceThirdJetBudget
#print axioms YangMills.RG.norm_iteratedFDeriv_three_cmp98UbarExpAverage_le_sourceBudget
