import YangMills.RG.BalabanCMP99SourceGeneratedSectionCRightFactor

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseRightFactor
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseMiddleTransitionDefectCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseRightFactorCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseRightFactorCoordinates_eq_defect_comp_covariance
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceTransitionCoordinates_eq_comp_rightFactor
