import YangMills.RG.BalabanCMP99SourceEq395GlobalRegionalMiddleExponentialDecay

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDist
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDecayAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleGreenTransportPhysical_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectTerminalCoordinates_exponentialKernelBound
