import YangMills.RG.BalabanCMP116SourcePi4ExactSparseWalkMatrix

namespace YangMills.RG

#print axioms cmp116SourcePi4ExactSparseWalkLayer
#print axioms cmp116SourcePi4ExactHeadAnchoredWalkLayer
#print axioms cmp116SourcePi4ExactGeneratedAnchoredWalkLayer
#print axioms cmp116SourcePi4ExactSparseWalkLayer_eq_headAnchored
#print axioms cmp116SourcePi4ExactHeadAnchoredWalkLayer_eq_generated
#print axioms cmp116SourcePi4ExactPatchedCovariance_eq_tsum_sparseWalkLayers
#print axioms cmp116SourcePi4ExactPatchedCovariance_eq_tsum_headAnchoredWalkLayers
#print axioms cmp116SourcePi4ExactPatchedCovariance_eq_tsum_generatedAnchoredWalkLayers
#print axioms cmp116SourcePi4_precision_mul_tsum_sparseWalkLayerMatrix_eq_one
#print axioms cmp116SourcePi4_precision_mul_tsum_headAnchoredWalkLayerMatrix_eq_one
#print axioms cmp116SourcePi4_precision_mul_tsum_generatedAnchoredWalkLayerMatrix_eq_one
#print axioms cmp116SourcePi4ExactGeneratedAnchoredCovarianceMatrix
#print axioms cmp116SourcePi4ExactGeneratedAnchoredCovarianceMatrix_eq_exact
#print axioms det_cmp116SourcePi4PhysicalPrecisionMatrix_ne_zero
#print axioms det_cmp116SourcePi4ExactGeneratedAnchoredCovarianceMatrix_ne_zero

end YangMills.RG
