/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80CorrectedPhysicalRegularity
import YangMills.RG.BalabanCMP102Eq80PhysicalCorrectionFirstOrder
import YangMills.RG.BalabanCMP116RadialTaylorOperator

/-!
# Radial form of the background-dependent CMP102 equation-(80) sector

The localized minimizer telescoping reconstructs the difference between
the equation-(80) potential at the physical background minimizer and at
the zero minimizer.  It does not reconstruct the full CMP116 activity.

This module names precisely that background-dependent sector and gives it
its exact radial Taylor operator.  It makes no identification with the
source residual `V''_k` or with the complete domain activity `V_k(Y, ·)`.
-/

open scoped RealInnerProductSpace

namespace YangMills.RG

noncomputable section

private abbrev FineField (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  FinePhysicalOneCochain 4 M (2 * Q) Nc

private abbrev CoarseField (Q Nc : ℕ) [NeZero (2 * Q)] :=
  CoarsePhysicalOneCochain 4 (2 * Q) Nc

private abbrev FineEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  FineField M Q Nc →L[ℝ] FineField M Q Nc

/-- The exact part of the corrected equation-(80) potential generated by
turning on its physical background minimizer. -/
noncomputable def
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J A : FineField M Q Nc) : ℝ :=
  let D := cmp102Eq80PhysicalBackgroundCorrection
    U ha hP hε hsmall hbudget ρ radius
      (fun _ => r₀) (fun _ => s₀) S hcontract
  cmp102Eq80CorrectedPhysicalGlobalPotential
      U ha hP hε hsmall hbudget ρ radius
      (fun _ => r₀) (fun _ => s₀) S hcontract D₃ V₀ Δπ J A -
    cmp102Eq80GlobalPotential D D₃ V₀ 0 Δπ J A

/-- With the minimizer set to zero the only surviving term of equation
(80) is the bare potential `V₀`. -/
theorem
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_eq_sub_V0
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J A : FineField M Q Nc) :
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
        U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
        D₃ V₀ Δπ J A =
      cmp102Eq80CorrectedPhysicalGlobalPotential
          U ha hP hε hsmall hbudget ρ radius
          (fun _ => r₀) (fun _ => s₀) S hcontract D₃ V₀ Δπ J A -
        V₀ A := by
  simp [
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential,
    cmp102Eq80GlobalPotential]

/-- `C²` regularity of the exact background-dependent sector. -/
theorem
    contDiff_two_cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hρ : ∀ A, 0 < ρ A)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J : FineField M Q Nc)
    (hD₃ : ContDiff ℝ ⊤ D₃) (hV₀ : ContDiff ℝ ⊤ V₀) :
    ContDiff ℝ 2
      (cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
        U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
        D₃ V₀ Δπ J) := by
  have hcorrected :=
    contDiff_two_cmp102Eq80CorrectedPhysicalGlobalPotential
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hρ hcontract
      D₃ V₀ Δπ J hD₃ hV₀
  convert hcorrected.sub (hV₀.of_le le_top) using 1
  funext A
  simp [
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential,
    cmp102Eq80GlobalPotential]

/-- Normalization of the background-dependent sector at the origin. -/
theorem
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_zero
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J : FineField M Q Nc)
    (hD₃0 : D₃ 0 = 0) (hV₀0 : V₀ 0 = 0) :
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
        U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
        D₃ V₀ Δπ J 0 = 0 := by
  rw [
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_eq_sub_V0,
    cmp102Eq80CorrectedPhysicalGlobalPotential_zero
      U ha hP hε hsmall hbudget ρ radius
        (fun _ => r₀) (fun _ => s₀) S hcontract
        D₃ V₀ Δπ J hD₃0 hV₀0,
    hV₀0,
    sub_zero]

/-- First-order normalization of the background-dependent sector. -/
theorem
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_hasFDerivAt_zero
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J : FineField M Q Nc)
    (hD₃0 : D₃ 0 = 0)
    (hD₃ : HasFDerivAt D₃
      (0 : FineField M Q Nc →L[ℝ] CoarseField Q Nc) 0)
    (hV₀ : HasFDerivAt V₀
      (0 : FineField M Q Nc →L[ℝ] ℝ) 0) :
    HasFDerivAt
      (cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
        U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
        D₃ V₀ Δπ J)
      (0 : FineField M Q Nc →L[ℝ] ℝ) 0 := by
  have hcorrected :=
    cmp102Eq80CorrectedPhysicalGlobalPotential_hasFDerivAt_zero_constRadii
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
      D₃ V₀ Δπ J hD₃0 hD₃ hV₀
  convert hcorrected.sub hV₀ using 1
  · funext A
    simp [
      cmp102Eq80CorrectedPhysicalBackgroundDependentPotential,
      cmp102Eq80GlobalPotential]
  · simp

/-- Radial Taylor operator of exactly the sector reconstructed by the
localized minimizer expansion. -/
noncomputable def
    cmp102Eq80CorrectedPhysicalBackgroundDependentRadialOperator
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hρ : ∀ A, 0 < ρ A)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J : FineField M Q Nc)
    (hD₃ : ContDiff ℝ ⊤ D₃) (hV₀ : ContDiff ℝ ⊤ V₀)
    (A : FineField M Q Nc) : FineEndomorphism M Q Nc :=
  cmp116RadialTaylorOperator
    (cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
      D₃ V₀ Δπ J)
    A
    (contDiff_two_cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hρ hcontract
      D₃ V₀ Δπ J hD₃ hV₀)

/-- Exact radial identity for the background-dependent equation-(80)
sector, without identifying it with the complete localized activity. -/
theorem
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_eq_radial
    {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    {a CP ε : ℝ} (ha : 0 < a)
    (hP : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
      (matrixSUNAdjointModel Nc) CP)
    (hε : 0 ≤ ε) (hsmall : PhysicalWilsonSmallBackground U ε)
    (hbudget : cmp116ConcreteInteractingWilsonGaugeDefectBudget 4 Nc ε <
      min 1 a / CP)
    (ρ radius : FineField M Q Nc → ℝ)
    (r₀ s₀ : ℝ)
    (S : ∀ A, CMP102PhysicalBackgroundCorrectionScalarData
      U ha hP hε hsmall hbudget A (ρ A) (radius A) r₀ s₀)
    (hρ : ∀ A, 0 < ρ A)
    (hcontract : ∀ A, ((S A).toBallData).contractionRate < 1)
    (D₃ : FineField M Q Nc → CoarseField Q Nc)
    (V₀ : FineField M Q Nc → ℝ)
    (Δπ : FineEndomorphism M Q Nc)
    (J : FineField M Q Nc)
    (hD₃smooth : ContDiff ℝ ⊤ D₃) (hV₀smooth : ContDiff ℝ ⊤ V₀)
    (hD₃0 : D₃ 0 = 0)
    (hD₃ : HasFDerivAt D₃
      (0 : FineField M Q Nc →L[ℝ] CoarseField Q Nc) 0)
    (hV₀0 : V₀ 0 = 0)
    (hV₀ : HasFDerivAt V₀
      (0 : FineField M Q Nc →L[ℝ] ℝ) 0)
    (A : FineField M Q Nc) :
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
        U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
        D₃ V₀ Δπ J A =
      (1 / 2 : ℝ) * inner ℝ A
        (cmp102Eq80CorrectedPhysicalBackgroundDependentRadialOperator
          U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hρ hcontract
          D₃ V₀ Δπ J hD₃smooth hV₀smooth A A) := by
  let f :=
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
      D₃ V₀ Δπ J
  have hsmooth : ContDiff ℝ 2 f :=
    contDiff_two_cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hρ hcontract
      D₃ V₀ Δπ J hD₃smooth hV₀smooth
  have hf0 : f 0 = 0 :=
    cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_zero
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
      D₃ V₀ Δπ J hD₃0 hV₀0
  have hdf0 : fderiv ℝ f 0 = 0 :=
    (cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_hasFDerivAt_zero
      U ha hP hε hsmall hbudget ρ radius r₀ s₀ S hcontract
      D₃ V₀ Δπ J hD₃0 hD₃ hV₀).fderiv
  simpa [
    f,
    cmp102Eq80CorrectedPhysicalBackgroundDependentRadialOperator] using
    cmp116RadialTaylorOperator_eq_of_normalized f A hsmooth hf0 hdf0

end

end YangMills.RG
