import YangMills.RG.BalabanCMP99PatchedParametrixWalkExpansion

/-! Axiom audit for the CMP99 patched-parametrix walk expansion. -/

#print axioms YangMills.RG.cmp99OrderedTupleProduct_cons
#print axioms YangMills.RG.sum_pow_eq_sum_cmp99OrderedTupleProduct
#print axioms YangMills.RG.cmp99SingleSpeciesWalk_length
#print axioms YangMills.RG.cmp99SingleSpeciesWalk_term
#print axioms YangMills.RG.sum_mul_sum_pow_eq_sum_cmp99SingleSpeciesWalk_term
#print axioms YangMills.RG.CMP99GeneralizedWalk.norm_term_le_of_factor_bounds
#print axioms YangMills.RG.sum_cmp99PhysicalPatchHead
#print axioms YangMills.RG.sum_cmp99PhysicalPatchContinuation
#print axioms YangMills.RG.cmp99PatchedPhysicalParametrix_mul_neg_defect_pow_eq_walk_sum
#print axioms YangMills.RG.cmp99CorrectedPatchedPhysicalCovariance_eq_tsum_walk_layers
#print axioms YangMills.RG.norm_physicalBondProjection_le_one_anyVolume
#print axioms YangMills.RG.norm_cmp99PhysicalPatchHead_le
#print axioms YangMills.RG.norm_cmp99PhysicalPatchContinuation_le
#print axioms YangMills.RG.norm_cmp99PhysicalSingleSpeciesWalk_term_le
