import YangMills.RG.BalabanCMP89Eq248StabilizedGreenEndpointPeriodicity

/-!
PRE-VALIDATION: this audit source is present, its `.olean` has not yet been
materialized, and its declarations have not yet been compiler verified.
-/

#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointMomentumTerm_coordinateAliasPeriodShift
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointAliasTerm_eq_momentumTerm
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointIntegrand_physicalPeriodShift
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointAliasTerm_eq_stabilizedTerm
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointCentralTerm_eq_stabilized
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointIntegrand_eq_stabilized
#print axioms YangMills.RG.cmp89Eq248ComplexStabilizedGreenEndpointIntegrand_physicalPeriodShift_of_nonzero
