import YangMills.RG.BalabanCMP116SourcePi4FullComplexContourDefect

#print axioms YangMills.RG.cmp116SourcePi4ComplexContourRatio
#print axioms YangMills.RG.cmp116SourcePi4ComplexContourPrefactor
#print axioms YangMills.RG.cmp116SourcePi4ComplexDefectLayerAmplitude_eq_contourPrefactor_mul
#print axioms YangMills.RG.hasSum_cmp116SourcePi4ComplexDefectLayerAmplitude
#print axioms YangMills.RG.summable_cmp116SourcePi4FullComplexWeakenedCovarianceLayer_sub_one
#print axioms YangMills.RG.summable_cmp116SourcePi4FullComplexWeakenedCovarianceLayer_one
#print axioms YangMills.RG.linfty_opNorm_cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_sub_one_le
