import YangMills.RG.BalabanCMP99Eq389GeneratedMassCommonMetric

#print axioms YangMills.RG.sum_norm_finitePiLpTypedKernelReindex_single_varying
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalFullSiteEquiv_blockSite_eq_of_sameTerminalBlock
#print axioms YangMills.RG.cmp99Eq342RescaledBlockDist_sourceSeparated_eq_of_sameTerminalBlock
