import YangMills.RG.BalabanCMP102Eq80PhysicalDomainCoefficientThirdFieldDerivative

#print axioms YangMills.RG.cmp102PartialPropagatorJetThirdFieldDerivative_apply
#print axioms YangMills.RG.norm_cmp102PartialPropagatorJetThirdFieldDerivative_le
#print axioms YangMills.RG.norm_iteratedFDeriv_fixedFirstSlice_normed_le
#print axioms YangMills.RG.norm_iteratedFDeriv_three_cmp102PartialPropagatorJet_one_le
#print axioms YangMills.RG.norm_cmp102Eq80PhysicalFineHeadTailDomainCoefficientThirdFieldDerivative_le_sourceJets
#print axioms YangMills.RG.norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceJets
