import YangMills.RG.BalabanCMP99PatchedParametrixCollar
import YangMills.RG.PhysicalExponentialKernelComposition

/-!
# CMP99 patched parametrix: exponential kernel bound for one defect

The exact exterior-flux factorization is combined here with finite range of
the global precision, the local Combes--Thomas estimate, and exponential
kernel composition.  This produces a volume-uniform exponential kernel bound
for a single chart defect.  The additional small factor coming from a concrete
core-to-exterior collar width is deliberately left to the next geometric
specialization.
-/

namespace YangMills.RG

noncomputable section

private abbrev PhysicalEndomorphism (d N Nc : ℕ) [NeZero N] :=
  PhysicalGaugeOneCochain d N Nc →L[ℝ]
    PhysicalGaugeOneCochain d N Nc

/-- Explicit amplitude generated by the three intermediate bond sums in the
four-factor exterior-flux defect. -/
noncomputable def cmp99SingleDefectDecayAmplitude
    (M κ : ℝ) (R : ℕ) (c mass Ssum : ℝ) : ℝ :=
  (M * Real.exp (κ * (R : ℝ))) *
    ((2 / min c mass) * 1 * Ssum) * Ssum * Ssum

/-- A core is separated from the exterior of its enlarged domain by at least
`L` in the chosen physical metric. -/
def CMP99CoreExteriorSeparated
    {d N : ℕ} [NeZero N]
    (core enlarged : Finset (PhysicalBond d N))
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (L : ℕ) : Prop :=
  ∀ source, source ∈ core → ∀ target, target ∉ enlarged →
    L ≤ dist target source

/-- An exterior--core factorization converts metric separation into an
explicit small factor, while retaining half of the original decay rate. -/
theorem physicalExteriorCoreKernelBound_of_separated
    {d N Nc : ℕ} [NeZero N]
    (Middle : PhysicalEndomorphism d N Nc)
    (core enlarged : Finset (PhysicalBond d N))
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    {A rate : ℝ} {L : ℕ}
    (hD : PhysicalCovarianceExponentialKernelBound
      ((physicalBondComplementProjection enlarged).comp
        (Middle.comp (physicalBondProjection core)))
      dist A rate)
    (hsep : CMP99CoreExteriorSeparated core enlarged dist L) :
    PhysicalCovarianceExponentialKernelBound
      ((physicalBondComplementProjection enlarged).comp
        (Middle.comp (physicalBondProjection core)))
      dist
      (A * Real.exp (-((rate / 2) * (L : ℝ))))
      (rate / 2) := by
  refine ⟨mul_nonneg hD.1 (Real.exp_pos _).le, half_pos hD.2.1, ?_⟩
  intro source target v
  by_cases hs : source ∈ core
  · by_cases ht : target ∈ enlarged
    · simp only [ContinuousLinearMap.comp_apply, physicalBondComplementProjection,
        ContinuousLinearMap.sub_apply, ContinuousLinearMap.id_apply]
      change ‖Middle (physicalBondProjection core
        (singlePhysicalBondCochain source v)) target -
          physicalBondProjection enlarged
            (Middle (physicalBondProjection core
              (singlePhysicalBondCochain source v))) target‖ ≤ _
      rw [physicalBondProjection_apply_mem enlarged ht, sub_self, norm_zero]
      exact mul_nonneg
        (mul_nonneg
          (mul_nonneg hD.1 (Real.exp_pos _).le)
          (Real.exp_pos _).le)
        (norm_nonneg v)
    · have hLnat := hsep source hs target ht
      have hL : (L : ℝ) ≤ (dist target source : ℝ) := by
        exact_mod_cast hLnat
      have hexp :
          Real.exp (-(rate * (dist target source : ℝ))) ≤
            Real.exp (-((rate / 2) * (L : ℝ))) *
              Real.exp (-((rate / 2) * (dist target source : ℝ))) := by
        rw [← Real.exp_add]
        apply Real.exp_le_exp.mpr
        nlinarith [hD.2.1]
      calc
        ‖((physicalBondComplementProjection enlarged).comp
              (Middle.comp (physicalBondProjection core)))
            (singlePhysicalBondCochain
              (d := d) (N := N) (Nc := Nc) source v) target‖
            ≤ A * Real.exp (-(rate * (dist target source : ℝ))) * ‖v‖ :=
          hD.2.2 source target v
        _ ≤ A *
              (Real.exp (-((rate / 2) * (L : ℝ))) *
                Real.exp (-((rate / 2) * (dist target source : ℝ)))) * ‖v‖ :=
          mul_le_mul_of_nonneg_right
            (mul_le_mul_of_nonneg_left hexp hD.1) (norm_nonneg v)
        _ = (A * Real.exp (-((rate / 2) * (L : ℝ)))) *
              Real.exp (-((rate / 2) * (dist target source : ℝ))) * ‖v‖ := by
          ring
  · simp only [ContinuousLinearMap.comp_apply]
    rw [physicalBondProjection_single_not_mem core source v hs, map_zero,
      map_zero]
    change ‖(0 : SUNLieCoord Nc)‖ ≤ _
    rw [norm_zero]
    exact mul_nonneg
      (mul_nonneg
        (mul_nonneg hD.1 (Real.exp_pos _).le)
        (Real.exp_pos _).le)
      (norm_nonneg v)

/-- A single patched-parametrix defect is exponentially localized.  All
constants are visible: finite-range conversion costs `exp(κR)` and the three
intermediate bond sums cost three copies of `Ssum`. -/
theorem cmp99SinglePhysicalParametrixDefect_exponentialKernelBound
    {d N Nc : ℕ} [NeZero N]
    (K : PhysicalEndomorphism d N Nc)
    {core enlarged : Finset (PhysicalBond d N)}
    (hsub : core ⊆ enlarged)
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (hsymm : ∀ p q, dist p q = dist q p)
    (hself : ∀ p, dist p p = 0)
    (htri : ∀ x y z, dist x y ≤ dist x z + dist z y)
    {R NR : ℕ} {M c mass κ σ Ssum : ℝ}
    (hM : 0 ≤ M) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ) (hSsum : 0 ≤ Ssum)
    (hsum : ∀ x,
      ∑ z : PhysicalBond d N,
        Real.exp (-(σ * (dist x z : ℝ))) ≤ Ssum)
    (hrange : PhysicalCovarianceFiniteRange K dist R)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => M))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond d N,
      (Finset.univ.filter (fun y => dist x y ≤ R)).card ≤ NR)
    (htilt :
      (M + |mass|) *
          (Real.exp (κ * (R : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2) :
    PhysicalCovarianceExponentialKernelBound
      ((K - cmp99LocalizedPhysicalPrecision K enlarged mass).comp
        ((cmp99LocalizedPhysicalCovariance K enlarged hc hmass hK).comp
          (physicalBondProjection core)))
      dist
      (cmp99SingleDefectDecayAmplitude M κ R c mass Ssum)
      (((κ - σ) - σ) - σ) := by
  have hκ : 0 < κ := by linarith
  have h2σκ : 2 * σ < κ := by linarith
  have hσlast : σ < (κ - σ) - σ := by linarith
  have hrate2 : 0 < (κ - σ) - σ := by linarith
  have htriCT : ∀ p q s, dist p s ≤ dist p q + dist q s := by
    intro p q s
    exact htri p s q
  have hKexp :
      PhysicalCovarianceExponentialKernelBound K dist
        (M * Real.exp (κ * (R : ℝ))) κ :=
    physicalCovarianceExponentialKernelBound_of_finiteRange
      dist hM hκ K hrange hbound
  have hCexp :
      PhysicalCovarianceExponentialKernelBound
        (cmp99LocalizedPhysicalCovariance K enlarged hc hmass hK)
        dist (2 / min c mass) κ :=
    cmp99LocalizedPhysicalCovariance_exponentialKernelBound
      dist hsymm htriCT hself K enlarged hc hmass hM hNR
        hrange hbound hK hκ htilt
  have hPexp :
      PhysicalCovarianceExponentialKernelBound
        (physicalBondProjection core : PhysicalEndomorphism d N Nc)
        dist 1 κ :=
    physicalBondProjection_exponentialKernelBound dist hself core hκ
  have hQexp :
      PhysicalCovarianceExponentialKernelBound
        (physicalBondComplementProjection enlarged : PhysicalEndomorphism d N Nc)
        dist 1 κ := by
    simpa using
      (physicalCovarianceExponentialKernelBound_of_finiteRange
        dist zero_le_one hκ
          (physicalBondComplementProjection enlarged : PhysicalEndomorphism d N Nc)
          (physicalBondComplementProjection_finiteRange dist hself enlarged)
          (physicalBondComplementProjection_kernelBound enlarged))
  have hKCP :
      PhysicalCovarianceExponentialKernelBound
        (K.comp
          ((cmp99LocalizedPhysicalCovariance K enlarged hc hmass hK).comp
            (physicalBondProjection core)))
        dist
        ((M * Real.exp (κ * (R : ℝ))) *
          ((2 / min c mass) * 1 * Ssum) * Ssum)
        ((κ - σ) - σ) :=
    physicalCovarianceExponentialKernelBound_comp_three
      dist htri hσ h2σκ hSsum K
        (cmp99LocalizedPhysicalCovariance K enlarged hc hmass hK)
        (physicalBondProjection core) hKexp hCexp hPexp hsum
  have hQweak :
      PhysicalCovarianceExponentialKernelBound
        (physicalBondComplementProjection enlarged : PhysicalEndomorphism d N Nc)
        dist 1 ((κ - σ) - σ) :=
    physicalCovarianceExponentialKernelBound_mono_rate
      dist hrate2 (by linarith) _ hQexp
  have hflux :
      PhysicalCovarianceExponentialKernelBound
        ((physicalBondComplementProjection enlarged).comp
          (K.comp
            ((cmp99LocalizedPhysicalCovariance K enlarged hc hmass hK).comp
              (physicalBondProjection core))))
        dist
        (1 *
          ((M * Real.exp (κ * (R : ℝ))) *
            ((2 / min c mass) * 1 * Ssum) * Ssum) * Ssum)
        (((κ - σ) - σ) - σ) :=
    physicalCovarianceExponentialKernelBound_comp
      dist htri hσ hσlast hSsum _ _ hQweak hKCP hsum
  rw [cmp99SinglePhysicalParametrixDefect_eq_exterior_flux
    K hsub hc hmass hK]
  simpa [cmp99SingleDefectDecayAmplitude, mul_assoc] using hflux

end

end YangMills.RG
