import YangMills.RG.BalabanCMP99SourceFlatQprimeFourierAmplitude

#print axioms YangMills.RG.cmp99SourceFlatQprimeOffsetCharacter
#print axioms YangMills.RG.cmp99SourceFlatQprimeOffsetAmplitude
#print axioms YangMills.RG.cmp99SourceFlatQprimeOffsetAmplitude_eq_entireAverageAmplitude
#print axioms YangMills.RG.cmp99SourceFlatQprimeOffsetAmplitude_mul_neg_eq
