import YangMills.RG.BalabanCMP102Eq80SourcePi4FaaDiBrunoPhysicalExpansion

#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBrunoBlockCoordinates_injective
#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBrunoBlockCoordinates_fresh
#print axioms YangMills.RG.ftaylorSeries_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealCovariance_apply_orderedPartitionBlock
#print axioms YangMills.RG.iteratedFDeriv_cmp102Eq80SourcePi4RealPotentialVertexPolynomial_apply_coordinateBlock_eq_physicalOrderedPartitions
#print axioms YangMills.RG.ftaylorSeries_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealCovariance_apply_orderedPartitionBlock_at
#print axioms YangMills.RG.iteratedFDeriv_cmp102Eq80SourcePi4RealPotentialVertexPolynomial_apply_coordinateBlock_at_eq_physicalOrderedPartitions
