import YangMills.RG.BalabanCMP102Eq80PhysicalDomainFTCEq136Residual

#print axioms YangMills.RG.cmp102Eq80Eq136ResidualMetricRate
#print axioms YangMills.RG.cmp102Eq80Eq136ThirdJetProducerPrefactor
#print axioms YangMills.RG.CMP102Eq80Eq136ThirdJetProducerBudget
#print axioms YangMills.RG.cmp102Eq80PhysicalDomainFTCThirdFieldCubicCutoffMajorant_le_eq136
#print axioms YangMills.RG.abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_eq136_of_source
