import YangMills.RG.BalabanCMP102Eq80PhysicalFineHeadTailAnchoredLocalization

#print axioms YangMills.RG.cmp102Eq80SourcePi4FineHeadTailLocalizationDomain
#print axioms YangMills.RG.cmp102Eq80SourcePi4AnchorCarrier_subset_fineHeadTailLocalizationDomain
#print axioms YangMills.RG.cmp102Eq80SourcePi4FineHeadTailLocalizationDomain_subset
#print axioms YangMills.RG.walkConnected_cmp102Eq80SourcePi4FineHeadTailLocalizationDomain
#print axioms YangMills.RG.cmp102Eq80PhysicalFineHeadTailDerivative_sum_eq_sum_carrierAnchoredFibers
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_physicalChoiceWord_eq_tsum_carrierAnchoredFibers
#print axioms YangMills.RG.cmp102Eq80PhysicalChoiceAnchoredDerivativeSeries
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_physicalWord_eq_sum_choiceAnchoredSeries
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_physicalNeumannLayer_eq_tsum_localizedWords
