import YangMills.RG.BalabanCMP102Eq80SourcePi4V0SecondMixedLocalization

#print axioms YangMills.RG.cmp102Eq80V0BilinearTerm_sum_sum
#print axioms YangMills.RG.cmp102Eq80SourcePi4V0BilinearDomainCoefficient_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4V0BilinearDomainCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp102Eq80SourcePi4V0SecondMixedDomainCoefficient_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4V0SecondMixedDomainCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp102Eq80V0SecondMixedTerm_fullRealMixed_eq_sum_pi4Domains
