import YangMills.RG.BalabanCMP99SourceSectionCSmoothTypedFactorWalk

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceLabelOperator
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceLabelOperator_cut
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceLabelOperator_commutator
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceLabelWeightedRowAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceLabelOperator_weightedRowKernelBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceOperatorWalk
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceOperatorWalk_weightedRowKernelBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceOperatorWalk_exponentialKernelBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceCutOperatorWalk
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceCutOperatorWalk_eq_factorTower
