/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP109ConstraintCorrectionFixedPoint

/-!
# Parameter-uniform CMP109 constraint correction

PRE-VALIDATION: the source is present, its `.olean` has not yet been
materialized, and the result is not yet compiler-verified.

CMP116 equations (1.13)--(1.14) apply the CMP109 fixed-point construction to
the weakened background `H(s)` uniformly on an admissible polydisc in `s`.
The pointwise Banach theorem already exists in
`BalabanCMP109ConstraintCorrectionFixedPoint`; this module packages the
source-faithful family statement with common radii and one common contraction
budget.

The fixed points are constructed internally from the literal maps
`D ↦ C(A - hD)`.  No family of preselected solutions is accepted.  The
admissible parameter set is required to be nonempty, so the uniform statement
cannot be inhabited by choosing an empty polydisc.

Honest scope: the family data still contains the source estimates which show
that the chart and self-map budgets hold uniformly for `H(s)`.  Those are the
analytic contents of CMP116 (1.13)--(1.14), ultimately fed by the printed walk
bound.  This module performs the uniform Banach step; it does not prove that
walk bound, construct `H(s)`, or discharge Lemma 1 equation (1.36).

Oracle target: `[propext, Classical.choice, Quot.sound]`. No placeholders or
local axioms.
-/

namespace YangMills.RG

open YangMills

noncomputable section

variable {Parameter : Type*}
variable {d L N' Nc : ℕ}
variable [NeZero d] [NeZero L] [NeZero N'] [NeZero Nc]
  [NeZero (L * N')]

/-- Uniform source data for the CMP109 correction over an admissible parameter
family.  The common scalars `rho`, `localRadius`, and `relativeRadius` make the
resulting norm and contraction estimates uniform in the parameter. -/
structure CMP109ConstraintCorrectionParameterFamilyData
    (admissible : Parameter → Prop)
    (background : Parameter → PhysicalGaugeBackground d (L * N') Nc)
    (A : FinePhysicalOneCochain d L N' Nc)
    (rho localRadius relativeRadius : ℝ) where
  admissible_nonempty : Set.Nonempty {s | admissible s}
  ballData : ∀ s, admissible s →
    CMP109ConstraintCorrectionBallData
      (background s) A rho localRadius relativeRadius
  contraction_lt_one :
    cmp102PhysicalCorrectionContractionRate
          Nc d L localRadius relativeRadius *
        (L : ℝ) ^ (d - 1) < 1

namespace CMP109ConstraintCorrectionParameterFamilyData

variable
    {admissible : Parameter → Prop}
    {background : Parameter → PhysicalGaugeBackground d (L * N') Nc}
    {A : FinePhysicalOneCochain d L N' Nc}
    {rho localRadius relativeRadius : ℝ}
    (F : CMP109ConstraintCorrectionParameterFamilyData
      admissible background A rho localRadius relativeRadius)

/-- The common scalar contraction budget is exactly the pointwise contraction
rate generated by each member's literal CMP109 map. -/
theorem contractionRate_lt_one
    (s : Parameter) (hs : admissible s) :
    (F.ballData s hs).contractionRate < 1 := by
  simpa [CMP109ConstraintCorrectionBallData.contractionRate] using
    F.contraction_lt_one

/-- The parameter-indexed correction, selected from the unique Banach point
of the literal map at that parameter. -/
noncomputable def correction
    (s : Parameter) (hs : admissible s) :
    PhysicalGaugeOneCochainSup d N' Nc :=
  Classical.choose
    ((F.ballData s hs).existsUnique_constraintCorrection
      (F.contractionRate_lt_one s hs))

/-- Every selected correction lies in the same certified ball, uniformly in
the admissible parameter. -/
theorem correction_mem_ball
    (s : Parameter) (hs : admissible s) :
    ‖F.correction s hs‖ ≤ rho := by
  exact
    (Classical.choose_spec
      ((F.ballData s hs).existsUnique_constraintCorrection
        (F.contractionRate_lt_one s hs))).1.1

/-- The selected family solves the literal fixed-point equation at every
admissible parameter. -/
theorem correction_fixedPoint
    (s : Parameter) (hs : admissible s) :
    cmp109ConstraintCorrectionMap
        (background s) A rho localRadius relativeRadius
        (F.ballData s hs) (F.correction s hs) =
      F.correction s hs := by
  exact
    (Classical.choose_spec
      ((F.ballData s hs).existsUnique_constraintCorrection
        (F.contractionRate_lt_one s hs))).1.2

/-- Physical form of the family fixed-point equation
`D(H(s),A) = C(A - h D(H(s),A))`. -/
theorem correction_physicalEquation
    (s : Parameter) (hs : admissible s) :
    physicalGaugeOneCochainSupEquiv
        (cmp102PhysicalNonlinearCorrectionOfBudget (background s)
          (A - cmp96ConstraintPivotInsertion (L := L)
            (physicalGaugeOneCochainSupEquiv.symm (F.correction s hs)))
          ((F.ballData s hs).chartBudget (F.correction s hs)
            (F.correction_mem_ball s hs))) =
      F.correction s hs := by
  rw [← (F.ballData s hs).correctionMap_eq_of_mem
    (F.correction s hs) (F.correction_mem_ball s hs)]
  exact F.correction_fixedPoint s hs

end CMP109ConstraintCorrectionParameterFamilyData

end

end YangMills.RG
