/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116ComplexQuadraticSchur
import YangMills.RG.BalabanCMP116MatrixGaussianCarrier

/-!
# Carrier-supported complex interaction absorption

On the conditioned Gaussian carrier, the volume-uniform bilateral Schur
bound for `R2`, the physical potential, and the large-field energy consume a
single `alpha5` budget.  This is the almost-everywhere form needed before the
inner integration in equation (2.23).
-/

namespace YangMills.RG

open Matrix
open scoped BigOperators Matrix.Norms.Operator

noncomputable section

/-- Scalar absorption of the literal complex `R2` quadratic, potential, and
large-field energy after the ambient Gaussian energy has been identified
with its conditioned carrier. -/
theorem cmp116Eq220_eq221_eq222_complexInteraction_le_localized
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ) (x : ι → ℝ)
    (potential : ℂ)
    (carrierEnergy cutoffEnergy potentialRate r2Rate gamma alpha residual : ℝ)
    (hpotential :
      potential.re ≤ potentialRate / 2 * carrierEnergy + residual)
    (hR2 :
      (‖A‖ + ‖A.transpose‖) / 2 ≤ r2Rate)
    (hambient : (∑ i, x i ^ 2) = carrierEnergy)
    (hcutoff : cutoffEnergy ≤ carrierEnergy)
    (hgamma : 0 ≤ gamma)
    (hbudget : potentialRate + r2Rate + gamma ≤ alpha) :
    (cmp116Eq214ComplexQuadratic A x + potential).re +
        gamma / 2 * cutoffEnergy ≤
      alpha / 2 * carrierEnergy + residual := by
  have henergy : 0 ≤ carrierEnergy := by
    rw [← hambient]
    exact Finset.sum_nonneg fun i hi => sq_nonneg _
  have hcoeff :
      (‖A‖ + ‖A.transpose‖) / 4 ≤ r2Rate / 2 := by
    linarith
  have hquadratic :
      (cmp116Eq214ComplexQuadratic A x).re ≤
        r2Rate / 2 * carrierEnergy := by
    calc
      (cmp116Eq214ComplexQuadratic A x).re ≤
          (‖A‖ + ‖A.transpose‖) / 4 * ∑ i, x i ^ 2 :=
        cmp116Eq214ComplexQuadratic_re_le_linfty_bilateral A x
      _ = (‖A‖ + ‖A.transpose‖) / 4 * carrierEnergy := by
        rw [hambient]
      _ ≤ r2Rate / 2 * carrierEnergy :=
        mul_le_mul_of_nonneg_right hcoeff henergy
  have hcutoffScaled :
      gamma / 2 * cutoffEnergy ≤ gamma / 2 * carrierEnergy :=
    mul_le_mul_of_nonneg_left hcutoff (by positivity)
  have hbudgetScaled :
      (potentialRate + r2Rate + gamma) / 2 * carrierEnergy ≤
        alpha / 2 * carrierEnergy :=
    mul_le_mul_of_nonneg_right (by linarith) henergy
  rw [Complex.add_re]
  linarith

/-- Almost-everywhere absorption generated by a certified conditioned
Gaussian root. -/
theorem cmp116Eq220_eq221_eq222_complexInteraction_le_localized_ae
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    {C R : Matrix ι ι ℝ} {S : Finset ι}
    (hroot : MatrixConditionedGaussianRootCertificate C R S)
    (A : Matrix ι ι ℂ)
    (potential : (ι → ℝ) → ℂ)
    (cutoffEnergy : (ι → ℝ) → ℝ)
    (potentialRate r2Rate gamma alpha residual : ℝ)
    (hpotential : ∀ᵐ x ∂matrixGaussianPi R,
      (potential x).re ≤
        potentialRate / 2 * (∑ i ∈ S, x i ^ 2) + residual)
    (hR2 :
      (‖A‖ + ‖A.transpose‖) / 2 ≤ r2Rate)
    (hcutoff : ∀ᵐ x ∂matrixGaussianPi R,
      cutoffEnergy x ≤ ∑ i ∈ S, x i ^ 2)
    (hgamma : 0 ≤ gamma)
    (hbudget : potentialRate + r2Rate + gamma ≤ alpha) :
    ∀ᵐ x ∂matrixGaussianPi R,
      (cmp116Eq214ComplexQuadratic A x + potential x).re +
          gamma / 2 * cutoffEnergy x ≤
        alpha / 2 * (∑ i ∈ S, x i ^ 2) + residual := by
  filter_upwards [hroot.ae_supported, hpotential, hcutoff] with x hx hp hc
  exact cmp116Eq220_eq221_eq222_complexInteraction_le_localized
    A x (potential x) (∑ i ∈ S, x i ^ 2) (cutoffEnergy x)
    potentialRate r2Rate gamma alpha residual hp hR2
    hx.sum_sq_eq_sum_mem hc hgamma hbudget

end

end YangMills.RG
