/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80PhysicalFineHeadTailSourceMetricDecay
import YangMills.RG.BalabanCMP116Eq136To220

/-!
# Scalar compatibility of the CMP102 walk ratio with the CMP116 residual rate

The source-metric random-walk bounds split one physical walk ratio into
cardinality decay, tree-metric decay and a residual summation ratio.  The
split was previously supplied as three auxiliary numbers.  Here it is made
canonical: the first two factors are the exact exponentials required by the
chosen rates, and the residual factor is forced by equality.

For the CMP116 residual estimate the metric rate is fixed to
`(1 - 2 * delta) * kappa`.  Consequently the whole scalar compatibility
condition is the single displayed inequality

`branching * physicalRatio *
    exp ((kappaCard + (1 - 2 * delta) * kappa) * 10000) < 1`.

The ratios here are per walk-budget unit.  The constant `10000` is the
proved upper bound on the physical cardinality/tree-metric cost contributed
by one such unit (including the fixed anchor), so the hypothesis
`ratio ≤ exp (-rate * 10000)` is the per-unit condition that yields decay at
rate `rate` in the accumulated physical measure.  It is not an aggregated
ratio and is not used as a substitute for the domain metric: the resulting
source estimate still contains
`exp (-kappaMetric * treeMetric Y)`.
-/

namespace YangMills.RG

noncomputable section

/-- Exact cardinality-decay share of the physical walk ratio. -/
noncomputable def cmp102Eq80CanonicalCardRatio (kappaCard : ℝ) : ℝ :=
  Real.exp (-(kappaCard * 10000))

/-- Exact tree-metric-decay share of the physical walk ratio. -/
noncomputable def cmp102Eq80CanonicalMetricRatio (kappaMetric : ℝ) : ℝ :=
  Real.exp (-(kappaMetric * 10000))

/-- Residual summation share forced by the two selected decay rates. -/
noncomputable def cmp102Eq80CanonicalSummationRatio
    (physicalRatio kappaCard kappaMetric : ℝ) : ℝ :=
  physicalRatio * Real.exp ((kappaCard + kappaMetric) * 10000)

/-- The canonical shares multiply back to the physical ratio exactly. -/
theorem cmp102Eq80CanonicalRatio_mul_eq
    (physicalRatio kappaCard kappaMetric : ℝ) :
    cmp102Eq80CanonicalCardRatio kappaCard *
        (cmp102Eq80CanonicalMetricRatio kappaMetric *
          cmp102Eq80CanonicalSummationRatio
            physicalRatio kappaCard kappaMetric) =
      physicalRatio := by
  unfold cmp102Eq80CanonicalCardRatio
    cmp102Eq80CanonicalMetricRatio
    cmp102Eq80CanonicalSummationRatio
  calc
    Real.exp (-(kappaCard * 10000)) *
          (Real.exp (-(kappaMetric * 10000)) *
            (physicalRatio *
              Real.exp ((kappaCard + kappaMetric) * 10000))) =
        physicalRatio *
          ((Real.exp (-(kappaCard * 10000)) *
            Real.exp (-(kappaMetric * 10000))) *
            Real.exp ((kappaCard + kappaMetric) * 10000)) := by ring
    _ = physicalRatio *
          Real.exp
            (-(kappaCard * 10000) + -(kappaMetric * 10000) +
              (kappaCard + kappaMetric) * 10000) := by
      rw [Real.exp_add, Real.exp_add]
    _ = physicalRatio := by
      ring_nf
      simp

/-- All nonnegativity and decay obligations of the source-metric split are
generated by the canonical choice; only smallness of the residual summation
share remains quantitative. -/
theorem cmp102Eq80CanonicalRatioCertificate
    {physicalRatio kappaCard kappaMetric : ℝ}
    (hphysical : 0 ≤ physicalRatio) :
    0 ≤ cmp102Eq80CanonicalCardRatio kappaCard ∧
    0 ≤ cmp102Eq80CanonicalMetricRatio kappaMetric ∧
    0 ≤ cmp102Eq80CanonicalSummationRatio
      physicalRatio kappaCard kappaMetric ∧
    physicalRatio ≤
      cmp102Eq80CanonicalCardRatio kappaCard *
        (cmp102Eq80CanonicalMetricRatio kappaMetric *
          cmp102Eq80CanonicalSummationRatio
            physicalRatio kappaCard kappaMetric) ∧
    cmp102Eq80CanonicalCardRatio kappaCard ≤
      Real.exp (-(kappaCard * 10000)) ∧
    cmp102Eq80CanonicalMetricRatio kappaMetric ≤
      Real.exp (-(kappaMetric * 10000)) := by
  refine ⟨Real.exp_nonneg _, Real.exp_nonneg _, ?_, ?_, le_rfl, le_rfl⟩
  · exact mul_nonneg hphysical (Real.exp_nonneg _)
  · rw [cmp102Eq80CanonicalRatio_mul_eq]

/-- The exact metric rate required by the CMP116 residual majorant (1.36). -/
noncomputable def cmp102Eq80Eq220MetricRate
    (delta kappa : ℝ) : ℝ :=
  (1 - 2 * delta) * kappa

/-- Canonical residual ratio after installing the exact (1.36) metric rate. -/
noncomputable def cmp102Eq80Eq220SummationRatio
    (physicalRatio kappaCard delta kappa : ℝ) : ℝ :=
  cmp102Eq80CanonicalSummationRatio physicalRatio kappaCard
    (cmp102Eq80Eq220MetricRate delta kappa)

/-- The unique remaining scalar compatibility condition between the literal
CMP102 walk ratio and the CMP116 residual decay.  Its conclusion is precisely
the branching smallness premise consumed by the source-metric summation. -/
theorem cmp102Eq80Eq220_branching_small_of_budget
    {physicalRatio kappaCard delta kappa : ℝ}
    (branching : ℝ)
    (hbudget :
      branching * physicalRatio *
          Real.exp
            ((kappaCard + (1 - 2 * delta) * kappa) * 10000) < 1) :
    branching *
        cmp102Eq80Eq220SummationRatio
          physicalRatio kappaCard delta kappa < 1 := by
  simpa [
    cmp102Eq80Eq220SummationRatio,
    cmp102Eq80CanonicalSummationRatio,
    cmp102Eq80Eq220MetricRate,
    mul_assoc] using hbudget

/-- Logarithmic form of the exact decay budget.  This theorem makes explicit
that increasing the requested rate makes the physical ratio obligation
strictly stronger. -/
theorem ratio_le_exp_neg_rate_mul_10000_iff
    {ratio rate : ℝ} (hratio : 0 < ratio) :
    ratio ≤ Real.exp (-(rate * 10000)) ↔
      rate ≤ -(Real.log ratio) / 10000 := by
  rw [← Real.log_le_iff_le_exp hratio]
  constructor <;> intro h
  · nlinarith
  · nlinarith

/-- Specialization of the logarithmic budget to the metric rate appearing
in (1.36). -/
theorem cmp102Eq80Eq220_metric_decay_iff
    {metricRatio delta kappa : ℝ} (hratio : 0 < metricRatio) :
    metricRatio ≤
        Real.exp (-((cmp102Eq80Eq220MetricRate delta kappa) * 10000)) ↔
      (1 - 2 * delta) * kappa ≤
        -(Real.log metricRatio) / 10000 := by
  simpa [cmp102Eq80Eq220MetricRate] using
    (ratio_le_exp_neg_rate_mul_10000_iff
      (ratio := metricRatio)
      (rate := (1 - 2 * delta) * kappa) hratio)

end

end YangMills.RG
