import YangMills.RG.BalabanCMP99SourceRegionalCoarseCovarianceTelescope

open YangMills.RG

#print axioms continuousLinearMap_rectangular_telescope
#print axioms cmp99OmegaCoarseDirectRestriction_self
#print axioms cmp99OmegaCoarseDirectRestriction_comp
#print axioms cmp99OmegaCoarseDirectRestriction_apply
#print axioms cmp99OmegaCoarseDirectRestriction_single_of_mem
#print axioms cmp99OmegaCoarseDirectRestriction_single_of_not_mem
#print axioms cmp99OmegaCoarseDirectRestriction_transition
#print axioms cmp99OmegaEmbeddedCoarseCovariance_apply_single_of_mem
#print axioms cmp99OmegaEmbeddedCoarseCovariance_apply_single_of_not_mem
#print axioms cmp99OmegaEmbeddedCoarseCovariance_exponentialKernelBound
#print axioms cmp99OmegaEmbeddedCoarseCovarianceTransition_apply_single_of_mem
#print axioms cmp99OmegaEmbeddedCoarseCovarianceTransition_apply_single_of_not_mem
#print axioms cmp99OmegaEmbeddedCoarseCovarianceTransition_exponentialKernelBound
#print axioms cmp99OmegaEmbeddedCoarseCovarianceTransition_eq_sub
#print axioms cmp99OmegaEmbeddedCoarseCovarianceTransition_eq_nat_sub
#print axioms cmp99OmegaEmbeddedCoarseCovarianceNat_endpoints
#print axioms sum_cmp99OmegaEmbeddedCoarseCovarianceTransition_eq_total
#print axioms cmp99OmegaTotalCoarseCovarianceTransition_exponentialKernelBound_sum
#print axioms cmp99OmegaTotalCoarseCovarianceTransition_exponentialKernelBound
