import YangMills.RG.BalabanCMP89Eq249UniformNoncentralComplexRadius

#print axioms YangMills.RG.cmp89Eq249NoncentralComplexGapBudget_le_of_uniformRadiusCondition
#print axioms YangMills.RG.half_momentum_gap_le_norm_cmp89Eq245EntireScaledLaplacianSymbol_of_uniformRadius
