import YangMills.RG.BalabanCMP99SourceGeneratedSmoothGreenCommutator

open YangMills.RG

#print axioms cmp99SourceGeneratedSmoothCutoffScale
#print axioms cmp99SourceGeneratedSmoothCutoffScale_pos
#print axioms cmp99SourceGeneratedSmoothCutoffCenter
#print axioms cmp99SourceGeneratedSmoothCutoffCenter_val
#print axioms finTorusDistanceCoordinates
#print axioms norm_finTorusDistanceCoordinates_sub_le
#print axioms sum_norm_finTorusDistanceCoordinates_sub_le_four_finBoxDist
#print axioms cmp99SourceGeneratedPhysicalGreenSmoothSquareCommutator
#print axioms cmp99SourceGeneratedPhysicalGreenSmoothCommutator
#print axioms cmp99SourceGeneratedPhysicalGreenSmoothCommutator_exponential
#print axioms norm_cmp99SourceGeneratedPhysicalGreenSmoothCommutator_le
#print axioms cmp99SourceGeneratedPhysicalGreenSmoothSquareCommutator_exponential
#print axioms norm_cmp99SourceGeneratedPhysicalGreenSmoothSquareCommutator_le
#print axioms cmp99SourceGeneratedPhysicalGreenSmoothSquareCommutator_exponential_torusDistance
#print axioms norm_cmp99SourceGeneratedPhysicalGreenSmoothSquareCommutator_torusDistance_le
