import YangMills.RG.BalabanCMP99SourceFlatFullComplexPrecisionParticularSolution

/-! Cold-sealed axiom audit for the flat physical particular solution. -/

#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_particularSolution_fixedCoarseFibre
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_particularSolution_eq_zero_of_coarseAlias_ne
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_fourierMode_eq_zero_of_coarseAlias_ne
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_particularSolution_eq_zero_of_coarseAlias_ne
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_particularSolution_fixedCoarseFibre
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionAction_particularSolution
