import YangMills.RG.BalabanCMP99SourceEq395Neumann

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalPatchedCovariance
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrection
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrectedCovariance
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrectedCovariance_eq_tsum_pow
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalMiddle_comp_correctedCovariance_eq_id
