import YangMills.RG.BalabanCMP98Eq123PhysicalProductBound

#print axioms YangMills.RG.norm_cmp98Eq123PhysicalTwoFactorProduct_sub_zero_sub_first_le
#print axioms YangMills.RG.norm_cmp98Eq123PhysicalTwoFactorProductRemainder_le_sourceBudget
