import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedPhysicalLargeBlockCutoff

/-!
# Audit: separated-scale physical CMP99 cutoff
-/

#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoff
#print axioms YangMills.RG.norm_cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoff_sub_le
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockLaplacianBudget
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockMassBudget
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoffNumerator
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoffBudget
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoffBudget_eq
#print axioms YangMills.RG.exists_cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoffBudget_lt_one
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalLargeBlockCutoffBudget_self
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalPrecision_largeBlockCutoff_fixedOutputWeighted
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedPhysicalPrecision_largeBlockCutoff_exponentialKernelBound
