import YangMills.RG.BalabanCMP102Eq80MinimizerTelescoping

#print axioms YangMills.RG.cmp102Eq80MinimizerIncrement
#print axioms YangMills.RG.cmp102Eq80GlobalPotential_add_minimizer
#print axioms YangMills.RG.cmp102Eq80MinimizerIncrement_eq_integral_directionalDerivative
#print axioms YangMills.RG.cmp102Eq80MinimizerPartialSum
#print axioms YangMills.RG.cmp102Eq80MinimizerPartialSum_zero
#print axioms YangMills.RG.cmp102Eq80MinimizerPartialSum_succ
#print axioms YangMills.RG.cmp102Eq80GlobalPotential_partialSum_eq_sum_increments
#print axioms YangMills.RG.continuous_cmp102Eq80GlobalPotential_minimizer
#print axioms YangMills.RG.tendsto_cmp102Eq80GlobalPotential_partialSum_increments
