import YangMills.RG.BalabanCMP99SourceGeneratedPhysicalPrecisionCompression


#print axioms YangMills.RG.cmp99NestedActiveRegionExtension_extendZero_eq
#print axioms YangMills.RG.cmp99ActiveRegionSourceCovariantLaplacian_nested_compression_eq
#print axioms YangMills.RG.CMP99SourceNestedRegionChains.sourceGaugePrecision_compression
