import YangMills.RG.BalabanCMP99Eq359TowerRealSliceAgreement

#print axioms YangMills.RG.CMP99Eq359TowerRealSliceAgreement
#print axioms YangMills.RG.CMP99Eq359TowerRealSliceAgreement.stop
#print axioms YangMills.RG.CMP99Eq359TowerRealSliceAgreement.step
