import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothBasicFactor

open YangMills.RG

#print axioms cmp99SourceGeneratedSmoothGreenLinearCommutatorNormBound
#print axioms cmp99SourceGeneratedSmoothFineBasicFactorNormBound
#print axioms cmp99SourceGeneratedSmoothBasicAdjointFactorNormBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothFineSectionCBasicFactor
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothFineSectionCBasicFactor_eq_source
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedCMP95SourceCenteredSmoothFineSectionCBasicFactor_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothSectionCBasicAdjointFactor
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothSectionCBasicAdjointFactor_eq_source
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedCMP95SourceCenteredSmoothSectionCBasicAdjointFactor_le
