import YangMills.RG.BalabanCMP102Eq80SourcePi4FaaDiBrunoPhysicalInnerJet

#print axioms YangMills.RG.cmp116CoordinateFiniteDifference_sourcePi4FullRealMixedCovariance_eq_insert
#print axioms YangMills.RG.cmp116IteratedCoordinateFiniteDifference_sourcePi4FullRealMixedCovariance_eq_carrier
#print axioms YangMills.RG.fderiv_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealMixedCovariance_apply_single
#print axioms YangMills.RG.ftaylorSeries_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealMixedCovariance_one_apply_single
#print axioms YangMills.RG.ftaylorSeries_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealCovariance_apply_coordinateBlock
#print axioms YangMills.RG.ftaylorSeries_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealCovariance_apply_coordinateBlock_at
