import YangMills.RG.BalabanCMP116WeakenedRandomWalkSeries

/-!
# CMP99 equations (3.107)--(3.108): untyped generalized-walk skeleton

Balaban's generalized random walk has a distinguished initial pair `(0, X₀)`
followed by an ordered list `((α₁, X₁), ..., (αₙ, Xₙ))`, with consecutive
localization domains intersecting.  The displayed notation for the
corresponding operator term is the product

`R₀(X₀) R_{α₁}(X₁) ... R_{αₙ}(Xₙ)`.

CMP116 weakens this term by every coarse cube meeting the union of the
localization domains (with the source-specific thickening absorbed in the map
`domainActive`).  A single domain may activate several cubes, so the active
carrier is a union, not the image of one cube per step.

CMP99 printed page 413 also states that the factors generally act between
different scales and that not every sequence of labels is type-correct; the
paper suppresses this typing in the displayed sum because it does not affect
the estimates.  Thus this module records the untyped combinatorial skeleton,
not the complete physical operator alphabet.  The dependent carrier version
lives in `DependentArrowWalk` and the Section-C typed modules.

This module closes the structural and bounded-branching part of that skeleton:

* the distinguished head, labelled tail, overlap chain, and a common-monoid
  model of the ordered product;
* the exact active union and the bound `card active ≤ B * (length + 1)`;
* the finite family of admissible tails of a fixed length generated by a
  finite successor family;
* the uniform count `card tails ≤ K ^ n` from a branching bound `K`.

Honest scope: the concrete simple localization domains, the complete successor
family from Sect. C of CMP99, the heterogeneous ordered operators `R₀`, `R_α`,
and the geometric kernel estimate (3.108) are not constructed here.  In
particular, the analytic decay is not stored as a field of the walk structure,
and no common ambient carrier is asserted.
-/

namespace YangMills.RG

universe u v w z

/-- One labelled continuation `(α, X)` of a CMP99 generalized random walk. -/
structure CMP99WalkStep (Label : Type u) (Domain : Type v) where
  label : Label
  domain : Domain
  deriving DecidableEq

/-- The raw source shape `((0,X₀),(α₁,X₁),...,(αₙ,Xₙ))`.  Admissibility is a
separate predicate so list induction does not carry proof fields. -/
structure CMP99GeneralizedWalk (Label : Type u) (Domain : Type v) where
  head : Domain
  tail : List (CMP99WalkStep Label Domain)
  deriving DecidableEq

namespace CMP99GeneralizedWalk

variable {Label : Type u} {Domain : Type v} {Cube : Type w} {E : Type z}

/-- The source convention `|ω| = n`: the distinguished head is not counted. -/
def length (walk : CMP99GeneralizedWalk Label Domain) : ℕ :=
  walk.tail.length

/-- The ordered list `X₀, X₁, ..., Xₙ` of localization domains. -/
def domains (walk : CMP99GeneralizedWalk Label Domain) : List Domain :=
  walk.head :: walk.tail.map CMP99WalkStep.domain

@[simp]
theorem length_domains (walk : CMP99GeneralizedWalk Label Domain) :
    walk.domains.length = walk.length + 1 := by
  simp [domains, length]

/-- Consecutive source domains intersect (or satisfy a supplied replacement
relation). -/
def IsAdmissible (meets : Domain → Domain → Prop)
    (walk : CMP99GeneralizedWalk Label Domain) : Prop :=
  (walk.domains).IsChain meets

/-- Common-monoid model of the ordered, generally noncommutative notation in
(3.107).  It is literal only after a common carrier has separately been
justified; the physical Section-C factors are generally heterogeneous. -/
def term [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) : E :=
  (R0 walk.head :: walk.tail.map (fun step => R step.label step.domain)).prod

/-- The ordered list of operator factors whose product is the source walk
term. -/
def factors
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) : List E :=
  R0 walk.head :: walk.tail.map (fun step => R step.label step.domain)

@[simp] theorem term_eq_prod_factors [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) :
    walk.term R0 R = (walk.factors R0 R).prod := rfl

@[simp] theorem length_factors
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) :
    (walk.factors R0 R).length = walk.domains.length := by
  simp [factors, domains]

/-- The literal operator factor at an index of the ordered domain list.  The
cast changes only the length proof: the underlying natural-number position is
definitionally unchanged. -/
def factorAt
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain)
    (i : Fin walk.domains.length) : E :=
  (walk.factors R0 R).get
    (i.cast (walk.length_factors R0 R).symm)

/-- Any property enjoyed by every head and continuation factor is enjoyed by
the factor at the matching ordered domain occurrence. -/
theorem factorAt_property
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain)
    (P : Domain → E → Prop)
    (h0 : ∀ X, P X (R0 X))
    (hR : ∀ label X, P X (R label X))
    (i : Fin walk.domains.length) :
    P (walk.domains.get i) (walk.factorAt R0 R i) := by
  rcases i with ⟨i, hi⟩
  cases i with
  | zero =>
      simpa [domains, factorAt, factors] using h0 walk.head
  | succ j =>
      have hj : j < walk.tail.length := by
        simpa [domains] using hi
      simpa [domains, factorAt, factors] using
        hR (walk.tail.get ⟨j, hj⟩).label
          (walk.tail.get ⟨j, hj⟩).domain

/-- Split the noncommutative source term at any literal factor occurrence. -/
theorem term_eq_prod_take_mul_get_mul_prod_drop [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain)
    (i : Fin (walk.factors R0 R).length) :
    walk.term R0 R =
      ((walk.factors R0 R).take i).prod *
        (walk.factors R0 R).get i *
        ((walk.factors R0 R).drop (i + 1)).prod := by
  rw [term_eq_prod_factors]
  have htake :=
    List.prod_take_succ (walk.factors R0 R) i i.isLt
  have hsplit :=
    List.prod_take_mul_prod_drop (walk.factors R0 R) (i + 1)
  rw [htake] at hsplit
  exact hsplit.symm

@[simp]
theorem term_nil [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E) (X0 : Domain) :
    term R0 R ⟨X0, []⟩ = R0 X0 := by
  simp [term]

@[simp]
theorem term_cons [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E)
    (X0 : Domain) (step : CMP99WalkStep Label Domain)
    (tail : List (CMP99WalkStep Label Domain)) :
    term R0 R ⟨X0, step :: tail⟩ =
      R0 X0 * (R step.label step.domain ::
        tail.map (fun next => R next.label next.domain)).prod := by
  simp [term]

section Active

variable [DecidableEq Cube]

/-- Membership in a folded union is witnessed by one member of the source
list. -/
private theorem mem_foldr_union_map_iff
    (domainActive : Domain → Finset Cube) (d : Cube) :
    ∀ domains : List Domain,
      d ∈ (domains.map domainActive).foldr (· ∪ ·) ∅ ↔
        ∃ X ∈ domains, d ∈ domainActive X := by
  intro domains
  induction domains with
  | nil => simp
  | cons X rest ih =>
      simp [ih]

/-- Union of all weakening cubes meeting the source localization domains. -/
def active (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) : Finset Cube :=
  (walk.domains.map domainActive).foldr (· ∪ ·) ∅

/-- A weakening cube is active exactly when one domain in the ordered walk
activates it. -/
theorem mem_active_iff_exists_domain
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube) :
    d ∈ walk.active domainActive ↔
      ∃ X ∈ walk.domains, d ∈ domainActive X := by
  exact mem_foldr_union_map_iff domainActive d walk.domains

/-- Indexed form of `mem_active_iff_exists_domain`, suited to splitting the
ordered operator product at a physically active domain. -/
theorem mem_active_iff_exists_get
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube) :
    d ∈ walk.active domainActive ↔
      ∃ i : Fin walk.domains.length,
        d ∈ domainActive (walk.domains.get i) := by
  rw [mem_active_iff_exists_domain]
  exact List.exists_mem_iff_get

/-- A canonical (classically selected) occurrence of an active weakening
cube in the ordered domain list.  Later operator factorization may split the
walk at this index without adding an arbitrary domain parameter. -/
noncomputable def activeDomainIndex
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    Fin walk.domains.length :=
  Classical.choose
    ((mem_active_iff_exists_get domainActive walk d).mp hd)

/-- The selected occurrence really activates the requested cube. -/
theorem mem_domainActive_get_activeDomainIndex
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    d ∈ domainActive
      (walk.domains.get (walk.activeDomainIndex domainActive d hd)) :=
  Classical.choose_spec
    ((mem_active_iff_exists_get domainActive walk d).mp hd)

/-- The finite set of ordered domain occurrences which activate a given
weakening cube. -/
def activeDomainIndices
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube) :
    Finset (Fin walk.domains.length) :=
  Finset.univ.filter fun i =>
    d ∈ domainActive (walk.domains.get i)

/-- An active cube has at least one activating domain occurrence. -/
theorem activeDomainIndices_nonempty
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    (walk.activeDomainIndices domainActive d).Nonempty := by
  rcases (walk.mem_active_iff_exists_get domainActive d).mp hd with ⟨i, hi⟩
  exact ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩⟩

/-- The first ordered domain occurrence which activates a weakening cube.
Unlike an arbitrary classical witness, this supports a disjoint first-hit
resummation of walks. -/
noncomputable def firstActiveDomainIndex
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    Fin walk.domains.length :=
  (walk.activeDomainIndices domainActive d).min'
    (walk.activeDomainIndices_nonempty domainActive d hd)

/-- The first selected occurrence really activates the requested cube. -/
theorem mem_domainActive_get_firstActiveDomainIndex
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    d ∈ domainActive
      (walk.domains.get (walk.firstActiveDomainIndex domainActive d hd)) := by
  exact (Finset.mem_filter.mp
    (Finset.min'_mem _ (walk.activeDomainIndices_nonempty
      domainActive d hd))).2

/-- Every activating occurrence lies weakly after the first one. -/
theorem firstActiveDomainIndex_le_of_mem
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive)
    (i : Fin walk.domains.length)
    (hi : d ∈ domainActive (walk.domains.get i)) :
    walk.firstActiveDomainIndex domainActive d hd ≤ i := by
  exact Finset.min'_le _ _ (Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩)

/-- No domain occurrence strictly before the first active occurrence activates
the requested cube. -/
theorem not_mem_domainActive_get_of_lt_firstActiveDomainIndex
    (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive)
    (i : Fin walk.domains.length)
    (hi : i < walk.firstActiveDomainIndex domainActive d hd) :
    d ∉ domainActive (walk.domains.get i) := by
  intro himem
  exact (not_le_of_gt hi)
    (walk.firstActiveDomainIndex_le_of_mem domainActive d hd i himem)

/-- The literal operator factor at the selected active domain occurrence. -/
noncomputable def activeFactor
    (domainActive : Domain → Finset Cube)
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) : E :=
  walk.factorAt R0 R (walk.activeDomainIndex domainActive d hd)

/-- The selected factor inherits every factorwise property at a domain which
activates the requested weakening cube. -/
theorem activeFactor_property
    (domainActive : Domain → Finset Cube)
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive)
    (P : Domain → E → Prop)
    (h0 : ∀ X, P X (R0 X))
    (hR : ∀ label X, P X (R label X)) :
    P
      (walk.domains.get (walk.activeDomainIndex domainActive d hd))
      (walk.activeFactor domainActive R0 R d hd) := by
  exact walk.factorAt_property R0 R P h0 hR
    (walk.activeDomainIndex domainActive d hd)

/-- Split the noncommutative walk term at the selected active factor. -/
theorem term_eq_prefix_mul_activeFactor_mul_suffix [Monoid E]
    (domainActive : Domain → Finset Cube)
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    walk.term R0 R =
      ((walk.factors R0 R).take
        (walk.activeDomainIndex domainActive d hd)).prod *
      walk.activeFactor domainActive R0 R d hd *
      ((walk.factors R0 R).drop
        (walk.activeDomainIndex domainActive d hd + 1)).prod := by
  simpa [activeFactor, factorAt] using
    walk.term_eq_prod_take_mul_get_mul_prod_drop R0 R
      ((walk.activeDomainIndex domainActive d hd).cast
        (walk.length_factors R0 R).symm)

/-- The literal operator factor at the first active domain occurrence. -/
noncomputable def firstActiveFactor
    (domainActive : Domain → Finset Cube)
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) : E :=
  walk.factorAt R0 R (walk.firstActiveDomainIndex domainActive d hd)

/-- Split the noncommutative walk term at its first active factor. -/
theorem term_eq_prefix_mul_firstActiveFactor_mul_suffix [Monoid E]
    (domainActive : Domain → Finset Cube)
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) (d : Cube)
    (hd : d ∈ walk.active domainActive) :
    walk.term R0 R =
      ((walk.factors R0 R).take
        (walk.firstActiveDomainIndex domainActive d hd)).prod *
      walk.firstActiveFactor domainActive R0 R d hd *
      ((walk.factors R0 R).drop
        (walk.firstActiveDomainIndex domainActive d hd + 1)).prod := by
  simpa [firstActiveFactor, factorAt] using
    walk.term_eq_prod_take_mul_get_mul_prod_drop R0 R
      ((walk.firstActiveDomainIndex domainActive d hd).cast
        (walk.length_factors R0 R).symm)

private theorem card_foldr_union_le_mul_length
    (domainActive : Domain → Finset Cube) (B : ℕ)
    (hB : ∀ X, (domainActive X).card ≤ B) :
    ∀ domains : List Domain,
      ((domains.map domainActive).foldr (· ∪ ·) ∅).card ≤
        B * domains.length := by
  intro domains
  induction domains with
  | nil => simp
  | cons X rest ih =>
      calc
        ((domainActive X :: rest.map domainActive).foldr (· ∪ ·) ∅).card ≤
            (domainActive X).card +
              ((rest.map domainActive).foldr (· ∪ ·) ∅).card :=
          Finset.card_union_le _ _
        _ ≤ B + B * rest.length := Nat.add_le_add (hB X) ih
        _ = B * (X :: rest).length := by
          simp [Nat.mul_add, Nat.add_comm]

/-- If every source domain activates at most `B` weakening cubes, a walk of
source length `n` activates at most `B(n+1)` cubes. -/
theorem card_active_le_mul_length_add_one
    (domainActive : Domain → Finset Cube) (B : ℕ)
    (hB : ∀ X, (domainActive X).card ≤ B)
    (walk : CMP99GeneralizedWalk Label Domain) :
    (walk.active domainActive).card ≤ B * (walk.length + 1) := by
  simpa [active, length_domains] using
    card_foldr_union_le_mul_length domainActive B hB walk.domains

end Active

section ActiveCore

variable {Bond : Type*}
variable [Fintype Domain] [DecidableEq Domain]
variable [DecidableEq Cube] [DecidableEq Bond]

/-- Domains whose weakening carrier meets a fixed finite contour carrier. -/
def contourRelevantDomains
    (domainActive : Domain → Finset Cube) (carrier : Finset Cube) :
    Finset Domain :=
  Finset.univ.filter fun X => ¬ Disjoint (domainActive X) carrier

/-- The single finite physical core obtained by joining all domains which
meet a fixed contour carrier. -/
def contourActiveCore
    (core : Domain → Finset Bond)
    (domainActive : Domain → Finset Cube) (carrier : Finset Cube) :
    Finset Bond :=
  (contourRelevantDomains domainActive carrier).biUnion core

/-- A domain which activates one cube of the contour has its complete core in
the common contour-active core. -/
theorem core_subset_contourActiveCore_of_mem
    (core : Domain → Finset Bond)
    (domainActive : Domain → Finset Cube) (carrier : Finset Cube)
    (X : Domain) (d : Cube)
    (hdomain : d ∈ domainActive X) (hcarrier : d ∈ carrier) :
    core X ⊆ contourActiveCore core domainActive carrier := by
  have hdisjoint : ¬ Disjoint (domainActive X) carrier := by
    intro h
    exact (Finset.disjoint_left.mp h) hdomain hcarrier
  have hX : X ∈ contourRelevantDomains domainActive carrier :=
    Finset.mem_filter.mpr ⟨Finset.mem_univ X, hdisjoint⟩
  intro b hb
  exact Finset.mem_biUnion.mpr ⟨X, hX, hb⟩

end ActiveCore

end CMP99GeneralizedWalk

section BoundedBranching

variable {Label : Type u} {Domain : Type v}
variable [DecidableEq Label] [DecidableEq Domain]

/-- All admissible labelled tails of exactly `n` steps starting at `X`.
The finite family `successors X` is the explicit local branching data. -/
def cmp99AdmissibleTails
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (X : Domain) : ℕ → Finset (List (CMP99WalkStep Label Domain))
  | 0 => {[]}
  | n + 1 =>
      (successors X).biUnion fun step =>
        (cmp99AdmissibleTails successors step.domain n).image (step :: ·)

/-- Membership fixes the source length exactly. -/
theorem length_eq_of_mem_cmp99AdmissibleTails
    (successors : Domain → Finset (CMP99WalkStep Label Domain)) :
    ∀ {n X tail}, tail ∈ cmp99AdmissibleTails successors X n →
      tail.length = n := by
  intro n
  induction n with
  | zero =>
      intro X tail htail
      simpa [cmp99AdmissibleTails] using congrArg List.length
        (Finset.mem_singleton.mp htail)
  | succ n ih =>
      intro X tail htail
      simp only [cmp99AdmissibleTails, Finset.mem_biUnion,
        Finset.mem_image] at htail
      obtain ⟨step, _hstep, rest, hrest, rfl⟩ := htail
      simp [ih hrest]

/-- The generated tails satisfy the consecutive-overlap predicate whenever
each declared successor overlaps its source domain. -/
theorem chain_of_mem_cmp99AdmissibleTails
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (meets : Domain → Domain → Prop)
    (hsucc : ∀ X step, step ∈ successors X → meets X step.domain) :
    ∀ {n X tail}, tail ∈ cmp99AdmissibleTails successors X n →
      (X :: tail.map CMP99WalkStep.domain).IsChain meets := by
  intro n
  induction n with
  | zero =>
      intro X tail htail
      have hnil : tail = [] := Finset.mem_singleton.mp
        (by simpa [cmp99AdmissibleTails] using htail)
      subst hnil
      simp
  | succ n ih =>
      intro X tail htail
      simp only [cmp99AdmissibleTails, Finset.mem_biUnion,
        Finset.mem_image] at htail
      obtain ⟨step, hstep, rest, hrest, rfl⟩ := htail
      exact List.IsChain.cons_cons (hsucc X step hstep) (ih hrest)

/-- A uniform branching bound gives the source-faithful `K^n` walk count,
independent of the total number of localization domains in the volume. -/
theorem card_cmp99AdmissibleTails_le_pow
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (K : ℕ) (hK : ∀ X, (successors X).card ≤ K) :
    ∀ (n : ℕ) (X : Domain),
      (cmp99AdmissibleTails successors X n).card ≤ K ^ n := by
  intro n
  induction n with
  | zero =>
      intro X
      simp [cmp99AdmissibleTails]
  | succ n ih =>
      intro X
      calc
        (cmp99AdmissibleTails successors X (n + 1)).card =
            ((successors X).biUnion fun step =>
              (cmp99AdmissibleTails successors step.domain n).image
                (step :: ·)).card := rfl
        _ ≤ ∑ step ∈ successors X,
              ((cmp99AdmissibleTails successors step.domain n).image
                (step :: ·)).card := Finset.card_biUnion_le
        _ ≤ ∑ _step ∈ successors X, K ^ n := by
          gcongr with step hstep
          rw [Finset.card_image_of_injective]
          · exact ih step.domain
          · intro a b hab
            exact (List.cons.inj hab).2
        _ = (successors X).card * K ^ n := by simp
        _ ≤ K * K ^ n := Nat.mul_le_mul_right (K ^ n) (hK X)
        _ = K ^ (n + 1) := by simp [pow_succ, Nat.mul_comm]

/-- The countable anchored walk index generated by a finite successor family. -/
abbrev CMP99AnchoredWalk
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (X0 : Domain) :=
  Σ n : ℕ, ↥(cmp99AdmissibleTails successors X0 n)

/-- Forget the generation certificate and recover the literal source walk. -/
def CMP99AnchoredWalk.toGeneralizedWalk
    {successors : Domain → Finset (CMP99WalkStep Label Domain)}
    {X0 : Domain} (walk : CMP99AnchoredWalk successors X0) :
    CMP99GeneralizedWalk Label Domain :=
  ⟨X0, walk.2.1⟩

@[simp]
theorem CMP99AnchoredWalk.toGeneralizedWalk_length
    {successors : Domain → Finset (CMP99WalkStep Label Domain)}
    {X0 : Domain} (walk : CMP99AnchoredWalk successors X0) :
    walk.toGeneralizedWalk.length = walk.1 := by
  exact length_eq_of_mem_cmp99AdmissibleTails successors walk.2.2

end BoundedBranching

end YangMills.RG
