import YangMills.RG.BalabanCMP116SourceRestrictedContourDensityTraceBound

#print axioms YangMills.RG.norm_cmp116SourceRestrictedContour_logDetDensity_le_exp_half_trace
#print axioms YangMills.RG.norm_cmp116SourceRestrictedContour_logDetDensity_le_exp_traceBudget
#print axioms YangMills.RG.cmp116SourceRestrictedContourDeterminantPerCarrierCost
#print axioms YangMills.RG.norm_cmp116SourceRestrictedContour_logDetDensity_le_exp_detCost_card
#print axioms YangMills.RG.norm_cmp116SourceRestrictedContour_logDetDensity_le_exp_detCost_card_physicalGap
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_restricted_outerWeight_le_exp_half_trace_mul_of_r1
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_restricted_outerWeight_le_exp_traceBudget_mul_of_r1
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_restricted_outerWeight_le_exp_detCost_card_mul_of_r1
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_restricted_outerWeight_le_exp_detCost_card_physicalGap_of_pi4_mem
