import YangMills.RG.BalabanCMP89Eq246FineToFineGreenProductContourTelescope

/-! Axiom audit for the four-coordinate CMP89 (2.46) contour telescope. -/

#print axioms YangMills.RG.cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand
#print axioms YangMills.RG.integrable_cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand
#print axioms YangMills.RG.integral_cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand_stage_succ
#print axioms YangMills.RG.integral_cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand_zero_eq_four
#print axioms YangMills.RG.integral_cmp89Eq246PhysicalFineToFineGreenIntegrand_eq_signed
