import YangMills.RG.BalabanCMP116Eq226PhysicalContourResidualLedger

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_term_le_eq226DomainGap_of_outerInteractionEnergy_cutoff
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_term_le_eq226SourceTermWeight_of_outerInteractionEnergy_residualLedger
