import YangMills.RG.BalabanCMP99Eq335PhysicalRegularityClassLocalizedPrecision



namespace YangMills.RG

#print axioms CMP99Eq335PhysicalRegularityClass.localizedRetainedPhysicalPrecision
#print axioms CMP99Eq335PhysicalRegularityClass.localizedRetainedPhysicalPrecision_eq
#print axioms CMP99Eq335PhysicalRegularityClass.localizedRetainedPhysicalPrecision_eq_canonical
#print axioms CMP99Eq335PhysicalRegularityClass.localizedRetainedPhysicalPrecision_eq_exponentialSource
#print axioms CMP99Eq335PhysicalRegularityClass.localizedRetainedPhysicalPrecision_isSymmetric
#print axioms CMP99Eq335PhysicalRegularityClass.inner_localizedRetainedPhysicalPrecision

end YangMills.RG
