import YangMills.RG.BalabanCMP109PhysicalPivotFlat

#print axioms YangMills.RG.cmp98Eq124EntrancePrefixRightVariation_single_pivot_eq_zero
#print axioms YangMills.RG.cmp98Eq124ExitPrefixRightVariation_single_pivot_eq_zero
#print axioms YangMills.RG.cmp98Eq124_trivial_coarse_average_add_direct_eq_zero
#print axioms YangMills.RG.cmp98Eq124RightPrintedFourLinePhysicalVariation_single_pivot_trivial
#print axioms YangMills.RG.cmp98Eq124RightRawMainLine_trivial_eq_flatBlockConstraint
#print axioms YangMills.RG.cmp98Eq119NonlinearRightVariation_single_pivot_trivial_eq_printed
#print axioms YangMills.RG.cmp109PhysicalLinearConstraint_single_constraintPivot_trivial
#print axioms YangMills.RG.cmp109PhysicalPivotResponseCLM_trivial
#print axioms YangMills.RG.cmp109PhysicalPivotDefectCLM_trivial
#print axioms YangMills.RG.norm_cmp109PhysicalPivotDefectCLM_trivial_lt_one
