/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102AmbientOrientedEdgeFDerivBound
import YangMills.RG.BalabanCMP98UbarLogAverageFDeriv

/-!
# Quantitative ambient derivatives of literal Wilson lines

This module lifts the audited single-edge exponential budgets through the
literal noncommutative ordered product.  It first derives the missing value
and value-Lipschitz estimates for either edge orientation, then constructs
the exact recursive Fréchet derivative of an arbitrary finite contour.

No contour-level value, derivative, or Lipschitz constant is supplied by the
caller.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102AmbientWilsonLineMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- Value budget for one oriented link on the ambient radius-`r` ball. -/
def cmp102AmbientEdgeValueBudget (r : ℝ) : ℝ :=
  1 + expSecondDerivativeBudget r * r ^ 2 +
    expDerivativeBudget r * r

/-- Value-Lipschitz budget for one oriented link on the radius-`r` ball. -/
def cmp102AmbientEdgeValueLipschitzBudget (r : ℝ) : ℝ :=
  2 * r * expSecondDerivativeBudget r + expDerivativeBudget r

theorem cmp102AmbientEdgeValueBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    0 ≤ cmp102AmbientEdgeValueBudget r := by
  unfold cmp102AmbientEdgeValueBudget
  have hB₂ : 0 ≤ expSecondDerivativeBudget r :=
    expSecondDerivativeBudget_nonneg r hr
  have hB₁ : 0 ≤ expDerivativeBudget r :=
    expDerivativeBudget_nonneg r hr
  positivity

theorem cmp102AmbientEdgeValueLipschitzBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    0 ≤ cmp102AmbientEdgeValueLipschitzBudget r := by
  unfold cmp102AmbientEdgeValueLipschitzBudget
  have hB₂ : 0 ≤ expSecondDerivativeBudget r :=
    expSecondDerivativeBudget_nonneg r hr
  have hB₁ : 0 ≤ expDerivativeBudget r :=
    expDerivativeBudget_nonneg r hr
  positivity

/-- The value of either oriented edge is generated by the exponential
budget; reverse orientation costs nothing because conjugate transpose is
an isometry for the matrix operator norm. -/
theorem norm_ambientOrientedEdgeMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (e : ConcreteEdge d (M * N')) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖ambientOrientedEdgeMatrix U Z e‖ ≤
      cmp102AmbientEdgeValueBudget r := by
  have hExp :
      ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ ≤
        cmp102AmbientEdgeValueBudget r := by
    simpa only [cmp102AmbientEdgeValueBudget] using
      (norm_exp_le_derivativeBudgets hr hZ)
  cases h : e.sign
  · rw [ambientOrientedEdgeMatrix, h]
    simp only [Bool.false_eq_true, if_false,
      Matrix.l2_opNorm_conjTranspose]
    unfold ambientPositiveBondMatrix physicalMatrixExp
    calc
      ‖NormedSpace.exp (Z (physicalBondOfEdge e)) *
          (U (positiveEdgeOfPhysicalBond
            (physicalBondOfEdge e))).val‖
          ≤ ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ *
              ‖orientedWilsonPositiveBase U e‖ := norm_mul_le _ _
      _ = ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ := by
        rw [norm_orientedWilsonPositiveBase, mul_one]
      _ ≤ cmp102AmbientEdgeValueBudget r := hExp
  · rw [ambientOrientedEdgeMatrix, h]
    simp only [if_true]
    unfold ambientPositiveBondMatrix physicalMatrixExp
    calc
      ‖NormedSpace.exp (Z (physicalBondOfEdge e)) *
          (U (positiveEdgeOfPhysicalBond
            (physicalBondOfEdge e))).val‖
          ≤ ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ *
              ‖orientedWilsonPositiveBase U e‖ := norm_mul_le _ _
      _ = ‖NormedSpace.exp (Z (physicalBondOfEdge e))‖ := by
        rw [norm_orientedWilsonPositiveBase, mul_one]
      _ ≤ cmp102AmbientEdgeValueBudget r := hExp

/-- The displacement of either oriented edge is Lipschitz in the global
ambient product norm.  The quadratic Taylor remainder is linearized only
after using the two radius-`r` hypotheses. -/
theorem norm_ambientOrientedEdgeMatrix_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (e : ConcreteEdge d (M * N')) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ‖Z (physicalBondOfEdge e)‖ ≤ r)
    (hW : ‖W (physicalBondOfEdge e)‖ ≤ r) :
    ‖ambientOrientedEdgeMatrix U Z e -
        ambientOrientedEdgeMatrix U W e‖ ≤
      cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := by
  let b := physicalBondOfEdge e
  let δ := ‖Z b - W b‖
  have hδ0 : 0 ≤ δ := norm_nonneg _
  have hδr : δ ≤ 2 * r := by
    dsimp only [δ]
    calc
      ‖Z b - W b‖ ≤ ‖Z b‖ + ‖W b‖ := norm_sub_le _ _
      _ ≤ r + r := add_le_add hZ hW
      _ = 2 * r := by ring
  have hδglobal : δ ≤ ‖Z - W‖ := by
    dsimp only [δ]
    simpa only [Pi.sub_apply] using
      (norm_physicalAmbientMatrixTangent_apply_le (Z - W) b)
  have hB₂ : 0 ≤ expSecondDerivativeBudget r :=
    expSecondDerivativeBudget_nonneg r hr
  have hB₁ : 0 ≤ expDerivativeBudget r :=
    expDerivativeBudget_nonneg r hr
  have hTaylor :
      ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖ ≤
        cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := by
    calc
      ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖
          ≤ expSecondDerivativeBudget r * δ ^ 2 +
              expDerivativeBudget r * δ := by
        simpa only [δ] using
          (norm_exp_sub_exp_le_derivativeBudgets hr hZ hW)
      _ ≤ expSecondDerivativeBudget r * ((2 * r) * δ) +
              expDerivativeBudget r * δ := by
        gcongr
        nlinarith
      _ = cmp102AmbientEdgeValueLipschitzBudget r * δ := by
        unfold cmp102AmbientEdgeValueLipschitzBudget
        ring
      _ ≤ cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ :=
        mul_le_mul_of_nonneg_left hδglobal
          (cmp102AmbientEdgeValueLipschitzBudget_nonneg hr)
  have hPositive :
      ‖ambientPositiveBondMatrix U Z b -
          ambientPositiveBondMatrix U W b‖ ≤
        cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := by
    have hfactor :
        ambientPositiveBondMatrix U Z b -
            ambientPositiveBondMatrix U W b =
          (NormedSpace.exp (Z b) - NormedSpace.exp (W b)) *
            (U (positiveEdgeOfPhysicalBond b)).val := by
      unfold ambientPositiveBondMatrix physicalMatrixExp
      noncomm_ring
    rw [hfactor]
    calc
      ‖(NormedSpace.exp (Z b) - NormedSpace.exp (W b)) *
          (U (positiveEdgeOfPhysicalBond b)).val‖
          ≤ ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖ *
              ‖orientedWilsonPositiveBase U e‖ := norm_mul_le _ _
      _ = ‖NormedSpace.exp (Z b) - NormedSpace.exp (W b)‖ := by
        rw [norm_orientedWilsonPositiveBase, mul_one]
      _ ≤ cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖ := hTaylor
  cases h : e.sign
  · rw [ambientOrientedEdgeMatrix, ambientOrientedEdgeMatrix, h]
    simp only [Bool.false_eq_true, if_false, ← Matrix.conjTranspose_sub,
      Matrix.l2_opNorm_conjTranspose]
    exact hPositive
  · rw [ambientOrientedEdgeMatrix, ambientOrientedEdgeMatrix, h]
    simp only [if_true]
    exact hPositive

/-- Exact recursive Fréchet derivative of a literal ordered Wilson line. -/
def cmp98AmbientWilsonLineDerivative
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z H : PhysicalAmbientMatrixTangent d (M * N') Nc) :
    List (ConcreteEdge d (M * N')) → Matrix (Fin Nc) (Fin Nc) ℂ
  | [] => 0
  | e :: es =>
      cmp102AmbientOrientedEdgeDerivative U Z H e *
          cmp98AmbientWilsonLineMatrix U Z es +
        ambientOrientedEdgeMatrix U Z e *
          cmp98AmbientWilsonLineDerivative U Z H es

/-- The recursive ordered expression is the literal ambient Fréchet
derivative, with no commutation of edge factors. -/
theorem fderiv_cmp98AmbientWilsonLineMatrix_apply
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z H : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) :
    fderiv ℝ (fun W => cmp98AmbientWilsonLineMatrix U W es) Z H =
      cmp98AmbientWilsonLineDerivative U Z H es := by
  induction es with
  | nil =>
      have hconst :
          HasFDerivAt
            (fun _ : PhysicalAmbientMatrixTangent d (M * N') Nc =>
              (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) 0 Z :=
        hasFDerivAt_const (𝕜 := ℝ) (x := Z) (c := (1 :
          Matrix (Fin Nc) (Fin Nc) ℂ))
      have hApply := congrArg
        (fun L : PhysicalAmbientMatrixTangent d (M * N') Nc →L[ℝ]
          Matrix (Fin Nc) (Fin Nc) ℂ => L H) hconst.fderiv
      simpa only [cmp98AmbientWilsonLineMatrix_nil,
        cmp98AmbientWilsonLineDerivative, ContinuousLinearMap.zero_apply]
        using hApply
  | cons e es ih =>
      have hHead :=
        (analyticAt_ambientOrientedEdgeMatrix U Z e).differentiableAt.hasFDerivAt
      have hTail :=
        (analyticAt_cmp98AmbientWilsonLineMatrix U Z es).differentiableAt.hasFDerivAt
      have hEq := (hHead.mul' hTail).fderiv
      have hApply := congrArg
        (fun L : PhysicalAmbientMatrixTangent d (M * N') Nc →L[ℝ]
          Matrix (Fin Nc) (Fin Nc) ℂ => L H) hEq
      change
        fderiv ℝ
            (fun W =>
              ambientOrientedEdgeMatrix U W e *
                cmp98AmbientWilsonLineMatrix U W es) Z H =
          ambientOrientedEdgeMatrix U Z e *
              fderiv ℝ
                (fun W => cmp98AmbientWilsonLineMatrix U W es) Z H +
            fderiv ℝ
                (fun W => ambientOrientedEdgeMatrix U W e) Z H *
              cmp98AmbientWilsonLineMatrix U Z es at hApply
      rw [ih, fderiv_ambientOrientedEdgeMatrix_apply U Z H e] at hApply
      simpa only [cmp98AmbientWilsonLineMatrix_cons,
        cmp98AmbientWilsonLineDerivative, add_comm] using hApply

/-- Recursive value budget for a contour of a given length. -/
def cmp98AmbientWilsonLineValueBudget (r : ℝ) : ℕ → ℝ
  | 0 => 1
  | n + 1 =>
      cmp102AmbientEdgeValueBudget r *
        cmp98AmbientWilsonLineValueBudget r n

/-- The literal contour value is bounded solely from its edge radius. -/
theorem norm_cmp98AmbientWilsonLineMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ∀ e ∈ es, ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖cmp98AmbientWilsonLineMatrix U Z es‖ ≤
      cmp98AmbientWilsonLineValueBudget r es.length := by
  induction es with
  | nil =>
      simp only [cmp98AmbientWilsonLineMatrix_nil, List.length_nil,
        cmp98AmbientWilsonLineValueBudget, norm_one, le_refl]
  | cons e es ih =>
      rw [cmp98AmbientWilsonLineMatrix_cons]
      calc
        ‖ambientOrientedEdgeMatrix U Z e *
            cmp98AmbientWilsonLineMatrix U Z es‖
            ≤ ‖ambientOrientedEdgeMatrix U Z e‖ *
                ‖cmp98AmbientWilsonLineMatrix U Z es‖ := norm_mul_le _ _
        _ ≤ cmp102AmbientEdgeValueBudget r *
              ‖cmp98AmbientWilsonLineMatrix U Z es‖ := by
          exact mul_le_mul_of_nonneg_right
            (norm_ambientOrientedEdgeMatrix_le U Z e hr
              (hZ e (by simp))) (norm_nonneg _)
        _ ≤ cmp102AmbientEdgeValueBudget r *
              cmp98AmbientWilsonLineValueBudget r es.length := by
          exact mul_le_mul_of_nonneg_left
            (ih (fun e he => hZ e (by simp [he])))
            (cmp102AmbientEdgeValueBudget_nonneg hr)
        _ = cmp98AmbientWilsonLineValueBudget r (e :: es).length := by
          simp only [List.length_cons, cmp98AmbientWilsonLineValueBudget]

/-- Recursive value-Lipschitz budget for a contour. -/
def cmp98AmbientWilsonLineValueLipschitzBudget (r : ℝ) : ℕ → ℝ
  | 0 => 0
  | n + 1 =>
      cmp102AmbientEdgeValueLipschitzBudget r *
          cmp98AmbientWilsonLineValueBudget r n +
        cmp102AmbientEdgeValueBudget r *
          cmp98AmbientWilsonLineValueLipschitzBudget r n

/-- Recursive derivative budget for a contour. -/
def cmp98AmbientWilsonLineDerivativeBudget (r : ℝ) : ℕ → ℝ
  | 0 => 0
  | n + 1 =>
      expDerivativeBudget r *
          cmp98AmbientWilsonLineValueBudget r n +
        cmp102AmbientEdgeValueBudget r *
          cmp98AmbientWilsonLineDerivativeBudget r n

/-- Recursive derivative-Lipschitz budget.  Its four summands are exactly
the four ordered terms in the two-field derivative telescope. -/
def cmp98AmbientWilsonLineDerivativeLipschitzBudget (r : ℝ) : ℕ → ℝ
  | 0 => 0
  | n + 1 =>
      expSecondDerivativeBudget r *
          cmp98AmbientWilsonLineValueBudget r n +
        expDerivativeBudget r *
          cmp98AmbientWilsonLineValueLipschitzBudget r n +
        cmp102AmbientEdgeValueLipschitzBudget r *
          cmp98AmbientWilsonLineDerivativeBudget r n +
        cmp102AmbientEdgeValueBudget r *
          cmp98AmbientWilsonLineDerivativeLipschitzBudget r n

theorem cmp98AmbientWilsonLineValueBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    ∀ n, 0 ≤ cmp98AmbientWilsonLineValueBudget r n := by
  intro n
  induction n with
  | zero => simp [cmp98AmbientWilsonLineValueBudget]
  | succ n ih =>
      rw [cmp98AmbientWilsonLineValueBudget]
      exact mul_nonneg (cmp102AmbientEdgeValueBudget_nonneg hr) ih

theorem cmp98AmbientWilsonLineValueLipschitzBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    ∀ n, 0 ≤ cmp98AmbientWilsonLineValueLipschitzBudget r n := by
  intro n
  induction n with
  | zero => simp [cmp98AmbientWilsonLineValueLipschitzBudget]
  | succ n ih =>
      rw [cmp98AmbientWilsonLineValueLipschitzBudget]
      exact add_nonneg
        (mul_nonneg (cmp102AmbientEdgeValueLipschitzBudget_nonneg hr)
          (cmp98AmbientWilsonLineValueBudget_nonneg hr n))
        (mul_nonneg (cmp102AmbientEdgeValueBudget_nonneg hr) ih)

theorem cmp98AmbientWilsonLineDerivativeBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    ∀ n, 0 ≤ cmp98AmbientWilsonLineDerivativeBudget r n := by
  intro n
  induction n with
  | zero => simp [cmp98AmbientWilsonLineDerivativeBudget]
  | succ n ih =>
      rw [cmp98AmbientWilsonLineDerivativeBudget]
      exact add_nonneg
        (mul_nonneg (expDerivativeBudget_nonneg r hr)
          (cmp98AmbientWilsonLineValueBudget_nonneg hr n))
        (mul_nonneg (cmp102AmbientEdgeValueBudget_nonneg hr) ih)

theorem cmp98AmbientWilsonLineDerivativeLipschitzBudget_nonneg
    {r : ℝ} (hr : 0 ≤ r) :
    ∀ n, 0 ≤ cmp98AmbientWilsonLineDerivativeLipschitzBudget r n := by
  intro n
  induction n with
  | zero => simp [cmp98AmbientWilsonLineDerivativeLipschitzBudget]
  | succ n ih =>
      rw [cmp98AmbientWilsonLineDerivativeLipschitzBudget]
      exact add_nonneg
        (add_nonneg
          (add_nonneg
            (mul_nonneg (expSecondDerivativeBudget_nonneg r hr)
              (cmp98AmbientWilsonLineValueBudget_nonneg hr n))
            (mul_nonneg (expDerivativeBudget_nonneg r hr)
              (cmp98AmbientWilsonLineValueLipschitzBudget_nonneg hr n)))
          (mul_nonneg (cmp102AmbientEdgeValueLipschitzBudget_nonneg hr)
            (cmp98AmbientWilsonLineDerivativeBudget_nonneg hr n)))
        (mul_nonneg (cmp102AmbientEdgeValueBudget_nonneg hr) ih)

/-- Two-field value telescope for a literal ordered contour. -/
theorem norm_cmp98AmbientWilsonLineMatrix_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ∀ e ∈ es, ‖Z (physicalBondOfEdge e)‖ ≤ r)
    (hW : ∀ e ∈ es, ‖W (physicalBondOfEdge e)‖ ≤ r) :
    ‖cmp98AmbientWilsonLineMatrix U Z es -
        cmp98AmbientWilsonLineMatrix U W es‖ ≤
      cmp98AmbientWilsonLineValueLipschitzBudget r es.length *
        ‖Z - W‖ := by
  induction es with
  | nil =>
      simp [cmp98AmbientWilsonLineValueLipschitzBudget]
  | cons e es ih =>
      have hZtail : ∀ a ∈ es, ‖Z (physicalBondOfEdge a)‖ ≤ r :=
        fun a ha => hZ a (by simp [ha])
      have hWtail : ∀ a ∈ es, ‖W (physicalBondOfEdge a)‖ ≤ r :=
        fun a ha => hW a (by simp [ha])
      have hdecomp :
          ambientOrientedEdgeMatrix U Z e *
                cmp98AmbientWilsonLineMatrix U Z es -
              ambientOrientedEdgeMatrix U W e *
                cmp98AmbientWilsonLineMatrix U W es =
            (ambientOrientedEdgeMatrix U Z e -
                ambientOrientedEdgeMatrix U W e) *
                cmp98AmbientWilsonLineMatrix U Z es +
              ambientOrientedEdgeMatrix U W e *
                (cmp98AmbientWilsonLineMatrix U Z es -
                  cmp98AmbientWilsonLineMatrix U W es) := by
        noncomm_ring
      have hEdgeDiff :=
        norm_ambientOrientedEdgeMatrix_sub_le U Z W e hr
          (hZ e (by simp)) (hW e (by simp))
      have hTailValue :=
        norm_cmp98AmbientWilsonLineMatrix_le U Z es hr hZtail
      have hEdgeValue :=
        norm_ambientOrientedEdgeMatrix_le U W e hr (hW e (by simp))
      have hTailDiff := ih hZtail hWtail
      have hTerm₁ :
          ‖ambientOrientedEdgeMatrix U Z e -
              ambientOrientedEdgeMatrix U W e‖ *
                ‖cmp98AmbientWilsonLineMatrix U Z es‖ ≤
            (cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖) *
              cmp98AmbientWilsonLineValueBudget r es.length := by
        calc
          _ ≤ (cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖) *
                ‖cmp98AmbientWilsonLineMatrix U Z es‖ :=
            mul_le_mul_of_nonneg_right hEdgeDiff (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hTailValue
            (mul_nonneg
              (cmp102AmbientEdgeValueLipschitzBudget_nonneg hr)
              (norm_nonneg (Z - W)))
      have hTerm₂ :
          ‖ambientOrientedEdgeMatrix U W e‖ *
              ‖cmp98AmbientWilsonLineMatrix U Z es -
                cmp98AmbientWilsonLineMatrix U W es‖ ≤
            cmp102AmbientEdgeValueBudget r *
              (cmp98AmbientWilsonLineValueLipschitzBudget r es.length *
                ‖Z - W‖) := by
        calc
          _ ≤ cmp102AmbientEdgeValueBudget r *
                ‖cmp98AmbientWilsonLineMatrix U Z es -
                  cmp98AmbientWilsonLineMatrix U W es‖ :=
            mul_le_mul_of_nonneg_right hEdgeValue (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hTailDiff
            (cmp102AmbientEdgeValueBudget_nonneg hr)
      rw [cmp98AmbientWilsonLineMatrix_cons,
        cmp98AmbientWilsonLineMatrix_cons, hdecomp]
      calc
        ‖(ambientOrientedEdgeMatrix U Z e -
              ambientOrientedEdgeMatrix U W e) *
              cmp98AmbientWilsonLineMatrix U Z es +
            ambientOrientedEdgeMatrix U W e *
              (cmp98AmbientWilsonLineMatrix U Z es -
                cmp98AmbientWilsonLineMatrix U W es)‖
            ≤ ‖ambientOrientedEdgeMatrix U Z e -
                  ambientOrientedEdgeMatrix U W e‖ *
                  ‖cmp98AmbientWilsonLineMatrix U Z es‖ +
                ‖ambientOrientedEdgeMatrix U W e‖ *
                  ‖cmp98AmbientWilsonLineMatrix U Z es -
                    cmp98AmbientWilsonLineMatrix U W es‖ := by
          exact (norm_add_le _ _).trans
            (add_le_add (norm_mul_le _ _) (norm_mul_le _ _))
        _ ≤
            (cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖) *
                cmp98AmbientWilsonLineValueBudget r es.length +
              cmp102AmbientEdgeValueBudget r *
                (cmp98AmbientWilsonLineValueLipschitzBudget r es.length *
                  ‖Z - W‖) := by
          exact add_le_add hTerm₁ hTerm₂
        _ =
            cmp98AmbientWilsonLineValueLipschitzBudget r (e :: es).length *
              ‖Z - W‖ := by
          simp only [List.length_cons,
            cmp98AmbientWilsonLineValueLipschitzBudget]
          ring

/-- The derivative norm of a literal contour is generated recursively from
the single-edge derivative budget and the contour value budget. -/
theorem norm_fderiv_cmp98AmbientWilsonLineMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ∀ e ∈ es, ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖fderiv ℝ (fun W => cmp98AmbientWilsonLineMatrix U W es) Z‖ ≤
      cmp98AmbientWilsonLineDerivativeBudget r es.length := by
  induction es with
  | nil =>
      have hzero :
          fderiv ℝ
              (fun _ : PhysicalAmbientMatrixTangent d (M * N') Nc =>
                (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) Z = 0 :=
        (hasFDerivAt_const (𝕜 := ℝ) (x := Z) (c := (1 :
          Matrix (Fin Nc) (Fin Nc) ℂ))).fderiv
      rw [show
        (fun W : PhysicalAmbientMatrixTangent d (M * N') Nc =>
          cmp98AmbientWilsonLineMatrix U W []) =
          (fun _ => (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) by rfl]
      rw [hzero]
      simp only [List.length_nil, cmp98AmbientWilsonLineDerivativeBudget]
      apply ContinuousLinearMap.opNorm_le_bound
      · exact le_rfl
      · intro H
        simp
  | cons e es ih =>
      have hZtail : ∀ a ∈ es, ‖Z (physicalBondOfEdge a)‖ ≤ r :=
        fun a ha => hZ a (by simp [ha])
      apply ContinuousLinearMap.opNorm_le_bound
        (fderiv ℝ
          (fun W => cmp98AmbientWilsonLineMatrix U W (e :: es)) Z)
        (cmp98AmbientWilsonLineDerivativeBudget_nonneg hr (e :: es).length)
      intro H
      change
        ‖fderiv ℝ
            (fun W : PhysicalAmbientMatrixTangent d (M * N') Nc =>
              cmp98AmbientWilsonLineMatrix U W (e :: es)) Z H‖ ≤
          cmp98AmbientWilsonLineDerivativeBudget r (e :: es).length * ‖H‖
      rw [fderiv_cmp98AmbientWilsonLineMatrix_apply]
      unfold cmp98AmbientWilsonLineDerivative
      have hHeadDeriv :
          ‖cmp102AmbientOrientedEdgeDerivative U Z H e‖ ≤
            expDerivativeBudget r * ‖H‖ := by
        rw [← fderiv_ambientOrientedEdgeMatrix_apply U Z H e]
        exact (ContinuousLinearMap.le_opNorm _ H).trans
          (mul_le_mul_of_nonneg_right
            (norm_fderiv_ambientOrientedEdgeMatrix_le U Z e
              (hZ e (by simp))) (norm_nonneg H))
      have hTailValue :=
        norm_cmp98AmbientWilsonLineMatrix_le U Z es hr hZtail
      have hHeadValue :=
        norm_ambientOrientedEdgeMatrix_le U Z e hr (hZ e (by simp))
      have hTailDeriv :
          ‖cmp98AmbientWilsonLineDerivative U Z H es‖ ≤
            cmp98AmbientWilsonLineDerivativeBudget r es.length * ‖H‖ := by
        rw [← fderiv_cmp98AmbientWilsonLineMatrix_apply U Z H es]
        exact (ContinuousLinearMap.le_opNorm _ H).trans
          (mul_le_mul_of_nonneg_right (ih hZtail) (norm_nonneg H))
      have hTerm₁ :
          ‖cmp102AmbientOrientedEdgeDerivative U Z H e‖ *
              ‖cmp98AmbientWilsonLineMatrix U Z es‖ ≤
            (expDerivativeBudget r * ‖H‖) *
              cmp98AmbientWilsonLineValueBudget r es.length := by
        calc
          _ ≤ (expDerivativeBudget r * ‖H‖) *
                ‖cmp98AmbientWilsonLineMatrix U Z es‖ :=
            mul_le_mul_of_nonneg_right hHeadDeriv (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hTailValue
            (mul_nonneg (expDerivativeBudget_nonneg r hr) (norm_nonneg H))
      have hTerm₂ :
          ‖ambientOrientedEdgeMatrix U Z e‖ *
              ‖cmp98AmbientWilsonLineDerivative U Z H es‖ ≤
            cmp102AmbientEdgeValueBudget r *
              (cmp98AmbientWilsonLineDerivativeBudget r es.length * ‖H‖) := by
        calc
          _ ≤ cmp102AmbientEdgeValueBudget r *
                ‖cmp98AmbientWilsonLineDerivative U Z H es‖ :=
            mul_le_mul_of_nonneg_right hHeadValue (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hTailDeriv
            (cmp102AmbientEdgeValueBudget_nonneg hr)
      calc
        ‖cmp102AmbientOrientedEdgeDerivative U Z H e *
                cmp98AmbientWilsonLineMatrix U Z es +
              ambientOrientedEdgeMatrix U Z e *
                cmp98AmbientWilsonLineDerivative U Z H es‖
            ≤ ‖cmp102AmbientOrientedEdgeDerivative U Z H e‖ *
                  ‖cmp98AmbientWilsonLineMatrix U Z es‖ +
                ‖ambientOrientedEdgeMatrix U Z e‖ *
                  ‖cmp98AmbientWilsonLineDerivative U Z H es‖ := by
          exact (norm_add_le _ _).trans
            (add_le_add (norm_mul_le _ _) (norm_mul_le _ _))
        _ ≤
            (expDerivativeBudget r * ‖H‖) *
                cmp98AmbientWilsonLineValueBudget r es.length +
              cmp102AmbientEdgeValueBudget r *
                (cmp98AmbientWilsonLineDerivativeBudget r es.length *
                  ‖H‖) := by
          exact add_le_add hTerm₁ hTerm₂
        _ =
            cmp98AmbientWilsonLineDerivativeBudget r (e :: es).length *
              ‖H‖ := by
          simp only [List.length_cons, cmp98AmbientWilsonLineDerivativeBudget]
          ring

/-- Exact four-term ordered telescope for derivatives of a nonempty
contour at two ambient fields. -/
theorem fderiv_cmp98AmbientWilsonLineMatrix_cons_sub_apply
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z W H : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (e : ConcreteEdge d (M * N'))
    (es : List (ConcreteEdge d (M * N'))) :
    (fderiv ℝ
          (fun V => cmp98AmbientWilsonLineMatrix U V (e :: es)) Z -
        fderiv ℝ
          (fun V => cmp98AmbientWilsonLineMatrix U V (e :: es)) W) H =
      (fderiv ℝ
            (fun V => ambientOrientedEdgeMatrix U V e) Z -
          fderiv ℝ
            (fun V => ambientOrientedEdgeMatrix U V e) W) H *
          cmp98AmbientWilsonLineMatrix U Z es +
        fderiv ℝ
            (fun V => ambientOrientedEdgeMatrix U V e) W H *
          (cmp98AmbientWilsonLineMatrix U Z es -
            cmp98AmbientWilsonLineMatrix U W es) +
        (ambientOrientedEdgeMatrix U Z e -
            ambientOrientedEdgeMatrix U W e) *
          fderiv ℝ
            (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H +
        ambientOrientedEdgeMatrix U W e *
          ((fderiv ℝ
                (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
              fderiv ℝ
                (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H) := by
  simp only [ContinuousLinearMap.sub_apply]
  rw [fderiv_cmp98AmbientWilsonLineMatrix_apply U Z H (e :: es),
    fderiv_cmp98AmbientWilsonLineMatrix_apply U W H (e :: es)]
  unfold cmp98AmbientWilsonLineDerivative
  rw [← fderiv_ambientOrientedEdgeMatrix_apply U Z H e,
    ← fderiv_ambientOrientedEdgeMatrix_apply U W H e,
    ← fderiv_cmp98AmbientWilsonLineMatrix_apply U Z H es,
    ← fderiv_cmp98AmbientWilsonLineMatrix_apply U W H es]
  noncomm_ring

/-- The derivative variation of a literal contour is generated by the four
source-faithful ordered telescope terms. -/
theorem norm_fderiv_cmp98AmbientWilsonLineMatrix_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) {r : ℝ}
    (hr : 0 ≤ r)
    (hZ : ∀ e ∈ es, ‖Z (physicalBondOfEdge e)‖ ≤ r)
    (hW : ∀ e ∈ es, ‖W (physicalBondOfEdge e)‖ ≤ r) :
    ‖fderiv ℝ (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
        fderiv ℝ (fun V => cmp98AmbientWilsonLineMatrix U V es) W‖ ≤
      cmp98AmbientWilsonLineDerivativeLipschitzBudget r es.length *
        ‖Z - W‖ := by
  induction es with
  | nil =>
      have hzeroZ :
          fderiv ℝ
              (fun _ : PhysicalAmbientMatrixTangent d (M * N') Nc =>
                (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) Z = 0 :=
        (hasFDerivAt_const (𝕜 := ℝ) (x := Z) (c := (1 :
          Matrix (Fin Nc) (Fin Nc) ℂ))).fderiv
      have hzeroW :
          fderiv ℝ
              (fun _ : PhysicalAmbientMatrixTangent d (M * N') Nc =>
                (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) W = 0 :=
        (hasFDerivAt_const (𝕜 := ℝ) (x := W) (c := (1 :
          Matrix (Fin Nc) (Fin Nc) ℂ))).fderiv
      rw [show
        (fun V : PhysicalAmbientMatrixTangent d (M * N') Nc =>
          cmp98AmbientWilsonLineMatrix U V []) =
          (fun _ => (1 : Matrix (Fin Nc) (Fin Nc) ℂ)) by rfl]
      rw [hzeroZ, hzeroW]
      simp only [List.length_nil,
        cmp98AmbientWilsonLineDerivativeLipschitzBudget, zero_mul]
      apply ContinuousLinearMap.opNorm_le_bound
      · exact le_rfl
      · intro H
        simp
  | cons e es ih =>
      have hZtail : ∀ a ∈ es, ‖Z (physicalBondOfEdge a)‖ ≤ r :=
        fun a ha => hZ a (by simp [ha])
      have hWtail : ∀ a ∈ es, ‖W (physicalBondOfEdge a)‖ ≤ r :=
        fun a ha => hW a (by simp [ha])
      apply ContinuousLinearMap.opNorm_le_bound
        (fderiv ℝ
            (fun V => cmp98AmbientWilsonLineMatrix U V (e :: es)) Z -
          fderiv ℝ
            (fun V => cmp98AmbientWilsonLineMatrix U V (e :: es)) W)
        (mul_nonneg
          (cmp98AmbientWilsonLineDerivativeLipschitzBudget_nonneg hr
            (e :: es).length) (norm_nonneg (Z - W)))
      intro H
      rw [fderiv_cmp98AmbientWilsonLineMatrix_cons_sub_apply]
      have hDDHead :
          ‖(fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) Z -
                fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W) H‖ ≤
            (expSecondDerivativeBudget r * ‖Z - W‖) * ‖H‖ :=
        (ContinuousLinearMap.le_opNorm _ H).trans
          (mul_le_mul_of_nonneg_right
            (norm_fderiv_ambientOrientedEdgeMatrix_sub_le U Z W e
              (hZ e (by simp)) (hW e (by simp))) (norm_nonneg H))
      have hTailValue :=
        norm_cmp98AmbientWilsonLineMatrix_le U Z es hr hZtail
      have hDHead :
          ‖fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W H‖ ≤
            expDerivativeBudget r * ‖H‖ :=
        (ContinuousLinearMap.le_opNorm _ H).trans
          (mul_le_mul_of_nonneg_right
            (norm_fderiv_ambientOrientedEdgeMatrix_le U W e
              (hW e (by simp))) (norm_nonneg H))
      have hTailDiff :=
        norm_cmp98AmbientWilsonLineMatrix_sub_le
          U Z W es hr hZtail hWtail
      have hEdgeDiff :=
        norm_ambientOrientedEdgeMatrix_sub_le U Z W e hr
          (hZ e (by simp)) (hW e (by simp))
      have hDTail :
          ‖fderiv ℝ
              (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H‖ ≤
            cmp98AmbientWilsonLineDerivativeBudget r es.length * ‖H‖ :=
        (ContinuousLinearMap.le_opNorm _ H).trans
          (mul_le_mul_of_nonneg_right
            (norm_fderiv_cmp98AmbientWilsonLineMatrix_le
              U Z es hr hZtail) (norm_nonneg H))
      have hEdgeValue :=
        norm_ambientOrientedEdgeMatrix_le U W e hr (hW e (by simp))
      have hDDTail :
          ‖(fderiv ℝ
                (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
              fderiv ℝ
                (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H‖ ≤
            (cmp98AmbientWilsonLineDerivativeLipschitzBudget r es.length *
              ‖Z - W‖) * ‖H‖ :=
        (ContinuousLinearMap.le_opNorm _ H).trans
          (mul_le_mul_of_nonneg_right (ih hZtail hWtail) (norm_nonneg H))
      have hTerm₁ :
          ‖(fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) Z -
                fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W) H‖ *
              ‖cmp98AmbientWilsonLineMatrix U Z es‖ ≤
            ((expSecondDerivativeBudget r * ‖Z - W‖) * ‖H‖) *
              cmp98AmbientWilsonLineValueBudget r es.length := by
        calc
          _ ≤ ((expSecondDerivativeBudget r * ‖Z - W‖) * ‖H‖) *
                ‖cmp98AmbientWilsonLineMatrix U Z es‖ :=
            mul_le_mul_of_nonneg_right hDDHead (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hTailValue
            (mul_nonneg
              (mul_nonneg (expSecondDerivativeBudget_nonneg r hr)
                (norm_nonneg (Z - W))) (norm_nonneg H))
      have hTerm₂ :
          ‖fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W H‖ *
              ‖cmp98AmbientWilsonLineMatrix U Z es -
                cmp98AmbientWilsonLineMatrix U W es‖ ≤
            (expDerivativeBudget r * ‖H‖) *
              (cmp98AmbientWilsonLineValueLipschitzBudget r es.length *
                ‖Z - W‖) := by
        calc
          _ ≤ (expDerivativeBudget r * ‖H‖) *
                ‖cmp98AmbientWilsonLineMatrix U Z es -
                  cmp98AmbientWilsonLineMatrix U W es‖ :=
            mul_le_mul_of_nonneg_right hDHead (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hTailDiff
            (mul_nonneg (expDerivativeBudget_nonneg r hr) (norm_nonneg H))
      have hTerm₃ :
          ‖ambientOrientedEdgeMatrix U Z e -
              ambientOrientedEdgeMatrix U W e‖ *
              ‖fderiv ℝ
                (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H‖ ≤
            (cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖) *
              (cmp98AmbientWilsonLineDerivativeBudget r es.length * ‖H‖) := by
        calc
          _ ≤ (cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖) *
                ‖fderiv ℝ
                  (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H‖ :=
            mul_le_mul_of_nonneg_right hEdgeDiff (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hDTail
            (mul_nonneg
              (cmp102AmbientEdgeValueLipschitzBudget_nonneg hr)
              (norm_nonneg (Z - W)))
      have hTerm₄ :
          ‖ambientOrientedEdgeMatrix U W e‖ *
              ‖(fderiv ℝ
                    (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
                  fderiv ℝ
                    (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H‖ ≤
            cmp102AmbientEdgeValueBudget r *
              ((cmp98AmbientWilsonLineDerivativeLipschitzBudget r es.length *
                ‖Z - W‖) * ‖H‖) := by
        calc
          _ ≤ cmp102AmbientEdgeValueBudget r *
                ‖(fderiv ℝ
                      (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
                    fderiv ℝ
                      (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H‖ :=
            mul_le_mul_of_nonneg_right hEdgeValue (norm_nonneg _)
          _ ≤ _ := mul_le_mul_of_nonneg_left hDDTail
            (cmp102AmbientEdgeValueBudget_nonneg hr)
      calc
        ‖(fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) Z -
                fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W) H *
              cmp98AmbientWilsonLineMatrix U Z es +
            fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W H *
              (cmp98AmbientWilsonLineMatrix U Z es -
                cmp98AmbientWilsonLineMatrix U W es) +
            (ambientOrientedEdgeMatrix U Z e -
                ambientOrientedEdgeMatrix U W e) *
              fderiv ℝ
                (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H +
            ambientOrientedEdgeMatrix U W e *
              ((fderiv ℝ
                    (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
                  fderiv ℝ
                    (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H)‖
            ≤
              ‖(fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) Z -
                    fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W) H‖ *
                  ‖cmp98AmbientWilsonLineMatrix U Z es‖ +
                ‖fderiv ℝ
                    (fun V => ambientOrientedEdgeMatrix U V e) W H‖ *
                  ‖cmp98AmbientWilsonLineMatrix U Z es -
                    cmp98AmbientWilsonLineMatrix U W es‖ +
                ‖ambientOrientedEdgeMatrix U Z e -
                    ambientOrientedEdgeMatrix U W e‖ *
                  ‖fderiv ℝ
                    (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H‖ +
                ‖ambientOrientedEdgeMatrix U W e‖ *
                  ‖(fderiv ℝ
                        (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
                      fderiv ℝ
                        (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H‖ := by
          calc
            _ ≤
                ‖(fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) Z -
                      fderiv ℝ (fun V => ambientOrientedEdgeMatrix U V e) W) H *
                    cmp98AmbientWilsonLineMatrix U Z es‖ +
                  ‖fderiv ℝ
                      (fun V => ambientOrientedEdgeMatrix U V e) W H *
                    (cmp98AmbientWilsonLineMatrix U Z es -
                      cmp98AmbientWilsonLineMatrix U W es)‖ +
                  ‖(ambientOrientedEdgeMatrix U Z e -
                      ambientOrientedEdgeMatrix U W e) *
                    fderiv ℝ
                      (fun V => cmp98AmbientWilsonLineMatrix U V es) Z H‖ +
                  ‖ambientOrientedEdgeMatrix U W e *
                    ((fderiv ℝ
                          (fun V => cmp98AmbientWilsonLineMatrix U V es) Z -
                        fderiv ℝ
                          (fun V => cmp98AmbientWilsonLineMatrix U V es) W) H)‖ := by
              exact norm_add₄_le
            _ ≤ _ := by
              gcongr <;> exact norm_mul_le _ _
        _ ≤
            ((expSecondDerivativeBudget r * ‖Z - W‖) * ‖H‖) *
                cmp98AmbientWilsonLineValueBudget r es.length +
              (expDerivativeBudget r * ‖H‖) *
                (cmp98AmbientWilsonLineValueLipschitzBudget r es.length *
                  ‖Z - W‖) +
              (cmp102AmbientEdgeValueLipschitzBudget r * ‖Z - W‖) *
                (cmp98AmbientWilsonLineDerivativeBudget r es.length * ‖H‖) +
              cmp102AmbientEdgeValueBudget r *
                ((cmp98AmbientWilsonLineDerivativeLipschitzBudget r es.length *
                  ‖Z - W‖) * ‖H‖) := by
          exact add_le_add (add_le_add (add_le_add hTerm₁ hTerm₂) hTerm₃)
            hTerm₄
        _ =
            (cmp98AmbientWilsonLineDerivativeLipschitzBudget r
                (e :: es).length * ‖Z - W‖) * ‖H‖ := by
          simp only [List.length_cons,
            cmp98AmbientWilsonLineDerivativeLipschitzBudget]
          ring

end

end YangMills.RG
