import YangMills.RG.BalabanCMP102Eq80PhysicalDomainFTCSourceReassembly

#print axioms YangMills.RG.cmp102Eq80PhysicalFineHeadTailDomainDerivativeLayer_eq_zero_of_not_localizationDomain
#print axioms YangMills.RG.cmp102Eq80PhysicalFineHeadTailDomainCoefficient_eq_zero_of_not_localizationDomain
#print axioms YangMills.RG.cmp102Eq80PhysicalFineHeadTailDomainFTCContribution_eq_zero_of_not_localizationDomain
#print axioms YangMills.RG.cmp102Eq80PhysicalLayerWordDomainFTCContribution_eq_zero_of_not_localizationDomain
#print axioms YangMills.RG.cmp102Eq80SourcePi4PhysicalDomainFTCMinimizerIncrement_eq_sum_neumannDomainFTC
#print axioms YangMills.RG.cmp102Eq80SourcePi4PhysicalDomainFTCMinimizerIncrement_eq_sum_neumannDomainFTC_of_source
