import YangMills.RG.BalabanCMP89SourceFlatGeneratedFiniteDepthCanonicalNeumannPrecision

/-!
# Axiom audit for the canonical Neumann precision/Green pair

Cold compiler evidence for this audit is recorded in Verification Ledger
Addendum 1004.
-/

#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannTower
#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannLastPrefix
#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannPoincareCoefficient
#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannPrecision
#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannPoincare
#print axioms YangMills.RG.isCoerciveCLM_cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannPrecision
#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannPrecision_comp_green
#print axioms YangMills.RG.cmp89SourceFlatGeneratedFiniteDepthCanonicalNeumannGreen_comp_precision
