import YangMills.RG.BalabanCMP99PhysicalFineHeadTailWordExpansion

#print axioms YangMills.RG.cmp99SourcePi4PhysicalFineHeadTailWordTerm
#print axioms YangMills.RG.cmp99SourcePi4PhysicalBackgroundMinimizerChoiceWordTerm
#print axioms YangMills.RG.cmp99SourcePi4PhysicalBackgroundMinimizerWordTerm
#print axioms YangMills.RG.cmp99SourcePi4PhysicalBackgroundMinimizerWordTerm_eq_sum_fineWalkChoices
#print axioms YangMills.RG.cmp99SourcePi4PhysicalBackgroundMinimizerNeumannLayer
#print axioms YangMills.RG.summable_cmp99SourcePi4ComplexBackgroundMinimizerWordTerms_for_reconstruction_of_source
#print axioms YangMills.RG.summable_cmp99SourcePi4PhysicalBackgroundMinimizerWordTerms_of_source
#print axioms YangMills.RG.cmp99SourcePi4PhysicalBackgroundMinimizerNeumannLayer_eq_tsum_words_of_source
#print axioms YangMills.RG.cmp99SourcePi4PhysicalBackgroundMinimizerChoiceWordTerm_eq_tsum_headWalks_of_source
#print axioms YangMills.RG.summable_cmp99SourcePi4PhysicalFineHeadTailWordTerms_of_source
#print axioms YangMills.RG.cmp99SourcePi4PhysicalFineHeadTailWordTerm_eq_of_eqOn_active
