/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116SourceSigmaZeroActiveCarrier
import YangMills.RG.BalabanCMP116ComplexPhysicalWalkKernel

/-!
# Source-specific complex Cauchy bound for CMP99 patched walks

This module composes the literal `Pi^4`/`sigma_0` chart geometry, the physical
patched-parametrix walk terms, their volume-uniform summability theorem, and
the complex weakening contour.  The terminal result is a Cauchy boundary
bound for every physical kernel entry.

The radial operator majorant is not an input.  It is generated by evaluating
the already proved source-specific real series at the constant weakening
system `s = Rweak`; its monomial is exactly `Rweak ^ card(active walk)`.
The complex coefficient majorant then follows with constant one.
-/

namespace YangMills.RG

noncomputable section

universe u

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 1600000

/-- Terminal source-specific complex Cauchy estimate for one physical kernel
entry of the patched random-walk series.  No abstract radial majorant,
branching factor, active-carrier budget, or chart dictionary remains. -/
theorem cmp116Eq214CauchyBoundaryBound_sourceSigmaZeroPi4PhysicalWalkKernel
    {Label : Type u} [Fintype Label] [DecidableEq Label]
    {M Q Nc Rrange NR : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q) (hsourceRange : Rrange + 1 ≤ 4 * M)
    (K : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
      PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc)
    (hsymm : ∀ p q : PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist p q = physicalBondDist q p)
    (hself : ∀ p : PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist p p = 0)
    (htri : ∀ x y z : PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist x y ≤
        physicalBondDist x z + physicalBondDist z y)
    {Cker c mass κ σ Ssum Sdef : ℝ}
    (hCker : 0 ≤ Cker) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ)
    (hSsum : 0 ≤ Ssum) (hSdef : 0 ≤ Sdef)
    (hsum : ∀ x,
      ∑ z : PhysicalBond 4 (M * (2 * Q)),
        Real.exp (-(σ * (physicalBondDist x z : ℝ))) ≤ Ssum)
    (hsumDef : ∀ x,
      ∑ z : PhysicalBond 4 (M * (2 * Q)),
        Real.exp (-(((((κ - σ) - σ) - σ) *
          (physicalBondDist x z : ℝ)))) ≤ Sdef)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist Rrange)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => Cker))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond 4 (M * (2 * Q)),
      (Finset.univ.filter
        (fun y => physicalBondDist x y ≤ Rrange)).card ≤ NR)
    (htilt :
      (Cker + |mass|) *
          (Real.exp (κ * (Rrange : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2)
    (Δ : ℕ) (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ) :
    let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
      (Label := Label) anchor hsourceRange
    ∀ (left : ↥Dict.charts)
      {n : ℕ} (emb : Fin n ↪ FinBox 4 (2 * Q))
      (radius : Fin n → ℝ)
      (source target : PhysicalBond 4 (M * (2 * Q)))
      (input output : Fin (Nc ^ 2 - 1))
      (Rweak : ℝ) (hRweak : 1 ≤ Rweak)
      (hcap : ∀ i, 1 + radius i ≤ Rweak)
      (hsmall :
        ((Fintype.card Label *
            (625 * 626 * Δ ^ 1250) : ℕ) : ℝ) *
            (cmp99SingleDefectDecayAmplitude
              Cker κ Rrange c mass Ssum * Sdef) *
              Rweak ^ 10000 < 1),
      CMP116Eq214CauchyBoundaryBound n radius
        (fun z => cmp116ComplexWeakenedRandomWalkSeries
          (fun walk : CMP99AnchoredWalk
              (cmp99PhysicalPatchSuccessorSteps
                Dict.charts Dict.core Dict.enlarged
                physicalBondDist Rrange) left =>
            walk.active Dict.domainActive)
          (fun walk => cmp116ComplexPhysicalOperatorCoefficient
            (walk.term
              (cmp99PhysicalPatchHead Dict.charts K
                Dict.enlarged Dict.core hc hmass hK)
              (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                Dict.enlarged Dict.core hc hmass hK))
            source target input output)
          (cmp116ComplexWeakeningOfContour emb z))
        (∑' walk : CMP99AnchoredWalk
            (cmp99PhysicalPatchSuccessorSteps
              Dict.charts Dict.core Dict.enlarged
              physicalBondDist Rrange) left,
          Rweak ^ (walk.active Dict.domainActive).card *
            ‖cmp116ComplexPhysicalOperatorCoefficient
              (walk.term
                (cmp99PhysicalPatchHead Dict.charts K
                  Dict.enlarged Dict.core hc hmass hK)
                (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                  Dict.enlarged Dict.core hc hmass hK))
              source target input output‖) := by
  dsimp only
  intro left n emb radius source target input output
    Rweak hRweak hcap hsmall
  let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
    (Label := Label) anchor hsourceRange
  let successors := cmp99PhysicalPatchSuccessorSteps
    Dict.charts Dict.core Dict.enlarged physicalBondDist Rrange
  let term : CMP99AnchoredWalk successors left →
      (PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
        PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc) :=
    fun walk => walk.term
      (cmp99PhysicalPatchHead Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
  have hsR :
      (fun _ : FinBox 4 (2 * Q) => Rweak) ∈
        cmp116WeakeningPolydisc Rweak := by
    intro block
    simp [abs_of_nonneg (zero_le_one.trans hRweak)]
  have hsourceSummable :=
    summable_cmp116SourceSigmaZeroPi4PhysicalPatchWalkSeries
      (Label := Label) anchor hsourceRange K hsymm hself htri
      hCker hc hmass hσ h3σκ hSsum hSdef hsum hsumDef
      hrange hbound hK hNR htilt Δ hΔ hΔ1
      left (fun _ => Rweak) Rweak hRweak hsmall hsR
  have hradial : Summable fun walk : CMP99AnchoredWalk successors left =>
      Rweak ^ (walk.active Dict.domainActive).card • term walk := by
    refine Summable.congr hsourceSummable fun walk => ?_
    change
      cmp116WeakeningMonomial (walk.active Dict.domainActive)
          (fun _ => Rweak) • term walk =
        Rweak ^ (walk.active Dict.domainActive).card • term walk
    congr 1
    simp [cmp116WeakeningMonomial]
  exact cmp116Eq214CauchyBoundaryBound_of_physicalWalkKernel
    emb radius
    (fun walk : CMP99AnchoredWalk successors left =>
      walk.active Dict.domainActive)
    term source target input output Rweak hRweak hcap hradial

end

end YangMills.RG
