-- Promotion import:
import YangMills.RG.BalabanCMP89CenteredTorusGreenCoefficientPhase


-- SEALED AXIOM SURFACE: intended axiom surface for Step 8b.23/Unit E.14.

#print axioms YangMills.RG.exp_I_cmp89Eq251EntireAliasPhase_latticeDisplacement
#print axioms YangMills.RG.cmp89UnitAddTorus_mFourier_neg_mul_aliasFinePhase_eq_affineResiduePhase
#print axioms YangMills.RG.cmp89UnitAddTorus_mFourier_neg_mul_bareGreen_eq_affineResidue
#print axioms YangMills.RG.cmp89UnitAddTorus_mFourier_neg_mul_stabilizedGreenNumerator_eq_affineResidue
#print axioms YangMills.RG.cmp89UnitAddTorus_mFourier_neg_mul_stabilizedGreen_eq_affineResidue
