import YangMills.RG.BalabanCMP102Eq80PhysicalDomainFTCContribution

#print axioms YangMills.RG.cmp102Eq80PhysicalFineHeadTailDomainFTCContribution
#print axioms YangMills.RG.integral_cmp102Eq80PhysicalChoiceAnchoredDerivativeSeries_eq_sum_domainFTCContributions
#print axioms YangMills.RG.cmp102Eq80PhysicalLayerWordDomainFTCContribution
#print axioms YangMills.RG.integral_sum_cmp102Eq80PhysicalChoiceAnchoredDerivativeSeries_eq_sum_layerWordDomainFTCContributions
