/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116Eq226CenteredConditionedPhysicalTermSource
import YangMills.RG.BalabanCMP116Eq214LocalActivityIdentification
import YangMills.RG.BalabanCMP116Lemma3ScaleFamily

/-!
# Centered conditioned physical equation-(2.26) terms as a Lemma-3 boundary

This is the replacement for the pointwise contour-source route.  Each
summand is generated by `CMP116Eq226CenteredConditionedPhysicalTermSource`, whose
termwise estimate consumes the almost-everywhere interaction bound inside the
conditioned Gaussian integral.

The local activity and the analytic resummation are assembled from the same
conditioned density.  Consequently `activity_identification` is definitional;
the termwise field is obtained from the physical equation-(2.26) theorem and
is not an input to this module.
-/

namespace YangMills.RG

noncomputable section

private abbrev SourceBond (M Q : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)] [NeZero (M * (2 * Q))] :=
  PhysicalBond 4 (M * (2 * Q))

/-- One source-faithful term record for every member of the dependent
`D/P/Z0/Z0'` stack.  The outer carrier is supplied by the polymer index. -/
def CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : Type*}
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished : Finset (SourceBond M Q))
    (outerCarrier : σ → Finset (FinBox 4 (2 * Q))) : Type _ :=
  ∀ (Z : σ)
      (D : Finset (Finset (FinBox 4 (2 * Q))))
      (P : Finset (SourceBond M Q))
      (Z0 : CMP116SourcePhysicalLocalizedRegion Dict) (_Z0p : ιZ0'),
    CMP116Eq226CenteredConditionedPhysicalTermSource
      (nDelta := nDelta) (nY := nY) Dict
      (cmp116Eq214SmallFieldBondCarrier ambient distinguished D)
      P Z0.1 (outerCarrier Z)

/-- The resummation whose summands and weights are definitionally those of
the centered centered conditioned physical term records. -/
def cmp116Eq226CenteredConditionedPhysicalContourResummation
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : Type*} [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished : Finset (SourceBond M Q))
    (outerCarrier : σ → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      σ → Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion Dict))
    (Z0PrimeIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion Dict → Finset ιZ0')
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
      (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0')
        Dict ambient distinguished
        outerCarrier) :
    CMP116HResummation σ
      (Finset (Finset (FinBox 4 (2 * Q))))
      (Finset (SourceBond M Q))
      (CMP116SourcePhysicalLocalizedRegion Dict) ιZ0'
      (PhysicalGaugeField 4 (M * (2 * Q)) Nc)
      (PhysicalGaugeField 4 (M * (2 * Q)) Nc) where
  DIndex := DIndex
  PIndex := PIndex
  Z0Index := Z0Index
  Z0PrimeIndex := Z0PrimeIndex
  summand := fun Z D P Z0 Z0p psi phi =>
    (S Z D P Z0 Z0p).conditionedDensity.toLocalFiniteGaussianData
      |>.toFiniteGaussianData.toAnalyticData.term
        (cmp116Eq214SmallFieldBondCarrier ambient distinguished D) P psi phi
  termWeight := fun Z D P Z0 Z0p =>
    (S Z D P Z0 Z0p).termWeight

/-- The corresponding local physical activity, assembled before global
evaluation. -/
def cmp116Eq226CenteredConditionedPhysicalContourActivity
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : Type*} [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished : Finset (SourceBond M Q))
    (outerCarrier : σ → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      σ → Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion Dict))
    (Z0PrimeIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion Dict → Finset ιZ0')
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
      (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0')
        Dict ambient distinguished
        outerCarrier)
    (Z : σ) :
    PhysicalGaugeLocalActivity 4 (M * (2 * Q)) Nc :=
  let R := cmp116Eq226CenteredConditionedPhysicalContourResummation
    Dict ambient distinguished outerCarrier
    DIndex PIndex Z0Index Z0PrimeIndex S
  LocalActivity.finsetSum (cmp116HIndexFinset R Z) fun x =>
    (S Z x.1.1 x.1.2 x.2.1 x.2.2).conditionedDensity
      |>.toLocalFiniteGaussianData.toLocalAnalyticData.localTerm
        (cmp116Eq214SmallFieldBondCarrier
          ambient distinguished x.1.1) x.1.2

/-- Global evaluation of the assembled activity is definitionally the
conditioned physical resummation. -/
@[simp] theorem globalEval_cmp116Eq226CenteredConditionedPhysicalContourActivity
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : Type*} [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished : Finset (SourceBond M Q))
    (outerCarrier : σ → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      σ → Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion Dict))
    (Z0PrimeIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion Dict → Finset ιZ0')
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
      (nDelta := nDelta) (nY := nY) Dict ambient distinguished
        outerCarrier)
    (Z : σ) (psi phi : PhysicalGaugeField 4 (M * (2 * Q)) Nc) :
    (cmp116Eq226CenteredConditionedPhysicalContourActivity
      Dict ambient distinguished outerCarrier
      DIndex PIndex Z0Index Z0PrimeIndex S Z).globalEval psi phi =
      balabanCMP116H
        (cmp116Eq226CenteredConditionedPhysicalContourResummation
          Dict ambient distinguished outerCarrier
          DIndex PIndex Z0Index Z0PrimeIndex S) Z psi phi := by
  rw [cmp116Eq226CenteredConditionedPhysicalContourActivity,
    LocalActivity.globalEval_finsetSum]
  rfl

/-- Every resummation summand satisfies its literal source weight, with no
termwise estimate supplied by the caller. -/
theorem cmp116Eq226CenteredConditionedPhysicalContourResummation_termwise
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : Type*} [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished : Finset (SourceBond M Q))
    (outerCarrier : σ → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      σ → Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion Dict))
    (Z0PrimeIndex :
      σ → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion Dict → Finset ιZ0')
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
      (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0')
        Dict ambient distinguished
        outerCarrier) :
    ∀ Z x,
      x ∈ cmp116HIndexFinset
        (cmp116Eq226CenteredConditionedPhysicalContourResummation
          Dict ambient distinguished outerCarrier
          DIndex PIndex Z0Index Z0PrimeIndex S) Z →
      ∀ psi phi,
        ‖(cmp116Eq226CenteredConditionedPhysicalContourResummation
            Dict ambient distinguished outerCarrier
            DIndex PIndex Z0Index Z0PrimeIndex S).summand
              Z x.1.1 x.1.2 x.2.1 x.2.2 psi phi‖ ≤
          (cmp116Eq226CenteredConditionedPhysicalContourResummation
            Dict ambient distinguished outerCarrier
            DIndex PIndex Z0Index Z0PrimeIndex S).termWeight
              Z x.1.1 x.1.2 x.2.1 x.2.2 := by
  intro Z x _ psi phi
  exact
    (S Z x.1.1 x.1.2 x.2.1 x.2.2).norm_term_le_termWeight psi phi

/-- Dependent scale family of the conditioned physical resummations. -/
def cmp116Eq226CenteredConditionedPhysicalContourResummationScaleFamily
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : ℕ → ℕ → Type*}
    [∀ t k, DecidableEq (ιZ0' t k)]
    (Dict : ∀ t k,
      PhysicalGaugeCMP116Dictionary 4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished :
      ∀ t k, Finset (SourceBond M Q))
    (outerCarrier :
      ∀ t k, σ t k → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      ∀ t k, σ t k →
        Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion (Dict t k)))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion (Dict t k) → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
        (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0' t k)
        (Dict t k) (ambient t k) (distinguished t k)
          (outerCarrier t k)) :
    ∀ t k,
      CMP116HResummation (σ t k)
        (Finset (Finset (FinBox 4 (2 * Q))))
        (Finset (SourceBond M Q))
        (CMP116SourcePhysicalLocalizedRegion (Dict t k)) (ιZ0' t k)
        (PhysicalGaugeField 4 (M * (2 * Q)) Nc)
        (PhysicalGaugeField 4 (M * (2 * Q)) Nc) :=
  fun t k =>
    cmp116Eq226CenteredConditionedPhysicalContourResummation
      (Dict t k) (ambient t k) (distinguished t k) (outerCarrier t k)
      (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k) (S t k)

/-- Dependent scale family of the corresponding local activities. -/
def cmp116Eq226CenteredConditionedPhysicalContourActivityScaleFamily
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : ℕ → ℕ → Type*}
    [∀ t k, DecidableEq (ιZ0' t k)]
    (Dict : ∀ t k,
      PhysicalGaugeCMP116Dictionary 4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished :
      ∀ t k, Finset (SourceBond M Q))
    (outerCarrier :
      ∀ t k, σ t k → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      ∀ t k, σ t k →
        Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion (Dict t k)))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion (Dict t k) → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
        (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0' t k)
        (Dict t k) (ambient t k) (distinguished t k)
          (outerCarrier t k)) :
    ∀ t k, σ t k → PhysicalGaugeLocalActivity 4 (M * (2 * Q)) Nc :=
  fun t k =>
    cmp116Eq226CenteredConditionedPhysicalContourActivity
      (Dict t k) (ambient t k) (distinguished t k) (outerCarrier t k)
      (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k) (S t k)

/-- Source-faithful Lemma-3 boundary for the corrected conditioned route. -/
theorem cmp116Eq226CenteredConditionedPhysicalContour_activityTermwiseScaleBoundary
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ : ℕ → ℕ → Type*}
    [∀ t k, DecidableEq (ιZ0' t k)]
    (Dict : ∀ t k,
      PhysicalGaugeCMP116Dictionary 4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished :
      ∀ t k, Finset (SourceBond M Q))
    (outerCarrier :
      ∀ t k, σ t k → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      ∀ t k, σ t k →
        Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion (Dict t k)))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion (Dict t k) → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
        (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0' t k)
        (Dict t k) (ambient t k) (distinguished t k)
          (outerCarrier t k)) :
    CMP116Lemma3ActivityTermwiseScaleBoundary
      (cmp116Eq226CenteredConditionedPhysicalContourResummationScaleFamily
        Dict ambient distinguished outerCarrier
        DIndex PIndex Z0Index Z0PrimeIndex S)
      (cmp116Eq226CenteredConditionedPhysicalContourActivityScaleFamily
        Dict ambient distinguished outerCarrier
        DIndex PIndex Z0Index Z0PrimeIndex S) where
  activity_identification := by
    intro t k Z psi phi
    exact
      globalEval_cmp116Eq226CenteredConditionedPhysicalContourActivity
        (Dict t k) (ambient t k) (distinguished t k) (outerCarrier t k)
        (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k)
        (S t k) Z psi phi
  termwise_estimate := by
    intro t k
    exact
      cmp116Eq226CenteredConditionedPhysicalContourResummation_termwise
        (Dict t k) (ambient t k) (distinguished t k) (outerCarrier t k)
        (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k)
        (S t k)

/-- Consume the corrected conditioned termwise boundary with the existing
equation-(2.29), `P`, and post-`P` source stages.  Neither activity
identification nor a termwise norm estimate is supplied by the caller. -/
def cmp116Eq226CenteredConditionedPhysicalContour_lemma3ActivityEstimate_of_boundaries
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {ιZ0' σ ιY : ℕ → ℕ → Type*}
    [∀ t k, DecidableEq (ιZ0' t k)]
    (Dict : ∀ t k,
      PhysicalGaugeCMP116Dictionary 4 (M * (2 * Q)) Nc 4 L lieDim)
    (ambient distinguished :
      ∀ t k, Finset (SourceBond M Q))
    (outerCarrier :
      ∀ t k, σ t k → Finset (FinBox 4 (2 * Q)))
    (DIndex :
      ∀ t k, σ t k →
        Finset (Finset (Finset (FinBox 4 (2 * Q)))))
    (PIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (Finset (SourceBond M Q)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          Finset (CMP116SourcePhysicalLocalizedRegion (Dict t k)))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Finset (FinBox 4 (2 * Q))) →
        Finset (SourceBond M Q) →
          CMP116SourcePhysicalLocalizedRegion (Dict t k) → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226CenteredConditionedPhysicalTermSourceFamily
        (nDelta := nDelta) (nY := nY) (ιZ0' := ιZ0' t k)
        (Dict t k) (ambient t k) (distinguished t k)
          (outerCarrier t k))
    (hp : ∀ t k, CMP116Lemma3Parameters)
    (sourceMetric : ∀ t k, σ t k → ℕ)
    (DParts :
      ∀ t k, σ t k →
        Finset (Finset (FinBox 4 (2 * Q))) → Finset (ιY t k))
    (alpha6 : ℕ → ℕ → ℝ)
    (eq229Metric : ∀ t k, σ t k → ιY t k → ℕ)
    (pResidualWeight :
      ∀ t k, σ t k →
        Finset (Finset (FinBox 4 (2 * Q))) →
          Finset (SourceBond M Q) → ℝ)
    (pStageBlockScale : ℕ → ℕ → ℕ)
    (pEntropyConstant epsilon2 pStageKappa : ℕ → ℕ → ℝ)
    (postPSourceWeight : ∀ t k, σ t k → ℝ)
    (postPAmplitude : ℕ → ℕ → ℝ)
    (eq229 :
      CMP116Lemma3Eq229ScaleBoundary hp
        (cmp116Eq226CenteredConditionedPhysicalContourResummationScaleFamily
          Dict ambient distinguished outerCarrier
          DIndex PIndex Z0Index Z0PrimeIndex S)
        DParts alpha6 eq229Metric)
    (pStage :
      CMP116Lemma3PStageSourceScaleBoundary
        (cmp116Eq226CenteredConditionedPhysicalContourResummationScaleFamily
          Dict ambient distinguished outerCarrier
          DIndex PIndex Z0Index Z0PrimeIndex S)
        pResidualWeight pStageBlockScale pEntropyConstant
        epsilon2 pStageKappa)
    (postP :
      CMP116Lemma3WeightedPostPSourceScaleBoundary hp
        (cmp116Eq226CenteredConditionedPhysicalContourResummationScaleFamily
          Dict ambient distinguished outerCarrier
          DIndex PIndex Z0Index Z0PrimeIndex S)
        sourceMetric DParts alpha6 eq229Metric pResidualWeight
        postPSourceWeight postPAmplitude) :
    CMP116Lemma3ActivityEstimateScaleFamily
      (cmp116Eq226CenteredConditionedPhysicalContourActivityScaleFamily
        Dict ambient distinguished outerCarrier
        DIndex PIndex Z0Index Z0PrimeIndex S)
      sourceMetric
      (fun t k => (hp t k).blockScale)
      (fun t k => (hp t k).C3)
      (fun t k => (hp t k).epsilon1)
      (fun t k => (hp t k).delta)
      (fun t k => (hp t k).kappa) :=
  CMP116Lemma3WeightedPostPScaleSourceAssumptions.lemma3_activity_estimate_of_boundaries
    eq229 pStage postP
    (cmp116Eq226CenteredConditionedPhysicalContour_activityTermwiseScaleBoundary
      Dict ambient distinguished outerCarrier
      DIndex PIndex Z0Index Z0PrimeIndex S)

end

end YangMills.RG
