import YangMills.RG.BalabanCMP116Eq226CenteredConditionedCombinedSourcePreEq136
import YangMills.RG.BalabanCMP116InteractingPhysicalPrecisionSourceAudit

/-!
The preceding assembler audit was compiler-verified at source checkpoint
`7fb235a3c86d3077b3d978a24a5623cd562eef9c`.  The interacting-precision
declarations below were compiler-verified from one fresh Colab CPU/high-RAM
clone at source checkpoint `5b061eb968885f5d724dc3b9226ee593ddc5d0db`.
-/

#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.total
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.residual
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.sourceRange_bound
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.finiteRange
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.coercivity_pos
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.K_coercive
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.K_comp_interactingCovariance
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.E0
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.threshold
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.alpha
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.rootBound
#print axioms YangMills.RG.CMP116CenteredConditionedCombinedSourceData.volumeRate
#print axioms YangMills.RG.cmp116Eq226CenteredConditionedCombinedSourcePreEq136
