import YangMills.RG.BalabanCMP99SourceOperatorCoarseRegionDiameter

open YangMills.RG

#print axioms activeGaugeRegionSiteFinBoxDist
#print axioms CMP99SourceDependentOmegaGeometry.operatorCoarseRegion_siteFinBoxDist_le_pi5
