import YangMills.RG.BalabanCMP116SourcePi4MixedWeakenedCovarianceDerivative

#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_empty
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_singleton
#print axioms YangMills.RG.hasDerivAt_cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_update
