import YangMills.RG.BalabanCMP99SourceFlatUbarPreservation

#print axioms YangMills.RG.cmp99SourceBaseCoarseBackground_flat_apply_pos
#print axioms YangMills.RG.UbarDeviation_cmp99SourceFlatGaugeConfig
#print axioms YangMills.RG.cmp99UbarSpecialUnitaryExponent_eq_zero_of_eq_one
#print axioms YangMills.RG.cmp99PhysicalUbarBlockOfDeviationBudget_flat
#print axioms YangMills.RG.cmp99PhysicalUbarGaugeConfigOfDeviationBudget_flat
