import YangMills.RG.BalabanCMP99SourceEq395RegionalMiddleCommutatorDecay

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceMiddleAmbient_eq_extend_onSource
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceMiddleAmbient_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalMiddle_smoothCommutator_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_exponentialKernelBound
