import YangMills.RG.BalabanCMP116Eq214PhysicalContourPotential

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.withPhysicalComplexTauPotential_potential
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.re_withPhysicalComplexTauPotential_potential_le_projection
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.withPhysicalComplexTauPotential_r1Matrix
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.withPhysicalComplexTauPotential_r2Matrix
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.withPhysicalComplexTauPotential_r3Matrix
