import YangMills.RG.BalabanCMP99SourceGeneratedRegionalCorrectionDecay

/-!
# Audit for the physical single-cell regional correction

-/

#print axioms YangMills.RG.CMP99RegionalFineSquarePartition.norm_value_le_one
#print axioms YangMills.RG.finBoxDist_exp_sum_le_cmp99OmegaSiteExpSumBound_any
#print axioms YangMills.RG.finitePiLpExponentialKernelBound_comp_finBox
#print axioms YangMills.RG.cmp99RegionalDirichletPrecision_exponentialKernelBound
#print axioms YangMills.RG.cmp99RegionalDirichletGreen_exponentialKernelBound
#print axioms YangMills.RG.cmp99RegionalExtendedDirichletGreen_exponentialKernelBound
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalAmbientPrecisionDecayAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalAmbientPrecision_exponentialKernelBound
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCell
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCell_hasFiniteRangeMargin
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalGreenRate
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalGreenRate_pos
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCorrectionAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalExtendedGreen_exponentialKernelBound
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCorrection
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCorrection_exponentialKernelBound
