import YangMills.RG.BalabanCMP99SourceGeneratedSectionCCommutatorSupportWeightedRow

#print axioms YangMills.RG.cmp99SourceGeneratedCMP95SmoothCommutatorSupportWeightedRowAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_apply_single_eq_zero_of_target
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCCommutatorTargetSites
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.mem_generatedCMP95SectionCCommutatorTargetSites_iff
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.card_generatedCMP95SectionCCommutatorTargetSites_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_weightedRow_supportSharp
