/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116CorrelatedGaussian

/-!
# Carrier support of a finite correlated Gaussian

The conditioned field in CMP116 (2.23) is integrated against a Gaussian whose
covariance root has image in the physical carrier `Z0`.  Bounds on the
integrand therefore need to hold only almost everywhere on that carrier, not
for arbitrary ambient coordinate vectors.

This file proves the exact pushforward statement.  It does not assert that a
particular CMP116 root has the required row support; that source
identification remains a separate operator theorem.
-/

namespace YangMills.RG

open MeasureTheory Matrix

noncomputable section

/-- A matrix has image in `S` when every row outside `S` vanishes. -/
def MatrixRangeSupportedOn
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (R : Matrix ι ι ℝ) (S : Finset ι) : Prop :=
  ∀ i, i ∉ S → ∀ j, R i j = 0

/-- A vector is supported on the finite carrier `S`. -/
def VectorSupportedOn
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) (x : ι → ℝ) : Prop :=
  ∀ i, i ∉ S → x i = 0

theorem MatrixRangeSupportedOn.mulVec_supported
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {R : Matrix ι ι ℝ} {S : Finset ι}
    (hR : MatrixRangeSupportedOn R S) (x : ι → ℝ) :
    VectorSupportedOn S (R *ᵥ x) := by
  intro i hi
  simp [Matrix.mulVec, dotProduct, hR i hi]

/-- A correlated Gaussian generated by a root whose image lies in `S` is
almost surely supported on `S`. -/
theorem ae_vectorSupportedOn_matrixGaussianPi
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (R : Matrix ι ι ℝ) (S : Finset ι)
    (hR : MatrixRangeSupportedOn R S) :
    ∀ᵐ x ∂matrixGaussianPi R, VectorSupportedOn S x := by
  have hmeas : MeasurableSet {x : ι → ℝ | VectorSupportedOn S x} := by
    rw [show {x : ι → ℝ | VectorSupportedOn S x} =
        ⋂ i : ι, ⋂ (_hi : i ∉ S), {x : ι → ℝ | x i = 0} by
      ext x
      simp [VectorSupportedOn]]
    exact MeasurableSet.iInter fun i =>
      MeasurableSet.iInter fun hi => by measurability
  rw [matrixGaussianPi]
  rw [ae_map_iff
    (show AEMeasurable (matrixMulVecCLM R)
      (standardGaussianPi ι) from by fun_prop)
    hmeas]
  exact Filter.Eventually.of_forall fun x =>
    hR.mulVec_supported x

/-- On the supported Gaussian, the ambient squared norm is exactly the
carrier energy. -/
theorem ae_sum_sq_eq_sum_mem_matrixGaussianPi
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (R : Matrix ι ι ℝ) (S : Finset ι)
    (hR : MatrixRangeSupportedOn R S) :
    ∀ᵐ x ∂matrixGaussianPi R,
      (∑ i, x i ^ 2) = ∑ i ∈ S, x i ^ 2 := by
  filter_upwards [ae_vectorSupportedOn_matrixGaussianPi R S hR] with x hx
  rw [← Finset.sum_subset (Finset.subset_univ S)]
  intro i hi hiS
  simp [hx i hiS]

end

end YangMills.RG
