import YangMills.RG.BalabanCMP89Eq246StabilizedAliasTransposeFullSolution

/-!
# Axiom audit: arbitrary-source transposed Eq. (2.46) fibre
-/

#print axioms YangMills.RG.cmp89Eq246CentralAverageColumn_ne_zero_of_pair_ne_zero
#print axioms YangMills.RG.cmp89Eq246StabilizedAliasTransposeNoncentralSourceMoment
#print axioms YangMills.RG.cmp89Eq246StabilizedAliasTransposeFullSolutionMoment
#print axioms YangMills.RG.cmp89Eq246StabilizedAliasTransposeFullSolution
#print axioms YangMills.RG.sum_column_mul_cmp89Eq246StabilizedAliasTransposeFullSolution_eq
#print axioms YangMills.RG.cmp89Eq246EntireAliasPrecisionMatrix_transpose_mulVec_stabilizedFullSolution
