import YangMills.RG.BalabanCMP99Eq360ComplexClosedPhysicalPrecision

#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.background0
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.background1
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.towerPair
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.baselineLaplacian
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.perturbedLaplacian
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.localLaplacianPerturbation
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.baselinePrecision
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.perturbedPrecision
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.precisionPerturbation
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.sourcePrecisionPerturbation
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.precisionPerturbation_eq_sourcePrecisionPerturbation
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.perturbedPrecision_eq_baselinePrecision_sub_perturbation
#print axioms YangMills.RG.CMP99Eq360ComplexClosedPhysicalInput.perturbedPrecision_eq_baselinePrecision_sub_sourcePerturbation
