import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedFlatPhysicalPointSourceOwnerBound

#print axioms YangMills.RG.norm_tsum_cmp99SourceSeparatedGeneratedFlatPhysicalGreen_zeroResidue_le_owner
#print axioms YangMills.RG.norm_cmp99SourceSeparatedGeneratedFlatPhysicalGreenQprimeStar_pointSource_apply_le_owner
