/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116CorrelatedGaussian

/-!
# Carrier support of a finite correlated Gaussian

The conditioned field in CMP116 (2.23) is integrated against a Gaussian whose
covariance root has image in the physical carrier `Z0`.  Bounds on the
integrand therefore need to hold only almost everywhere on that carrier, not
for arbitrary ambient coordinate vectors.

This file proves the exact pushforward statement.  It does not assert that a
particular CMP116 root has the required row support; that source
identification remains a separate operator theorem.
-/

namespace YangMills.RG

open MeasureTheory Matrix

noncomputable section

/-- A matrix has image in `S` when every row outside `S` vanishes. -/
def MatrixRangeSupportedOn
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (R : Matrix ι ι ℝ) (S : Finset ι) : Prop :=
  ∀ i, i ∉ S → ∀ j, R i j = 0

/-- A vector is supported on the finite carrier `S`. -/
def VectorSupportedOn
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) (x : ι → ℝ) : Prop :=
  ∀ i, i ∉ S → x i = 0

/-- A supported vector has no ambient energy outside its carrier. -/
theorem VectorSupportedOn.sum_sq_eq_sum_mem
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {S : Finset ι} {x : ι → ℝ}
    (hx : VectorSupportedOn S x) :
    (∑ i, x i ^ 2) = ∑ i ∈ S, x i ^ 2 := by
  rw [← Finset.sum_subset (Finset.subset_univ S)]
  intro i hi hiS
  simp [hx i hiS]

theorem MatrixRangeSupportedOn.mulVec_supported
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {R : Matrix ι ι ℝ} {S : Finset ι}
    (hR : MatrixRangeSupportedOn R S) (x : ι → ℝ) :
    VectorSupportedOn S (R *ᵥ x) := by
  intro i hi
  simp [Matrix.mulVec, dotProduct, hR i hi]

/-- A real self-adjoint square root cannot acquire rows outside the exact
carrier of its square.  Only the diagonal support of `C` is used. -/
theorem MatrixRangeSupportedOn.of_symmetric_square
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {R C : Matrix ι ι ℝ} {S : Finset ι}
    (hR : R.transpose = R)
    (hsq : R * R = C)
    (hC : MatrixRangeSupportedOn C S) :
    MatrixRangeSupportedOn R S := by
  intro i hi j
  have hsymm : ∀ k, R k i = R i k := by
    intro k
    have h := congrFun (congrFun hR k) i
    simpa using h.symm
  have hsum : (∑ k, R i k ^ 2) = 0 := by
    calc
      (∑ k, R i k ^ 2) = (R * R) i i := by
        simp [Matrix.mul_apply, hsymm, pow_two]
      _ = C i i := by rw [hsq]
      _ = 0 := hC i hi i
  have hj : R i j ^ 2 = 0 := by
    refine (Finset.sum_eq_zero_iff_of_nonneg ?_).mp hsum
      j (Finset.mem_univ j)
    intro k hk
    exact sq_nonneg _
  exact sq_eq_zero_iff.mp hj

/-- Exact finite-dimensional semantics of a conditioned Gaussian root:
`R` is a real self-adjoint square root of a covariance carried by `S`. -/
structure MatrixConditionedGaussianRootCertificate
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (C R : Matrix ι ι ℝ) (S : Finset ι) : Prop where
  root_symmetric : R.transpose = R
  root_square : R * R = C
  covariance_supported : MatrixRangeSupportedOn C S

/-- Quantitative nondegeneracy of a conditioned covariance on its physical
carrier.  This certificate is deliberately separate from the upper/smallness
certificate: it prevents an almost-everywhere interaction obligation from
being discharged by choosing the zero Gaussian root. -/
structure MatrixConditionedGaussianCovarianceLowerCertificate
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (C : Matrix ι ι ℝ) (S : Finset ι) where
  lowerBound : ℝ
  lowerBound_pos : 0 < lowerBound
  carrier_nonempty : S.Nonempty
  covariance_lower : ∀ v : ι → ℝ, VectorSupportedOn S v →
    lowerBound * dotProduct v v ≤ dotProduct v (C.mulVec v)

/-- The conditioned-root certificate generates exact carrier support of the
Gaussian coordinate map. -/
theorem MatrixConditionedGaussianRootCertificate.root_supported
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {C R : Matrix ι ι ℝ} {S : Finset ι}
    (h : MatrixConditionedGaussianRootCertificate C R S) :
    MatrixRangeSupportedOn R S :=
  MatrixRangeSupportedOn.of_symmetric_square
    h.root_symmetric h.root_square h.covariance_supported

/-- A correlated Gaussian generated by a root whose image lies in `S` is
almost surely supported on `S`. -/
theorem ae_vectorSupportedOn_matrixGaussianPi
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (R : Matrix ι ι ℝ) (S : Finset ι)
    (hR : MatrixRangeSupportedOn R S) :
    ∀ᵐ x ∂matrixGaussianPi R, VectorSupportedOn S x := by
  have hmeas : MeasurableSet {x : ι → ℝ | VectorSupportedOn S x} := by
    rw [show {x : ι → ℝ | VectorSupportedOn S x} =
        ⋂ i : ι, ⋂ (_hi : i ∉ S), {x : ι → ℝ | x i = 0} by
      ext x
      simp [VectorSupportedOn]]
    exact MeasurableSet.iInter fun i =>
      MeasurableSet.iInter fun hi => by measurability
  rw [matrixGaussianPi]
  rw [ae_map_iff
    (show AEMeasurable (matrixMulVecCLM R)
      (standardGaussianPi ι) from by fun_prop)
    hmeas]
  exact Filter.Eventually.of_forall fun x =>
    hR.mulVec_supported x

/-- Consequently the conditioned Gaussian itself is almost surely carried
by the physical coordinate set. -/
theorem MatrixConditionedGaussianRootCertificate.ae_supported
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {C R : Matrix ι ι ℝ} {S : Finset ι}
    (h : MatrixConditionedGaussianRootCertificate C R S) :
    ∀ᵐ x ∂matrixGaussianPi R, VectorSupportedOn S x :=
  ae_vectorSupportedOn_matrixGaussianPi R S h.root_supported

/-- On the supported Gaussian, the ambient squared norm is exactly the
carrier energy. -/
theorem ae_sum_sq_eq_sum_mem_matrixGaussianPi
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (R : Matrix ι ι ℝ) (S : Finset ι)
    (hR : MatrixRangeSupportedOn R S) :
    ∀ᵐ x ∂matrixGaussianPi R,
      (∑ i, x i ^ 2) = ∑ i ∈ S, x i ^ 2 := by
  filter_upwards [ae_vectorSupportedOn_matrixGaussianPi R S hR] with x hx
  exact hx.sum_sq_eq_sum_mem

end

end YangMills.RG
