import YangMills.RG.BalabanCMP89NeumannReflectionBranchSum

/-!
# CMP89 (2.42): algebra of the one-coordinate reflection orbit

PRE-VALIDATION: source is present, its `.olean` has not yet been materialized,
and no result in this module is compiler-verified.

After division by the printed lattice spacing `xi`, the two reflected
coordinates in CMP89 (2.42) are

`n |-> -n-1` and `n |-> 2*m-1-n`.

Their orbit has two parity branches, `2*k*m+n` and `2*k*m-n-1`, indexed by
`k : Int`.  This file records only that exact integer algebra, coordinate by
coordinate.  It does not identify the source rectangle, prove that the Green
kernel equals its image series, establish summability or distance decay, or
choose between any competing endpoint convention not fixed by (2.42).
-/

namespace YangMills.RG

/-- Reflection across the lower free boundary, in lattice-index units. -/
def cmp89NeumannLeftReflection (n : ℤ) : ℤ := -n - 1

/-- Reflection across the upper free boundary printed in (2.42), in
lattice-index units `m = M/xi`. -/
def cmp89NeumannRightReflection (m n : ℤ) : ℤ := 2 * m - 1 - n

/-- The two one-dimensional image branches generated by the printed
reflections.  `false` is the untranslated orientation and `true` is the
reflected orientation. -/
def cmp89NeumannReflectionOrbit (m n k : ℤ) (reflected : Bool) : ℤ :=
  if reflected then 2 * k * m - n - 1 else 2 * k * m + n

@[simp] theorem cmp89NeumannReflectionOrbit_false (m n k : ℤ) :
    cmp89NeumannReflectionOrbit m n k false = 2 * k * m + n := by
  rfl

@[simp] theorem cmp89NeumannReflectionOrbit_true (m n k : ℤ) :
    cmp89NeumannReflectionOrbit m n k true = 2 * k * m - n - 1 := by
  rfl

/-- The lower reflection exchanges the two branches and sends `k` to `-k`.
-/
theorem cmp89NeumannLeftReflection_orbit_false (m n k : ℤ) :
    cmp89NeumannLeftReflection
        (cmp89NeumannReflectionOrbit m n k false) =
      cmp89NeumannReflectionOrbit m n (-k) true := by
  simp [cmp89NeumannLeftReflection]
  ring

theorem cmp89NeumannLeftReflection_orbit_true (m n k : ℤ) :
    cmp89NeumannLeftReflection
        (cmp89NeumannReflectionOrbit m n k true) =
      cmp89NeumannReflectionOrbit m n (-k) false := by
  simp [cmp89NeumannLeftReflection]
  ring

/-- The upper reflection exchanges the two branches and sends `k` to
`1-k`. -/
theorem cmp89NeumannRightReflection_orbit_false (m n k : ℤ) :
    cmp89NeumannRightReflection m
        (cmp89NeumannReflectionOrbit m n k false) =
      cmp89NeumannReflectionOrbit m n (1 - k) true := by
  simp [cmp89NeumannRightReflection]
  ring

theorem cmp89NeumannRightReflection_orbit_true (m n k : ℤ) :
    cmp89NeumannRightReflection m
        (cmp89NeumannReflectionOrbit m n k true) =
      cmp89NeumannReflectionOrbit m n (1 - k) false := by
  simp [cmp89NeumannRightReflection]
  ring

/-- Alternating the lower then upper reflection increments the translation
index on the unreflected branch. -/
theorem cmp89NeumannRight_left_orbit_false (m n k : ℤ) :
    cmp89NeumannRightReflection m
        (cmp89NeumannLeftReflection
          (cmp89NeumannReflectionOrbit m n k false)) =
      cmp89NeumannReflectionOrbit m n (k + 1) false := by
  simp [cmp89NeumannLeftReflection, cmp89NeumannRightReflection]
  ring

/-- Alternating the upper then lower reflection decrements the translation
index on the unreflected branch. -/
theorem cmp89NeumannLeft_right_orbit_false (m n k : ℤ) :
    cmp89NeumannLeftReflection
        (cmp89NeumannRightReflection m
          (cmp89NeumannReflectionOrbit m n k false)) =
      cmp89NeumannReflectionOrbit m n (k - 1) false := by
  simp [cmp89NeumannLeftReflection, cmp89NeumannRightReflection]
  ring

/-- Coordinatewise `d`-dimensional reflection image: one Boolean parity
choice and one integer translation index per coordinate. -/
def cmp89NeumannReflectionImage {d : ℕ}
    (m n k : Fin d → ℤ) (branch : CMP89NeumannReflectionBranch d) :
    Fin d → ℤ :=
  fun mu => cmp89NeumannReflectionOrbit (m mu) (n mu) (k mu) (branch mu)

@[simp] theorem cmp89NeumannReflectionImage_apply {d : ℕ}
    (m n k : Fin d → ℤ) (branch : CMP89NeumannReflectionBranch d)
    (mu : Fin d) :
    cmp89NeumannReflectionImage m n k branch mu =
      cmp89NeumannReflectionOrbit (m mu) (n mu) (k mu) (branch mu) := by
  rfl

end YangMills.RG
