import YangMills.RG.BalabanCMP99SourceEq395PatchedCovarianceDecay

#print axioms YangMills.RG.cmp99SourceSquarePartition_sum_norm_mul_norm_le_one
#print axioms YangMills.RG.finitePiLpExponentialKernelBound_squarePartition_sum
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalPatchedCovariance_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrectedCovariance_exponentialKernelBound
