import YangMills.RG.BalabanCMP99SourceCommonTowerMass

namespace YangMills.RG

#print axioms CMP99SourceCommonTowerScaleIdentification.Qprime
#print axioms CMP99SourceCommonTowerScaleIdentification.gaugePrecision
#print axioms CMP99SourceCommonTowerScaleIdentification.spacingPairing_gaugePrecision
#print axioms CMP99SourceCommonTowerScaleIdentification.gaugePrecision_isCoercive
#print axioms CMP99SourceCommonTowerScaleIdentification.gaugePrecision_isSymmetric
#print axioms CMP99SourceCommonTowerScaleIdentification.green
#print axioms CMP99SourceCommonTowerScaleIdentification.gaugePrecision_comp_green
#print axioms CMP99SourceCommonTowerScaleIdentification.green_comp_gaugePrecision
#print axioms CMP99SourceCommonTowerScaleIdentification.green_isSymmetric
#print axioms CMP99SourceCommonTowerScaleIdentification.stratumAverage
#print axioms CMP99SourceCommonTowerScaleIdentification.stratumCoarseCovariance
#print axioms CMP99SourceCommonTowerScaleIdentification.inner_stratumCoarseCovariance
#print axioms CMP99SourceCommonTowerScaleIdentification.inner_stratumCoarseCovariance_nonneg
#print axioms CMP99SourceCommonTowerScaleIdentification.Qprime_apply

end YangMills.RG
