import YangMills.RG.BalabanCMP99SourceDependentRegionalTower

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.operatorCoarseRegion_sites
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.operatorRegion_zero
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.operatorRegion_blockSaturated
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.activeCoarseRegion_operatorRegion_succ_eq
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.retainedPhysicalTower
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.retainedPhysicalTower_prefix_depth
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.retainedPhysicalTower_Qprime_succ
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.retainedPhysicalTower_prefix_comp_weightedAdjoint
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.retainedPhysicalTower_weightedAdjoint_norm
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.retainedPhysicalTower_normalization_eq_one_pos
