import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedFlatPhysicalAmbientGreen

#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalAmbientPrecision
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalAmbientPrecision_eq_reindex
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalAmbientGreen
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalAmbientPrecision_comp_green
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalAmbientGreen_comp_precision
