import YangMills.RG.BalabanCMP89Eq246MassUniformPhysicalContour

/-! Axiom audit for the mass-uniform physical contour. -/

#print axioms YangMills.RG.integrable_cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand_massUniform
#print axioms YangMills.RG.integral_cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand_stage_succ_massUniform
#print axioms YangMills.RG.integral_cmp89Eq246PhysicalFineToFineGreenPartialProductIntegrand_zero_eq_four_massUniform
#print axioms YangMills.RG.integral_cmp89Eq246PhysicalFineToFineGreenIntegrand_eq_signed_massUniform
#print axioms YangMills.RG.cmp89Eq246DirectedNormalizedFullSolutionIntegral_physicalFine_eq_zero_massUniform
#print axioms YangMills.RG.cmp89Eq246DirectedNormalizedPhysicalFineKernel_eq_zero_massUniform
#print axioms YangMills.RG.norm_cmp89Eq246NormalizedPhysicalFineToFineGreen_le_massUniform
