import YangMills.RG.BalabanCMP89Eq246MassUniformCenteredGreenFourierSummability

/-!
# Axiom audit for full-G centered-torus Fourier summability
-/

#print axioms YangMills.RG.cmp89Eq246_affineTarget_sub_source
#print axioms YangMills.RG.cmp89Eq246PhysicalFineGreenDecay_eq_signedLatticeWeight_massUniform
#print axioms YangMills.RG.summable_cmp89Eq246CenteredFullGreenPhysicalFourierCoefficient_massUniform
#print axioms YangMills.RG.summable_mFourierCoeff_cmp89Eq246CenteredFullGreenTorus_massUniform
