import YangMills.RG.BalabanCMP116CenteredConditionedSmallnessCompatibility

#print axioms YangMills.RG.cmp116CenteredSmallnessWitness_shell
#print axioms YangMills.RG.cmp116CenteredSmallnessWitness_contourRatio
#print axioms YangMills.RG.cmp116CenteredSmallnessWitness_contourDefect
#print axioms YangMills.RG.cmp116CenteredSmallnessWitness_walk
#print axioms YangMills.RG.cmp116CenteredSmallnessWitness_rootedAnimal
#print axioms YangMills.RG.cmp116CenteredSmallnessWitness_animal
#print axioms YangMills.RG.cmp116CenteredConditionedJointSmallnessRegimeWitness
#print axioms YangMills.RG.cmp116CenteredConditioned_scalarSmallness_nonempty
