/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116ActiveDeterminantBound
import YangMills.RG.BalabanCMP116SourceRestrictedVisitedDeterminantPhysical

/-!
# Localized bound for the physical restricted-contour determinant density

The exact source determinant identity is now converted into a quantitative
bound.  Crucially, its exponent is the cardinality of the finite active-state
type generated by the contour carrier.  The ambient lattice dimension never
appears.

No norm estimate for the reduced active matrix is assumed.  The rectangular
characteristic-polynomial identity transports its nonzero eigenvalues to the
literal physical relative covariance defect, whose Neumann smallness is
already produced by the source contour construction.

This theorem is deliberately not advertised as the final polymer-volume
bound.  The transfer state remembers a subset of the contour carrier, so its
unreduced state count still contains powerset multiplicity.  A later
trace/walk localization or a smaller determinant realization is required
before replacing this exponent by a constant times the polymer cardinality.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

attribute [local instance] Classical.propDecidable

private abbrev PhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

/-- The finite state type on which the source-restricted contour determinant
is evaluated: active heads and active transfer targets, each paired with one
physical scalar coordinate. -/
abbrev CMP116SourceRestrictedActiveDeterminantState
    {M Q Nc : ℕ} [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (carrier : Finset (FinBox 4 (2 * Q))) :=
  Sum
    ({head : ↥(cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q)) //
      cmp116RestrictedHeadActive carrier
        (cmp116SourcePi4RestrictedDomainActive anchor) head} ×
      CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc)
    ({target :
        CMP116RestrictedTransferState Unit
          ↥(cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q)) carrier //
      cmp116RestrictedTransferTargetActive carrier
        (cmp116SourcePi4RestrictedDomainActive anchor) target} ×
      CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc)

set_option maxHeartbeats 2000000

/-- The literal physical relative covariance smallness bounds the logarithmic
contour density with an exponent equal to the source active-state count. -/
theorem norm_cmp116SourceRestrictedContour_logDetDensity_le_activeState
    {nContour M Q Nc R Δ : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    (carrier : Finset (FinBox 4 (2 * Q)))
    (e : Fin nContour ≃ ↥carrier)
    (z : Fin nContour → ℂ)
    (hsmall :
      ‖cmp116SourcePi4FullComplexRelativeCovarianceDefect
        (R := R) anchor K hc hmass hK
          (cmp116SourceRestrictedShiftedCoupling carrier e z)‖ < 1)
    {Ahead rho rate : ℝ}
    (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
      PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (Rweak : ℝ) (hRweak : 1 ≤ Rweak)
    (hcap : ∀ d ∈ carrier,
      ‖cmp116SourceRestrictedShiftedCoupling carrier e z d‖ ≤ Rweak)
    (hseries :
      (cmp116SourcePi4TerminalBranching Δ : ℝ) *
        rho * Rweak ^ 10000 < 1) :
    ‖cmp116Eq214LogDeterminantDensity
        (cmp116PhysicalEndomorphismComplexMatrix K)
        (cmp116SourcePi4FullComplexWeakenedPrecisionMatrix
          (R := R) anchor K hc hmass hK
            (cmp116SourceRestrictedShiftedCoupling carrier e z))‖ ≤
      ((1 -
          ‖cmp116SourcePi4FullComplexRelativeCovarianceDefect
            (R := R) anchor K hc hmass hK
              (cmp116SourceRestrictedShiftedCoupling carrier e z)‖) ^
        Fintype.card
          (CMP116SourceRestrictedActiveDeterminantState
            (M := M) (Nc := Nc) anchor carrier))⁻¹ := by
  let sigma :=
    cmp116SourceRestrictedShiftedCoupling carrier e z
  let domainActive :=
    cmp116SourcePi4RestrictedDomainActive anchor
  let successors :=
    cmp99PhysicalPatchSuccessorSteps
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      (cmp99SourcePi4ChartCore (M := M))
      cmp99SourcePi4ChartEnlarged physicalBondDist R
  let R0 :=
    cmp116SourcePi4RestrictedHeadMatrix K hc hmass hK
  let continuation :=
    cmp116SourcePi4RestrictedContinuationMatrix K hc hmass hK
  let Tnew :=
    cmp116RestrictedVisitedTransferMatrix
      carrier domainActive successors continuation sigma
  let Tbase :=
    cmp116RestrictedVisitedTransferMatrix
      carrier domainActive successors continuation (fun _ => 1)
  let Nnew :=
    cmp116RestrictedVisitedTransferResolvent
      carrier domainActive successors continuation sigma
  let Nbase :=
    cmp116RestrictedVisitedTransferResolvent
      carrier domainActive successors continuation (fun _ => 1)
  let p :=
    cmp116RestrictedTransferTargetActive
      (Label := Unit) carrier domainActive
  let AHead :=
    cmp116RestrictedHeadDefectLeft carrier domainActive R0 sigma
  let BHead :=
    cmp116RestrictedHeadDefectRight
      (Label := Unit) carrier domainActive Nnew
  let ADynamic :=
    cmp116RestrictedHeadReadoutProductLeft
      carrier domainActive R0 (fun _ => 1)
      (Nnew * Matrix.predicateColumnRestriction p (Tnew - Tbase))
  let BDynamic :=
    cmp116RestrictedHeadReadoutProductRight
      carrier
      (Matrix.predicateColumnInclusion
        (R := Matrix
          (CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc)
          (CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc) ℂ)
        p * Nbase)
  let A := Matrix.sumFactorLeft AHead ADynamic
  let B := Matrix.sumFactorRight BHead BDynamic
  let Kmat := cmp116PhysicalEndomorphismComplexMatrix K
  let density :=
    cmp116Eq214LogDeterminantDensity Kmat
      (cmp116SourcePi4FullComplexWeakenedPrecisionMatrix
        (R := R) anchor K hc hmass hK sigma)
  have hsum :
      Summable fun n : ℕ => Tnew ^ n := by
    exact
      summable_cmp116SourcePi4RestrictedVisitedTransferMatrix_pow
        anchor K hsourceRange hc hmass hK hrho hrate hgeom Cert htri
        hΔ hΔ1 carrier sigma Rweak hRweak hcap hseries
  have hcapOne : ∀ d ∈ carrier, ‖(1 : ℂ)‖ ≤ Rweak := by
    intro d hd
    simpa using hRweak
  have hsumOne :
      Summable fun n : ℕ => Tbase ^ n := by
    exact
      summable_cmp116SourcePi4RestrictedVisitedTransferMatrix_pow
        anchor K hsourceRange hc hmass hK hrho hrate hgeom Cert htri
        hΔ hΔ1 carrier (fun _ => 1)
        Rweak hRweak hcapOne hseries
  have hfactor :
      cmp116SourcePi4FullComplexRelativeCovarianceDefect
          (R := R) anchor K hc hmass hK sigma =
        (Kmat * A) * B := by
    exact
      cmp116SourcePi4FullComplexRelativeCovarianceDefect_restricted_eq_finiteFactorization
        anchor K hc hmass hK carrier e z hsum hsumOne
  have hexact :
      density ^ 2 * (1 + B * (Kmat * A)).det = 1 := by
    exact
      cmp116SourceRestrictedContour_logDetDensity_sq_mul_activeStateDet_eq_one
        anchor K hsourceRange hrange hc hmass hK hD carrier e z hsmall
        hsum hsumOne
  have hrectSmall : ‖(Kmat * A) * B‖ < 1 := by
    rw [← hfactor]
    exact hsmall
  have hbound :=
    Matrix.norm_density_le_inv_one_sub_ambient_norm_pow_activeCard
      density (Kmat * A) B hrectSmall hexact
  rw [← hfactor] at hbound
  simpa [sigma, domainActive, successors, R0, continuation, Tnew, Tbase,
    Nnew, Nbase, p, AHead, BHead, ADynamic, BDynamic, A, B, Kmat,
    density, CMP116SourceRestrictedActiveDeterminantState] using hbound

end

end YangMills.RG
