/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceRegionalCoarseAverage
import YangMills.RG.SUNAdjointModelInstance

/-!
# Adjoint holonomy transport for the regional CMP99 average

The one-scale regional average was first constructed for arbitrary real-linear
isometric transports.  This file supplies the physical transport functor:
every `SU(Nc)` holonomy acts on the fixed `su(Nc)` coordinate model by an
explicit linear isometric equivalence, with inverse given by the inverse
holonomy.  The regional block average and synthesis are then specialized to a
group-valued holonomy kernel.

Honest scope: `holonomy y x` is still supplied as group-valued data.  This file
does not construct the printed contour `Gamma^(j)_{y,x}` from lattice paths,
does not prove its gauge covariance, and does not build the recursive
backgrounds entering `Q'_j`.  It removes only the artificial isometry-valued
parameter: once a source holonomy is supplied, the transport used by the
average is now definitionally the true adjoint action.
-/

namespace YangMills.RG

open scoped RealInnerProductSpace

noncomputable section

namespace SUNAdjointModel

variable {Nc : ℕ} [NeZero Nc]

/-- The adjoint action of a group element, bundled with the inverse action as
a real-linear isometric equivalence. -/
noncomputable def adLinearIsometryEquiv
    (rho : SUNAdjointModel Nc) (u : SUN Nc) :
    SUNLieCoord Nc ≃ₗᵢ[ℝ] SUNLieCoord Nc where
  toLinearEquiv :=
    { toFun := rho.adCLM u
      invFun := rho.adCLM u⁻¹
      left_inv := rho.ad_inv_apply_ad u
      right_inv := rho.ad_apply_ad_inv u
      map_add' := map_add (rho.adCLM u)
      map_smul' := map_smul (rho.adCLM u) }
  norm_map' := rho.norm_ad u

@[simp] theorem adLinearIsometryEquiv_apply
    (rho : SUNAdjointModel Nc) (u : SUN Nc) (X : SUNLieCoord Nc) :
    rho.adLinearIsometryEquiv u X = rho.adCLM u X := rfl

@[simp] theorem adLinearIsometryEquiv_symm_apply
    (rho : SUNAdjointModel Nc) (u : SUN Nc) (X : SUNLieCoord Nc) :
    (rho.adLinearIsometryEquiv u).symm X = rho.adCLM u⁻¹ X := rfl

end SUNAdjointModel

variable {d M N' Nc : ℕ} [NeZero M] [NeZero N'] [NeZero Nc]

/-- The physical transport family generated by a group-valued holonomy
kernel. -/
noncomputable def cmp99AdjointBlockTransport
    (rho : SUNAdjointModel Nc)
    (holonomy : FinBox d N' → FinBox d (M * N') → SUN Nc) :
    FinBox d N' → FinBox d (M * N') →
      (SUNLieCoord Nc ≃ₗᵢ[ℝ] SUNLieCoord Nc) :=
  fun y x => rho.adLinearIsometryEquiv (holonomy y x)

omit [NeZero M] [NeZero N'] in
@[simp] theorem cmp99AdjointBlockTransport_apply
    (rho : SUNAdjointModel Nc)
    (holonomy : FinBox d N' → FinBox d (M * N') → SUN Nc)
    (y : FinBox d N') (x : FinBox d (M * N')) (X : SUNLieCoord Nc) :
    cmp99AdjointBlockTransport rho holonomy y x X =
      rho.adCLM (holonomy y x) X := rfl

/-- The one-scale regional CMP99 average with transport definitionally given
by the adjoint action of the supplied holonomies. -/
noncomputable def cmp99AdjointBlockAverageCLM
    (Omega : ActiveGaugeRegion d (M * N')) (w : ℝ)
    (rho : SUNAdjointModel Nc)
    (holonomy : FinBox d N' → FinBox d (M * N') → SUN Nc) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain
        (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
        (SUNLieCoord Nc) :=
  cmp99TransportedBlockAverageCLM Omega w
    (cmp99AdjointBlockTransport rho holonomy)

/-- Explicit synthesis for the physical adjoint-transport average. -/
noncomputable def cmp99AdjointBlockSynthesisCLM
    (Omega : ActiveGaugeRegion d (M * N')) (hOmega : Omega.BlockSaturated)
    (w : ℝ) (rho : SUNAdjointModel Nc)
    (holonomy : FinBox d N' → FinBox d (M * N') → SUN Nc) :
    ActiveGaugeZeroCochain
        (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
        (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  cmp99TransportedBlockSynthesisCLM Omega hOmega w
    (cmp99AdjointBlockTransport rho holonomy)

/-- Exact normalization for the source-facing adjoint-holonomy
specialization. -/
theorem cmp99AdjointBlockAverage_comp_synthesis
    (Omega : ActiveGaugeRegion d (M * N')) (hOmega : Omega.BlockSaturated)
    (w : ℝ) (rho : SUNAdjointModel Nc)
    (holonomy : FinBox d N' → FinBox d (M * N') → SUN Nc) :
    (cmp99AdjointBlockAverageCLM Omega w rho holonomy).comp
        (cmp99AdjointBlockSynthesisCLM Omega hOmega w rho holonomy) =
      (w ^ 2 * (M : ℝ) ^ d) •
        ContinuousLinearMap.id ℝ
          (ActiveGaugeZeroCochain
            (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
            (SUNLieCoord Nc)) :=
  cmp99TransportedBlockAverage_comp_synthesis Omega hOmega w
    (cmp99AdjointBlockTransport rho holonomy)

end

end YangMills.RG
