import YangMills.RG.BalabanCMP102IntrinsicAmbientCorrectionSourceBudget

#print axioms YangMills.RG.cmp98SourceOuterExpNormBudget_nonneg_of_nonneg
#print axioms YangMills.RG.cmp102SourceAmbientRelativeDeviationLipschitzBudget_nonneg
#print axioms YangMills.RG.cmp102SourceAmbientRelativeDeviationValueBudget_nonneg
#print axioms YangMills.RG.cmp102SourceIntrinsicAmbientCorrectionDerivativeLipschitzBudget_nonneg
#print axioms YangMills.RG.norm_cmp102AmbientRelativeDeviation_sub_le_sourceBudget
#print axioms YangMills.RG.norm_cmp102AmbientRelativeDeviation_le_sourceBudget
#print axioms YangMills.RG.norm_fderiv_cmp102IntrinsicAmbientCorrectionBond_sub_apply_le_sourceBudget
