import YangMills.RG.BalabanCMP102Eq80PhysicalIndexedEq136Residual

#print axioms YangMills.RG.cmp102Eq80PhysicalIndexedCouplingScaledResidual
#print axioms YangMills.RG.abs_half_inner_cmp116RadialTaylorResidualOperator_eq80IndexedPhysicalDomain_le_eq136
