/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99OneScaleRegionalPoincare
import YangMills.RG.BalabanCMP99SourceRetainedPhysicalMass

/-!
# Physical precision on a retained CMP99 source tower

CMP99 (3.23)--(3.24), printed pp. 394--395, uses the Dirichlet operator
`Delta^eta_U = (D^eta_U)^* D^eta_U` on the actual regional fine field.  The
previous retained-tower covariance layer accepted this operator as a
parameter.  Here it is constructed on an arbitrary physical active region,
so it applies directly to every region generated by the recursive source
tower.  Its energy, symmetry, and volume-independent norm bound are derived
from the literal covariant difference.
-/

namespace YangMills.RG

open YangMills
open scoped BigOperators RealInnerProductSpace

noncomputable section

variable {d N Nc : ℕ} [NeZero d] [NeZero N] [NeZero Nc]

/-- The printed scaled covariant derivative with Dirichlet zero extension
on an arbitrary physical active region. -/
noncomputable def cmp99ActiveRegionSourceCovariantD0CLM
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (U : PhysicalGaugeBackground d N Nc)
    (spacing : ℝ) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      PhysicalGaugeOneCochain d N Nc :=
  spacing⁻¹ • (covariantD0CLM rho U).comp (extendZeroZeroCLM Omega)

/-- The literal arbitrary-region Dirichlet covariant Laplacian. -/
noncomputable def cmp99ActiveRegionSourceCovariantLaplacian
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (U : PhysicalGaugeBackground d N Nc)
    (spacing : ℝ) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  (cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing).adjoint.comp
    (cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing)

/-- Exact regional Dirichlet energy identity. -/
theorem inner_cmp99ActiveRegionSourceCovariantLaplacian
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (U : PhysicalGaugeBackground d N Nc)
    (spacing : ℝ)
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    inner ℝ phi
        (cmp99ActiveRegionSourceCovariantLaplacian
          Omega rho U spacing phi) =
      ‖cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing phi‖ ^ 2 := by
  rw [cmp99ActiveRegionSourceCovariantLaplacian,
    ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.adjoint_inner_right, real_inner_self_eq_norm_sq]

/-- Self-adjointness of the physical arbitrary-region Laplacian. -/
theorem cmp99ActiveRegionSourceCovariantLaplacian_isSymmetric
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (U : PhysicalGaugeBackground d N Nc)
    (spacing : ℝ) :
    (cmp99ActiveRegionSourceCovariantLaplacian
      Omega rho U spacing).IsSymmetric := by
  let D := cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing
  intro phi psi
  change inner ℝ ((D.adjoint.comp D) phi) psi =
    inner ℝ phi ((D.adjoint.comp D) psi)
  simp only [ContinuousLinearMap.comp_apply]
  rw [ContinuousLinearMap.adjoint_inner_left,
    ContinuousLinearMap.adjoint_inner_right]

/-- Uniform arbitrary-region bound for the scaled covariant derivative. -/
theorem norm_cmp99ActiveRegionSourceCovariantD0CLM_le
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (U : PhysicalGaugeBackground d N Nc)
    {spacing : ℝ} (hspacing : 0 < spacing) :
    ‖cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing‖ ≤
      2 * Real.sqrt d / spacing := by
  apply ContinuousLinearMap.opNorm_le_bound
  · positivity
  intro phi
  have hD := ContinuousLinearMap.le_opNorm (covariantD0CLM rho U)
    (extendZeroZeroCLM Omega phi)
  have hDnorm := norm_covariantD0CLM_le rho U
  have hext := norm_extendZeroZeroCLM_eq Omega phi
  change ‖spacing⁻¹ • covariantD0CLM rho U
      (extendZeroZeroCLM Omega phi)‖ ≤
    (2 * Real.sqrt d / spacing) * ‖phi‖
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (inv_pos.mpr hspacing)]
  calc
    spacing⁻¹ * ‖covariantD0CLM rho U (extendZeroZeroCLM Omega phi)‖ ≤
        spacing⁻¹ * (‖covariantD0CLM rho U‖ * ‖phi‖) :=
      mul_le_mul_of_nonneg_left (by simpa [hext] using hD)
        (inv_nonneg.mpr hspacing.le)
    _ ≤ spacing⁻¹ * ((2 * Real.sqrt d) * ‖phi‖) := by
      gcongr
    _ = (2 * Real.sqrt d / spacing) * ‖phi‖ := by
      field_simp

/-- B2 upper bound for the physical regional covariant Laplacian.  It is
independent of the active-region cardinality and periodic volume. -/
theorem norm_cmp99ActiveRegionSourceCovariantLaplacian_le
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (U : PhysicalGaugeBackground d N Nc)
    {spacing : ℝ} (hspacing : 0 < spacing) :
    ‖cmp99ActiveRegionSourceCovariantLaplacian Omega rho U spacing‖ ≤
      4 * d / spacing ^ 2 := by
  rw [cmp99ActiveRegionSourceCovariantLaplacian,
    ContinuousLinearMap.norm_adjoint_comp_self]
  have hD := norm_cmp99ActiveRegionSourceCovariantD0CLM_le
    Omega rho U hspacing
  have hsqrt : (Real.sqrt (d : ℝ)) ^ 2 = (d : ℝ) :=
    Real.sq_sqrt (Nat.cast_nonneg d)
  have hbound : 0 ≤ 2 * Real.sqrt d / spacing := by positivity
  calc
    ‖cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing‖ *
        ‖cmp99ActiveRegionSourceCovariantD0CLM Omega rho U spacing‖ ≤
      (2 * Real.sqrt d / spacing) * (2 * Real.sqrt d / spacing) :=
        mul_le_mul hD hD (norm_nonneg _) hbound
    _ = 4 * d / spacing ^ 2 := by
      field_simp [ne_of_gt hspacing]
      nlinarith [hsqrt]

open Matrix
open scoped Matrix.Norms.L2Operator

variable {M : ℕ} [NeZero M]
variable {rho : SUNAdjointModel Nc}
variable {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
variable {background : GaugeConfig d N (SUN Nc)} {depth : ℕ}
variable {T : CMP99SourceRetainedPhysicalTower
  rho Omega M spacing background depth}

namespace CMP99SourceRetainedPhysicalScaleIdentification

universe u v

variable {FineSite : Type u} [DecidableEq FineSite]
variable {ScaleSite : Fin (depth + 1) → Type v}
variable [∀ r, DecidableEq (ScaleSite r)] [∀ r, Fintype (ScaleSite r)]
variable {S : CMP99SourceScaledStratification
  FineSite (depth + 1) ScaleSite}

/-- B1: the full retained precision with its Laplacian generated from the
same physical background and active region as the tower. -/
noncomputable def physicalGaugePrecision
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (a L eta : ℝ) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  I.gaugePrecision
    (cmp99ActiveRegionSourceCovariantLaplacian
      Omega rho background spacing) a L eta

/-- Symmetry is generated internally for the literal physical precision. -/
theorem physicalGaugePrecision_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (a L eta : ℝ) :
    (I.physicalGaugePrecision a L eta).IsSymmetric := by
  exact I.gaugePrecision_isSymmetric _ a L eta
    (cmp99ActiveRegionSourceCovariantLaplacian_isSymmetric
      Omega rho background spacing)

/-- Explicit, volume-independent B2 bound for the complete physical retained
precision. -/
noncomputable def physicalPrecisionUpperBound
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (a L eta : ℝ) : ℝ :=
  1 + 4 * d / spacing ^ 2 +
    ∑ r : Fin (depth + 1),
      |cmp99SourceCountingStratumWeight d a L eta r|

theorem physicalPrecisionUpperBound_pos
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    {a L eta : ℝ} (hspacing : 0 < spacing) :
    0 < I.physicalPrecisionUpperBound a L eta := by
  unfold physicalPrecisionUpperBound
  positivity

/-- The complete retained precision inherits the explicit physical
Laplacian bound; no Laplacian operator or norm certificate is a caller input. -/
theorem norm_physicalGaugePrecision_le_physicalPrecisionUpperBound
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (a L eta : ℝ) (hspacing : 0 < spacing) :
    ‖I.physicalGaugePrecision a L eta‖ ≤
      I.physicalPrecisionUpperBound a L eta := by
  have hbase := I.norm_gaugePrecision_le_precisionUpperBound
    (cmp99ActiveRegionSourceCovariantLaplacian
      Omega rho background spacing) a L eta hspacing
  have hlap := norm_cmp99ActiveRegionSourceCovariantLaplacian_le
    Omega rho background hspacing
  unfold precisionUpperBound at hbase
  unfold physicalGaugePrecision physicalPrecisionUpperBound
  linarith

end CMP99SourceRetainedPhysicalScaleIdentification

end

end YangMills.RG
