/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116Eq226PhysicalContourActivityBoundary

/-!
# Variable-arity equation-(2.26) contour terms

The Cauchy families in one CMP116 term are indexed by its physical gap and
its family of localization domains.  Their cardinalities can vary with
`D`, `P`, `Z₀`, and `Z₀'`.  A source family with globally fixed `nDelta` and
`nY` cannot represent that fact without padding or a false equal-cardinality
assumption.

This file packages both arities inside each term.  After packaging, the
resummation still has the same scalar summands and printed equation-(2.26)
weights, so the existing Lemma-3 boundary consumes it unchanged.  No analytic
estimate is added or renamed.
-/

namespace YangMills.RG

noncomputable section

universe uE uZ uS

/-- One physical contour term with term-dependent outer and inner Cauchy
arities. -/
structure CMP116Eq226VariableArityContourTermSource
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E : Type uE} [Norm E]
    (Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℝ) (q : ℕ)
    (C2 kappa1 delta kappa gamma gk : ℝ)
    (alpha outerBound outerRate sourceRate : ℝ)
    (Y0 P : Finset (Cube d L)) (Z0 : Finset (FinBox d N')) where
  nDelta : ℕ
  nY : ℕ
  data :
    CMP116Eq226PhysicalContourTermSource
      (nDelta := nDelta) (nY := nY)
      (d := d) (M := M) (N' := N') (Nc := Nc)
      (L := L) (lieDim := lieDim) (E := E) Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate Y0 P Z0

namespace CMP116Eq226VariableArityContourTermSource

variable
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E : Type uE} [Norm E]
    {Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim}
    {E0 epsilon1 C1 alpha4 : ℝ} {q : ℕ}
    {C2 kappa1 delta kappa gamma gk : ℝ}
    {alpha outerBound outerRate sourceRate : ℝ}
    {Y0 P : Finset (Cube d L)} {Z0 : Finset (FinBox d N')}

/-- The printed equation-(2.26) weight is inherited from the packaged
physical term. -/
def termWeight
    (S : CMP116Eq226VariableArityContourTermSource (E := E) Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate Y0 P Z0) : ℝ :=
  S.data.termWeight

/-- Packaging variable arities does not add a termwise estimate: the bound is
still generated by the literal physical source record. -/
theorem norm_term_le_termWeight
    (S : CMP116Eq226VariableArityContourTermSource (E := E) Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate Y0 P Z0)
    (psi phi : PhysicalGaugeField d (M * N') Nc) :
    ‖S.data.contour.toLocalFiniteGaussianData.toFiniteGaussianData
        |>.toAnalyticData.term Y0 P psi phi‖ ≤
      S.termWeight :=
  S.data.norm_term_le_termWeight psi phi

end CMP116Eq226VariableArityContourTermSource

/-- A variable-arity source record for every member of one dependent
`D/P/Z0/Z0'` stack. -/
def CMP116Eq226VariableArityContourTermSourceFamily
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E : Type uE} {ιZ0' : Type uZ} [Norm E]
    (Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℝ) (q : ℕ)
    (C2 kappa1 delta kappa gamma gk : ℝ)
    (alpha outerBound outerRate sourceRate : ℝ)
    (σ : Type uS) : Type (max uE uZ uS) :=
  ∀ (_Z : σ) (D P : Finset (Cube d L))
      (Z0 : Finset (FinBox d N')) (_Z0p : ιZ0'),
    CMP116Eq226VariableArityContourTermSource (E := E) Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate D P Z0

/-- Literal complex-contour resummation with the two Cauchy arities hidden
inside each physical term. -/
def cmp116Eq226VariableArityContourResummation
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E ιZ0' σ : Type*} [Norm E] [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℝ) (q : ℕ)
    (C2 kappa1 delta kappa gamma gk : ℝ)
    (alpha outerBound outerRate sourceRate : ℝ)
    (DIndex : σ → Finset (Finset (Cube d L)))
    (PIndex :
      σ → Finset (Cube d L) → Finset (Finset (Cube d L)))
    (Z0Index :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset ιZ0')
    (S : CMP116Eq226VariableArityContourTermSourceFamily
      (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
      (lieDim := lieDim) (E := E) (ιZ0' := ιZ0') Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate σ) :
    CMP116HResummation σ
      (Finset (Cube d L)) (Finset (Cube d L))
      (Finset (FinBox d N')) ιZ0'
      (PhysicalGaugeField d (M * N') Nc)
      (PhysicalGaugeField d (M * N') Nc) where
  DIndex := DIndex
  PIndex := PIndex
  Z0Index := Z0Index
  Z0PrimeIndex := Z0PrimeIndex
  summand := fun Z D P Z0 Z0p psi phi =>
    (S Z D P Z0 Z0p).data.contour.toLocalFiniteGaussianData
      |>.toFiniteGaussianData.toAnalyticData.term D P psi phi
  termWeight := fun Z D P Z0 Z0p =>
    (S Z D P Z0 Z0p).termWeight

/-- Every variable-arity contour term satisfies its definitionally installed
equation-(2.26) weight. -/
theorem cmp116Eq226VariableArityContourResummation_termwise
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E ιZ0' σ : Type*} [Norm E] [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℝ) (q : ℕ)
    (C2 kappa1 delta kappa gamma gk : ℝ)
    (alpha outerBound outerRate sourceRate : ℝ)
    (DIndex : σ → Finset (Finset (Cube d L)))
    (PIndex :
      σ → Finset (Cube d L) → Finset (Finset (Cube d L)))
    (Z0Index :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset ιZ0')
    (S : CMP116Eq226VariableArityContourTermSourceFamily
      (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
      (lieDim := lieDim) (E := E) (ιZ0' := ιZ0') Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate σ) :
    let R := cmp116Eq226VariableArityContourResummation Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate
      DIndex PIndex Z0Index Z0PrimeIndex S
    ∀ Z x, x ∈ cmp116HIndexFinset R Z →
      ∀ psi phi,
        ‖R.summand Z x.1.1 x.1.2 x.2.1 x.2.2 psi phi‖ ≤
          R.termWeight Z x.1.1 x.1.2 x.2.1 x.2.2 := by
  dsimp
  intro Z x _ psi phi
  exact
    (S Z x.1.1 x.1.2 x.2.1 x.2.2).norm_term_le_termWeight psi phi

/-- The finite local activity assembled from variable-arity contour terms. -/
def cmp116Eq226VariableArityContourActivity
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E ιZ0' σ : Type*} [Norm E] [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℝ) (q : ℕ)
    (C2 kappa1 delta kappa gamma gk : ℝ)
    (alpha outerBound outerRate sourceRate : ℝ)
    (DIndex : σ → Finset (Finset (Cube d L)))
    (PIndex :
      σ → Finset (Cube d L) → Finset (Finset (Cube d L)))
    (Z0Index :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset ιZ0')
    (S : CMP116Eq226VariableArityContourTermSourceFamily
      (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
      (lieDim := lieDim) (E := E) (ιZ0' := ιZ0') Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate σ)
    (Z : σ) :
    PhysicalGaugeLocalActivity d (M * N') Nc :=
  let R := cmp116Eq226VariableArityContourResummation Dict
    E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
    alpha outerBound outerRate sourceRate
    DIndex PIndex Z0Index Z0PrimeIndex S
  LocalActivity.finsetSum (cmp116HIndexFinset R Z) fun x =>
    (S Z x.1.1 x.1.2 x.2.1 x.2.2).data.contour
      |>.toLocalFiniteGaussianData.toLocalAnalyticData.localTerm
        x.1.1 x.1.2

/-- Global evaluation of the variable-arity local activity is exactly its
literal contour resummation. -/
@[simp] theorem globalEval_cmp116Eq226VariableArityContourActivity
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E ιZ0' σ : Type*} [Norm E] [DecidableEq ιZ0']
    (Dict : PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℝ) (q : ℕ)
    (C2 kappa1 delta kappa gamma gk : ℝ)
    (alpha outerBound outerRate sourceRate : ℝ)
    (DIndex : σ → Finset (Finset (Cube d L)))
    (PIndex :
      σ → Finset (Cube d L) → Finset (Finset (Cube d L)))
    (Z0Index :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      σ → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset ιZ0')
    (S : CMP116Eq226VariableArityContourTermSourceFamily
      (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
      (lieDim := lieDim) (E := E) (ιZ0' := ιZ0') Dict
      E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
      alpha outerBound outerRate sourceRate σ)
    (Z : σ) (psi phi : PhysicalGaugeField d (M * N') Nc) :
    (cmp116Eq226VariableArityContourActivity Dict
        E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
        alpha outerBound outerRate sourceRate
        DIndex PIndex Z0Index Z0PrimeIndex S Z).globalEval psi phi =
      balabanCMP116H
        (cmp116Eq226VariableArityContourResummation Dict
          E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
          alpha outerBound outerRate sourceRate
          DIndex PIndex Z0Index Z0PrimeIndex S) Z psi phi := by
  rw [cmp116Eq226VariableArityContourActivity,
    LocalActivity.globalEval_finsetSum]
  rfl

/-- Variable-arity contour resummations at every RG scale. -/
def cmp116Eq226VariableArityContourResummationScaleFamily
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E : Type*} [Norm E]
    {σ ιZ0' : ℕ → ℕ → Type*}
    [∀ _t _k, DecidableEq (ιZ0' _t _k)]
    (Dict : ∀ _t _k,
      PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℕ → ℕ → ℝ)
    (q : ℕ → ℕ → ℕ)
    (C2 kappa1 delta kappa gamma gk : ℕ → ℕ → ℝ)
    (alpha outerBound outerRate sourceRate : ℕ → ℕ → ℝ)
    (DIndex :
      ∀ t k, σ t k → Finset (Finset (Cube d L)))
    (PIndex :
      ∀ t k, σ t k → Finset (Cube d L) →
        Finset (Finset (Cube d L)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226VariableArityContourTermSourceFamily
        (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
        (lieDim := lieDim) (E := E) (ιZ0' := ιZ0' t k)
        (Dict t k) (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k)
        (q t k) (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
        (gamma t k) (gk t k) (alpha t k) (outerBound t k)
        (outerRate t k) (sourceRate t k) (σ t k)) :
    ∀ t k,
      CMP116HResummation (σ t k)
        (Finset (Cube d L)) (Finset (Cube d L))
        (Finset (FinBox d N')) (ιZ0' t k)
        (PhysicalGaugeField d (M * N') Nc)
        (PhysicalGaugeField d (M * N') Nc) :=
  fun t k =>
    cmp116Eq226VariableArityContourResummation (Dict t k)
      (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k) (q t k)
      (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
      (gamma t k) (gk t k) (alpha t k) (outerBound t k)
      (outerRate t k) (sourceRate t k)
      (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k) (S t k)

/-- Variable-arity local contour activities at every RG scale. -/
def cmp116Eq226VariableArityContourActivityScaleFamily
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E : Type*} [Norm E]
    {σ ιZ0' : ℕ → ℕ → Type*}
    [∀ _t _k, DecidableEq (ιZ0' _t _k)]
    (Dict : ∀ _t _k,
      PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℕ → ℕ → ℝ)
    (q : ℕ → ℕ → ℕ)
    (C2 kappa1 delta kappa gamma gk : ℕ → ℕ → ℝ)
    (alpha outerBound outerRate sourceRate : ℕ → ℕ → ℝ)
    (DIndex :
      ∀ t k, σ t k → Finset (Finset (Cube d L)))
    (PIndex :
      ∀ t k, σ t k → Finset (Cube d L) →
        Finset (Finset (Cube d L)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226VariableArityContourTermSourceFamily
        (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
        (lieDim := lieDim) (E := E) (ιZ0' := ιZ0' t k)
        (Dict t k) (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k)
        (q t k) (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
        (gamma t k) (gk t k) (alpha t k) (outerBound t k)
        (outerRate t k) (sourceRate t k) (σ t k)) :
    ∀ t k, σ t k → PhysicalGaugeLocalActivity d (M * N') Nc :=
  fun t k =>
    cmp116Eq226VariableArityContourActivity (Dict t k)
      (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k) (q t k)
      (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
      (gamma t k) (gk t k) (alpha t k) (outerBound t k)
      (outerRate t k) (sourceRate t k)
      (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k) (S t k)

/-- Source-faithful activity identification and termwise equation-(2.26)
estimate with no globally fixed contour arity. -/
theorem cmp116Eq226VariableArityContour_activityTermwiseScaleBoundary
    {d M N' Nc L lieDim : ℕ}
    [NeZero d] [NeZero M] [NeZero N'] [NeZero (M * N')]
    [NeZero Nc] [NeZero L] [NeZero lieDim]
    {E : Type*} [Norm E]
    {σ ιZ0' : ℕ → ℕ → Type*}
    [∀ _t _k, DecidableEq (ιZ0' _t _k)]
    (Dict : ∀ _t _k,
      PhysicalGaugeCMP116Dictionary d (M * N') Nc d L lieDim)
    (E0 epsilon1 C1 alpha4 : ℕ → ℕ → ℝ)
    (q : ℕ → ℕ → ℕ)
    (C2 kappa1 delta kappa gamma gk : ℕ → ℕ → ℝ)
    (alpha outerBound outerRate sourceRate : ℕ → ℕ → ℝ)
    (DIndex :
      ∀ t k, σ t k → Finset (Finset (Cube d L)))
    (PIndex :
      ∀ t k, σ t k → Finset (Cube d L) →
        Finset (Finset (Cube d L)))
    (Z0Index :
      ∀ t k, σ t k → Finset (Cube d L) → Finset (Cube d L) →
        Finset (Finset (FinBox d N')))
    (Z0PrimeIndex :
      ∀ t k, σ t k → Finset (Cube d L) → Finset (Cube d L) →
        Finset (FinBox d N') → Finset (ιZ0' t k))
    (S : ∀ t k,
      CMP116Eq226VariableArityContourTermSourceFamily
        (d := d) (M := M) (N' := N') (Nc := Nc) (L := L)
        (lieDim := lieDim) (E := E) (ιZ0' := ιZ0' t k)
        (Dict t k) (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k)
        (q t k) (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
        (gamma t k) (gk t k) (alpha t k) (outerBound t k)
        (outerRate t k) (sourceRate t k) (σ t k)) :
    CMP116Lemma3ActivityTermwiseScaleBoundary
      (cmp116Eq226VariableArityContourResummationScaleFamily Dict
        E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
        alpha outerBound outerRate sourceRate
        DIndex PIndex Z0Index Z0PrimeIndex S)
      (cmp116Eq226VariableArityContourActivityScaleFamily Dict
        E0 epsilon1 C1 alpha4 q C2 kappa1 delta kappa gamma gk
        alpha outerBound outerRate sourceRate
        DIndex PIndex Z0Index Z0PrimeIndex S) where
  activity_identification := by
    intro t k Z psi phi
    exact globalEval_cmp116Eq226VariableArityContourActivity
      (Dict t k) (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k)
      (q t k) (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
      (gamma t k) (gk t k) (alpha t k) (outerBound t k)
      (outerRate t k) (sourceRate t k)
      (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k)
      (S t k) Z psi phi
  termwise_estimate := by
    intro t k
    exact cmp116Eq226VariableArityContourResummation_termwise
      (Dict t k) (E0 t k) (epsilon1 t k) (C1 t k) (alpha4 t k)
      (q t k) (C2 t k) (kappa1 t k) (delta t k) (kappa t k)
      (gamma t k) (gk t k) (alpha t k) (outerBound t k)
      (outerRate t k) (sourceRate t k)
      (DIndex t k) (PIndex t k) (Z0Index t k) (Z0PrimeIndex t k)
      (S t k)

end

end YangMills.RG
