import YangMills.RG.BalabanCMP99SourceGeneratedCoarseCovarianceTransitionDecay

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceTransitionDist
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceTransitionDist_le_pi5
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceTransitionCoordinates_exponential
