import YangMills.RG.BalabanCMP99SourceFlatWeightedAdjointFourierOrientation

/-!
# Axiom audit: Fourier orientation of the flat physical weighted adjoint
-/

#print axioms YangMills.RG.cmp99SourceFlatQprimeAmplitudeMomentum_fourierNeg_eq_neg_add_period
#print axioms YangMills.RG.cmp89Eq245EntireAverageAmplitude_amplitudeMomentum_fourierNeg_eq_neg
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatWeightedAdjoint_fixedCoarse_eq_aliasRow
