/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102PhysicalLogAverageBackgroundLipschitz
import YangMills.RG.BalabanCMP102AmbientExpAverageBudget

/-!
# Background Lipschitz control of the CMP98 outer exponential

This module transports the source-scale background comparison of the
normalized logarithmic average through the literal outer exponential.
The value estimate uses the exponential Lipschitz budget.  The first
variation estimate uses the exact telescope

`D exp(Y_U) H_U - D exp(Y_0) H_0`

`= (D exp(Y_U) - D exp(Y_0)) H_U
   + D exp(Y_0) (H_U - H_0)`.

All constants are generated by the already audited first- and
second-derivative budgets.  The tangent remains the arbitrary CMP109 pivot
direction; no CMP116 cutoff bound is imposed.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102PhysicalExpAverageBackgroundMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

local instance cmp102PhysicalExpAverageBackgroundCLMNorm :
    Norm (Matrix (Fin Nc) (Fin Nc) ℂ →L[ℝ]
      Matrix (Fin Nc) (Fin Nc) ℂ) :=
  ContinuousLinearMap.hasOpNorm

local instance cmp102PhysicalExpAverageBackgroundCLMSeminormedAddCommGroup :
    SeminormedAddCommGroup
      (Matrix (Fin Nc) (Fin Nc) ℂ →L[ℝ]
        Matrix (Fin Nc) (Fin Nc) ℂ) :=
  ContinuousLinearMap.toSeminormedAddCommGroup

local instance cmp102PhysicalExpAverageBackgroundCLMNormedSpace :
    NormedSpace ℝ
      (Matrix (Fin Nc) (Fin Nc) ℂ →L[ℝ]
        Matrix (Fin Nc) (Fin Nc) ℂ) :=
  ContinuousLinearMap.toNormedSpace

/-- The physical first variation of the literal outer exponential. -/
noncomputable def cmp98UbarExpAveragePhysicalVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') : Matrix (Fin Nc) (Fin Nc) ℂ :=
  (fderiv ℝ
    (NormedSpace.exp : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ)
    (cmp98UbarLogAverage U b 0))
      (cmp98UbarLogAveragePhysicalVariation U A b)

/-- Generated background-Lipschitz budget for the outer exponential value. -/
def cmp102PhysicalExpAverageBackgroundValueBudget
    (d M : ℕ) (r ε : ℝ) : ℝ :=
  cmp102ExpLipschitzBudget (cmp102SourceLogAverageRadius r) *
    cmp102PhysicalLogAverageBackgroundValueBudget d M r ε

/-- Generated background-Lipschitz budget for the outer exponential first
variation, after factoring out the source sup norm of the tangent. -/
def cmp102PhysicalExpAverageBackgroundDerivativeBudget
    (d M : ℕ) (r ε : ℝ) : ℝ :=
  let R := cmp102SourceLogAverageRadius r
  let m : ℝ := ((2 * (d + 1) * M : ℕ) : ℝ)
  expSecondDerivativeBudget R *
        cmp102PhysicalLogAverageBackgroundValueBudget d M r ε *
        (nearLogDerivativeBudget r * m) +
    expDerivativeBudget R *
      cmp102PhysicalLogAverageBackgroundDerivativeBudget d M r ε

theorem cmp102PhysicalExpAverageBackgroundValueBudget_nonneg
    {d M : ℕ} {r ε : ℝ} (hr : 0 ≤ r) (hε : 0 ≤ ε) :
    0 ≤ cmp102PhysicalExpAverageBackgroundValueBudget d M r ε := by
  unfold cmp102PhysicalExpAverageBackgroundValueBudget
  exact mul_nonneg
    (cmp102ExpLipschitzBudget_nonneg _
      (cmp102SourceLogAverageRadius_nonneg hr))
    (cmp102PhysicalLogAverageBackgroundValueBudget_nonneg hr hε)

theorem cmp102PhysicalExpAverageBackgroundDerivativeBudget_nonneg
    {d M : ℕ} {r ε : ℝ} (hr : 0 ≤ r) (hε : 0 ≤ ε) :
    0 ≤ cmp102PhysicalExpAverageBackgroundDerivativeBudget d M r ε := by
  unfold cmp102PhysicalExpAverageBackgroundDerivativeBudget
  let R := cmp102SourceLogAverageRadius r
  have hR : 0 ≤ R := cmp102SourceLogAverageRadius_nonneg hr
  exact add_nonneg
    (mul_nonneg
      (mul_nonneg
        (expSecondDerivativeBudget_nonneg R hR)
        (cmp102PhysicalLogAverageBackgroundValueBudget_nonneg hr hε))
      (mul_nonneg (nearLogDerivativeBudget_nonneg r hr) (by positivity)))
    (mul_nonneg
      (expDerivativeBudget_nonneg R hR)
      (cmp102PhysicalLogAverageBackgroundDerivativeBudget_nonneg hr hε))

/-- The physical first variation of the outer exponential has the literal
source-length bound needed by the CMP98 product rule. -/
theorem norm_cmp98UbarExpAveragePhysicalVariation_le_sourceScale
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (r : ℝ)
    (hbase : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ 1 / 3)
    (hr13 : 1 / 3 ≤ r) (hr1 : r < 1) :
    ‖cmp98UbarExpAveragePhysicalVariation U A b‖ ≤
      expDerivativeBudget (cmp102SourceLogAverageRadius r) *
        nearLogDerivativeBudget r *
        ((2 * (d + 1) * M : ℕ) : ℝ) *
        cmp98SourceFieldSupNorm A := by
  let Y := cmp98UbarLogAverage U b 0
  let H := cmp98UbarLogAveragePhysicalVariation U A b
  let E := fderiv ℝ
    (NormedSpace.exp : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ) Y
  let R := cmp102SourceLogAverageRadius r
  let m : ℝ := ((2 * (d + 1) * M : ℕ) : ℝ)
  let S := cmp98SourceFieldSupNorm A
  have hr0 : 0 ≤ r := (by norm_num : (0 : ℝ) ≤ 1 / 3).trans hr13
  have hY : ‖Y‖ ≤ R := by
    have hbaser : ∀ x ∈ blockOf M N' b.1,
        ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ r :=
      fun x hx => (hbase x hx).trans hr13
    simpa only [Y, R] using
      norm_cmp98UbarLogAverage_le_sourceBudget U b 0 hr0 hr1 hbaser
  have hE : ‖E‖ ≤ expDerivativeBudget R := by
    exact norm_fderiv_exp_le_derivativeBudget hY
  have hH : ‖H‖ ≤ nearLogDerivativeBudget r * (m * S) := by
    simpa only [H, m, S] using
      norm_cmp98UbarLogAveragePhysicalVariation_le_sourceScale
        U A b r hbase hr13 hr1
  change ‖E H‖ ≤ _
  calc
    ‖E H‖ ≤ ‖E‖ * ‖H‖ := E.le_opNorm H
    _ ≤ expDerivativeBudget R *
        (nearLogDerivativeBudget r * (m * S)) := by
      exact mul_le_mul hE hH (norm_nonneg H)
        (expDerivativeBudget_nonneg R
          (cmp102SourceLogAverageRadius_nonneg hr0))
    _ = expDerivativeBudget R *
        nearLogDerivativeBudget r * m * S := by ring

/-- The literal outer exponential is background-Lipschitz, with no
periodic-volume factor. -/
theorem norm_cmp98UbarExpAverage_zero_sub_trivial_le_sourceScale
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (ε r : ℝ) (hε : 0 ≤ ε) (hr13 : 1 / 3 ≤ r) (hr1 : r < 1)
    (hsmall : PhysicalWilsonSmallBackground U ε)
    (b : PhysicalBond d N')
    (hbaseU : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ 1 / 3)
    (hbase0 : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix
        (trivialPhysicalGaugeBackground d (M * N') Nc) b x 0‖ ≤ 1 / 3) :
    ‖cmp98UbarExpAverage U b 0 -
        cmp98UbarExpAverage
          (trivialPhysicalGaugeBackground d (M * N') Nc) b 0‖ ≤
      cmp102PhysicalExpAverageBackgroundValueBudget d M r ε := by
  let U0 := trivialPhysicalGaugeBackground d (M * N') Nc
  let YU := cmp98UbarLogAverage U b 0
  let Y0 := cmp98UbarLogAverage U0 b 0
  let R := cmp102SourceLogAverageRadius r
  have hr0 : 0 ≤ r := (by norm_num : (0 : ℝ) ≤ 1 / 3).trans hr13
  have hbaseUr : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ r :=
    fun x hx => (hbaseU x hx).trans hr13
  have hbase0r : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U0 b x 0‖ ≤ r :=
    fun x hx => (hbase0 x hx).trans hr13
  have hYU : ‖YU‖ ≤ R := by
    simpa only [YU, R] using
      norm_cmp98UbarLogAverage_le_sourceBudget U b 0 hr0 hr1 hbaseUr
  have hY0 : ‖Y0‖ ≤ R := by
    simpa only [Y0, U0, R] using
      norm_cmp98UbarLogAverage_le_sourceBudget U0 b 0 hr0 hr1 hbase0r
  have hYdiff :
      ‖YU - Y0‖ ≤
        cmp102PhysicalLogAverageBackgroundValueBudget d M r ε := by
    simpa only [YU, Y0, U0] using
      norm_cmp98UbarLogAverage_zero_sub_trivial_le_sourceScale
        U ε r hε hr0 hr1 hsmall b hbaseUr hbase0r
  calc
    ‖cmp98UbarExpAverage U b 0 -
        cmp98UbarExpAverage U0 b 0‖ =
      ‖NormedSpace.exp YU - NormedSpace.exp Y0‖ := rfl
    _ ≤ cmp102ExpLipschitzBudget R * ‖YU - Y0‖ :=
      norm_exp_sub_exp_le_cmp102ExpLipschitzBudget
        (cmp102SourceLogAverageRadius_nonneg hr0) hYU hY0
    _ ≤ cmp102ExpLipschitzBudget R *
          cmp102PhysicalLogAverageBackgroundValueBudget d M r ε := by
      exact mul_le_mul_of_nonneg_left hYdiff
        (cmp102ExpLipschitzBudget_nonneg R
          (cmp102SourceLogAverageRadius_nonneg hr0))
    _ = cmp102PhysicalExpAverageBackgroundValueBudget d M r ε := rfl

/-- The physical first variation of the outer exponential is
background-Lipschitz with an explicit source-scale constant. -/
theorem
    norm_cmp98UbarExpAveragePhysicalVariation_sub_trivial_le_sourceScale
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (ε r : ℝ) (hε : 0 ≤ ε) (hr13 : 1 / 3 ≤ r) (hr1 : r < 1)
    (hsmall : PhysicalWilsonSmallBackground U ε)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N')
    (hbaseU : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ 1 / 3)
    (hbase0 : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix
        (trivialPhysicalGaugeBackground d (M * N') Nc) b x 0‖ ≤ 1 / 3) :
    ‖cmp98UbarExpAveragePhysicalVariation U A b -
        cmp98UbarExpAveragePhysicalVariation
          (trivialPhysicalGaugeBackground d (M * N') Nc) A b‖ ≤
      cmp102PhysicalExpAverageBackgroundDerivativeBudget d M r ε *
        cmp98SourceFieldSupNorm A := by
  let U0 := trivialPhysicalGaugeBackground d (M * N') Nc
  let m : ℝ := ((2 * (d + 1) * M : ℕ) : ℝ)
  let S : ℝ := cmp98SourceFieldSupNorm A
  let YU := cmp98UbarLogAverage U b 0
  let Y0 := cmp98UbarLogAverage U0 b 0
  let HU := cmp98UbarLogAveragePhysicalVariation U A b
  let H0 := cmp98UbarLogAveragePhysicalVariation U0 A b
  let EU := fderiv ℝ
    (NormedSpace.exp : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ) YU
  let E0 := fderiv ℝ
    (NormedSpace.exp : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ) Y0
  let R := cmp102SourceLogAverageRadius r
  let C :=
    cmp102PhysicalExpAverageBackgroundDerivativeBudget d M r ε * S
  have hr0 : 0 ≤ r := (by norm_num : (0 : ℝ) ≤ 1 / 3).trans hr13
  have hbaseUr : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ r :=
    fun x hx => (hbaseU x hx).trans hr13
  have hbase0r : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U0 b x 0‖ ≤ r :=
    fun x hx => (hbase0 x hx).trans hr13
  have hYU : ‖YU‖ ≤ R := by
    simpa only [YU, R] using
      norm_cmp98UbarLogAverage_le_sourceBudget U b 0 hr0 hr1 hbaseUr
  have hY0 : ‖Y0‖ ≤ R := by
    simpa only [Y0, U0, R] using
      norm_cmp98UbarLogAverage_le_sourceBudget U0 b 0 hr0 hr1 hbase0r
  have hYdiff :
      ‖YU - Y0‖ ≤
        cmp102PhysicalLogAverageBackgroundValueBudget d M r ε := by
    simpa only [YU, Y0, U0] using
      norm_cmp98UbarLogAverage_zero_sub_trivial_le_sourceScale
        U ε r hε hr0 hr1 hsmall b hbaseUr hbase0r
  have hHU :
      ‖HU‖ ≤ nearLogDerivativeBudget r * (m * S) := by
    simpa only [HU, m, S] using
      norm_cmp98UbarLogAveragePhysicalVariation_le_sourceScale
        U A b r hbaseU hr13 hr1
  have hHdiff :
      ‖HU - H0‖ ≤
        cmp102PhysicalLogAverageBackgroundDerivativeBudget d M r ε * S := by
    simpa only [HU, H0, U0, S] using
      norm_cmp98UbarLogAveragePhysicalVariation_sub_trivial_le_sourceScale
        U ε r hε hr0 hr1 hsmall A b hbaseUr hbase0r
  have hEU0 :
      ‖EU - E0‖ ≤
        expSecondDerivativeBudget R *
          cmp102PhysicalLogAverageBackgroundValueBudget d M r ε := by
    exact
      (norm_fderiv_exp_sub_le_secondDerivativeBudget hYU hY0).trans
        (mul_le_mul_of_nonneg_left hYdiff
          (expSecondDerivativeBudget_nonneg R
            (cmp102SourceLogAverageRadius_nonneg hr0)))
  have hE0 : ‖E0‖ ≤ expDerivativeBudget R := by
    exact norm_fderiv_exp_le_derivativeBudget hY0
  have halg :
      EU HU - E0 H0 = (EU - E0) HU + E0 (HU - H0) := by
    change EU HU - E0 H0 = (EU HU - E0 HU) + E0 (HU - H0)
    rw [E0.map_sub]
    abel
  change ‖EU HU - E0 H0‖ ≤ C
  calc
    ‖EU HU - E0 H0‖ =
        ‖(EU - E0) HU + E0 (HU - H0)‖ := congrArg norm halg
    _ ≤ ‖(EU - E0) HU‖ + ‖E0 (HU - H0)‖ := norm_add_le _ _
    _ ≤
        (expSecondDerivativeBudget R *
            cmp102PhysicalLogAverageBackgroundValueBudget d M r ε) *
            (nearLogDerivativeBudget r * (m * S)) +
          expDerivativeBudget R *
            (cmp102PhysicalLogAverageBackgroundDerivativeBudget d M r ε *
              S) := by
      apply add_le_add
      · exact ((EU - E0).le_opNorm HU).trans
          (mul_le_mul hEU0 hHU (norm_nonneg _)
            ((norm_nonneg _).trans hEU0))
      · exact (E0.le_opNorm (HU - H0)).trans
          (mul_le_mul hE0 hHdiff (norm_nonneg _)
            ((norm_nonneg _).trans hE0))
    _ = C := by
      unfold C cmp102PhysicalExpAverageBackgroundDerivativeBudget R m S
      ring

end

end YangMills.RG
