import YangMills.RG.BalabanCMP89Eq246MassUniformAnalyticDomain

/-! Axiom audit for the mass-uniform analytic domain. -/

#print axioms YangMills.RG.cmp89Eq246FullSolutionDomain_of_commonRadius_massUniform
#print axioms YangMills.RG.cmp89Eq246PhysicalFineToFineGreenIntegrand_boundarySeam_massUniform
#print axioms YangMills.RG.differentiableAt_cmp89Eq246StabilizedFineToFineGreenIntegrand_of_commonRadius_massUniform
#print axioms YangMills.RG.intervalIntegral_cmp89Eq246PhysicalFineToFineGreenIntegrand_coordinateShift_massUniform
