/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80SourcePi4FTCSecondOrderNormalization
import YangMills.RG.BalabanCMP116Eq142RadialDictionary

/-!
# Radial quadratic operator for the connected equation-(80) sector

This file consumes the source-specific `C²` theorem for the literal
connected equation-(80) activity.  It constructs the field-dependent
radial operator and proves the exact quadratic identity.

The object here is the quadratic core generated by the first weakening
sector.  It is deliberately not identified with the full localized
activity and no zero residual is manufactured.  The separate construction
and estimate of `V''_k` remain the next source-facing step.
-/

namespace YangMills.RG

open scoped RealInnerProductSpace

noncomputable section

private abbrev PhysicalField (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

private abbrev PhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalField M Q Nc →L[ℝ] PhysicalField M Q Nc

/-- The source-specific radial quadratic operator generated by the
connected equation-(80) activity.  Its `C²` certificate is constructed
internally from the literal FTC tree. -/
noncomputable def cmp102Eq80SourcePi4ConnectedDomainRadialQuadratic
    {M Q Nc R Δ : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    {Ahead rho rate Rweak : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
      PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hrange : R + 1 ≤ 4 * M)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (vertexBase : FinBox 4 (2 * Q) → ℝ)
    (vertexCoordinates : List (FinBox 4 (2 * Q)))
    (s : FinBox 4 (2 * Q) → ℝ)
    (L : List (FinBox 4 (2 * Q)))
    (W : Finset (FinBox 4 (2 * Q)))
    (hRweak : 1 ≤ Rweak)
    (hs : CMP116RealPhysicalContourRegion Rweak s)
    (hsmall :
      ‖cmp116SourcePi4ComplexContourRatio Δ rho Rweak‖ < 1)
    (hD : ContDiff ℝ ⊤ D) (hD₃ : ContDiff ℝ ⊤ D₃)
    (hV₀ : ContDiff ℝ ⊤ V₀)
    (B : PhysicalField M Q Nc) :
    PhysicalEndomorphism M Q Nc :=
  cmp116Eq142PhysicalRadialQuadratic
    (fun A =>
      cmp102Eq80SourcePi4ConnectedDomainActivity
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J A
        vertexBase vertexCoordinates s L W)
    (contDiff_two_cmp102Eq80SourcePi4ConnectedDomainActivity
      (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
      hAhead hrho hrate Cert htri hrange hΔ hΔ1
      vertexBase vertexCoordinates s L W
      hRweak hs hsmall hD hD₃ hV₀)
    B

/-- Exact equation-(1.42) quadratic identity for the connected
equation-(80) core. -/
theorem
    inner_cmp102Eq80SourcePi4ConnectedDomainRadialQuadratic_eq_activity
    {M Q Nc R Δ : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    {Ahead rho rate Rweak : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
      PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hrange : R + 1 ≤ 4 * M)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (vertexBase : FinBox 4 (2 * Q) → ℝ)
    (vertexCoordinates : List (FinBox 4 (2 * Q)))
    (s : FinBox 4 (2 * Q) → ℝ)
    (L : List (FinBox 4 (2 * Q)))
    (W : Finset (FinBox 4 (2 * Q)))
    (hRweak : 1 ≤ Rweak)
    (hs : CMP116RealPhysicalContourRegion Rweak s)
    (hsmall :
      ‖cmp116SourcePi4ComplexContourRatio Δ rho Rweak‖ < 1)
    (hD : ContDiff ℝ ⊤ D) (hD₃ : ContDiff ℝ ⊤ D₃)
    (hV₀ : ContDiff ℝ ⊤ V₀)
    (hD0 : D 0 = 0) (hD₃0 : D₃ 0 = 0)
    (hV₀0 : V₀ 0 = 0)
    (hD₃' : HasFDerivAt D₃
      (0 : PhysicalEndomorphism M Q Nc) 0)
    (hV₀' : HasFDerivAt V₀
      (0 : PhysicalField M Q Nc →L[ℝ] ℝ) 0)
    (B : PhysicalField M Q Nc) :
    (1 / 2 : ℝ) * inner ℝ B
        (cmp102Eq80SourcePi4ConnectedDomainRadialQuadratic
          (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
          hAhead hrho hrate Cert htri hrange hΔ hΔ1
          vertexBase vertexCoordinates s L W
          hRweak hs hsmall hD hD₃ hV₀ B B) =
      cmp102Eq80SourcePi4ConnectedDomainActivity
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J B
        vertexBase vertexCoordinates s L W := by
  let f :=
    fun A : PhysicalField M Q Nc =>
      cmp102Eq80SourcePi4ConnectedDomainActivity
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J A
        vertexBase vertexCoordinates s L W
  have hsmooth : ContDiff ℝ 2 f :=
    contDiff_two_cmp102Eq80SourcePi4ConnectedDomainActivity
      (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
      hAhead hrho hrate Cert htri hrange hΔ hΔ1
      vertexBase vertexCoordinates s L W
      hRweak hs hsmall hD hD₃ hV₀
  have hzero : f 0 = 0 := by
    simpa [f] using
      cmp102Eq80SourcePi4ConnectedDomainActivity_zero_field
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
        vertexBase vertexCoordinates s L W
        hD0 hD₃0 hV₀0
  have hlinear : fderiv ℝ f 0 = 0 := by
    have hfirst :=
      cmp102Eq80SourcePi4ConnectedDomainActivity_hasFDerivAt_zero_field
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
        hAhead hrho hrate Cert htri hrange hΔ hΔ1
        vertexBase vertexCoordinates s L W
        hRweak hs hsmall hD hD₃ hV₀
        hD0 hD₃0 hD₃' hV₀'
    simpa [f] using hfirst.fderiv
  simpa [cmp102Eq80SourcePi4ConnectedDomainRadialQuadratic, f] using
    inner_cmp116Eq142PhysicalRadialQuadratic_eq_activity
      f hsmooth hzero hlinear B

end

end YangMills.RG
