import YangMills.RG.BalabanCMP99SourceEq395GroupedCorrectionDecay

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrection_grouped_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalCorrection_le_groupedSchurAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalMiddle_comp_correctedCovariance_eq_id_of_groupedSchurSmall
