/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.SUNProductDeviation
import YangMills.RG.Ubar
import YangMills.RG.NearLogDeviationBudget

/-!
# Physical path-length bound for the CMP99 Ubar deviation

This module derives the small-field input for `UbarDeviationLogArg` from
literal linkwise smallness.  The exact coefficient is the total length of the
three fine Wilson paths plus the single coarse link.  No product estimate or
deviation budget is supplied by the caller.
-/

namespace YangMills.RG

open YangMills YangMills.GaugeConfig Matrix
open scoped Matrix.Norms.L2Operator BigOperators

noncomputable section

variable {d N' L Nc : ℕ} [NeZero N'] [NeZero L] [NeZero Nc]
  [FiniteLatticeGeometry d N' (SUN Nc)]
  [FiniteLatticeGeometry d (L * N') (SUN Nc)]

/-- The exact conservative no-winding threshold coming from the rational
Mercator majorant. -/
noncomputable def cmp99UbarNoWindingThreshold (Nc : ℕ) : ℝ :=
  2 * Real.pi / ((Nc : ℝ) + 2 * Real.pi)

/-- A nonnegative deviation radius strictly below the explicit threshold
canonically produces the complete no-winding budget. -/
noncomputable def cmp99PhysicalNoWindingBudget
    (δ : ℝ) (hδ : δ < cmp99UbarNoWindingThreshold Nc) :
    MatrixNearLogNoWindingBudget Nc := by
  have hNc : 0 < (Nc : ℝ) := by
    exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne Nc)
  have hden : 0 < (Nc : ℝ) + 2 * Real.pi := by positivity
  have hthreshold_lt_one : cmp99UbarNoWindingThreshold Nc < 1 := by
    rw [cmp99UbarNoWindingThreshold, div_lt_one hden]
    linarith [Real.pi_pos]
  have hδ1 : δ < 1 := lt_trans hδ hthreshold_lt_one
  refine ⟨δ, hδ1, ?_⟩
  rw [show (Nc : ℝ) * (δ / (1 - δ)) =
      ((Nc : ℝ) * δ) / (1 - δ) by ring]
  rw [div_lt_iff₀ (sub_pos.mpr hδ1)]
  have hscaled : ((Nc : ℝ) + 2 * Real.pi) * δ < 2 * Real.pi := by
    simpa only [mul_comm] using (lt_div_iff₀ hden).mp (by
      simpa [cmp99UbarNoWindingThreshold, mul_comm] using hδ)
  nlinarith [Real.pi_pos]

/-- The physical radius generated by three one-scale paths and one coarse
link. -/
def cmp99UbarPhysicalDeviationRadius (d L : ℕ) (ε : ℝ) : ℝ :=
  ((3 * d * (L - 1) + 1 : ℕ) : ℝ) * ε

/-- The canonical CMP99 physical no-winding budget.  Its only analytic input
is the explicit scalar threshold for the linkwise small-field radius. -/
noncomputable def cmp99UbarPhysicalNoWindingBudget
    (d L Nc : ℕ) [NeZero Nc] (ε : ℝ)
    (hsmall : cmp99UbarPhysicalDeviationRadius d L ε <
      cmp99UbarNoWindingThreshold Nc) :
    MatrixNearLogNoWindingBudget Nc :=
  cmp99PhysicalNoWindingBudget
    (cmp99UbarPhysicalDeviationRadius d L ε)
    hsmall

@[simp] theorem cmp99UbarPhysicalNoWindingBudget_delta
    (d L Nc : ℕ) [NeZero Nc] (ε : ℝ)
    (hsmall : cmp99UbarPhysicalDeviationRadius d L ε <
      cmp99UbarNoWindingThreshold Nc) :
    (cmp99UbarPhysicalNoWindingBudget d L Nc ε hsmall).δ =
      cmp99UbarPhysicalDeviationRadius d L ε :=
  by simp [cmp99UbarPhysicalNoWindingBudget,
    cmp99PhysicalNoWindingBudget]

/-- The represented CMP99 deviation is bounded by the deviations of its four
literal factors. -/
theorem norm_UbarDeviationLogArg_le_four_factors
    (A_fine : GaugeConfig d (L * N') (SUN Nc))
    (A_coarse : GaugeConfig d N' (SUN Nc))
    (C : FiniteLatticeGeometry.E (d := d) (N := N') (G := SUN Nc))
    (x : FinBox d (L * N'))
    (Γ_1 Γ_2 Γ_3 : FinBox d (L * N') →
      List (FiniteLatticeGeometry.E (d := d) (N := L * N') (G := SUN Nc))) :
    ‖UbarDeviationLogArg
        (𝔸 := Matrix (Fin Nc) (Fin Nc) ℂ)
        A_fine A_coarse C x Γ_1 Γ_2 Γ_3‖ ≤
      ‖((wilsonLine A_fine (Γ_1 x) : SUN Nc) :
          Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
      ‖((wilsonLine A_fine (Γ_2 x) : SUN Nc) :
          Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
      ‖((wilsonLine A_fine (Γ_3 x) : SUN Nc) :
          Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
      ‖(A_coarse C : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ := by
  change ‖((wilsonLine A_fine (Γ_1 x) *
      wilsonLine A_fine (Γ_2 x) *
      wilsonLine A_fine (Γ_3 x) *
      (A_coarse C)⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ _
  calc
    _ ≤ ‖((wilsonLine A_fine (Γ_1 x) *
          wilsonLine A_fine (Γ_2 x) : SUN Nc) :
            Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
        ‖((wilsonLine A_fine (Γ_3 x) * (A_coarse C)⁻¹ : SUN Nc) :
            Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ := by
      simpa only [mul_assoc] using norm_sun_mul_sub_one_le
        (wilsonLine A_fine (Γ_1 x) * wilsonLine A_fine (Γ_2 x))
        (wilsonLine A_fine (Γ_3 x) * (A_coarse C)⁻¹)
    _ ≤ (‖((wilsonLine A_fine (Γ_1 x) : SUN Nc) :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
          ‖((wilsonLine A_fine (Γ_2 x) : SUN Nc) :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖) +
        (‖((wilsonLine A_fine (Γ_3 x) : SUN Nc) :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
          ‖(((A_coarse C)⁻¹ : SUN Nc) :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖) :=
      add_le_add
        (norm_sun_mul_sub_one_le
          (wilsonLine A_fine (Γ_1 x)) (wilsonLine A_fine (Γ_2 x)))
        (norm_sun_mul_sub_one_le
          (wilsonLine A_fine (Γ_3 x)) (A_coarse C)⁻¹)
    _ = _ := by
      rw [norm_sun_inv_sub_one]
      ring

/-- Uniform linkwise smallness gives the exact physical coefficient
`|Γ₁| + |Γ₂| + |Γ₃| + 1`. -/
theorem norm_UbarDeviationLogArg_le_pathLength
    (A_fine : GaugeConfig d (L * N') (SUN Nc))
    (A_coarse : GaugeConfig d N' (SUN Nc))
    (C : FiniteLatticeGeometry.E (d := d) (N := N') (G := SUN Nc))
    (x : FinBox d (L * N'))
    (Γ_1 Γ_2 Γ_3 : FinBox d (L * N') →
      List (FiniteLatticeGeometry.E (d := d) (N := L * N') (G := SUN Nc)))
    (ε : ℝ)
    (hfine : ∀ e, (e ∈ Γ_1 x ∨ e ∈ Γ_2 x ∨ e ∈ Γ_3 x) →
      ‖(A_fine e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ ε)
    (hcoarse : ‖(A_coarse C : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ ε) :
    ‖UbarDeviationLogArg
        (𝔸 := Matrix (Fin Nc) (Fin Nc) ℂ)
        A_fine A_coarse C x Γ_1 Γ_2 Γ_3‖ ≤
      (((Γ_1 x).length + (Γ_2 x).length + (Γ_3 x).length + 1 : ℕ) : ℝ) * ε := by
  have h1 := norm_wilsonLine_sub_one_le_length_mul
    A_fine (Γ_1 x) ε (fun e he => hfine e (Or.inl he))
  have h2 := norm_wilsonLine_sub_one_le_length_mul
    A_fine (Γ_2 x) ε (fun e he => hfine e (Or.inr (Or.inl he)))
  have h3 := norm_wilsonLine_sub_one_le_length_mul
    A_fine (Γ_3 x) ε (fun e he => hfine e (Or.inr (Or.inr he)))
  calc
    _ ≤ ‖((wilsonLine A_fine (Γ_1 x) : SUN Nc) :
            Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
        ‖((wilsonLine A_fine (Γ_2 x) : SUN Nc) :
            Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
        ‖((wilsonLine A_fine (Γ_3 x) : SUN Nc) :
            Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ +
        ‖(A_coarse C : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ :=
      norm_UbarDeviationLogArg_le_four_factors A_fine A_coarse C x Γ_1 Γ_2 Γ_3
    _ ≤ ((Γ_1 x).length : ℝ) * ε +
        ((Γ_2 x).length : ℝ) * ε +
        ((Γ_3 x).length : ℝ) * ε + ε := by
      gcongr
    _ = _ := by
      push_cast
      ring

/-- Three one-scale contour bounds give the source-facing no-winding
coefficient `3 d (L - 1) + 1`. -/
theorem norm_UbarDeviationLogArg_le_three_blockContours
    (A_fine : GaugeConfig d (L * N') (SUN Nc))
    (A_coarse : GaugeConfig d N' (SUN Nc))
    (C : FiniteLatticeGeometry.E (d := d) (N := N') (G := SUN Nc))
    (x : FinBox d (L * N'))
    (Γ_1 Γ_2 Γ_3 : FinBox d (L * N') →
      List (FiniteLatticeGeometry.E (d := d) (N := L * N') (G := SUN Nc)))
    (ε : ℝ) (hε : 0 ≤ ε)
    (hfine : ∀ e, (e ∈ Γ_1 x ∨ e ∈ Γ_2 x ∨ e ∈ Γ_3 x) →
      ‖(A_fine e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ ε)
    (hcoarse : ‖(A_coarse C : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ ε)
    (hΓ1 : (Γ_1 x).length ≤ d * (L - 1))
    (hΓ2 : (Γ_2 x).length ≤ d * (L - 1))
    (hΓ3 : (Γ_3 x).length ≤ d * (L - 1)) :
    ‖UbarDeviationLogArg
        (𝔸 := Matrix (Fin Nc) (Fin Nc) ℂ)
        A_fine A_coarse C x Γ_1 Γ_2 Γ_3‖ ≤
      ((3 * d * (L - 1) + 1 : ℕ) : ℝ) * ε := by
  calc
    _ ≤ (((Γ_1 x).length + (Γ_2 x).length +
          (Γ_3 x).length + 1 : ℕ) : ℝ) * ε :=
      norm_UbarDeviationLogArg_le_pathLength
        A_fine A_coarse C x Γ_1 Γ_2 Γ_3 ε hfine hcoarse
    _ ≤ ((3 * d * (L - 1) + 1 : ℕ) : ℝ) * ε := by
      apply mul_le_mul_of_nonneg_right _ hε
      have hlen0 :
          (Γ_1 x).length + (Γ_2 x).length + (Γ_3 x).length + 1 ≤
            3 * (d * (L - 1)) + 1 := by
        omega
      have hlen :
          (Γ_1 x).length + (Γ_2 x).length + (Γ_3 x).length + 1 ≤
            3 * d * (L - 1) + 1 := by
        simpa only [mul_assoc] using hlen0
      exact_mod_cast hlen

/-- Source-facing closure: literal link smallness and the three contour
certificates place the physical Ubar logarithm argument inside the canonical
no-winding budget. -/
theorem norm_UbarDeviationLogArg_le_physicalNoWindingBudget
    (A_fine : GaugeConfig d (L * N') (SUN Nc))
    (A_coarse : GaugeConfig d N' (SUN Nc))
    (C : FiniteLatticeGeometry.E (d := d) (N := N') (G := SUN Nc))
    (x : FinBox d (L * N'))
    (Γ_1 Γ_2 Γ_3 : FinBox d (L * N') →
      List (FiniteLatticeGeometry.E (d := d) (N := L * N') (G := SUN Nc)))
    (ε : ℝ) (hε : 0 ≤ ε)
    (hsmall : cmp99UbarPhysicalDeviationRadius d L ε <
      cmp99UbarNoWindingThreshold Nc)
    (hfine : ∀ e, (e ∈ Γ_1 x ∨ e ∈ Γ_2 x ∨ e ∈ Γ_3 x) →
      ‖(A_fine e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ ε)
    (hcoarse : ‖(A_coarse C : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ ε)
    (hΓ1 : (Γ_1 x).length ≤ d * (L - 1))
    (hΓ2 : (Γ_2 x).length ≤ d * (L - 1))
    (hΓ3 : (Γ_3 x).length ≤ d * (L - 1)) :
    ‖UbarDeviationLogArg
        (𝔸 := Matrix (Fin Nc) (Fin Nc) ℂ)
        A_fine A_coarse C x Γ_1 Γ_2 Γ_3‖ ≤
      (cmp99UbarPhysicalNoWindingBudget
        d L Nc ε hsmall).δ := by
  simpa only [cmp99UbarPhysicalNoWindingBudget_delta,
    cmp99UbarPhysicalDeviationRadius] using
    norm_UbarDeviationLogArg_le_three_blockContours
      A_fine A_coarse C x Γ_1 Γ_2 Γ_3 ε hε hfine hcoarse hΓ1 hΓ2 hΓ3

end

end YangMills.RG
