import YangMills.RG.BalabanCMP99SourceGeneratedCoarseCovarianceTransitionTower

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.GeneratedCoarseCovarianceSiteFamily
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceCrossDist
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceCrossDist_self
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceCrossDist_triangle
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceCrossDist_transition
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceTransitionTowerStep
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceTransitionTower
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceTransitionTower_length
#print axioms CMP99SourceDependentOmegaGeometry.generatedCoarseCovarianceTransitionTower_weightedRowKernelBound
