import YangMills.RG.BalabanCMP99SourceRetainedPhysicalTower

namespace YangMills.RG

#print axioms nonempty_cmp99SourceRetainedPhysicalTower
#print axioms cmp99SourceGeneratedRetainedPhysicalTower
#print axioms cmp99SourceRetainedPhysicalTower
#print axioms CMP99SourceRetainedPhysicalTower.towerAt_depth
#print axioms CMP99SourceRetainedPhysicalTower.towerAt_terminalSpacing
#print axioms CMP99SourceRetainedPhysicalTower.levelCarrierEq
#print axioms CMP99SourceRetainedPhysicalTower.levelEquiv
#print axioms CMP99SourceRetainedPhysicalTower.prefix_comp_weightedAdjoint
#print axioms CMP99SourceRetainedPhysicalTower.Qprime_succ
#print axioms CMP99SourceRetainedPhysicalTower.norm_nextAverage_sq_le
#print axioms CMP99SourceRetainedPhysicalTower.norm_Qprime_succ_sq_le
#print axioms CMP99SourceRetainedPhysicalTower.norm_Qprime_sq_le_pow

end YangMills.RG
