import YangMills.RG.BalabanCMP102Eq80PhysicalFineHeadTailFixedRightBound

#print axioms YangMills.RG.cmp102Eq80PhysicalFineWalkMajorant
#print axioms YangMills.RG.norm_cmp99SourcePi4ComplexFineWalkTerm_le_physicalMajorant
#print axioms YangMills.RG.cmp102Eq80PhysicalCoarseFineWalkDefectMajorant
#print axioms YangMills.RG.norm_cmp99SourcePi4ComplexCoarseFineWalkDefectTerm_le_physicalMajorant
#print axioms YangMills.RG.norm_cmp99DependentOrderedProduct_le_prod_norm
#print axioms YangMills.RG.norm_cmp99SourcePi4ComplexCoarseFineWalkWordTerm_le_physicalMajorants
#print axioms YangMills.RG.norm_cmp99SourcePi4ComplexFineHeadTailFixedRight_le_physicalMajorants
