import YangMills.RG.BalabanCMP116SourcePi4RealMixedWeakenedCovariance

#print axioms YangMills.RG.cmp116SourcePi4FullRealWeakenedCovarianceMixedDerivative
#print axioms YangMills.RG.cmp116SourcePi4RealMixedCovarianceEntryCurve
#print axioms YangMills.RG.cmp116SourcePi4RealMixedCovarianceEntryDerivative
#print axioms YangMills.RG.cmp116SourcePi4FullRealWeakenedCovarianceMixedDerivative_empty_one_eq_exact
#print axioms YangMills.RG.hasDerivAt_re_cmp116SourcePi4FullComplexWeakenedCovarianceMatrixMixedDerivative_update
