/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116FiniteStateResolventFactorization

/-!
# Restricted visited-state transfer matrix

This module turns the exact visited-carrier update into a finite transfer
matrix.  A node with label `none` is a possible distinguished head; a node
with label `some alpha` is a continuation factor.  The transition matrix
charges only the contour coordinates newly activated by its target domain.

The key support theorem is entrywise: if a transition adds no new contour
coordinate, its value is identical at an arbitrary restricted coupling and
at full coupling.  Thus the transfer defect is supported on genuinely active
state transitions, the input needed by the finite-state resolvent
factorization.

This file does not yet identify matrix powers with the source walk layers.
-/

namespace YangMills.RG

noncomputable section

universe u v w

/-- One node of the augmented transfer graph.  Only `some` nodes may be
targets of a continuation transition. -/
structure CMP116VisitedTransferNode (Label : Type u) (Domain : Type v) where
  kind : Option Label
  domain : Domain
  deriving DecidableEq, Fintype

/-- Transfer state: current labelled domain together with the finite set of
contour coordinates visited so far. -/
abbrev CMP116RestrictedTransferState
    (Label : Type u) (Domain : Type v)
    {Delta : Type w} [DecidableEq Delta] (carrier : Finset Delta) :=
  CMP116VisitedTransferNode Label Domain ×
    CMP116RestrictedVisitedState carrier

/-- The operator factor stored at one transfer node. -/
def cmp116VisitedTransferNodeFactor
    {Label : Type u} {Domain : Type v} {Index : Type*}
    (R0 : Domain → Matrix Index Index ℂ)
    (R : Label → Domain → Matrix Index Index ℂ)
    (node : CMP116VisitedTransferNode Label Domain) :
    Matrix Index Index ℂ :=
  match node.kind with
  | none => R0 node.domain
  | some label => R label node.domain

/-- Finite augmented transfer matrix.  Its target factor is multiplied after
the factors already accumulated along the path. -/
def cmp116RestrictedVisitedTransferMatrix
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ) :
    Matrix
      (CMP116RestrictedTransferState Label Domain carrier)
      (CMP116RestrictedTransferState Label Domain carrier)
      (Matrix Index Index ℂ) :=
  fun source target =>
    match target.1.kind with
    | none => 0
    | some label =>
        if _hstep :
            (⟨label, target.1.domain⟩ : CMP99WalkStep Label Domain) ∈
              successors source.1.domain then
          if _hstate :
              target.2 =
                CMP116RestrictedVisitedState.update carrier source.2
                  (domainActive target.1.domain) then
            CMP116RestrictedVisitedState.transitionWeight
                carrier sigma source.2 (domainActive target.1.domain) •
              R label target.1.domain
          else 0
        else 0

/-- Unique augmented target state generated by one physical successor step. -/
def cmp116RestrictedTransferNextState
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Delta]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (visited : CMP116RestrictedVisitedState carrier)
    (step : CMP99WalkStep Label Domain) :
    CMP116RestrictedTransferState Label Domain carrier :=
  (⟨some step.label, step.domain⟩,
    CMP116RestrictedVisitedState.update
      carrier visited (domainActive step.domain))

/-- Different labelled physical steps generate different augmented target
states. -/
theorem cmp116RestrictedTransferNextState_injective
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Delta]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (visited : CMP116RestrictedVisitedState carrier) :
    Function.Injective
      (cmp116RestrictedTransferNextState
        (Label := Label) (Domain := Domain)
        carrier domainActive visited) := by
  intro left right h
  have hnode := congrArg (fun state => state.1) h
  have hkind := congrArg CMP116VisitedTransferNode.kind hnode
  have hdomain := congrArg CMP116VisitedTransferNode.domain hnode
  cases left
  cases right
  simp only [cmp116RestrictedTransferNextState,
    Option.some.injEq] at hkind hdomain
  simp_all

/-- The transfer entry at the unique state generated by a declared successor
is exactly its newly-activated scalar weight times its physical operator
factor. -/
theorem cmp116RestrictedVisitedTransferMatrix_apply_nextState
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (source : CMP116RestrictedTransferState Label Domain carrier)
    (step : CMP99WalkStep Label Domain)
    (hstep : step ∈ successors source.1.domain) :
    cmp116RestrictedVisitedTransferMatrix
        carrier domainActive successors R sigma source
        (cmp116RestrictedTransferNextState
          carrier domainActive source.2 step) =
      CMP116RestrictedVisitedState.transitionWeight
          carrier sigma source.2 (domainActive step.domain) •
        R step.label step.domain := by
  simp [cmp116RestrictedVisitedTransferMatrix,
    cmp116RestrictedTransferNextState, hstep]

/-- Every transfer entry outside the finite image of the physical successor
family is zero. -/
theorem cmp116RestrictedVisitedTransferMatrix_apply_eq_zero_of_not_mem_nextStates
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (source target :
      CMP116RestrictedTransferState Label Domain carrier)
    (hnot :
      target ∉
        (successors source.1.domain).image
          (cmp116RestrictedTransferNextState
            carrier domainActive source.2)) :
    cmp116RestrictedVisitedTransferMatrix
        carrier domainActive successors R sigma source target = 0 := by
  rcases target with ⟨⟨kind, targetDomain⟩, targetVisited⟩
  cases kind with
  | none =>
      simp [cmp116RestrictedVisitedTransferMatrix]
  | some label =>
      let step : CMP99WalkStep Label Domain := ⟨label, targetDomain⟩
      by_cases hstep : step ∈ successors source.1.domain
      · by_cases hstate :
          targetVisited =
            CMP116RestrictedVisitedState.update carrier source.2
              (domainActive targetDomain)
        · exfalso
          apply hnot
          apply Finset.mem_image.mpr
          refine ⟨step, hstep, ?_⟩
          simp [cmp116RestrictedTransferNextState, step, hstate]
        · simp [cmp116RestrictedVisitedTransferMatrix, step,
            hstep, hstate]
      · simp [cmp116RestrictedVisitedTransferMatrix, step, hstep]

/-- At full coupling every allowed transition has scalar weight one. -/
theorem cmp116RestrictedVisitedTransferMatrix_one
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (source target :
      CMP116RestrictedTransferState Label Domain carrier) :
    cmp116RestrictedVisitedTransferMatrix
        carrier domainActive successors R (fun _ => 1) source target =
      match target.1.kind with
      | none => 0
      | some label =>
          if (⟨label, target.1.domain⟩ :
                CMP99WalkStep Label Domain) ∈
              successors source.1.domain ∧
              target.2 =
                CMP116RestrictedVisitedState.update carrier source.2
                  (domainActive target.1.domain) then
            R label target.1.domain
          else 0 := by
  classical
  unfold cmp116RestrictedVisitedTransferMatrix
  split
  · rfl
  · rename_i label
    split <;> split <;>
      simp_all [CMP116RestrictedVisitedState.transitionWeight,
        cmp116ComplexWeakeningMonomial]

/-- If the target domain adds no new contour coordinate, the corresponding
transition entry has zero contour defect. -/
theorem cmp116RestrictedVisitedTransferMatrix_sub_one_eq_zero_of_newlyActive_eq_empty
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (source target :
      CMP116RestrictedTransferState Label Domain carrier)
    (hnew :
      CMP116RestrictedVisitedState.newlyActive carrier source.2
        (domainActive target.1.domain) = ∅) :
    (cmp116RestrictedVisitedTransferMatrix
        carrier domainActive successors R sigma -
      cmp116RestrictedVisitedTransferMatrix
        carrier domainActive successors R (fun _ => 1))
        source target = 0 := by
  classical
  rw [Matrix.sub_apply]
  cases hkind : target.1.kind with
  | none =>
      simp [cmp116RestrictedVisitedTransferMatrix, hkind]
  | some label =>
      simp [cmp116RestrictedVisitedTransferMatrix, hkind,
        CMP116RestrictedVisitedState.transitionWeight,
        hnew, cmp116ComplexWeakeningMonomial]

/-- Ordered continuation product with the restricted visited state updated at
every physical step. -/
def cmp116RestrictedVisitedTailProduct
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ) :
    CMP116RestrictedVisitedState carrier →
      List (CMP99WalkStep Label Domain) → Matrix Index Index ℂ
  | _, [] => 1
  | visited, step :: rest =>
      CMP116RestrictedVisitedState.transitionWeight
          carrier sigma visited (domainActive step.domain) •
        (R step.label step.domain *
          cmp116RestrictedVisitedTailProduct
            carrier domainActive R sigma
            (CMP116RestrictedVisitedState.update
              carrier visited (domainActive step.domain))
            rest)

/-- The recursive continuation product is exactly the original ordered
operator product multiplied by the visited-state weakening weight. -/
theorem cmp116ComplexVisitedWeakeningProduct_smul_tailProd_eq
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (visited : CMP116RestrictedVisitedState carrier) :
    ∀ tail : List (CMP99WalkStep Label Domain),
      cmp116ComplexVisitedWeakeningProduct sigma visited.1
          (tail.map fun step =>
            domainActive step.domain ∩ carrier) •
        (tail.map fun step => R step.label step.domain).prod =
      cmp116RestrictedVisitedTailProduct
        carrier domainActive R sigma visited tail := by
  intro tail
  induction tail generalizing visited with
  | nil =>
      simp [cmp116ComplexVisitedWeakeningProduct,
        cmp116RestrictedVisitedTailProduct]
  | cons step rest ih =>
      simp only [List.map_cons, List.prod_cons,
        cmp116ComplexVisitedWeakeningProduct,
        cmp116RestrictedVisitedTailProduct]
      rw [← ih
        (CMP116RestrictedVisitedState.update
          carrier visited (domainActive step.domain))]
      simp only [CMP116RestrictedVisitedState.transitionWeight,
        CMP116RestrictedVisitedState.newlyActive,
        CMP116RestrictedVisitedState.coe_update]
      rw [mul_smul, mul_smul_comm]

/-- One source generalized walk, with its literal restricted weakening
monomial, is exactly its head factor followed by the visited-state
continuation product. -/
theorem CMP99GeneralizedWalk.restrictedShiftedMonomial_smul_term_eq_visitedProduct
    {n : ℕ} {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta) (e : Fin n ≃ ↥carrier)
    (z : Fin n → ℂ)
    (domainActive : Domain → Finset Delta)
    (R0 : Domain → Matrix Index Index ℂ)
    (R : Label → Domain → Matrix Index Index ℂ)
    (walk : CMP99GeneralizedWalk Label Domain) :
    cmp116ComplexWeakeningMonomial (walk.active domainActive)
          (cmp116SourceRestrictedShiftedCoupling carrier e z) •
        walk.term R0 R =
      CMP116RestrictedVisitedState.transitionWeight
          carrier
          (cmp116SourceRestrictedShiftedCoupling carrier e z)
          (CMP116RestrictedVisitedState.empty carrier)
          (domainActive walk.head) •
        (R0 walk.head *
          cmp116RestrictedVisitedTailProduct
            carrier domainActive R
            (cmp116SourceRestrictedShiftedCoupling carrier e z)
            (CMP116RestrictedVisitedState.update carrier
              (CMP116RestrictedVisitedState.empty carrier)
              (domainActive walk.head))
            walk.tail) := by
  rw [walk.restrictedShiftedWeakeningMonomial_eq_visitedProduct
    domainActive carrier e z]
  simp only [CMP99GeneralizedWalk.domains, CMP99GeneralizedWalk.term,
    List.map_cons]
  rw [List.map_map]
  have hmap :
      walk.tail.map
          ((fun X : Domain => domainActive X ∩ carrier) ∘
            CMP99WalkStep.domain) =
        walk.tail.map
          (fun step => domainActive step.domain ∩ carrier) := by
    exact List.map_congr_left (fun step _ => rfl)
  rw [hmap]
  change
    cmp116ComplexVisitedWeakeningProduct
        (cmp116SourceRestrictedShiftedCoupling carrier e z) ∅
        ((domainActive walk.head ∩ carrier) ::
          walk.tail.map
            (fun step => domainActive step.domain ∩ carrier)) •
      (R0 walk.head ::
        walk.tail.map (fun step => R step.label step.domain)).prod =
    _
  simp only [cmp116ComplexVisitedWeakeningProduct, List.prod_cons]
  rw [← cmp116ComplexVisitedWeakeningProduct_smul_tailProd_eq
    carrier domainActive R
    (cmp116SourceRestrictedShiftedCoupling carrier e z)
    (CMP116RestrictedVisitedState.update carrier
      (CMP116RestrictedVisitedState.empty carrier)
      (domainActive walk.head)) walk.tail]
  simp only [CMP116RestrictedVisitedState.transitionWeight,
    CMP116RestrictedVisitedState.newlyActive,
    CMP116RestrictedVisitedState.coe_empty,
    CMP116RestrictedVisitedState.coe_update]
  rw [mul_smul, mul_smul_comm]

end

end YangMills.RG
