import YangMills.RG.BalabanCMP99Eq360C6dSourceAmbientBaselinePrecision


#print axioms YangMills.RG.cmp99Eq360C6dSourceAmbientBaselinePrecision
#print axioms YangMills.RG.cmp99RegionalDirichletPrecision_C6dSourceAmbientBaseline_eq
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPhysicalCoercivity_eq_C6dBaseline
#print axioms YangMills.RG.isCoerciveCLM_cmp99Eq360C6dSourceAmbientBaselinePrecision
#print axioms YangMills.RG.isCoerciveCLM_cmp99Eq360C6dSourceAmbientBaselineCompression
#print axioms YangMills.RG.cmp99Eq360C6dSourceAmbientBaselineDirichletGreen
#print axioms YangMills.RG.cmp99Eq360C6dSourceAmbientBaselinePrecision_comp_dirichletGreen
#print axioms YangMills.RG.cmp99Eq360C6dSourceAmbientBaselineDirichletGreen_eq_baseline
