import YangMills.RG.BalabanCMP102Eq80SourcePi4FTCConnectedDomainActivity

#print axioms YangMills.RG.continuous_cmp102Eq80SourcePi4FTCConnectedDomainActivity_comp
#print axioms YangMills.RG.intervalIntegrable_cmp102Eq80SourcePi4FTCConnectedDomainActivity_update
#print axioms YangMills.RG.cmp102Eq80SourcePi4FTCConnectedDomainTotal_eq_sum_activity
#print axioms YangMills.RG.cmp102Eq80SourcePi4FTCNondecoupledRemainder_eq_sum_connectedDomainActivity
