import YangMills.RG.BalabanCMP99SourceEq395GroupedNeumannDecay

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrection_grouped_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalCorrection_le_groupedNeumannRatio
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrection_pow_grouped_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrection_tsum_pow_grouped_exponentialKernelBound
