import YangMills.RG.BalabanCMP116Eq225OuterTraceInteractionResidual

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_analyticIntegrand_le_of_outerTraceInteractionEnergy_cutoff
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_outerTraceInteractionEnergy_cutoff_onPolydiscs
