/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116RestrictedVisitedTailSum

/-!
# Restricted visited-state transfer powers

This module identifies the recursive finite physical tail sum with the row
sum of a power of the augmented visited-state transfer matrix.

The first theorem is the exact one-step reindexing: every nonzero transfer
entry is generated by one unique physical successor.  No ambient-state
cardinality enters the formula.
-/

namespace YangMills.RG

noncomputable section

universe u v w

/-- Summing one transfer row against an arbitrary operator-valued function
is exactly the finite sum over declared physical successors. -/
theorem cmp116RestrictedVisitedTransferMatrix_row_mul_sum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (source : CMP116RestrictedTransferState Label Domain carrier)
    (F :
      CMP116RestrictedTransferState Label Domain carrier →
        Matrix Index Index ℂ) :
    (∑ target,
        cmp116RestrictedVisitedTransferMatrix
            carrier domainActive successors R sigma source target *
          F target) =
      ∑ step ∈ successors source.1.domain,
        CMP116RestrictedVisitedState.transitionWeight
            carrier sigma source.2 (domainActive step.domain) •
          (R step.label step.domain *
            F (cmp116RestrictedTransferNextState
              carrier domainActive source.2 step)) := by
  classical
  let nextState :=
    cmp116RestrictedTransferNextState
      (Label := Label) (Domain := Domain)
      carrier domainActive source.2
  let generated :=
    (successors source.1.domain).image nextState
  calc
    (∑ target,
        cmp116RestrictedVisitedTransferMatrix
            carrier domainActive successors R sigma source target *
          F target) =
        ∑ target ∈ generated,
          cmp116RestrictedVisitedTransferMatrix
              carrier domainActive successors R sigma source target *
            F target := by
      symm
      apply Finset.sum_subset (Finset.subset_univ generated)
      intro target _ hnot
      rw [
        cmp116RestrictedVisitedTransferMatrix_apply_eq_zero_of_not_mem_nextStates
          carrier domainActive successors R sigma source target hnot]
      simp
    _ =
        ∑ step ∈ successors source.1.domain,
          CMP116RestrictedVisitedState.transitionWeight
              carrier sigma source.2 (domainActive step.domain) •
            (R step.label step.domain *
              F (cmp116RestrictedTransferNextState
                carrier domainActive source.2 step)) := by
      rw [Finset.sum_image]
      · apply Finset.sum_congr rfl
        intro step hstep
        rw [
          cmp116RestrictedVisitedTransferMatrix_apply_nextState
            carrier domainActive successors R sigma source step hstep]
        simp [nextState]
      · exact
          (cmp116RestrictedTransferNextState_injective
            carrier domainActive source.2).injOn

/-- The row sum of the `n`-th transfer power is exactly the recursively
generated physical tail sum, for every augmented source state. -/
theorem cmp116RestrictedVisitedTransferMatrix_power_row_sum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ) :
    ∀ (n : ℕ)
      (source : CMP116RestrictedTransferState Label Domain carrier),
      (∑ target,
          (cmp116RestrictedVisitedTransferMatrix
              carrier domainActive successors R sigma ^ n)
            source target) =
        cmp116RestrictedVisitedTailSum
          carrier domainActive successors R sigma n
          source.1.domain source.2 := by
  classical
  intro n
  induction n with
  | zero =>
      intro source
      simp only [pow_zero, cmp116RestrictedVisitedTailSum]
      rw [Fintype.sum_eq_single source]
      · simp
      · intro target hne
        simp [Ne.symm hne]
  | succ n ih =>
      intro source
      let transfer :=
        cmp116RestrictedVisitedTransferMatrix
          carrier domainActive successors R sigma
      calc
        (∑ target, (transfer ^ (n + 1)) source target) =
            ∑ middle,
              transfer source middle *
                (∑ target, (transfer ^ n) middle target) := by
          rw [pow_succ']
          simp_rw [Matrix.mul_apply]
          rw [Finset.sum_comm]
          simp_rw [← Finset.mul_sum]
        _ =
            ∑ step ∈ successors source.1.domain,
              CMP116RestrictedVisitedState.transitionWeight
                  carrier sigma source.2 (domainActive step.domain) •
                (R step.label step.domain *
                  (∑ target,
                    (transfer ^ n)
                      (cmp116RestrictedTransferNextState
                        carrier domainActive source.2 step) target)) := by
          exact cmp116RestrictedVisitedTransferMatrix_row_mul_sum
            carrier domainActive successors R sigma source
              (fun middle => ∑ target, (transfer ^ n) middle target)
        _ =
            cmp116RestrictedVisitedTailSum
              carrier domainActive successors R sigma (n + 1)
              source.1.domain source.2 := by
          simp only [cmp116RestrictedVisitedTailSum]
          apply Finset.sum_congr rfl
          intro step _hstep
          rw [ih (cmp116RestrictedTransferNextState
            carrier domainActive source.2 step)]
          rfl

end

end YangMills.RG
