import YangMills.RG.BalabanCMP99Eq360C6dSourceSeparatedPhysicalBackground

#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedPhysicalBackground
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedPhysicalBackground_apply
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientSiteEquiv_shift
