import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedFlatPhysicalPointSourceEndpoint

#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalGreenQprimeStar_pointSource_apply_eq_normalized_sum_endpointIntegrand
