import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothBasicFactorDecay

#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalPrecisionWeightedRowAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedSmoothGreenLinearCommutatorPointAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedSmoothGreenCutoffWeightedRowAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedSmoothFineBasicWeightedRowAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalPrecision_weightedRowKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothFineSectionCBasicFactor_weightedRow

