/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102AmbientOrientedEdgeFDerivBound
import YangMills.RG.NearLogExpThirdDerivativeChangeOriginBound

/-!
# Physical third jet of one oriented ambient edge

The third derivative is generated by the literal noncommutative exponential
series.  Evaluation at one bond, right multiplication by the unitary
background, and conjugate transpose for the reverse orientation are all
contractive.  Consequently no edge-level third-jet certificate is supplied
by the caller.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d N Nc : ℕ} [NeZero d] [NeZero N] [NeZero Nc]

local instance cmp102AmbientThirdJetMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

local instance cmp102AmbientThirdJetMatrixCLMSeminormed :
    SeminormedAddCommGroup
      (Matrix (Fin Nc) (Fin Nc) ℂ →L[ℝ]
      Matrix (Fin Nc) (Fin Nc) ℂ) :=
  ContinuousLinearMap.toSeminormedAddCommGroup

local instance cmp102AmbientThirdJetEvalCLMSeminormed :
    SeminormedAddCommGroup
      (PhysicalAmbientMatrixTangent d N Nc →L[ℝ]
      Matrix (Fin Nc) (Fin Nc) ℂ) :=
  ContinuousLinearMap.toSeminormedAddCommGroup

/-- Right multiplication by a fixed matrix, bundled as a real continuous
linear map. -/
def cmp102AmbientRightMulCLM
    (A : Matrix (Fin Nc) (Fin Nc) ℂ) :
    Matrix (Fin Nc) (Fin Nc) ℂ →L[ℝ]
      Matrix (Fin Nc) (Fin Nc) ℂ :=
  MulOpposite.op A • ContinuousLinearMap.id ℝ
    (Matrix (Fin Nc) (Fin Nc) ℂ)

omit [NeZero Nc] in
@[simp] theorem cmp102AmbientRightMulCLM_apply
    (A X : Matrix (Fin Nc) (Fin Nc) ℂ) :
    cmp102AmbientRightMulCLM A X = X * A := by
  simp [cmp102AmbientRightMulCLM]

omit [NeZero Nc] in
/-- Right multiplication has operator norm at most the norm of its fixed
factor. -/
theorem norm_cmp102AmbientRightMulCLM_le
    (A : Matrix (Fin Nc) (Fin Nc) ℂ) :
    ‖cmp102AmbientRightMulCLM A‖ ≤ ‖A‖ := by
  apply ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg A)
  intro X
  simpa [mul_comm] using
    (norm_mul_le X A)

/-- Evaluation of one bond coordinate has operator norm at most one. -/
theorem norm_physicalAmbientBondEvalCLM_le_one
    (b : PhysicalBond d N) :
    ‖physicalAmbientBondEvalCLM
        (Nc := Nc) b‖ ≤ 1 := by
  apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
  intro Z
  simpa using
    norm_physicalAmbientMatrixTangent_apply_le
      (Nc := Nc) Z b

omit [NeZero Nc] in
/-- Conjugate transpose is contractive for the matrix operator norm. -/
theorem norm_matrixConjTransposeCLM_le_one :
    ‖matrixConjTransposeCLM (Nc := Nc)‖ ≤ 1 := by
  apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
  intro A
  simpa only [one_mul, matrixConjTransposeCLM_apply] using
    le_of_eq (Matrix.l2_opNorm_conjTranspose A)

/-- The third jet of the exponential after physical-bond evaluation inherits
the literal exponential coefficient budget. -/
theorem norm_iteratedFDeriv_three_physicalMatrixExp_eval_le
    (Z : PhysicalAmbientMatrixTangent d N Nc)
    (b : PhysicalBond d N) (r : NNReal)
    (hZ : ‖Z b‖₊ ≤ r) :
    ‖iteratedFDeriv ℝ 3
        (fun W : PhysicalAmbientMatrixTangent d N Nc =>
          physicalMatrixExp (W b)) Z‖ ≤
      expThirdDerivativeBallBudget
        (A := Matrix (Fin Nc) (Fin Nc) ℂ) r := by
  letI : IsTopologicalRing (Matrix (Fin Nc) (Fin Nc) ℂ) :=
    physicalMatrixTopologicalRing Nc
  let e := physicalAmbientBondEvalCLM
    (Nc := Nc) b
  have hexp : ContDiff ℝ ⊤
      (NormedSpace.exp :
        Matrix (Fin Nc) (Fin Nc) ℂ →
          Matrix (Fin Nc) (Fin Nc) ℂ) :=
    contDiff_iff_contDiffAt.mpr fun A =>
      (NormedSpace.exp_analytic A).contDiffAt
  have heNorm : ‖e‖ ≤ 1 :=
    norm_physicalAmbientBondEvalCLM_le_one
      (Nc := Nc) b
  change
    ‖iteratedFDeriv ℝ 3
        ((NormedSpace.exp :
          Matrix (Fin Nc) (Fin Nc) ℂ →
            Matrix (Fin Nc) (Fin Nc) ℂ) ∘ e) Z‖ ≤ _
  calc
    ‖iteratedFDeriv ℝ 3
        ((NormedSpace.exp :
          Matrix (Fin Nc) (Fin Nc) ℂ →
            Matrix (Fin Nc) (Fin Nc) ℂ) ∘ e) Z‖ =
        ‖(iteratedFDeriv ℝ 3
            (NormedSpace.exp :
              Matrix (Fin Nc) (Fin Nc) ℂ →
                Matrix (Fin Nc) (Fin Nc) ℂ)
            (e Z)).compContinuousLinearMap (fun _ => e)‖ :=
      congrArg norm
        (ContinuousLinearMap.iteratedFDeriv_comp_right
          (n := (⊤ : WithTop ℕ∞)) e hexp Z
          (i := 3) le_top)
    _ ≤
        ‖iteratedFDeriv ℝ 3
          (NormedSpace.exp :
            Matrix (Fin Nc) (Fin Nc) ℂ →
              Matrix (Fin Nc) (Fin Nc) ℂ) (e Z)‖ *
          ∏ _ : Fin 3, ‖e‖ :=
      ContinuousMultilinearMap.norm_compContinuousLinearMap_le _ _
    _ ≤
        ‖iteratedFDeriv ℝ 3
          (NormedSpace.exp :
            Matrix (Fin Nc) (Fin Nc) ℂ →
              Matrix (Fin Nc) (Fin Nc) ℂ) (e Z)‖ * 1 := by
      gcongr
      exact Finset.prod_le_one
        (fun _ _ => norm_nonneg e)
        (fun _ _ => heNorm)
    _ ≤ expThirdDerivativeBallBudget
          (A := Matrix (Fin Nc) (Fin Nc) ℂ) r := by
      rw [mul_one]
      exact norm_iteratedFDeriv_three_exp_le_ballBudget
        r (by simpa [e, physicalAmbientBondEvalCLM] using hZ)

/-- The actual third Fréchet derivative of one oriented physical edge is
bounded by the source-generated exponential budget.  Both orientations are
covered without a caller-supplied derivative estimate. -/
theorem norm_iteratedFDeriv_three_ambientOrientedEdgeMatrix_le
    (U : PhysicalGaugeBackground d N Nc)
    (Z : PhysicalAmbientMatrixTangent d N Nc)
    (e : ConcreteEdge d N) (r : NNReal)
    (hZ : ‖Z (physicalBondOfEdge e)‖₊ ≤ r) :
    ‖iteratedFDeriv ℝ 3
        (fun W => ambientOrientedEdgeMatrix U W e) Z‖ ≤
      expThirdDerivativeBallBudget
        (A := Matrix (Fin Nc) (Fin Nc) ℂ) r := by
  let b := physicalBondOfEdge e
  let base := orientedWilsonPositiveBase U e
  let right := cmp102AmbientRightMulCLM base
  have hright : ‖right‖ ≤ 1 := by
    exact (norm_cmp102AmbientRightMulCLM_le base).trans_eq
      (norm_orientedWilsonPositiveBase U e)
  have hpositive :
      ‖iteratedFDeriv ℝ 3
          (fun W : PhysicalAmbientMatrixTangent d N Nc =>
            ambientPositiveBondMatrix U W b) Z‖ ≤
        expThirdDerivativeBallBudget
          (A := Matrix (Fin Nc) (Fin Nc) ℂ) r := by
    have hexpEval :
        ContDiffAt ℝ ⊤
          (fun W : PhysicalAmbientMatrixTangent d N Nc =>
            physicalMatrixExp (W b)) Z :=
      (analyticAt_physicalMatrixExp_eval Z b).contDiffAt
    have hfun :
        (fun W : PhysicalAmbientMatrixTangent d N Nc =>
          ambientPositiveBondMatrix U W b) =
        right ∘
          (fun W : PhysicalAmbientMatrixTangent d N Nc =>
            physicalMatrixExp (W b)) := by
      funext W
      simp [ambientPositiveBondMatrix, right, base,
        orientedWilsonPositiveBase, b]
    rw [hfun]
    calc
      ‖iteratedFDeriv ℝ 3
          (right ∘
            (fun W : PhysicalAmbientMatrixTangent d N Nc =>
              physicalMatrixExp (W b))) Z‖
          ≤ ‖right‖ *
              ‖iteratedFDeriv ℝ 3
                (fun W : PhysicalAmbientMatrixTangent d N Nc =>
                  physicalMatrixExp (W b)) Z‖ :=
        right.norm_iteratedFDeriv_comp_left hexpEval le_top
      _ ≤ 1 *
          expThirdDerivativeBallBudget
            (A := Matrix (Fin Nc) (Fin Nc) ℂ) r := by
        gcongr
        exact norm_iteratedFDeriv_three_physicalMatrixExp_eval_le
          Z b r hZ
      _ = _ := one_mul _
  by_cases hs : e.sign
  · simpa [ambientOrientedEdgeMatrix, hs, b] using hpositive
  · have hpos :
        ContDiffAt ℝ ⊤
          (fun W : PhysicalAmbientMatrixTangent d N Nc =>
            ambientPositiveBondMatrix U W b) Z :=
      (analyticAt_ambientPositiveBondMatrix U Z b).contDiffAt
    let star := matrixConjTransposeCLM (Nc := Nc)
    have hfun :
        (fun W : PhysicalAmbientMatrixTangent d N Nc =>
          ambientOrientedEdgeMatrix U W e) =
        star ∘
          (fun W : PhysicalAmbientMatrixTangent d N Nc =>
            ambientPositiveBondMatrix U W b) := by
      funext W
      simp [ambientOrientedEdgeMatrix, hs, b, star]
    rw [hfun]
    calc
      ‖iteratedFDeriv ℝ 3
          (star ∘
            (fun W : PhysicalAmbientMatrixTangent d N Nc =>
              ambientPositiveBondMatrix U W b)) Z‖
          ≤ ‖star‖ *
              ‖iteratedFDeriv ℝ 3
                (fun W : PhysicalAmbientMatrixTangent d N Nc =>
                  ambientPositiveBondMatrix U W b) Z‖ :=
        star.norm_iteratedFDeriv_comp_left
          hpos le_top
      _ ≤ 1 *
          expThirdDerivativeBallBudget
            (A := Matrix (Fin Nc) (Fin Nc) ℂ) r := by
        gcongr
        exact norm_matrixConjTransposeCLM_le_one
      _ = _ := one_mul _

end

end YangMills.RG
