/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102AmbientWilsonLineFDerivBound
import YangMills.RG.BalabanCMP98SourceFieldScale

/-!
# Collapse of the literal ambient four-contour deviation

The CMP98 local deviation is written as three ordered Wilson lines followed
by the conjugate transpose of the straight coarse contour.  This module
proves that, in the real ambient chart used by the Hessian campaign, the
whole expression is literally one Wilson line along the source four-contour
word, minus the identity.

Consequently its value, derivative, value-Lipschitz, and
derivative-Lipschitz estimates are generated by the already audited
finite-line recurrences.  No four-factor constant is supplied by the caller.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102AmbientFourContourMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- Reversing one concrete edge is conjugate transpose in the ambient
real-analytic chart. -/
theorem ambientOrientedEdgeMatrix_reverse
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (e : ConcreteEdge d (M * N')) :
    ambientOrientedEdgeMatrix U Z
        (FiniteLatticeGeometry.reverse
          (d := d) (N := M * N') (G := SUN Nc) e) =
      (ambientOrientedEdgeMatrix U Z e)ᴴ := by
  change ambientOrientedEdgeMatrix U Z (edgeFlip e) =
    (ambientOrientedEdgeMatrix U Z e)ᴴ
  rcases e with ⟨x, i, sign⟩
  cases sign <;>
    simp [ambientOrientedEdgeMatrix, edgeFlip,
      physicalBondOfEdge]

/-- Ambient Wilson lines multiply under literal list concatenation. -/
theorem cmp98AmbientWilsonLineMatrix_append
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es₁ es₂ : List (ConcreteEdge d (M * N'))) :
    cmp98AmbientWilsonLineMatrix U Z (es₁ ++ es₂) =
      cmp98AmbientWilsonLineMatrix U Z es₁ *
        cmp98AmbientWilsonLineMatrix U Z es₂ := by
  induction es₁ with
  | nil =>
      simp
  | cons e es ih =>
      simp only [List.cons_append, cmp98AmbientWilsonLineMatrix_cons,
        ih, mul_assoc]

/-- Reversal of an ambient Wilson line is conjugate transpose.  This uses
real differentiability: conjugate transpose is a real-linear isometry. -/
theorem cmp98AmbientWilsonLineMatrix_reverseLatticePath
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) :
    cmp98AmbientWilsonLineMatrix U Z
        (reverseLatticePath
          (d := d) (N := M * N') (G := SUN Nc) es) =
      (cmp98AmbientWilsonLineMatrix U Z es)ᴴ := by
  induction es with
  | nil =>
      rw [reverseLatticePath_nil,
        cmp98AmbientWilsonLineMatrix_nil,
        Matrix.conjTranspose_one]
  | cons e es ih =>
      have hsingle :
          cmp98AmbientWilsonLineMatrix U Z
              [FiniteLatticeGeometry.reverse
                (d := d) (N := M * N') (G := SUN Nc) e] =
            (ambientOrientedEdgeMatrix U Z e)ᴴ := by
        rw [cmp98AmbientWilsonLineMatrix_cons,
          cmp98AmbientWilsonLineMatrix_nil, mul_one,
          ambientOrientedEdgeMatrix_reverse]
      rw [reverseLatticePath_cons,
        cmp98AmbientWilsonLineMatrix_append, ih, hsingle,
        cmp98AmbientWilsonLineMatrix_cons,
        Matrix.conjTranspose_mul]

/-- The literal local deviation is one source four-contour Wilson line
minus the identity, also away from the physical skew-adjoint slice. -/
theorem cmp98UbarAmbientDeviationMatrix_eq_sourceFourContour
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc) :
    cmp98UbarAmbientDeviationMatrix U b x Z =
      cmp98AmbientWilsonLineMatrix U Z
        (cmp98SourceFourContourEdges (Nc := Nc) b x) - 1 := by
  unfold cmp98UbarAmbientDeviationMatrix cmp98SourceFourContourEdges
  rw [cmp98AmbientWilsonLineMatrix_append,
    cmp98AmbientWilsonLineMatrix_append,
    cmp98AmbientWilsonLineMatrix_append,
    cmp98AmbientWilsonLineMatrix_reverseLatticePath]

/-- Source-generated value budget for the literal local deviation. -/
theorem norm_cmp98UbarAmbientDeviationMatrix_le_lineBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r : ℝ} (hr : 0 ≤ r)
    (hZ : ∀ e ∈ cmp98SourceFourContourEdges (Nc := Nc) b x,
      ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ ≤
      cmp98AmbientWilsonLineValueBudget r
          (cmp98SourceFourContourEdges (Nc := Nc) b x).length + 1 := by
  rw [cmp98UbarAmbientDeviationMatrix_eq_sourceFourContour]
  exact (norm_sub_le _ _).trans
    (add_le_add
      (norm_cmp98AmbientWilsonLineMatrix_le U Z _ hr hZ)
      (by simp))

/-- Source-generated derivative budget for the literal local deviation. -/
theorem norm_fderiv_cmp98UbarAmbientDeviationMatrix_le_lineBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r : ℝ} (hr : 0 ≤ r)
    (hZ : ∀ e ∈ cmp98SourceFourContourEdges (Nc := Nc) b x,
      ‖Z (physicalBondOfEdge e)‖ ≤ r) :
    ‖fderiv ℝ (fun W => cmp98UbarAmbientDeviationMatrix U b x W) Z‖ ≤
      cmp98AmbientWilsonLineDerivativeBudget r
        (cmp98SourceFourContourEdges (Nc := Nc) b x).length := by
  have hfun :
      (fun W : PhysicalAmbientMatrixTangent d (M * N') Nc =>
        cmp98UbarAmbientDeviationMatrix U b x W) =
      fun W =>
        cmp98AmbientWilsonLineMatrix U W
          (cmp98SourceFourContourEdges (Nc := Nc) b x) - 1 := by
    funext W
    exact cmp98UbarAmbientDeviationMatrix_eq_sourceFourContour U b x W
  rw [hfun, fderiv_sub_const]
  exact norm_fderiv_cmp98AmbientWilsonLineMatrix_le U Z _ hr hZ

/-- Source-generated value-Lipschitz budget for the literal deviation. -/
theorem norm_cmp98UbarAmbientDeviationMatrix_sub_le_lineBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r : ℝ} (hr : 0 ≤ r)
    (hZ : ∀ e ∈ cmp98SourceFourContourEdges (Nc := Nc) b x,
      ‖Z (physicalBondOfEdge e)‖ ≤ r)
    (hW : ∀ e ∈ cmp98SourceFourContourEdges (Nc := Nc) b x,
      ‖W (physicalBondOfEdge e)‖ ≤ r) :
    ‖cmp98UbarAmbientDeviationMatrix U b x Z -
        cmp98UbarAmbientDeviationMatrix U b x W‖ ≤
      cmp98AmbientWilsonLineValueLipschitzBudget r
          (cmp98SourceFourContourEdges (Nc := Nc) b x).length *
        ‖Z - W‖ := by
  rw [cmp98UbarAmbientDeviationMatrix_eq_sourceFourContour,
    cmp98UbarAmbientDeviationMatrix_eq_sourceFourContour]
  simpa only [sub_sub_sub_cancel_right] using
    norm_cmp98AmbientWilsonLineMatrix_sub_le U Z W _ hr hZ hW

/-- Source-generated derivative-Lipschitz budget for the literal
deviation. -/
theorem norm_fderiv_cmp98UbarAmbientDeviationMatrix_sub_le_lineBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r : ℝ} (hr : 0 ≤ r)
    (hZ : ∀ e ∈ cmp98SourceFourContourEdges (Nc := Nc) b x,
      ‖Z (physicalBondOfEdge e)‖ ≤ r)
    (hW : ∀ e ∈ cmp98SourceFourContourEdges (Nc := Nc) b x,
      ‖W (physicalBondOfEdge e)‖ ≤ r) :
    ‖fderiv ℝ (fun V => cmp98UbarAmbientDeviationMatrix U b x V) Z -
        fderiv ℝ (fun V => cmp98UbarAmbientDeviationMatrix U b x V) W‖ ≤
      cmp98AmbientWilsonLineDerivativeLipschitzBudget r
          (cmp98SourceFourContourEdges (Nc := Nc) b x).length *
        ‖Z - W‖ := by
  have hfun :
      (fun V : PhysicalAmbientMatrixTangent d (M * N') Nc =>
        cmp98UbarAmbientDeviationMatrix U b x V) =
      fun V =>
        cmp98AmbientWilsonLineMatrix U V
          (cmp98SourceFourContourEdges (Nc := Nc) b x) - 1 := by
    funext V
    exact cmp98UbarAmbientDeviationMatrix_eq_sourceFourContour U b x V
  rw [hfun, fderiv_sub_const, fderiv_sub_const]
  exact norm_fderiv_cmp98AmbientWilsonLineMatrix_sub_le
    U Z W _ hr hZ hW

end

end YangMills.RG
