/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP98Eq124ContourSplit
import YangMills.RG.BalabanCMP98LeftTrivializedExp

/-!
# Physical `g(ad)` form of CMP98 equation (124)

The literal logarithmic block average has already been differentiated on a
physical one-cochain and split into its middle-contour term and its three
corrections.  This module differentiates the outer exponential and consumes
the exact source identity

`exp(-B) D exp_B = g(ad B)`.

Thus `g(ad)` is no longer a symbolic correction supplied to equation (124):
it is generated by the physical exponential of the literal logarithmic
average.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp98Eq124GAdMatrixL2NormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- The outer exponential in the literal nonlinear block average. -/
def cmp98UbarExpAverage
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N')
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc) :
    Matrix (Fin Nc) (Fin Nc) ℂ :=
  NormedSpace.exp (cmp98UbarLogAverage U b Z)

/-- Exact derivative of the outer exponential at the physical background. -/
theorem hasFDerivAt_cmp98UbarExpAverage
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N')
    (hsmall : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ < 1) :
    HasFDerivAt (cmp98UbarExpAverage U b)
      ((fderiv ℝ
          (NormedSpace.exp : Matrix (Fin Nc) (Fin Nc) ℂ →
            Matrix (Fin Nc) (Fin Nc) ℂ)
          (cmp98UbarLogAverage U b 0)).comp
        (fderiv ℝ (cmp98UbarLogAverage U b) 0)) 0 := by
  have hExp := hasFDerivAt_exp_ordered (cmp98UbarLogAverage U b 0)
  have hLog := hasFDerivAt_cmp98UbarLogAverage U b 0 hsmall
  have hcomp := hExp.comp 0 hLog
  convert hcomp using 1
  exact congrArg₂ (fun f g => f.comp g) hExp.fderiv hLog.fderiv

/-- On a physical tangent, the derivative of the outer exponential consumes
the already constructed physical logarithmic variation. -/
theorem fderiv_cmp98UbarExpAverage_zero_apply_physical
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N')
    (hsmall : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ < 1) :
    fderiv ℝ (cmp98UbarExpAverage U b) 0
        (physicalSuTangentToAmbient
          (physicalCochainToSuMatrixTangent A)) =
      fderiv ℝ
          (NormedSpace.exp : Matrix (Fin Nc) (Fin Nc) ℂ →
            Matrix (Fin Nc) (Fin Nc) ℂ)
          (cmp98UbarLogAverage U b 0)
        (cmp98UbarLogAveragePhysicalVariation U A b) := by
  have houter := (hasFDerivAt_cmp98UbarExpAverage U b hsmall).fderiv
  rw [houter, ContinuousLinearMap.comp_apply]
  rw [fderiv_cmp98UbarLogAverage_zero_apply_physical U A b hsmall]

/-- The complete physical `g(ad)` contribution to CMP98 (124). -/
def cmp98Eq124GAdPhysicalVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') : Matrix (Fin Nc) (Fin Nc) ℂ :=
  cmp98GAd (cmp98UbarLogAverage U b 0)
    (cmp98UbarLogAveragePhysicalVariation U A b)

/-- The distinguished middle-contour `g(ad)` contribution. -/
def cmp98Eq124GAdMiddleVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') : Matrix (Fin Nc) (Fin Nc) ℂ :=
  cmp98GAd (cmp98UbarLogAverage U b 0)
    (cmp98Eq124MiddleLogVariation U A b)

/-- The three remaining raw contour-derivative contributions after the same
`g(ad)` map.  These are not yet claimed to coincide term-by-term with the
three algebraically regrouped correction lines printed in CMP98 (124). -/
def cmp98Eq124GAdCorrectionVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') : Matrix (Fin Nc) (Fin Nc) ℂ :=
  cmp98GAd (cmp98UbarLogAverage U b 0)
    (cmp98Eq124CorrectionLogVariation U A b)

/-- Exact source-shaped split after applying `g(ad)`. -/
theorem cmp98Eq124GAdPhysicalVariation_eq_middle_add_corrections
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') :
    cmp98Eq124GAdPhysicalVariation U A b =
      cmp98Eq124GAdMiddleVariation U A b +
        cmp98Eq124GAdCorrectionVariation U A b := by
  rw [cmp98Eq124GAdPhysicalVariation, cmp98Eq124GAdMiddleVariation,
    cmp98Eq124GAdCorrectionVariation,
    cmp98UbarLogAveragePhysicalVariation_eq_middle_add_corrections,
    map_add]

/- **Physical consumption of CMP98 (32)--(33) inside (124).**  The
left-trivialized derivative of the literal outer exponential is exactly the
constructed `g(ad)` physical variation. -/
theorem cmp98Eq124_leftTrivialized_physicalVariation_eq_gad
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N')
    (hsmall : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ < 1) :
    NormedSpace.exp (-(cmp98UbarLogAverage U b 0)) *
        fderiv ℝ (cmp98UbarExpAverage U b) 0
          (physicalSuTangentToAmbient
            (physicalCochainToSuMatrixTangent A)) =
      cmp98Eq124GAdPhysicalVariation U A b := by
  rw [fderiv_cmp98UbarExpAverage_zero_apply_physical U A b hsmall]
  exact cmp98_exp_neg_mul_fderiv_exp_eq_gad_apply
    (cmp98UbarLogAverage U b 0)
    (cmp98UbarLogAveragePhysicalVariation U A b)

/-- Terminal four-contour form of the physical left-trivialized variation. -/
theorem cmp98Eq124_leftTrivialized_physicalVariation_eq_middle_add_corrections
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N')
    (hsmall : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ < 1) :
    NormedSpace.exp (-(cmp98UbarLogAverage U b 0)) *
        fderiv ℝ (cmp98UbarExpAverage U b) 0
          (physicalSuTangentToAmbient
            (physicalCochainToSuMatrixTangent A)) =
      cmp98Eq124GAdMiddleVariation U A b +
        cmp98Eq124GAdCorrectionVariation U A b := by
  rw [cmp98Eq124_leftTrivialized_physicalVariation_eq_gad U A b hsmall,
    cmp98Eq124GAdPhysicalVariation_eq_middle_add_corrections]

end

end YangMills.RG
