import YangMills.RG.BalabanCMP99SourceGeneratedRegionalCorrectionDecay

/-!
# Audit for the physical single-cell regional correction

PRE-VALIDATION: this source is present, its `.olean` has not yet been
materialized, and its declarations have not yet been compiler-verified.
-/

#print axioms YangMills.RG.CMP99RegionalFineSquarePartition.norm_value_le_one
#print axioms YangMills.RG.cmp99RegionalDirichletPrecision_exponentialKernelBound
#print axioms YangMills.RG.cmp99RegionalDirichletGreen_exponentialKernelBound
#print axioms YangMills.RG.cmp99RegionalExtendedDirichletGreen_exponentialKernelBound
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalAmbientPrecisionDecayAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalAmbientPrecision_exponentialKernelBound
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCell
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCell_hasFiniteRangeMargin
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalGreenRate
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCorrectionAmplitude
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalExtendedGreen_exponentialKernelBound
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalRegionalCorrection_exponentialKernelBound
