import YangMills.RG.BalabanCMP99Eq337ComplexClosedRadiusScalar

/-!
Cold-sealed with the imported source from checkpoint
`ae676b71f2bae392560db80cbadcd24e6193305a`; see
`validation-evidence/eq337-complex-closed-radius-module-cold-ae676b71`.
-/

#print axioms YangMills.RG.cmp99ComplexClosedRadiusFactorEnvelope_mono
#print axioms YangMills.RG.cmp99ComplexClosedRadiusAt_next
#print axioms YangMills.RG.cmp99ComplexClosedRadiusDeviation_le_coefficient_mul
#print axioms YangMills.RG.cmp99ComplexClosedRadiusDeviation_nonneg
#print axioms YangMills.RG.cmp99ComplexClosedRadiusExp_le_four_mul
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNextLink_le_coefficient_mul
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNextLink_nonneg
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNext_le_two_mul
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNext_nonneg
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNext_le_growthFactor_mul
#print axioms YangMills.RG.cmp99ComplexClosedRadiusDeviationCoefficient_pos
#print axioms YangMills.RG.cmp99ComplexClosedRadiusLinkCoefficient_pos
#print axioms YangMills.RG.one_le_cmp99ComplexClosedRadiusGrowthFactor
#print axioms YangMills.RG.CMP99ComplexClosedRadiusBudget.radiusAt_nonneg_and_le
#print axioms YangMills.RG.CMP99ComplexClosedRadiusBudget.deviation_lt_threshold
