import YangMills.RG.BalabanCMP99Eq360C6dSourceSeparatedAmbientMetric

#print axioms YangMills.RG.finBoxDist_cmp99SourceFullActiveRegionSiteEquiv
#print axioms YangMills.RG.finBoxDist_cmp99SourceSeparatedGeneratedPhysicalStep7bActiveSiteEquiv
#print axioms YangMills.RG.finBoxDist_cmp99Eq360C6dSourceSeparatedAmbientSiteEquiv
