-- Promotion import:
import YangMills.RG.BalabanCMP99DiagonalFiniteGreenOwnerBound


-- SEALED AXIOM SURFACE: intended axiom surface for Step 8b.23/Unit F.22.

#print axioms YangMills.RG.cmp99DiagonalPeriodicDisplacement
#print axioms YangMills.RG.cmp89Eq251LatticeL1Length_cmp99DiagonalPeriodicDisplacement_eq
#print axioms YangMills.RG.cmp89Eq251LatticeL1Length_centeredDiagonalPeriodicDisplacement_eq
#print axioms YangMills.RG.cmp99DiagonalOwner_mul_dist_real_le_periodicL1_add_boundary
#print axioms YangMills.RG.cmp89SignedLatticeL1ExponentialWeight_centeredDiagonal_le_owner
#print axioms YangMills.RG.norm_tsum_cmp89Eq248PhysicalGreen_zeroResidue_le_diagonalOwner_draft
