/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceRetainedPhysicalTower
import YangMills.RG.BalabanCMP99SourceStratumTowerCovariance
import YangMills.RG.BalabanCMP99SourceMassWeights
import YangMills.RG.BalabanCMP99OneScalePhysicalGreenCovariance
import YangMills.RG.BalabanCMP99SourceStratifiedPrecisionNorm

/-!
# The CMP99 stratified mass from one retained physical `Ubar` tower

This adapter removes the remaining possibility of supplying unrelated
operators `Q'_r` to the mass in CMP99 (3.24).  Every scale operator is the
corresponding prefix retained from one recursively generated physical tower.
The only dictionary is an isometric identification of its terminal carrier
with the source lattice on which `Lambda_r` lives.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped BigOperators Matrix.Norms.L2Operator RealInnerProductSpace

noncomputable section

universe u v

variable {d M N Nc depth : ℕ}
variable [NeZero d] [NeZero M] [NeZero N] [NeZero Nc]
variable {rho : SUNAdjointModel Nc}
variable {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
variable {background : GaugeConfig d N (SUN Nc)}

/-- The scale typing of one retained physical tower.  Its constructor is
private: the only public producer below uses the literal site family and
isometries generated by the tower itself. -/
structure CMP99SourceRetainedPhysicalScaleIdentification
    {FineSite : Type u} [DecidableEq FineSite]
    {ScaleSite : Fin (depth + 1) → Type v}
    [∀ r, DecidableEq (ScaleSite r)] [∀ r, Fintype (ScaleSite r)]
    (T : CMP99SourceRetainedPhysicalTower rho Omega M spacing background depth)
    (S : CMP99SourceScaledStratification FineSite (depth + 1) ScaleSite) where
  private mk ::
  levelEquiv : ∀ r : Fin (depth + 1),
    (T.towerAt r).TerminalSpace.carrier ≃ₗᵢ[ℝ]
      CMP99SourceScaledStratification.ScaleField
        (ScaleSite := ScaleSite) (SUNLieCoord Nc) r

namespace CMP99SourceRetainedPhysicalScaleIdentification

/-- Canonical scale identification.  No scale-site type or isometry is a
caller input: both come from the private physical recursion in `T`. -/
noncomputable def ofRetainedTower
    {FineSite : Type u} [DecidableEq FineSite]
    (T : CMP99SourceRetainedPhysicalTower
      rho Omega M spacing background depth)
    (S : CMP99SourceScaledStratification
      FineSite (depth + 1) T.levelSite) :
    CMP99SourceRetainedPhysicalScaleIdentification T S :=
  CMP99SourceRetainedPhysicalScaleIdentification.mk T.levelEquiv

@[simp] theorem ofRetainedTower_levelEquiv
    {FineSite : Type u} [DecidableEq FineSite]
    (T : CMP99SourceRetainedPhysicalTower
      rho Omega M spacing background depth)
    (S : CMP99SourceScaledStratification
      FineSite (depth + 1) T.levelSite)
    (r : Fin (depth + 1)) :
    (ofRetainedTower T S).levelEquiv r = T.levelEquiv r := rfl

variable {FineSite : Type u} [DecidableEq FineSite]
variable {ScaleSite : Fin (depth + 1) → Type v}
variable [∀ r, DecidableEq (ScaleSite r)] [∀ r, Fintype (ScaleSite r)]
variable {T : CMP99SourceRetainedPhysicalTower
  rho Omega M spacing background depth}
variable {S : CMP99SourceScaledStratification
  FineSite (depth + 1) ScaleSite}

/-- The literal order-`r` average from the retained physical `Ubar` chain. -/
noncomputable def Qprime
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      CMP99SourceScaledStratification.ScaleField
        (ScaleSite := ScaleSite) (SUNLieCoord Nc) r :=
  (I.levelEquiv r).toContinuousLinearMap.comp (T.towerAt r).Qprime

/-- The complete precision in CMP99 (3.23)--(3.24), with every mass average
generated by the same physical background chain. -/
noncomputable def gaugePrecision
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  cmp99SourceScaledGaugePrecision S covariantLaplacian I.Qprime d a L eta

/-- The physical retained precision inherits coercivity from its covariant
Laplacian; all printed mass weights are nonnegative. -/
theorem gaugePrecision_isCoercive
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    IsCoerciveCLM (I.gaugePrecision covariantLaplacian a L eta) c := by
  exact isCoerciveCLM_cmp99SourceStratifiedGaugePrecision
    (fun r => CMP99SourceScaledStratification.ScaleField
      (ScaleSite := ScaleSite) (SUNLieCoord Nc) r)
    (fun r => S.StratumField (SUNLieCoord Nc) r)
    covariantLaplacian I.Qprime (fun r => S.restrictStratumCLM r)
    (fun r => le_of_lt
      (cmp99SourceCountingStratumWeight_pos d ha hL heta r)) hDelta

/-- Symmetry of the complete retained precision. -/
theorem gaugePrecision_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) (hDelta : covariantLaplacian.IsSymmetric) :
    (I.gaugePrecision covariantLaplacian a L eta).IsSymmetric := by
  exact cmp99SourceStratifiedGaugePrecision_isSymmetric
    (fun r => CMP99SourceScaledStratification.ScaleField
      (ScaleSite := ScaleSite) (SUNLieCoord Nc) r)
    (fun r => S.StratumField (SUNLieCoord Nc) r)
    covariantLaplacian I.Qprime (fun r => S.restrictStratumCLM r)
    (cmp99SourceCountingStratumWeight d a L eta) hDelta

/-- Green operator generated from the complete retained precision. -/
noncomputable def green
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  covarianceOfIsCoerciveCLM
    (I.gaugePrecision covariantLaplacian a L eta) hc
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)

/-- Exact right Green identity. -/
theorem gaugePrecision_comp_green
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    (I.gaugePrecision covariantLaplacian a L eta).comp
        (I.green covariantLaplacian ha hL heta hc hDelta) =
      ContinuousLinearMap.id ℝ
        (ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) := by
  exact precision_comp_covarianceOfIsCoerciveCLM _ hc _

/-- Exact left Green identity. -/
theorem green_comp_gaugePrecision
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c) :
    (I.green covariantLaplacian ha hL heta hc hDelta).comp
        (I.gaugePrecision covariantLaplacian a L eta) =
      ContinuousLinearMap.id ℝ
        (ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) := by
  exact covarianceOfIsCoerciveCLM_comp_precision _ hc _

/-- Symmetry of the generated full Green. -/
theorem green_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric) :
    (I.green covariantLaplacian ha hL heta hc hDelta).IsSymmetric := by
  exact covarianceOfIsCoerciveCLM_isSymmetric _ hc
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)

/-- The actual source average restricted to `Lambda_r`. -/
noncomputable def stratumAverage
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  (T.towerAt r).stratumAverage S r (I.levelEquiv r)

/-- Its exact source-weighted adjoint. -/
noncomputable def stratumWeightedAdjoint
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  (T.towerAt r).stratumWeightedAdjoint S r (I.levelEquiv r)

/-- Coisometry of every physically retained restricted average. -/
theorem stratumAverage_comp_stratumWeightedAdjoint
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    (I.stratumAverage r).comp (I.stratumWeightedAdjoint r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) :=
  (T.towerAt r).stratumAverage_comp_stratumWeightedAdjoint
    S r (I.levelEquiv r)

/-- The exact terminal spacing of the retained prefix is positive, derived
from the physical scale and the initial spacing. -/
theorem towerAt_terminalSpacing_pos
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing) :
    0 < (T.towerAt r).terminalSpacing := by
  rw [T.towerAt_terminalSpacing]
  exact mul_pos (pow_pos hM r.val) hspacing

/-- Restriction to a source stratum is a counting-norm contraction. -/
theorem norm_restrictStratumCLM_le_one
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) :
    ‖S.restrictStratumCLM (g := SUNLieCoord Nc) r‖ ≤ 1 := by
  apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
  intro phi
  have hsq : ‖S.restrictStratumCLM r phi‖ ^ 2 ≤ ‖phi‖ ^ 2 := by
    rw [S.norm_restrictStratumCLM_sq, PiLp.norm_sq_eq_of_L2]
    exact Finset.sum_le_sum_of_subset_of_nonneg
      (Finset.subset_univ (S.strata r))
      (fun y _ _ => sq_nonneg ‖phi y‖)
  nlinarith [norm_nonneg (S.restrictStratumCLM r phi), norm_nonneg phi]

/-- The canonical scale dictionary preserves the exact iterated source
contraction.  Thus the typed order-`r` average carries the literal factor
`(M⁻ᵈ)^r`, not merely the coarse estimate `≤ 1`. -/
theorem norm_Qprime_apply_sq_le_pow
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    ‖I.Qprime r phi‖ ^ 2 ≤
      (cmp99SourceBlockAverageWeight M d) ^ r.val * ‖phi‖ ^ 2 := by
  change ‖I.levelEquiv r ((T.towerAt r).Qprime phi)‖ ^ 2 ≤ _
  rw [(I.levelEquiv r).norm_map]
  exact T.norm_Qprime_sq_le_pow r phi

/-- Restricting the physical order-`r` average to the printed stratum
`Lambda_r` preserves the same exact multiscale contraction factor. -/
theorem norm_stratumAverage_apply_sq_le_pow
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    ‖I.stratumAverage r phi‖ ^ 2 ≤
      (cmp99SourceBlockAverageWeight M d) ^ r.val * ‖phi‖ ^ 2 := by
  have hrestrict :
      ‖S.restrictStratumCLM r (I.Qprime r phi)‖ ^ 2 ≤
        ‖I.Qprime r phi‖ ^ 2 := by
    rw [S.norm_restrictStratumCLM_sq, PiLp.norm_sq_eq_of_L2]
    exact Finset.sum_le_sum_of_subset_of_nonneg
      (Finset.subset_univ (S.strata r))
      (fun y _ _ => sq_nonneg ‖I.Qprime r phi y‖)
  calc
    ‖I.stratumAverage r phi‖ ^ 2 =
        ‖S.restrictStratumCLM r (I.Qprime r phi)‖ ^ 2 := rfl
    _ ≤ ‖I.Qprime r phi‖ ^ 2 := hrestrict
    _ ≤ (cmp99SourceBlockAverageWeight M d) ^ r.val * ‖phi‖ ^ 2 :=
      I.norm_Qprime_apply_sq_le_pow r phi

/-- The complete physical mass contribution in CMP99 (3.24) is bounded by
the printed coefficient sum with the generated multiscale volume factors.
No norm bound for any `Q'_r` is supplied by the caller. -/
theorem inner_gaugePrecision_le_with_source_prefix_weights
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta : ℝ} (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta)
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    inner ℝ phi (I.gaugePrecision covariantLaplacian a L eta phi) ≤
      inner ℝ phi (covariantLaplacian phi) +
        (∑ r : Fin (depth + 1),
          cmp99SourceCountingStratumWeight d a L eta r *
            (cmp99SourceBlockAverageWeight M d) ^ r.val) * ‖phi‖ ^ 2 := by
  rw [gaugePrecision, cmp99SourceScaledGaugePrecision,
    CMP99SourceScaledStratification.sourceGaugeMass,
    ContinuousLinearMap.add_apply, inner_add_right,
    inner_cmp99SourceStratifiedGaugeMass]
  apply add_le_add_right
  calc
    (∑ r : Fin (depth + 1),
        cmp99SourceCountingStratumWeight d a L eta r *
          ‖S.restrictStratumCLM r (I.Qprime r phi)‖ ^ 2) ≤
      ∑ r : Fin (depth + 1),
        cmp99SourceCountingStratumWeight d a L eta r *
          ((cmp99SourceBlockAverageWeight M d) ^ r.val * ‖phi‖ ^ 2) := by
        apply Finset.sum_le_sum
        intro r _hr
        exact mul_le_mul_of_nonneg_left
          (I.norm_stratumAverage_apply_sq_le_pow r phi)
          (le_of_lt (cmp99SourceCountingStratumWeight_pos d ha hL heta r))
    _ = (∑ r : Fin (depth + 1),
          cmp99SourceCountingStratumWeight d a L eta r *
            (cmp99SourceBlockAverageWeight M d) ^ r.val) * ‖phi‖ ^ 2 := by
      rw [Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro r _hr
      ring

/-- Every physical retained prefix is a contraction in counting norm.  The
monotonicity of the source spacing is generated from `M >= 1`. -/
theorem norm_Qprime_le_one
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1)) (hspacing : 0 < spacing) :
    ‖I.Qprime r‖ ≤ 1 := by
  have hMone : (1 : ℝ) ≤ M := by
    exact_mod_cast Nat.one_le_iff_ne_zero.mpr (NeZero.ne M)
  have hterminal : 0 < (T.towerAt r).terminalSpacing :=
    I.towerAt_terminalSpacing_pos r (zero_lt_one.trans_le hMone) hspacing
  have hmono : spacing ≤ (T.towerAt r).terminalSpacing := by
    rw [T.towerAt_terminalSpacing]
    calc
      spacing = 1 * spacing := by ring
      _ ≤ (M : ℝ) ^ r.val * spacing :=
        mul_le_mul_of_nonneg_right (one_le_pow₀ hMone) hspacing.le
  have hTower : ‖(T.towerAt r).Qprime‖ ≤ 1 :=
    (T.towerAt r).norm_Qprime_le_one_unconditional
      hspacing.le hterminal hmono
  apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
  intro phi
  change ‖I.levelEquiv r ((T.towerAt r).Qprime phi)‖ ≤ 1 * ‖phi‖
  rw [(I.levelEquiv r).norm_map]
  calc
    ‖(T.towerAt r).Qprime phi‖ ≤
        ‖(T.towerAt r).Qprime‖ * ‖phi‖ :=
      ContinuousLinearMap.le_opNorm _ _
    _ ≤ 1 * ‖phi‖ :=
      mul_le_mul_of_nonneg_right hTower (norm_nonneg phi)

/-- Explicit volume-independent upper-bound constant for the complete
retained precision. -/
noncomputable def precisionUpperBound
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) : ℝ :=
  1 + ‖covariantLaplacian‖ +
    ∑ r : Fin (depth + 1),
      |cmp99SourceCountingStratumWeight d a L eta r|

/-- The explicit precision bound is strictly positive without any
nondegeneracy premise on the finite ambient carrier. -/
theorem precisionUpperBound_pos
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) :
    0 < I.precisionUpperBound covariantLaplacian a L eta := by
  unfold precisionUpperBound
  positivity

/-- B2 upper bound for the complete physical retained precision.  It uses
only the ambient Laplacian norm and the printed finite mass coefficients;
no region or volume cardinality occurs. -/
theorem norm_gaugePrecision_le_precisionUpperBound
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (a L eta : ℝ) (hspacing : 0 < spacing) :
    ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤
      I.precisionUpperBound covariantLaplacian a L eta := by
  let weight : Fin (depth + 1) → ℝ :=
    cmp99SourceCountingStratumWeight d a L eta
  let A : ∀ r : Fin (depth + 1),
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        S.StratumField (SUNLieCoord Nc) r :=
    fun r => (S.restrictStratumCLM r).comp (I.Qprime r)
  have hA : ∀ r, ‖A r‖ ≤ 1 := by
    intro r
    calc
      ‖A r‖ ≤ ‖S.restrictStratumCLM (g := SUNLieCoord Nc) r‖ *
          ‖I.Qprime r‖ :=
        ContinuousLinearMap.opNorm_comp_le _ _
      _ ≤ 1 := by
        have hR := I.norm_restrictStratumCLM_le_one r
        have hQ := I.norm_Qprime_le_one r hspacing
        nlinarith [norm_nonneg (S.restrictStratumCLM
          (g := SUNLieCoord Nc) r), norm_nonneg (I.Qprime r)]
  unfold gaugePrecision precisionUpperBound cmp99SourceScaledGaugePrecision
  calc
    ‖cmp99SourceStratifiedGaugePrecision
        (fun r => CMP99SourceScaledStratification.ScaleField
          (ScaleSite := ScaleSite) (SUNLieCoord Nc) r)
        (fun r => S.StratumField (SUNLieCoord Nc) r)
        covariantLaplacian I.Qprime (fun r => S.restrictStratumCLM r)
        weight‖ ≤
        ‖covariantLaplacian‖ + ∑ r : Fin (depth + 1), |weight r| :=
      norm_cmp99SourceStratifiedGaugePrecision_le
        (fun r => CMP99SourceScaledStratification.ScaleField
          (ScaleSite := ScaleSite) (SUNLieCoord Nc) r)
        (fun r => S.StratumField (SUNLieCoord Nc) r)
        covariantLaplacian I.Qprime (fun r => S.restrictStratumCLM r)
        weight hA
    _ ≤ 1 + ‖covariantLaplacian‖ +
        ∑ r : Fin (depth + 1), |weight r| := by linarith

/-- The middle operator `Q'_r (G')^2 (Q'_r)^dagger` on the literal stratum. -/
noncomputable def stratumCoarseCovarianceMiddle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  (T.towerAt r).stratumCoarseCovarianceMiddle S r (I.levelEquiv r)
    (I.green covariantLaplacian ha hL heta hc hDelta)

/-- B5 for one source stratum: a uniform upper bound on the complete
precision yields the printed lower bound on the generated middle operator.
No adjoint lower bound, surjectivity, or terminal-spacing premise is free. -/
theorem isCoerciveCLM_stratumCoarseCovarianceMiddle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    IsCoerciveCLM
      (I.stratumCoarseCovarianceMiddle covariantLaplacian
        ha hL heta hc hDelta r) (Lambda ^ 2)⁻¹ := by
  exact (T.towerAt r).isCoerciveCLM_stratumCoarseCovarianceMiddle
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- The generated printed covariance on the physical stratum. -/
noncomputable def stratumCoarseCovariance
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  (T.towerAt r).stratumCoarseCovariance S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- Exact left inverse equation for the generated physical stratum
covariance. -/
theorem stratumCoarseCovariance_comp_middle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM hspacing
      hLambdaPos hDelta hDeltaSymm hLambda r).comp
        (I.stratumCoarseCovarianceMiddle covariantLaplacian
          ha hL heta hc hDelta r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) := by
  exact (T.towerAt r).stratumCoarseCovariance_comp_middle
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- Exact right inverse equation for the generated physical stratum
covariance. -/
theorem stratumCoarseCovariance_middle_comp
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovarianceMiddle covariantLaplacian
      ha hL heta hc hDelta r).comp
        (I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM
          hspacing hLambdaPos hDelta hDeltaSymm hLambda r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) := by
  exact (T.towerAt r).stratumCoarseCovariance_middle_comp
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- Symmetry of the generated physical stratum covariance. -/
theorem stratumCoarseCovariance_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c Lambda : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hLambdaPos : 0 < Lambda)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (hLambda : ‖I.gaugePrecision covariantLaplacian a L eta‖ ≤ Lambda)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM hspacing
      hLambdaPos hDelta hDeltaSymm hLambda r).IsSymmetric := by
  exact (T.towerAt r).stratumCoarseCovariance_isSymmetric
    S r (I.levelEquiv r)
    (I.gaugePrecision covariantLaplacian a L eta)
    hspacing (I.towerAt_terminalSpacing_pos r hM hspacing)
    hc hLambdaPos
    (I.gaugePrecision_isCoercive covariantLaplacian ha hL heta hDelta)
    (I.gaugePrecision_isSymmetric covariantLaplacian a L eta hDeltaSymm)
    hLambda

/-- B5 with the upper constant generated from the retained physical
precision itself.  No caller-supplied `Lambda` or norm certificate remains. -/
theorem isCoerciveCLM_stratumCoarseCovarianceMiddle_physical
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (r : Fin (depth + 1)) :
    IsCoerciveCLM
      (I.stratumCoarseCovarianceMiddle covariantLaplacian
        ha hL heta hc hDelta r)
      ((I.precisionUpperBound covariantLaplacian a L eta) ^ 2)⁻¹ := by
  exact I.isCoerciveCLM_stratumCoarseCovarianceMiddle covariantLaplacian
    ha hL heta hc hM hspacing
    (I.precisionUpperBound_pos covariantLaplacian a L eta)
    hDelta hDeltaSymm
    (I.norm_gaugePrecision_le_precisionUpperBound
      covariantLaplacian a L eta hspacing) r

/-- The printed covariance with its precision upper bound generated
internally from the literal retained tower. -/
noncomputable def physicalStratumCoarseCovariance
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (r : Fin (depth + 1)) :
    S.StratumField (SUNLieCoord Nc) r →L[ℝ]
      S.StratumField (SUNLieCoord Nc) r :=
  I.stratumCoarseCovariance covariantLaplacian ha hL heta hc hM hspacing
    (I.precisionUpperBound_pos covariantLaplacian a L eta)
    hDelta hDeltaSymm
    (I.norm_gaugePrecision_le_precisionUpperBound
      covariantLaplacian a L eta hspacing) r

/-- Exact left inverse equation for the fully generated physical stratum
covariance. -/
theorem physicalStratumCoarseCovariance_comp_middle
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (r : Fin (depth + 1)) :
    (I.physicalStratumCoarseCovariance covariantLaplacian
      ha hL heta hc hM hspacing hDelta hDeltaSymm r).comp
        (I.stratumCoarseCovarianceMiddle covariantLaplacian
          ha hL heta hc hDelta r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) := by
  exact I.stratumCoarseCovariance_comp_middle covariantLaplacian
    ha hL heta hc hM hspacing
    (I.precisionUpperBound_pos covariantLaplacian a L eta)
    hDelta hDeltaSymm
    (I.norm_gaugePrecision_le_precisionUpperBound
      covariantLaplacian a L eta hspacing) r

/-- Exact right inverse equation for the fully generated physical stratum
covariance. -/
theorem physicalStratumCoarseCovariance_middle_comp
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (r : Fin (depth + 1)) :
    (I.stratumCoarseCovarianceMiddle covariantLaplacian
      ha hL heta hc hDelta r).comp
        (I.physicalStratumCoarseCovariance covariantLaplacian
          ha hL heta hc hM hspacing hDelta hDeltaSymm r) =
      ContinuousLinearMap.id ℝ (S.StratumField (SUNLieCoord Nc) r) := by
  exact I.stratumCoarseCovariance_middle_comp covariantLaplacian
    ha hL heta hc hM hspacing
    (I.precisionUpperBound_pos covariantLaplacian a L eta)
    hDelta hDeltaSymm
    (I.norm_gaugePrecision_le_precisionUpperBound
      covariantLaplacian a L eta hspacing) r

/-- Symmetry of the fully generated physical stratum covariance. -/
theorem physicalStratumCoarseCovariance_isSymmetric
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (covariantLaplacian :
      ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) →L[ℝ]
        ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    {a L eta c : ℝ}
    (ha : 0 < a) (hL : 0 < L) (heta : 0 < eta) (hc : 0 < c)
    (hM : 0 < (M : ℝ)) (hspacing : 0 < spacing)
    (hDelta : IsCoerciveCLM covariantLaplacian c)
    (hDeltaSymm : covariantLaplacian.IsSymmetric)
    (r : Fin (depth + 1)) :
    (I.physicalStratumCoarseCovariance covariantLaplacian
      ha hL heta hc hM hspacing hDelta hDeltaSymm r).IsSymmetric := by
  exact I.stratumCoarseCovariance_isSymmetric covariantLaplacian
    ha hL heta hc hM hspacing
    (I.precisionUpperBound_pos covariantLaplacian a L eta)
    hDelta hDeltaSymm
    (I.norm_gaugePrecision_le_precisionUpperBound
      covariantLaplacian a L eta hspacing) r

@[simp] theorem Qprime_apply
    (I : CMP99SourceRetainedPhysicalScaleIdentification T S)
    (r : Fin (depth + 1))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    I.Qprime r phi = I.levelEquiv r ((T.towerAt r).Qprime phi) := rfl

end CMP99SourceRetainedPhysicalScaleIdentification

end

end YangMills.RG
