/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116ComplexOuterNearLog

/-!
# Trace powers from symmetric multipliers

The real-symmetric correction generated by a complex quadratic form has trace
powers controlled by testing the original complex matrix against symmetric
ambient multipliers.  This is the exact bridge needed by the physical
coordinate-pivot estimate.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

/-- A symmetric-multiplier trace estimate for `A`, together with a norm bound
for its real-symmetric correction, gives the geometric trace-power estimate
consumed by the Mercator logarithm. -/
theorem norm_trace_complexified_neg_symmetricRealPart_pow_succ_le_of_multiplier
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ) {L q : ℝ}
    (hL : 0 ≤ L)
    (hD : ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
        Complex.ofRealHom‖ ≤ q)
    (htrace : ∀ P : Matrix ι ι ℂ, P.transpose = P →
      ‖Matrix.trace (A * P)‖ ≤ L * ‖P‖) :
    ∀ m : ℕ,
      ‖Matrix.trace
        (((-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
          Complex.ofRealHom) ^ (m + 1))‖ ≤
        L * q ^ m := by
  intro m
  let D : Matrix ι ι ℂ :=
    (-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
      Complex.ofRealHom
  have hDt : D.transpose = D := by
    ext i j
    change
      Complex.ofReal
          (-cmp116Eq214ComplexQuadraticSymmetricRealPart A j i) =
        Complex.ofReal
          (-cmp116Eq214ComplexQuadraticSymmetricRealPart A i j)
    have hsym :=
      congrFun
        (congrFun
          (cmp116Eq214ComplexQuadraticSymmetricRealPart_transpose A) i) j
    simpa using congrArg (fun t : ℝ => Complex.ofReal (-t)) hsym
  have hPt : (D ^ m).transpose = D ^ m := by
    rw [Matrix.transpose_pow, hDt]
  calc
    ‖Matrix.trace (D ^ (m + 1))‖ ≤
        ‖Matrix.trace (A * D ^ m)‖ :=
      norm_trace_complexified_neg_symmetricRealPart_pow_succ_le A m
    _ ≤ L * ‖D ^ m‖ := htrace (D ^ m) hPt
    _ ≤ L * ‖D‖ ^ m := by
      gcongr
      exact norm_pow_le D m
    _ ≤ L * q ^ m := by
      gcongr

end

end YangMills.RG
