/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.OrientedLatticePath
import YangMills.RG.ConcreteOrientedLatticePath
import YangMills.RG.BlockMaps
import YangMills.RG.BalabanCMP99SourceAdjointTransport

/-!
# Contour holonomy for the regional CMP99 average

A contour system assigns to every coarse/fine pair `(y,x)` a literal path on
the fine lattice from the canonical block basepoint of `y` to `x`.  Its
holonomy is therefore an ordered product of actual gauge links, rather than an
arbitrary group-valued kernel.  Endpoint gauge covariance and the induced
adjoint-transport intertwining law are derived from the path.

Honest scope: the contour system is data.  This file does not yet select the
specific recursive CMP99 contours `Gamma^(j)_{y,x}`, impose their length or
block-stay estimates, or construct the averaged backgrounds entering `Q'_j`.
It does prove cochain-level covariance of the complete one-scale regional
average.  No multiscale recursion or source-specific contour estimate is
inferred from that covariance theorem.
-/

namespace YangMills.RG

open YangMills YangMills.GaugeConfig

noncomputable section

/-- A family of literal fine-lattice contours from each coarse block
basepoint to every fine site. -/
abbrev CMP99ContourSystem
    (d M N' : ℕ) [NeZero M]
    (G : Type*) [Group G] [FiniteLatticeGeometry d (M * N') G] :=
  ∀ (y : FinBox d N') (x : FinBox d (M * N')),
    OrientedLatticePath (G := G) (blockBasepoint M N' y) x

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

/-- Ordered holonomy kernel generated by a literal contour system. -/
def cmp99ContourHolonomy
    (Gamma : CMP99ContourSystem d M N' (SUN Nc))
    (A : GaugeConfig d (M * N') (SUN Nc)) :
    FinBox d N' → FinBox d (M * N') → SUN Nc :=
  fun y x => (Gamma y x).holonomy A

omit [NeZero Nc] in
@[simp] theorem cmp99ContourHolonomy_apply
    (Gamma : CMP99ContourSystem d M N' (SUN Nc))
    (A : GaugeConfig d (M * N') (SUN Nc))
    (y : FinBox d N') (x : FinBox d (M * N')) :
    cmp99ContourHolonomy Gamma A y x = (Gamma y x).holonomy A := rfl

omit [NeZero Nc] in
/-- Endpoint gauge covariance of every contour holonomy. -/
theorem cmp99ContourHolonomy_gaugeAct
    (Gamma : CMP99ContourSystem d M N' (SUN Nc))
    (u : GaugeTransform d (M * N') (SUN Nc))
    (A : GaugeConfig d (M * N') (SUN Nc))
    (y : FinBox d N') (x : FinBox d (M * N')) :
    cmp99ContourHolonomy Gamma (GaugeConfig.gaugeAct u A) y x =
      u (blockBasepoint M N' y) * cmp99ContourHolonomy Gamma A y x *
        (u x)⁻¹ :=
  (Gamma y x).holonomy_gaugeAct u A

/-- The physical adjoint transport intertwines the gauge action at the fine
endpoint with the gauge action at the coarse block basepoint. -/
theorem cmp99AdjointBlockTransport_contour_gaugeAct
    (rho : SUNAdjointModel Nc)
    (Gamma : CMP99ContourSystem d M N' (SUN Nc))
    (u : GaugeTransform d (M * N') (SUN Nc))
    (A : GaugeConfig d (M * N') (SUN Nc))
    (y : FinBox d N') (x : FinBox d (M * N'))
    (X : SUNLieCoord Nc) :
    cmp99AdjointBlockTransport rho
        (cmp99ContourHolonomy Gamma (GaugeConfig.gaugeAct u A)) y x
        (rho.adCLM (u x) X) =
      rho.adCLM (u (blockBasepoint M N' y))
        (cmp99AdjointBlockTransport rho
          (cmp99ContourHolonomy Gamma A) y x X) := by
  simp only [cmp99AdjointBlockTransport_apply,
    cmp99ContourHolonomy_gaugeAct]
  rw [rho.ad_mul, rho.ad_mul]
  simp only [ContinuousLinearMap.comp_apply, rho.ad_inv_apply_ad]

/-- Pointwise gauge action on a regional fine zero-cochain. -/
def cmp99RegionalFineGaugeAct
    (Omega : ActiveGaugeRegion d (M * N'))
    (rho : SUNAdjointModel Nc)
    (u : GaugeTransform d (M * N') (SUN Nc))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) :=
  WithLp.toLp 2 fun x => rho.adCLM (u x.1) (phi x)

omit [NeZero d] in
@[simp] theorem cmp99RegionalFineGaugeAct_apply
    (Omega : ActiveGaugeRegion d (M * N'))
    (rho : SUNAdjointModel Nc)
    (u : GaugeTransform d (M * N') (SUN Nc))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc))
    (x : ActiveGaugeRegion.Site Omega) :
    cmp99RegionalFineGaugeAct Omega rho u phi x =
      rho.adCLM (u x.1) (phi x) := rfl

/-- The induced gauge action on the active coarse field uses the gauge
function at the canonical fine basepoint of each coarse block. -/
def cmp99RegionalCoarseGaugeAct
    (Omega : ActiveGaugeRegion d (M * N'))
    (rho : SUNAdjointModel Nc)
    (u : GaugeTransform d (M * N') (SUN Nc))
    (eta : ActiveGaugeZeroCochain
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
      (SUNLieCoord Nc)) :
    ActiveGaugeZeroCochain
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
      (SUNLieCoord Nc) :=
  WithLp.toLp 2 fun y =>
    rho.adCLM (u (blockBasepoint M N' y.1)) (eta y)

omit [NeZero d] in
@[simp] theorem cmp99RegionalCoarseGaugeAct_apply
    (Omega : ActiveGaugeRegion d (M * N'))
    (rho : SUNAdjointModel Nc)
    (u : GaugeTransform d (M * N') (SUN Nc))
    (eta : ActiveGaugeZeroCochain
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
      (SUNLieCoord Nc))
    (y : ActiveGaugeRegion.Site
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)) :
    cmp99RegionalCoarseGaugeAct Omega rho u eta y =
      rho.adCLM (u (blockBasepoint M N' y.1)) (eta y) := rfl

/-- Gauge covariance of the complete one-scale regional block average.  The
fine endpoint action cancels inside every contour transport and the common
coarse endpoint action passes through the finite block sum. -/
theorem cmp99AdjointBlockAverageCLM_contour_gaugeAct
    (Omega : ActiveGaugeRegion d (M * N')) (w : ℝ)
    (rho : SUNAdjointModel Nc)
    (Gamma : CMP99ContourSystem d M N' (SUN Nc))
    (u : GaugeTransform d (M * N') (SUN Nc))
    (A : GaugeConfig d (M * N') (SUN Nc))
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    cmp99AdjointBlockAverageCLM Omega w rho
        (cmp99ContourHolonomy Gamma (GaugeConfig.gaugeAct u A))
        (cmp99RegionalFineGaugeAct Omega rho u phi) =
      cmp99RegionalCoarseGaugeAct Omega rho u
        (cmp99AdjointBlockAverageCLM Omega w rho
          (cmp99ContourHolonomy Gamma A) phi) := by
  apply PiLp.ext
  intro y
  change w • ∑ x : {x : FinBox d (M * N') // x ∈ blockOf M N' y.1},
      cmp99AdjointBlockTransport rho
        (cmp99ContourHolonomy Gamma (GaugeConfig.gaugeAct u A)) y.1 x.1
        (rho.adCLM (u x.1)
          (phi (cmp99ActiveFineSiteOfBlock Omega y x))) =
    rho.adCLM (u (blockBasepoint M N' y.1))
      (w • ∑ x : {x : FinBox d (M * N') // x ∈ blockOf M N' y.1},
        cmp99AdjointBlockTransport rho
          (cmp99ContourHolonomy Gamma A) y.1 x.1
          (phi (cmp99ActiveFineSiteOfBlock Omega y x)))
  rw [map_smul, map_sum]
  congr 1
  apply Finset.sum_congr rfl
  intro x _hx
  exact cmp99AdjointBlockTransport_contour_gaugeAct
    rho Gamma u A y.1 x.1 (phi (cmp99ActiveFineSiteOfBlock Omega y x))

/-- Non-vacuity witness: the concrete periodic lattice admits a contour system
from every coarse block basepoint to every fine site.  The selected paths are
not claimed to be the recursive CMP99 contours. -/
noncomputable def concreteCMP99ContourSystem :
    CMP99ContourSystem d M N' (SUN Nc) :=
  fun y x => concreteOrientedLatticePath (G := SUN Nc)
    (blockBasepoint M N' y) x

end

end YangMills.RG
