import YangMills.RG.BalabanCMP99SourceGeneratedSectionCRightFactorNorm

open YangMills.RG

#print axioms cmp99SourceGeneratedWeightedAdjointNormBound
#print axioms cmp99SourceGeneratedPhysicalCoarseRightFactorNormBound
#print axioms cmp99SourceGeneratedPhysicalCoarseMiddleDefectNormBound
#print axioms cmp99SourceGeneratedPhysicalCoarseCovarianceNormBound
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedWeightedAdjoint_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseCovarianceMiddle_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseRightFactor_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseMiddleTransitionDefect_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseRightFactorCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseMiddleTransitionDefectCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseCovarianceCoordinates_le
