import YangMills.RG.BalabanCMP99SourceGeneratedArbitraryCoarseMiddleTransition

#print axioms YangMills.RG.cmp99SourceGeneratedNestedCoarseMiddleDefect
#print axioms YangMills.RG.cmp99SourceGeneratedNestedCoarseMiddleGreenTransport
#print axioms YangMills.RG.cmp99SourceGeneratedNestedPhysicalGreenTransition
#print axioms YangMills.RG.cmp99SourceGeneratedNestedPhysicalPrecisionDefect_eq_laplacianDefect
#print axioms YangMills.RG.cmp99SourceGeneratedNestedPhysicalGreen_transition_resolvent
#print axioms YangMills.RG.cmp99SourceGeneratedPhysicalCoarseCovarianceMiddle_eq_Qprime_green_sq_arbitrary
#print axioms YangMills.RG.cmp99SourceGeneratedNestedCoarseMiddleDefect_eq_greenMismatch
