import YangMills.RG.BalabanCMP99SourceGeneratedGreenTransitionDecay

open YangMills.RG

#print axioms cmp99NestedActiveRegionRestriction_single_of_mem
#print axioms cmp99NestedActiveRegionRestriction_single_of_not_mem
#print axioms cmp99NestedLaplacianPrecisionDefect_finiteRange_one
#print axioms cmp99NestedLaplacianPrecisionDefect_kernelBound
#print axioms activeGaugeRegion_finBoxDist_exp_sum_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalPrecisionDefect_finiteRange_one
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalPrecisionDefect_kernelBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalPrecisionDefect_exponentialKernelBound
#print axioms CMP99SourceDependentOmegaGeometry.cmp99SourceGeneratedPhysicalGreenTransitionDecayAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalGreenTransition_exponentialKernelBound
