import YangMills.RG.BalabanCMP99RectangularMinimizerAnalyticFTC

#print axioms YangMills.RG.isOpen_cmp99ComplexBackgroundMinimizerNonsingularSet
#print axioms YangMills.RG.differentiableOn_cmp99ComplexBackgroundMinimizerCurveEntry
#print axioms YangMills.RG.continuousOn_cmp99ComplexBackgroundMinimizerCurveDerivativeEntry
#print axioms YangMills.RG.continuousOn_cmp99PhysicalRectangularOfComplexMatrix_of_entrywise
#print axioms YangMills.RG.continuousOn_cmp99SourcePi4BackgroundMinimizerDerivative_compOfReal_of_source
#print axioms YangMills.RG.integral_cmp99SourcePi4BackgroundMinimizerDerivative_eq_sub_of_source
#print axioms YangMills.RG.integral_cmp99SourcePi4RealBackgroundMinimizerOperatorDerivative_eq_sub_of_source
