import YangMills.RG.BalabanCMP102Eq80SourcePi4CarrierAnchoredPotentialDerivative

#print axioms YangMills.RG.cmp116SourcePi4FullRealWeakenedCovarianceMixedDerivative_eq_sum_pi4CarrierAnchoredDomainOperator
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_add
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_zero
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_sum
#print axioms YangMills.RG.cmp102Eq80PropagatorDirectionalDerivative_fullRealMixed_eq_sum_pi4CarrierAnchoredDomains
