import YangMills.RG.BalabanCMP116WeakenedRandomWalkSeries

/-!
# CMP99 equations (3.107)--(3.108): source-faithful generalized walks

Balaban's generalized random walk has a distinguished initial pair `(0, X₀)`
followed by an ordered list `((α₁, X₁), ..., (αₙ, Xₙ))`, with consecutive
localization domains intersecting.  The corresponding operator term is the
noncommutative product

`R₀(X₀) R_{α₁}(X₁) ... R_{αₙ}(Xₙ)`.

CMP116 weakens this term by every coarse cube meeting the union of the
localization domains (with the source-specific thickening absorbed in the map
`domainActive`).  A single domain may activate several cubes, so the active
carrier is a union, not the image of one cube per step.

This module closes the structural and bounded-branching part of the source
dictionary:

* the distinguished head, labelled tail, overlap chain, and ordered product;
* the exact active union and the bound `card active ≤ B * (length + 1)`;
* the finite family of admissible tails of a fixed length generated by a
  finite successor family;
* the uniform count `card tails ≤ K ^ n` from a branching bound `K`.

Honest scope: the concrete simple localization domains, the complete successor
family from Sect. C of CMP99, the ordered operators `R₀`, `R_α`, and the
geometric kernel estimate (3.108) are not constructed here.  In particular,
the analytic decay is not stored as a field of the walk structure.
-/

namespace YangMills.RG

universe u v w z

/-- One labelled continuation `(α, X)` of a CMP99 generalized random walk. -/
structure CMP99WalkStep (Label : Type u) (Domain : Type v) where
  label : Label
  domain : Domain
  deriving DecidableEq

/-- The raw source shape `((0,X₀),(α₁,X₁),...,(αₙ,Xₙ))`.  Admissibility is a
separate predicate so list induction does not carry proof fields. -/
structure CMP99GeneralizedWalk (Label : Type u) (Domain : Type v) where
  head : Domain
  tail : List (CMP99WalkStep Label Domain)
  deriving DecidableEq

namespace CMP99GeneralizedWalk

variable {Label : Type u} {Domain : Type v} {Cube : Type w} {E : Type z}

/-- The source convention `|ω| = n`: the distinguished head is not counted. -/
def length (walk : CMP99GeneralizedWalk Label Domain) : ℕ :=
  walk.tail.length

/-- The ordered list `X₀, X₁, ..., Xₙ` of localization domains. -/
def domains (walk : CMP99GeneralizedWalk Label Domain) : List Domain :=
  walk.head :: walk.tail.map CMP99WalkStep.domain

@[simp]
theorem length_domains (walk : CMP99GeneralizedWalk Label Domain) :
    walk.domains.length = walk.length + 1 := by
  simp [domains, length]

/-- Consecutive source domains intersect (or satisfy a supplied replacement
relation). -/
def IsAdmissible (meets : Domain → Domain → Prop)
    (walk : CMP99GeneralizedWalk Label Domain) : Prop :=
  (walk.domains).IsChain meets

/-- The literal ordered, generally noncommutative product in (3.107). -/
def term [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E)
    (walk : CMP99GeneralizedWalk Label Domain) : E :=
  (R0 walk.head :: walk.tail.map (fun step => R step.label step.domain)).prod

@[simp]
theorem term_nil [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E) (X0 : Domain) :
    term R0 R ⟨X0, []⟩ = R0 X0 := by
  simp [term]

@[simp]
theorem term_cons [Monoid E]
    (R0 : Domain → E) (R : Label → Domain → E)
    (X0 : Domain) (step : CMP99WalkStep Label Domain)
    (tail : List (CMP99WalkStep Label Domain)) :
    term R0 R ⟨X0, step :: tail⟩ =
      R0 X0 * (R step.label step.domain ::
        tail.map (fun next => R next.label next.domain)).prod := by
  simp [term]

section Active

variable [DecidableEq Cube]

/-- Union of all weakening cubes meeting the source localization domains. -/
def active (domainActive : Domain → Finset Cube)
    (walk : CMP99GeneralizedWalk Label Domain) : Finset Cube :=
  (walk.domains.map domainActive).foldr (· ∪ ·) ∅

private theorem card_foldr_union_le_mul_length
    (domainActive : Domain → Finset Cube) (B : ℕ)
    (hB : ∀ X, (domainActive X).card ≤ B) :
    ∀ domains : List Domain,
      ((domains.map domainActive).foldr (· ∪ ·) ∅).card ≤
        B * domains.length := by
  intro domains
  induction domains with
  | nil => simp
  | cons X rest ih =>
      calc
        ((domainActive X :: rest.map domainActive).foldr (· ∪ ·) ∅).card ≤
            (domainActive X).card +
              ((rest.map domainActive).foldr (· ∪ ·) ∅).card :=
          Finset.card_union_le _ _
        _ ≤ B + B * rest.length := Nat.add_le_add (hB X) ih
        _ = B * (X :: rest).length := by
          simp [Nat.mul_add, Nat.add_comm]

/-- If every source domain activates at most `B` weakening cubes, a walk of
source length `n` activates at most `B(n+1)` cubes. -/
theorem card_active_le_mul_length_add_one
    (domainActive : Domain → Finset Cube) (B : ℕ)
    (hB : ∀ X, (domainActive X).card ≤ B)
    (walk : CMP99GeneralizedWalk Label Domain) :
    (walk.active domainActive).card ≤ B * (walk.length + 1) := by
  simpa [active, length_domains] using
    card_foldr_union_le_mul_length domainActive B hB walk.domains

end Active

end CMP99GeneralizedWalk

section BoundedBranching

variable {Label : Type u} {Domain : Type v}
variable [DecidableEq Label] [DecidableEq Domain]

/-- All admissible labelled tails of exactly `n` steps starting at `X`.
The finite family `successors X` is the explicit local branching data. -/
def cmp99AdmissibleTails
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (X : Domain) : ℕ → Finset (List (CMP99WalkStep Label Domain))
  | 0 => {[]}
  | n + 1 =>
      (successors X).biUnion fun step =>
        (cmp99AdmissibleTails successors step.domain n).image (step :: ·)

/-- Membership fixes the source length exactly. -/
theorem length_eq_of_mem_cmp99AdmissibleTails
    (successors : Domain → Finset (CMP99WalkStep Label Domain)) :
    ∀ {n X tail}, tail ∈ cmp99AdmissibleTails successors X n →
      tail.length = n := by
  intro n
  induction n with
  | zero =>
      intro X tail htail
      simpa [cmp99AdmissibleTails] using congrArg List.length
        (Finset.mem_singleton.mp htail)
  | succ n ih =>
      intro X tail htail
      simp only [cmp99AdmissibleTails, Finset.mem_biUnion,
        Finset.mem_image] at htail
      obtain ⟨step, _hstep, rest, hrest, rfl⟩ := htail
      simp [ih hrest]

/-- The generated tails satisfy the consecutive-overlap predicate whenever
each declared successor overlaps its source domain. -/
theorem chain_of_mem_cmp99AdmissibleTails
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (meets : Domain → Domain → Prop)
    (hsucc : ∀ X step, step ∈ successors X → meets X step.domain) :
    ∀ {n X tail}, tail ∈ cmp99AdmissibleTails successors X n →
      (X :: tail.map CMP99WalkStep.domain).IsChain meets := by
  intro n
  induction n with
  | zero =>
      intro X tail htail
      have hnil : tail = [] := Finset.mem_singleton.mp
        (by simpa [cmp99AdmissibleTails] using htail)
      subst hnil
      simp
  | succ n ih =>
      intro X tail htail
      simp only [cmp99AdmissibleTails, Finset.mem_biUnion,
        Finset.mem_image] at htail
      obtain ⟨step, hstep, rest, hrest, rfl⟩ := htail
      exact List.IsChain.cons_cons (hsucc X step hstep) (ih hrest)

/-- A uniform branching bound gives the source-faithful `K^n` walk count,
independent of the total number of localization domains in the volume. -/
theorem card_cmp99AdmissibleTails_le_pow
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (K : ℕ) (hK : ∀ X, (successors X).card ≤ K) :
    ∀ (n : ℕ) (X : Domain),
      (cmp99AdmissibleTails successors X n).card ≤ K ^ n := by
  intro n
  induction n with
  | zero =>
      intro X
      simp [cmp99AdmissibleTails]
  | succ n ih =>
      intro X
      calc
        (cmp99AdmissibleTails successors X (n + 1)).card =
            ((successors X).biUnion fun step =>
              (cmp99AdmissibleTails successors step.domain n).image
                (step :: ·)).card := rfl
        _ ≤ ∑ step ∈ successors X,
              ((cmp99AdmissibleTails successors step.domain n).image
                (step :: ·)).card := Finset.card_biUnion_le
        _ ≤ ∑ _step ∈ successors X, K ^ n := by
          gcongr with step hstep
          rw [Finset.card_image_of_injective]
          · exact ih step.domain
          · intro a b hab
            exact (List.cons.inj hab).2
        _ = (successors X).card * K ^ n := by simp
        _ ≤ K * K ^ n := Nat.mul_le_mul_right (K ^ n) (hK X)
        _ = K ^ (n + 1) := by simp [pow_succ, Nat.mul_comm]

/-- The countable anchored walk index generated by a finite successor family. -/
abbrev CMP99AnchoredWalk
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (X0 : Domain) :=
  Σ n : ℕ, ↥(cmp99AdmissibleTails successors X0 n)

/-- Forget the generation certificate and recover the literal source walk. -/
def CMP99AnchoredWalk.toGeneralizedWalk
    {successors : Domain → Finset (CMP99WalkStep Label Domain)}
    {X0 : Domain} (walk : CMP99AnchoredWalk successors X0) :
    CMP99GeneralizedWalk Label Domain :=
  ⟨X0, walk.2.1⟩

@[simp]
theorem CMP99AnchoredWalk.toGeneralizedWalk_length
    {successors : Domain → Finset (CMP99WalkStep Label Domain)}
    {X0 : Domain} (walk : CMP99AnchoredWalk successors X0) :
    walk.toGeneralizedWalk.length = walk.1 := by
  exact length_eq_of_mem_cmp99AdmissibleTails successors walk.2.2

end BoundedBranching

end YangMills.RG
