-- Promotion import:
import YangMills.RG.BalabanCMP89CenteredPeriodicL1ResidueSum


-- SEALED AXIOM SURFACE: intended axiom surface for Step 8b.23/Unit F.19.

#print axioms YangMills.RG.cmp89CenteredPeriodicOneDimensionalExpWeight
#print axioms YangMills.RG.cmp89CenteredPeriodicOneDimensionalExpWeight_nonneg
#print axioms YangMills.RG.cmp89CenteredPeriodicOneDimensionalExpWeight_neg_neg
#print axioms YangMills.RG.cmp89CenteredPeriodicOneDimensionalExpWeight_nat_eq
#print axioms YangMills.RG.cmp89CenteredPeriodicOneDimensionalExpWeight_neg_add_one_le
#print axioms YangMills.RG.summable_cmp89CenteredPeriodicOneDimensionalExpWeight_of_nonneg
#print axioms YangMills.RG.summable_cmp89CenteredPeriodicOneDimensionalExpWeight
#print axioms YangMills.RG.tsum_cmp89CenteredPeriodicOneDimensionalExpWeight_le_of_nonneg
#print axioms YangMills.RG.tsum_cmp89CenteredPeriodicOneDimensionalExpWeight_le
#print axioms YangMills.RG.cmp89CenteredPeriodicL1ResidueWeight
#print axioms YangMills.RG.cmp89CenteredPeriodicL1ResidueWeight_eq_signedLatticeWeight
#print axioms YangMills.RG.summable_pi_int_prod_nonneg
#print axioms YangMills.RG.tsum_pi_int_prod_nonneg
#print axioms YangMills.RG.summable_cmp89CenteredPeriodicL1ResidueWeight
#print axioms YangMills.RG.tsum_cmp89CenteredPeriodicL1ResidueWeight_le
#print axioms YangMills.RG.tsum_cmp89CenteredPeriodicL1ResidueWeight_physical_le
#print axioms YangMills.RG.tsum_cmp89CenteredPeriodicL1ResidueWeight_physical_uniform_le
