import YangMills.RG.BalabanCMP89SourceSeparatedAmbientPrefixPrecision

/-!
# Axiom audit

-/

#print axioms YangMills.RG.cmp85LastPositivePrefix_succ_sourceIndex
#print axioms YangMills.RG.cmp89SourceSeparatedFinePrefixPrecision
#print axioms YangMills.RG.cmp89SourceSeparatedPrefixCoercivity
#print axioms YangMills.RG.cmp89SourceSeparatedPrefixCoercivity_pos
#print axioms YangMills.RG.cmp89SourceSeparatedAmbientPrefixPrecision
#print axioms YangMills.RG.isCoerciveCLM_cmp89SourceSeparatedAmbientPrefixPrecision
#print axioms YangMills.RG.cmp89SourceSeparatedAmbientPrefixPrecision_comp_green
#print axioms YangMills.RG.cmp89SourceSeparatedAmbientPrefixGreen_comp_precision
