import YangMills.RG.BalabanCMP116Eq221PhysicalInteractionExponent

#print axioms YangMills.RG.PhysicalGaugeCMP116Dictionary.inner_physicalBondProjection_right_eq_left
#print axioms YangMills.RG.PhysicalGaugeCMP116Dictionary.inner_cmp116Eq221PhysicalR3Source
#print axioms YangMills.RG.PhysicalGaugeCMP116Dictionary.cmp116Eq221PhysicalRealInteractionExponent_eq_split
#print axioms YangMills.RG.CMP116Eq216PhysicalKernelCertificate.physicalRealInteractionExponent_le_coordinateAlpha5_physicalCutoff_geometric
