import YangMills.RG.BalabanCMP99Eq337ComplexClosedRadiusPhysicalBridge

#print axioms YangMills.RG.cmp99ComplexClosedRadiusDeviation_eq_eq337Uniform
#print axioms YangMills.RG.cmp99ComplexClosedRadiusLog_eq_ubarLogRadius
#print axioms YangMills.RG.cmp99ComplexClosedRadiusExp_eq_ubarExpRadius
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNextLink_eq_sourceNextLinkRadius
#print axioms YangMills.RG.cmp99ComplexClosedRadiusNext_eq_sourceNextOrientedLinkRadius
#print axioms YangMills.RG.cmp99ComplexClosedRadiusPhysicalNoWindingBudget
#print axioms YangMills.RG.cmp99ComplexClosedRadiusAt_succ_eq_sourceNextOrientedLinkRadius
