import YangMills.RG.BalabanCMP99Eq360C6dSourceSeparatedAmbientGreenZeroDepthActions

-- PRE-VALIDATION: source present; its `.olean` is not yet materialized and the result is not compiler-verified.

#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen_zero_leftDerivative_blockLocalizedSupBound
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen_zero_rightAdjoint_blockLocalizedSupBound
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen_zero_laplacian_blockLocalizedSupBound
