/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116ComplexOuterNearLog

/-!
# Trace powers from symmetric multipliers

The real-symmetric correction generated by a complex quadratic form has trace
powers controlled by testing the original complex matrix against symmetric
ambient multipliers.  This is the exact bridge needed by the physical
coordinate-pivot estimate.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

/-- A symmetric-multiplier trace estimate for `A`, together with a norm bound
for its real-symmetric correction, gives the geometric trace-power estimate
consumed by the Mercator logarithm. -/
theorem norm_trace_complexified_neg_symmetricRealPart_pow_succ_le_of_multiplier
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ) {L q : ℝ}
    (hL : 0 ≤ L)
    (hD : ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
        Complex.ofRealHom‖ ≤ q)
    (htrace : ∀ P : Matrix ι ι ℂ, P.transpose = P →
      ‖Matrix.trace (A * P)‖ ≤ L * ‖P‖) :
    ∀ m : ℕ,
      ‖Matrix.trace
        (((-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
          Complex.ofRealHom) ^ (m + 1))‖ ≤
        L * q ^ m := by
  intro m
  let D : Matrix ι ι ℂ :=
    (-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
      Complex.ofRealHom
  have hDt : D.transpose = D := by
    ext i j
    change
      Complex.ofReal
          (-cmp116Eq214ComplexQuadraticSymmetricRealPart A j i) =
        Complex.ofReal
          (-cmp116Eq214ComplexQuadraticSymmetricRealPart A i j)
    have hsym :=
      congrFun
        (congrFun
          (cmp116Eq214ComplexQuadraticSymmetricRealPart_transpose A) i) j
    simpa using congrArg (fun t : ℝ => Complex.ofReal (-t)) hsym
  have hPt : (D ^ m).transpose = D ^ m := by
    rw [Matrix.transpose_pow, hDt]
  calc
    ‖Matrix.trace (D ^ (m + 1))‖ ≤
        ‖Matrix.trace (A * D ^ m)‖ :=
      norm_trace_complexified_neg_symmetricRealPart_pow_succ_le A m
    _ ≤ L * ‖D ^ m‖ := htrace (D ^ m) hPt
    _ ≤ L * ‖D‖ ^ m := by
      gcongr
      exact norm_pow_le D m
    _ ≤ L * q ^ m := by
      gcongr

/-- The exact global outer Gaussian is bounded directly from a
symmetric-multiplier trace estimate for the original complex quadratic
matrix.  No pointwise localization of the outer field is assumed. -/
theorem integral_exp_re_complexQuadratic_standardGaussianPi_le_of_multiplier
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ)
    (hpos :
      (1 - cmp116Eq214ComplexQuadraticSymmetricRealPart A).PosDef)
    (hsmall :
      ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
        Complex.ofRealHom‖ < 1)
    {L : ℝ} (hL : 0 ≤ L)
    (htrace : ∀ P : Matrix ι ι ℂ, P.transpose = P →
      ‖Matrix.trace (A * P)‖ ≤ L * ‖P‖) :
    (∫ x : ι → ℝ,
        Real.exp ((cmp116Eq214ComplexQuadratic A x).re)
        ∂standardGaussianPi ι) ≤
      Real.exp
        ((L /
          (1 -
            ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
              Complex.ofRealHom‖)) / 2) := by
  let q : ℝ :=
    ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
      Complex.ofRealHom‖
  apply
    integral_exp_re_complexQuadratic_standardGaussianPi_le_of_tracePowers
      A hpos hsmall (L := L) (q := q) (norm_nonneg _) (by simpa [q] using hsmall)
  exact
    norm_trace_complexified_neg_symmetricRealPart_pow_succ_le_of_multiplier
      A hL (by simp [q]) htrace

end

end YangMills.RG
