import YangMills.RG.BalabanCMP99SourceSeparatedLargeBlockPartition

/-!
# Audit: source-separated CMP99 large-block partition
-/

#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockSide
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockCutoffScale
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockSide_self
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockCutoffScale_self
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockCutoffScale_pos
#print axioms YangMills.RG.cmp99RegionalLatticeSize_sourceSeparatedLargeBlockCarrier
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockCoordinate
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockCutoff
#print axioms YangMills.RG.sum_cmp99SourceSeparatedLargeBlockCutoff_sq
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockSquarePartition
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockCutoffScale_mul_Q
#print axioms YangMills.RG.cmp99SourceGenerated_precisionRange_div_separatedLargeBlockCutoffScale
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockSlope_mul_precisionRange
#print axioms YangMills.RG.norm_cmp99SourceSeparatedLargeBlockSquarePartition_value_sub_le
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockActiveCells
#print axioms YangMills.RG.cmp99SourceSeparatedLargeBlockActiveCells_subset
#print axioms YangMills.RG.card_cmp99SourceSeparatedLargeBlockActiveCells_le_sixteen
