import YangMills.RG.BalabanCMP116Eq226SourceLedger

#print axioms YangMills.RG.cmp116Eq226SourceTermWeight_eq_stageLedger
#print axioms YangMills.RG.cmp116Eq226DomainFactor_eq_two_mul_tauInverse
#print axioms YangMills.RG.cmp116Eq218TauAbsSolved_mul_eq226DomainFactor
#print axioms YangMills.RG.cmp116Eq218TauRadiusProduct_mul_eq226DomainProduct
#print axioms YangMills.RG.cmp116Eq214CauchyRate_le_mul_eq226DomainProduct
#print axioms YangMills.RG.CMP116Eq214AnalyticData.norm_term_le_deltaCauchyRate_mul_eq226DomainProduct
#print axioms YangMills.RG.cmp116Eq226PBondFactor_eq_exp_ten_mul_sourceRate
#print axioms YangMills.RG.cmp116Eq222PenaltyFactor_eq_eq226PBondFactor
#print axioms YangMills.RG.cmp116Eq222ResidualPenaltyFactor_eq_mul_eq226PBondFactor
#print axioms YangMills.RG.cmp116Eq226PBondFactor_eq_eq231CardinalityFactor_pow_five
#print axioms YangMills.RG.cmp116Eq237FixedZ0PrimeWeight_eq_eq226Factors
#print axioms YangMills.RG.cmp116Eq226SourceTermWeight_le_targetLedger_of_factorwise
#print axioms YangMills.RG.cmp116Eq226PBondFactor_le_of_penalty
#print axioms YangMills.RG.cmp116Eq226GapFactor_le_of_penalty
#print axioms YangMills.RG.cmp116Eq226GaussianVolumeFactor_le_of_exponent
#print axioms YangMills.RG.cmp116Eq226SourceTermWeight_le_targetLedger_of_scalarDictionaries
#print axioms YangMills.RG.cmp116Eq226DomainFactor_nonneg
#print axioms YangMills.RG.cmp116Eq226SourceTermWeight_nonneg
