import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothBasicAdjointDecay

#print axioms YangMills.RG.cmp99SourceGeneratedWeightedAdjointWeightedRowAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedPhysicalWeightedAdjoint_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothPhysicalBasicAdjointFactor
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.transportedGeneratedCMP95SourceCenteredSmoothBasicAdjointFactor
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothPhysicalBasicAdjointFactor_eq_transported
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSmoothPhysicalBasicAdjointFactor_weightedRow
