import YangMills.RG.BalabanCMP99SourceFlatGeneratedQprimeDirectOwnerKernel

#print axioms YangMills.RG.cmp99SourceIteratedLift_terminalOwner_eq_iff_generatedTerminalBlockSite_eq
#print axioms YangMills.RG.cmp99SourceIteratedLift_flatExplicitWeightedMass_single_apply
#print axioms YangMills.RG.cmp99SourceIteratedLift_flatExplicitCountingMass_single_apply
