import YangMills.RG.BalabanCMP99SourceTransportedAverageExactReadCarrier

/-!


Axiom queue for the exact one-step transported-average read carrier.
-/

#print axioms YangMills.RG.cmp99SourceTransportedAverageFineReadBonds
#print axioms YangMills.RG.physicalBondOfEdge_mem_cmp99SourceTransportedAverageFineReadBonds
#print axioms YangMills.RG.cmp99BlockContainedContourHolonomy_eq_of_eqOn_averageReadBonds
#print axioms YangMills.RG.cmp99SourceWeightedPhysicalTransport_apply_eq_of_eqOn_readBonds
#print axioms YangMills.RG.cmp99SourceTransportedBlockAverageCLM_eq_of_eqOn_readBonds
