import YangMills.RG.BalabanCMP99Eq351ExponentialAdjointRemainderBound

#print axioms YangMills.RG.cmp99Eq351_expTailMajorant_le_four_thirds_sq
#print axioms YangMills.RG.cmp99Eq351_norm_exp_neg_le_four_thirds
#print axioms YangMills.RG.norm_cmp99Eq351ExponentialAdjointRemainderCLM_apply_le
