import YangMills.RG.BalabanCMP99SourceEq395ThirdBoundary

#print axioms YangMills.RG.cmp99Eq395SampledCutoff_value_eq_one_of_mem_baseCell
#print axioms YangMills.RG.cmp99Eq395SampledCutoff_value_eq_piCharacteristic
#print axioms YangMills.RG.cmp99Eq395PhysicalSmoothMultiplier_sq_eq_self
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedRAtom_eq_cutoff_sub_global_head
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalThirdLeft_single_apply_eq_zero_of_same_side
