import YangMills.RG.BalabanCMP102Eq80SourcePi4PhysicalSecondMixedLocalization

#print axioms YangMills.RG.cmp102Eq80SourcePi4PhysicalSecondMixedDomainCoefficient_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4PhysicalSecondMixedDomainCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp102Eq80SourcePi4SecondMixedDerivativeValue_eq_sum_physicalDomains
