import YangMills.RG.BalabanCMP116Eq226SourceLedger

#print axioms YangMills.RG.cmp116Eq226SourceTermWeight_eq_stageLedger
#print axioms YangMills.RG.cmp116Eq226DomainFactor_nonneg
#print axioms YangMills.RG.cmp116Eq226SourceTermWeight_nonneg
