import YangMills.RG.BalabanCMP102AmbientFourContourUniformBudget

#print axioms YangMills.RG.one_le_cmp102AmbientEdgeValueBudget
#print axioms YangMills.RG.cmp98AmbientWilsonLineValueBudget_monotone
#print axioms YangMills.RG.cmp98AmbientWilsonLineValueLipschitzBudget_monotone
#print axioms YangMills.RG.cmp98AmbientWilsonLineDerivativeBudget_monotone
#print axioms YangMills.RG.cmp98AmbientWilsonLineDerivativeLipschitzBudget_monotone
#print axioms YangMills.RG.norm_cmp98UbarAmbientDeviationMatrix_le_sourceLengthBudget
#print axioms YangMills.RG.norm_fderiv_cmp98UbarAmbientDeviationMatrix_le_sourceLengthBudget
#print axioms YangMills.RG.norm_cmp98UbarAmbientDeviationMatrix_sub_le_sourceLengthBudget
#print axioms YangMills.RG.norm_fderiv_cmp98UbarAmbientDeviationMatrix_sub_le_sourceLengthBudget
