import YangMills.RG.BalabanCMP99Eq360ComplexRegionalLaplacianRealSlice

#print axioms YangMills.RG.cmp99Eq360ComplexDirichletExtend_realSlice
#print axioms YangMills.RG.cmp99Eq360ComplexCovariantDifference_realSlice
#print axioms YangMills.RG.cmp99Eq360ComplexRegionalLaplacian_realSlice
