import YangMills.RG.BalabanCMP99SourceGeneratedSectionCHeadIdentification

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorFactorCoordinates_eq_head
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_eq_head
