import YangMills.RG.BalabanCMP99SourceRegionalCoarseCovarianceDecay

open YangMills.RG

#print axioms Real.exp_sub_one_le_mul_exp_of_nonneg
#print axioms cmp99_exponentialTiltWeight_le
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceDecayRate
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseMiddleDecayAmplitude_nonneg
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceDecayRate_pos
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceDecayRate_budget
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovariance_exponentialKernelBound
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceTransitionDecayRate
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceTransitionDecayAmplitude
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovariance_transition_exponentialKernelBound
