import YangMills.RG.BalabanCMP102Eq80CouplingScaledSecondJet

#print axioms YangMills.RG.iteratedFDeriv_two_cmp102Eq80CouplingScaledPotential
#print axioms YangMills.RG.cmp116FDerivHessian_cmp102Eq80CouplingScaledPotential
#print axioms YangMills.RG.norm_iteratedFDeriv_two_cmp102Eq80CouplingScaledPotential_le
#print axioms YangMills.RG.abs_cmp116FDerivHessian_cmp102Eq80CouplingScaledPotential_le_of_source
#print axioms YangMills.RG.abs_cmp116FDerivHessian_cmp102Eq80CouplingScaledPotential_le_explicit
#print axioms YangMills.RG.abs_cmp116FDerivHessian_cmp102Eq80CouplingScaledPotential_le_explicit_of_hessian
