/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP109Lemma1CombinedCenteredRegion
import YangMills.RG.BalabanCMP109Lemma1Eq136SourceCertificate
import YangMills.RG.BalabanCMP116Eq214AnalyticResummation
import YangMills.RG.BalabanCMP116Eq222CutoffSupNormTransport

/-!
# Source-faithful common small-field carrier for the direct and Lemma-1 sectors

The centered localization region `Z0` and the small-field cutoff carrier are
different source objects.  `Z0` must contain the selected large-field bonds
`P` in order to localize the contour integral.  The small-field carrier in
CMP116 equations (2.3) and (2.14), by contrast, is the complement of the
literal exterior carrier generated by the selected domain family.  Every
admissible `P` is a subset of that exterior carrier.

This file constructs the common small-field carrier from the already
canonical direct/native block family.  It proves that every direct
equation-(80) bond support and every native Lemma-1 fluctuation-bond support
is contained in it, and that it is disjoint from every source-admissible
large-field set `P`.  It also gives an explicit real-valued witness showing
that the resulting signed cutoff is algebraically nonzero; this rules out the
overlap vacuity of the retracted all-`InteriorBonds(Z0)` construction.

Honest scope: the witness is a cutoff-carrier test, not a construction of the
physical Gaussian coordinate or of the nonlinear correction `D(B)`.  The
analytic Lemma-1 equation-(1.36) estimate remains exactly the field
`CMP109Lemma1Eq136SourceCertificate.bound`.
-/

namespace YangMills.RG

noncomputable section

/-- A physical bond whose source block belongs to the domain union cannot be
part of the physical exterior carrier, hence belongs to the equation-(2.14)
small-field carrier. -/
theorem mem_cmp116Eq214SmallFieldBondCarrier_of_sourceBlock_mem_Y0
    {d M N' : ℕ} [NeZero M] [NeZero N']
    (D : Finset (Finset (FinBox d N')))
    (bond : PhysicalBond d (M * N'))
    (hsource : cmp116BondSourceBlock bond ∈ cmp116Eq23Y0 D) :
    bond ∈ cmp116Eq214SmallFieldBondCarrier
      (Finset.univ : Finset (PhysicalBond d (M * N'))) ∅ D := by
  rw [mem_cmp116Eq214SmallFieldBondCarrier_iff]
  refine ⟨Finset.mem_univ _, ?_⟩
  intro houtside
  have hdisjoint :
      Disjoint (cmp116BondBlocks bond) (cmp116Eq23Y0 D) :=
    (mem_cmp116Eq23PhysicalBondOutsideCarrier_iff.mp houtside).2.1
  exact (Finset.disjoint_left.mp hdisjoint)
    (by simp [cmp116BondBlocks]) hsource

/-- The common source small-field carrier obtained from the exact combined
direct/native block family, independently of the later centered region
`Z0`. -/
noncomputable def cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc) :
    Finset (PhysicalBond 4 (M * (2 * Q))) :=
  cmp116Eq214SmallFieldBondCarrier Finset.univ ∅
    (cmp116Eq80Lemma1CombinedBlockDomainFamily anchor D E)

/-- Every selected direct equation-(80) bond lies in the common source
small-field carrier. -/
theorem cmp102Eq80SourcePi4PhysicalY0_subset_combinedSourceSmallFieldCarrier
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc) :
    cmp102Eq80SourcePi4PhysicalY0 (M := M) anchor D ⊆
      cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor D E := by
  intro bond hbond
  apply mem_cmp116Eq214SmallFieldBondCarrier_of_sourceBlock_mem_Y0
  unfold cmp102Eq80SourcePi4PhysicalY0 at hbond
  rw [mem_cmp116Eq23Y0_iff] at hbond
  rcases hbond with ⟨S, hS, hbond⟩
  rcases Finset.mem_image.mp hS with ⟨W, hWD, rfl⟩
  have hsource :=
    mem_cmp116LocalizationDomain_bondSupport_sourceBlock hbond
  rw [mem_cmp116Eq23Y0_iff]
  refine ⟨W.1, ?_, hsource⟩
  apply Finset.mem_union_left
  exact Finset.mem_image.mpr ⟨W, hWD, rfl⟩

/-- Every native Lemma-1 fluctuation bond at a canonical terminal index lies
in the same common source small-field carrier. -/
theorem cmp109Lemma1SourceBondSupport_subset_combinedSourceSmallFieldCarrier
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (i : Fin (CMP109Lemma1NativeDomainCount E)) :
    cmp109Lemma1SourceBondSupport (cmp109Lemma1NativeDomainAt E i) ⊆
      cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor D E := by
  intro bond hbond
  apply mem_cmp116Eq214SmallFieldBondCarrier_of_sourceBlock_mem_Y0
  have hsource :
      cmp116BondSource bond ∈ (cmp109Lemma1NativeDomainAt E i).blocks :=
    (mem_cmp109Lemma1SourceBondSupport_iff.mp hbond).1
  rw [mem_cmp116Eq23Y0_iff]
  refine ⟨cmp109Lemma1NativeIndexedDomainSupport E i, ?_, ?_⟩
  · exact Finset.mem_union_right _
      (cmp109Lemma1NativeIndexedDomainSupport_mem_supportFamily E i)
  · exact Finset.mem_image.mpr
      ⟨cmp116BondSource bond, hsource, rfl⟩

/-- Source admissibility of `P` implies literal separation of the common
small-field and large-field carriers. -/
theorem cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier_disjoint_of_P_subset
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (hP : P ⊆ cmp116Eq23PhysicalBondOutsideCarrier Finset.univ ∅
      (cmp116Eq80Lemma1CombinedBlockDomainFamily anchor D E)) :
    Disjoint
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor D E) P := by
  rw [Finset.disjoint_left]
  intro bond hsmall hlarge
  have hdisjoint := cmp116Eq214_disjoint_smallField_outside
    (Finset.univ : Finset (PhysicalBond 4 (M * (2 * Q)))) ∅
    (cmp116Eq80Lemma1CombinedBlockDomainFamily anchor D E)
  exact (Finset.disjoint_left.mp hdisjoint) hsmall (hP hlarge)

/-- Generic explicit witness that disjoint small/large carriers do not make
the signed cutoff vacuous.  The field is zero on the small carrier and equal
to the positive threshold on `P`. -/
theorem cmp116SignedCutoff_piecewiseRealWitness_ne_zero
    {Bond : Type*} [DecidableEq Bond]
    (small P : Finset Bond) (threshold : ℝ)
    (hthreshold : 0 < threshold) (hdisjoint : Disjoint small P) :
    (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff small threshold
            (fun bond => if bond ∈ P then threshold else 0) *
        cmp116LargeFieldCutoff P threshold
          (fun bond => if bond ∈ P then threshold else 0) ≠ 0 := by
  have hsmall :
      cmp116SmallFieldCutoff small threshold
          (fun bond => if bond ∈ P then threshold else 0) = 1 := by
    unfold cmp116SmallFieldCutoff
    apply Finset.prod_eq_one
    intro bond hbond
    have hnot : bond ∉ P :=
      fun hmem => (Finset.disjoint_left.mp hdisjoint) hbond hmem
    simp [cmp116SmallFieldIndicator, hnot, hthreshold]
  have hlarge :
      cmp116LargeFieldCutoff P threshold
          (fun bond => if bond ∈ P then threshold else 0) = 1 := by
    unfold cmp116LargeFieldCutoff
    apply Finset.prod_eq_one
    intro bond hbond
    simp [cmp116LargeFieldIndicator, hbond, abs_of_pos hthreshold]
  rw [hsmall, hlarge]
  simp

/-- Specialized non-vacuity test for the corrected combined source carrier.
This is intentionally an algebraic witness, not a physical Gaussian-field
constructor. -/
theorem cmp116Eq80Lemma1CombinedSourceSignedCutoff_piecewiseWitness_ne_zero
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (threshold : ℝ) (hthreshold : 0 < threshold)
    (hP : P ⊆ cmp116Eq23PhysicalBondOutsideCarrier Finset.univ ∅
      (cmp116Eq80Lemma1CombinedBlockDomainFamily anchor D E)) :
    (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff
            (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor D E)
            threshold (fun bond => if bond ∈ P then threshold else 0) *
        cmp116LargeFieldCutoff P threshold
          (fun bond => if bond ∈ P then threshold else 0) ≠ 0 := by
  exact cmp116SignedCutoff_piecewiseRealWitness_ne_zero _ _ threshold hthreshold
    (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier_disjoint_of_P_subset
      anchor D E P hP)

/-- Nonvanishing of the corrected common signed cutoff supplies the exact
per-domain small-field premise consumed by the source-pinned Lemma-1
certificate. -/
theorem cmp109Lemma1SourceSmallField_of_combinedSourceCutoff
    {Index : Type*} {M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (D : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (P : Finset (PhysicalBond 4 (M * (2 * Q))))
    (epsilon1 gk : ℝ) (hepsilon1 : 0 ≤ epsilon1) (hgk : 0 < gk)
    (b : CMP116Eq214GaussianCoordinate
      (PhysicalBond 4 (M * (2 * Q))) (Nc ^ 2 - 1))
    (hcutoff :
      (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff
            (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor D E)
            (epsilon1 / gk) (cmp116SourcePhysicalCoordinateCochain b) *
          cmp116LargeFieldCutoff P (epsilon1 / gk)
            (cmp116SourcePhysicalCoordinateCochain b) ≠ 0)
    (i : Fin (CMP109Lemma1NativeDomainCount E)) :
    cmp109Lemma1SourceSmallField epsilon1 gk
      (cmp109Lemma1NativeDomainAt E i)
      (cmp116SourcePhysicalCoordinateCochain b) := by
  unfold cmp109Lemma1SourceSmallField
  exact
    cmp98SourceFieldSupNorm_physicalBondProjection_le_threshold_of_cutoffFactor_ne_zero
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor D E)
      P
      (cmp109Lemma1SourceBondSupport (cmp109Lemma1NativeDomainAt E i))
      (epsilon1 / gk) b
      (div_nonneg hepsilon1 (le_of_lt hgk))
      (cmp109Lemma1SourceBondSupport_subset_combinedSourceSmallFieldCarrier
        anchor D E i)
      hcutoff

end

end YangMills.RG
