/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102PhysicalTwoFieldContour

/-!
# Two-field control of the physical CMP98 Ubar logarithmic average

This module propagates the literal two-field contour estimate through the
four-contour deviation and the normalized Mercator average defining
`Ubar`.  The Mercator Lipschitz constant is generated by the audited
derivative bound on a common source ball.  Exact block cardinality cancels
the `M⁻ᵈ` normalization, so the final estimate remains volume-independent.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102TwoFieldUbarMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- Explicit two-field budget for one literal CMP98 four-contour word. -/
def cmp102SourceFourContourTwoFieldBudget
    (A B : PhysicalGaugeOneCochain d (M * N') Nc) (t : ℝ) : ℝ :=
  ((2 * (d + 1) * M : ℕ) : ℝ) *
    (cmp102ExpLipschitzBudget (1 / 2) *
      (|t| * cmp98SourceFieldSupNorm (A - B)))

theorem cmp102SourceFourContourTwoFieldBudget_nonneg
    (A B : PhysicalGaugeOneCochain d (M * N') Nc) (t : ℝ) :
    0 ≤ cmp102SourceFourContourTwoFieldBudget A B t := by
  unfold cmp102SourceFourContourTwoFieldBudget
  exact mul_nonneg (Nat.cast_nonneg _)
    (mul_nonneg
      (cmp102ExpLipschitzBudget_nonneg (1 / 2) (by norm_num))
      (mul_nonneg (abs_nonneg t)
        (cmp98SourceFieldSupNorm_nonneg (A - B))))

/-- The literal ambient four-contour deviations at two physical fields
differ by the source-explicit contour budget. -/
theorem norm_cmp98UbarAmbientDeviationMatrix_twoField_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A B : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1) (t : ℝ)
    (hA : |t| * cmp98SourceFieldSupNorm A ≤ 1 / 2)
    (hB : |t| * cmp98SourceFieldSupNorm B ≤ 1 / 2) :
    ‖cmp98UbarAmbientDeviationMatrix U b x
          (t • physicalSuTangentToAmbient
            (physicalCochainToSuMatrixTangent A)) -
        cmp98UbarAmbientDeviationMatrix U b x
          (t • physicalSuTangentToAmbient
            (physicalCochainToSuMatrixTangent B))‖ ≤
      cmp102SourceFourContourTwoFieldBudget A B t := by
  rw [cmp98UbarAmbientDeviationMatrix_line_eq_deviationCurve,
    cmp98UbarAmbientDeviationMatrix_line_eq_deviationCurve]
  unfold cmp98UbarDeviationCurve
  rw [cmp98UbarFourFactorProduct_eq_sourceContourMatrixCurve,
    cmp98UbarFourFactorProduct_eq_sourceContourMatrixCurve]
  have hcancel :
      cmp98ContourMatrixCurve U A
            (cmp98SourceFourContourEdges (Nc := Nc) b x) t - 1 -
          (cmp98ContourMatrixCurve U B
            (cmp98SourceFourContourEdges (Nc := Nc) b x) t - 1) =
        cmp98ContourMatrixCurve U A
            (cmp98SourceFourContourEdges (Nc := Nc) b x) t -
          cmp98ContourMatrixCurve U B
            (cmp98SourceFourContourEdges (Nc := Nc) b x) t := by
    abel
  rw [hcancel]
  exact norm_cmp98SourceFourContourMatrixCurve_sub_le_sourceScale
    U A B b x hx t (1 / 2) (by norm_num) hA hB

/-- The local Mercator summands at two physical fields satisfy the same
source-explicit Lipschitz estimate on a common source ball. -/
theorem norm_nearLog_cmp98UbarAmbientDeviationMatrix_twoField_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A B : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1) (t r : ℝ)
    (hbase :
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ 1 / 3)
    (hA : |t| * cmp98SourceFieldSupNorm A ≤ 1 / 2)
    (hB : |t| * cmp98SourceFieldSupNorm B ≤ 1 / 2)
    (hrA : 1 / 3 + cmp98SourceContourDisplacementBudget A t ≤ r)
    (hrB : 1 / 3 + cmp98SourceContourDisplacementBudget B t ≤ r)
    (hr1 : r < 1) :
    ‖nearLog
          (cmp98UbarAmbientDeviationMatrix U b x
            (t • physicalSuTangentToAmbient
              (physicalCochainToSuMatrixTangent A))) -
        nearLog
          (cmp98UbarAmbientDeviationMatrix U b x
            (t • physicalSuTangentToAmbient
              (physicalCochainToSuMatrixTangent B)))‖ ≤
      nearLogDerivativeBudget r *
        cmp102SourceFourContourTwoFieldBudget A B t := by
  let DA := cmp98UbarAmbientDeviationMatrix U b x
    (t • physicalSuTangentToAmbient
      (physicalCochainToSuMatrixTangent A))
  let DB := cmp98UbarAmbientDeviationMatrix U b x
    (t • physicalSuTangentToAmbient
      (physicalCochainToSuMatrixTangent B))
  let D0 := cmp98UbarAmbientDeviationMatrix U b x 0
  have hdispA : ‖DA - D0‖ ≤
      cmp98SourceContourDisplacementBudget A t := by
    simpa [DA, D0, cmp98SourceContourDisplacementBudget] using
      norm_cmp98UbarAmbientDeviationMatrix_physicalLine_sub_zero_le
        U A b x hx t hA
  have hdispB : ‖DB - D0‖ ≤
      cmp98SourceContourDisplacementBudget B t := by
    simpa [DB, D0, cmp98SourceContourDisplacementBudget] using
      norm_cmp98UbarAmbientDeviationMatrix_physicalLine_sub_zero_le
        U B b x hx t hB
  have hDA : ‖DA‖ ≤ r := by
    calc
      ‖DA‖ ≤ ‖DA - D0‖ + ‖D0‖ := by
        simpa only [sub_add_cancel] using norm_add_le (DA - D0) D0
      _ ≤ cmp98SourceContourDisplacementBudget A t + 1 / 3 :=
        add_le_add hdispA hbase
      _ = 1 / 3 + cmp98SourceContourDisplacementBudget A t := by ring
      _ ≤ r := hrA
  have hDB : ‖DB‖ ≤ r := by
    calc
      ‖DB‖ ≤ ‖DB - D0‖ + ‖D0‖ := by
        simpa only [sub_add_cancel] using norm_add_le (DB - D0) D0
      _ ≤ cmp98SourceContourDisplacementBudget B t + 1 / 3 :=
        add_le_add hdispB hbase
      _ = 1 / 3 + cmp98SourceContourDisplacementBudget B t := by ring
      _ ≤ r := hrB
  have hdiff : ‖DA - DB‖ ≤
      cmp102SourceFourContourTwoFieldBudget A B t := by
    simpa [DA, DB] using
      norm_cmp98UbarAmbientDeviationMatrix_twoField_sub_le
        U A B b x hx t hA hB
  have hr0 : 0 ≤ r := (norm_nonneg DA).trans hDA
  exact (norm_nearLog_sub_nearLog_le hr0 hr1 hDA hDB).trans
    (mul_le_mul_of_nonneg_left hdiff
      (nearLogDerivativeBudget_nonneg r hr0))

/-- The normalized logarithmic average inherits the pointwise two-field
budget with no block-cardinality loss. -/
theorem norm_cmp98UbarLogAverage_twoField_sub_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A B : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (t r : ℝ)
    (hbase : ∀ x ∈ blockOf M N' b.1,
      ‖cmp98UbarAmbientDeviationMatrix U b x 0‖ ≤ 1 / 3)
    (hA : |t| * cmp98SourceFieldSupNorm A ≤ 1 / 2)
    (hB : |t| * cmp98SourceFieldSupNorm B ≤ 1 / 2)
    (hrA : 1 / 3 + cmp98SourceContourDisplacementBudget A t ≤ r)
    (hrB : 1 / 3 + cmp98SourceContourDisplacementBudget B t ≤ r)
    (hr1 : r < 1) :
    ‖cmp98UbarLogAverage U b
          (t • physicalSuTangentToAmbient
            (physicalCochainToSuMatrixTangent A)) -
        cmp98UbarLogAverage U b
          (t • physicalSuTangentToAmbient
            (physicalCochainToSuMatrixTangent B))‖ ≤
      nearLogDerivativeBudget r *
        cmp102SourceFourContourTwoFieldBudget A B t := by
  let ZA : PhysicalAmbientMatrixTangent d (M * N') Nc :=
    t • physicalSuTangentToAmbient (physicalCochainToSuMatrixTangent A)
  let ZB : PhysicalAmbientMatrixTangent d (M * N') Nc :=
    t • physicalSuTangentToAmbient (physicalCochainToSuMatrixTangent B)
  let SA : Matrix (Fin Nc) (Fin Nc) ℂ :=
    ∑ x ∈ blockOf M N' b.1,
      nearLog (cmp98UbarAmbientDeviationMatrix U b x ZA)
  let SB : Matrix (Fin Nc) (Fin Nc) ℂ :=
    ∑ x ∈ blockOf M N' b.1,
      nearLog (cmp98UbarAmbientDeviationMatrix U b x ZB)
  let SD : Matrix (Fin Nc) (Fin Nc) ℂ :=
    ∑ x ∈ blockOf M N' b.1,
      (nearLog (cmp98UbarAmbientDeviationMatrix U b x ZA) -
        nearLog (cmp98UbarAmbientDeviationMatrix U b x ZB))
  let C := nearLogDerivativeBudget r *
    cmp102SourceFourContourTwoFieldBudget A B t
  have hpoint : ∀ x ∈ blockOf M N' b.1,
      ‖nearLog (cmp98UbarAmbientDeviationMatrix U b x ZA) -
        nearLog (cmp98UbarAmbientDeviationMatrix U b x ZB)‖ ≤ C := by
    intro x hx
    simpa [ZA, ZB, C] using
      norm_nearLog_cmp98UbarAmbientDeviationMatrix_twoField_sub_le
        U A B b x hx t r (hbase x hx) hA hB hrA hrB hr1
  have hsum : SA - SB = SD := by
    dsimp only [SA, SB, SD]
    exact (Finset.sum_sub_distrib
      (fun x => nearLog (cmp98UbarAmbientDeviationMatrix U b x ZA))
      (fun x => nearLog (cmp98UbarAmbientDeviationMatrix U b x ZB))).symm
  have havgReal :
      cmp98UbarLogAverage U b ZA - cmp98UbarLogAverage U b ZB =
        ((M : ℝ) ^ d)⁻¹ • SD := by
    rw [cmp98UbarLogAverage, cmp98UbarLogAverage]
    change ((M : ℝ) ^ d)⁻¹ • SA - ((M : ℝ) ^ d)⁻¹ • SB = _
    calc
      ((M : ℝ) ^ d)⁻¹ • SA - ((M : ℝ) ^ d)⁻¹ • SB =
          ((M : ℝ) ^ d)⁻¹ • (SA - SB) :=
        (smul_sub ((M : ℝ) ^ d)⁻¹ SA SB).symm
      _ = ((M : ℝ) ^ d)⁻¹ • SD := congrArg _ hsum
  have hrealComplex :
      ((M : ℝ) ^ d)⁻¹ • SD = (((M : ℝ) ^ d)⁻¹ : ℂ) • SD := by
    ext i j
    simp [RCLike.real_smul_eq_coe_mul]
  have havg :
      cmp98UbarLogAverage U b ZA - cmp98UbarLogAverage U b ZB =
        (((M : ℝ) ^ d)⁻¹ : ℂ) • SD :=
    havgReal.trans hrealComplex
  have hM : (M : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne M)
  have hMd : (M : ℝ) ^ d ≠ 0 := pow_ne_zero d hM
  have hnormc : ‖(((M : ℝ) ^ d)⁻¹ : ℂ)‖ = ((M : ℝ) ^ d)⁻¹ := by
    rw [norm_inv, norm_pow, Complex.norm_real, Real.norm_eq_abs,
      abs_of_nonneg (Nat.cast_nonneg M)]
  rw [havg, norm_smul, hnormc]
  calc
    ((M : ℝ) ^ d)⁻¹ * ‖SD‖
        ≤ ((M : ℝ) ^ d)⁻¹ *
            ∑ x ∈ blockOf M N' b.1,
              ‖nearLog (cmp98UbarAmbientDeviationMatrix U b x ZA) -
                nearLog (cmp98UbarAmbientDeviationMatrix U b x ZB)‖ := by
          gcongr
          dsimp only [SD]
          exact norm_sum_le _ _
    _ ≤ ((M : ℝ) ^ d)⁻¹ *
          ∑ _x ∈ blockOf M N' b.1, C := by
      gcongr with x hx
      exact hpoint x hx
    _ = C := by
      rw [Finset.sum_const, blockOf_card]
      simp only [nsmul_eq_mul, Nat.cast_pow]
      rw [← mul_assoc, inv_mul_cancel₀ hMd, one_mul]
    _ = nearLogDerivativeBudget r *
        cmp102SourceFourContourTwoFieldBudget A B t := rfl

end

end YangMills.RG
