import YangMills.RG.BalabanCMP99SourceEq395MiddleGapPhysicalAdjoint

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalMiddleGap_comp_smoothMultiplier_eq_liftedAdjoint
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_eq_liftedAdjoint_add_commutator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefect_liftedAdjoint_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalMiddleGap_comp_smoothMultiplier_exponentialKernelBound
