import YangMills.RG.BalabanCMP99SourceGeneratedWeightedAdjointRange

#print axioms YangMills.RG.CMP99SourceActiveRegionChain.terminalSiteOfFine
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.sameTerminalBlock_iff_terminalSiteOfFine_eq
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.terminalHilbertSpace_eq_coordinate
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.physicalWeightedAdjoint
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.physicalWeightedAdjoint_eq_transported
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.norm_physicalWeightedAdjoint
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.physicalWeightedAdjoint_single_apply_eq_zero
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.terminalRepresentative
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.terminalSiteOfFine_representative
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.terminalSiteOfFine_ne_of_dist_gt
#print axioms YangMills.RG.cmp99SourceIteratedLift_terminalBlock_diameter
#print axioms YangMills.RG.cmp99SourceIteratedLift_physicalWeightedAdjoint_finiteRange
