import YangMills.RG.BalabanCMP99ActiveGaugeRegionReindexGreen


#print axioms YangMills.RG.cmp99SourceAmbientDirichletGreen
#print axioms YangMills.RG.cmp99SourceAmbientDirichletGreen_comp_precision
#print axioms YangMills.RG.cmp99SourceAmbientDirichletPrecision_comp_green
#print axioms YangMills.RG.finitePiLpTypedKernelReindex_sourceAmbientDirichletGreen
