import YangMills.RG.BalabanCMP99SourceEq395FirstLeftWeightedRow

#print axioms YangMills.RG.finBoxDist_exp_sum_le_cmp99OmegaSiteExpSumBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalFirstLeft_weightedRow
