import YangMills.RG.BalabanCMP99SourceGeneratedFullComplexADepthDecayNoGo

#print axioms YangMills.RG.cmp99SourceGeneratedFullComplexSpacing_succ_scale
#print axioms YangMills.RG.cmp99SourcePoincareEnergyCoeff_canonical_succ
#print axioms YangMills.RG.cmp99SourceGeneratedCanonicalFullComplexA_succ_le_half
#print axioms YangMills.RG.cmp99SourceGeneratedCanonicalFullComplexA_add_le_div_pow
#print axioms YangMills.RG.cmp99SourceGeneratedCanonicalFullComplexA_eventually_lt
#print axioms YangMills.RG.exists_cmp99SourceGeneratedCanonicalFullComplexA_lt_massParameter
