import YangMills.RG.BalabanCMP99SourceRegionalSectionCRightFactor

open YangMills.RG

#print axioms cmp99OmegaSourcePhysicalOneStepCoarseRightFactor
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseRightFactorDecayRate
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseRightFactorDecayAmplitude
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovariance_transition_eq_comp_rightFactor
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseRightFactor_eq_greenMismatch_comp_covariance
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseRightFactor_exponentialKernelBound
