import YangMills.RG.BalabanCMP99Eq360ComplexLocalLaplacianPerturbation

#print axioms YangMills.RG.cmp99Eq360ComplexLocalLaplacianPerturbation
#print axioms YangMills.RG.cmp99Eq360ComplexLocalLaplacianPerturbation_apply
#print axioms YangMills.RG.cmp99Eq360_complexRegionalLaplacian_sub_eq_localPerturbation
#print axioms YangMills.RG.cmp99Eq360_complexRegionalLaplacian_eq_sub_localPerturbation
