import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothCommutatorFactor

open YangMills.RG

#print axioms cmp99SourceGeneratedSmoothGreenCommutatorNormBound
#print axioms cmp99SourceGeneratedSmoothSectionCMiddleNormBound
#print axioms cmp99SourceGeneratedSmoothSectionCFactorNormBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorMiddle
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorMiddleCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalSmoothSectionCCommutatorMiddle_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalSmoothSectionCCommutatorMiddleCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorFactorCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalSmoothSectionCCommutatorFactorCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalSmoothSectionCCommutatorFactorCertificate
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95PhysicalSmoothSectionCCommutatorFactorCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedCMP95PhysicalSmoothSectionCCommutatorFactorCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95PhysicalSmoothSectionCCommutatorFactorCertificate
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCertificate
