/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceEq325GaugeProjection

/-!
# The projected gauge mass in CMP99 equation (3.26)

CMP99 equation (3.26) contains the one-cochain operator

`D_U^eta R(U) D_U^{eta*}`,

where `R(U)` is the literal equation-(3.25) zero-cochain projection.  This
file constructs that term from the already generated physical regional
covariant derivative.  The idempotence and symmetry proved for `R` show
that its quadratic form is exactly the squared norm of the projected
covariant divergence.  In particular the term is positive and symmetric;
neither property is supplied by the caller.

This is the projected gauge contribution only.  The remaining one-cochain
terms `Delta'_pi` and `Q^* a Q` of the complete source precision are not
identified here.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator RealInnerProductSpace

noncomputable section

/-- Generic source-shaped operator `D R D*`. -/
noncomputable def cmp99ProjectedGaugeMassCLM
    {E F : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F]
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (D : E →L[ℝ] F) (R : E →L[ℝ] E) : F →L[ℝ] F :=
  D.comp (R.comp D.adjoint)

/-- An orthogonal projection turns the quadratic form of `D R D*` into a
squared norm. -/
theorem inner_cmp99ProjectedGaugeMassCLM_eq_norm_sq
    {E F : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F]
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (D : E →L[ℝ] F) (R : E →L[ℝ] E)
    (hR : R.IsSymmetric) (hRR : R.comp R = R) (A : F) :
    inner ℝ A (cmp99ProjectedGaugeMassCLM D R A) =
      ‖R (D.adjoint A)‖ ^ 2 := by
  have hRR_apply : R (R (D.adjoint A)) = R (D.adjoint A) := by
    have h := congrArg (fun T : E →L[ℝ] E => T (D.adjoint A)) hRR
    simpa only [ContinuousLinearMap.comp_apply] using h
  calc
    inner ℝ A (cmp99ProjectedGaugeMassCLM D R A) =
        inner ℝ (D (R (D.adjoint A))) A := real_inner_comm _ _
    _ = inner ℝ (R (D.adjoint A)) (D.adjoint A) :=
      (ContinuousLinearMap.adjoint_inner_right D _ _).symm
    _ = inner ℝ (D.adjoint A) (R (D.adjoint A)) := real_inner_comm _ _
    _ = inner ℝ (D.adjoint A) (R (R (D.adjoint A))) := by rw [hRR_apply]
    _ = inner ℝ (R (D.adjoint A)) (R (D.adjoint A)) :=
      (hR _ _).symm
    _ = ‖R (D.adjoint A)‖ ^ 2 := real_inner_self_eq_norm_sq _

/-- Positivity is generated by the orthogonal projection, not assumed. -/
theorem inner_cmp99ProjectedGaugeMassCLM_nonneg
    {E F : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F]
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (D : E →L[ℝ] F) (R : E →L[ℝ] E)
    (hR : R.IsSymmetric) (hRR : R.comp R = R) (A : F) :
    0 ≤ inner ℝ A (cmp99ProjectedGaugeMassCLM D R A) := by
  rw [inner_cmp99ProjectedGaugeMassCLM_eq_norm_sq D R hR hRR A]
  positivity

/-- Symmetry of the projected gauge mass. -/
theorem cmp99ProjectedGaugeMassCLM_isSymmetric
    {E F : Type*}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [NormedAddCommGroup F] [InnerProductSpace ℝ F]
    [FiniteDimensional ℝ E] [FiniteDimensional ℝ F]
    (D : E →L[ℝ] F) (R : E →L[ℝ] E) (hR : R.IsSymmetric) :
    (cmp99ProjectedGaugeMassCLM D R).IsSymmetric := by
  intro A B
  calc
    inner ℝ (cmp99ProjectedGaugeMassCLM D R A) B =
        inner ℝ (R (D.adjoint A)) (D.adjoint B) :=
      (ContinuousLinearMap.adjoint_inner_right D _ _).symm
    _ = inner ℝ (D.adjoint A) (R (D.adjoint B)) := hR _ _
    _ = inner ℝ (R (D.adjoint B)) (D.adjoint A) := real_inner_comm _ _
    _ = inner ℝ (D (R (D.adjoint B))) A :=
      ContinuousLinearMap.adjoint_inner_right D _ _
    _ = inner ℝ A (cmp99ProjectedGaugeMassCLM D R B) := real_inner_comm _ _

variable {d M N Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N] [NeZero Nc]

/-- Literal projected gauge term `D_U^eta R(U) D_U^{eta*}` on the terminal
source region. -/
noncomputable def cmp99SourceEq326ProjectedGaugeMass
    (hd : 2 ≤ d) (hM : 2 ≤ M) (Omega : ActiveGaugeRegion d N)
    (depth : ℕ) {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig d
      (cmp99RegionalLatticeSize M N (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget d M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge d
      (cmp99RegionalLatticeSize M N (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff d M (depth + 1)
      spacing epsilon < 1) :
    PhysicalGaugeOneCochain d
        (cmp99RegionalLatticeSize M N (depth + 1)) Nc →L[ℝ]
      PhysicalGaugeOneCochain d
        (cmp99RegionalLatticeSize M N (depth + 1)) Nc :=
  let terminal := cmp99IteratedLiftActiveRegion (M := M) Omega (depth + 1)
  let D := cmp99ActiveRegionSourceCovariantD0CLM terminal
    (matrixSUNAdjointModel Nc) background spacing
  let R := cmp99SourceEq325PhysicalGaugeProjection hd hM Omega depth
    hspacing background budget fineSmall hsmall
  cmp99ProjectedGaugeMassCLM D R

set_option maxRecDepth 6000 in
set_option maxHeartbeats 4000000 in
/-- Exact physical quadratic-form identity for the equation-(3.26) gauge
term. -/
theorem inner_cmp99SourceEq326ProjectedGaugeMass_eq_norm_sq
    (hd : 2 ≤ d) (hM : 2 ≤ M) (Omega : ActiveGaugeRegion d N)
    (depth : ℕ) {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig d
      (cmp99RegionalLatticeSize M N (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget d M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge d
      (cmp99RegionalLatticeSize M N (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff d M (depth + 1)
      spacing epsilon < 1)
    (A : PhysicalGaugeOneCochain d
      (cmp99RegionalLatticeSize M N (depth + 1)) Nc) :
    let terminal := cmp99IteratedLiftActiveRegion (M := M) Omega (depth + 1)
    let D := cmp99ActiveRegionSourceCovariantD0CLM terminal
      (matrixSUNAdjointModel Nc) background spacing
    let R := cmp99SourceEq325PhysicalGaugeProjection hd hM Omega depth
      hspacing background budget fineSmall hsmall
    inner ℝ A
        (cmp99SourceEq326ProjectedGaugeMass hd hM Omega depth hspacing
          background budget fineSmall hsmall A) =
      ‖R (D.adjoint A)‖ ^ 2 := by
  dsimp only
  apply inner_cmp99ProjectedGaugeMassCLM_eq_norm_sq
  · exact cmp99SourceEq325PhysicalGaugeProjection_isSymmetric hd hM Omega
      depth hspacing background budget fineSmall hsmall
  · exact cmp99SourceEq325PhysicalGaugeProjection_comp_self hd hM Omega
      depth hspacing background budget fineSmall hsmall

set_option maxRecDepth 6000 in
set_option maxHeartbeats 4000000 in
/-- Positivity of the literal equation-(3.26) projected gauge term. -/
theorem inner_cmp99SourceEq326ProjectedGaugeMass_nonneg
    (hd : 2 ≤ d) (hM : 2 ≤ M) (Omega : ActiveGaugeRegion d N)
    (depth : ℕ) {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig d
      (cmp99RegionalLatticeSize M N (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget d M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge d
      (cmp99RegionalLatticeSize M N (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff d M (depth + 1)
      spacing epsilon < 1)
    (A : PhysicalGaugeOneCochain d
      (cmp99RegionalLatticeSize M N (depth + 1)) Nc) :
    0 ≤ inner ℝ A
      (cmp99SourceEq326ProjectedGaugeMass hd hM Omega depth hspacing
        background budget fineSmall hsmall A) := by
  rw [inner_cmp99SourceEq326ProjectedGaugeMass_eq_norm_sq hd hM Omega depth
    hspacing background budget fineSmall hsmall A]
  positivity

set_option maxRecDepth 6000 in
set_option maxHeartbeats 4000000 in
/-- The physical equation-(3.26) projected gauge term is symmetric. -/
theorem cmp99SourceEq326ProjectedGaugeMass_isSymmetric
    (hd : 2 ≤ d) (hM : 2 ≤ M) (Omega : ActiveGaugeRegion d N)
    (depth : ℕ) {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig d
      (cmp99RegionalLatticeSize M N (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget d M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge d
      (cmp99RegionalLatticeSize M N (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff d M (depth + 1)
      spacing epsilon < 1) :
    (cmp99SourceEq326ProjectedGaugeMass hd hM Omega depth hspacing
      background budget fineSmall hsmall).IsSymmetric := by
  unfold cmp99SourceEq326ProjectedGaugeMass
  apply cmp99ProjectedGaugeMassCLM_isSymmetric
  exact cmp99SourceEq325PhysicalGaugeProjection_isSymmetric hd hM Omega depth
    hspacing background budget fineSmall hsmall

end
end YangMills.RG
