import YangMills.RG.BalabanCMP99SourceDisplayedSectionCSubalphabet

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCSubalphabet
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousSpace_coarse_eq
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCSourceLabelNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCLabelNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCLabelOperator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCCoarseLabelOperator_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCLabelOperator_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCOperatorWalk_le
