import YangMills.RG.BalabanCMP99SourceEq395GlobalRegionalMiddleBridge

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalRegion_subset_full
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefect
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleGreenTransport
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefect_eq_greenMismatch
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalGreenTransition_exponentialKernelBound
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectCoordinates
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleGreenTransportCoordinates
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectCoordinates_eq_greenMismatch
