import YangMills.RG.BalabanCMP116SourceRestrictedConditionedPhysicalR3SourceRateProducer

#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_sub_one_le_radius
#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_le_one_add_radius
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.withSourcePi4RestrictedComplexGaussianOfPhysicalContour_r3Matrix
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.dotProduct_sourcePi4RestrictedConditioned_r3RealSource_self_le_physical
