/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116SourceSigmaZeroActiveCarrier
import YangMills.RG.BalabanCMP116ComplexPhysicalWalkKernel
import YangMills.RG.BalabanCMP99PatchedParametrixGeometricWeightedDecay
import YangMills.RG.BalabanCMP99PatchedParametrixFixedRateSummability

/-!
# Source-specific complex Cauchy bound for CMP99 patched walks

This module composes the literal `Pi^4`/`sigma_0` chart geometry, the physical
patched-parametrix walk terms, their volume-uniform summability theorem, and
the complex weakening contour.  The terminal result is a Cauchy boundary
bound for every physical kernel entry.

The radial operator majorant is not an input.  It is generated by evaluating
the already proved source-specific real series at the constant weakening
system `s = Rweak`; its monomial is exactly `Rweak ^ card(active walk)`.
The complex coefficient majorant then follows with constant one.
-/

namespace YangMills.RG

noncomputable section

universe u

set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 1600000

/-- Terminal source-specific complex Cauchy estimate for one physical kernel
entry of the patched random-walk series.  No abstract radial majorant,
branching factor, active-carrier budget, or chart dictionary remains. -/
theorem cmp116Eq214CauchyBoundaryBound_sourceSigmaZeroPi4PhysicalWalkKernel
    {Label : Type u} [Fintype Label] [DecidableEq Label]
    {M Q Nc Rrange NR : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q) (hsourceRange : Rrange + 1 ≤ 4 * M)
    (K : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
      PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc)
    (hsymm : ∀ p q : PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist p q = physicalBondDist q p)
    (hself : ∀ p : PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist p p = 0)
    (htri : ∀ x y z : PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist x y ≤
        physicalBondDist x z + physicalBondDist z y)
    {Cker c mass κ σ Ssum Sdef : ℝ}
    (hCker : 0 ≤ Cker) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ)
    (hSsum : 0 ≤ Ssum) (hSdef : 0 ≤ Sdef)
    (hsum : ∀ x,
      ∑ z : PhysicalBond 4 (M * (2 * Q)),
        Real.exp (-(σ * (physicalBondDist x z : ℝ))) ≤ Ssum)
    (hsumDef : ∀ x,
      ∑ z : PhysicalBond 4 (M * (2 * Q)),
        Real.exp (-(((((κ - σ) - σ) - σ) *
          (physicalBondDist x z : ℝ)))) ≤ Sdef)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist Rrange)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => Cker))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond 4 (M * (2 * Q)),
      (Finset.univ.filter
        (fun y => physicalBondDist x y ≤ Rrange)).card ≤ NR)
    (htilt :
      (Cker + |mass|) *
          (Real.exp (κ * (Rrange : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2)
    (Δ : ℕ) (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ) :
    let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
      (Label := Label) anchor hsourceRange
    ∀ (left : ↥Dict.charts)
      {n : ℕ} (emb : Fin n ↪ FinBox 4 (2 * Q))
      (radius : Fin n → ℝ)
      (source target : PhysicalBond 4 (M * (2 * Q)))
      (input output : Fin (Nc ^ 2 - 1))
      (Rweak : ℝ) (hRweak : 1 ≤ Rweak)
      (hcap : ∀ i, 1 + radius i ≤ Rweak)
      (hsmall :
        ((Fintype.card Label *
            (625 * 626 * Δ ^ 1250) : ℕ) : ℝ) *
            (cmp99SingleDefectDecayAmplitude
              Cker κ Rrange c mass Ssum * Sdef) *
              Rweak ^ 10000 < 1),
      CMP116Eq214CauchyBoundaryBound n radius
        (fun z => cmp116ComplexWeakenedRandomWalkSeries
          (fun walk : CMP99AnchoredWalk
              (cmp99PhysicalPatchSuccessorSteps
                Dict.charts Dict.core Dict.enlarged
                physicalBondDist Rrange) left =>
            walk.active Dict.domainActive)
          (fun walk => cmp116ComplexPhysicalOperatorCoefficient
            (walk.term
              (cmp99PhysicalPatchHead Dict.charts K
                Dict.enlarged Dict.core hc hmass hK)
              (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                Dict.enlarged Dict.core hc hmass hK))
            source target input output)
          (cmp116ComplexWeakeningOfContour emb z))
        (∑' walk : CMP99AnchoredWalk
            (cmp99PhysicalPatchSuccessorSteps
              Dict.charts Dict.core Dict.enlarged
              physicalBondDist Rrange) left,
          Rweak ^ (walk.active Dict.domainActive).card *
            ‖cmp116ComplexPhysicalOperatorCoefficient
              (walk.term
                (cmp99PhysicalPatchHead Dict.charts K
                  Dict.enlarged Dict.core hc hmass hK)
                (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                  Dict.enlarged Dict.core hc hmass hK))
              source target input output‖) := by
  dsimp only
  intro left n emb radius source target input output
    Rweak hRweak hcap hsmall
  let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
    (Label := Label) anchor hsourceRange
  let successors := cmp99PhysicalPatchSuccessorSteps
    Dict.charts Dict.core Dict.enlarged physicalBondDist Rrange
  let term : CMP99AnchoredWalk successors left →
      (PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
        PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc) :=
    fun walk => walk.term
      (cmp99PhysicalPatchHead Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
  have hsR :
      (fun _ : FinBox 4 (2 * Q) => Rweak) ∈
        cmp116WeakeningPolydisc Rweak := by
    intro block
    simp [abs_of_nonneg (zero_le_one.trans hRweak)]
  have hsourceSummable :=
    summable_cmp116SourceSigmaZeroPi4PhysicalPatchWalkSeries
      (Label := Label) anchor hsourceRange K hsymm hself htri
      hCker hc hmass hσ h3σκ hSsum hSdef hsum hsumDef
      hrange hbound hK hNR htilt Δ hΔ hΔ1
      left (fun _ => Rweak) Rweak hRweak hsmall hsR
  have hradial : Summable fun walk : CMP99AnchoredWalk successors left =>
      Rweak ^ (walk.active Dict.domainActive).card • term walk := by
    refine Summable.congr hsourceSummable fun walk => ?_
    change
      cmp116WeakeningMonomial (walk.active Dict.domainActive)
          (fun _ => Rweak) • term walk =
        Rweak ^ (walk.active Dict.domainActive).card • term walk
    congr 1
    simp [cmp116WeakeningMonomial]
  exact cmp116Eq214CauchyBoundaryBound_of_physicalWalkKernel
    emb radius
    (fun walk : CMP99AnchoredWalk successors left =>
      walk.active Dict.domainActive)
    term source target input output Rweak hRweak hcap hradial

/-- Closed radial majorant for one literal source patched-walk coefficient.

This is the quantitative core shared by the Cauchy-boundary theorem and the
base-contour estimate.  It exposes neither an unevaluated branching factor nor
an assumed whole-walk bound. -/
theorem tsum_sourceSigmaZeroPi4PhysicalWalkCoefficient_le_fixedRate
    {Label : Type u} [Fintype Label] [DecidableEq Label]
    {M Q Nc Rrange NR : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q) (hsourceRange : Rrange + 1 ≤ 4 * M)
    (K : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
      PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc)
    {Cker c mass κ σ μ : ℝ}
    (hCker : 0 ≤ Cker) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ) (hμ : 0 < μ)
    (hgeomBase :
      ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-σ) < 1)
    (hgeomHead :
      ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-((κ - σ) - μ)) < 1)
    (hgeomContinuation :
      ((2 ^ 4 : ℕ) : ℝ) *
        Real.exp (-((((κ - σ) - σ) - σ) - μ)) < 1)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist Rrange)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => Cker))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond 4 (M * (2 * Q)),
      (Finset.univ.filter
        (fun y => physicalBondDist x y ≤ Rrange)).card ≤ NR)
    (htilt :
      (Cker + |mass|) *
          (Real.exp (κ * (Rrange : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2)
    (Δ : ℕ) (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ) :
    let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
      (Label := Label) anchor hsourceRange
    let Ahead := cmp99PhysicalPatchHeadWeightedAmplitude c mass
      (cmp99PhysicalBondGeometricRowSum 4 σ)
      (cmp99PhysicalBondGeometricRowSum 4 ((κ - σ) - μ))
    let rho := cmp99PhysicalPatchContinuationWeightedAmplitude
      Cker κ Rrange c mass
      (cmp99PhysicalBondGeometricRowSum 4 σ)
      (cmp99PhysicalBondGeometricRowSum 4
        ((((κ - σ) - σ) - σ) - μ))
    let branching : ℕ :=
      Fintype.card Label * (625 * 626 * Δ ^ 1250)
    ∀ (left : ↥Dict.charts)
      (source target : PhysicalBond 4 (M * (2 * Q)))
      (input output : Fin (Nc ^ 2 - 1))
      (Rweak : ℝ) (hRweak : 1 ≤ Rweak)
      (hsmall :
        (branching : ℝ) * rho * Rweak ^ 10000 < 1),
      Summable (fun walk : CMP99AnchoredWalk
          (cmp99PhysicalPatchSuccessorSteps
            Dict.charts Dict.core Dict.enlarged
            physicalBondDist Rrange) left =>
        Rweak ^ (walk.active Dict.domainActive).card *
          ‖cmp116ComplexPhysicalOperatorCoefficient
            (walk.term
              (cmp99PhysicalPatchHead Dict.charts K
                Dict.enlarged Dict.core hc hmass hK)
              (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                Dict.enlarged Dict.core hc hmass hK))
            source target input output‖) ∧
      (∑' walk : CMP99AnchoredWalk
          (cmp99PhysicalPatchSuccessorSteps
            Dict.charts Dict.core Dict.enlarged
            physicalBondDist Rrange) left,
        Rweak ^ (walk.active Dict.domainActive).card *
          ‖cmp116ComplexPhysicalOperatorCoefficient
            (walk.term
              (cmp99PhysicalPatchHead Dict.charts K
                Dict.enlarged Dict.core hc hmass hK)
              (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                Dict.enlarged Dict.core hc hmass hK))
            source target input output‖) ≤
          ((Ahead *
              Real.exp (-(μ *
                (physicalBondDist target source : ℝ))) *
              Rweak ^ 10000) *
            (1 - (branching : ℝ) * rho * Rweak ^ 10000)⁻¹) := by
  dsimp only
  intro left source target input output Rweak hRweak hsmall
  let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
    (Label := Label) anchor hsourceRange
  let successors := cmp99PhysicalPatchSuccessorSteps
    Dict.charts Dict.core Dict.enlarged physicalBondDist Rrange
  let term : CMP99AnchoredWalk successors left →
      (PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
        PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc) :=
    fun walk => walk.term
      (cmp99PhysicalPatchHead Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
  let value : CMP99AnchoredWalk successors left → SUNLieCoord Nc :=
    fun walk => cmp99PhysicalAnchoredPatchWalkValue
      Dict.charts K Dict.enlarged Dict.core hc hmass hK source target
      (EuclideanSpace.single input (1 : ℝ)) walk
  let Ahead := cmp99PhysicalPatchHeadWeightedAmplitude c mass
    (cmp99PhysicalBondGeometricRowSum 4 σ)
    (cmp99PhysicalBondGeometricRowSum 4 ((κ - σ) - μ))
  let rho := cmp99PhysicalPatchContinuationWeightedAmplitude
    Cker κ Rrange c mass
    (cmp99PhysicalBondGeometricRowSum 4 σ)
    (cmp99PhysicalBondGeometricRowSum 4
      ((((κ - σ) - σ) - σ) - μ))
  let branching : ℕ :=
    Fintype.card Label * (625 * 626 * Δ ^ 1250)
  let A : ℝ :=
    Ahead * Real.exp (-(μ *
      (physicalBondDist target source : ℝ)))
  let Cert :=
    cmp99PhysicalPatchWeightedCertificate_of_geometricPhysicalData
      Dict.charts K Dict.enlarged Dict.core Dict.core_subset_enlarged
      hCker hc hmass hσ h3σκ hμ.le
      hgeomBase hgeomHead hgeomContinuation
      hrange hbound hK hNR htilt
  have hAhead : 0 ≤ Ahead := by
    exact (Cert.head left).1
  have hrho : 0 ≤ rho := by
    exact (Cert.continuation left).1
  have hA : 0 ≤ A := by
    exact mul_nonneg hAhead (Real.exp_nonneg _)
  have hbranch :
      ∀ current, (successors current).card ≤ branching := by
    intro current
    exact
      CMP99LabeledPhysicalChartDictionary.card_physicalSuccessorSteps_le_labeledSimpleDomainBound
        Dict Δ hΔ hΔ1 current
  have hvalue : ∀ walk : CMP99AnchoredWalk successors left,
      ‖value walk‖ ≤ A * rho ^ walk.1 := by
    intro walk
    have hfixed :=
      norm_cmp99PhysicalAnchoredPatchWalkValue_le_fixedRate
        Cert hμ source target (EuclideanSpace.single input (1 : ℝ)) walk
    simpa [value, A, Ahead, rho, EuclideanSpace.norm_single] using hfixed
  have hradialValue :
      Summable fun walk : CMP99AnchoredWalk successors left =>
        Rweak ^ (walk.active Dict.domainActive).card * ‖value walk‖ :=
    summable_cmp99AnchoredWalk_radialMajorant_of_term
      successors left Dict.domainActive value branching 10000
      A rho Rweak hbranch Dict.active_card_le hA hrho hRweak
      hsmall hvalue
  have hcoefficient : ∀ walk : CMP99AnchoredWalk successors left,
      ‖cmp116ComplexPhysicalOperatorCoefficient
          (term walk) source target input output‖ ≤ ‖value walk‖ := by
    intro walk
    simpa [term, value, cmp99PhysicalAnchoredPatchWalkValue] using
      (norm_cmp116ComplexPhysicalOperatorCoefficient_le_targetValue
        (term walk) source target input output)
  have hradialCoefficient :
      Summable fun walk : CMP99AnchoredWalk successors left =>
        Rweak ^ (walk.active Dict.domainActive).card *
          ‖cmp116ComplexPhysicalOperatorCoefficient
            (term walk) source target input output‖ := by
    apply Summable.of_nonneg_of_le
    · intro walk
      exact mul_nonneg (pow_nonneg (zero_le_one.trans hRweak) _)
        (norm_nonneg _)
    · intro walk
      exact mul_le_mul_of_nonneg_left (hcoefficient walk)
        (pow_nonneg (zero_le_one.trans hRweak) _)
    · exact hradialValue
  have hclosedValue :
      (∑' walk : CMP99AnchoredWalk successors left,
        Rweak ^ (walk.active Dict.domainActive).card * ‖value walk‖) ≤
        (A * Rweak ^ 10000) *
          (1 - (branching : ℝ) * rho * Rweak ^ 10000)⁻¹ :=
    tsum_cmp99AnchoredWalk_radialMajorant_of_term_le
      successors left Dict.domainActive value branching 10000
      A rho Rweak hbranch Dict.active_card_le hA hrho hRweak
      hsmall hvalue
  have hclosedCoefficient :
      (∑' walk : CMP99AnchoredWalk successors left,
        Rweak ^ (walk.active Dict.domainActive).card *
          ‖cmp116ComplexPhysicalOperatorCoefficient
            (term walk) source target input output‖) ≤
        (A * Rweak ^ 10000) *
          (1 - (branching : ℝ) * rho * Rweak ^ 10000)⁻¹ := by
    exact (Summable.tsum_le_tsum
      (fun walk => mul_le_mul_of_nonneg_left (hcoefficient walk)
        (pow_nonneg (zero_le_one.trans hRweak) _))
      hradialCoefficient hradialValue).trans hclosedValue
  exact ⟨hradialCoefficient, by
    simpa [A, Ahead, rho, branching, mul_assoc] using hclosedCoefficient⟩

/-- Source-specific complex Cauchy estimate with the boundary majorant reduced
to a closed geometric expression and fixed spatial decay.

Unlike the preceding operator-norm endpoint, this theorem constructs the
weighted-row certificate from the physical kernel, evaluates every walk at a
single source Lie basis vector and target bond, counts the literal
`Pi^4`/`sigma_0` active carrier, and sums the resulting geometric series.
The conclusion therefore retains `exp (-mu * physicalBondDist target source)`
and contains no unevaluated `tsum`. -/
theorem cmp116Eq214CauchyBoundaryBound_sourceSigmaZeroPi4PhysicalWalkKernel_fixedRate
    {Label : Type u} [Fintype Label] [DecidableEq Label]
    {M Q Nc Rrange NR : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q) (hsourceRange : Rrange + 1 ≤ 4 * M)
    (K : PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
      PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc)
    {Cker c mass κ σ μ : ℝ}
    (hCker : 0 ≤ Cker) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ) (hμ : 0 < μ)
    (hgeomBase :
      ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-σ) < 1)
    (hgeomHead :
      ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-((κ - σ) - μ)) < 1)
    (hgeomContinuation :
      ((2 ^ 4 : ℕ) : ℝ) *
        Real.exp (-((((κ - σ) - σ) - σ) - μ)) < 1)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist Rrange)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => Cker))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond 4 (M * (2 * Q)),
      (Finset.univ.filter
        (fun y => physicalBondDist x y ≤ Rrange)).card ≤ NR)
    (htilt :
      (Cker + |mass|) *
          (Real.exp (κ * (Rrange : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2)
    (Δ : ℕ) (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ) :
    let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
      (Label := Label) anchor hsourceRange
    let Ahead := cmp99PhysicalPatchHeadWeightedAmplitude c mass
      (cmp99PhysicalBondGeometricRowSum 4 σ)
      (cmp99PhysicalBondGeometricRowSum 4 ((κ - σ) - μ))
    let rho := cmp99PhysicalPatchContinuationWeightedAmplitude
      Cker κ Rrange c mass
      (cmp99PhysicalBondGeometricRowSum 4 σ)
      (cmp99PhysicalBondGeometricRowSum 4
        ((((κ - σ) - σ) - σ) - μ))
    let branching : ℕ :=
      Fintype.card Label * (625 * 626 * Δ ^ 1250)
    ∀ (left : ↥Dict.charts)
      {n : ℕ} (emb : Fin n ↪ FinBox 4 (2 * Q))
      (radius : Fin n → ℝ)
      (source target : PhysicalBond 4 (M * (2 * Q)))
      (input output : Fin (Nc ^ 2 - 1))
      (Rweak : ℝ) (hRweak : 1 ≤ Rweak)
      (hcap : ∀ i, 1 + radius i ≤ Rweak)
      (hsmall :
        (branching : ℝ) * rho * Rweak ^ 10000 < 1),
      CMP116Eq214CauchyBoundaryBound n radius
        (fun z => cmp116ComplexWeakenedRandomWalkSeries
          (fun walk : CMP99AnchoredWalk
              (cmp99PhysicalPatchSuccessorSteps
                Dict.charts Dict.core Dict.enlarged
                physicalBondDist Rrange) left =>
            walk.active Dict.domainActive)
          (fun walk => cmp116ComplexPhysicalOperatorCoefficient
            (walk.term
              (cmp99PhysicalPatchHead Dict.charts K
                Dict.enlarged Dict.core hc hmass hK)
              (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
                Dict.enlarged Dict.core hc hmass hK))
            source target input output)
          (cmp116ComplexWeakeningOfContour emb z))
        ((Ahead *
            Real.exp (-(μ *
              (physicalBondDist target source : ℝ))) *
            Rweak ^ 10000) *
          (1 - (branching : ℝ) * rho * Rweak ^ 10000)⁻¹) := by
  dsimp only
  intro left n emb radius source target input output
    Rweak hRweak hcap hsmall
  let Dict := cmp116SourceSigmaZeroPi4PhysicalChartDictionary
    (Label := Label) anchor hsourceRange
  let successors := cmp99PhysicalPatchSuccessorSteps
    Dict.charts Dict.core Dict.enlarged physicalBondDist Rrange
  let term : CMP99AnchoredWalk successors left →
      (PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
        PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc) :=
    fun walk => walk.term
      (cmp99PhysicalPatchHead Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation Dict.charts K
        Dict.enlarged Dict.core hc hmass hK)
  let value : CMP99AnchoredWalk successors left → SUNLieCoord Nc :=
    fun walk => cmp99PhysicalAnchoredPatchWalkValue
      Dict.charts K Dict.enlarged Dict.core hc hmass hK source target
      (EuclideanSpace.single input (1 : ℝ)) walk
  let Ahead := cmp99PhysicalPatchHeadWeightedAmplitude c mass
    (cmp99PhysicalBondGeometricRowSum 4 σ)
    (cmp99PhysicalBondGeometricRowSum 4 ((κ - σ) - μ))
  let rho := cmp99PhysicalPatchContinuationWeightedAmplitude
    Cker κ Rrange c mass
    (cmp99PhysicalBondGeometricRowSum 4 σ)
    (cmp99PhysicalBondGeometricRowSum 4
      ((((κ - σ) - σ) - σ) - μ))
  let branching : ℕ :=
    Fintype.card Label * (625 * 626 * Δ ^ 1250)
  let A : ℝ :=
    Ahead * Real.exp (-(μ *
      (physicalBondDist target source : ℝ)))
  let Cert :=
    cmp99PhysicalPatchWeightedCertificate_of_geometricPhysicalData
      Dict.charts K Dict.enlarged Dict.core Dict.core_subset_enlarged
      hCker hc hmass hσ h3σκ hμ.le
      hgeomBase hgeomHead hgeomContinuation
      hrange hbound hK hNR htilt
  have hAhead : 0 ≤ Ahead := by
    exact (Cert.head left).1
  have hrho : 0 ≤ rho := by
    exact (Cert.continuation left).1
  have hA : 0 ≤ A := by
    exact mul_nonneg hAhead (Real.exp_nonneg _)
  have hbranch :
      ∀ current, (successors current).card ≤ branching := by
    intro current
    exact
      CMP99LabeledPhysicalChartDictionary.card_physicalSuccessorSteps_le_labeledSimpleDomainBound
        Dict Δ hΔ hΔ1 current
  have hvalue : ∀ walk : CMP99AnchoredWalk successors left,
      ‖value walk‖ ≤ A * rho ^ walk.1 := by
    intro walk
    have hfixed :=
      norm_cmp99PhysicalAnchoredPatchWalkValue_le_fixedRate
        Cert hμ source target (EuclideanSpace.single input (1 : ℝ)) walk
    simpa [value, A, Ahead, rho, EuclideanSpace.norm_single] using hfixed
  have hradialValue :
      Summable fun walk : CMP99AnchoredWalk successors left =>
        Rweak ^ (walk.active Dict.domainActive).card * ‖value walk‖ :=
    summable_cmp99AnchoredWalk_radialMajorant_of_term
      successors left Dict.domainActive value branching 10000
      A rho Rweak hbranch Dict.active_card_le hA hrho hRweak
      hsmall hvalue
  have hcoefficient : ∀ walk : CMP99AnchoredWalk successors left,
      ‖cmp116ComplexPhysicalOperatorCoefficient
          (term walk) source target input output‖ ≤ ‖value walk‖ := by
    intro walk
    simpa [term, value, cmp99PhysicalAnchoredPatchWalkValue] using
      (norm_cmp116ComplexPhysicalOperatorCoefficient_le_targetValue
        (term walk) source target input output)
  have hradialCoefficient :
      Summable fun walk : CMP99AnchoredWalk successors left =>
        Rweak ^ (walk.active Dict.domainActive).card *
          ‖cmp116ComplexPhysicalOperatorCoefficient
            (term walk) source target input output‖ := by
    apply Summable.of_nonneg_of_le
    · intro walk
      exact mul_nonneg (pow_nonneg (zero_le_one.trans hRweak) _)
        (norm_nonneg _)
    · intro walk
      exact mul_le_mul_of_nonneg_left (hcoefficient walk)
        (pow_nonneg (zero_le_one.trans hRweak) _)
    · exact hradialValue
  have hclosedValue :
      (∑' walk : CMP99AnchoredWalk successors left,
        Rweak ^ (walk.active Dict.domainActive).card * ‖value walk‖) ≤
        (A * Rweak ^ 10000) *
          (1 - (branching : ℝ) * rho * Rweak ^ 10000)⁻¹ :=
    tsum_cmp99AnchoredWalk_radialMajorant_of_term_le
      successors left Dict.domainActive value branching 10000
      A rho Rweak hbranch Dict.active_card_le hA hrho hRweak
      hsmall hvalue
  have hclosedCoefficient :
      (∑' walk : CMP99AnchoredWalk successors left,
        Rweak ^ (walk.active Dict.domainActive).card *
          ‖cmp116ComplexPhysicalOperatorCoefficient
            (term walk) source target input output‖) ≤
        (A * Rweak ^ 10000) *
          (1 - (branching : ℝ) * rho * Rweak ^ 10000)⁻¹ := by
    exact (Summable.tsum_le_tsum
      (fun walk => mul_le_mul_of_nonneg_left (hcoefficient walk)
        (pow_nonneg (zero_le_one.trans hRweak) _))
      hradialCoefficient hradialValue).trans hclosedValue
  have hboundary :=
    cmp116Eq214CauchyBoundaryBound_of_complexWeakenedRandomWalkSeries
      emb radius
      (fun walk : CMP99AnchoredWalk successors left =>
        walk.active Dict.domainActive)
      (fun walk => cmp116ComplexPhysicalOperatorCoefficient
        (term walk) source target input output)
      Rweak hRweak hcap hradialCoefficient
  apply CMP116Eq214CauchyBoundaryBound.mono n radius _ _ hboundary
  simpa [A, Ahead, rho, branching, mul_assoc] using hclosedCoefficient

end

end YangMills.RG
