import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothHeterogeneousFactorWalkDecay

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousCoordinateSite
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousFineCoordinate
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousCoordinateDist
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousCoordinateDist_self
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousCoordinateDist_triangle
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousLabelWeightedRowAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousCoordinateLabelOperator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousCoordinateLabelOperator_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousCoordinateOperatorWalk_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousCoordinateOperatorWalk_exponential
