import YangMills.RG.BalabanCMP99SourceEq395HeadSupport

open YangMills.RG

#print axioms cmp99Eq395PhysicalHeadWeightedRowAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.finitePiLpTypedWeightedRowKernelBound_of_bilateral_finset_support
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalHead_apply_single_eq_zero_of_target
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalHead_apply_single_eq_zero_of_source
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalHead_apply_single_eq_zero_of_endpoint
#print axioms CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalHead_weightedRow
