import YangMills.RG.BalabanCMP102Eq80PhysicalMinimizerDomainLocalization

#print axioms YangMills.RG.cmp102Eq80SourcePi4PhysicalDomainLocalizedMinimizerIncrement
#print axioms YangMills.RG.cmp102Eq80SourcePi4PhysicalLocalizedMinimizerIncrement_eq_domainLocalized
#print axioms YangMills.RG.cmp102Eq80MinimizerIncrement_eq_sourcePi4PhysicalDomainLocalized
#print axioms YangMills.RG.tendsto_sum_cmp102Eq80SourcePi4PhysicalDomainLocalizedMinimizerIncrements
