import YangMills.RG.BalabanCMP99SourceFlatFullComplexPrecisionParticularSolution

/-!
PRE-VALIDATION: source is present, its `.olean` has not yet been materialized,
and the result has not yet been verified by the Lean compiler.
-/

#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_particularSolution_fixedCoarseFibre
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_particularSolution_eq_zero_of_coarseAlias_ne
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_fourierMode_eq_zero_of_coarseAlias_ne
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_particularSolution_eq_zero_of_coarseAlias_ne
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_particularSolution_fixedCoarseFibre
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionAction_particularSolution
