import YangMills.RG.BalabanCMP102Eq80CorrectedPhysicalMinimizerDomainLocalization

#print axioms YangMills.RG.cmp102Eq80CorrectedSourcePi4PhysicalDomainLocalizedMinimizerIncrement
#print axioms YangMills.RG.tendsto_sum_cmp102Eq80CorrectedSourcePi4PhysicalDomainLocalizedMinimizerIncrements
