import YangMills.RG.BalabanCMP116SourcePi4MixedDerivativeDomainSupport

#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainLayerCoefficient_eq_zero_of_root_not_mem
#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainLayerCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainCoefficient_eq_zero_of_root_not_mem
#print axioms YangMills.RG.cmp116SourcePi4MixedDerivativeDomainCoefficient_eq_zero_of_not_walkConnected
