/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116InteractingCombesThomas

/-!
# Source package for the interacting CMP116 precision

**PRE-VALIDATION.** The source is present, but its `.olean` has not yet been
materialized and no declaration in this module is compiler-verified yet.

This package fixes the precision used by the combined CMP102/CMP116 source to
the literal Wilson-plus-gauge Hessian.  Its finite range, surviving coercivity,
exact inverse, and Combes--Thomas endpoint are derived from the already proved
physical theorems.

The flat Hodge--Poincare estimate, the small-background condition, and the
strict defect budget remain explicit source hypotheses.  They are not renamed
terminal estimates.
-/

namespace YangMills.RG

open scoped RealInnerProductSpace

noncomputable section

variable {M Q Nc : ℕ}
  [NeZero M] [NeZero Q] [NeZero Nc]
  [NeZero (2 * Q)] [NeZero (M * (2 * Q))]

/-- Source-facing hypotheses from which the literal interacting precision and
covariance are generated. -/
structure CMP116InteractingPhysicalPrecisionSource
    (U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc) where
  a : ℝ
  CP : ℝ
  backgroundEpsilon : ℝ
  a_pos : 0 < a
  poincare : FlatGaugeHodgePoincare 4 M (2 * Q) Nc
    (matrixSUNAdjointModel Nc) CP
  backgroundEpsilon_nonneg : 0 ≤ backgroundEpsilon
  smallBackground : PhysicalWilsonSmallBackground U backgroundEpsilon
  defectBudget :
    cmp116ConcreteInteractingWilsonGaugeDefectBudget
        4 Nc backgroundEpsilon <
      min 1 a / CP

namespace CMP116InteractingPhysicalPrecisionSource

variable {U : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc}

/-- The exact range of the interacting precision in fundamental-bond units. -/
def sourceRange
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) : ℕ :=
  3 * M

/-- The coercivity left after the complete Wilson/gauge defect. -/
def coercivityConstant
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) : ℝ :=
  min 1 X.a / X.CP -
    cmp116ConcreteInteractingWilsonGaugeDefectBudget
      4 Nc X.backgroundEpsilon

/-- Literal interacting Wilson-plus-gauge precision. -/
noncomputable def precision
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
      PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc :=
  interactingPhysicalBasePrecisionCLM U X.a

/-- Exact covariance generated by the surviving coercivity. -/
noncomputable def covariance
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
      PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc :=
  interactingPhysicalCovarianceCLM U X.a_pos X.poincare
    X.backgroundEpsilon_nonneg X.smallBackground X.defectBudget

theorem sourceRange_bound
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U)
    (hM : 1 ≤ M) :
    X.sourceRange + 1 ≤ 4 * M := by
  simp only [sourceRange]
  omega

theorem finiteRange
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    PhysicalCovarianceFiniteRange X.precision physicalBondDist X.sourceRange := by
  simpa [precision, sourceRange] using
    (interactingPhysicalBasePrecisionCLM_finiteRange U X.a)

theorem coercivity_pos
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    0 < X.coercivityConstant := by
  exact sub_pos.mpr X.defectBudget

theorem coercive
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    IsCoerciveCLM X.precision X.coercivityConstant := by
  simpa [precision, coercivityConstant] using
    (isCoerciveCLM_interactingPhysicalBasePrecision
      U X.a_pos X.poincare X.backgroundEpsilon_nonneg X.smallBackground)

theorem precision_comp_covariance
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    X.precision.comp X.covariance =
      ContinuousLinearMap.id ℝ
        (PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc) := by
  simpa [precision, covariance] using
    (interactingPhysicalBasePrecision_comp_covariance
      U X.a_pos X.poincare X.backgroundEpsilon_nonneg
        X.smallBackground X.defectBudget)

theorem exists_covariance_CT
    (X : CMP116InteractingPhysicalPrecisionSource (M := M) (Q := Q) U) :
    ∃ theta : ℝ, 0 < theta ∧
      PhysicalCovarianceExponentialKernelBound
        X.covariance physicalBondDist
        (2 / X.coercivityConstant) theta := by
  simpa [covariance, coercivityConstant] using
    (exists_interactingPhysicalCovariance_CT
      U X.a_pos X.poincare X.backgroundEpsilon_nonneg
        X.smallBackground X.defectBudget)

end CMP116InteractingPhysicalPrecisionSource

end

end YangMills.RG
