import YangMills.RG.BalabanCMP102Eq80SourcePi4SecondFieldDerivativeBound

#print axioms YangMills.RG.norm_cmp102PartialPropagatorJetSecondFieldDerivative_le
#print axioms YangMills.RG.cmp102Eq80SourcePi4DomainDirectionMajorant_nonneg
#print axioms YangMills.RG.norm_cmp102Eq80SourcePi4FaaDiBrunoDomainChoiceSecondFieldDerivativeAt_le
#print axioms YangMills.RG.norm_cmp102Eq80SourcePi4FaaDiBrunoDomainCoefficientSecondFieldDerivativeAt_le
