import YangMills.RG.BalabanCMP98SourceNearLogDomain

#print axioms YangMills.RG.cmp98SourceContourDisplacementBudget_nonneg
#print axioms YangMills.RG.cmp98SourceContourQuadraticBudget_nonneg
#print axioms YangMills.RG.cmp98UbarAmbientDeviationMatrix_physicalLine_lt_one_of_third
#print axioms YangMills.RG.norm_nearLog_cmp98UbarAmbientDeviationMatrix_physicalLine_sub_zero_le
#print axioms YangMills.RG.norm_nearLog_cmp98UbarAmbientDeviationMatrix_physicalLine_sub_zero_sub_linear_le
#print axioms YangMills.RG.norm_cmp98UbarLogAverage_physicalLine_sub_zero_sub_linear_le
#print axioms YangMills.RG.norm_cmp98UbarLogAverage_physicalLine_sub_zero_le
#print axioms YangMills.RG.norm_cmp98UbarLogAverage_zero_le
#print axioms YangMills.RG.norm_cmp98UbarLogAverage_physicalLine_le_sourceRadius
#print axioms YangMills.RG.norm_cmp98UbarExpAverage_physicalLine_sub_zero_sub_linear_le
#print axioms YangMills.RG.analyticAt_cmp98UbarLogAverage_physicalLine_of_sourceBudget
#print axioms YangMills.RG.analyticAt_cmp98UbarExpAverage_physicalLine_of_sourceBudget
