import YangMills.RG.BalabanCMP99SourceGeneratedSectionCHeadFactor

#print axioms YangMills.RG.cmp99SourceGeneratedSectionCHeadWeightedRowAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCSourceHeadFactorCoordinates
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedSectionCSourceHeadFactorCoordinates_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCSourceHeadFactorCertificate
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCSourceHeadFactorCoordinates_exponential
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCSourceHeadFactorCoordinates_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadFactorCoordinates
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadFactorCoordinates_weightedRow
