import YangMills.RG.BalabanCMP116Eq226ConditionedPhysicalContourActivityBoundary

#print axioms YangMills.RG.globalEval_cmp116Eq226ConditionedPhysicalContourActivity
#print axioms YangMills.RG.cmp116Eq226ConditionedPhysicalContourResummation_termwise
#print axioms YangMills.RG.cmp116Eq226ConditionedPhysicalContour_activityTermwiseScaleBoundary
