import YangMills.RG.BalabanCMP99SourceEq395LocalizedAtomNorm

#print axioms YangMills.RG.norm_cmp99Eq395_extend_comp_comp_restrict_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalSmoothMultiplier_le_one
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalSourceCharacteristic_le_one
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalMiddle_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalCovariance_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalRAtom_second_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_cmp99Eq395PhysicalRAtom_third_le
