import YangMills.RG.BalabanCMP99SourceSeparatedSourceFlowFlatPhysicalPointSourceOwnerBound

#print axioms YangMills.RG.norm_tsum_cmp99SourceSeparatedSourceFlowFlatPhysicalGreen_zeroResidue_le_owner
#print axioms YangMills.RG.norm_cmp99SourceSeparatedSourceFlowFlatPhysicalGreenQprimeStar_pointSource_apply_le_owner
