/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116SourcePi4FullComplexR2Norm
import YangMills.RG.BalabanCMP116SourcePi4FullComplexContourDefectTranspose

/-!
# Physical column bound for the source-complex `R2`

The transpose resolvent estimate is connected here to the explicit source
contour defect.  The matrix-valued relative-smallness premise disappears;
the only condition is the column analogue of the physical Neumann scalar
inequality.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

private abbrev PhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

/-- Explicit transpose-relative contour defect bound. -/
noncomputable def cmp116SourcePi4PhysicalComplexTransposeRelativeDefectBound
    {M Q Nc : ℕ} [NeZero M] [NeZero Q]
    (K : PhysicalEndomorphism M Q Nc)
    (Delta : ℕ) (Ahead rho rate radius Rweak : ℝ) : ℝ :=
  ‖(cmp116PhysicalEndomorphismComplexMatrix K).transpose‖ *
    cmp116SourcePi4PhysicalComplexContourDefectBound
      Nc Delta Ahead rho rate radius Rweak

/-- Explicit source `R2` column budget generated by the transpose-relative
Neumann series. -/
noncomputable def cmp116SourcePi4PhysicalComplexR2ColumnBound
    {M Q Nc : ℕ} [NeZero M] [NeZero Q]
    (K : PhysicalEndomorphism M Q Nc)
    (Delta : ℕ) (Ahead rho rate radius Rweak : ℝ) : ℝ :=
  let precisionColumn :=
    ‖(cmp116PhysicalEndomorphismComplexMatrix K).transpose‖
  let covarianceDefect :=
    cmp116SourcePi4PhysicalComplexContourDefectBound
      Nc Delta Ahead rho rate radius Rweak
  let relativeDefect := precisionColumn * covarianceDefect
  ((1 - relativeDefect)⁻¹ * precisionColumn) *
    covarianceDefect * precisionColumn

set_option maxHeartbeats 6000000 in
/-- The literal source-complex `R2` has a volume-uniform column bound
constructed from the physical contour certificate. -/
theorem linfty_opNorm_transpose_cmp116SourcePi4FullComplexR2Matrix_le_physical
    {M Q Nc R Delta : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hfiniteRange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    {Ahead rho rate radius Rweak : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
      PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hDelta : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Delta)
    (hDelta1 : 1 ≤ Delta)
    (sigma : FinBox 4 (2 * Q) → ℂ)
    (hradius : 0 ≤ radius) (hRweak : 1 ≤ Rweak)
    (hdiff : ∀ d, ‖sigma d - 1‖ ≤ radius)
    (hcap : ∀ d, ‖sigma d‖ ≤ Rweak)
    (hseries :
      ‖cmp116SourcePi4ComplexContourRatio Delta rho Rweak‖ < 1)
    (hneumannTranspose :
      cmp116SourcePi4PhysicalComplexTransposeRelativeDefectBound
        K Delta Ahead rho rate radius Rweak < 1) :
    ‖(cmp116SourcePi4FullComplexR2Matrix
        (R := R) anchor K hc hmass hK sigma).transpose‖ ≤
      cmp116SourcePi4PhysicalComplexR2ColumnBound
        K Delta Ahead rho rate radius Rweak := by
  let covarianceDefect :=
    cmp116SourcePi4FullComplexWeakenedCovarianceMatrix
          (R := R) anchor K hc hmass hK sigma -
      cmp116SourcePi4FullComplexWeakenedCovarianceMatrix
          (R := R) anchor K hc hmass hK (fun _ => 1)
  let covarianceDefectBound :=
    cmp116SourcePi4PhysicalComplexContourDefectBound
      Nc Delta Ahead rho rate radius Rweak
  let precisionColumn :=
    ‖(cmp116PhysicalEndomorphismComplexMatrix K).transpose‖
  let relativeDefect :=
    ‖(cmp116PhysicalEndomorphismComplexMatrix K).transpose *
      covarianceDefect.transpose‖
  let relativeDefectBound := precisionColumn * covarianceDefectBound
  have hcovarianceDefect :
      ‖covarianceDefect.transpose‖ ≤ covarianceDefectBound := by
    simpa [covarianceDefect, covarianceDefectBound,
      cmp116SourcePi4PhysicalComplexContourDefectBound, inv_pow] using
      (linfty_opNorm_transpose_cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_sub_one_le
        anchor K hc hmass hK hAhead hrho hrate hgeom Cert htri
        hsourceRange hDelta hDelta1 sigma hradius hRweak hdiff hcap hseries)
  have hrelative : relativeDefect ≤ relativeDefectBound := by
    calc
      relativeDefect ≤ precisionColumn * ‖covarianceDefect.transpose‖ := by
        exact Matrix.linfty_opNorm_mul _ _
      _ ≤ precisionColumn * covarianceDefectBound :=
        mul_le_mul_of_nonneg_left hcovarianceDefect (norm_nonneg _)
  have hrelativeSmall : relativeDefect < 1 :=
    hrelative.trans_lt (by
      simpa [relativeDefectBound, precisionColumn, covarianceDefectBound,
        cmp116SourcePi4PhysicalComplexTransposeRelativeDefectBound]
        using hneumannTranspose)
  have hraw :=
    linfty_opNorm_transpose_cmp116SourcePi4FullComplexR2Matrix_le
      anchor K hsourceRange hfiniteRange hc hmass hK hD sigma
      (by simpa [relativeDefect, covarianceDefect] using hrelativeSmall)
  have hboundSmall : relativeDefectBound < 1 := by
    simpa [relativeDefectBound, precisionColumn, covarianceDefectBound,
      cmp116SourcePi4PhysicalComplexTransposeRelativeDefectBound]
      using hneumannTranspose
  have hinv :
      (1 - relativeDefect)⁻¹ ≤ (1 - relativeDefectBound)⁻¹ := by
    exact
      (inv_le_inv₀ (by linarith [hrelativeSmall])
        (by linarith [hboundSmall])).2 (by linarith)
  have hprecisionColumn : 0 ≤ precisionColumn := by
    exact norm_nonneg _
  have hinvBound : 0 ≤ (1 - relativeDefectBound)⁻¹ := by
    exact inv_nonneg.mpr (by linarith [hboundSmall])
  change ‖(cmp116SourcePi4FullComplexR2Matrix
      (R := R) anchor K hc hmass hK sigma).transpose‖ ≤
    ((1 - relativeDefectBound)⁻¹ * precisionColumn) *
      covarianceDefectBound * precisionColumn
  calc
    ‖(cmp116SourcePi4FullComplexR2Matrix
        (R := R) anchor K hc hmass hK sigma).transpose‖ ≤
        ((1 - relativeDefect)⁻¹ * precisionColumn) *
          ‖covarianceDefect.transpose‖ * precisionColumn := by
      simpa [relativeDefect, covarianceDefect, precisionColumn] using hraw
    _ ≤ ((1 - relativeDefectBound)⁻¹ * precisionColumn) *
          covarianceDefectBound * precisionColumn := by
      apply mul_le_mul_of_nonneg_right _ hprecisionColumn
      apply mul_le_mul
      · exact mul_le_mul_of_nonneg_right hinv hprecisionColumn
      · exact hcovarianceDefect
      · exact norm_nonneg _
      · exact mul_nonneg hinvBound hprecisionColumn

end

end YangMills.RG
