/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceGeneratedSectionCHeadedTypedWalk
import YangMills.RG.BalabanCMP99SourceGeneratedSectionCSmoothHeterogeneousFactorWalkDecay
import YangMills.RG.BalabanCMP99SourceGeneratedTerminalCoordinates

/-!
# The explicitly displayed CMP99 Section C subalphabet

Pages 412--415 of CMP99 display a covariance head, the cut and commutator
coarse factors, and the basic and basic-adjoint heterogeneous factors.  The
paper then says "etc."; consequently this file deliberately constructs only
the subalphabet generated by those five proved species.  It does not claim
that the list is exhaustive or that its walk sum is the complete propagator.

The main point is compositional.  The coarse operators are transported into
the same generated Hilbert bundle already used by the heterogeneous factors.
The transport is along the proved equality between the terminal space of the
literal Q-prime tower and the physical coarse field, so it preserves operator
norm exactly.  Every well-typed word in the displayed subalphabet therefore
evaluates to a literal ordered product with a source-derived product bound.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator RealInnerProductSpace

noncomputable section

universe v

variable {M Nc Q j : ℕ} [NeZero M] [NeZero Nc] [NeZero Q]
variable {cell : FinBox 4 Q}
variable {ScaleSite : Fin (j + 2) → Type v}
variable [∀ r, DecidableEq (ScaleSite r)]
variable {Scaled : CMP99SourceScaledStratification
  (FinBox 4 (2 * Q)) (j + 2) ScaleSite}
variable {dist : FinBox 4 (2 * Q) → FinBox 4 (2 * Q) → ℕ}
variable {gap : Fin (j + 1) → ℕ}

namespace CMP99SourceDependentOmegaGeometry

/-- The five source species explicitly displayed on CMP99 pp. 412--415.
`coarse` contains the head, cut and commutator labels; `heterogeneous`
contains the basic and basic-adjoint labels.  This is intentionally a
subalphabet, not an exhaustive reconstruction of the paper's "etc.". -/
inductive CMP99DisplayedSectionCSubalphabet (j : ℕ) :
    CMP99SectionCHeterogeneousIndex j →
      CMP99SectionCHeterogeneousIndex j → Type where
  | coarse {r s : Fin (j + 2)} (label : CMP99SectionCHeadedTypedLabel j r s) :
      CMP99DisplayedSectionCSubalphabet j (r, .coarse) (s, .coarse)
  | heterogeneous {r s : CMP99SectionCHeterogeneousIndex j}
      (label : GeneratedSectionCHeterogeneousLabel j r s) :
      CMP99DisplayedSectionCSubalphabet j r s

set_option maxRecDepth 3000
set_option maxHeartbeats 6000000
set_option synthInstance.maxHeartbeats 200000

/-- At a coarse heterogeneous index, the generated tower really ends on the
physical coarse Hilbert bundle at that scale. -/
theorem generatedSectionCHeterogeneousSpace_coarse_eq
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ) (spacing epsilon : ℝ)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (s : Fin (j + 2)) :
    D.generatedSectionCHeterogeneousSpace hpi5 hM depth spacing epsilon
        background budget fineSmall (s, .coarse) =
      cmp99SourcePhysicalTerminalHilbertSpace Nc
        (D.operatorCoarseRegion hpi5 s) := by
  simpa [generatedSectionCHeterogeneousSpace] using
    (cmp99SourceIteratedLift_weightedQprimeTower_terminalSpace_eq
      (Nc := Nc) (M := M) (show 2 ≤ 4 by norm_num) hM
      (matrixSUNAdjointModel Nc) (D.operatorCoarseRegion hpi5 s) (depth + 1)
      spacing epsilon background budget.toRadiusChain fineSmall)

/-- Norm amplitude of the cut and commutator species on the coarse carrier. -/
noncomputable def generatedCMP95DisplayedSectionCSourceLabelNormAmplitude
    (P : CMP95SourceSmoothPartitionProfile)
    (M depth : ℕ) (spacing epsilon : ℝ)
    {r s : Fin (j + 2)} :
    CMP99SectionCTypedFactorLabel j (fun _ _ => Empty) r s → ℝ
  | .cut _ => cmp99SourceGeneratedPhysicalCoarseRightFactorNormBound
      M depth spacing epsilon
  | .commutator _ => cmp99SourceGeneratedSmoothSectionCFactorNormBound
      P M depth spacing epsilon
  | .other alpha => nomatch alpha

/-- Norm amplitude of the three explicitly displayed coarse species. -/
noncomputable def generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude
    (P : CMP95SourceSmoothPartitionProfile)
    (M depth : ℕ) (spacing epsilon : ℝ)
    {r s : Fin (j + 2)} : CMP99SectionCHeadedTypedLabel j r s → ℝ
  | .displayed label =>
      generatedCMP95DisplayedSectionCSourceLabelNormAmplitude
        P M depth spacing epsilon label
  | .head _ =>
      cmp99SourceGeneratedPhysicalCoarseCovarianceNormBound
        M depth spacing epsilon

/-- Norm amplitude attached to each member of the displayed subalphabet. -/
noncomputable def generatedCMP95DisplayedSectionCLabelNormAmplitude
    (P : CMP95SourceSmoothPartitionProfile)
    (M depth : ℕ) (spacing epsilon : ℝ)
    {r s : CMP99SectionCHeterogeneousIndex j} :
    CMP99DisplayedSectionCSubalphabet j r s → ℝ
  | .coarse label =>
      generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude
        P M depth spacing epsilon label
  | .heterogeneous label =>
      generatedCMP95SectionCHeterogeneousLabelNormAmplitude
        P M depth spacing epsilon label

/-- Literal interpretation of all five displayed species in one generated
Hilbert family.  Coarse arrows are transported from the physical coarse
bundle into the equal terminal bundle of the Q-prime tower. -/
noncomputable def generatedCMP95DisplayedSectionCLabelOperator
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    {r s : CMP99SectionCHeterogeneousIndex j} :
    CMP99DisplayedSectionCSubalphabet j r s →
      DependentBundledHilbertArrow
        (D.generatedSectionCHeterogeneousSpace hpi5 hM depth spacing epsilon
          background budget fineSmall) r s := by
  intro label
  cases label with
  | @coarse r s old =>
      exact cmp99SourceTerminalCLMTransport
        (D.generatedSectionCHeterogeneousSpace_coarse_eq hpi5 hM depth
          spacing epsilon background budget fineSmall r).symm
        (D.generatedSectionCHeterogeneousSpace_coarse_eq hpi5 hM depth
          spacing epsilon background budget fineSmall s).symm
        (D.generatedCMP95SectionCHeadedLabelOperator P hpi5 hM depth hspacing
          background budget fineSmall hsmall old)
  | heterogeneous old =>
      exact D.generatedCMP95SectionCHeterogeneousLabelOperator P hpi5 hM depth
        hspacing background budget fineSmall hsmall old

/-- The three physical coarse labels satisfy their corresponding literal norm
budgets before transport into the common heterogeneous family. -/
theorem norm_generatedCMP95DisplayedSectionCCoarseLabelOperator_le
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    {r s : Fin (j + 2)} (label : CMP99SectionCHeadedTypedLabel j r s) :
    ‖D.generatedCMP95SectionCHeadedLabelOperator P hpi5 hM depth hspacing
      background budget fineSmall hsmall label‖ ≤
      generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude
        P M depth spacing epsilon label := by
  cases label with
  | displayed old =>
      cases old with
      | cut k =>
          simpa [generatedCMP95SectionCHeadedLabelOperator,
            generatedCMP95SectionCSourceLabelOperator,
            generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude,
            generatedCMP95DisplayedSectionCSourceLabelNormAmplitude] using
            D.norm_generatedPhysicalCoarseSectionCCutFactorCoordinates_le
              hpi5 k
              (D.generatedSectionCSourceTransitionCutData
                (cmp95SourcePeriodicCoarseSquarePartition P Q) hpi5 k)
              hM depth hspacing background budget fineSmall hsmall
      | commutator =>
          simpa [generatedCMP95SectionCHeadedLabelOperator,
            generatedCMP95SectionCSourceLabelOperator,
            generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude,
            generatedCMP95DisplayedSectionCSourceLabelNormAmplitude] using
            D.norm_generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_le
              P hpi5 r hM depth hspacing background budget fineSmall hsmall
      | other alpha => exact Empty.elim alpha
  | head =>
      simpa [generatedCMP95SectionCHeadedLabelOperator,
        generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude] using
        D.norm_generatedSectionCSourceHeadFactorCoordinates_le
          (cmp95SourcePeriodicCoarseSquarePartition P Q) hpi5 r hM depth
          hspacing background budget fineSmall hsmall

/-- Every displayed factor has its literal volume-independent source norm
bound after the isometric terminal-space transport. -/
theorem norm_generatedCMP95DisplayedSectionCLabelOperator_le
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    {r s : CMP99SectionCHeterogeneousIndex j}
    (label : CMP99DisplayedSectionCSubalphabet j r s) :
    ‖D.generatedCMP95DisplayedSectionCLabelOperator P hpi5 hM depth hspacing
      background budget fineSmall hsmall label‖ ≤
      generatedCMP95DisplayedSectionCLabelNormAmplitude
        P M depth spacing epsilon label := by
  cases label with
  | coarse old =>
      simpa [generatedCMP95DisplayedSectionCLabelOperator,
        generatedCMP95DisplayedSectionCLabelNormAmplitude,
        norm_cmp99SourceTerminalCLMTransport] using
        D.norm_generatedCMP95DisplayedSectionCCoarseLabelOperator_le P hpi5 hM
          depth hspacing background budget fineSmall hsmall old
  | heterogeneous old =>
      simpa [generatedCMP95DisplayedSectionCLabelOperator,
        generatedCMP95DisplayedSectionCLabelNormAmplitude] using
        D.norm_generatedCMP95SectionCHeterogeneousLabelOperator_le P hpi5 hM
          depth hspacing background budget fineSmall hsmall old

/-- Every well-typed word in the five displayed source species evaluates to
the literal ordered operator product and is bounded by the ordered product of
the five source-derived amplitudes. -/
theorem norm_generatedCMP95DisplayedSectionCOperatorWalk_le
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    {r s : CMP99SectionCHeterogeneousIndex j}
    (walk : DependentArrowWalk (CMP99DisplayedSectionCSubalphabet j) r s) :
    ‖dependentBundledHilbertWalkOperator
      (D.generatedSectionCHeterogeneousSpace hpi5 hM depth spacing epsilon
        background budget fineSmall)
      (walk.map (D.generatedCMP95DisplayedSectionCLabelOperator P hpi5 hM
        depth hspacing background budget fineSmall hsmall))‖ ≤
      walk.amplitude
        (generatedCMP95DisplayedSectionCLabelNormAmplitude
          P M depth spacing epsilon) := by
  apply norm_dependentBundledHilbertWalkOperator_map_le
  · intro a b label
    exact (norm_nonneg
      (D.generatedCMP95DisplayedSectionCLabelOperator P hpi5 hM depth
        hspacing background budget fineSmall hsmall label)).trans
      (D.norm_generatedCMP95DisplayedSectionCLabelOperator_le P hpi5 hM depth
        hspacing background budget fineSmall hsmall label)
  · exact fun label =>
      D.norm_generatedCMP95DisplayedSectionCLabelOperator_le P hpi5 hM depth
        hspacing background budget fineSmall hsmall label

end CMP99SourceDependentOmegaGeometry

end
end YangMills.RG
