import YangMills.RG.BalabanCMP99SourceEq395ThirdBoundary

#print axioms YangMills.RG.cmp99Eq395SampledCutoff_value_eq_one_of_mem_baseCell
#print axioms YangMills.RG.cmp99Eq395SampledCutoff_value_eq_piCharacteristic
#print axioms YangMills.RG.cmp99Eq395PhysicalSmoothMultiplier_sq_eq_self
#print axioms YangMills.RG.cmp99Eq395PhysicalSmoothMultiplier_eq_sourceCharacteristic
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_eq_global_sub_regional
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_eq_escape_add_interiorMismatch
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_eq_middleGap_add_commutator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_single_apply
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedLeftDefect_single_apply_ite
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedRAtom_eq_cutoff_sub_global_head
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedRAtom_eq_neg_global_regional_gap_comp_tail
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGroupedRAtom_eq_neg_middleGap_commutator_comp_tail
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalThirdLeft_single_apply_eq_zero_of_same_side
