import YangMills.RG.BalabanCMP116SourcePi4RealMixedCovarianceVertexInterpolation

#print axioms YangMills.RG.cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealMixedCovariance_eq
#print axioms YangMills.RG.cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealMixedCovariance_update_eq
#print axioms YangMills.RG.hasDerivAt_cmp116FiniteMultiaffineInterpolation_sourcePi4FullRealMixedCovariance
