import YangMills.RG.BalabanCMP102PhysicalBackgroundCorrectionLipschitz

#print axioms YangMills.RG.cmp98SourceFieldSupNorm_physicalHShift_sub_le
#print axioms YangMills.RG.cmp102PhysicalBackgroundCorrectionSupNorm_sub_le
