import YangMills.RG.BalabanCMP116SourcePhysicalBondField
import YangMills.RG.BalabanCMP116SourceRestrictedPhysicalContourDensity

namespace YangMills.RG

noncomputable section

private abbrev DirectPhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

namespace CMP116Eq214PhysicalContourDensity

/-- Private neutral carrier used only to assemble every public field from its
literal source producer.  No theorem exposes this seed as physical data. -/
private def directSourceSeed
    {nDelta nY M Q Nc : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    {Site : Type*} {Psi Phi : Site → Type*}
    (spectatorSupport fluctuationSupport : Finset Site)
    (deltaRadius : Fin nDelta → ℝ) (yRadius : Fin nY → ℝ) :
    CMP116Eq214PhysicalContourDensity nDelta nY
      (PhysicalBond 4 (M * (2 * Q))) Site Psi Phi
      (SUNLieCoord Nc) (Nc ^ 2 - 1) where
  spectatorSupport := spectatorSupport
  fluctuationSupport := fluctuationSupport
  deltaRadius := deltaRadius
  yRadius := yRadius
  referenceRoot := 0
  baseGamma := fun _ _ => 0
  contourGamma := fun _ _ _ _ => 0
  baseCovariance := fun _ _ => 1
  contourCovariance := fun _ _ _ _ => 1
  basePrecision := fun _ _ => 1
  contourPrecision := fun _ _ _ _ => 1
  determinantDensity := fun _ _ _ _ => 1
  potential := fun _ _ _ _ _ => 0
  bondField := fun _ _ => 0
  threshold := 0
  contourGamma_zero := by simp
  contourCovariance_zero := by simp
  contourPrecision_zero := by simp
  determinantDensity_zero := by simp
  determinantDensity_sq_mul_basePrecision_det := by simp
  potential_zero := by simp

/-- Non-circular assembly constructor for the restricted physical CMP116
contour density.

The private neutral carrier supplies only the dependent record shell.  The
returned record installs, in order, the supplied physical quadratic/residual
families, the literal bond field and cutoff threshold, and the complete
restricted physical complex Gaussian generated by the patched-walk contour
estimate.  No already inhabited contour density is an argument.  This
constructor measures and removes assembly circularity; source faithfulness of
the potential still requires the indexed equation-(80) family adapter. -/
def ofSourcePi4RestrictedPhysicalContour
    {nDelta nY M Q Nc R Δ L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero L] [NeZero lieDim]
    {Site : Type*} {Psi Phi : Site → Type*}
    (spectatorSupport fluctuationSupport : Finset Site)
    (deltaRadius : Fin nDelta → ℝ) (yRadius : Fin nY → ℝ)
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (D : Finset (Fin nY))
    (quadratic :
      (Fin nDelta → ℂ) →
      RestrictedField spectatorSupport Psi →
      RestrictedField fluctuationSupport Phi →
      Fin nY → PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →
        DirectPhysicalEndomorphism M Q Nc)
    (remainder :
      (Fin nDelta → ℂ) →
      RestrictedField spectatorSupport Psi →
      RestrictedField fluctuationSupport Phi →
      Fin nY → PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ)
    (threshold : ℝ)
    (anchor : FinBox 4 Q)
    (contourCarrier : Finset (FinBox 4 (2 * Q)))
    (hcarrier : contourCarrier ⊆ cmp116SourceSigmaZero anchor)
    (e : Fin nDelta ≃ ↥contourCarrier)
    (Z0 : Finset (FinBox 4 (2 * Q)))
    (K root : DirectPhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hfiniteRange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    {Ahead rho rate radius : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
      PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (hradius : 0 ≤ radius)
    (hradiusCap : ∀ i, 1 + deltaRadius i ≤ radius)
    (hseries :
      ‖cmp116SourcePi4ComplexContourRatio Δ rho (1 + radius)‖ < 1)
    (hneumann :
      (@norm
        (Matrix
          (CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc)
          (CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc) ℂ)
        Matrix.linftyOpNormedRing.toNorm
        (cmp116PhysicalEndomorphismComplexMatrix K)) *
        cmp116SourcePi4PhysicalComplexContourDefectBound
          Nc Δ Ahead rho rate radius (1 + radius) < 1) :
    CMP116Eq214PhysicalContourDensity nDelta nY
      (PhysicalBond 4 (M * (2 * Q))) Site Psi Phi
      (SUNLieCoord Nc) (Nc ^ 2 - 1) :=
  let C0 :=
    directSourceSeed spectatorSupport fluctuationSupport deltaRadius yRadius
  let Cpotential :=
    C0.withSourcePhysicalComplexTauPotential
      Dict D quadratic remainder Z0
  let Cphysical := Cpotential.withSourcePhysicalBondField threshold
  Cphysical.withSourcePi4RestrictedComplexGaussianOfPhysicalContour
    anchor contourCarrier hcarrier e Z0 K root
    hsourceRange hfiniteRange hc hmass hK hD
    hAhead hrho hrate hgeom Cert htri hΔ hΔ1
    hradius hradiusCap hseries hneumann

end CMP116Eq214PhysicalContourDensity

end

end YangMills.RG
