import YangMills.RG.BalabanCMP99SourceRegionTransition

namespace YangMills.RG

#print axioms cmp99OmegaTransitionRestriction
#print axioms cmp99OmegaTransitionExtension
#print axioms cmp99OmegaTransition_region_subset
#print axioms cmp99OmegaTransitionRestriction_comp_extension
#print axioms norm_cmp99OmegaTransitionExtension
#print axioms cmp99TypedPrecisionDefect
#print axioms typedGreen_transition_resolvent
#print axioms cmp99OmegaSourcePhysicalOneStepGreen_transition_resolvent

end YangMills.RG
