import YangMills.RG.BalabanCMP102Eq80CorrectedPhysicalBackgroundDependentRadial

#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_eq_sub_V0
#print axioms YangMills.RG.contDiff_two_cmp102Eq80CorrectedPhysicalBackgroundDependentPotential
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_zero
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_hasFDerivAt_zero
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentRadialOperator
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_eq_radial
