/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116Eq214PhysicalContourInnerDensity
import YangMills.RG.BalabanCMP116Eq223CovarianceOpNorm

/-!
# Canonical real source of the complex `R3` contour factor

The inner Gaussian source is not arbitrary: it is the negative real part of
the literal complex `R3` matrix applied to the outer field.  This module
records that identity and its immediate `L2` energy bound.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

namespace CMP116Eq214PhysicalContourDensity

variable {nDelta nY lieDim : ℕ} {Bond Site E : Type*}
  {Psi Phi : Site → Type*} [Fintype Bond] [DecidableEq Bond] [Norm E]

/-- Canonical real source generated by the signed complex `R3` mixed term. -/
def r3RealSource
    (C : CMP116Eq214PhysicalContourDensity nDelta nY
      Bond Site Psi Phi E lieDim)
    (sigma : Fin nDelta → ℂ) (tau : Fin nY → ℂ)
    (psi : RestrictedField C.spectatorSupport Psi)
    (phi : RestrictedField C.fluctuationSupport Phi)
    (x : CMP116Eq214GaussianCoordinate Bond lieDim) :
    CMP116Eq214GaussianCoordinate Bond lieDim :=
  -((cmp116Eq214RealPartMatrix
    (C.r3Matrix sigma tau psi phi)).mulVec x)

/-- The norm of the literal inner weight is exactly the exponential of the
canonical real source paired with the inner Gaussian coordinate. -/
theorem norm_innerWeight_eq_exp_sum_r3RealSource
    (C : CMP116Eq214PhysicalContourDensity nDelta nY
      Bond Site Psi Phi E lieDim)
    (sigma : Fin nDelta → ℂ) (tau : Fin nY → ℂ)
    (psi : RestrictedField C.spectatorSupport Psi)
    (phi : RestrictedField C.fluctuationSupport Phi)
    (x b : CMP116Eq214GaussianCoordinate Bond lieDim) :
    ‖C.toLocalFiniteGaussianData.innerWeight sigma tau psi phi x b‖ =
      Real.exp (∑ i, C.r3RealSource sigma tau psi phi x i * b i) := by
  rw [show
    C.toLocalFiniteGaussianData.innerWeight sigma tau psi phi x b =
      Complex.exp
        (-cmp116Eq214ComplexMixed
          (C.r3Matrix sigma tau psi phi) x b) by rfl]
  rw [Complex.norm_exp]
  congr 1
  rw [Complex.neg_re, cmp116Eq214ComplexMixed_re]
  simp only [r3RealSource, Pi.neg_apply]
  simp only [dotProduct]
  rw [← Finset.sum_neg_distrib]
  apply Finset.sum_congr rfl
  intro i _
  ring

/-- The canonical source energy is controlled by the `L2` operator norm of
the literal real-part `R3` matrix. -/
theorem dotProduct_r3RealSource_self_le_l2_opNorm_sq
    (C : CMP116Eq214PhysicalContourDensity nDelta nY
      Bond Site Psi Phi E lieDim)
    (sigma : Fin nDelta → ℂ) (tau : Fin nY → ℂ)
    (psi : RestrictedField C.spectatorSupport Psi)
    (phi : RestrictedField C.fluctuationSupport Phi)
    (x : CMP116Eq214GaussianCoordinate Bond lieDim) :
    C.r3RealSource sigma tau psi phi x ⬝ᵥ
        C.r3RealSource sigma tau psi phi x ≤
      ‖cmp116Eq214RealPartMatrix
          (C.r3Matrix sigma tau psi phi)‖ ^ 2 *
        (x ⬝ᵥ x) := by
  let A := cmp116Eq214RealPartMatrix (C.r3Matrix sigma tau psi phi)
  have h := dotProduct_mulVec_self_le_l2_opNorm_sq A x
  simpa [r3RealSource, A, dotProduct] using h

end CMP116Eq214PhysicalContourDensity

end

end YangMills.RG
