import YangMills.RG.BalabanCMP99SourceFlatFullComplexPrecisionStabilizedQprimeStarCLM

/-!
PRE-VALIDATION: source is present, its `.olean` has not yet been materialized,
and the result has not yet been verified by the Lean compiler.
-/

#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionStabilizedParticularSolution_add
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionStabilizedParticularSolution_smul
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionStabilizedQprimeStarField_add
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionStabilizedQprimeStarField_smul
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionStabilizedQprimeStarFieldCLM_apply
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionAction_stabilizedQprimeStarFieldCLM
