import YangMills.RG.BalabanCMP99OneScalePhysicalGreenCovariance

/-! Public oracle for the one-scale physical Green/coarse covariance chain. -/

namespace YangMills.RG

#print axioms CMP99SourceWeightedRegionalTower.norm_Qprime_le_one_unconditional
#print axioms cmp99OmegaSourcePhysicalOneStepTower
#print axioms cmp99OmegaSourcePhysicalOneStepTower_terminalSpacing
#print axioms cmp99OmegaSourcePhysicalOneStepTower_Qprime
#print axioms cmp99OmegaSourcePhysicalGaugePrecision_oneStepTower_eq
#print axioms cmp99OmegaSourcePhysicalOneStepPrecisionUpperBound
#print axioms cmp99OmegaSourcePhysicalOneStepPrecisionUpperBound_pos
#print axioms norm_cmp99OmegaSourcePhysicalOneStepGaugePrecision_le
#print axioms cmp99OmegaSourcePhysicalOneStepCoercivityConstant
#print axioms cmp99OmegaSourcePhysicalOneStepCoercivityConstant_pos
#print axioms cmp99OmegaSourcePhysicalOneStepGreen
#print axioms cmp99OmegaSourcePhysicalOneStepPrecision_comp_green
#print axioms cmp99OmegaSourcePhysicalOneStepGreen_comp_precision
#print axioms cmp99OmegaSourcePhysicalOneStepGreen_isSymmetric
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceMiddle
#print axioms coercive_cmp99OmegaSourcePhysicalOneStepCoarseCovarianceMiddle
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovariance
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovariance_comp_middle
#print axioms cmp99OmegaSourcePhysicalOneStepMiddle_comp_coarseCovariance

end YangMills.RG
