/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP98UbarLogAverageFDeriv
import YangMills.RG.BalabanCMP116WilsonOrientedEdgeVariation

/-!
# Exact first variation of the literal CMP98 contours

The complete CMP98 operator (124) is obtained by differentiating ordered
Wilson products, not by supplying a linear block map after the fact.  This
file constructs the first variation of an arbitrary literal contour by the
ordered product rule and proves that it is the genuine derivative of the
ambient contour holonomy on physical `su(N)` directions.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

/-- The ordered contour product evaluated on the physical one-parameter
unitary chart generated by `A`. -/
def cmp98ContourMatrixCurve
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc) :
    List (ConcreteEdge d (M * N')) → ℝ → Matrix (Fin Nc) (Fin Nc) ℂ
  | [], _ => 1
  | e :: es, t => orientedWilsonFactor U A e t *
      cmp98ContourMatrixCurve U A es t

/-- Recursive ordered first variation of the contour product. -/
def cmp98ContourFirstVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc) :
    List (ConcreteEdge d (M * N')) → ℝ → Matrix (Fin Nc) (Fin Nc) ℂ
  | [], _ => 0
  | e :: es, t =>
      orientedWilsonFactorFirst U A e t *
          cmp98ContourMatrixCurve U A es t +
        orientedWilsonFactor U A e t *
          cmp98ContourFirstVariation U A es t

@[simp] theorem cmp98ContourMatrixCurve_nil
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc) (t : ℝ) :
    cmp98ContourMatrixCurve U A [] t = 1 := rfl

@[simp] theorem cmp98ContourFirstVariation_nil
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc) (t : ℝ) :
    cmp98ContourFirstVariation U A [] t = 0 := rfl

/-- The recursive expression is the exact derivative of the ordered contour
product at every real chart parameter. -/
theorem hasDerivAt_cmp98ContourMatrixCurve
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) (t : ℝ) :
    HasDerivAt (cmp98ContourMatrixCurve U A es)
      (cmp98ContourFirstVariation U A es t) t := by
  induction es with
  | nil =>
      simpa only [cmp98ContourMatrixCurve_nil,
        cmp98ContourFirstVariation_nil] using
        (hasDerivAt_const (x := t) (c := (1 : Matrix (Fin Nc) (Fin Nc) ℂ)))
  | cons e es ih =>
      simpa only [cmp98ContourMatrixCurve, cmp98ContourFirstVariation] using
        (hasDerivAt_orientedWilsonFactor U A e t).mul ih

/-- The recursive physical curve is literally the ambient Wilson product
restricted to the physical tangent line. -/
theorem cmp98AmbientWilsonLineMatrix_line_eq_contourMatrixCurve
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) (t : ℝ) :
    cmp98AmbientWilsonLineMatrix U
        (t • physicalSuTangentToAmbient
          (physicalCochainToSuMatrixTangent A)) es =
      cmp98ContourMatrixCurve U A es t := by
  induction es with
  | nil => rfl
  | cons e es ih =>
      rw [cmp98AmbientWilsonLineMatrix_cons, cmp98ContourMatrixCurve,
        ambientOrientedEdgeMatrix_line_eq_orientedWilsonFactor U A e t, ih]

/-- Directional form of the ambient Fréchet derivative: its value on a
physical one-cochain is exactly the ordered recursive contour variation. -/
theorem fderiv_cmp98AmbientWilsonLineMatrix_zero_apply_physical
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) :
    fderiv ℝ (fun Z => cmp98AmbientWilsonLineMatrix U Z es) 0
        (physicalSuTangentToAmbient
          (physicalCochainToSuMatrixTangent A)) =
      cmp98ContourFirstVariation U A es 0 := by
  let V : PhysicalAmbientMatrixTangent d (M * N') Nc :=
    physicalSuTangentToAmbient (physicalCochainToSuMatrixTangent A)
  have hline : HasDerivAt (fun t : ℝ => t • V) V 0 := by
    simpa using (hasDerivAt_id (𝕜 := ℝ) 0).smul_const V
  have hout : HasFDerivAt
      (fun Z => cmp98AmbientWilsonLineMatrix U Z es)
      (fderiv ℝ (fun Z => cmp98AmbientWilsonLineMatrix U Z es) ((0 : ℝ) • V))
      ((0 : ℝ) • V) :=
    (analyticAt_cmp98AmbientWilsonLineMatrix U ((0 : ℝ) • V) es).differentiableAt.hasFDerivAt
  have hambient : HasDerivAt
      (fun t : ℝ => cmp98AmbientWilsonLineMatrix U (t • V) es)
      (fderiv ℝ (fun Z => cmp98AmbientWilsonLineMatrix U Z es) 0 V) 0 := by
    have hcomp := hout.comp_hasDerivAt 0 hline
    have hzero : (0 : ℝ) • V = 0 := zero_smul ℝ V
    rw [hzero] at hcomp
    simpa [Function.comp_def] using hcomp
  have hphysical : HasDerivAt
      (fun t : ℝ => cmp98AmbientWilsonLineMatrix U (t • V) es)
      (cmp98ContourFirstVariation U A es 0) 0 := by
    convert hasDerivAt_cmp98ContourMatrixCurve U A es 0 using 1
    funext t
    simpa [V] using
      (cmp98AmbientWilsonLineMatrix_line_eq_contourMatrixCurve U A es t)
  exact hambient.unique hphysical

end

end YangMills.RG
