import YangMills.RG.BalabanCMP99SourceRegionalCoarseMiddleDecay

open YangMills.RG

#print axioms cmp99OmegaSourcePhysicalOneStepCoarseMiddleDecayAmplitude
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceMiddle_exponentialKernelBound
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseMiddleTransitionDecayAmplitude
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseMiddleTransitionDefect_exponentialKernelBound
