/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceRegionalScale
import YangMills.RG.BalabanCMP99SourceWeightedRegionalTower

/-!
# Background-faithful source-weighted CMP99 tower

This wrapper combines the source-normalized `M^{-d}` regional average with
the recursively generated physical `Ubar` background.  A nonterminal tail is
indexed by `S.data.nextBackground`, so neither its background nor its
parallel transport can be replaced by caller-chosen data.
-/

namespace YangMills.RG

open YangMills

noncomputable section

variable {d Nc : ℕ} [NeZero d] [NeZero Nc]

/-- A weighted regional tower indexed by the physical background consumed by
its first printed average. -/
structure CMP99SourceWeightedPhysicalTower
    (rho : SUNAdjointModel Nc) {N : ℕ} [NeZero N]
    (Omega : ActiveGaugeRegion d N) (spacing : ℝ)
    (background : GaugeConfig d N (SUN Nc)) where
  private mk ::
  toWeightedTower : CMP99SourceWeightedRegionalTower
    (g := SUNLieCoord Nc) Omega spacing

/-- Empty physical tower. -/
noncomputable def CMP99SourceWeightedPhysicalTower.stop
    (rho : SUNAdjointModel Nc) {N : ℕ} [NeZero N]
    (Omega : ActiveGaugeRegion d N) (spacing : ℝ)
    (background : GaugeConfig d N (SUN Nc)) :
    CMP99SourceWeightedPhysicalTower rho Omega spacing background where
  toWeightedTower := CMP99SourceWeightedRegionalTower.stop
    (g := SUNLieCoord Nc) Omega spacing

/-- The literal adjoint transport used by the regional average in the current
physical background. -/
noncomputable def cmp99SourceWeightedPhysicalTransport
    (rho : SUNAdjointModel Nc)
    {M N' : ℕ} [NeZero M] [NeZero N']
    (background : GaugeConfig d (M * N') (SUN Nc)) :
    FinBox d N' → FinBox d (M * N') →
      (SUNLieCoord Nc ≃ₗᵢ[ℝ] SUNLieCoord Nc) :=
  cmp99AdjointBlockTransport rho
    (cmp99ContourHolonomy
      (cmp99BlockContainedContourSystem (G := SUN Nc)) background)

/-- Add a normalized physical scale.  The tail background is definitionally
the `Ubar` generated by the same scale data. -/
noncomputable def CMP99SourceWeightedPhysicalTower.step
    (rho : SUNAdjointModel Nc)
    {M N' : ℕ} [NeZero M] [NeZero N']
    (Omega : ActiveGaugeRegion d (M * N'))
    (spacing : ℝ)
    (background : GaugeConfig d (M * N') (SUN Nc))
    (S : CMP99SourceNormalizedRegionalScale Omega background)
    (tail : CMP99SourceWeightedPhysicalTower rho
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
      ((M : ℝ) * spacing)
      S.toSourceScale.data.nextBackground) :
    CMP99SourceWeightedPhysicalTower rho Omega spacing background where
  toWeightedTower := CMP99SourceWeightedRegionalTower.step
    Omega S.blockSaturated spacing
    (cmp99SourceWeightedPhysicalTransport rho background)
    tail.toWeightedTower

@[simp] theorem CMP99SourceWeightedPhysicalTower.toWeightedTower_stop
    (rho : SUNAdjointModel Nc) {N : ℕ} [NeZero N]
    (Omega : ActiveGaugeRegion d N) (spacing : ℝ)
    (background : GaugeConfig d N (SUN Nc)) :
    (CMP99SourceWeightedPhysicalTower.stop rho Omega spacing background).toWeightedTower =
      CMP99SourceWeightedRegionalTower.stop
        (g := SUNLieCoord Nc) Omega spacing := rfl

/-- Exact printed operator order at a physical source step. -/
theorem CMP99SourceWeightedPhysicalTower.Qprime_step
    (rho : SUNAdjointModel Nc)
    {M N' : ℕ} [NeZero M] [NeZero N']
    (Omega : ActiveGaugeRegion d (M * N')) (spacing : ℝ)
    (background : GaugeConfig d (M * N') (SUN Nc))
    (S : CMP99SourceNormalizedRegionalScale Omega background)
    (tail : CMP99SourceWeightedPhysicalTower rho
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega)
      ((M : ℝ) * spacing)
      S.toSourceScale.data.nextBackground) :
    (CMP99SourceWeightedPhysicalTower.step
      rho Omega spacing background S tail).toWeightedTower.Qprime =
      tail.toWeightedTower.Qprime.comp
        (cmp99SourceTransportedBlockAverageCLM Omega
          (cmp99SourceWeightedPhysicalTransport rho background)) := rfl

/-- Source-specific normalization for every background-faithful physical
tower. -/
theorem CMP99SourceWeightedPhysicalTower.Qprime_comp_weightedAdjoint_eq_Cj
    {rho : SUNAdjointModel Nc} {N : ℕ} [NeZero N]
    {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
    {background : GaugeConfig d N (SUN Nc)}
    (T : CMP99SourceWeightedPhysicalTower rho Omega spacing background) :
    T.toWeightedTower.Qprime.comp T.toWeightedTower.weightedAdjoint =
      cmp99SourceTowerNormalization T.toWeightedTower.depth •
        ContinuousLinearMap.id ℝ
          T.toWeightedTower.TerminalSpace.carrier :=
  T.toWeightedTower.Qprime_comp_weightedAdjoint_eq_Cj

/-- Exact source Hilbert norm law for the physical tower. -/
theorem CMP99SourceWeightedPhysicalTower.weightedAdjoint_norm_eq_sqrt_Cj
    {rho : SUNAdjointModel Nc} {N : ℕ} [NeZero N]
    {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
    {background : GaugeConfig d N (SUN Nc)}
    (T : CMP99SourceWeightedPhysicalTower rho Omega spacing background)
    (eta : T.toWeightedTower.TerminalSpace.carrier) :
    cmp99SourceSpacingNorm d spacing
        (T.toWeightedTower.weightedAdjoint eta) =
      Real.sqrt
          (cmp99SourceTowerNormalization T.toWeightedTower.depth) *
        cmp99SourceSpacingNorm d T.toWeightedTower.terminalSpacing eta :=
  T.toWeightedTower.weightedAdjoint_norm_eq_sqrt_Cj eta

end

end YangMills.RG
