import YangMills.RG.BalabanCMP99SourceGeneratedSectionCTypedTower

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCoarseCrossDist
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCoarseCrossDist_self
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCoarseCrossDist_triangle
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCoarseCrossDist_transition
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCutTowerStep
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCutFactorTower
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCutFactorTower_length
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCCutFactorTower_weightedRowKernelBound
