import YangMills.RG.BalabanCMP89NeumannRectangularRegionalOwnerTransport

#print axioms YangMills.RG.cmp89NeumannReflectionPeriodProduct_uniform_le_draft
#print axioms YangMills.RG.cmp89NeumannFineWeight_le_ownerWeight_of_metric_bridge_draft
#print axioms YangMills.RG.norm_cmp89Eq248PhysicalRegionalGreen_le_owner_of_geometry_draft
