import YangMills.RG.BalabanCMP99SourceScaledStratification

/-! Public oracle for the dependent-lattice CMP99 source mass. -/

namespace YangMills.RG

#print axioms CMP99SourceScaledStratification.restrictStratumCLM
#print axioms CMP99SourceScaledStratification.restrictStratumCLM_apply
#print axioms CMP99SourceScaledStratification.extendStratumCLM_apply_of_mem
#print axioms CMP99SourceScaledStratification.extendStratumCLM_apply_of_not_mem
#print axioms CMP99SourceScaledStratification.restrictStratumCLM_comp_extendStratumCLM
#print axioms CMP99SourceScaledStratification.norm_extendStratumCLM_eq
#print axioms CMP99SourceScaledStratification.inner_restrictStratumCLM_eq_extendStratumCLM
#print axioms CMP99SourceScaledStratification.extendStratumCLM_eq_adjoint_restrictStratumCLM
#print axioms CMP99SourceScaledStratification.restrictStratumCLM_comp_adjoint
#print axioms CMP99SourceScaledStratification.norm_restrictStratumCLM_sq
#print axioms CMP99SourceScaledStratification.sourceGaugeMass
#print axioms CMP99SourceScaledStratification.inner_sourceGaugeMass

end YangMills.RG
