import YangMills.RG.BalabanCMP99SourceRetainedPhysicalMass

namespace YangMills.RG

#print axioms CMP99SourceRetainedPhysicalScaleIdentification.Qprime
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision_isCoercive
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.green
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision_comp_green
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.green_comp_gaugePrecision
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.green_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumAverage
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumWeightedAdjoint
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumAverage_comp_stratumWeightedAdjoint
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.towerAt_terminalSpacing_pos
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovarianceMiddle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.isCoerciveCLM_stratumCoarseCovarianceMiddle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance_comp_middle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance_middle_comp
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.Qprime_apply

end YangMills.RG
