import YangMills.RG.BalabanCMP99SourceFlatGeneratedTerminalBlockCollapse

#print axioms YangMills.RG.cmp99GeneratedFineBoxOneBlockEquiv
#print axioms YangMills.RG.cmp99GeneratedTerminalBlockSite_eq_blockSite_pow
#print axioms YangMills.RG.cmp99SourceBlockAverageWeight_pow_eq_oneBlock
#print axioms YangMills.RG.cmp99SourceBlockAverageWeight_two_mul_eq_oneBlock_sq
#print axioms YangMills.RG.cmp99SourceIteratedLift_flatExplicitCountingMass_single_apply_oneBlock
