import YangMills.RG.BalabanCMP89SourceNeumannCoarseDerivativeDecomposition

/-!
# Axiom audit: exact regional Neumann coarse-derivative decomposition

-/

#print axioms YangMills.RG.cmp99SourceParallelAverageDefectCochain
#print axioms YangMills.RG.cmp99SourceParallelAverageDefectCochain_apply
#print axioms YangMills.RG.restrictOne_covariantD0_cmp99FullSourceBlockAverage_eq_defect_add_remainder
#print axioms YangMills.RG.cmp89SourceNeumannRegionalCovariantD0CLM_oneScaleAverage_eq_twoSpecies
