import YangMills.RG.BalabanCMP99SourceSectionCHeterogeneousFactorWalk

open YangMills.RG

#print axioms CMP99SectionCCarrierKind
#print axioms dependentBundledHilbertWalkOperator
#print axioms dependentBundledHilbertWalkOperator_singleton
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousSpace
#print axioms CMP99SourceDependentOmegaGeometry.GeneratedSectionCHeterogeneousLabel
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousLabelOperator
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCBasicAdjointLabelWalk
#print axioms CMP99SourceDependentOmegaGeometry.generatedSectionCBasicAdjointLabelWalk_eq_source
