import YangMills.RG.BalabanCMP99SourceGeneratedSectionCCommutatorFactor

open YangMills.RG

#print axioms cmp99SourceGeneratedFinePartitionCutoff
#print axioms norm_cmp99SourceGeneratedFinePartitionCutoff_le_one
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorMiddle
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorMiddleCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCoordinates
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseSectionCCommutatorMiddle_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalCoarseSectionCCommutatorFactorCoordinates_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCertificate
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCertificate_operator
