import YangMills.RG.BalabanCMP102Eq80CorrectedPhysicalCompleteDomainFTCRadial

#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalCompleteDomainFTCActivity
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalCompleteDomainFTCSeries
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalCompleteDomainFTCActivity_eq_zero_of_not_localizationDomain
#print axioms YangMills.RG.exists_uniform_bound_cmp102Eq80CorrectedPhysicalCompleteDomainFTCActivity
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalBackgroundDependentPotential_eq_completeDomainFTC_of_source
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalCompleteDomainFTCSeries_eq_radial
