import YangMills.RG.BalabanCMP116SourcePhysicalAEInteraction

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.ae_interactionExponent_le_sourcePhysicalAlpha5
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.ae_interactionExponent_le_sourcePhysicalAlpha5_of_potential
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.ae_interactionExponent_le_withConditionedOuterCarrier
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.ae_interactionExponent_le_withConditionedOuterCarrier_of_support
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.cutoffFactor_withConditionedOuterCarrier
