import YangMills.RG.BalabanCMP99SourceGeneratedQprimeTransition

open YangMills.RG

#print axioms norm_cmp99NestedActiveRegionRestriction_le_one
#print axioms cmp99SourceTransportedBlockWeightedAdjoint_nested_transition
#print axioms CMP99SourceNestedRegionChains.exists_terminalRestriction_intertwining
#print axioms CMP99SourceNestedRegionChains.terminalRestriction
#print axioms CMP99SourceNestedRegionChains.Qprime_comp_restriction
#print axioms CMP99SourceNestedRegionChains.restriction_comp_weightedAdjoint
#print axioms CMP99SourceNestedRegionChains.norm_terminalRestriction_le_one
#print axioms cmp99SourceIteratedLiftTerminalRestriction
#print axioms norm_cmp99SourceIteratedLiftTerminalRestriction_le_one
#print axioms cmp99SourceIteratedLift_Qprime_transition
#print axioms cmp99SourceIteratedLift_weightedAdjoint_transition
#print axioms CMP99SourceDependentOmegaGeometry.generatedTerminalRestriction
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedTerminalRestriction_le_one
#print axioms CMP99SourceDependentOmegaGeometry.generatedQprime_transition
#print axioms CMP99SourceDependentOmegaGeometry.generatedWeightedAdjoint_transition
