/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116Eq214PhysicalContourR3Source
import YangMills.RG.BalabanCMP116ComplexQuadraticSchur

/-!
# Bilateral Schur control of the complex `R3` source energy

The `R3` source enters the inner Gaussian through the real matrix
`Re R3`.  A row estimate alone does not control its Euclidean source energy.
This module proves the dimension-free bilateral Schur bound

`‖(Re A) x‖₂² ≤ ‖A‖_∞ ‖Aᵀ‖_∞ ‖x‖₂²`.

Together with a conditioned outer carrier, this turns the physical row and
column estimates already proved for `R3` into the exact source-rate input of
equations (2.24)--(2.25), without an ambient-cardinality factor.
-/

namespace YangMills.RG

open Matrix
open scoped BigOperators Matrix.Norms.Operator

noncomputable section

/-- Weighted finite-dimensional Schur estimate from explicit row and column
sums. -/
theorem dotProduct_mulVec_self_le_row_col
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (A : Matrix ι ι ℝ) (x : ι → ℝ) (rowBound colBound : ℝ)
    (hrow0 : 0 ≤ rowBound)
    (hrow : ∀ i, ∑ j, |A i j| ≤ rowBound)
    (hcol : ∀ j, ∑ i, |A i j| ≤ colBound) :
    dotProduct (Matrix.mulVec A x) (Matrix.mulVec A x) ≤
      rowBound * colBound * (x ⬝ᵥ x) := by
  rw [dotProduct]
  calc
    ∑ i, (∑ j, A i j * x j) * ∑ j, A i j * x j =
        ∑ i, (∑ j, A i j * x j) ^ 2 := by
      apply Finset.sum_congr rfl
      intro i _
      rw [pow_two]
    _ ≤ ∑ i, rowBound * ∑ j, |A i j| * x j ^ 2 := by
      apply Finset.sum_le_sum
      intro i _
      have hcs :
          (∑ j, A i j * x j) ^ 2 ≤
            (∑ j, |A i j|) * ∑ j, |A i j| * x j ^ 2 := by
        apply Finset.sum_sq_le_sum_mul_sum_of_sq_eq_mul
        · intro j _
          exact abs_nonneg _
        · intro j _
          exact mul_nonneg (abs_nonneg _) (sq_nonneg _)
        · intro j _
          rw [mul_pow, ← sq_abs]
          ring
      exact hcs.trans
        (mul_le_mul_of_nonneg_right (hrow i)
          (Finset.sum_nonneg fun j _ =>
            mul_nonneg (abs_nonneg _) (sq_nonneg _)))
    _ = rowBound * ∑ j, x j ^ 2 * ∑ i, |A i j| := by
      rw [← Finset.mul_sum]
      congr 1
      rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro j _
      rw [← Finset.sum_mul]
      ring
    _ ≤ rowBound * ∑ j, x j ^ 2 * colBound := by
      apply mul_le_mul_of_nonneg_left _ hrow0
      apply Finset.sum_le_sum
      intro j _
      exact mul_le_mul_of_nonneg_left (hcol j) (sq_nonneg _)
    _ = rowBound * colBound * (x ⬝ᵥ x) := by
      rw [dotProduct]
      simp only [pow_two]
      rw [← Finset.sum_mul]
      ring

/-- The entrywise real part of a complex matrix inherits its row sum from
the complex `L∞` operator norm. -/
theorem row_sum_abs_realPart_le_linfty
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ) (i : ι) :
    ∑ j, |cmp116Eq214RealPartMatrix A i j| ≤ ‖A‖ := by
  calc
    ∑ j, |cmp116Eq214RealPartMatrix A i j| ≤
        ∑ j, ‖A i j‖ := by
      apply Finset.sum_le_sum
      intro j _
      exact Complex.abs_re_le_norm _
    _ ≤ ‖A‖ := Matrix.row_sum_norm_le_linfty_opNorm A i

/-- Column companion, expressed by the row norm of the analytic transpose. -/
theorem col_sum_abs_realPart_le_linfty_transpose
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ) (j : ι) :
    ∑ i, |cmp116Eq214RealPartMatrix A i j| ≤ ‖A.transpose‖ := by
  calc
    ∑ i, |cmp116Eq214RealPartMatrix A i j| ≤
        ∑ i, ‖A.transpose j i‖ := by
      apply Finset.sum_le_sum
      intro i _
      simpa [cmp116Eq214RealPartMatrix, Matrix.transpose_apply] using
        (Complex.abs_re_le_norm (A i j))
    _ ≤ ‖A.transpose‖ :=
      Matrix.row_sum_norm_le_linfty_opNorm A.transpose j

/-- Dimension-free bilateral Schur estimate for the real source generated by
a complex matrix. -/
theorem dotProduct_realPart_mulVec_self_le_linfty_bilateral
    {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (A : Matrix ι ι ℂ) (x : ι → ℝ) :
    dotProduct
        (Matrix.mulVec (cmp116Eq214RealPartMatrix A) x)
        (Matrix.mulVec (cmp116Eq214RealPartMatrix A) x) ≤
      ‖A‖ * ‖A.transpose‖ * (x ⬝ᵥ x) := by
  exact dotProduct_mulVec_self_le_row_col
    (cmp116Eq214RealPartMatrix A) x ‖A‖ ‖A.transpose‖
    (norm_nonneg _)
    (row_sum_abs_realPart_le_linfty A)
    (col_sum_abs_realPart_le_linfty_transpose A)

end

end YangMills.RG
