import YangMills.RG.BalabanCMP116Eq225ConditionedOuterTraceInteractionCutoffSupport

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_analyticIntegrand_le_of_conditionedOuterTraceInteractionEnergy_cutoffSupport
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_conditionedOuterTraceInteractionEnergy_cutoffSupport_onShiftedCenteredPolydiscs
