import YangMills.RG.BalabanCMP116Eq225OuterTraceInteractionEnergy

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_analyticIntegrand_le_of_outerTraceInteractionEnergy
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_outerTraceInteractionEnergy
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_outerTraceInteractionEnergy_bilateralSmall
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_outerTraceInteractionEnergy_bilateralSmall_onPolydiscs
