import Mathlib

/-!
# Two-level quantitative Poincare absorption

This leaf isolates the scalar algebra required to compose a fine one-scale
Poincare estimate with a coarse retained-prefix estimate when the transported
coarse derivative contains a nonzero multiple of the original fine norm.
The smallness condition `fineCoeff * coarseCoeff * feedbackCoeff < 1` remains
literal; it is not absorbed into an unnamed constant.
-/

namespace YangMills.RG

/-- Exact two-level absorption.  The result deliberately exposes the complete
denominator generated by the feedback term. -/
theorem le_twoLevelPoincare_of_feedback_lt_one
    (fineNormSq fineDerivativeSq coarseNormSq terminalNormSq : ℝ)
    (fineCoeff coarseCoeff derivativeCoeff feedbackCoeff : ℝ)
    (fineCoeff_nonneg : 0 ≤ fineCoeff)
    (fine_bound :
      fineNormSq ≤ fineCoeff * (fineDerivativeSq + coarseNormSq))
    (coarse_bound :
      coarseNormSq ≤ coarseCoeff *
        (derivativeCoeff * fineDerivativeSq +
          feedbackCoeff * fineNormSq + terminalNormSq))
    (feedback_small : fineCoeff * coarseCoeff * feedbackCoeff < 1) :
    fineNormSq ≤
      (fineCoeff * (1 + coarseCoeff * derivativeCoeff) * fineDerivativeSq +
          fineCoeff * coarseCoeff * terminalNormSq) /
        (1 - fineCoeff * coarseCoeff * feedbackCoeff) := by
  have coarse_scaled :=
    mul_le_mul_of_nonneg_left coarse_bound fineCoeff_nonneg
  apply (le_div_iff₀ (sub_pos.mpr feedback_small)).2
  nlinarith [fine_bound, coarse_scaled]

/-- Normed-space form of the same two-level composition.  The maps are kept
abstract: the source-facing specialization must still identify the literal
fine derivative, transported average, coarse derivative and retained terminal
average. -/
theorem norm_sq_le_twoLevelPoincare_of_derivative_feedback
    {E F G H I : Type*}
    [NormedAddCommGroup E] [NormedAddCommGroup F]
    [NormedAddCommGroup G] [NormedAddCommGroup H]
    [NormedAddCommGroup I]
    (fineDerivative : E → F) (fineAverage : E → G)
    (coarseDerivative : G → H) (terminalAverage : G → I)
    (fineCoeff coarseCoeff derivativeCoeff feedbackCoeff : ℝ)
    (fineCoeff_nonneg : 0 ≤ fineCoeff)
    (coarseCoeff_nonneg : 0 ≤ coarseCoeff)
    (fine_bound : ∀ phi,
      ‖phi‖ ^ 2 ≤ fineCoeff *
        (‖fineDerivative phi‖ ^ 2 + ‖fineAverage phi‖ ^ 2))
    (coarse_bound : ∀ psi,
      ‖psi‖ ^ 2 ≤ coarseCoeff *
        (‖coarseDerivative psi‖ ^ 2 + ‖terminalAverage psi‖ ^ 2))
    (derivative_bound : ∀ phi,
      ‖coarseDerivative (fineAverage phi)‖ ^ 2 ≤
        derivativeCoeff * ‖fineDerivative phi‖ ^ 2 +
          feedbackCoeff * ‖phi‖ ^ 2)
    (feedback_small : fineCoeff * coarseCoeff * feedbackCoeff < 1) :
    ∀ phi,
      ‖phi‖ ^ 2 ≤
        (fineCoeff * (1 + coarseCoeff * derivativeCoeff) *
              ‖fineDerivative phi‖ ^ 2 +
            fineCoeff * coarseCoeff *
              ‖terminalAverage (fineAverage phi)‖ ^ 2) /
          (1 - fineCoeff * coarseCoeff * feedbackCoeff) := by
  intro phi
  have coarse_composed :
      ‖fineAverage phi‖ ^ 2 ≤ coarseCoeff *
        (derivativeCoeff * ‖fineDerivative phi‖ ^ 2 +
          feedbackCoeff * ‖phi‖ ^ 2 +
          ‖terminalAverage (fineAverage phi)‖ ^ 2) := by
    calc
      ‖fineAverage phi‖ ^ 2 ≤ coarseCoeff *
          (‖coarseDerivative (fineAverage phi)‖ ^ 2 +
            ‖terminalAverage (fineAverage phi)‖ ^ 2) :=
        coarse_bound (fineAverage phi)
      _ ≤ coarseCoeff *
          ((derivativeCoeff * ‖fineDerivative phi‖ ^ 2 +
              feedbackCoeff * ‖phi‖ ^ 2) +
            ‖terminalAverage (fineAverage phi)‖ ^ 2) := by
        apply mul_le_mul_of_nonneg_left _ coarseCoeff_nonneg
        nlinarith [derivative_bound phi]
      _ = _ := by ring
  exact le_twoLevelPoincare_of_feedback_lt_one
    (‖phi‖ ^ 2) (‖fineDerivative phi‖ ^ 2) (‖fineAverage phi‖ ^ 2)
    (‖terminalAverage (fineAverage phi)‖ ^ 2)
    fineCoeff coarseCoeff derivativeCoeff feedbackCoeff
    fineCoeff_nonneg (fine_bound phi) coarse_composed feedback_small

end YangMills.RG
