import YangMills.RG.BalabanCMP116Eq214PhysicalRealLocalData

#print axioms YangMills.RG.cmp116Eq214PhysicalRealLocalData_weightProduct_eq
#print axioms YangMills.RG.cmp116Eq214PhysicalRealLocalData_norm_outerWeight_le
