/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import Mathlib.Analysis.Matrix.Order
import YangMills.RG.BalabanCMP116Eq223PhysicalSmallness
import YangMills.RG.BalabanCMP116MatrixGaussianCarrier

/-!
# Localized covariance compression and its positive square root

PRE-VALIDATION: this source is present, its `.olean` has not yet been
materialized, and none of the results in this file is compiler-verified.

The conditioned Gaussian in CMP116 is not generated by the unrestricted
inverse of the interacting precision.  Its covariance is the compression

`P_S C P_S`

to the localized scalar coordinates, and its root is the positive matrix
square root of that compression.  This file constructs those two finite
matrix objects and proves the universal facts needed by the terminal root
certificate:

* compression preserves positive semidefiniteness;
* compression has range in `S` and cannot increase the `L²` operator norm;
* `CFC.sqrt` supplies a symmetric square root of the compressed covariance.

Honest scope: `C` remains an arbitrary positive-semidefinite finite matrix.
This file does not identify it with the coordinate matrix of the interacting
physical inverse, prove the inverse-coercivity bound, or construct the lower
nondegeneracy certificate.  Those are the separate source-facing parts of
the localized-compression bridge.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator MatrixOrder

noncomputable section

/-- Compression of a finite covariance to the localized coordinates `S`. -/
def cmp116LocalizedCovarianceCompression
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) (C : Matrix ι ι ℝ) : Matrix ι ι ℝ :=
  cmp116Eq223CoordinateProjection S * C *
    cmp116Eq223CoordinateProjection S

/-- The localized diagonal projector is symmetric. -/
theorem cmp116Eq223CoordinateProjection_transpose
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) :
    (cmp116Eq223CoordinateProjection S)ᵀ =
      cmp116Eq223CoordinateProjection S := by
  simp [cmp116Eq223CoordinateProjection, Matrix.diagonal_transpose]

/-- The `L²` operator norm of the localized projector is at most one. -/
theorem norm_cmp116Eq223CoordinateProjection_le_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) :
    ‖cmp116Eq223CoordinateProjection S‖ ≤ (1 : ℝ) := by
  rw [cmp116Eq223CoordinateProjection, Matrix.l2_opNorm_diagonal]
  refine (pi_norm_le_iff_of_nonneg zero_le_one).2 ?_
  intro i
  by_cases hi : i ∈ S <;> simp [hi]

/-- Compression on both sides cannot increase the matrix `L²` operator
norm. -/
theorem norm_cmp116LocalizedCovarianceCompression_le
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) (C : Matrix ι ι ℝ) :
    ‖cmp116LocalizedCovarianceCompression S C‖ ≤ ‖C‖ := by
  let P := cmp116Eq223CoordinateProjection S
  have hP : ‖P‖ ≤ (1 : ℝ) :=
    norm_cmp116Eq223CoordinateProjection_le_one S
  calc
    ‖cmp116LocalizedCovarianceCompression S C‖ = ‖P * C * P‖ := rfl
    _ ≤ ‖P * C‖ * ‖P‖ := norm_mul_le _ _
    _ ≤ (‖P‖ * ‖C‖) * ‖P‖ :=
      mul_le_mul_of_nonneg_right (norm_mul_le _ _) (norm_nonneg _)
    _ ≤ (1 * ‖C‖) * 1 := by gcongr
    _ = ‖C‖ := by ring

/-- The compressed covariance has no rows outside its localized carrier. -/
theorem cmp116LocalizedCovarianceCompression_supported
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) (C : Matrix ι ι ℝ) :
    MatrixRangeSupportedOn
      (cmp116LocalizedCovarianceCompression S C) S := by
  intro i hi j
  simp [cmp116LocalizedCovarianceCompression,
    cmp116Eq223CoordinateProjection, Matrix.mul_assoc,
    Matrix.diagonal_mul, hi]

/-- Positive semidefiniteness survives localized compression. -/
theorem cmp116LocalizedCovarianceCompression_posSemidef
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {C : Matrix ι ι ℝ} (S : Finset ι)
    (hC : C.PosSemidef) :
    (cmp116LocalizedCovarianceCompression S C).PosSemidef := by
  let P := cmp116Eq223CoordinateProjection S
  have h := hC.conjTranspose_mul_mul_same P
  have hP : Pᴴ = P := by
    rw [Matrix.conjTranspose_eq_transpose_of_trivial]
    exact cmp116Eq223CoordinateProjection_transpose S
  rw [hP] at h
  exact h

/-- Canonical positive square root of the localized covariance. -/
def cmp116LocalizedCovarianceRoot
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (S : Finset ι) (C : Matrix ι ι ℝ) : Matrix ι ι ℝ :=
  CFC.sqrt (cmp116LocalizedCovarianceCompression S C)

/-- The canonical positive square root and compressed covariance satisfy the
exact terminal conditioned-root certificate. -/
theorem cmp116LocalizedCovarianceRoot_certificate
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {C : Matrix ι ι ℝ} (S : Finset ι)
    (hC : C.PosSemidef) :
    MatrixConditionedGaussianRootCertificate
      (cmp116LocalizedCovarianceCompression S C)
      (cmp116LocalizedCovarianceRoot S C) S := by
  let A := cmp116LocalizedCovarianceCompression S C
  have hA : A.PosSemidef :=
    cmp116LocalizedCovarianceCompression_posSemidef S hC
  have hroot : (CFC.sqrt A).transpose = CFC.sqrt A := by
    have hrootHermitian : (CFC.sqrt A).IsHermitian :=
      (CFC.sqrt_nonneg A).posSemidef.1
    rw [Matrix.conjTranspose_eq_transpose_of_trivial] at hrootHermitian
    exact hrootHermitian
  refine {
    root_symmetric := hroot
    root_square := ?_
    covariance_supported :=
      cmp116LocalizedCovarianceCompression_supported S C }
  · rw [hroot]
    exact hA.sqrt_mul_self

end

end YangMills.RG
