import YangMills.RG.BalabanCMP89Eq246AliasReflectionTransposeFullSolution

/-!
# Axiom audit for arbitrary-source full-solution reflection
-/

namespace YangMills.RG

#print axioms cmp89Eq246StabilizedAliasTransposeNoncentralSourceMoment_neg_reflection
#print axioms cmp89Eq246StabilizedAliasTransposeFullSolutionMoment_neg_reflection
#print axioms cmp89Eq246StabilizedAliasTransposeFullSolution_neg_reflection

end YangMills.RG
