import YangMills.RG.BalabanCMP116PhysicalEndomorphismMatrix

namespace YangMills.RG

#print axioms cmp116PhysicalCoordinateLinearEquiv
#print axioms cmp116PhysicalEndomorphismRealMatrix
#print axioms cmp116PhysicalEndomorphismComplexMatrix
#print axioms cmp116PhysicalEndomorphismComplexMatrix_comp
#print axioms cmp116PhysicalEndomorphismComplexMatrix_apply
#print axioms cmp116SourcePi4_precision_mul_exactCovarianceMatrix_eq_one

end YangMills.RG
