/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116RestrictedVisitedTailSum

/-!
# Restricted visited-state transfer powers

This module identifies the recursive finite physical tail sum with the row
sum of a power of the augmented visited-state transfer matrix.

The first theorem is the exact one-step reindexing: every nonzero transfer
entry is generated by one unique physical successor.  No ambient-state
cardinality enters the formula.
-/

namespace YangMills.RG

noncomputable section

universe u v w

/-- Summing one transfer row against an arbitrary operator-valued function
is exactly the finite sum over declared physical successors. -/
theorem cmp116RestrictedVisitedTransferMatrix_row_mul_sum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (source : CMP116RestrictedTransferState Label Domain carrier)
    (F :
      CMP116RestrictedTransferState Label Domain carrier →
        Matrix Index Index ℂ) :
    (∑ target,
        cmp116RestrictedVisitedTransferMatrix
            carrier domainActive successors R sigma source target *
          F target) =
      ∑ step ∈ successors source.1.domain,
        CMP116RestrictedVisitedState.transitionWeight
            carrier sigma source.2 (domainActive step.domain) •
          (R step.label step.domain *
            F (cmp116RestrictedTransferNextState
              carrier domainActive source.2 step)) := by
  classical
  let nextState :=
    cmp116RestrictedTransferNextState
      (Label := Label) (Domain := Domain)
      carrier domainActive source.2
  let generated :=
    (successors source.1.domain).image nextState
  calc
    (∑ target,
        cmp116RestrictedVisitedTransferMatrix
            carrier domainActive successors R sigma source target *
          F target) =
        ∑ target ∈ generated,
          cmp116RestrictedVisitedTransferMatrix
              carrier domainActive successors R sigma source target *
            F target := by
      symm
      apply Finset.sum_subset (Finset.subset_univ generated)
      intro target _ hnot
      rw [
        cmp116RestrictedVisitedTransferMatrix_apply_eq_zero_of_not_mem_nextStates
          carrier domainActive successors R sigma source target hnot]
      simp
    _ =
        ∑ step ∈ successors source.1.domain,
          CMP116RestrictedVisitedState.transitionWeight
              carrier sigma source.2 (domainActive step.domain) •
            (R step.label step.domain *
              F (cmp116RestrictedTransferNextState
                carrier domainActive source.2 step)) := by
      rw [Finset.sum_image]
      · apply Finset.sum_congr rfl
        intro step hstep
        rw [
          cmp116RestrictedVisitedTransferMatrix_apply_nextState
            carrier domainActive successors R sigma source step hstep]
        simp [nextState]
      · exact
          (cmp116RestrictedTransferNextState_injective
            carrier domainActive source.2).injOn

/-- The row sum of the `n`-th transfer power is exactly the recursively
generated physical tail sum, for every augmented source state. -/
theorem cmp116RestrictedVisitedTransferMatrix_power_row_sum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ) :
    ∀ (n : ℕ)
      (source : CMP116RestrictedTransferState Label Domain carrier),
      (∑ target,
          (cmp116RestrictedVisitedTransferMatrix
              carrier domainActive successors R sigma ^ n)
            source target) =
        cmp116RestrictedVisitedTailSum
          carrier domainActive successors R sigma n
          source.1.domain source.2 := by
  classical
  intro n
  induction n with
  | zero =>
      intro source
      simp only [pow_zero, cmp116RestrictedVisitedTailSum]
      rw [Fintype.sum_eq_single source]
      · simp
      · intro target hne
        simp [Ne.symm hne]
  | succ n ih =>
      intro source
      let transfer :=
        cmp116RestrictedVisitedTransferMatrix
          carrier domainActive successors R sigma
      calc
        (∑ target, (transfer ^ (n + 1)) source target) =
            ∑ middle,
              transfer source middle *
                (∑ target, (transfer ^ n) middle target) := by
          rw [pow_succ']
          simp_rw [Matrix.mul_apply]
          rw [Finset.sum_comm]
          simp_rw [← Finset.mul_sum]
        _ =
            ∑ step ∈ successors source.1.domain,
              CMP116RestrictedVisitedState.transitionWeight
                  carrier sigma source.2 (domainActive step.domain) •
                (R step.label step.domain *
                  (∑ target,
                    (transfer ^ n)
                      (cmp116RestrictedTransferNextState
                        carrier domainActive source.2 step) target)) := by
          exact cmp116RestrictedVisitedTransferMatrix_row_mul_sum
            carrier domainActive successors R sigma source
              (fun middle => ∑ target, (transfer ^ n) middle target)
        _ =
            cmp116RestrictedVisitedTailSum
              carrier domainActive successors R sigma (n + 1)
              source.1.domain source.2 := by
          simp only [cmp116RestrictedVisitedTailSum]
          apply Finset.sum_congr rfl
          intro step _hstep
          rw [ih (cmp116RestrictedTransferNextState
            carrier domainActive source.2 step)]
          rfl

/-- Augmented state reached immediately after the distinguished physical
head has charged its contour coordinates. -/
def cmp116RestrictedTransferHeadState
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Delta]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (head : Domain) :
    CMP116RestrictedTransferState Label Domain carrier :=
  (⟨none, head⟩,
    CMP116RestrictedVisitedState.update carrier
      (CMP116RestrictedVisitedState.empty carrier)
      (domainActive head))

/-- Direct finite layer of source-shaped walks on a restricted shifted
contour. -/
def cmp116RestrictedGeneratedWalkLayer
    {nContour : ℕ}
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta) (e : Fin nContour ≃ ↥carrier)
    (z : Fin nContour → ℂ)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R0 : Domain → Matrix Index Index ℂ)
    (R : Label → Domain → Matrix Index Index ℂ)
    (n : ℕ) :
    Matrix Index Index ℂ :=
  ∑ head,
    ∑ tail ∈ cmp99AdmissibleTails successors head n,
      let walk : CMP99GeneralizedWalk Label Domain := ⟨head, tail⟩
      cmp116ComplexWeakeningMonomial (walk.active domainActive)
          (cmp116SourceRestrictedShiftedCoupling carrier e z) •
        walk.term R0 R

/-- Head-weighted row-power presentation of the same finite physical walk
layer. -/
def cmp116RestrictedVisitedTransferPowerLayer
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R0 : Domain → Matrix Index Index ℂ)
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (n : ℕ) :
    Matrix Index Index ℂ :=
  ∑ head,
    CMP116RestrictedVisitedState.transitionWeight
        carrier sigma (CMP116RestrictedVisitedState.empty carrier)
        (domainActive head) •
      (R0 head *
        ∑ target,
          (cmp116RestrictedVisitedTransferMatrix
              carrier domainActive successors R sigma ^ n)
            (cmp116RestrictedTransferHeadState
              (Label := Label) carrier domainActive head)
            target)

/-- Every finite restricted source walk layer is exactly its head-weighted
augmented-transfer power layer. -/
theorem cmp116RestrictedGeneratedWalkLayer_eq_transferPowerLayer
    {nContour : ℕ}
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [Fintype Label] [Fintype Domain]
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta) (e : Fin nContour ≃ ↥carrier)
    (z : Fin nContour → ℂ)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R0 : Domain → Matrix Index Index ℂ)
    (R : Label → Domain → Matrix Index Index ℂ)
    (n : ℕ) :
    cmp116RestrictedGeneratedWalkLayer
        carrier e z domainActive successors R0 R n =
      cmp116RestrictedVisitedTransferPowerLayer
        carrier domainActive successors R0 R
          (cmp116SourceRestrictedShiftedCoupling carrier e z) n := by
  classical
  unfold cmp116RestrictedGeneratedWalkLayer
  unfold cmp116RestrictedVisitedTransferPowerLayer
  apply Fintype.sum_congr
  intro head
  let sigma :=
    cmp116SourceRestrictedShiftedCoupling carrier e z
  let visited :=
    CMP116RestrictedVisitedState.update carrier
      (CMP116RestrictedVisitedState.empty carrier)
      (domainActive head)
  calc
    (∑ tail ∈ cmp99AdmissibleTails successors head n,
        let walk : CMP99GeneralizedWalk Label Domain := ⟨head, tail⟩
        cmp116ComplexWeakeningMonomial (walk.active domainActive) sigma •
          walk.term R0 R) =
        ∑ tail ∈ cmp99AdmissibleTails successors head n,
          CMP116RestrictedVisitedState.transitionWeight
              carrier sigma
              (CMP116RestrictedVisitedState.empty carrier)
              (domainActive head) •
            (R0 head *
              cmp116RestrictedVisitedTailProduct
                carrier domainActive R sigma visited tail) := by
      apply Finset.sum_congr rfl
      intro tail _htail
      exact
        CMP99GeneralizedWalk.restrictedShiftedMonomial_smul_term_eq_visitedProduct
          carrier e z domainActive R0 R ⟨head, tail⟩
    _ =
        CMP116RestrictedVisitedState.transitionWeight
            carrier sigma
            (CMP116RestrictedVisitedState.empty carrier)
            (domainActive head) •
          (R0 head *
            cmp116RestrictedVisitedGeneratedTailSum
              carrier domainActive successors R sigma n head visited) := by
      rw [cmp116RestrictedVisitedGeneratedTailSum]
      rw [← Finset.smul_sum, ← Finset.mul_sum]
    _ =
        CMP116RestrictedVisitedState.transitionWeight
            carrier sigma
            (CMP116RestrictedVisitedState.empty carrier)
            (domainActive head) •
          (R0 head *
            cmp116RestrictedVisitedTailSum
              carrier domainActive successors R sigma n head visited) := by
      rw [cmp116RestrictedVisitedGeneratedTailSum_eq_tailSum]
    _ =
        CMP116RestrictedVisitedState.transitionWeight
            carrier sigma
            (CMP116RestrictedVisitedState.empty carrier)
            (domainActive head) •
          (R0 head *
            ∑ target,
              (cmp116RestrictedVisitedTransferMatrix
                  carrier domainActive successors R sigma ^ n)
                (cmp116RestrictedTransferHeadState
                  (Label := Label) carrier domainActive head)
                target) := by
      rw [cmp116RestrictedVisitedTransferMatrix_power_row_sum
        carrier domainActive successors R sigma n
        (cmp116RestrictedTransferHeadState
          (Label := Label) carrier domainActive head)]
      rfl

end

end YangMills.RG
