import YangMills.RG.BalabanCMP99SourceGeneratedSectionCCommutatorFactorDecay

open YangMills.RG

#print axioms cmp99SourceGeneratedPhysicalCoarseCommutatorWeightedRowAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCoordinates_exponential
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCoordinates_weightedRow
