import YangMills.RG.BalabanCMP116Eq214ConditionedOuterR1Control

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.conditionedOuterProjection_eq_finsetCoordinateProjection
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.linfty_opNorm_conditionedOuterProjection_le_one
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.linfty_opNorm_conditionedOuterProjection_mul_mul_le
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.linfty_opNorm_transpose_conditionedOuterProjection_mul_mul_le
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.transpose_conditionedOuterProjection_mul_mul
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.trace_conditionedOuterProjection_mul_mul_mul
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_trace_conditionedOuterProjection_mul_mul_le_of
