import YangMills.RG.BalabanCMP99SourceActiveRegionFullCompanionPrecision


#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionTower
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionCountingCoefficient
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionCountingCoefficient_eq_regional
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecision
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecision_compression
#print axioms YangMills.RG.isCoerciveCLM_cmp99SourceActiveRegionFullCompanionPrecision
