import YangMills.RG.BalabanCMP116Eq216PhysicalR3

#print axioms YangMills.RG.cmp116PhysicalGammaOperator_apply
#print axioms YangMills.RG.cmp116PhysicalGammaOperator_sub_eq_telescope
#print axioms YangMills.RG.norm_physicalBondProjection_le_one
#print axioms YangMills.RG.norm_cmp116PhysicalGammaOperator_sub_le
#print axioms YangMills.RG.cmp116InteractingPhysicalR3Correction_eq_telescope
#print axioms YangMills.RG.norm_cmp116InteractingPhysicalR3Correction_le
