/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102AmbientFourContourThirdJetBound
import YangMills.RG.BalabanCMP102AmbientLocalNearLogBudget
import YangMills.RG.LocalQuantitativeComposition
import YangMills.RG.NearLogExpThirdDerivativeChangeOriginBound

/-!
# Third jets of the literal CMP98 local logarithm

This file transports the source-generated physical four-contour jets through
the locally analytic Mercator logarithm.  The outer jets are generated by
the literal Mercator series, and the inner jets by the ordered physical
Wilson line.  The local quantitative Faà di Bruno theorem is used because
`nearLog` is analytic only on its unit ball.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
  [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102AmbientLocalNearLogThirdJetMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

local instance cmp102AmbientLocalNearLogThirdJetCMLSeminormed (n : ℕ) :
    SeminormedAddCommGroup
      (PhysicalAmbientMatrixTangent d (M * N') Nc [×n]→L[ℝ]
        Matrix (Fin Nc) (Fin Nc) ℂ) :=
  ContinuousMultilinearMap.seminormedAddCommGroup

/-- One generated budget dominating the value and the first three
Mercator jets on the strict closed ball of radius `q`. -/
def cmp102SourceNearLogOrderThreeOuterBudget
    (q : NNReal) : ℝ :=
  max (nearLogDerivativeBudget q * q)
    (max (nearLogDerivativeBudget q)
      (max (nearLogSecondDerivativeBudget q)
        (nearLogThirdDerivativeBallBudget
          (A := Matrix (Fin Nc) (Fin Nc) ℂ) q)))

/-- The generated common outer budget controls every Mercator jet through
order three. -/
theorem norm_iteratedFDeriv_nearLog_le_orderThreeOuterBudget
    (q : NNReal) (hq : (q : ℝ) < 1)
    {Y : Matrix (Fin Nc) (Fin Nc) ℂ} (hY : ‖Y‖ < q)
    (i : ℕ) (hi : i ≤ 3) :
    ‖iteratedFDeriv ℝ i
        (nearLog :
          Matrix (Fin Nc) (Fin Nc) ℂ →
            Matrix (Fin Nc) (Fin Nc) ℂ) Y‖ ≤
      cmp102SourceNearLogOrderThreeOuterBudget
        (Nc := Nc) q := by
  interval_cases i
  · have hzeroOrder :
        ‖iteratedFDeriv ℝ 0
            (nearLog :
              Matrix (Fin Nc) (Fin Nc) ℂ →
                Matrix (Fin Nc) (Fin Nc) ℂ) Y‖ =
          ‖nearLog Y‖ :=
      norm_iteratedFDeriv_zero
    have hzero :
        ‖(0 : Matrix (Fin Nc) (Fin Nc) ℂ)‖ ≤ (q : ℝ) := by
      simpa using q.2
    calc
      ‖iteratedFDeriv ℝ 0
          (nearLog :
            Matrix (Fin Nc) (Fin Nc) ℂ →
              Matrix (Fin Nc) (Fin Nc) ℂ) Y‖ =
          ‖nearLog Y‖ := hzeroOrder
      _ =
          ‖nearLog Y -
            nearLog (0 : Matrix (Fin Nc) (Fin Nc) ℂ)‖ := by
        rw [nearLog_zero, sub_zero]
      _ ≤ nearLogDerivativeBudget q *
            ‖Y - (0 : Matrix (Fin Nc) (Fin Nc) ℂ)‖ :=
        norm_nearLog_sub_nearLog_le q.2 hq hY.le hzero
      _ ≤ nearLogDerivativeBudget q * q := by
        rw [sub_zero]
        exact mul_le_mul_of_nonneg_left hY.le
          (nearLogDerivativeBudget_nonneg q q.2)
      _ ≤ _ := le_max_left _ _
  · calc
      ‖iteratedFDeriv ℝ 1
          (nearLog :
            Matrix (Fin Nc) (Fin Nc) ℂ →
              Matrix (Fin Nc) (Fin Nc) ℂ) Y‖ =
          ‖fderiv ℝ
            (nearLog :
              Matrix (Fin Nc) (Fin Nc) ℂ →
                Matrix (Fin Nc) (Fin Nc) ℂ) Y‖ :=
        norm_iteratedFDeriv_one
          (𝕜 := ℝ) (x := Y)
          (nearLog :
            Matrix (Fin Nc) (Fin Nc) ℂ →
              Matrix (Fin Nc) (Fin Nc) ℂ)
      _ ≤ nearLogDerivativeBudget q :=
        norm_fderiv_nearLog_le_derivativeBudget q.2 hq hY.le
      _ ≤ _ :=
        (le_max_left _ _).trans (le_max_right _ _)
  · exact
      (norm_iteratedFDeriv_two_nearLog_le_secondDerivativeBudget
        q.2 hq hY).trans
        ((le_max_left _ _).trans
          ((le_max_right _ _).trans (le_max_right _ _)))
  · have hYnn : ‖Y‖₊ ≤ q := by
      exact_mod_cast hY.le
    exact
      (norm_iteratedFDeriv_three_nearLog_le_ballBudget
        q hq hYnn).trans
        ((le_max_right _ _).trans
          ((le_max_right _ _).trans (le_max_right _ _)))

/-- The inner Faà di Bruno radius is the common physical contour-jet
budget, enlarged to be at least one so that it controls all powers one
through three. -/
def cmp102SourceFourContourCompositionRadius
    (d M : ℕ) (r : NNReal) : ℝ :=
  max 1
    (cmp102SourceFourContourOrderThreeJetBudget
      (Nc := Nc) d M r)

/-- Explicit third-jet budget for the literal local logarithm. -/
def cmp102SourceLocalNearLogThirdJetBudget
    (d M : ℕ) (r q : NNReal) : ℝ :=
  6 * cmp102SourceNearLogOrderThreeOuterBudget
        (Nc := Nc) q *
    cmp102SourceFourContourCompositionRadius
        (Nc := Nc) d M r ^ 3

set_option maxHeartbeats 1200000 in
/-- Every positive jet through order three of the literal local logarithm
is controlled by the same source-generated third-jet budget. -/
theorem norm_iteratedFDeriv_nearLog_cmp98UbarAmbientDeviationMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (r q : NNReal) (hZ : ‖Z‖ < r)
    (hq : (q : ℝ) < 1)
    (hD : ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ < q)
    (i : ℕ) (hi1 : 1 ≤ i) (hi3 : i ≤ 3) :
    ‖iteratedFDeriv ℝ i
        (fun W =>
          nearLog (cmp98UbarAmbientDeviationMatrix U b x W)) Z‖ ≤
      cmp102SourceLocalNearLogThirdJetBudget
        (Nc := Nc) d M r q := by
  let inner :
      PhysicalAmbientMatrixTangent d (M * N') Nc →
        Matrix (Fin Nc) (Fin Nc) ℂ :=
    fun W => cmp98UbarAmbientDeviationMatrix U b x W
  let outer :
      Matrix (Fin Nc) (Fin Nc) ℂ →
        Matrix (Fin Nc) (Fin Nc) ℂ :=
    nearLog
  let C :=
    cmp102SourceNearLogOrderThreeOuterBudget
      (Nc := Nc) q
  let D :=
    cmp102SourceFourContourCompositionRadius
      (Nc := Nc) d M r
  have houter : ContDiffAt ℝ i outer (inner Z) :=
    (analyticAt_nearLog_of_norm_lt_one
      (show ‖inner Z‖ < 1 from hD.trans hq)).contDiffAt.of_le le_top
  have hinner : ContDiffAt ℝ i inner Z :=
    (analyticAt_cmp98UbarAmbientDeviationMatrix U b x Z).contDiffAt.of_le
      le_top
  have hC : ∀ j, j ≤ i →
      ‖iteratedFDeriv ℝ j outer (inner Z)‖ ≤ C := by
    intro j hj
    exact norm_iteratedFDeriv_nearLog_le_orderThreeOuterBudget
      q hq hD j (hj.trans hi3)
  have hDnonneg : 0 ≤ D := by
    exact zero_le_one.trans (le_max_left _ _)
  have hDone : 1 ≤ D :=
    le_max_left _ _
  have hDjets : ∀ j, 1 ≤ j → j ≤ i →
      ‖iteratedFDeriv ℝ j inner Z‖ ≤ D ^ j := by
    intro j hj1 hji
    have hraw :
        ‖iteratedFDeriv ℝ j inner Z‖ ≤
          cmp102SourceFourContourOrderThreeJetBudget
            (Nc := Nc) d M r := by
      exact
        norm_iteratedFDeriv_cmp98UbarAmbientDeviationMatrix_le_sourceLengthBudget
          U b x hx Z r hZ j (by omega) (hji.trans hi3)
    calc
      ‖iteratedFDeriv ℝ j inner Z‖
          ≤ cmp102SourceFourContourOrderThreeJetBudget
              (Nc := Nc) d M r := hraw
      _ ≤ D := le_max_right _ _
      _ = D ^ 1 := (pow_one D).symm
      _ ≤ D ^ j := pow_le_pow_right₀ hDone hj1
  have hmain :=
    norm_iteratedFDeriv_comp_le_at_of_both_local
      houter hinner hC hDjets
  have hCnonneg : 0 ≤ C :=
    (norm_nonneg (iteratedFDeriv ℝ 0 outer (inner Z))).trans
      (hC 0 (Nat.zero_le i))
  have hfac : (i.factorial : ℝ) ≤ 6 := by
    interval_cases i <;> norm_num
  have hpow : D ^ i ≤ D ^ 3 :=
    pow_le_pow_right₀ hDone hi3
  change
    ‖iteratedFDeriv ℝ i (outer ∘ inner) Z‖ ≤ _ at hmain
  calc
    ‖iteratedFDeriv ℝ i (outer ∘ inner) Z‖
        ≤ (i.factorial : ℝ) * C * D ^ i := hmain
    _ ≤ 6 * C * D ^ 3 := by
      exact mul_le_mul
        (mul_le_mul_of_nonneg_right hfac hCnonneg) hpow
        (pow_nonneg hDnonneg i) (mul_nonneg (by norm_num) hCnonneg)
    _ = cmp102SourceLocalNearLogThirdJetBudget
        (Nc := Nc) d M r q := rfl

set_option maxHeartbeats 1200000 in
/-- The third derivative of the literal local logarithm is controlled
entirely by the source contour length, the edge radius, and the Mercator
radius.  No composite third-jet bound is supplied by the caller. -/
theorem norm_iteratedFDeriv_three_nearLog_cmp98UbarAmbientDeviationMatrix_le
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    (r q : NNReal) (hZ : ‖Z‖ < r)
    (hq : (q : ℝ) < 1)
    (hD : ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ < q) :
    ‖iteratedFDeriv ℝ 3
        (fun W =>
          nearLog (cmp98UbarAmbientDeviationMatrix U b x W)) Z‖ ≤
      cmp102SourceLocalNearLogThirdJetBudget
        (Nc := Nc) d M r q :=
  norm_iteratedFDeriv_nearLog_cmp98UbarAmbientDeviationMatrix_le
    U b x hx Z r q hZ hq hD 3 (by omega) (by omega)

end

end YangMills.RG
