import YangMills.RG.BalabanCMP116SourcePi4FullComplexR2TransposePhysicalBound

#print axioms YangMills.RG.cmp116SourcePi4PhysicalComplexTransposeRelativeDefectBound
#print axioms YangMills.RG.cmp116SourcePi4PhysicalComplexR2ColumnBound
#print axioms YangMills.RG.linfty_opNorm_transpose_cmp116SourcePi4FullComplexR2Matrix_le_physical
