/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116Eq225SourceEnergy

/-!
# CMP116 equation (2.25): outer `R₁` energy and source energy together

The literal physical split places the `R₁` quadratic correction in the outer
Gaussian weight.  Consequently that weight is not uniformly bounded in the
outer field.  The correct interface bounds it by an exponential of localized
outer energy and integrates this cost together with the energy generated by
the `R₃` source after the inner Gaussian is completed.

This module removes the false need for a pointwise constant outer bound while
retaining the exact localized Gaussian moment.  The only smallness condition
is imposed on the sum of the two physical energy rates.
-/

namespace YangMills.RG

open Matrix MeasureTheory
open scoped BigOperators Matrix.Norms.L2Operator

noncomputable section

namespace CMP116Eq214FiniteGaussianData

/-- Fixed-contour equation-(2.25) bound with an energy-dependent outer weight.
The combined exponent is the sum of the literal `R₁` rate and the completed-
square `R₃` source rate. -/
theorem norm_analyticIntegrand_le_of_outerInteractionEnergy
    {nDelta nY lieDim : ℕ} {Bond Psi Phi E : Type*}
    [Fintype Bond] [DecidableEq Bond] [Norm E]
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Psi Phi E lieDim)
    (Y0 P : Finset Bond)
    (sigma : Fin nDelta → ℂ) (tau : Fin nY → ℂ)
    (psi : Psi) (phi : Phi)
    (S : Finset (Bond × Fin lieDim))
    (alpha sourceRate sourceResidual outerBound outerRate : ℝ)
    (r : CMP116Eq214GaussianCoordinate Bond lieDim →
      Bond × Fin lieDim → ℝ)
    (halpha : 0 ≤ alpha)
    (hsmall : alpha * ‖G.covarianceRoot sigma tau‖ ^ 2 < 1)
    (hbeta :
      2 * (outerRate +
        cmp116Eq225SourceCoefficient (G.covarianceRoot sigma tau) alpha *
          sourceRate) < 1)
    (houter_nonneg : 0 ≤ outerBound)
    (houter : ∀ x,
      ‖G.outerWeight sigma tau psi phi x‖ ≤
        outerBound * Real.exp (outerRate * ∑ i ∈ S, x i ^ 2))
    (hdom : ∀ x,
      ∀ᵐ b ∂matrixGaussianPi (G.covarianceRoot sigma tau),
        ‖G.toAnalyticData.innerIntegrand Y0 P sigma tau psi phi x b‖ ≤
          cmp116Eq223RealGaussian
            (-(alpha • cmp116Eq223CoordinateProjection S)) (r x) b)
    (hsource : ∀ x,
      (r x) ⬝ᵥ (r x) ≤
        sourceRate * (∑ i ∈ S, x i ^ 2) + sourceResidual) :
    ‖G.toAnalyticData.analyticIntegrand Y0 P sigma tau psi phi‖ ≤
      outerBound *
        (cmp116Eq225LocalizedSourceEnergyPrefactor S
          (G.covarianceRoot sigma tau) alpha sourceResidual *
        (Real.sqrt
          ((1 - 2 * (outerRate +
            cmp116Eq225SourceCoefficient (G.covarianceRoot sigma tau) alpha *
              sourceRate)) ^ S.card))⁻¹) := by
  let coeff := cmp116Eq225SourceCoefficient
    (G.covarianceRoot sigma tau) alpha
  let beta := outerRate + coeff * sourceRate
  unfold CMP116Eq214AnalyticData.analyticIntegrand
  rw [G.toAnalyticData_mu0]
  unfold balabanCMP116Dmu0Flat
  rw [← mul_assoc]
  apply norm_integral_le_of_localizedGaussianEnergy
    S beta
      (outerBound *
        cmp116Eq225LocalizedSourceEnergyPrefactor S
          (G.covarianceRoot sigma tau) alpha sourceResidual)
      (by simpa [beta, coeff] using hbeta)
  filter_upwards [] with x
  rw [norm_mul]
  have hinner :=
    G.norm_innerIntegral_le_eq224Majorant_of_l2OpNormSmallness
      Y0 P sigma tau psi phi x S alpha (r x) halpha hsmall (hdom x)
  have hmajor := cmp116Eq224_localized_gaussianMajorant_le_sourceEnergy_card
    S (G.covarianceRoot sigma tau) alpha (r x) x sourceRate sourceResidual
      halpha hsmall (hsource x)
  let energy := ∑ i ∈ S, x i ^ 2
  calc
    ‖G.outerWeight sigma tau psi phi x‖ *
        ‖∫ b, G.toAnalyticData.innerIntegrand Y0 P sigma tau psi phi x b
          ∂G.toAnalyticData.conditionedMeasure sigma tau‖ ≤
      (outerBound * Real.exp (outerRate * energy)) *
        cmp116Eq224GaussianMajorant (G.covarianceRoot sigma tau)
          (-(alpha • cmp116Eq223CoordinateProjection S))
          (fun i => ((r x) i : ℂ)) := by
            exact mul_le_mul (by simpa [energy] using houter x) hinner
              (norm_nonneg _)
              (mul_nonneg houter_nonneg (Real.exp_nonneg _))
    _ ≤ (outerBound * Real.exp (outerRate * energy)) *
        (cmp116Eq225LocalizedSourceEnergyPrefactor S
          (G.covarianceRoot sigma tau) alpha sourceResidual *
          Real.exp ((coeff * sourceRate) * energy)) := by
            exact mul_le_mul_of_nonneg_left
              (by simpa [coeff, energy] using hmajor)
              (mul_nonneg houter_nonneg (Real.exp_nonneg _))
    _ = (outerBound *
        cmp116Eq225LocalizedSourceEnergyPrefactor S
          (G.covarianceRoot sigma tau) alpha sourceResidual) *
        Real.exp (beta * energy) := by
      rw [show beta * energy = outerRate * energy +
          (coeff * sourceRate) * energy by simp [beta]; ring,
        Real.exp_add]
      ring

end CMP116Eq214FiniteGaussianData

end

end YangMills.RG
