/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116CorrelatedGaussian
import YangMills.RG.BalabanCMP116Dmu0
import YangMills.RG.BalabanCMP116Eq214IntegrandEstimate

/-!
# CMP116 equation (2.14): finite Gaussian specialization

The general analytic term permits arbitrary measures so that its source shape
can be audited independently.  This module supplies the physical finite
Gaussian specialization:

* the outer `X` law is the literal flattened CMP116 product Gaussian `dμ₀`;
* the conditioned `B` law is the pushforward Gaussian `matrixGaussianPi R`
  generated by a real covariance-root matrix at the contour parameters.

Both probability obligations are therefore theorems.  The contour-dependent
root matrix and Wilson weights remain explicit because identifying them with
the physical Hessian/Green operator is the live source theorem.
-/

namespace YangMills.RG

open MeasureTheory

/-- Flattened finite bond/Lie coordinate space used simultaneously for the
standard `X` variables and conditioned `B` variables. -/
abbrev CMP116Eq214GaussianCoordinate (Bond : Type*) (lieDim : ℕ) :=
  Bond × Fin lieDim → ℝ

/-- Equation-(2.14) data after fixing both Gaussian laws to their concrete
finite-dimensional constructions. -/
structure CMP116Eq214FiniteGaussianData
    (nDelta nY : ℕ) (Bond Ψ Φ E : Type*)
    [Fintype Bond] [Norm E] (lieDim : ℕ) where
  deltaRadius : Fin nDelta → ℝ
  yRadius : Fin nY → ℝ
  covarianceRoot :
    (Fin nDelta → ℂ) → (Fin nY → ℂ) →
      Matrix (Bond × Fin lieDim) (Bond × Fin lieDim) ℝ
  outerWeight :
    (Fin nDelta → ℂ) → (Fin nY → ℂ) → Ψ → Φ →
      CMP116Eq214GaussianCoordinate Bond lieDim → ℂ
  innerWeight :
    (Fin nDelta → ℂ) → (Fin nY → ℂ) → Ψ → Φ →
      CMP116Eq214GaussianCoordinate Bond lieDim →
      CMP116Eq214GaussianCoordinate Bond lieDim → ℂ
  bondField : CMP116Eq214GaussianCoordinate Bond lieDim → Bond → E
  threshold : ℝ
  interactionExponent :
    (Fin nDelta → ℂ) → (Fin nY → ℂ) → Ψ → Φ →
      CMP116Eq214GaussianCoordinate Bond lieDim → ℂ

namespace CMP116Eq214FiniteGaussianData

variable {nDelta nY lieDim : ℕ} {Bond Ψ Φ E : Type*}
  [Fintype Bond] [Norm E]

/-- Forgetful map to the general analytic-data interface, with both measures
fixed by construction. -/
noncomputable def toAnalyticData
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Ψ Φ E lieDim) :
    CMP116Eq214AnalyticData nDelta nY Bond
      (CMP116Eq214GaussianCoordinate Bond lieDim)
      (CMP116Eq214GaussianCoordinate Bond lieDim) Ψ Φ E where
  deltaRadius := G.deltaRadius
  yRadius := G.yRadius
  mu0 := balabanCMP116Dmu0Flat Bond lieDim
  conditionedMeasure := fun sigma tau =>
    matrixGaussianPi (G.covarianceRoot sigma tau)
  outerWeight := G.outerWeight
  innerWeight := G.innerWeight
  bondField := G.bondField
  threshold := G.threshold
  interactionExponent := G.interactionExponent

@[simp] theorem toAnalyticData_mu0
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Ψ Φ E lieDim) :
    G.toAnalyticData.mu0 = balabanCMP116Dmu0Flat Bond lieDim := by
  rfl

@[simp] theorem toAnalyticData_conditionedMeasure
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Ψ Φ E lieDim)
    (sigma : Fin nDelta → ℂ) (tau : Fin nY → ℂ) :
    G.toAnalyticData.conditionedMeasure sigma tau =
      matrixGaussianPi (G.covarianceRoot sigma tau) := by
  rfl

/-- The outer source measure is a probability measure, with no new premise. -/
theorem toAnalyticData_mu0_isProbability
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Ψ Φ E lieDim) :
    IsProbabilityMeasure G.toAnalyticData.mu0 := by
  simpa using balabanCMP116Dmu0Flat_isProbability Bond lieDim

/-- Every contour-dependent conditioned measure is a probability measure by
its pushforward construction. -/
theorem toAnalyticData_conditionedMeasure_isProbability
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Ψ Φ E lieDim)
    (sigma : Fin nDelta → ℂ) (tau : Fin nY → ℂ) :
    IsProbabilityMeasure (G.toAnalyticData.conditionedMeasure sigma tau) := by
  rw [toAnalyticData_conditionedMeasure]
  infer_instance

/-- For finite Gaussian data, uniform Wilson-weight bounds directly generate
the complete nested contour predicate; no measure hypotheses remain. -/
theorem nestedCauchyBoundaryBound_of_uniformWeights
    (G : CMP116Eq214FiniteGaussianData nDelta nY Bond Ψ Φ E lieDim)
    (Y0 P : Finset Bond) (psi : Ψ) (phi : Φ)
    (outerBound innerBound interactionBound : ℝ)
    (houter_nonneg : 0 ≤ outerBound)
    (houter : ∀ sigma tau x,
      ‖G.outerWeight sigma tau psi phi x‖ ≤ outerBound)
    (hinner : ∀ sigma tau x b,
      ‖G.innerWeight sigma tau psi phi x b‖ ≤ innerBound)
    (hinteraction : ∀ sigma tau b,
      (G.interactionExponent sigma tau psi phi b).re ≤ interactionBound) :
    CMP116Eq214NestedCauchyBoundaryBound nDelta nY
      G.deltaRadius G.yRadius
      (fun sigma tau =>
        G.toAnalyticData.analyticIntegrand Y0 P sigma tau psi phi)
      (outerBound * (innerBound * Real.exp interactionBound)) := by
  exact G.toAnalyticData.nestedCauchyBoundaryBound_of_uniformPhysicalBounds
    Y0 P psi phi outerBound innerBound interactionBound houter_nonneg
    G.toAnalyticData_mu0_isProbability
    G.toAnalyticData_conditionedMeasure_isProbability
    houter hinner hinteraction

end CMP116Eq214FiniteGaussianData

end YangMills.RG
