/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SectionCPrecisionShellMass

/-!
# From a physical shell collar to bilateral decay distances

The bilateral kernel theorem keeps the lower distances `dx` and `dy` to the
thickened shell explicit.  This file supplies them from a finite, checkable
collar condition on the unthickened shell.  If a bond is at distance at least
`L + R` from every shell bond, the triangle inequality places it at distance
at least `L` from the closed `R`-thickening.
-/

namespace YangMills.RG

noncomputable section

private abbrev PhysicalEndomorphism (d N Nc : ℕ) [NeZero N] :=
  PhysicalGaugeOneCochain d N Nc →L[ℝ]
    PhysicalGaugeOneCochain d N Nc

/-- Bonds separated from every bond of `D` by the collar width `L + R`. -/
def cmp99PhysicalBondShellGap
    {d N : ℕ} [NeZero N]
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (D : Finset (PhysicalBond d N)) (R L : ℕ) :
    Finset (PhysicalBond d N) :=
  Finset.univ.filter fun x => ∀ shell ∈ D, L + R ≤ dist x shell

@[simp] theorem mem_cmp99PhysicalBondShellGap_iff
    {d N : ℕ} [NeZero N]
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (D : Finset (PhysicalBond d N)) (R L : ℕ)
    (x : PhysicalBond d N) :
    x ∈ cmp99PhysicalBondShellGap dist D R L ↔
      ∀ shell ∈ D, L + R ≤ dist x shell := by
  simp [cmp99PhysicalBondShellGap]

/-- A collar of width `L + R` around the raw shell yields a lower distance
`L` to every bond in its closed `R`-thickening. -/
theorem cmp99PhysicalBondShellGap_le_dist_thickening
    {d N : ℕ} [NeZero N]
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (htriangle : ∀ x middle shell,
      dist x shell ≤ dist x middle + dist middle shell)
    (D : Finset (PhysicalBond d N)) (R L : ℕ)
    {x : PhysicalBond d N}
    (hx : x ∈ cmp99PhysicalBondShellGap dist D R L) :
    ∀ middle, middle ∈ cmp99PhysicalBondThickening dist R D →
      L ≤ dist x middle := by
  intro middle hmiddle
  rw [mem_cmp99PhysicalBondThickening_iff] at hmiddle
  obtain ⟨shell, hshell, hnear⟩ := hmiddle
  have hgap := (mem_cmp99PhysicalBondShellGap_iff
    dist D R L x).1 hx shell hshell
  have htri := htriangle x middle shell
  omega

/-- Physical-bond-distance specialization of the shell-gap lemma. -/
theorem cmp99PhysicalBondShellGap_le_physicalBondDist_thickening
    {d N : ℕ} [NeZero N]
    (D : Finset (PhysicalBond d N)) (R L : ℕ)
    {x : PhysicalBond d N}
    (hx : x ∈ cmp99PhysicalBondShellGap physicalBondDist D R L) :
    ∀ middle,
      middle ∈ cmp99PhysicalBondThickening physicalBondDist R D →
        L ≤ physicalBondDist x middle :=
  cmp99PhysicalBondShellGap_le_dist_thickening
    physicalBondDist physicalBondDist_triangle D R L hx

/-- The explicit precision-shell mass estimate with both external distance
binders generated by physical collar membership. -/
theorem cmp99SectionCCovarianceDifference_bilateralDecay_of_shellGaps
    {d N Nc : ℕ} [NeZero N]
    (K : PhysicalEndomorphism d N Nc)
    {S1 S0 : Finset (PhysicalBond d N)} (hsub : S1 ⊆ S0)
    (R : ℕ) (hrange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {CK NR c mass A0 A1 mu : ℝ}
    (hCK : 0 ≤ CK) (hNR : 0 ≤ NR)
    (hkernel : PhysicalCovarianceKernelBound K (fun _ _ => CK))
    (hball : ∀ source : PhysicalBond d N,
      (((Finset.univ.filter fun target =>
        physicalBondDist target source ≤ R).card : ℕ) : ℝ) ≤ NR)
    (hc : 0 < c) (hmass : 0 < mass) (hcoercive : IsCoerciveCLM K c)
    (hC0 : PhysicalCovarianceExponentialKernelBound
      (cmp99LocalizedPhysicalCovariance K S0 hc hmass hcoercive)
      physicalBondDist A0 mu)
    (hC1 : PhysicalCovarianceExponentialKernelBound
      (cmp99LocalizedPhysicalCovariance K S1 hc hmass hcoercive)
      physicalBondDist A1 mu)
    {source target : PhysicalBond d N} {Lx Ly : ℕ}
    (htarget : target ∈ cmp99PhysicalBondShellGap
      physicalBondDist (S0 \ S1) R Lx)
    (hsource : source ∈ cmp99PhysicalBondShellGap
      physicalBondDist (S0 \ S1) R Ly)
    (v0 : SUNLieCoord Nc) :
    ‖cmp99SectionCCovarianceDifference K S0 S1 hc hmass hcoercive
        (singlePhysicalBondCochain source v0) target‖ ≤
      A0 * A1 * ((3 * CK * NR + |mass|) * (S0 \ S1).card) *
        Real.exp (-(mu * (Lx : ℝ))) *
        Real.exp (-(mu * (Ly : ℝ))) * ‖v0‖ := by
  apply cmp99SectionCCovarianceDifference_bilateralShellDecay_of_finiteRangeKernelBound
    K hsub physicalBondDist physicalBondDist_comm physicalBondDist_self
      R hrange hCK hNR hkernel hball hc hmass hcoercive hC0 hC1
  · exact cmp99PhysicalBondShellGap_le_physicalBondDist_thickening
      (S0 \ S1) R Lx htarget
  · exact fun middle hmiddle => by
      rw [physicalBondDist_comm]
      exact (cmp99PhysicalBondShellGap_le_physicalBondDist_thickening
        (S0 \ S1) R Ly hsource) middle hmiddle

/-- Equal collars on both external bonds yield the expected doubled exponent
`exp (-2 * mu * L)`. -/
theorem cmp99SectionCCovarianceDifference_bilateralDecay_of_commonShellGap
    {d N Nc : ℕ} [NeZero N]
    (K : PhysicalEndomorphism d N Nc)
    {S1 S0 : Finset (PhysicalBond d N)} (hsub : S1 ⊆ S0)
    (R : ℕ) (hrange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {CK NR c mass A0 A1 mu : ℝ}
    (hCK : 0 ≤ CK) (hNR : 0 ≤ NR)
    (hkernel : PhysicalCovarianceKernelBound K (fun _ _ => CK))
    (hball : ∀ source : PhysicalBond d N,
      (((Finset.univ.filter fun target =>
        physicalBondDist target source ≤ R).card : ℕ) : ℝ) ≤ NR)
    (hc : 0 < c) (hmass : 0 < mass) (hcoercive : IsCoerciveCLM K c)
    (hC0 : PhysicalCovarianceExponentialKernelBound
      (cmp99LocalizedPhysicalCovariance K S0 hc hmass hcoercive)
      physicalBondDist A0 mu)
    (hC1 : PhysicalCovarianceExponentialKernelBound
      (cmp99LocalizedPhysicalCovariance K S1 hc hmass hcoercive)
      physicalBondDist A1 mu)
    {source target : PhysicalBond d N} {L : ℕ}
    (htarget : target ∈ cmp99PhysicalBondShellGap
      physicalBondDist (S0 \ S1) R L)
    (hsource : source ∈ cmp99PhysicalBondShellGap
      physicalBondDist (S0 \ S1) R L)
    (v0 : SUNLieCoord Nc) :
    ‖cmp99SectionCCovarianceDifference K S0 S1 hc hmass hcoercive
        (singlePhysicalBondCochain source v0) target‖ ≤
      A0 * A1 * ((3 * CK * NR + |mass|) * (S0 \ S1).card) *
        Real.exp (-(2 * mu * (L : ℝ))) * ‖v0‖ := by
  have h := cmp99SectionCCovarianceDifference_bilateralDecay_of_shellGaps
    K hsub R hrange hCK hNR hkernel hball hc hmass hcoercive hC0 hC1
      htarget hsource v0
  have hexp :
      Real.exp (-(mu * (L : ℝ))) * Real.exp (-(mu * (L : ℝ))) =
        Real.exp (-(2 * mu * (L : ℝ))) := by
    rw [← Real.exp_add]
    congr 1
    ring
  calc
    ‖cmp99SectionCCovarianceDifference K S0 S1 hc hmass hcoercive
        (singlePhysicalBondCochain source v0) target‖ ≤
        A0 * A1 * ((3 * CK * NR + |mass|) * (S0 \ S1).card) *
          Real.exp (-(mu * (L : ℝ))) *
          Real.exp (-(mu * (L : ℝ))) * ‖v0‖ := h
    _ = A0 * A1 * ((3 * CK * NR + |mass|) * (S0 \ S1).card) *
          (Real.exp (-(mu * (L : ℝ))) *
            Real.exp (-(mu * (L : ℝ)))) * ‖v0‖ := by ring
    _ = A0 * A1 * ((3 * CK * NR + |mass|) * (S0 \ S1).card) *
          Real.exp (-(2 * mu * (L : ℝ))) * ‖v0‖ := by
      rw [hexp]

end

end YangMills.RG
