import YangMills.RG.BalabanCMP102Eq80SourcePi4CarrierAnchoredPotentialDerivativeSupport

#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainMatrix_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainMatrix_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainOperator_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainOperator_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainPotentialDerivative_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainPotentialDerivative_eq_zero_of_not_walkConnected
