import YangMills.RG.BalabanCMP102Eq80SourcePi4CarrierAnchoredLocalizationSeries

#print axioms YangMills.RG.summable_cmp102Eq80SourcePi4CarrierAnchoredDomainLayerCoefficient
#print axioms YangMills.RG.norm_cmp102Eq80SourcePi4CarrierAnchoredDomainCoefficient_le
#print axioms YangMills.RG.tendsto_cmp102Eq80SourcePi4CarrierAnchoredDomainPartial
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainCoefficient_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4CarrierAnchoredDomainCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrixMixedDerivative_eq_sum_pi4CarrierAnchoredDomainCoefficient
