import YangMills.RG.BalabanCMP99SourceRegionalCoarseCovarianceTransition

open YangMills.RG

#print axioms typedCoarseMiddleDefect_eq_greenMismatch
#print axioms cmp99OmegaSourcePhysicalOneStepTerminalRestriction
#print axioms cmp99OmegaSourcePhysicalOneStepQ_terminal_transition
#print axioms cmp99OmegaSourcePhysicalOneStepQ_adjoint_terminal_transition
#print axioms cmp99OmegaSourcePhysicalOneStep_weightedAdjoint_terminal_transition
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseMiddleTransitionDefect
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseMiddleTransitionDefect_eq_greenMismatch
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovarianceTransition
#print axioms cmp99OmegaSourcePhysicalOneStepCoarseCovariance_transition_resolvent
