import YangMills.RG.BalabanCMP99SourceDisplayedSectionCSubalphabet

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCSubalphabet
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCHeterogeneousSpace_coarse_eq
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCSourceLabelNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCLabelNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCLabelOperator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCCoarseLabelOperator_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCLabelOperator_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCOperatorWalk_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCUniformNormAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCUniformNormAmplitude_nonneg
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCCoarseLabelNormAmplitude_le_uniform
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousLabelNormAmplitude_le_uniform
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCLabelNormAmplitude_le_uniform
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.DependentArrowWalk.amplitude_le_pow_length_of_uniform
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCOperatorWalk_le_uniform_pow
