import YangMills.RG.BalabanCMP116SourceRestrictedCoordinatePivotFirstHit

#print axioms YangMills.RG.mem_active_of_cmp116RestrictedOrderedPivotWeight_ne_zero
#print axioms YangMills.RG.cmp116SourcePi4ForwardWalk_matrix_eq_coordinatePivot_finiteCarrierFactors
#print axioms YangMills.RG.cmp116SourcePi4ForwardWalk_trace_eq_coordinatePivot_reducedTrace
#print axioms YangMills.RG.norm_cmp116SourcePi4ForwardWalk_coordinatePivot_weight_mul_trace_le
