/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceGeneratedScaledGradientRecurrence
import YangMills.RG.BalabanCMP99OneScaleRegionalPoincare

/-!
# Source-generated regional Poincare chain

The field norm at every prefix is generated by the same typed region,
background, and averaging recursion as the scaled-gradient energy.  The
one-step Poincare estimate is then stated directly between adjacent generated
prefixes with the printed lattice-spacing factor.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N] [NeZero Nc]

/-- Exact conversion from the unscaled Dirichlet covariant difference to the
source derivative at spacing `spacing`. -/
theorem norm_covariantD0_extendZero_sq_eq_spacing_sq_mul_scaled
    (Omega : ActiveGaugeRegion d N)
    (rho : SUNAdjointModel Nc)
    (background : GaugeConfig d N (SUN Nc))
    {spacing : ℝ} (hspacing : 0 < spacing)
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    ‖covariantD0CLM rho background (extendZeroZeroCLM Omega phi)‖ ^ 2 =
      spacing ^ 2 *
        ‖cmp99ActiveRegionSourceCovariantD0CLM
          Omega rho background spacing phi‖ ^ 2 := by
  change ‖covariantD0CLM rho background
      (extendZeroZeroCLM Omega phi)‖ ^ 2 =
    spacing ^ 2 *
      ‖spacing⁻¹ • covariantD0CLM rho background
        (extendZeroZeroCLM Omega phi)‖ ^ 2
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (inv_pos.mpr hspacing)]
  field_simp [ne_of_gt hspacing]

/-- Squared norm of the recursively averaged physical field at every prefix
of a typed source region chain. -/
noncomputable def CMP99SourceActiveRegionChain.fieldNormSq
    {N depth : ℕ} {Omega : ActiveGaugeRegion d N}
    (regions : CMP99SourceActiveRegionChain d M N Omega depth)
    (hd : 2 ≤ d) (hM : 2 ≤ M) :
    letI : NeZero N := regions.neZero
    (epsilon : ℝ) → (background : GaugeConfig d N (SUN Nc)) →
    (chain : CMP99SourceUbarRadiusChain d M Nc depth epsilon) →
    (fineSmall : ∀ e : ConcreteEdge d N,
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon) →
    Fin (depth + 1) → ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) → ℝ := by
  letI : NeZero N := regions.neZero
  intro epsilon background chain fineSmall
  induction regions generalizing epsilon with
  | stop Omega =>
      intro _r phi
      exact ‖phi‖ ^ 2
  | @step N' depth _ Omega hOmega tail ih =>
      letI : NeZero (M * N') := inferInstance
      let Scale : CMP99SourceNormalizedRegionalScale Omega background :=
        CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM Omega background
          hOmega epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
      have nextSmall : ∀ e : ConcreteEdge d N',
          ‖(Scale.toSourceScale.data.nextBackground e :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤
            cmp99SourceUbarNextFineRadius d M epsilon := by
        intro e
        simpa [Scale, CMP99SourceNormalizedRegionalScale.ofFineSmall,
          CMP99SourceRegionalScale.ofFineSmall] using
          norm_cmp99SourceRegionalScaleDataOfFineSmall_nextBackground_sub_one_le
            hd hM Omega background (cmp99SourceBlockAverageWeight M d)
            epsilon chain.epsilon_nonneg chain.head_noWinding
            chain.head_logSmall fineSmall e
      let coarsePhi := cmp99SourceTransportedBlockAverageCLM Omega
        (cmp99SourceWeightedPhysicalTransport
          (matrixSUNAdjointModel Nc) background)
      intro r phi
      exact Fin.cases (‖phi‖ ^ 2)
        (fun s => ih (cmp99SourceUbarNextFineRadius d M epsilon)
          Scale.toSourceScale.data.nextBackground chain.tail nextSmall s
          (coarsePhi phi)) r

@[simp] theorem CMP99SourceActiveRegionChain.fieldNormSq_zero
    {depth : ℕ} {Omega : ActiveGaugeRegion d N}
    (regions : CMP99SourceActiveRegionChain d M N Omega depth)
    (hd : 2 ≤ d) (hM : 2 ≤ M) :
    letI : NeZero N := regions.neZero
    ∀ (epsilon : ℝ) (background : GaugeConfig d N (SUN Nc))
      (chain : CMP99SourceUbarRadiusChain d M Nc depth epsilon)
      (fineSmall : ∀ e : ConcreteEdge d N,
        ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
      (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)),
      regions.fieldNormSq hd hM epsilon background chain fineSmall 0 phi =
        ‖phi‖ ^ 2 := by
  letI : NeZero N := regions.neZero
  induction regions <;> intros <;> rfl

/-- The first adjacent source fields satisfy the literal one-scale regional
Poincare estimate with the scaled derivative energy. -/
theorem CMP99SourceActiveRegionChain.fieldNormSq_zero_le_energy_add_one
    {N' depth : ℕ} [NeZero N']
    (Omega : ActiveGaugeRegion d (M * N'))
    (hOmega : Omega.BlockSaturated)
    (tail : CMP99SourceActiveRegionChain d M N'
      (cmp99ActiveCoarseRegion (M := M) (N' := N') Omega) depth)
    (hd : 2 ≤ d) (hM : 2 ≤ M) {spacing epsilon : ℝ}
    (hspacing : 0 < spacing)
    (background : GaugeConfig d (M * N') (SUN Nc))
    (chain : CMP99SourceUbarRadiusChain d M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge d (M * N'),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)) :
    let regions := CMP99SourceActiveRegionChain.step Omega hOmega tail
    regions.fieldNormSq hd hM epsilon background chain fineSmall 0 phi ≤
      cmp99OneScaleBlockPoincareConstant d M *
        (spacing ^ 2 *
            regions.scaledGradientEnergy hd hM spacing epsilon background chain
              fineSmall 0 phi +
          regions.fieldNormSq hd hM epsilon background chain fineSmall
            ⟨1, by omega⟩ phi) := by
  dsimp only
  have h := norm_sq_le_cmp99OneScaleRegionalPoincare Omega hOmega
    (matrixSUNAdjointModel Nc) background phi
  rw [norm_covariantD0_extendZero_sq_eq_spacing_sq_mul_scaled
    Omega (matrixSUNAdjointModel Nc) background hspacing phi] at h
  let Scale : CMP99SourceNormalizedRegionalScale Omega background :=
    CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM Omega background
      hOmega epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
  have nextSmall : ∀ e : ConcreteEdge d N',
      ‖(Scale.toSourceScale.data.nextBackground e :
          Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤
        cmp99SourceUbarNextFineRadius d M epsilon := by
    intro e
    simpa [Scale, CMP99SourceNormalizedRegionalScale.ofFineSmall,
      CMP99SourceRegionalScale.ofFineSmall] using
      norm_cmp99SourceRegionalScaleDataOfFineSmall_nextBackground_sub_one_le
        hd hM Omega background (cmp99SourceBlockAverageWeight M d)
        epsilon chain.epsilon_nonneg chain.head_noWinding
        chain.head_logSmall fineSmall e
  let coarsePhi := cmp99SourceTransportedBlockAverageCLM Omega
    (cmp99SourceWeightedPhysicalTransport
      (matrixSUNAdjointModel Nc) background) phi
  let regions := CMP99SourceActiveRegionChain.step Omega hOmega tail
  have hone : regions.fieldNormSq hd hM epsilon background chain fineSmall
      ⟨1, by omega⟩ phi = ‖coarsePhi‖ ^ 2 := by
    change tail.fieldNormSq hd hM
      (cmp99SourceUbarNextFineRadius d M epsilon)
      Scale.toSourceScale.data.nextBackground chain.tail nextSmall 0
      coarsePhi = ‖coarsePhi‖ ^ 2
    exact tail.fieldNormSq_zero hd hM _ _ _ _ _
  rw [regions.fieldNormSq_zero, regions.scaledGradientEnergy_zero, hone]
  simpa [coarsePhi] using h

/-- The fully iterated regional Poincare bound.  Its successor branch uses
the literal source spacing, generated `Ubar` background, and transported
block average before recurring on the typed coarse region. -/
noncomputable def CMP99SourceActiveRegionChain.poincareBound
    {N depth : ℕ} {Omega : ActiveGaugeRegion d N}
    (regions : CMP99SourceActiveRegionChain d M N Omega depth)
    (hd : 2 ≤ d) (hM : 2 ≤ M) :
    letI : NeZero N := regions.neZero
    (spacing epsilon : ℝ) → (background : GaugeConfig d N (SUN Nc)) →
    (chain : CMP99SourceUbarRadiusChain d M Nc depth epsilon) →
    (fineSmall : ∀ e : ConcreteEdge d N,
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon) →
    ActiveGaugeZeroCochain Omega (SUNLieCoord Nc) → ℝ := by
  letI : NeZero N := regions.neZero
  intro spacing epsilon background chain fineSmall
  induction regions generalizing spacing epsilon with
  | stop Omega =>
      intro phi
      exact ‖phi‖ ^ 2
  | @step N' depth _ Omega hOmega tail ih =>
      letI : NeZero (M * N') := inferInstance
      let Scale : CMP99SourceNormalizedRegionalScale Omega background :=
        CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM Omega background
          hOmega epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
      have nextSmall : ∀ e : ConcreteEdge d N',
          ‖(Scale.toSourceScale.data.nextBackground e :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤
            cmp99SourceUbarNextFineRadius d M epsilon := by
        intro e
        simpa [Scale, CMP99SourceNormalizedRegionalScale.ofFineSmall,
          CMP99SourceRegionalScale.ofFineSmall] using
          norm_cmp99SourceRegionalScaleDataOfFineSmall_nextBackground_sub_one_le
            hd hM Omega background (cmp99SourceBlockAverageWeight M d)
            epsilon chain.epsilon_nonneg chain.head_noWinding
            chain.head_logSmall fineSmall e
      let coarsePhi := cmp99SourceTransportedBlockAverageCLM Omega
        (cmp99SourceWeightedPhysicalTransport
          (matrixSUNAdjointModel Nc) background)
      intro phi
      exact cmp99OneScaleBlockPoincareConstant d M *
        (spacing ^ 2 *
            ‖cmp99ActiveRegionSourceCovariantD0CLM Omega
              (matrixSUNAdjointModel Nc) background spacing phi‖ ^ 2 +
          ih ((M : ℝ) * spacing)
            (cmp99SourceUbarNextFineRadius d M epsilon)
            Scale.toSourceScale.data.nextBackground chain.tail nextSmall
            (coarsePhi phi))

/-- Iteration of the physical one-scale Poincare estimate along the complete
source-generated region and background tower.  No intermediate field,
background, region, or Poincare remainder is a caller input. -/
theorem CMP99SourceActiveRegionChain.fieldNormSq_zero_le_poincareBound
    {depth : ℕ} {Omega : ActiveGaugeRegion d N}
    (regions : CMP99SourceActiveRegionChain d M N Omega depth)
    (hd : 2 ≤ d) (hM : 2 ≤ M) :
    letI : NeZero N := regions.neZero
    ∀ {spacing epsilon : ℝ}, 0 < spacing →
    ∀ (background : GaugeConfig d N (SUN Nc))
      (chain : CMP99SourceUbarRadiusChain d M Nc depth epsilon)
      (fineSmall : ∀ e : ConcreteEdge d N,
        ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
      (phi : ActiveGaugeZeroCochain Omega (SUNLieCoord Nc)),
      regions.fieldNormSq hd hM epsilon background chain fineSmall 0 phi ≤
        regions.poincareBound hd hM spacing epsilon background chain fineSmall phi := by
  letI : NeZero N := regions.neZero
  induction regions with
  | stop Omega =>
      intro spacing epsilon hspacing background chain fineSmall phi
      rfl
  | @step N' depth _ Omega hOmega tail ih =>
      intro spacing epsilon hspacing background chain fineSmall phi
      letI : NeZero (M * N') := inferInstance
      let Scale : CMP99SourceNormalizedRegionalScale Omega background :=
        CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM Omega background
          hOmega epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
      have nextSmall : ∀ e : ConcreteEdge d N',
          ‖(Scale.toSourceScale.data.nextBackground e :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤
            cmp99SourceUbarNextFineRadius d M epsilon := by
        intro e
        simpa [Scale, CMP99SourceNormalizedRegionalScale.ofFineSmall,
          CMP99SourceRegionalScale.ofFineSmall] using
          norm_cmp99SourceRegionalScaleDataOfFineSmall_nextBackground_sub_one_le
            hd hM Omega background (cmp99SourceBlockAverageWeight M d)
            epsilon chain.epsilon_nonneg chain.head_noWinding
            chain.head_logSmall fineSmall e
      let coarsePhi := cmp99SourceTransportedBlockAverageCLM Omega
        (cmp99SourceWeightedPhysicalTransport
          (matrixSUNAdjointModel Nc) background) phi
      have htail := ih
        (mul_pos (Nat.cast_pos.mpr (NeZero.pos M)) hspacing)
        Scale.toSourceScale.data.nextBackground chain.tail nextSmall coarsePhi
      have hCP : 0 ≤ cmp99OneScaleBlockPoincareConstant d M := by
        exact le_of_lt cmp99OneScaleBlockPoincareConstant_pos
      have hhead' : ‖phi‖ ^ 2 ≤
          cmp99OneScaleBlockPoincareConstant d M *
            (spacing ^ 2 *
                ‖cmp99ActiveRegionSourceCovariantD0CLM Omega
                  (matrixSUNAdjointModel Nc) background spacing phi‖ ^ 2 +
              ‖coarsePhi‖ ^ 2) := by
        have hbase := norm_sq_le_cmp99OneScaleRegionalPoincare Omega hOmega
          (matrixSUNAdjointModel Nc) background phi
        rw [norm_covariantD0_extendZero_sq_eq_spacing_sq_mul_scaled
          Omega (matrixSUNAdjointModel Nc) background hspacing phi] at hbase
        simpa [coarsePhi] using hbase
      have htail' : ‖coarsePhi‖ ^ 2 ≤
          tail.poincareBound hd hM ((M : ℝ) * spacing)
            (cmp99SourceUbarNextFineRadius d M epsilon)
            Scale.toSourceScale.data.nextBackground chain.tail nextSmall
            coarsePhi := by
        rw [← tail.fieldNormSq_zero hd hM
          (cmp99SourceUbarNextFineRadius d M epsilon)
          Scale.toSourceScale.data.nextBackground chain.tail nextSmall
          coarsePhi]
        exact htail
      change ‖phi‖ ^ 2 ≤ _
      calc
        ‖phi‖ ^ 2 ≤
            cmp99OneScaleBlockPoincareConstant d M *
              (spacing ^ 2 *
                  ‖cmp99ActiveRegionSourceCovariantD0CLM Omega
                    (matrixSUNAdjointModel Nc) background spacing phi‖ ^ 2 +
                ‖coarsePhi‖ ^ 2) := hhead'
        _ ≤ cmp99OneScaleBlockPoincareConstant d M *
              (spacing ^ 2 *
                  ‖cmp99ActiveRegionSourceCovariantD0CLM Omega
                    (matrixSUNAdjointModel Nc) background spacing phi‖ ^ 2 +
                tail.poincareBound hd hM ((M : ℝ) * spacing)
                  (cmp99SourceUbarNextFineRadius d M epsilon)
                  Scale.toSourceScale.data.nextBackground chain.tail nextSmall
                  coarsePhi) := by
          gcongr
        _ = _ := by
          rfl

/-- Canonical source-facing iteration from one closed small-field budget.
All regions, saturation proofs, radii, backgrounds, and adjacent fields are
generated internally. -/
theorem cmp99SourceIteratedLift_fieldNormSq_zero_le_poincareBound_of_closedBudget
    (hd : 2 ≤ d) (hM : 2 ≤ M) (Omega : ActiveGaugeRegion d N)
    (depth : ℕ) {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig d
      (cmp99RegionalLatticeSize M N depth) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget d M Nc depth epsilon)
    (fineSmall : ∀ e : ConcreteEdge d
      (cmp99RegionalLatticeSize M N depth),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (phi : ActiveGaugeZeroCochain
      (cmp99IteratedLiftActiveRegion (M := M) Omega depth)
      (SUNLieCoord Nc)) :
    let regions := cmp99SourceIteratedLiftActiveRegionChain
      (M := M) Omega depth
    let chain := budget.toRadiusChain
    regions.fieldNormSq hd hM epsilon background chain fineSmall 0 phi ≤
      regions.poincareBound hd hM spacing epsilon background chain fineSmall phi := by
  dsimp only
  exact CMP99SourceActiveRegionChain.fieldNormSq_zero_le_poincareBound
    (cmp99SourceIteratedLiftActiveRegionChain (M := M) Omega depth)
    hd hM hspacing background budget.toRadiusChain fineSmall phi

end

end YangMills.RG
