import YangMills.RG.BalabanCMP102Eq80RectangularOrderFourJetRadius

#print axioms YangMills.RG.cmp102Eq80RectangularOrderFourJetRadius
#print axioms YangMills.RG.cmp102Eq80JointRemainderRadius_orderFour_of_correctionJets
