import YangMills.RG.BalabanCMP116Eq225ConditionedOuterTraceInteractionResidual

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.cmp116Eq224_localized_gaussianMajorant_le_conditionedSourceEnergy_card
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.norm_analyticIntegrand_le_of_conditionedOuterTraceInteractionEnergy_cutoff
#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.nestedCauchyBoundaryBound_of_conditionedOuterTraceInteractionEnergy_cutoff_onPolydiscs
