/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102AmbientFourContourUniformBudget
import YangMills.RG.NearLogLipschitz
import YangMills.RG.NearLogSecondDerivativeBound

/-!
# Uniform Mercator budgets for the literal CMP98 local contour

This module composes the source-generated four-contour estimates with the
audited Mercator series.  The resulting value, derivative, value-Lipschitz,
and derivative-Lipschitz bounds contain no point-dependent contour length
and no supplied local analytic constants.
-/

namespace YangMills.RG

open Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

local instance cmp102AmbientLocalNearLogMatrixNormOneClass :
    NormOneClass (Matrix (Fin Nc) (Fin Nc) ℂ) where
  norm_one := by
    rw [← Matrix.diagonal_one, Matrix.l2_opNorm_diagonal]
    simp

/-- Uniform value budget after applying the local Mercator logarithm. -/
def cmp102SourceLocalNearLogValueBudget
    (q : ℝ) : ℝ :=
  nearLogDerivativeBudget q * q

/-- Uniform derivative budget after applying the local Mercator logarithm. -/
def cmp102SourceLocalNearLogDerivativeBudget
    (d M : ℕ) (r q : ℝ) : ℝ :=
  nearLogDerivativeBudget q *
    cmp102SourceFourContourDeviationDerivativeBudget d M r

/-- Uniform value-Lipschitz budget after applying the local Mercator
logarithm. -/
def cmp102SourceLocalNearLogValueLipschitzBudget
    (d M : ℕ) (r q : ℝ) : ℝ :=
  nearLogDerivativeBudget q *
    cmp102SourceFourContourDeviationValueLipschitzBudget d M r

/-- Uniform derivative-Lipschitz budget after applying the local Mercator
logarithm. -/
def cmp102SourceLocalNearLogDerivativeLipschitzBudget
    (d M : ℕ) (r q : ℝ) : ℝ :=
  nearLogSecondDerivativeBudget q *
      cmp102SourceFourContourDeviationValueLipschitzBudget d M r *
      cmp102SourceFourContourDeviationDerivativeBudget d M r +
    nearLogDerivativeBudget q *
      cmp102SourceFourContourDeviationDerivativeLipschitzBudget d M r

/-- The literal local logarithm has a uniform source-generated value bound. -/
theorem norm_nearLog_cmp98UbarAmbientDeviationMatrix_le_sourceBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {q : ℝ} (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hD : ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ ≤ q) :
    ‖nearLog (cmp98UbarAmbientDeviationMatrix U b x Z)‖ ≤
      cmp102SourceLocalNearLogValueBudget q := by
  let D := cmp98UbarAmbientDeviationMatrix U b x Z
  have hzero : ‖(0 : Matrix (Fin Nc) (Fin Nc) ℂ)‖ ≤ q := by
    simpa using hq0
  have h := norm_nearLog_sub_nearLog_le hq0 hq1 hD hzero
  calc
    ‖nearLog D‖ ≤ nearLogDerivativeBudget q * ‖D‖ := by
      simpa [D] using h
    _ ≤ nearLogDerivativeBudget q * q :=
      mul_le_mul_of_nonneg_left hD
        (nearLogDerivativeBudget_nonneg q hq0)
    _ = cmp102SourceLocalNearLogValueBudget q := rfl

/-- The derivative of the literal local logarithm is generated by the
Mercator derivative and the source four-contour derivative. -/
theorem norm_fderiv_nearLog_cmp98UbarAmbientDeviationMatrix_le_sourceBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1)
    (Z : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r q : ℝ} (hr : 0 ≤ r) (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hZ : ‖Z‖ ≤ r)
    (hD : ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ ≤ q) :
    ‖fderiv ℝ
        (fun W => nearLog (cmp98UbarAmbientDeviationMatrix U b x W)) Z‖ ≤
      cmp102SourceLocalNearLogDerivativeBudget d M r q := by
  let D := cmp98UbarAmbientDeviationMatrix U b x Z
  let A := fderiv ℝ
    (nearLog : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ) D
  let B := fderiv ℝ
    (fun W => cmp98UbarAmbientDeviationMatrix U b x W) Z
  have hlog :
      HasFDerivAt (nearLog :
        Matrix (Fin Nc) (Fin Nc) ℂ →
          Matrix (Fin Nc) (Fin Nc) ℂ) A D := by
    have hraw :=
      hasFDerivAt_nearLog_of_norm_lt_one (hD.trans_lt hq1)
    dsimp only [A, D]
    convert hraw using 1
    exact hraw.fderiv
  have hdev :
      HasFDerivAt
        (fun W => cmp98UbarAmbientDeviationMatrix U b x W) B Z := by
    simpa [B] using
      (analyticAt_cmp98UbarAmbientDeviationMatrix U b x Z
        ).differentiableAt.hasFDerivAt
  have hcomp :
      fderiv ℝ
          (fun W => nearLog (cmp98UbarAmbientDeviationMatrix U b x W)) Z =
        A.comp B := by
    simpa only [Function.comp_apply] using (hlog.comp Z hdev).fderiv
  rw [hcomp]
  have hA : ‖A‖ ≤ nearLogDerivativeBudget q := by
    simpa [A, D] using
      norm_fderiv_nearLog_le_derivativeBudget hq0 hq1 hD
  have hB :
      ‖B‖ ≤ cmp102SourceFourContourDeviationDerivativeBudget d M r := by
    simpa [B] using
      norm_fderiv_cmp98UbarAmbientDeviationMatrix_le_sourceLengthBudget
        U b x hx Z hr hZ
  calc
    ‖A.comp B‖ ≤ ‖A‖ * ‖B‖ :=
      ContinuousLinearMap.opNorm_comp_le A B
    _ ≤ nearLogDerivativeBudget q *
          cmp102SourceFourContourDeviationDerivativeBudget d M r := by
      exact mul_le_mul hA hB (norm_nonneg B)
        (nearLogDerivativeBudget_nonneg q hq0)
    _ = cmp102SourceLocalNearLogDerivativeBudget d M r q := rfl

/-- The literal local logarithm is uniformly Lipschitz on the ambient ball
whenever both source deviations stay in the Mercator ball. -/
theorem norm_nearLog_cmp98UbarAmbientDeviationMatrix_sub_le_sourceBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1)
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r q : ℝ} (hr : 0 ≤ r) (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hZ : ‖Z‖ ≤ r) (hW : ‖W‖ ≤ r)
    (hDZ : ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ ≤ q)
    (hDW : ‖cmp98UbarAmbientDeviationMatrix U b x W‖ ≤ q) :
    ‖nearLog (cmp98UbarAmbientDeviationMatrix U b x Z) -
        nearLog (cmp98UbarAmbientDeviationMatrix U b x W)‖ ≤
      cmp102SourceLocalNearLogValueLipschitzBudget d M r q *
        ‖Z - W‖ := by
  calc
    ‖nearLog (cmp98UbarAmbientDeviationMatrix U b x Z) -
        nearLog (cmp98UbarAmbientDeviationMatrix U b x W)‖
        ≤ nearLogDerivativeBudget q *
            ‖cmp98UbarAmbientDeviationMatrix U b x Z -
              cmp98UbarAmbientDeviationMatrix U b x W‖ :=
      norm_nearLog_sub_nearLog_le hq0 hq1 hDZ hDW
    _ ≤ nearLogDerivativeBudget q *
          (cmp102SourceFourContourDeviationValueLipschitzBudget d M r *
            ‖Z - W‖) := by
      gcongr
      exact nearLogDerivativeBudget_nonneg q hq0
      exact
        norm_cmp98UbarAmbientDeviationMatrix_sub_le_sourceLengthBudget
          U b x hx Z W hr hZ hW
    _ = cmp102SourceLocalNearLogValueLipschitzBudget d M r q *
          ‖Z - W‖ := by
      unfold cmp102SourceLocalNearLogValueLipschitzBudget
      ring

/-- The derivative of the literal local logarithm is uniformly Lipschitz.
The two summands are respectively the variation of the Mercator derivative
and the variation of the source four-contour derivative. -/
theorem norm_fderiv_nearLog_cmp98UbarAmbientDeviationMatrix_sub_le_sourceBudget
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N'))
    (hx : x ∈ blockOf M N' b.1)
    (Z W : PhysicalAmbientMatrixTangent d (M * N') Nc)
    {r q : ℝ} (hr : 0 ≤ r) (hq0 : 0 ≤ q) (hq1 : q < 1)
    (hZ : ‖Z‖ ≤ r) (hW : ‖W‖ ≤ r)
    (hDZ : ‖cmp98UbarAmbientDeviationMatrix U b x Z‖ ≤ q)
    (hDW : ‖cmp98UbarAmbientDeviationMatrix U b x W‖ ≤ q) :
    ‖fderiv ℝ
          (fun V => nearLog (cmp98UbarAmbientDeviationMatrix U b x V)) Z -
        fderiv ℝ
          (fun V => nearLog (cmp98UbarAmbientDeviationMatrix U b x V)) W‖ ≤
      cmp102SourceLocalNearLogDerivativeLipschitzBudget d M r q *
        ‖Z - W‖ := by
  let DZ := cmp98UbarAmbientDeviationMatrix U b x Z
  let DW := cmp98UbarAmbientDeviationMatrix U b x W
  let AZ := fderiv ℝ
    (nearLog : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ) DZ
  let AW := fderiv ℝ
    (nearLog : Matrix (Fin Nc) (Fin Nc) ℂ →
      Matrix (Fin Nc) (Fin Nc) ℂ) DW
  let BZ := fderiv ℝ
    (fun V => cmp98UbarAmbientDeviationMatrix U b x V) Z
  let BW := fderiv ℝ
    (fun V => cmp98UbarAmbientDeviationMatrix U b x V) W
  have hcompZ :
      fderiv ℝ
          (fun V => nearLog (cmp98UbarAmbientDeviationMatrix U b x V)) Z =
        AZ.comp BZ := by
    have hlog := hasFDerivAt_nearLog_of_norm_lt_one
      (show ‖DZ‖ < 1 from
        (show ‖DZ‖ ≤ q by simpa [DZ] using hDZ).trans_lt hq1)
    have hdev :=
      (analyticAt_cmp98UbarAmbientDeviationMatrix U b x Z
        ).differentiableAt.hasFDerivAt
    have hraw := (hlog.comp Z hdev).fderiv
    rw [← hlog.fderiv] at hraw
    simpa only [Function.comp_apply, AZ, BZ, DZ] using hraw
  have hcompW :
      fderiv ℝ
          (fun V => nearLog (cmp98UbarAmbientDeviationMatrix U b x V)) W =
        AW.comp BW := by
    have hlog := hasFDerivAt_nearLog_of_norm_lt_one
      (show ‖DW‖ < 1 from
        (show ‖DW‖ ≤ q by simpa [DW] using hDW).trans_lt hq1)
    have hdev :=
      (analyticAt_cmp98UbarAmbientDeviationMatrix U b x W
        ).differentiableAt.hasFDerivAt
    have hraw := (hlog.comp W hdev).fderiv
    rw [← hlog.fderiv] at hraw
    simpa only [Function.comp_apply, AW, BW, DW] using hraw
  have htelescope :
      AZ.comp BZ - AW.comp BW =
        (AZ - AW).comp BZ + AW.comp (BZ - BW) := by
    apply ContinuousLinearMap.ext
    intro H
    change AZ (BZ H) - AW (BW H) =
      (AZ (BZ H) - AW (BZ H)) + AW (BZ H - BW H)
    rw [AW.map_sub]
    abel
  have hAZAW :
      ‖AZ - AW‖ ≤ nearLogSecondDerivativeBudget q *
          (cmp102SourceFourContourDeviationValueLipschitzBudget d M r *
            ‖Z - W‖) := by
    exact
      (norm_fderiv_nearLog_sub_le_secondDerivativeBudget
        hq0 hq1 hDZ hDW).trans
        (mul_le_mul_of_nonneg_left
          (norm_cmp98UbarAmbientDeviationMatrix_sub_le_sourceLengthBudget
            U b x hx Z W hr hZ hW)
          (nearLogSecondDerivativeBudget_nonneg q hq0))
  have hBZ :
      ‖BZ‖ ≤ cmp102SourceFourContourDeviationDerivativeBudget d M r := by
    exact
      norm_fderiv_cmp98UbarAmbientDeviationMatrix_le_sourceLengthBudget
        U b x hx Z hr hZ
  have hAW : ‖AW‖ ≤ nearLogDerivativeBudget q := by
    exact norm_fderiv_nearLog_le_derivativeBudget hq0 hq1 hDW
  have hBZBW :
      ‖BZ - BW‖ ≤
        cmp102SourceFourContourDeviationDerivativeLipschitzBudget d M r *
          ‖Z - W‖ := by
    exact
      norm_fderiv_cmp98UbarAmbientDeviationMatrix_sub_le_sourceLengthBudget
        U b x hx Z W hr hZ hW
  have hL0 :
      0 ≤ cmp102SourceFourContourDeviationValueLipschitzBudget d M r := by
    exact cmp98AmbientWilsonLineValueLipschitzBudget_nonneg hr _
  rw [hcompZ, hcompW, htelescope]
  calc
    ‖(AZ - AW).comp BZ + AW.comp (BZ - BW)‖
        ≤ ‖(AZ - AW).comp BZ‖ + ‖AW.comp (BZ - BW)‖ :=
      norm_add_le ((AZ - AW).comp BZ) (AW.comp (BZ - BW))
    _ ≤ ‖AZ - AW‖ * ‖BZ‖ + ‖AW‖ * ‖BZ - BW‖ := by
      gcongr
      · exact ContinuousLinearMap.opNorm_comp_le _ _
      · exact ContinuousLinearMap.opNorm_comp_le _ _
    _ ≤
        (nearLogSecondDerivativeBudget q *
            (cmp102SourceFourContourDeviationValueLipschitzBudget d M r *
              ‖Z - W‖)) *
            cmp102SourceFourContourDeviationDerivativeBudget d M r +
          nearLogDerivativeBudget q *
            (cmp102SourceFourContourDeviationDerivativeLipschitzBudget d M r *
              ‖Z - W‖) := by
      apply add_le_add
      · exact mul_le_mul hAZAW hBZ (norm_nonneg BZ)
          (mul_nonneg
            (nearLogSecondDerivativeBudget_nonneg q hq0)
            (mul_nonneg hL0 (norm_nonneg _)))
      · exact mul_le_mul hAW hBZBW (norm_nonneg (BZ - BW))
          (nearLogDerivativeBudget_nonneg q hq0)
    _ = cmp102SourceLocalNearLogDerivativeLipschitzBudget d M r q *
          ‖Z - W‖ := by
      unfold cmp102SourceLocalNearLogDerivativeLipschitzBudget
      ring

end

end YangMills.RG
