import YangMills.RG.BalabanCMP99SourceActiveRegionFullCompanionPrecisionDecay

#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecisionUpperBound
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecisionUpperBound_pos
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanion_QprimeMass_finiteRange
#print axioms YangMills.RG.norm_cmp99SourceActiveRegionFullCompanionPrecision_le
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecision_kernelBound
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecision_finiteRange
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionPrecision_exponentialKernelBound
