import YangMills.RG.BalabanCMP99SourceGeneratedSectionCBasicFactor

open YangMills.RG

#print axioms cmp99SourceGeneratedPhysicalFineBasicFactorNormBound
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalFineSectionCPrecisionCommutator
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalFineSectionCBasicFactor
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalFineSectionCBasicFactor_eq_source
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedPhysicalFineSectionCBasicFactor_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalFineSectionCBasicFactorCertificate
