import YangMills.RG.BalabanCMP102Eq80PhysicalFineHeadTailSourceMetricLayerWordSum

#print axioms YangMills.RG.cmp102Eq80PhysicalLayerWordSourceMetricDecayPrefactor
#print axioms YangMills.RG.norm_cmp102Eq80PhysicalLayerWordDomainMatrixCoefficient_le_sourceMetricProduct
#print axioms YangMills.RG.summable_cmp102Eq80PhysicalLayerWordSourceMetricProduct
#print axioms YangMills.RG.cmp102Eq80PhysicalNeumannDomainMatrixCoefficient
#print axioms YangMills.RG.summable_cmp102Eq80PhysicalLayerWordDomainMatrixCoefficient_of_sourceMetricSplit
