import YangMills.RG.BalabanCMP99SourceGeneratedSectionCHeadSupport

namespace YangMills.RG

#print axioms cmp95PeriodicCoordinateSupport
#print axioms cmp95PeriodicSquareWeight_eq_zero_of_not_support
#print axioms cmp95PeriodicTensorSupport
#print axioms cmp95PeriodicTensorCutoff_eq_zero_of_not_support
#print axioms cmp95SourcePeriodicCoarseCellSupport
#print axioms cmp95SourcePeriodicCoarseSquarePartition_value_eq_zero_of_not_support
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadFactorCoordinates_apply_single_eq_zero_of_target
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadFactorCoordinates_apply_single_eq_zero_of_source
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadFactorCoordinates_apply_single_eq_zero_of_endpoint

end YangMills.RG
