import YangMills.RG.BalabanCMP99SourceLocalizedRetainedTower

#print axioms YangMills.RG.CMP99SourceLocalizedRetainedTower
#print axioms YangMills.RG.cmp99SourceLocalizedRetainedTower
#print axioms YangMills.RG.CMP99SourceLocalizedRetainedTower.terminalQprime_eq
#print axioms YangMills.RG.CMP99SourceLocalizedRetainedTower.terminalQprime_transport_eq
