import YangMills.RG.BalabanCMP89Eq249NoncentralRealGap

/-! Cold-sealed axiom audit for the mass-uniform noncentral CMP89 gap. -/

#print axioms YangMills.RG.one_div_nine_le_cmp89Eq245ScaledLaplacianSymbol_noncentral_alias
#print axioms YangMills.RG.cmp89Eq245ScaledLaplacianSymbol_noncentral_alias_pos
#print axioms YangMills.RG.cmp89Eq250AliasDenominatorSummand_noncentral_nonneg
#print axioms YangMills.RG.cmp89Eq249RealNoncentralAliasSum_nonneg_massUniform
#print axioms YangMills.RG.cmp89Eq249CentralStabilizedLowerConstant_le_real_massUniform
#print axioms YangMills.RG.cmp89Eq249CentralStabilizedLowerConstant_le_re_massUniform
#print axioms YangMills.RG.cmp85Eq215Floor_le_cmp89Eq249CentralStabilizedAliasDenominator_re_massUniform
