import YangMills.RG.BalabanCMP116Eq221PhysicalCoordinateBridge

#print axioms YangMills.RG.PhysicalGaugeCMP116Dictionary.sum_norm_sq_flatPhysicalLinearIsometryEquiv_physicalInteriorBonds
#print axioms YangMills.RG.PhysicalGaugeCMP116Dictionary.sum_norm_sq_flatPhysicalLinearIsometryEquiv_physicalInteriorBonds_eq_dotProduct
#print axioms YangMills.RG.CMP116Eq216PhysicalKernelCertificate.three_operator_forms_le_coordinateLocalization_geometric
#print axioms YangMills.RG.CMP116Eq216PhysicalKernelCertificate.three_operator_forms_absorb_into_coordinateAlpha5_geometric
#print axioms YangMills.RG.CMP116Eq216PhysicalKernelCertificate.interactionExponent_le_coordinateAlpha5_geometric
