import YangMills.RG.BalabanCMP99SourceEq395GlobalRegionalMiddleDecay

#print axioms YangMills.RG.cmp99SourceTerminalCLMTransport_rectangularSandwich
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleGreenTransportPhysical
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleGreenTransportCoordinates_eq_physical
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectTerminalCoordinates
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectTerminalCoordinates_eq_physical
