import YangMills.RG.BalabanCMP99SourceActiveRegionFullCompanionZeroDepthGreen


namespace YangMills.RG

#print axioms cmp99SourceActiveRegionFullCompanionDirichletPrecision_zero
#print axioms isCoerciveCLM_cmp99SourceActiveRegionFullCompanionDirichletPrecision_zero
#print axioms cmp99SourceActiveRegionFullCompanionDirichletGreen_zero
#print axioms cmp99SourceActiveRegionFullCompanionDirichletPrecision_comp_green_zero
#print axioms cmp99SourceActiveRegionFullCompanionDirichletGreen_comp_precision_zero
#print axioms norm_cmp99SourceActiveRegionFullCompanionDirichletGreen_zero_le

end YangMills.RG
