import YangMills.RG.BalabanCMP99SourceRetainedPhysicalPrecision

namespace YangMills.RG

#print axioms cmp99ActiveRegionSourceCovariantD0CLM
#print axioms cmp99ActiveRegionSourceCovariantLaplacian
#print axioms inner_cmp99ActiveRegionSourceCovariantLaplacian
#print axioms cmp99ActiveRegionSourceCovariantLaplacian_isSymmetric
#print axioms norm_cmp99ActiveRegionSourceCovariantD0CLM_le
#print axioms norm_cmp99ActiveRegionSourceCovariantLaplacian_le
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalGaugePrecision
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalGaugePrecision_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalPrecisionUpperBound
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalPrecisionUpperBound_pos
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.norm_physicalGaugePrecision_le_physicalPrecisionUpperBound

end YangMills.RG
