/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116RestrictedVisitedTransfer

/-!
# Recursive sum of restricted visited-state tails

The source finite family `cmp99AdmissibleTails` is generated recursively from
the physical successor family.  This file proves that summing the exact
visited-state operator product over that family is identical to the matching
finite transfer recursion.

This is the finite-layer reindexing needed before identifying the recursion
with powers of the augmented transfer matrix.
-/

namespace YangMills.RG

noncomputable section

universe u v w

/-- Recursive continuation sum generated by one finite physical successor
family. -/
def cmp116RestrictedVisitedTailSum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ) :
    ℕ → Domain → CMP116RestrictedVisitedState carrier →
      Matrix Index Index ℂ
  | 0, _, _ => 1
  | n + 1, X, visited =>
      ∑ step ∈ successors X,
        CMP116RestrictedVisitedState.transitionWeight
            carrier sigma visited (domainActive step.domain) •
          (R step.label step.domain *
            cmp116RestrictedVisitedTailSum
              carrier domainActive successors R sigma n step.domain
              (CMP116RestrictedVisitedState.update
                carrier visited (domainActive step.domain)))

/-- Direct source sum over the literal finite family of admissible tails. -/
def cmp116RestrictedVisitedGeneratedTailSum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ)
    (n : ℕ) (X : Domain)
    (visited : CMP116RestrictedVisitedState carrier) :
    Matrix Index Index ℂ :=
  ∑ tail ∈ cmp99AdmissibleTails successors X n,
    cmp116RestrictedVisitedTailProduct
      carrier domainActive R sigma visited tail

private theorem cmp99AdmissibleTailConsImages_pairwiseDisjoint
    {Label : Type u} {Domain : Type v}
    [DecidableEq Label] [DecidableEq Domain]
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (X : Domain) (n : ℕ) :
    (↑(successors X) : Set _).PairwiseDisjoint
      (fun step =>
        (cmp99AdmissibleTails successors step.domain n).image
          (step :: ·)) := by
  intro left _ right _ hne
  change Disjoint
    ((cmp99AdmissibleTails successors left.domain n).image
      (left :: ·))
    ((cmp99AdmissibleTails successors right.domain n).image
      (right :: ·))
  rw [Finset.disjoint_left]
  intro tail hleft hright
  simp only [Finset.mem_image] at hleft hright
  obtain ⟨leftRest, _hleftRest, rfl⟩ := hleft
  obtain ⟨rightRest, _hrightRest, hEq⟩ := hright
  exact hne (List.cons.inj hEq.symm).1

/-- The direct finite source sum is exactly the recursive visited-state
transfer sum, at every length and every initial visited state. -/
theorem cmp116RestrictedVisitedGeneratedTailSum_eq_tailSum
    {Label : Type u} {Domain : Type v} {Delta : Type w}
    [DecidableEq Label] [DecidableEq Domain] [DecidableEq Delta]
    {Index : Type*} [Fintype Index] [DecidableEq Index]
    (carrier : Finset Delta)
    (domainActive : Domain → Finset Delta)
    (successors : Domain → Finset (CMP99WalkStep Label Domain))
    (R : Label → Domain → Matrix Index Index ℂ)
    (sigma : Delta → ℂ) :
    ∀ (n : ℕ) (X : Domain)
      (visited : CMP116RestrictedVisitedState carrier),
      cmp116RestrictedVisitedGeneratedTailSum
          carrier domainActive successors R sigma n X visited =
        cmp116RestrictedVisitedTailSum
          carrier domainActive successors R sigma n X visited := by
  intro n
  induction n with
  | zero =>
      intro X visited
      simp [cmp116RestrictedVisitedGeneratedTailSum,
        cmp99AdmissibleTails, cmp116RestrictedVisitedTailSum,
        cmp116RestrictedVisitedTailProduct]
  | succ n ih =>
      intro X visited
      rw [cmp116RestrictedVisitedGeneratedTailSum,
        cmp99AdmissibleTails,
        Finset.sum_biUnion
          (cmp99AdmissibleTailConsImages_pairwiseDisjoint
            successors X n)]
      simp only [cmp116RestrictedVisitedTailSum]
      apply Finset.sum_congr rfl
      intro step _hstep
      rw [Finset.sum_image]
      · simp only [cmp116RestrictedVisitedTailProduct]
        rw [← Finset.smul_sum]
        apply congrArg
          (fun T : Matrix Index Index ℂ =>
            CMP116RestrictedVisitedState.transitionWeight
                carrier sigma visited (domainActive step.domain) • T)
        rw [← Finset.mul_sum]
        apply congrArg
          (fun T : Matrix Index Index ℂ =>
            R step.label step.domain * T)
        exact ih step.domain
          (CMP116RestrictedVisitedState.update
            carrier visited (domainActive step.domain))
      · intro left _ right _ hEq
        exact (List.cons.inj hEq).2

end

end YangMills.RG
