/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116CenteredConditionedCombinedEq80PartialEq136
import YangMills.RG.BalabanCMP116Eq226CenteredConditionedPhysicalTermSource
import YangMills.RG.BalabanCMP116Eq80Lemma1CombinedHessianSupport
import YangMills.RG.BalabanCMP116Eq226OptimalInteractionAlpha

/-!
# Combined partial centered-conditioned term-source constructor

**PRE-VALIDATION.** The source is present in this Git checkpoint, but its
`.olean` has not yet been materialized from this checkpoint and the result is
not yet verified by the Lean compiler.

This module assembles the canonical direct/native equation-(80)/Lemma-1
potential into the centered-conditioned equation-(2.26) source record.  The
private helper builds the pre-`(1.36)` telescope; a separate ledger pins its
literal total, residual, domains, amplitude, and cutoff threshold before the
final field is generated.

The public constructor does not expose a pointwise equation-(1.36) premise.
Its residual and total functions are identified with the literal combined
ledger, and the final bound is generated by the source-specific theorem.
-/

namespace YangMills.RG

noncomputable section

private abbrev CombinedConstructorBond (M Q : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  PhysicalBond 4 (M * (2 * Q))

private abbrev CombinedConstructorFineField (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  FinePhysicalOneCochain 4 M (2 * Q) Nc

private abbrev CombinedConstructorCoarseField (Q Nc : ℕ)
    [NeZero (2 * Q)] :=
  CoarsePhysicalOneCochain 4 (2 * Q) Nc

private abbrev CombinedConstructorRectangularFieldMap (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  CombinedConstructorCoarseField Q Nc →L[ℝ]
    CombinedConstructorFineField M Q Nc

private noncomputable def
    assembleCMP116Eq226CenteredConditionedCombinedPartialPreEq136
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (Y0 P : Finset (CombinedConstructorBond M Q))
    (Z0 Z : Finset (FinBox 4 (2 * Q))) :=
  fun base
      anchor contourCarrier carrier_subset_sigmaZero carrier_subset_Z0
      Z0_subset_Z contourEquiv K root sourceRange sourceRange_bound
      finiteRange coercivityConstant mass coercivity_pos mass_pos K_coercive
      patchedDefect_small Ahead rho rate radius Ahead_nonneg rho_nonneg
      rate_pos shell_small patchCertificate distance_triangle Delta
      degree_bound one_le_Delta radius_nonneg radius_cap contour_series_small
      neumann_small neumann_transpose_small total residual smooth
      kernelSupport domainMetric domainCard domainSupport E0 epsilon1 C1
      alpha4 C3 C2 kappa1 delta kappa gk rowSum threshold alpha gamma q
      gapScale gapCard qBound qBound_nonneg qBound_lt_one rootBound
      volumeRate conditionedCovariance conditionedRoot
      conditionedCovariance_nondegenerate E0_pos epsilon1_pos C1_pos
      alpha4_pos C3_nonneg C3_le one_le_M eight_le_q one_lt_kappa1
      source_budget domainMetric_nonneg exponential_row_bound metric_budget
      hessian_zero_off_support eq143 interaction_budget deltaRadius_eq
      normalizedGap yRadius_eq gk_ne threshold_eq alpha_nonneg root_small
      gamma_nonneg threshold_nonneg outer_small domain_nonempty domain_subset
      rootBound_nonneg rooted_residual volume_budget =>
    ({
      base := base
      anchor := anchor
      contourCarrier := contourCarrier
      carrier_subset_sigmaZero := carrier_subset_sigmaZero
      carrier_subset_Z0 := carrier_subset_Z0
      Z0_subset_Z := Z0_subset_Z
      contourEquiv := contourEquiv
      K := K
      root := root
      sourceRange := sourceRange
      sourceRange_bound := sourceRange_bound
      finiteRange := finiteRange
      coercivityConstant := coercivityConstant
      mass := mass
      coercivity_pos := coercivity_pos
      mass_pos := mass_pos
      K_coercive := K_coercive
      patchedDefect_small := patchedDefect_small
      Ahead := Ahead
      rho := rho
      rate := rate
      radius := radius
      Ahead_nonneg := Ahead_nonneg
      rho_nonneg := rho_nonneg
      rate_pos := rate_pos
      shell_small := shell_small
      patchCertificate := patchCertificate
      distance_triangle := distance_triangle
      Delta := Delta
      degree_bound := degree_bound
      one_le_Delta := one_le_Delta
      radius_nonneg := radius_nonneg
      radius_cap := radius_cap
      contour_series_small := contour_series_small
      neumann_small := neumann_small
      neumann_transpose_small := neumann_transpose_small
      total := total
      residual := residual
      smooth := smooth
      kernelSupport := kernelSupport
      domainMetric := domainMetric
      domainCard := domainCard
      domainSupport := domainSupport
      E0 := E0
      epsilon1 := epsilon1
      C1 := C1
      alpha4 := alpha4
      C3 := C3
      C2 := C2
      kappa1 := kappa1
      delta := delta
      kappa := kappa
      gk := gk
      rowSum := rowSum
      threshold := threshold
      alpha := alpha
      gamma := gamma
      q := q
      gapScale := gapScale
      gapCard := gapCard
      qBound := qBound
      qBound_nonneg := qBound_nonneg
      qBound_lt_one := qBound_lt_one
      rootBound := rootBound
      volumeRate := volumeRate
      conditionedCovariance := conditionedCovariance
      conditionedRoot := conditionedRoot
      conditionedCovariance_nondegenerate :=
        conditionedCovariance_nondegenerate
      E0_pos := E0_pos
      epsilon1_pos := epsilon1_pos
      C1_pos := C1_pos
      alpha4_pos := alpha4_pos
      C3_nonneg := C3_nonneg
      C3_le := C3_le
      one_le_M := one_le_M
      eight_le_q := eight_le_q
      one_lt_kappa1 := one_lt_kappa1
      source_budget := source_budget
      domainMetric_nonneg := domainMetric_nonneg
      exponential_row_bound := exponential_row_bound
      metric_budget := metric_budget
      hessian_zero_off_support := hessian_zero_off_support
      eq143 := eq143
      interaction_budget := interaction_budget
      deltaRadius_eq := deltaRadius_eq
      normalizedGap := normalizedGap
      yRadius_eq := yRadius_eq
      gk_ne := gk_ne
      threshold_eq := threshold_eq
      alpha_nonneg := alpha_nonneg
      root_small := root_small
      gamma_nonneg := gamma_nonneg
      threshold_nonneg := threshold_nonneg
      outer_small := outer_small
      domain_nonempty := domain_nonempty
      domain_subset := domain_subset
      rootBound_nonneg := rootBound_nonneg
      rooted_residual := rooted_residual
      volume_budget := volume_budget
    } : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z)

/-- Public field assembler for the pre-`(1.36)` terminal record.  It cannot
produce a `TermSource`: completing it still requires the separately derived
literal source estimate. -/
noncomputable def
    cmp116Eq226CenteredConditionedPartialPreEq136OfFields
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (Y0 P : Finset (CombinedConstructorBond M Q))
    (Z0 Z : Finset (FinBox 4 (2 * Q))) :=
  assembleCMP116Eq226CenteredConditionedCombinedPartialPreEq136
    (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z

/-- Identifies a pre-`(1.36)` record with the literal direct/native ledger.
These equalities prevent the finalizer from accepting an arbitrary residual,
domain dictionary, kernel support, amplitude, cutoff threshold, or interaction
coefficient.  The last equality is the canonical minimal choice allowed by
the interaction budget; it is a normalization, not an estimate of
`root_small` or `outer_small`. -/
structure CMP116CenteredConditionedCombinedEq80LedgerIdentification
    {Index : Type*} {nDelta M Q Nc n L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (P : Finset (CombinedConstructorBond M Q))
    (Z : Finset (FinBox 4 (2 * Q)))
    (anchor : FinBox 4 Q)
    (domains : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (V : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    (baseCoarseCovariance :
      CombinedConstructorCoarseField Q Nc →L[ℝ]
        CombinedConstructorCoarseField Q Nc)
    (layerWord : Fin n → ℕ)
    (D D₃ : CombinedConstructorFineField M Q Nc →
      CombinedConstructorCoarseField Q Nc)
    (V₀ : CombinedConstructorFineField M Q Nc → ℝ)
    (Pprop T : CombinedConstructorRectangularFieldMap M Q Nc)
    (DeltaPi : CombinedConstructorFineField M Q Nc →L[ℝ]
      CombinedConstructorFineField M Q Nc)
    (J : CombinedConstructorFineField M Q Nc)
    (E0Direct : ℝ)
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z)
    (choice : CMP99SourcePi4CoarseFineWalkChoice
      M Q S.sourceRange layerWord)
    (lemma1 : CMP109Lemma1Eq136SourceCertificate (q := S.q)
      E V S.gk D S.epsilon1 S.C1 S.C2 S.kappa1 S.delta S.kappa) : Prop where
  total_eq :
    S.total =
      cmp116CenteredConditionedCombinedEq80PartialTotal
        S.base.spectatorSupport S.base.fluctuationSupport anchor domains E V
        S.contourCarrier S.contourEquiv S.K S.coercivity_pos S.mass_pos
        S.K_coercive baseCoarseCovariance layerWord choice D D₃ V₀ Pprop T
        DeltaPi J S.gk
  residual_eq :
    S.residual =
      cmp116CenteredConditionedCombinedEq80PartialResidual
        S.base.spectatorSupport S.base.fluctuationSupport anchor domains E V
        S.contourCarrier S.contourEquiv S.K S.coercivity_pos S.mass_pos
        S.K_coercive baseCoarseCovariance layerWord choice D D₃ V₀ Pprop T
        DeltaPi J S.gk
  domainMetric_eq :
    S.domainMetric = cmp116Eq80Lemma1CombinedDomainMetric anchor domains E
  domainCard_eq :
    S.domainCard = cmp116Eq80Lemma1CombinedDomainCard anchor domains E
  domainSupport_eq :
    S.domainSupport = cmp116Eq80Lemma1CombinedDomainSupport anchor domains E
  kernelSupport_eq :
    S.kernelSupport = cmp116Eq80Lemma1CombinedKernelSupport anchor domains E
  E0_eq : S.E0 = E0Direct + lemma1.E0
  threshold_eq : S.threshold = S.epsilon1 / S.gk
  alpha_eq :
    S.alpha =
      cmp116Eq226OptimalInteractionAlpha
        (cmp116Eq220CenteredSourcePotentialRate Finset.univ
          (fun y => (S.domainMetric y : ℝ)) S.domainCard
          S.C3 S.epsilon1 M S.C2 S.kappa1 S.alpha4 S.rowSum)
        (cmp116SourcePi4PhysicalComplexR2BilateralBound
          S.K S.Delta S.Ahead S.rho S.rate S.radius (1 + S.radius))
        S.gamma

/-- Smoothness of an identified combined quadratic core is generated by its
literal fixed projected direct Hessian and the identically zero native core;
it is not an independent analytic input. -/
theorem CMP116CenteredConditionedCombinedEq80LedgerIdentification.smooth
    {Index : Type*} {nDelta M Q Nc n L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (P : Finset (CombinedConstructorBond M Q))
    (Z : Finset (FinBox 4 (2 * Q)))
    (anchor : FinBox 4 Q)
    (domains : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (V : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    (baseCoarseCovariance :
      CombinedConstructorCoarseField Q Nc →L[ℝ]
        CombinedConstructorCoarseField Q Nc)
    (layerWord : Fin n → ℕ)
    (D D₃ : CombinedConstructorFineField M Q Nc →
      CombinedConstructorCoarseField Q Nc)
    (V₀ : CombinedConstructorFineField M Q Nc → ℝ)
    (Pprop T : CombinedConstructorRectangularFieldMap M Q Nc)
    (DeltaPi : CombinedConstructorFineField M Q Nc →L[ℝ]
      CombinedConstructorFineField M Q Nc)
    (J : CombinedConstructorFineField M Q Nc)
    (E0Direct : ℝ)
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z)
    (choice : CMP99SourcePi4CoarseFineWalkChoice
      M Q S.sourceRange layerWord)
    (lemma1 : CMP109Lemma1Eq136SourceCertificate (q := S.q)
      E V S.gk D S.epsilon1 S.C1 S.C2 S.kappa1 S.delta S.kappa)
    (ledger : CMP116CenteredConditionedCombinedEq80LedgerIdentification
      Dict P Z anchor domains E V baseCoarseCovariance layerWord D D₃ V₀
      Pprop T DeltaPi J E0Direct S choice lemma1) :
    ∀ sigma psi phi y, ContDiff ℝ 2
      (cmp116Eq142PhysicalQuadraticCore
        (S.total sigma psi phi) (S.residual sigma psi phi) y) := by
  rw [ledger.total_eq, ledger.residual_eq]
  exact fun sigma psi phi =>
    contDiff_cmp116CenteredConditionedCombinedEq80PartialQuadraticCore
      S.base.spectatorSupport S.base.fluctuationSupport anchor domains E V
      S.contourCarrier S.contourEquiv S.K S.coercivity_pos S.mass_pos
      S.K_coercive baseCoarseCovariance sigma psi phi layerWord choice
      D D₃ V₀ Pprop T DeltaPi J S.gk

/-- For an identified literal combined ledger, the terminal off-support
Hessian field is generated by the bilateral direct projection and exact
native cancellation.  In particular it is independent of the corresponding
field stored in `S`. -/
theorem
    CMP116CenteredConditionedCombinedEq80LedgerIdentification.hessian_zero_off_support
    {Index : Type*} {nDelta M Q Nc n L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (P : Finset (CombinedConstructorBond M Q))
    (Z : Finset (FinBox 4 (2 * Q)))
    (anchor : FinBox 4 Q)
    (domains : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (V : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    (baseCoarseCovariance :
      CombinedConstructorCoarseField Q Nc →L[ℝ]
        CombinedConstructorCoarseField Q Nc)
    (layerWord : Fin n → ℕ)
    (D D₃ : CombinedConstructorFineField M Q Nc →
      CombinedConstructorCoarseField Q Nc)
    (V₀ : CombinedConstructorFineField M Q Nc → ℝ)
    (Pprop T : CombinedConstructorRectangularFieldMap M Q Nc)
    (DeltaPi : CombinedConstructorFineField M Q Nc →L[ℝ]
      CombinedConstructorFineField M Q Nc)
    (J : CombinedConstructorFineField M Q Nc)
    (E0Direct : ℝ)
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z)
    (choice : CMP99SourcePi4CoarseFineWalkChoice
      M Q S.sourceRange layerWord)
    (lemma1 : CMP109Lemma1Eq136SourceCertificate (q := S.q)
      E V S.gk D S.epsilon1 S.C1 S.C2 S.kappa1 S.delta S.kappa)
    (ledger : CMP116CenteredConditionedCombinedEq80LedgerIdentification
      Dict P Z anchor domains E V baseCoarseCovariance layerWord D D₃ V₀
      Pprop T DeltaPi J E0Direct S choice lemma1) :
    ∀ psi phi sigma,
      CMP116Eq214ShiftedPolydisc nDelta S.base.deltaRadius sigma →
      ∀ b y source target,
        ¬ S.kernelSupport y source target →
          ∀ (v w : SUNLieCoord Nc), ∀ t ∈ Set.Icc (0 : ℝ) 1,
            cmp116FDerivHessian
              (cmp116Eq142PhysicalQuadraticCore
                (S.total sigma
                  (restrictGlobal S.base.spectatorSupport psi)
                  (restrictGlobal S.base.fluctuationSupport phi))
                (S.residual sigma
                  (restrictGlobal S.base.spectatorSupport psi)
                  (restrictGlobal S.base.fluctuationSupport phi)) y)
              (t • physicalBondProjection
                (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds
                  (cmp116Eq80Lemma1CombinedCenteredRegion
                    anchor domains E P))
                (cmp116SourcePhysicalCoordinateCochain b))
              (singlePhysicalBondCochain
                (d := 4) (N := M * (2 * Q)) (Nc := Nc) source v)
              (singlePhysicalBondCochain
                (d := 4) (N := M * (2 * Q)) (Nc := Nc) target w) = 0 := by
  rw [ledger.kernelSupport_eq, ledger.total_eq, ledger.residual_eq]
  exact
    cmp116CenteredConditionedCombinedEq80_hessian_zero_off_support
      S.base.spectatorSupport S.base.fluctuationSupport anchor domains E V
      S.contourCarrier S.contourEquiv S.base.deltaRadius
      (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds
        (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P))
      S.K S.coercivity_pos S.mass_pos S.K_coercive baseCoarseCovariance
      layerWord choice D D₃ V₀ Pprop T DeltaPi J S.gk

set_option maxHeartbeats 1800000 in
set_option synthInstance.maxHeartbeats 280000 in
/-- The missing final field for an identified combined pre-source.  The
direct estimate is generated by the equation-(80) third-jet chain and the
native estimate is exactly the named CMP109 Lemma-1 certificate. -/
theorem cmp116CenteredConditionedCombinedPartialPreEq136_eq136
    {Index : Type*} {nDelta M Q Nc n L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (P : Finset (CombinedConstructorBond M Q))
    (Z : Finset (FinBox 4 (2 * Q)))
    (anchor : FinBox 4 Q)
    (domains : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (V : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    (baseCoarseCovariance :
      CombinedConstructorCoarseField Q Nc →L[ℝ]
        CombinedConstructorCoarseField Q Nc)
    (layerWord : Fin n → ℕ)
    (D D₃ : CombinedConstructorFineField M Q Nc →
      CombinedConstructorCoarseField Q Nc)
    (V₀ : CombinedConstructorFineField M Q Nc → ℝ)
    (Pprop T : CombinedConstructorRectangularFieldMap M Q Nc)
    (DeltaPi : CombinedConstructorFineField M Q Nc →L[ℝ]
      CombinedConstructorFineField M Q Nc)
    (J : CombinedConstructorFineField M Q Nc)
    (E0Direct : ℝ)
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z)
    (choice : CMP99SourcePi4CoarseFineWalkChoice
      M Q S.sourceRange layerWord)
    (lemma1 : CMP109Lemma1Eq136SourceCertificate (q := S.q)
      E V S.gk D S.epsilon1 S.C1 S.C2 S.kappa1 S.delta S.kappa)
    (ledger : CMP116CenteredConditionedCombinedEq80LedgerIdentification
      Dict P Z anchor domains E V baseCoarseCovariance layerWord D D₃ V₀
      Pprop T DeltaPi J E0Direct S choice lemma1)
    (hD : ContDiff ℝ ⊤ D) (hD₃ : ContDiff ℝ ⊤ D₃)
    (hV₀ : ContDiff ℝ ⊤ V₀)
    (C Rjet sourceJetBound : ℝ)
    (hsourceJetBound : 0 ≤ sourceJetBound)
    (hC : ∀ X, cmp98SourceFieldSupNorm X ≤ S.epsilon1 / S.gk →
      ∀ t ∈ Set.uIoc (0 : ℝ) 1, ∀ j, j ≤ 4 →
        ‖iteratedFDeriv ℝ j V₀
          (cmp102Eq80JointRemainderInner
            D (Pprop + t • T,
              cmp109ConstrainedLinearFluctuation (L := M) S.gk X))‖ ≤ C)
    (hRjet : ∀ X, cmp98SourceFieldSupNorm X ≤ S.epsilon1 / S.gk →
      ∀ t ∈ Set.uIoc (0 : ℝ) 1, ∀ j,
        1 ≤ j → j ≤ 4 →
        ‖iteratedFDeriv ℝ j
            (fun z : CombinedConstructorRectangularFieldMap M Q Nc ×
                CombinedConstructorFineField M Q Nc => z.2)
            (Pprop + t • T,
              cmp109ConstrainedLinearFluctuation (L := M) S.gk X)‖ +
          cmp102Eq80JointEvaluationJetMajorant D j
            (Pprop + t • T,
              cmp109ConstrainedLinearFluctuation (L := M) S.gk X) ≤
            Rjet ^ j)
    (hsourceJet : ∀ X,
      cmp98SourceFieldSupNorm X ≤ S.epsilon1 / S.gk →
      ∀ t ∈ Set.uIoc (0 : ℝ) 1,
        max
          (cmp102Eq80JointPotentialSourceJetMajorant
            D D₃ DeltaPi J 4
              (Pprop + t • T,
                cmp109ConstrainedLinearFluctuation (L := M) S.gk X)
              C Rjet) 0 ≤ sourceJetBound)
    (cardRatio metricRatio summationRatio kappaCard : ℝ)
    (hcardRatio0 : 0 ≤ cardRatio)
    (hmetricRatio0 : 0 ≤ metricRatio)
    (hsummation0 : 0 ≤ summationRatio)
    (hkappaCard : 0 < kappaCard)
    (hE0Direct : 0 ≤ E0Direct)
    (hepsilon1_one : S.epsilon1 ≤ 1)
    (hC1 : 0 ≤ S.C1)
    (hresidualRate0 :
      0 ≤ cmp102Eq80Eq136ResidualMetricRate S.delta S.kappa)
    (hsplit :
      cmp102Eq80PhysicalFineHeadTailWalkRatio
          (M := M) baseCoarseCovariance S.Ahead S.rho S.rate
            (1 + S.radius) ≤
        cardRatio * (metricRatio * summationRatio))
    (hcardDecay :
      cardRatio ≤ Real.exp (-(kappaCard * 10000)))
    (hmetricDecay :
      metricRatio ≤ Real.exp
        (-(cmp102Eq80Eq136ResidualMetricRate S.delta S.kappa * 10000)))
    (hsmall :
      ((cmp116SourcePi4TerminalBranching S.Delta : ℕ) : ℝ) *
        summationRatio < 1)
    (hbudget : CMP102Eq80Eq136ThirdJetProducerBudget
      (M := M) baseCoarseCovariance sourceJetBound kappaCard
      S.delta S.kappa summationRatio layerWord S.Delta S.q E0Direct
      S.C1 S.C2 S.kappa1) :
    ∀ psi phi sigma,
      CMP116Eq214ShiftedPolydisc nDelta S.base.deltaRadius sigma →
      ∀ b y,
        (-1 : ℂ) ^ P.card *
            cmp116SmallFieldCutoff
              (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier
                anchor domains E)
              S.threshold (cmp116SourcePhysicalCoordinateCochain b) *
            cmp116LargeFieldCutoff P S.threshold
              (cmp116SourcePhysicalCoordinateCochain b) ≠ 0 →
        |S.residual sigma
          (restrictGlobal S.base.spectatorSupport psi)
          (restrictGlobal S.base.fluctuationSupport phi) y
          (physicalBondProjection
            (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds
              (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P))
            (cmp116SourcePhysicalCoordinateCochain b))| ≤
          cmp116Eq136ResidualMajorant S.E0 S.epsilon1 S.C1 M S.q
            S.C2 S.kappa1 S.delta S.kappa (S.domainMetric y : ℝ) := by
  intro psi phi sigma hsigma b y hcutoff
  rw [ledger.threshold_eq] at hcutoff
  rw [ledger.residual_eq, ledger.E0_eq, ledger.domainMetric_eq]
  exact
    abs_cmp116CenteredConditionedCombinedEq80PartialResidual_le_eq136
      Dict S.base.spectatorSupport S.base.fluctuationSupport anchor domains
      E V P S.contourCarrier S.contourEquiv S.base.deltaRadius S.radius
      S.radius_nonneg S.radius_cap S.K S.coercivity_pos S.mass_pos
      S.K_coercive baseCoarseCovariance S.Ahead_nonneg S.rho_nonneg
      S.rate_pos S.shell_small S.patchCertificate S.sourceRange_bound
      S.degree_bound S.one_le_Delta sigma hsigma S.contour_series_small
      layerWord choice D D₃ V₀ Pprop T DeltaPi J S.gk S.epsilon1 S.C1
      S.C2 S.kappa1 S.delta S.kappa lemma1 hD hD₃ hV₀ C Rjet
      sourceJetBound hsourceJetBound hC hRjet hsourceJet hcardRatio0
      hmetricRatio0 hsummation0 hkappaCard E0Direct hE0Direct
      hepsilon1_one hC1 hresidualRate0 hsplit hcardDecay hmetricDecay
      hsmall hbudget b hcutoff
      (restrictGlobal S.base.spectatorSupport psi)
      (restrictGlobal S.base.fluctuationSupport phi) y

/-- Source-facing analytic inputs used to generate the direct equation-(80)
part of `(1.36)`.  The structure contains component jets and explicit random
walk budgets, never a residual bound or a completed `TermSource`. -/
structure CMP116CenteredConditionedCombinedEq80Eq136AnalyticInputs
    {Index : Type*} {nDelta M Q Nc n L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (P : Finset (CombinedConstructorBond M Q))
    (Z : Finset (FinBox 4 (2 * Q)))
    (anchor : FinBox 4 Q)
    (domains : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (V : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    (baseCoarseCovariance :
      CombinedConstructorCoarseField Q Nc →L[ℝ]
        CombinedConstructorCoarseField Q Nc)
    (layerWord : Fin n → ℕ)
    (D D₃ : CombinedConstructorFineField M Q Nc →
      CombinedConstructorCoarseField Q Nc)
    (V₀ : CombinedConstructorFineField M Q Nc → ℝ)
    (Pprop T : CombinedConstructorRectangularFieldMap M Q Nc)
    (DeltaPi : CombinedConstructorFineField M Q Nc →L[ℝ]
      CombinedConstructorFineField M Q Nc)
    (J : CombinedConstructorFineField M Q Nc)
    (E0Direct : ℝ)
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z)
    (choice : CMP99SourcePi4CoarseFineWalkChoice
      M Q S.sourceRange layerWord) where
  hD : ContDiff ℝ ⊤ D
  hD₃ : ContDiff ℝ ⊤ D₃
  hV₀ : ContDiff ℝ ⊤ V₀
  C : ℝ
  Rjet : ℝ
  sourceJetBound : ℝ
  hsourceJetBound : 0 ≤ sourceJetBound
  hC : ∀ X, cmp98SourceFieldSupNorm X ≤ S.epsilon1 / S.gk →
    ∀ t ∈ Set.uIoc (0 : ℝ) 1, ∀ j, j ≤ 4 →
      ‖iteratedFDeriv ℝ j V₀
        (cmp102Eq80JointRemainderInner
          D (Pprop + t • T,
            cmp109ConstrainedLinearFluctuation (L := M) S.gk X))‖ ≤ C
  hRjet : ∀ X, cmp98SourceFieldSupNorm X ≤ S.epsilon1 / S.gk →
    ∀ t ∈ Set.uIoc (0 : ℝ) 1, ∀ j,
      1 ≤ j → j ≤ 4 →
      ‖iteratedFDeriv ℝ j
          (fun z : CombinedConstructorRectangularFieldMap M Q Nc ×
              CombinedConstructorFineField M Q Nc => z.2)
          (Pprop + t • T,
            cmp109ConstrainedLinearFluctuation (L := M) S.gk X)‖ +
        cmp102Eq80JointEvaluationJetMajorant D j
          (Pprop + t • T,
            cmp109ConstrainedLinearFluctuation (L := M) S.gk X) ≤ Rjet ^ j
  hsourceJet : ∀ X, cmp98SourceFieldSupNorm X ≤ S.epsilon1 / S.gk →
    ∀ t ∈ Set.uIoc (0 : ℝ) 1,
      max
        (cmp102Eq80JointPotentialSourceJetMajorant
          D D₃ DeltaPi J 4
            (Pprop + t • T,
              cmp109ConstrainedLinearFluctuation (L := M) S.gk X)
            C Rjet) 0 ≤ sourceJetBound
  cardRatio : ℝ
  metricRatio : ℝ
  summationRatio : ℝ
  kappaCard : ℝ
  hcardRatio0 : 0 ≤ cardRatio
  hmetricRatio0 : 0 ≤ metricRatio
  hsummation0 : 0 ≤ summationRatio
  hkappaCard : 0 < kappaCard
  hE0Direct : 0 ≤ E0Direct
  hepsilon1_one : S.epsilon1 ≤ 1
  hC1 : 0 ≤ S.C1
  hresidualRate0 :
    0 ≤ cmp102Eq80Eq136ResidualMetricRate S.delta S.kappa
  hsplit :
    cmp102Eq80PhysicalFineHeadTailWalkRatio
        (M := M) baseCoarseCovariance S.Ahead S.rho S.rate
          (1 + S.radius) ≤
      cardRatio * (metricRatio * summationRatio)
  hcardDecay : cardRatio ≤ Real.exp (-(kappaCard * 10000))
  hmetricDecay : metricRatio ≤ Real.exp
    (-(cmp102Eq80Eq136ResidualMetricRate S.delta S.kappa * 10000))
  hsmall :
    ((cmp116SourcePi4TerminalBranching S.Delta : ℕ) : ℝ) *
      summationRatio < 1
  hbudget : CMP102Eq80Eq136ThirdJetProducerBudget
    (M := M) baseCoarseCovariance sourceJetBound kappaCard
    S.delta S.kappa summationRatio layerWord S.Delta S.q E0Direct
    S.C1 S.C2 S.kappa1

set_option maxHeartbeats 1800000 in
/-- First non-circular partial constructor of the centered-conditioned
equation-(2.26) source.  All fields other than `(1.36)` arrive in `S`; the
literal combined ledger is pinned by `ledger`, and `(1.36)` is generated from
`analytic` plus the named Lemma-1 certificate. -/
noncomputable def
    cmp116Eq226CenteredConditionedCombinedPartialTermSourceOfPreEq136
    {Index : Type*} {nDelta M Q Nc n L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (P : Finset (CombinedConstructorBond M Q))
    (Z : Finset (FinBox 4 (2 * Q)))
    (anchor : FinBox 4 Q)
    (domains : Finset (CMP102Eq80SourcePi4PhysicalDomainLabel anchor))
    (E : CMP109LocalizedActionExpansion Index 2 (M * (2 * Q)) Nc)
    (V : PhysicalGaugeBackground 4 (M * (2 * Q)) Nc)
    (baseCoarseCovariance :
      CombinedConstructorCoarseField Q Nc →L[ℝ]
        CombinedConstructorCoarseField Q Nc)
    (layerWord : Fin n → ℕ)
    (D D₃ : CombinedConstructorFineField M Q Nc →
      CombinedConstructorCoarseField Q Nc)
    (V₀ : CombinedConstructorFineField M Q Nc → ℝ)
    (Pprop T : CombinedConstructorRectangularFieldMap M Q Nc)
    (DeltaPi : CombinedConstructorFineField M Q Nc →L[ℝ]
      CombinedConstructorFineField M Q Nc)
    (J : CombinedConstructorFineField M Q Nc)
    (E0Direct : ℝ)
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z)
    (choice : CMP99SourcePi4CoarseFineWalkChoice
      M Q S.sourceRange layerWord)
    (lemma1 : CMP109Lemma1Eq136SourceCertificate (q := S.q)
      E V S.gk D S.epsilon1 S.C1 S.C2 S.kappa1 S.delta S.kappa)
    (ledger : CMP116CenteredConditionedCombinedEq80LedgerIdentification
      Dict P Z anchor domains E V baseCoarseCovariance layerWord D D₃ V₀
      Pprop T DeltaPi J E0Direct S choice lemma1)
    (analytic : CMP116CenteredConditionedCombinedEq80Eq136AnalyticInputs
      Dict P Z anchor domains E V baseCoarseCovariance layerWord D D₃ V₀
      Pprop T DeltaPi J E0Direct S choice) :
    CMP116Eq226CenteredConditionedPhysicalTermSource
      (nDelta := nDelta)
      (nY := CMP116Eq80Lemma1CombinedDomainCount anchor domains E)
      Dict
      (cmp116Eq80Lemma1CombinedSourceSmallFieldCarrier anchor domains E)
      P (cmp116Eq80Lemma1CombinedCenteredRegion anchor domains E P) Z :=
  ⟨S,
    cmp116CenteredConditionedCombinedPartialPreEq136_eq136
      Dict P Z anchor domains E V baseCoarseCovariance layerWord D D₃ V₀
      Pprop T DeltaPi J E0Direct S choice lemma1 ledger
      analytic.hD analytic.hD₃ analytic.hV₀ analytic.C analytic.Rjet
      analytic.sourceJetBound analytic.hsourceJetBound analytic.hC
      analytic.hRjet analytic.hsourceJet analytic.cardRatio
      analytic.metricRatio analytic.summationRatio analytic.kappaCard
      analytic.hcardRatio0 analytic.hmetricRatio0 analytic.hsummation0
      analytic.hkappaCard analytic.hE0Direct analytic.hepsilon1_one
      analytic.hC1 analytic.hresidualRate0 analytic.hsplit
      analytic.hcardDecay analytic.hmetricDecay analytic.hsmall
      analytic.hbudget⟩

end

end YangMills.RG
