/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80PhysicalDomainCoefficientThirdFieldDerivative
import YangMills.RG.BalabanCMP102Eq80PhysicalFineHeadTailSourceMetricDecay
import YangMills.RG.BalabanCMP102Eq80RectangularOrderFourJetRadius

/-!
# Source-metric bound for the literal CMP102 domain third field jet

The order-four source jet of the global equation-(80) potential and the
domain decay of a connected coefficient play different roles.  The source
maps `D`, `D₃`, and `V₀` provide a volume-uniform component-jet factor.  The
cardinality and tree-metric decay in `Y` is generated by the literal
random-walk domain matrix coefficient.

This separation is essential: requiring the same nonzero global source maps
to decay when an unrelated domain `Y` is moved would be false.  The terminal
theorem below therefore contains no scalar `sourceJetBound` and assumes no
bound for a completed domain activity.  Its source factor is the explicit
four-term majorant built from the component jets, while all `Y` dependence is
produced by the existing physical random-walk estimate.

This module does not yet prove uniform small-field bounds for the component
jets and does not identify the resulting majorant with equation (1.36).
-/

open scoped Matrix.Norms.Operator RealInnerProductSpace

namespace YangMills.RG

noncomputable section

private abbrev MetricFineField (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  FinePhysicalOneCochain 4 M (2 * Q) Nc

private abbrev MetricCoarseField (Q Nc : ℕ) [NeZero (2 * Q)] :=
  CoarsePhysicalOneCochain 4 (2 * Q) Nc

private abbrev MetricRectangularFieldMap (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)]
    [NeZero (M * (2 * Q))] :=
  MetricCoarseField Q Nc →L[ℝ] MetricFineField M Q Nc

/-- Explicit third-jet majorant with the source and domain factors kept
separate.  The first factor is generated from `D`, `D₃`, `V₀`, `Δπ`, and
`J`; the remaining factors are the exact rectangular reconstruction norm
and the source-metric random-walk decay. -/
noncomputable def
    cmp102Eq80PhysicalDomainThirdFieldSourceMetricMajorant
    {M Q Nc n : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (D D₃ : MetricFineField M Q Nc → MetricCoarseField Q Nc)
    (H : MetricRectangularFieldMap M Q Nc)
    (Δπ : MetricFineField M Q Nc →L[ℝ] MetricFineField M Q Nc)
    (J A : MetricFineField M Q Nc)
    (C Rjet : ℝ)
    (baseCoarseCovariance :
      MetricCoarseField Q Nc →L[ℝ] MetricCoarseField Q Nc)
    (κcard κmetric summationRatio : ℝ)
    (layerWord : Fin n → ℕ)
    (Y : CMP116LocalizationDomain M (2 * Q))
    (Δ : ℕ) : ℝ :=
  max
      (cmp102Eq80JointPotentialSourceJetMajorant
        D D₃ Δπ J 4 (H, A) C Rjet) 0 *
    (ContinuousLinearMap.opNorm (𝕜 := ℝ)
      (cmp99PhysicalRectangularOfComplexMatrixContinuousLinearMap
        (d := 4) (N₁ := 2 * Q) (N₂ := M * (2 * Q)) (Nc := Nc)) *
      (cmp102Eq80PhysicalFineHeadTailSourceMetricDecayPrefactor
          baseCoarseCovariance κcard κmetric summationRatio layerWord Y *
        (1 -
          ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
            summationRatio)⁻¹))

/-- The third field derivative of one literal equation-(80) domain
coefficient inherits the physical cardinality/tree-metric decay.  No
domain-dependent assumption is imposed on the global source maps, and no
free `sourceJetBound` occurs in the conclusion. -/
theorem
    norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceMetric
    {M Q Nc R Δ n : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (K : MetricFineField M Q Nc →L[ℝ] MetricFineField M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (baseCoarseCovariance :
      MetricCoarseField Q Nc →L[ℝ] MetricCoarseField Q Nc)
    {Ahead rho rate Rweak : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (hrange : R + 1 ≤ 4 * M)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (sigma : FinBox 4 (2 * Q) → ℂ)
    (hRweak : 1 ≤ Rweak)
    (hcap : ∀ d, ‖sigma d‖ ≤ Rweak)
    (hsmallContour :
      ‖cmp116SourcePi4ComplexContourRatio Δ rho Rweak‖ < 1)
    (layerWord : Fin n → ℕ)
    (choice : CMP99SourcePi4CoarseFineWalkChoice M Q R layerWord)
    (D D₃ : MetricFineField M Q Nc → MetricCoarseField Q Nc)
    (V₀ : MetricFineField M Q Nc → ℝ)
    (H : MetricRectangularFieldMap M Q Nc)
    (Δπ : MetricFineField M Q Nc →L[ℝ] MetricFineField M Q Nc)
    (J A : MetricFineField M Q Nc)
    (Y : CMP116LocalizationDomain M (2 * Q))
    (hD : ContDiff ℝ ⊤ D) (hD₃ : ContDiff ℝ ⊤ D₃)
    (hV₀ : ContDiff ℝ ⊤ V₀)
    (C Rjet : ℝ)
    (hC : ∀ i, i ≤ 4 →
      ‖iteratedFDeriv ℝ i V₀
        (cmp102Eq80JointRemainderInner D (H, A))‖ ≤ C)
    (hRjet : ∀ i, 1 ≤ i → i ≤ 4 →
      ‖iteratedFDeriv ℝ i
          (fun q :
              MetricRectangularFieldMap M Q Nc ×
                MetricFineField M Q Nc => q.2)
          (H, A)‖ +
        cmp102Eq80JointEvaluationJetMajorant D i (H, A) ≤ Rjet ^ i)
    {cardRatio metricRatio summationRatio κcard κmetric : ℝ}
    (hcardRatio0 : 0 ≤ cardRatio)
    (hmetricRatio0 : 0 ≤ metricRatio)
    (hsummation0 : 0 ≤ summationRatio)
    (hκcard : 0 ≤ κcard)
    (hκmetric : 0 ≤ κmetric)
    (hsplit :
      cmp102Eq80PhysicalFineHeadTailWalkRatio
          (M := M) baseCoarseCovariance Ahead rho rate Rweak ≤
        cardRatio * (metricRatio * summationRatio))
    (hcardDecay :
      cardRatio ≤ Real.exp (-(κcard * 10000)))
    (hmetricDecay :
      metricRatio ≤ Real.exp (-(κmetric * 10000)))
    (hsmall :
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
        summationRatio < 1) :
    ‖iteratedFDeriv ℝ 3
        (fun X =>
          cmp102Eq80PhysicalFineHeadTailDomainCoefficient
            anchor K hc hmass hK baseCoarseCovariance
            sigma layerWord choice D D₃ H Δπ J X
            (fderiv ℝ V₀ (X - H (D X))) Y.blocks)
        A‖ ≤
      cmp102Eq80PhysicalDomainThirdFieldSourceMetricMajorant
        D D₃ H Δπ J A C Rjet baseCoarseCovariance
        κcard κmetric summationRatio layerWord Y Δ := by
  let L :=
    cmp99PhysicalRectangularOfComplexMatrixContinuousLinearMap
      (d := 4) (N₁ := 2 * Q) (N₂ := M * (2 * Q)) (Nc := Nc)
  let matrixCoefficient :=
    cmp102Eq80PhysicalFineHeadTailDomainMatrixCoefficient
      anchor K hc hmass hK baseCoarseCovariance
      sigma layerWord choice Y.blocks
  let rawSourceMajorant :=
    cmp102Eq80JointPotentialSourceJetMajorant
      D D₃ Δπ J 4 (H, A) C Rjet
  let sourceMajorant := max rawSourceMajorant 0
  have hmatrix :
      ‖matrixCoefficient‖ ≤
        cmp102Eq80PhysicalFineHeadTailSourceMetricDecayPrefactor
            baseCoarseCovariance κcard κmetric summationRatio layerWord Y *
          (1 -
            ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
              summationRatio)⁻¹ := by
    simpa [matrixCoefficient] using
      norm_cmp102Eq80PhysicalFineHeadTailDomainMatrixCoefficient_le_sourceMetricDecay
        anchor K hc hmass hK baseCoarseCovariance
        hAhead hrho hrate hgeom Cert hrange hΔ hΔ1
        sigma hRweak hcap layerWord choice Y
        hcardRatio0 hmetricRatio0 hsummation0 hκcard hκmetric
        hsplit hcardDecay hmetricDecay hsmall
  have hL0 : 0 ≤ ContinuousLinearMap.opNorm L :=
    ContinuousLinearMap.opNorm_nonneg L
  have hmatrixReconstruct :
      ‖cmp99PhysicalRectangularOfComplexMatrix matrixCoefficient‖ ≤
        ContinuousLinearMap.opNorm L *
          (cmp102Eq80PhysicalFineHeadTailSourceMetricDecayPrefactor
              baseCoarseCovariance κcard κmetric summationRatio layerWord Y *
            (1 -
              ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
                summationRatio)⁻¹) := by
    calc
      ‖cmp99PhysicalRectangularOfComplexMatrix matrixCoefficient‖ ≤
          ContinuousLinearMap.opNorm L * ‖matrixCoefficient‖ := by
        simpa [L] using L.le_opNorm matrixCoefficient
      _ ≤ ContinuousLinearMap.opNorm L *
          (cmp102Eq80PhysicalFineHeadTailSourceMetricDecayPrefactor
              baseCoarseCovariance κcard κmetric summationRatio layerWord Y *
            (1 -
              ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
                summationRatio)⁻¹) :=
        mul_le_mul_of_nonneg_left hmatrix hL0
  have hsource0 : 0 ≤ sourceMajorant := by
    exact le_max_right _ _
  have hrawSource_le : rawSourceMajorant ≤ sourceMajorant := by
    exact le_max_left _ _
  have hcoefficient :=
    norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceJets
      anchor K hc hmass hK baseCoarseCovariance
      hAhead hrho hrate hgeom Cert hrange hΔ hΔ1
      sigma hRweak hcap hsmallContour layerWord choice
      D D₃ V₀ H Δπ J A Y.blocks hD hD₃ hV₀
      C Rjet hC hRjet
  calc
    ‖iteratedFDeriv ℝ 3
        (fun X =>
          cmp102Eq80PhysicalFineHeadTailDomainCoefficient
            anchor K hc hmass hK baseCoarseCovariance
            sigma layerWord choice D D₃ H Δπ J X
            (fderiv ℝ V₀ (X - H (D X))) Y.blocks)
        A‖ ≤
      rawSourceMajorant *
        ‖cmp99PhysicalRectangularOfComplexMatrix matrixCoefficient‖ := by
          simpa [rawSourceMajorant, matrixCoefficient] using hcoefficient
    _ ≤ sourceMajorant *
        ‖cmp99PhysicalRectangularOfComplexMatrix matrixCoefficient‖ :=
      mul_le_mul_of_nonneg_right hrawSource_le
        (norm_nonneg
          (cmp99PhysicalRectangularOfComplexMatrix matrixCoefficient))
    _ ≤ sourceMajorant *
        (ContinuousLinearMap.opNorm L *
          (cmp102Eq80PhysicalFineHeadTailSourceMetricDecayPrefactor
              baseCoarseCovariance κcard κmetric summationRatio layerWord Y *
            (1 -
              ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
                summationRatio)⁻¹)) :=
      mul_le_mul_of_nonneg_left hmatrixReconstruct hsource0
    _ = _ := by
      rfl

/-- Source-metric third-jet bound with the auxiliary inner-map radius
discharged from the literal value and first four jets of `D`.  The remaining
source obligations are componentwise: derivatives of `D`, derivatives of
`V₀` at the literal remainder point, and the explicit `D₃` jets retained in
the displayed source majorant. -/
theorem
    norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceMetric_of_correctionJets
    {M Q Nc R Δ n : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))]
    (anchor : FinBox 4 Q)
    (K : MetricFineField M Q Nc →L[ℝ] MetricFineField M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (baseCoarseCovariance :
      MetricCoarseField Q Nc →L[ℝ] MetricCoarseField Q Nc)
    {Ahead rho rate Rweak : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (hrange : R + 1 ≤ 4 * M)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (sigma : FinBox 4 (2 * Q) → ℂ)
    (hRweak : 1 ≤ Rweak)
    (hcap : ∀ d, ‖sigma d‖ ≤ Rweak)
    (hsmallContour :
      ‖cmp116SourcePi4ComplexContourRatio Δ rho Rweak‖ < 1)
    (layerWord : Fin n → ℕ)
    (choice : CMP99SourcePi4CoarseFineWalkChoice M Q R layerWord)
    (D D₃ : MetricFineField M Q Nc → MetricCoarseField Q Nc)
    (V₀ : MetricFineField M Q Nc → ℝ)
    (H : MetricRectangularFieldMap M Q Nc)
    (Δπ : MetricFineField M Q Nc →L[ℝ] MetricFineField M Q Nc)
    (J A : MetricFineField M Q Nc)
    (Y : CMP116LocalizationDomain M (2 * Q))
    (hD : ContDiff ℝ ⊤ D) (hD₃ : ContDiff ℝ ⊤ D₃)
    (hV₀ : ContDiff ℝ ⊤ V₀)
    (B₀ B₁ B₂ B₃ B₄ C : ℝ)
    (hD₀ : ‖D A‖ ≤ B₀)
    (hD₁ : ‖iteratedFDeriv ℝ 1 D A‖ ≤ B₁)
    (hD₂ : ‖iteratedFDeriv ℝ 2 D A‖ ≤ B₂)
    (hD₃jet : ‖iteratedFDeriv ℝ 3 D A‖ ≤ B₃)
    (hD₄ : ‖iteratedFDeriv ℝ 4 D A‖ ≤ B₄)
    (hC : ∀ i, i ≤ 4 →
      ‖iteratedFDeriv ℝ i V₀
        (cmp102Eq80JointRemainderInner D (H, A))‖ ≤ C)
    {cardRatio metricRatio summationRatio κcard κmetric : ℝ}
    (hcardRatio0 : 0 ≤ cardRatio)
    (hmetricRatio0 : 0 ≤ metricRatio)
    (hsummation0 : 0 ≤ summationRatio)
    (hκcard : 0 ≤ κcard)
    (hκmetric : 0 ≤ κmetric)
    (hsplit :
      cmp102Eq80PhysicalFineHeadTailWalkRatio
          (M := M) baseCoarseCovariance Ahead rho rate Rweak ≤
        cardRatio * (metricRatio * summationRatio))
    (hcardDecay :
      cardRatio ≤ Real.exp (-(κcard * 10000)))
    (hmetricDecay :
      metricRatio ≤ Real.exp (-(κmetric * 10000)))
    (hsmall :
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) *
        summationRatio < 1) :
    ‖iteratedFDeriv ℝ 3
        (fun X =>
          cmp102Eq80PhysicalFineHeadTailDomainCoefficient
            anchor K hc hmass hK baseCoarseCovariance
            sigma layerWord choice D D₃ H Δπ J X
            (fderiv ℝ V₀ (X - H (D X))) Y.blocks)
        A‖ ≤
      cmp102Eq80PhysicalDomainThirdFieldSourceMetricMajorant
        D D₃ H Δπ J A C
        (cmp102Eq80RectangularOrderFourJetRadius
          ‖H‖ B₀ B₁ B₂ B₃ B₄)
        baseCoarseCovariance κcard κmetric summationRatio
        layerWord Y Δ := by
  apply
    norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceMetric
      anchor K hc hmass hK baseCoarseCovariance
      hAhead hrho hrate hgeom Cert hrange hΔ hΔ1
      sigma hRweak hcap hsmallContour layerWord choice
      D D₃ V₀ H Δπ J A Y hD hD₃ hV₀ C
      (cmp102Eq80RectangularOrderFourJetRadius
        ‖H‖ B₀ B₁ B₂ B₃ B₄)
      hC
      ?_
      hcardRatio0 hmetricRatio0 hsummation0 hκcard hκmetric
      hsplit hcardDecay hmetricDecay hsmall
  intro i hi₁ hi₄
  exact
    cmp102Eq80JointRemainderRadius_orderFour_of_correctionJets
      D hD H A B₀ B₁ B₂ B₃ B₄
      hD₀ hD₁ hD₂ hD₃jet hD₄ i hi₁ hi₄

end

end YangMills.RG
