import YangMills.RG.BalabanCMP116RestrictedVisitedTransferResolvent

#print axioms YangMills.RG.cmp116RestrictedVisitedTransferResolvent
#print axioms YangMills.RG.cmp116RestrictedVisitedTransferHeadReadout
#print axioms YangMills.RG.cmp116RestrictedVisitedTransferHeadReadoutCLM
#print axioms YangMills.RG.cmp116RestrictedVisitedTransferPowerLayer_eq_headReadout
#print axioms YangMills.RG.tsum_cmp116RestrictedVisitedTransferPowerLayer_eq_headReadout_resolvent
#print axioms YangMills.RG.cmp116RestrictedVisitedTransferResolvent_mul_one_sub
#print axioms YangMills.RG.one_sub_mul_cmp116RestrictedVisitedTransferResolvent
#print axioms YangMills.RG.cmp116RestrictedVisitedTransferResolvent_sub_one_eq_activeTargetFactorization
