import YangMills.RG.BalabanCMP99SourceGeneratedMassTransition

open YangMills.RG

#print axioms cmp99NestedActiveRegionRestriction
#print axioms cmp99SourceTransportedBlockAverage_nested_transition
#print axioms cmp99SourceTransportedBlockAverage_adjoint_nested_transition
#print axioms cmp99SourceTransportedBlockMass_nested_transition
#print axioms CMP99SourceWeightedRegionalTower.countingMass_step
#print axioms cmp99NestedComposedMass_transition
#print axioms CMP99SourceActiveRegionChain.generatedCountingMass
#print axioms CMP99SourceActiveRegionChain.generatedCountingMass_eq_QprimeMass
#print axioms CMP99SourceNestedRegionChains
#print axioms CMP99SourceNestedRegionChains.cast_regions
#print axioms cmp99SourceIteratedLift_nestedRegionChains
#print axioms CMP99SourceNestedRegionChains.generatedCountingMass_transition
#print axioms cmp99SourceIteratedLift_generatedCountingMass_transition
#print axioms cmp99SourceIteratedLift_QprimeMass_transition
#print axioms CMP99SourceDependentOmegaGeometry.generatedQprimeMass_transition
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalPrecisionDefect_eq_laplacianDefect
