/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116SourceRestrictedConditionedCenteredPhysicalEq226Boundary

/-!
# A centered source-faithful conditioned physical equation-(2.26) term

This record packages the literal source estimates `(1.43)` and `(1.36)`.
It does not store a termwise bound, a Gaussian boundary estimate, or an
equation-`(2.26)` conclusion.  Those are generated by the centered physical
boundary theorem.
-/

namespace YangMills.RG

noncomputable section

open MeasureTheory
open scoped Matrix.Norms.Operator

private abbrev CenteredSourceBond (M Q : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)] [NeZero (M * (2 * Q))] :=
  PhysicalBond 4 (M * (2 * Q))

private abbrev CenteredSourceEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] [NeZero (2 * Q)] [NeZero (M * (2 * Q))] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

/-- Every field of a centered conditioned equation-(2.14) source except the
literal equation-(1.36) estimate.  Keeping this telescope independent makes
the source-specific constructor elaborate the remaining obligations before
it generates `(1.36)` from the direct/native physical ledger. -/
structure CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (Y0 P : Finset (CenteredSourceBond M Q))
    (Z0 Z : Finset (FinBox 4 (2 * Q))) where
  base :
    CMP116Eq214PhysicalContourDensity nDelta nY
      (CenteredSourceBond M Q) (CenteredSourceBond M Q)
      (fun _ => SUNLieCoord Nc) (fun _ => SUNLieCoord Nc)
      (SUNLieCoord Nc) (Nc ^ 2 - 1)
  anchor : FinBox 4 Q
  contourCarrier : Finset (FinBox 4 (2 * Q))
  carrier_subset_sigmaZero :
    contourCarrier ⊆ cmp116SourceSigmaZero anchor
  carrier_subset_Z0 : contourCarrier ⊆ Z0
  Z0_subset_Z : Z0 ⊆ Z
  contourEquiv : Fin nDelta ≃ ↥contourCarrier
  K : CenteredSourceEndomorphism M Q Nc
  root : CenteredSourceEndomorphism M Q Nc
  sourceRange : ℕ
  sourceRange_bound : sourceRange + 1 ≤ 4 * M
  finiteRange :
    PhysicalCovarianceFiniteRange K physicalBondDist sourceRange
  coercivityConstant : ℝ
  mass : ℝ
  coercivity_pos : 0 < coercivityConstant
  mass_pos : 0 < mass
  K_coercive : IsCoerciveCLM K coercivityConstant
  patchedDefect_small :
    ‖cmp99PatchedPhysicalParametrixDefect
        (cmp99SourcePi4Charts :
          Finset (CMP99SourcePi4Chart Unit Q))
        K cmp99SourcePi4ChartEnlarged
        (cmp99SourcePi4ChartCore (M := M))
        coercivity_pos mass_pos K_coercive‖ < 1
  Ahead : ℝ
  rho : ℝ
  rate : ℝ
  radius : ℝ
  Ahead_nonneg : 0 ≤ Ahead
  rho_nonneg : 0 ≤ rho
  rate_pos : 0 < rate
  shell_small : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1
  patchCertificate :
    CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      coercivity_pos mass_pos K_coercive physicalBondDist Ahead rho rate
  distance_triangle : ∀ target source middle : CenteredSourceBond M Q,
    physicalBondDist target source ≤
      physicalBondDist target middle + physicalBondDist middle source
  Delta : ℕ
  degree_bound : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Delta
  one_le_Delta : 1 ≤ Delta
  radius_nonneg : 0 ≤ radius
  radius_cap : ∀ i, 1 + base.deltaRadius i ≤ radius
  contour_series_small :
    ‖cmp116SourcePi4ComplexContourRatio Delta rho (1 + radius)‖ < 1
  neumann_small :
    ‖cmp116PhysicalEndomorphismComplexMatrix K‖ *
      cmp116SourcePi4PhysicalComplexContourDefectBound
        Nc Delta Ahead rho rate radius (1 + radius) < 1
  neumann_transpose_small :
    cmp116SourcePi4PhysicalComplexTransposeRelativeDefectBound
      K Delta Ahead rho rate radius (1 + radius) < 1
  total :
    (Fin nDelta → ℂ) →
    RestrictedField base.spectatorSupport (fun _ => SUNLieCoord Nc) →
    RestrictedField base.fluctuationSupport (fun _ => SUNLieCoord Nc) →
    Fin nY → PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ
  residual :
    (Fin nDelta → ℂ) →
    RestrictedField base.spectatorSupport (fun _ => SUNLieCoord Nc) →
    RestrictedField base.fluctuationSupport (fun _ => SUNLieCoord Nc) →
    Fin nY → PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc → ℝ
  smooth : ∀ sigma psi phi y,
    ContDiff ℝ 2
      (cmp116Eq142PhysicalQuadraticCore
        (total sigma psi phi) (residual sigma psi phi) y)
  kernelSupport :
    Fin nY → CenteredSourceBond M Q → CenteredSourceBond M Q → Prop
  domainMetric : Fin nY → ℕ
  domainCard : Fin nY → ℕ
  domainSupport : Fin nY → Finset (FinBox 4 (2 * Q))
  E0 : ℝ
  epsilon1 : ℝ
  C1 : ℝ
  alpha4 : ℝ
  C3 : ℝ
  C2 : ℝ
  kappa1 : ℝ
  delta : ℝ
  kappa : ℝ
  gk : ℝ
  rowSum : ℝ
  threshold : ℝ
  alpha : ℝ
  gamma : ℝ
  q : ℕ
  gapScale : ℕ
  gapCard : ℕ
  qBound : ℝ
  qBound_nonneg : 0 ≤ qBound
  qBound_lt_one : qBound < 1
  rootBound : ℝ
  volumeRate : ℝ
  conditionedCovariance :
    Matrix
      (PhysicalGaugeCoordIndex 4 (M * (2 * Q)) Nc)
      (PhysicalGaugeCoordIndex 4 (M * (2 * Q)) Nc) ℝ
  conditionedRoot :
    MatrixConditionedGaussianRootCertificate
      conditionedCovariance
      (cmp116PhysicalEndomorphismRealMatrix root)
      (cmp116SourcePhysicalLocalizedCoordinates Dict Z0)
  conditionedCovariance_nondegenerate :
    MatrixConditionedGaussianCovarianceLowerCertificate
      conditionedCovariance
      (cmp116SourcePhysicalLocalizedCoordinates Dict Z0)
  E0_pos : 0 < E0
  epsilon1_pos : 0 < epsilon1
  C1_pos : 0 < C1
  alpha4_pos : 0 < alpha4
  C3_nonneg : 0 ≤ C3
  C3_le : C3 ≤ E0 * C1
  one_le_M : 1 ≤ M
  eight_le_q : 8 ≤ q
  one_lt_kappa1 : 1 < kappa1
  source_budget :
    (1 - 3 * delta) * kappa ≤ (1 / 8 : ℝ) * (kappa1 - 1)
  domainMetric_nonneg : ∀ y : Fin nY, 0 ≤ (domainMetric y : ℝ)
  exponential_row_bound : ∀ target : CenteredSourceBond M Q,
    ∑ source : CenteredSourceBond M Q,
      Real.exp (-(cmp116Eq219InternalRate M kappa1 *
        (physicalBondDist target source : ℝ))) ≤ rowSum
  metric_budget : ∀ y source target,
    kernelSupport y source target →
      cmp116Eq219InternalRate M kappa1 *
          (physicalBondDist target source : ℝ) ≤
        (1 / 4 : ℝ) * (kappa1 - 1) * domainCard y
  hessian_zero_off_support : ∀ psi phi sigma,
    CMP116Eq214ShiftedPolydisc nDelta base.deltaRadius sigma →
    ∀ b y source target,
    ¬ kernelSupport y source target →
      ∀ (v w : SUNLieCoord Nc), ∀ t ∈ Set.Icc (0 : ℝ) 1,
        cmp116FDerivHessian
          (cmp116Eq142PhysicalQuadraticCore
            (total sigma
              (restrictGlobal base.spectatorSupport psi)
              (restrictGlobal base.fluctuationSupport phi))
            (residual sigma
              (restrictGlobal base.spectatorSupport psi)
              (restrictGlobal base.fluctuationSupport phi)) y)
          (t • physicalBondProjection
            (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
            (cmp116SourcePhysicalCoordinateCochain b))
          (singlePhysicalBondCochain
            (d := 4) (N := M * (2 * Q)) (Nc := Nc) source v)
          (singlePhysicalBondCochain
            (d := 4) (N := M * (2 * Q)) (Nc := Nc) target w) = 0
  eq143 : ∀ psi phi sigma,
    CMP116Eq214ShiftedPolydisc nDelta base.deltaRadius sigma →
    ∀ b y source target (v w : SUNLieCoord Nc),
    ∀ t ∈ Set.Icc (0 : ℝ) 1,
      |cmp116FDerivHessian
        (cmp116Eq142PhysicalQuadraticCore
          (total sigma
            (restrictGlobal base.spectatorSupport psi)
            (restrictGlobal base.fluctuationSupport phi))
          (residual sigma
            (restrictGlobal base.spectatorSupport psi)
            (restrictGlobal base.fluctuationSupport phi)) y)
        (t • physicalBondProjection
          (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
          (cmp116SourcePhysicalCoordinateCochain b))
        (singlePhysicalBondCochain
          (d := 4) (N := M * (2 * Q)) (Nc := Nc) source v)
        (singlePhysicalBondCochain
          (d := 4) (N := M * (2 * Q)) (Nc := Nc) target w)| ≤
        cmp116Eq143QMajorant C3 epsilon1 M C2 kappa1
          (domainMetric y : ℝ) (domainCard y) * ‖v‖ * ‖w‖
  interaction_budget :
    cmp116Eq220CenteredSourcePotentialRate Finset.univ
        (fun y => (domainMetric y : ℝ)) domainCard
        C3 epsilon1 M C2 kappa1 alpha4 rowSum +
      cmp116SourcePi4PhysicalComplexR2BilateralBound
        K Delta Ahead rho rate radius (1 + radius) +
      gamma ≤ alpha
  deltaRadius_eq :
    let quadratic := fun sigma psi phi =>
      cmp116Eq142PhysicalSourceQuadratic
        (total sigma psi phi) (residual sigma psi phi)
        (smooth sigma psi phi)
    let Cphysical :=
      (base.withSourcePhysicalComplexTauPotential
        Dict Finset.univ quadratic residual Z0).withSourcePhysicalBondField
          threshold
    (Cphysical.withSourcePi4RestrictedComplexGaussianOfPhysicalContour
      anchor contourCarrier carrier_subset_sigmaZero contourEquiv Z0 K root
      sourceRange_bound finiteRange coercivity_pos mass_pos K_coercive
      patchedDefect_small Ahead_nonneg rho_nonneg rate_pos shell_small
      patchCertificate distance_triangle degree_bound one_le_Delta
      radius_nonneg (by simpa [Cphysical] using radius_cap)
      contour_series_small neumann_small).deltaRadius =
        fun _ => cmp116Eq214SigmaCauchyRadius kappa1
  normalizedGap :
    ((((gapScale * M : ℕ) : ℝ) ^ 4)⁻¹ * (gapCard : ℝ)) =
      (nDelta : ℝ)
  yRadius_eq :
    let quadratic := fun sigma psi phi =>
      cmp116Eq142PhysicalSourceQuadratic
        (total sigma psi phi) (residual sigma psi phi)
        (smooth sigma psi phi)
    let Cphysical :=
      (base.withSourcePhysicalComplexTauPotential
        Dict Finset.univ quadratic residual Z0).withSourcePhysicalBondField
          threshold
    (Cphysical.withSourcePi4RestrictedComplexGaussianOfPhysicalContour
      anchor contourCarrier carrier_subset_sigmaZero contourEquiv Z0 K root
      sourceRange_bound finiteRange coercivity_pos mass_pos K_coercive
      patchedDefect_small Ahead_nonneg rho_nonneg rate_pos shell_small
      patchCertificate distance_triangle degree_bound one_le_Delta
      radius_nonneg (by simpa [Cphysical] using radius_cap)
      contour_series_small neumann_small).yRadius =
        fun Y =>
          cmp116Eq218TauAbsSolved E0 epsilon1 C1 alpha4 M q
            C2 kappa1 delta kappa (domainMetric Y : ℝ)
  gk_ne : gk ≠ 0
  threshold_eq :
    let quadratic := fun sigma psi phi =>
      cmp116Eq142PhysicalSourceQuadratic
        (total sigma psi phi) (residual sigma psi phi)
        (smooth sigma psi phi)
    let Cphysical :=
      (base.withSourcePhysicalComplexTauPotential
        Dict Finset.univ quadratic residual Z0).withSourcePhysicalBondField
          threshold
    (Cphysical.withSourcePi4RestrictedComplexGaussianOfPhysicalContour
      anchor contourCarrier carrier_subset_sigmaZero contourEquiv Z0 K root
      sourceRange_bound finiteRange coercivity_pos mass_pos K_coercive
      patchedDefect_small Ahead_nonneg rho_nonneg rate_pos shell_small
      patchCertificate distance_triangle degree_bound one_le_Delta
      radius_nonneg (by simpa [Cphysical] using radius_cap)
      contour_series_small neumann_small).threshold = epsilon1 / gk
  alpha_nonneg : 0 ≤ alpha
  root_small :
    alpha *
      (@norm
        (Matrix
          (PhysicalGaugeCoordIndex 4 (M * (2 * Q)) Nc)
          (PhysicalGaugeCoordIndex 4 (M * (2 * Q)) Nc) ℝ)
        Matrix.instL2OpNormedAddCommGroup.toNorm
        (cmp116PhysicalEndomorphismRealMatrix root)) ^ 2 < 1
  gamma_nonneg : 0 ≤ gamma
  threshold_nonneg : 0 ≤ threshold
  outer_small :
    2 *
      (cmp116SourcePi4PhysicalComplexR1DefectBilateralBudget
          K root coercivity_pos mass_pos K_coercive Z0 Delta
            Ahead rho rate radius (1 + radius) +
        |cmp116Eq225SourceCoefficient
            (cmp116PhysicalEndomorphismRealMatrix root) alpha *
          cmp116SourcePi4PhysicalComplexR3SourceRate
            K root Z0 Delta Ahead rho rate radius (1 + radius)|) ≤
      qBound
  domain_nonempty : ∀ Y : Fin nY, (domainSupport Y).Nonempty
  domain_subset : ∀ Y : Fin nY, domainSupport Y ⊆ Z0
  rootBound_nonneg : 0 ≤ rootBound
  rooted_residual : ∀ i ∈ Z0,
    ∑ Y ∈ (Finset.univ.filter fun Y : Fin nY =>
        i ∈ domainSupport Y),
      cmp116Eq220CenteredSourceResidualWeight
        (fun y => (domainMetric y : ℝ))
        E0 epsilon1 C1 M q C2 kappa1 delta kappa alpha4 Y ≤ rootBound
  volume_budget :
    rootBound +
        cmp116SourceRestrictedConditionedPhysicalOuterPerCarrierCost
          K root coercivity_pos mass_pos K_coercive Z0 Delta radius rate
            Ahead rho alpha
            (cmp116SourcePi4PhysicalComplexR3SourceRate
              K root Z0 Delta Ahead rho rate radius (1 + radius))
            qBound
            (cmp116SourceRestrictedUniformContourDeterminantCost
              M Nc Delta radius (1 + radius) rate Ahead rho
                ‖cmp116PhysicalEndomorphismComplexMatrix K‖) ≤
      volumeRate * alpha

/-- Physical source data for one centered conditioned equation-(2.14)
summand.  Equation `(1.36)` is the final field: every independent geometric,
operatorial, analytic, and scalar obligation is fixed before it is generated
on the literal cutoff support.  Covariance nondegeneracy remains a mandatory
independent field. -/
structure CMP116Eq226CenteredConditionedPhysicalTermSource
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    (Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim)
    (Y0 P : Finset (CenteredSourceBond M Q))
    (Z0 Z : Finset (FinBox 4 (2 * Q)))
    extends CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z where
  eq136 : ∀ psi phi sigma,
    CMP116Eq214ShiftedPolydisc nDelta base.deltaRadius sigma →
    ∀ b y,
      (-1 : ℂ) ^ P.card *
          cmp116SmallFieldCutoff Y0 threshold
            (cmp116SourcePhysicalCoordinateCochain b) *
          cmp116LargeFieldCutoff P threshold
            (cmp116SourcePhysicalCoordinateCochain b) ≠ 0 →
      |residual sigma
        (restrictGlobal base.spectatorSupport psi)
        (restrictGlobal base.fluctuationSupport phi) y
        (physicalBondProjection
          (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
          (cmp116SourcePhysicalCoordinateCochain b))| ≤
        cmp116Eq136ResidualMajorant E0 epsilon1 C1 M q
          C2 kappa1 delta kappa (domainMetric y : ℝ)

namespace CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136

variable
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim}
    {Y0 P : Finset (CenteredSourceBond M Q)}
    {Z0 Z : Finset (FinBox 4 (2 * Q))}

/-- Generic finalizer for the factored record.  Source-facing constructors do
not export its last argument: they generate it from their physical residual
theorem after constructing `S`. -/
noncomputable def complete
    (S : CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z)
    (hEq136 : ∀ psi phi sigma,
      CMP116Eq214ShiftedPolydisc nDelta S.base.deltaRadius sigma →
      ∀ b y,
        (-1 : ℂ) ^ P.card *
            cmp116SmallFieldCutoff Y0 S.threshold
              (cmp116SourcePhysicalCoordinateCochain b) *
            cmp116LargeFieldCutoff P S.threshold
              (cmp116SourcePhysicalCoordinateCochain b) ≠ 0 →
        |S.residual sigma
          (restrictGlobal S.base.spectatorSupport psi)
          (restrictGlobal S.base.fluctuationSupport phi) y
          (physicalBondProjection
            (PhysicalGaugeCMP116Dictionary.cmp116Eq223PhysicalInteriorBonds Z0)
            (cmp116SourcePhysicalCoordinateCochain b))| ≤
          cmp116Eq136ResidualMajorant S.E0 S.epsilon1 S.C1 M S.q
            S.C2 S.kappa1 S.delta S.kappa (S.domainMetric y : ℝ)) :
    CMP116Eq226CenteredConditionedPhysicalTermSource
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z :=
  ⟨S, hEq136⟩

end CMP116Eq226CenteredConditionedPhysicalTermSourcePreEq136

namespace CMP116Eq226CenteredConditionedPhysicalTermSource

variable
    {nDelta nY M Q Nc L lieDim : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    [NeZero (2 * Q)] [NeZero (M * (2 * Q))] [NeZero L] [NeZero lieDim]
    {Dict : PhysicalGaugeCMP116Dictionary
      4 (M * (2 * Q)) Nc 4 L lieDim}
    {Y0 P : Finset (CenteredSourceBond M Q)}
    {Z0 Z : Finset (FinBox 4 (2 * Q))}

/-- The fully assembled centered conditioned density. -/
noncomputable def conditionedDensity
    (S : CMP116Eq226CenteredConditionedPhysicalTermSource
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z) :=
  let quadratic := fun sigma psi phi =>
    cmp116Eq142PhysicalSourceQuadratic
      (S.total sigma psi phi) (S.residual sigma psi phi)
      (S.smooth sigma psi phi)
  let Cphysical :=
    (S.base.withSourcePhysicalComplexTauPotential
      Dict Finset.univ quadratic S.residual Z0).withSourcePhysicalBondField
        S.threshold
  let Craw :=
    Cphysical.withSourcePi4RestrictedComplexGaussianOfPhysicalContour
      S.anchor S.contourCarrier S.carrier_subset_sigmaZero S.contourEquiv
      Z0 S.K S.root S.sourceRange_bound S.finiteRange
      S.coercivity_pos S.mass_pos S.K_coercive S.patchedDefect_small
      S.Ahead_nonneg S.rho_nonneg S.rate_pos S.shell_small
      S.patchCertificate S.distance_triangle S.degree_bound S.one_le_Delta
      S.radius_nonneg (by simpa [Cphysical, quadratic] using S.radius_cap)
      S.contour_series_small S.neumann_small
  Craw.withConditionedOuterCarrier
    (cmp116SourcePhysicalLocalizedCoordinates Dict Z)

/-- The literal centered equation-(2.26) source weight. -/
noncomputable def termWeight
    (S : CMP116Eq226CenteredConditionedPhysicalTermSource
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z) : ℝ :=
  cmp116Eq226SourceTermWeight S.E0 S.epsilon1 S.C1 S.alpha4 M S.q
    S.C2 S.kappa1 S.delta S.kappa S.gamma S.gk S.gapScale S.gapCard
    S.volumeRate S.alpha Z.card S.domainMetric Finset.univ P

set_option maxHeartbeats 30000000 in
/-- The centered source record derives its termwise equation-(2.26)
estimate.  Neither the interaction bound nor the termwise estimate is a
field of the record. -/
theorem norm_term_le_termWeight
    (S : CMP116Eq226CenteredConditionedPhysicalTermSource
      (nDelta := nDelta) (nY := nY) Dict Y0 P Z0 Z)
    (psi phi : PhysicalGaugeField 4 (M * (2 * Q)) Nc) :
    ‖S.conditionedDensity.toLocalFiniteGaussianData.toFiniteGaussianData
        |>.toAnalyticData.term Y0 P psi phi‖ ≤
      S.termWeight := by
  unfold conditionedDensity termWeight
  exact
    S.base.norm_term_le_eq226SourceTermWeight_of_sourcePi4ConditionedCenteredPhysicalPotentialLedger
      Dict S.anchor S.contourCarrier Z0 Z
      S.carrier_subset_sigmaZero S.carrier_subset_Z0 S.Z0_subset_Z
      S.contourEquiv S.K S.root S.sourceRange_bound S.finiteRange
      S.coercivity_pos S.mass_pos S.K_coercive S.patchedDefect_small
      S.Ahead_nonneg S.rho_nonneg S.rate_pos S.shell_small
      S.patchCertificate S.distance_triangle S.degree_bound S.one_le_Delta
      S.radius_nonneg S.radius_cap S.contour_series_small S.neumann_small
      S.neumann_transpose_small S.total S.residual S.smooth
      S.kernelSupport S.domainMetric S.domainCard S.domainSupport
      Y0 P psi phi S.E0 S.epsilon1 S.C1 S.alpha4 S.C3 S.C2 S.kappa1
      S.delta S.kappa S.gk S.rowSum S.threshold S.alpha S.gamma
      S.gapScale S.gapCard S.qBound_nonneg S.qBound_lt_one
      S.rootBound S.volumeRate S.conditionedCovariance S.conditionedRoot
      S.conditionedCovariance_nondegenerate
      S.E0_pos S.epsilon1_pos S.C1_pos S.alpha4_pos S.C3_nonneg S.C3_le
      S.one_le_M S.eight_le_q S.one_lt_kappa1 S.source_budget
      S.domainMetric_nonneg S.exponential_row_bound S.metric_budget
      (S.hessian_zero_off_support psi phi) (S.eq143 psi phi)
      (S.eq136 psi phi) S.interaction_budget S.deltaRadius_eq
      S.normalizedGap S.yRadius_eq S.gk_ne S.threshold_eq
      S.alpha_nonneg S.root_small S.gamma_nonneg S.threshold_nonneg
      S.outer_small S.domain_nonempty S.domain_subset S.rootBound_nonneg
      S.rooted_residual S.volume_budget

end CMP116Eq226CenteredConditionedPhysicalTermSource

end

end YangMills.RG
