import YangMills.RG.BalabanCMP99SourceRegionalCombesThomas

namespace YangMills.RG

#print axioms cmp99OmegaSiteDist
#print axioms cmp99OmegaSiteDist_comm
#print axioms cmp99OmegaSiteDist_self
#print axioms cmp99OmegaSiteDist_triangle
#print axioms cmp99OmegaSiteDist_ball_card_le
#print axioms cmp99OmegaSiteDist_exp_sum_le_geometric
#print axioms cmp99OmegaSiteExpSumBound
#print axioms summable_cmp99OmegaSiteExpSumBound
#print axioms cmp99OmegaSiteDist_exp_sum_le
#print axioms cmp99OmegaTransitionSiteDist
#print axioms cmp99OmegaTransitionRestriction_single_of_mem
#print axioms cmp99OmegaTransitionRestriction_single_of_not_mem
#print axioms cmp99OmegaSourceCovariantLaplacian_finiteRange_one
#print axioms cmp99OmegaSourcePhysicalOneStepQ_adjoint_comp_finiteRange_M
#print axioms cmp99OmegaSourcePhysicalOneStepGaugePrecision_finiteRange_M
#print axioms cmp99OmegaSourcePhysicalOneStepPrecisionDefect_finiteRange_M
#print axioms cmp99OmegaSourcePhysicalOneStepPrecisionDefect_kernelBound
#print axioms cmp99OmegaSourcePhysicalOneStepGaugePrecision_kernelBound
#print axioms cmp99OmegaSourcePhysicalOneStepGreen_exponentialKernelBound
#print axioms cmp99OmegaSourcePhysicalOneStepCombesThomasRate
#print axioms cmp99OmegaSourcePhysicalOneStepCombesThomasRate_pos
#print axioms cmp99OmegaSourcePhysicalOneStepCombesThomasRate_budget
#print axioms cmp99OmegaSourcePhysicalOneStepGreen_canonicalExponentialKernelBound
#print axioms cmp99OmegaSourcePhysicalOneStepGreenTransitionDecayAmplitude
#print axioms cmp99OmegaSourcePhysicalOneStepGreen_transition_exponentialKernelBound

end YangMills.RG
