import YangMills.RG.BalabanCMP102Eq80PhysicalDomainThirdFieldSourceMetricBound

#print axioms YangMills.RG.cmp102Eq80PhysicalDomainThirdFieldSourceMetricMajorant
#print axioms YangMills.RG.norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceMetric
#print axioms YangMills.RG.norm_iteratedFDeriv_three_cmp102Eq80PhysicalFineHeadTailDomainCoefficient_le_sourceMetric_of_correctionJets
