import YangMills.RG.BalabanCMP116ComplexOuterTracePowers

#print axioms YangMills.RG.norm_trace_complexified_neg_symmetricRealPart_pow_succ_le_of_multiplier
#print axioms YangMills.RG.integral_exp_re_complexQuadratic_standardGaussianPi_le_of_multiplier
