import YangMills.RG.BalabanCMP99Eq360C6dSourceSeparatedAmbientGreenDecayZeroDepth

#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientPrecisionDecayAmplitude_zero
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientPrecision_zero_exponentialKernelBound
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen_zero_exponentialKernelBound
