/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116SourcePi4TerminalGroupedPhysicalWeightedRow
import YangMills.RG.PhysicalWeightedRowKernelTsum
import YangMills.RG.PhysicalWeightedRowKernelMatrix

/-!
# Volume-uniform fixed-rate bound for the exact source covariance

The terminal-path count, exact source-core partition, and factorwise physical
kernel certificate combine into a geometric majorant for every complete walk
layer.  Summing over the walk length gives a fixed-rate weighted-row estimate
for the exact quotient patched covariance with no ambient-volume factor.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

private abbrev PhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

/-- The exact physical quotient covariance inherits the convergent geometric
row amplitude generated by the local `Π⁴` branching factor. -/
theorem cmp116SourcePi4QuotientExactPatchedCovariance_weightedRow_physical
    {M Q Nc R Δ : ℕ} [NeZero M] [NeZero Q]
    (K : PhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    (dist : PhysicalBond 4 (M * (2 * Q)) →
      PhysicalBond 4 (M * (2 * Q)) → ℕ)
    {Ahead rho rate : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 ≤ rate)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK dist Ahead rho rate)
    (htri : ∀ target source middle,
      dist target source ≤ dist target middle + dist middle source)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (hsmall :
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) * rho < 1) :
    PhysicalCovarianceWeightedRowKernelBound
      (cmp116SourcePi4QuotientExactPatchedCovariance
        K hc hmass hK)
      dist
      (Ahead *
        (1 - ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) * rho)⁻¹)
      rate := by
  let branch : ℝ :=
    ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ)
  let q : ℝ := branch * rho
  have hbranch : 0 ≤ branch := by
    dsimp [branch]
    positivity
  have hq0 : 0 ≤ q := mul_nonneg hbranch hrho
  have hqnorm : ‖q‖ < 1 := by
    simpa only [Real.norm_eq_abs, abs_of_nonneg hq0, q, branch] using hsmall
  have hAgeom : Summable (fun n : ℕ => Ahead * q ^ n) :=
    (summable_geometric_of_norm_lt_one hqnorm).mul_left Ahead
  have hlayer (n : ℕ) :
      PhysicalCovarianceWeightedRowKernelBound
        (cmp116SourcePi4QuotientGeneratedWalkLayer
          (R := R) K hc hmass hK n)
        dist (Ahead * q ^ n) rate := by
    have hraw :=
      cmp116SourcePi4QuotientGeneratedWalkLayer_weightedRow_physical
        K hc hmass hK dist hAhead hrho hrate Cert htri hsourceRange
        hΔ hΔ1 n
    convert hraw using 1
    dsimp [q, branch]
    rw [mul_pow, Nat.cast_pow]
    ring
  have hsum :=
    physicalCovarianceWeightedRowKernelBound_tsum
      (fun n : ℕ =>
        cmp116SourcePi4QuotientGeneratedWalkLayer
          (R := R) K hc hmass hK n)
      dist (fun n : ℕ => Ahead * q ^ n)
      (summable_cmp116SourcePi4QuotientGeneratedWalkLayer
        K hsourceRange hrange hc hmass hK hD)
      hAgeom
      (fun n => mul_nonneg hAhead (pow_nonneg hq0 n))
      hrate hlayer
  rw [←
    cmp116SourcePi4QuotientExactPatchedCovariance_eq_tsum_generatedLayers
      K hsourceRange hrange hc hmass hK hD] at hsum
  have hgeom :
      (∑' n : ℕ, Ahead * q ^ n) = Ahead * (1 - q)⁻¹ := by
    rw [tsum_mul_left, tsum_geometric_of_norm_lt_one hqnorm]
  simpa only [hgeom, q, branch] using hsum

/-- Matrix norm form of the exact source covariance estimate.  This is the
base-inverse bound consumed by the complex contour Neumann criterion. -/
theorem linfty_opNorm_cmp116SourcePi4QuotientExactPatchedCovarianceMatrix_le
    {M Q Nc R Δ : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (K : PhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    {Ahead rho rate : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
        PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (hsmall :
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) * rho < 1)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1) :
    ‖cmp116PhysicalEndomorphismComplexMatrix
        (cmp116SourcePi4QuotientExactPatchedCovariance
          K hc hmass hK)‖ ≤
      (Ahead *
        (1 - ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) * rho)⁻¹) *
        (((Nc ^ 2 - 1 : ℕ) : ℝ) *
          cmp99PhysicalBondGeometricRowSum 4 rate) := by
  apply
    linfty_opNorm_cmp116PhysicalEndomorphismComplexMatrix_le_of_weightedRow
  · exact hrate
  · exact hgeom
  · exact
      cmp116SourcePi4QuotientExactPatchedCovariance_weightedRow_physical
        K hsourceRange hrange hc hmass hK hD physicalBondDist
        hAhead hrho hrate.le Cert htri hΔ hΔ1 hsmall

/-- Column-norm companion of the exact source covariance estimate.  The
physical weighted kernel certificate controls it with the same constant,
independently of the ambient volume. -/
theorem linfty_opNorm_transpose_cmp116SourcePi4QuotientExactPatchedCovarianceMatrix_le
    {M Q Nc R Δ : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (K : PhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hrange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    {Ahead rho rate : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho) (hrate : 0 < rate)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M))
      hc hmass hK physicalBondDist Ahead rho rate)
    (htri : ∀ target source middle :
        PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hΔ : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Δ)
    (hΔ1 : 1 ≤ Δ)
    (hsmall :
      ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) * rho < 1)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1) :
    ‖(cmp116PhysicalEndomorphismComplexMatrix
        (cmp116SourcePi4QuotientExactPatchedCovariance
          K hc hmass hK)).transpose‖ ≤
      (Ahead *
        (1 - ((cmp116SourcePi4TerminalBranching Δ : ℕ) : ℝ) * rho)⁻¹) *
        (((Nc ^ 2 - 1 : ℕ) : ℝ) *
          cmp99PhysicalBondGeometricRowSum 4 rate) := by
  apply
    linfty_opNorm_transpose_cmp116PhysicalEndomorphismComplexMatrix_le_of_weightedRow
  · exact hrate
  · exact hgeom
  · exact
      cmp116SourcePi4QuotientExactPatchedCovariance_weightedRow_physical
        K hsourceRange hrange hc hmass hK hD physicalBondDist
        hAhead hrho hrate.le Cert htri hΔ hΔ1 hsmall

end

end YangMills.RG
