import YangMills.RG.BalabanCMP99SourceEq395CanonicalCovariance

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCanonicalCovariance
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395FullCoarseRegion_extendZero_comp_restrict_eq_id
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395GeneratedPhysicalCovarianceOnSource_comp_middle
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCanonicalCovariance_comp_globalMiddle_eq_id
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalCorrectedCovariance_eq_canonical
