import YangMills.RG.BalabanCMP89Eq249CentralStabilizedRealLower

/-! Cold-sealed axiom audit for the stabilized CMP89 real lower bound. -/

#print axioms YangMills.RG.cmp89Eq249ComplexNoncentralAliasSum_ofReal_eq
#print axioms YangMills.RG.cmp89Eq249CentralEntireAveragePair_ofReal_eq
#print axioms YangMills.RG.cmp89Eq249CentralStabilizedAliasDenominator_ofReal_eq
#print axioms YangMills.RG.cmp89Eq249RealNoncentralAliasSum_nonneg
#print axioms YangMills.RG.cmp89Eq249CentralStabilizedLowerConstant_le_real
#print axioms YangMills.RG.cmp89Eq249CentralStabilizedLowerConstant_le_re
#print axioms YangMills.RG.cmp89Eq249CentralStabilizedLowerConstant_mono
#print axioms YangMills.RG.cmp85Eq215Floor_le_cmp89Eq249CentralStabilizedAliasDenominator_re
