import YangMills.RG.BalabanCMP99SourceGeneratedCoarseCovarianceTransition

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceMiddle_eq_Qprime_green_sq
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseMiddleTransitionDefect
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseMiddleGreenTransport
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseMiddleTransitionDefect_eq_greenMismatch
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovarianceTransition
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseCovariance_transition_resolvent
