import YangMills.RG.BalabanCMP99Eq360C6dSourceBaselineGreen


namespace YangMills.RG

#print axioms cmp99Eq360C6dSourceBaselinePhysicalPrecision
#print axioms isCoerciveCLM_cmp99Eq360C6dSourceBaselinePhysicalPrecision
#print axioms cmp99Eq360C6dSourceBaselinePhysicalPrecision_isSymmetric
#print axioms cmp99Eq360C6dSourceBaselinePhysicalGreen
#print axioms cmp99Eq360C6dSourceBaselinePhysicalPrecision_comp_green
#print axioms cmp99Eq360C6dSourceBaselinePhysicalGreen_comp_precision
#print axioms norm_cmp99Eq360C6dSourceBaselinePhysicalGreen_le
#print axioms cmp99Eq360C6dSourceBaselinePhysicalGreen_isSymmetric

end YangMills.RG
