import YangMills.RG.BalabanCMP99SourceRetainedPhysicalMass

namespace YangMills.RG

#print axioms CMP99SourceRetainedPhysicalScaleIdentification.ofRetainedTower
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.ofRetainedTower_levelEquiv
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.Qprime
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision_isCoercive
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.green
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.gaugePrecision_comp_green
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.green_comp_gaugePrecision
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.green_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumAverage
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumWeightedAdjoint
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumAverage_comp_stratumWeightedAdjoint
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.towerAt_terminalSpacing_pos
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.norm_restrictStratumCLM_le_one
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.norm_Qprime_apply_sq_le_pow
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.norm_stratumAverage_apply_sq_le_pow
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.inner_gaugePrecision_le_with_source_prefix_weights
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.norm_Qprime_le_one
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.precisionUpperBound
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.precisionUpperBound_pos
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.norm_gaugePrecision_le_precisionUpperBound
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovarianceMiddle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.isCoerciveCLM_stratumCoarseCovarianceMiddle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance_comp_middle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance_middle_comp
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.stratumCoarseCovariance_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.isCoerciveCLM_stratumCoarseCovarianceMiddle_physical
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalStratumCoarseCovariance
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalStratumCoarseCovariance_comp_middle
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalStratumCoarseCovariance_middle_comp
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.physicalStratumCoarseCovariance_isSymmetric
#print axioms CMP99SourceRetainedPhysicalScaleIdentification.Qprime_apply

end YangMills.RG
