import YangMills.RG.BalabanCMP89Eq245EntireAverageAliasStripBound

#print axioms YangMills.RG.norm_cmp89Eq245EntireAverageBase_sub_realSlice_le
#print axioms YangMills.RG.norm_cmp89Eq245EntireAverageBase_pow_sub_one_le
#print axioms YangMills.RG.cmp89Eq245EntireAverageFactor_eq_geometricQuotient
#print axioms YangMills.RG.one_div_three_pi_mul_abs_le_norm_cmp89Eq245EntireAverageBase_sub_one
#print axioms YangMills.RG.one_div_six_pi_mul_abs_le_norm_cmp89Eq245EntireAverageBase_sub_one
#print axioms YangMills.RG.norm_cmp89Eq245EntireAverageFactor_scaled_alias_le
#print axioms YangMills.RG.norm_cmp89Eq245EntireAverageAmplitude_scaled_alias_le
