import YangMills.RG.BalabanCMP99SourceGeneratedSectionCEq3108

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedSectionCSourceCutFactorTower_exponentialKernelBound_toward_eq3108
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceCutFactorTower_exponentialKernelBound_toward_eq3108
