import YangMills.RG.BalabanCMP99SourceGeneratedTerminalCoordinates

open YangMills.RG

#print axioms CMP99SourceActiveRegionChain.terminalSite
#print axioms CMP99SourceActiveRegionChain.terminalSite_mpr
#print axioms cmp99SourcePhysicalTerminalHilbertSpace
#print axioms CMP99SourceActiveRegionChain.terminalHilbertSpace
#print axioms CMP99SourceActiveRegionChain.terminalHilbertSpace_mpr
#print axioms CMP99SourceActiveRegionChain.weightedQprimeTower_terminalSpace_eq
#print axioms CMP99SourceActiveRegionChain.weightedQprimeTower_terminalCarrier_eq
#print axioms cmp99SourceIteratedLiftActiveRegionChain_terminalSite_eq
#print axioms cmp99SourceIteratedLiftActiveRegionChain_terminalHilbertSpace_eq
#print axioms cmp99SourceIteratedLift_weightedQprimeTower_terminalSpace_eq
#print axioms cmp99SourceIteratedLift_weightedQprimeTower_terminalCarrier_eq
#print axioms cmp99SourceTerminalCLMTransport
#print axioms cmp99SourceTerminalCLMTransport_apply_heq
#print axioms cmp99SourceTerminalCLMTransport_trans
#print axioms norm_cmp99SourceTerminalCLMTransport
#print axioms cmp99SourceTerminalCLMTransport_comp
#print axioms cmp99SourceTerminalCLMTransport_smul
#print axioms cmp99SourceTerminalCLMTransport_adjoint
#print axioms cmp99SourceTerminalCLMTransport_sandwich
