import YangMills.RG.BalabanCMP116ComplexOuterActiveDeterminant

#print axioms YangMills.RG.one_sub_norm_pow_activeCard_le_det_shifted_symmetricRealPart
#print axioms YangMills.RG.integral_exp_re_complexQuadratic_le_activeCard
