import YangMills.RG.BalabanCMP116SourcePi4FullComplexWeakenedCovarianceDerivativeSeries

#print axioms YangMills.RG.norm_cmp116SourcePi4FullComplexWeakenedCovarianceLayerDerivative_apply_le
#print axioms YangMills.RG.hasDerivAt_cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_update
