import YangMills.RG.BalabanCMP99SourceGeneratedSectionCHeadSupportWeightedRow

namespace YangMills.RG

#print axioms cmp95SourcePeriodicCoarseOffsetBlock
#print axioms cmp95SourcePeriodicCoarseCellCarrier
#print axioms card_cmp95SourcePeriodicCoarseCellCarrier_le
#print axioms cmp95PeriodicCoordinateSupport_displacement
#print axioms cmp95SourcePeriodicCoarseCellSupport_mem_carrier
#print axioms cmp95SourcePeriodicCoarseCellSupportFinset
#print axioms mem_cmp95SourcePeriodicCoarseCellSupportFinset_iff
#print axioms card_filter_cmp95SourcePeriodicCoarseCellSupport_le
#print axioms cmp99SourceGeneratedCMP95SectionCHeadWeightedRowAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadSupportSites
#print axioms CMP99SourceDependentOmegaGeometry.mem_generatedCMP95SectionCSourceHeadSupportSites_iff
#print axioms CMP99SourceDependentOmegaGeometry.card_generatedCMP95SectionCSourceHeadSupportSites_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCSourceHeadFactorCoordinates_weightedRow_supportSharp

end YangMills.RG
