import YangMills.RG.BalabanCMP116SourcePi4PhysicalComplexContourNonsingularity

#print axioms YangMills.RG.cmp116SourcePi4PhysicalComplexContourDefectBound
#print axioms YangMills.RG.linfty_opNorm_cmp116SourcePi4FullComplexRelativeCovarianceDefect_le
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_det_ne_zero_of_physicalContour
#print axioms YangMills.RG.cmp116SourcePi4_fullComplexPrecision_mul_covariance_eq_one_of_physicalContour
