import YangMills.RG.BalabanCMP99SourceFlatFullComplexPrecisionFibreAction

/-! Cold-sealed axiom audit for the arbitrary fixed-fibre precision action. -/

#print axioms YangMills.RG.cmp99SourceFlatFixedCoarseFibreCoefficientExtension_apply
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_fixedCoarseFibreFourierSynthesis
#print axioms YangMills.RG.cmp99SourceFlatFixedCoarseFibreFourierSynthesis_eq_sum
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionAction_add
#print axioms YangMills.RG.cmp99SourceFlatFullComplexPrecisionAction_finset_sum
#print axioms YangMills.RG.cmp99FlatPhysicalFibreDFT_sourceFlatFullComplexPrecision_fixedCoarseFibre
