import YangMills.RG.BalabanCMP116SourceRestrictedPhysicalAEInteractionBoundary

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.ae_interactionExponent_le_sourcePi4RestrictedPhysicalAlpha5
