import YangMills.RG.BalabanCMP116SourceRestrictedVisitedResolventFactorization

#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceMatrix_restricted_sub_one_eq_finiteFactorization
#print axioms YangMills.RG.cmp116SourcePi4FullComplexRelativeCovarianceDefect_restricted_eq_finiteFactorization
#print axioms YangMills.RG.cmp116SourceRestrictedContour_logDetDensity_sq_mul_activeStateDet_eq_one
