import YangMills.RG.BalabanCMP116SourcePi4MixedWeakenedCovarianceDerivativeSeries

#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_empty
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_singleton
#print axioms YangMills.RG.cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_insert_eq_sub
#print axioms YangMills.RG.hasDerivAt_cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative_update
#print axioms YangMills.RG.summable_norm_cmp116SourcePi4FullComplexWeakenedCovarianceLayer
#print axioms YangMills.RG.summable_norm_cmp116SourcePi4FullComplexWeakenedCovarianceLayerMixedDerivative
#print axioms YangMills.RG.hasDerivAt_cmp116SourcePi4FullComplexWeakenedCovarianceMatrixMixedDerivative_update
