import YangMills.RG.BalabanCMP99SourceEq395GlobalRegionalMiddleSourceDecay

#print axioms YangMills.RG.cmp99SourceIteratedLift_terminalRepresentative_finBoxDist_rectangular
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectOnSource
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99Eq395PhysicalGlobalRegionalMiddleDefectOnSource_exponentialKernelBound
