/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99GeneralizedRandomWalkSummability
import YangMills.RG.BalabanCMP99SourceDisplayedSectionCSubalphabet

/-!
# The convergent series generated by the displayed CMP99 Section C factors

CMP99 (3.107) has one distinguished covariance head followed by a word of
continuation factors.  This file flattens exactly the four continuation
species already reconstructed from the printed formulas: cut, commutator,
basic, and basic-adjoint.  Their source and target carriers remain explicit.

The resulting successor family has at most three arrows out of every carrier:
at a coarse scale there are the commutator, the optional next-scale cut, and
the coarse-to-fine basic-adjoint arrow; at a fine scale only the basic arrow
is available.  Every generated flat word is transported back to a genuinely
typed `DependentArrowWalk`, so the ordered product is never formed by padding
rectangular operators with zeroes.

Honest scope: this is the absolutely convergent subseries generated by the
five factors displayed explicitly on CMP99 pp. 412--415.  The paper writes
"etc."; hence no theorem below identifies this subseries with the complete
propagator.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator RealInnerProductSpace

noncomputable section

universe v

namespace CMP99SourceDependentOmegaGeometry

/-- The four displayed continuation species after the distinguished head. -/
inductive CMP99DisplayedSectionCContinuation (j : ℕ) where
  | cut (r : Fin (j + 1))
  | commutator (s : Fin (j + 2))
  | basic (s : Fin (j + 2))
  | basicAdjoint (s : Fin (j + 2))
deriving DecidableEq, Fintype

/-- Literal source carrier of a flattened displayed continuation. -/
def CMP99DisplayedSectionCContinuation.source
    {j : ℕ} : CMP99DisplayedSectionCContinuation j →
      CMP99SectionCHeterogeneousIndex j
  | .cut r => (r.castSucc, .coarse)
  | .commutator s => (s, .coarse)
  | .basic s => (s, .fine)
  | .basicAdjoint s => (s, .coarse)

/-- Literal target carrier of a flattened displayed continuation. -/
def CMP99DisplayedSectionCContinuation.target
    {j : ℕ} : CMP99DisplayedSectionCContinuation j →
      CMP99SectionCHeterogeneousIndex j
  | .cut r => (r.succ, .coarse)
  | .commutator s => (s, .coarse)
  | .basic s => (s, .fine)
  | .basicAdjoint s => (s, .fine)

/-- Restore a flat continuation as the corresponding dependent source label. -/
def CMP99DisplayedSectionCContinuation.toDependentLabel
    {j : ℕ} (label : CMP99DisplayedSectionCContinuation j) :
    CMP99DisplayedSectionCSubalphabet j label.source label.target := by
  cases label with
  | cut r => exact .coarse (.displayed (.cut r))
  | commutator s => exact .coarse (.displayed (.commutator s))
  | basic s => exact .heterogeneous (.basic s)
  | basicAdjoint s => exact .heterogeneous (.basicAdjoint s)

/-- A flat continuation paired with its definitionally correct target. -/
def cmp99DisplayedSectionCContinuationStep {j : ℕ}
    (label : CMP99DisplayedSectionCContinuation j) :
    CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
      (CMP99SectionCHeterogeneousIndex j) :=
  ⟨label, label.target⟩

/-- The finite, source-typed successor family generated by the four printed
continuation species. -/
def cmp99DisplayedSectionCSuccessors {j : ℕ}
    (i : CMP99SectionCHeterogeneousIndex j) :
    Finset (CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
      (CMP99SectionCHeterogeneousIndex j)) :=
  match i with
  | (s, .coarse) =>
      let base := {
        cmp99DisplayedSectionCContinuationStep (.commutator s),
        cmp99DisplayedSectionCContinuationStep (.basicAdjoint s) }
      if h : s.val < j + 1 then
        insert (cmp99DisplayedSectionCContinuationStep (.cut ⟨s.val, h⟩)) base
      else base
  | (s, .fine) =>
      {cmp99DisplayedSectionCContinuationStep (.basic s)}

/-- The displayed continuation alphabet has branching at most three,
independently of the number of scales and of the ambient volume. -/
theorem card_cmp99DisplayedSectionCSuccessors_le_three {j : ℕ}
    (i : CMP99SectionCHeterogeneousIndex j) :
    (cmp99DisplayedSectionCSuccessors i).card ≤ 3 := by
  rcases i with ⟨s, kind⟩
  cases kind with
  | coarse =>
      have hbase : ({
          cmp99DisplayedSectionCContinuationStep (.commutator s),
          cmp99DisplayedSectionCContinuationStep (.basicAdjoint s) } :
          Finset (CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
            (CMP99SectionCHeterogeneousIndex j))).card ≤ 2 := by
        calc
          _ ≤ ({cmp99DisplayedSectionCContinuationStep (.basicAdjoint s)} :
              Finset (CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
                (CMP99SectionCHeterogeneousIndex j))).card + 1 :=
            Finset.card_insert_le _ _
          _ = 2 := by simp
      simp only [cmp99DisplayedSectionCSuccessors]
      split
      · calc
          _ ≤ ({
              cmp99DisplayedSectionCContinuationStep (.commutator s),
              cmp99DisplayedSectionCContinuationStep (.basicAdjoint s) } :
              Finset (CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
                (CMP99SectionCHeterogeneousIndex j))).card + 1 :=
            Finset.card_insert_le _ _
          _ ≤ 2 + 1 := Nat.add_le_add_right hbase 1
          _ = 3 := rfl
      · exact hbase.trans (by omega)
  | fine => simp [cmp99DisplayedSectionCSuccessors]

/-- Membership in the explicit successor family certifies both endpoints. -/
theorem endpoints_of_mem_cmp99DisplayedSectionCSuccessors {j : ℕ}
    {i : CMP99SectionCHeterogeneousIndex j}
    {step : CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
      (CMP99SectionCHeterogeneousIndex j)}
    (hstep : step ∈ cmp99DisplayedSectionCSuccessors i) :
    step.label.source = i ∧ step.domain = step.label.target := by
  rcases i with ⟨s, kind⟩
  cases kind with
  | coarse =>
      simp only [cmp99DisplayedSectionCSuccessors] at hstep
      split at hstep
      · simp only [Finset.mem_insert, Finset.mem_singleton] at hstep
        rcases hstep with h | h | h
        · subst step
          constructor
          · ext
            · rfl
            · rfl
          · rfl
        · subst step
          simp [CMP99DisplayedSectionCContinuation.source,
            CMP99DisplayedSectionCContinuation.target,
            cmp99DisplayedSectionCContinuationStep]
        · subst step
          simp [CMP99DisplayedSectionCContinuation.source,
            CMP99DisplayedSectionCContinuation.target,
            cmp99DisplayedSectionCContinuationStep]
      · simp only [Finset.mem_insert, Finset.mem_singleton] at hstep
        rcases hstep with h | h
        · subst step
          simp [CMP99DisplayedSectionCContinuation.source,
            CMP99DisplayedSectionCContinuation.target,
            cmp99DisplayedSectionCContinuationStep]
        · subst step
          simp [CMP99DisplayedSectionCContinuation.source,
            CMP99DisplayedSectionCContinuation.target,
            cmp99DisplayedSectionCContinuationStep]
  | fine =>
      simp only [cmp99DisplayedSectionCSuccessors,
        Finset.mem_singleton] at hstep
      subst step
      simp [CMP99DisplayedSectionCContinuation.source,
        CMP99DisplayedSectionCContinuation.target,
        cmp99DisplayedSectionCContinuationStep]

/-- A flat list is well typed from `start` when every label starts at the
current carrier and hands its literal target to the remaining list. -/
def CMP99DisplayedSectionCContinuation.IsTyped {j : ℕ}
    (start : CMP99SectionCHeterogeneousIndex j) :
    List (CMP99DisplayedSectionCContinuation j) → Prop
  | [] => True
  | label :: rest =>
      label.source = start ∧
        CMP99DisplayedSectionCContinuation.IsTyped label.target rest

/-- Every tail generated by the explicit successors is well typed. -/
theorem isTyped_of_mem_cmp99DisplayedSectionCAdmissibleTails {j : ℕ} :
    ∀ {n : ℕ} {start : CMP99SectionCHeterogeneousIndex j}
      {tail : List (CMP99WalkStep (CMP99DisplayedSectionCContinuation j)
        (CMP99SectionCHeterogeneousIndex j))},
      tail ∈ cmp99AdmissibleTails cmp99DisplayedSectionCSuccessors start n →
      CMP99DisplayedSectionCContinuation.IsTyped start
        (tail.map CMP99WalkStep.label) := by
  intro n
  induction n with
  | zero =>
      intro start tail htail
      have hnil : tail = [] := Finset.mem_singleton.mp
        (by simpa [cmp99AdmissibleTails] using htail)
      subst tail
      trivial
  | succ n ih =>
      intro start tail htail
      simp only [cmp99AdmissibleTails, Finset.mem_biUnion,
        Finset.mem_image] at htail
      obtain ⟨step, hstep, rest, hrest, rfl⟩ := htail
      have hend := endpoints_of_mem_cmp99DisplayedSectionCSuccessors hstep
      simp only [List.map_cons]
      constructor
      · exact hend.1
      · simpa [hend.2] using ih hrest

/-- Turn a well-typed flat list into a genuinely dependent arrow walk. -/
def CMP99DisplayedSectionCContinuation.toDependentWalk {j : ℕ} :
    ∀ {start : CMP99SectionCHeterogeneousIndex j}
      (labels : List (CMP99DisplayedSectionCContinuation j)),
      CMP99DisplayedSectionCContinuation.IsTyped start labels →
      Σ target, DependentArrowWalk (CMP99DisplayedSectionCSubalphabet j)
        start target
  | start, [], _ => ⟨start, .nil start⟩
  | start, label :: rest, htyped => by
      rcases htyped with ⟨hsource, hrest⟩
      subst start
      let tail := CMP99DisplayedSectionCContinuation.toDependentWalk rest hrest
      exact ⟨tail.1, .cons label.toDependentLabel tail.2⟩

/-- Flattening and restoring a typed continuation preserves its length. -/
theorem CMP99DisplayedSectionCContinuation.length_toDependentWalk {j : ℕ} :
    ∀ {start : CMP99SectionCHeterogeneousIndex j}
      (labels : List (CMP99DisplayedSectionCContinuation j))
      (htyped : CMP99DisplayedSectionCContinuation.IsTyped start labels),
      (CMP99DisplayedSectionCContinuation.toDependentWalk labels htyped).2.length =
        labels.length := by
  intro start labels
  induction labels generalizing start with
  | nil =>
      intro htyped
      rfl
  | cons label rest ih =>
      intro htyped
      rcases htyped with ⟨hsource, hrest⟩
      subst start
      simp only [CMP99DisplayedSectionCContinuation.toDependentWalk,
        DependentArrowWalk.length, List.length_cons]
      rw [ih hrest]

/-- A generated anchored continuation tail on the real dependent carriers. -/
def CMP99AnchoredWalk.toDisplayedSectionCDependentWalk {j : ℕ}
    {start : CMP99SectionCHeterogeneousIndex j}
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors start) :
    Σ target, DependentArrowWalk (CMP99DisplayedSectionCSubalphabet j)
      start target :=
  CMP99DisplayedSectionCContinuation.toDependentWalk
    (walk.2.1.map CMP99WalkStep.label)
    (isTyped_of_mem_cmp99DisplayedSectionCAdmissibleTails walk.2.2)

@[simp] theorem CMP99AnchoredWalk.toDisplayedSectionCDependentWalk_length
    {j : ℕ} {start : CMP99SectionCHeterogeneousIndex j}
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors start) :
    (CMP99AnchoredWalk.toDisplayedSectionCDependentWalk walk).2.length =
      walk.1 := by
  rw [toDisplayedSectionCDependentWalk,
    CMP99DisplayedSectionCContinuation.length_toDependentWalk]
  simp only [List.length_map]
  exact length_eq_of_mem_cmp99AdmissibleTails
    cmp99DisplayedSectionCSuccessors walk.2.2

/-- Prepend the distinguished covariance head required by CMP99 (3.107). -/
def CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk {j : ℕ}
    (s : Fin (j + 2))
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
      (s, CMP99SectionCCarrierKind.coarse)) :
    Σ target, DependentArrowWalk (CMP99DisplayedSectionCSubalphabet j)
      (s, CMP99SectionCCarrierKind.coarse) target := by
  let tail := CMP99AnchoredWalk.toDisplayedSectionCDependentWalk walk
  exact ⟨tail.1, .cons (.coarse (.head s)) tail.2⟩

@[simp] theorem CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk_length
    {j : ℕ} (s : Fin (j + 2))
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
      (s, CMP99SectionCCarrierKind.coarse)) :
    (CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk s walk).2.length =
      walk.1 + 1 := by
  simp [toDisplayedSectionCHeadedDependentWalk, DependentArrowWalk.length]

private theorem prod_map_const_eq_pow {alpha : Type*}
    (rho : ℝ) (xs : List alpha) :
    (xs.map fun _ => rho).prod = rho ^ xs.length := by
  induction xs with
  | nil => simp
  | cons _ rest ih => simp [pow_succ, mul_comm]

/-- A constant scalar head and continuation weight evaluate exactly to the
radial majorant indexed by source length. -/
theorem CMP99AnchoredWalk.term_const_eq {j : ℕ}
    {start : CMP99SectionCHeterogeneousIndex j}
    (A rho : ℝ)
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors start) :
    walk.term (fun _ => A) (fun _ _ => rho) = A * rho ^ walk.1 := by
  rw [CMP99AnchoredWalk.term, CMP99GeneralizedWalk.term]
  rw [List.prod_cons, prod_map_const_eq_pow]
  congr 1
  exact congrArg (rho ^ ·) <|
    length_eq_of_mem_cmp99AdmissibleTails
      cmp99DisplayedSectionCSuccessors walk.2.2

variable {M Nc Q j : ℕ} [NeZero M] [NeZero Nc] [NeZero Q]
variable {cell : FinBox 4 Q}
variable {ScaleSite : Fin (j + 2) → Type v}
variable [∀ r, DecidableEq (ScaleSite r)]
variable {Scaled : CMP99SourceScaledStratification
  (FinBox 4 (2 * Q)) (j + 2) ScaleSite}
variable {dist : FinBox 4 (2 * Q) → FinBox 4 (2 * Q) → ℕ}
variable {gap : Fin (j + 1) → ℕ}

/-- The literal headed operator associated with a generated flat word.  Its
target remains in the sigma type because the printed factors are genuinely
rectangular between coarse and fine carriers. -/
noncomputable def generatedCMP95DisplayedSectionCHeadedWalkOperator
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    (s : Fin (j + 2))
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
      (s, CMP99SectionCCarrierKind.coarse)) :
    Σ target, DependentBundledHilbertArrow
      (D.generatedSectionCHeterogeneousSpace hpi5 hM depth spacing epsilon
        background budget fineSmall)
      (s, CMP99SectionCCarrierKind.coarse) target := by
  let typed := CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk s walk
  exact ⟨typed.1, dependentBundledHilbertWalkOperator
    (D.generatedSectionCHeterogeneousSpace hpi5 hM depth spacing epsilon
      background budget fineSmall)
    (typed.2.map (D.generatedCMP95DisplayedSectionCLabelOperator P hpi5 hM
      depth hspacing background budget fineSmall hsmall))⟩

/-- Every displayed headed word has the physical geometric norm majorant
`rho^(n+1)`, where `n` is the number of continuation factors. -/
theorem norm_generatedCMP95DisplayedSectionCHeadedWalkOperator_le
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    (s : Fin (j + 2))
    (walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
      (s, CMP99SectionCCarrierKind.coarse)) :
    ‖(D.generatedCMP95DisplayedSectionCHeadedWalkOperator P hpi5 hM depth
      hspacing background budget fineSmall hsmall s walk).2‖ ≤
      generatedCMP95DisplayedSectionCUniformNormAmplitude
          P M depth spacing epsilon *
        generatedCMP95DisplayedSectionCUniformNormAmplitude
          P M depth spacing epsilon ^ walk.1 := by
  let typed := CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk s walk
  have hbound := D.norm_generatedCMP95DisplayedSectionCOperatorWalk_le_uniform_pow
    P hpi5 hM depth hspacing background budget fineSmall hsmall typed.2
  rw [CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk_length] at hbound
  simpa only [generatedCMP95DisplayedSectionCHeadedWalkOperator, typed,
    pow_succ, mul_comm] using hbound

/-- The norms of all physically typed words in the displayed subseries are
summable under the explicit source-independent branching condition
`3 * rho < 1`.  This proves convergence of the displayed subseries without
identifying it with the paper's non-exhaustively specified full propagator. -/
theorem summable_norm_generatedCMP95DisplayedSectionCHeadedWalkOperator
    (D : CMP99SourceDependentOmegaGeometry
      (FinBox 4 (2 * Q)) j ScaleSite Scaled
      (cmp99SourceTildePiLargeBlocks cell 3)
      (cmp99SourceTildePiLargeBlocks cell 4) dist gap)
    (P : CMP95SourceSmoothPartitionProfile)
    (hpi5 : D.fineRegion (cmp99OmegaZeroIndex j) ⊆
      cmp99SourceTildePiLargeBlocks cell 5)
    (hM : 2 ≤ M) (depth : ℕ)
    {spacing epsilon : ℝ} (hspacing : 0 < spacing)
    (background : GaugeConfig 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)) (SUN Nc))
    (budget : CMP99SourceUbarClosedBudget 4 M Nc (depth + 1) epsilon)
    (fineSmall : ∀ e : ConcreteEdge 4
      (cmp99RegionalLatticeSize M (2 * Q) (depth + 1)),
      ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon)
    (hsmall : cmp99SourcePoincareErrorCoeff 4 M (depth + 1)
      spacing epsilon < 1)
    (s : Fin (j + 2))
    (hcontract : 3 * generatedCMP95DisplayedSectionCUniformNormAmplitude
      P M depth spacing epsilon < 1) :
    Summable fun walk : CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
        (s, CMP99SectionCCarrierKind.coarse) =>
      ‖(D.generatedCMP95DisplayedSectionCHeadedWalkOperator P hpi5 hM depth
        hspacing background budget fineSmall hsmall s walk).2‖ := by
  let rho := generatedCMP95DisplayedSectionCUniformNormAmplitude
    P M depth spacing epsilon
  have hrho : 0 ≤ rho :=
    generatedCMP95DisplayedSectionCUniformNormAmplitude_nonneg
      P M depth spacing epsilon
  have hmajorant : Summable fun walk :
      CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
        (s, CMP99SectionCCarrierKind.coarse) => rho * rho ^ walk.1 := by
    have hterm : ∀ walk :
        CMP99AnchoredWalk cmp99DisplayedSectionCSuccessors
          (s, CMP99SectionCCarrierKind.coarse),
        ‖walk.term (fun _ => rho) (fun _ _ => rho)‖ ≤
          rho * rho ^ walk.1 := by
      intro walk
      rw [CMP99AnchoredWalk.term_const_eq]
      simp only [Real.norm_eq_abs, abs_of_nonneg
        (mul_nonneg hrho (pow_nonneg hrho walk.1))]
      exact le_rfl
    have hradial := summable_cmp99AnchoredWalk_radialMajorant
      cmp99DisplayedSectionCSuccessors
      (s, CMP99SectionCCarrierKind.coarse)
      (fun _ => (∅ : Finset Unit))
      (fun _ => rho) (fun _ _ => rho)
      3 0 rho rho 1
      card_cmp99DisplayedSectionCSuccessors_le_three
      (fun _ => by simp) hrho hrho (by norm_num)
      (by simpa [rho] using hcontract)
      hterm
    have habs : |rho| = rho := abs_of_nonneg hrho
    simpa [CMP99AnchoredWalk.active, CMP99GeneralizedWalk.active,
      CMP99AnchoredWalk.term_const_eq, Real.norm_eq_abs, habs] using hradial
  exact Summable.of_nonneg_of_le
    (fun _ => norm_nonneg _)
    (fun walk => D.norm_generatedCMP95DisplayedSectionCHeadedWalkOperator_le
      P hpi5 hM depth hspacing background budget fineSmall hsmall s walk)
    hmajorant

end CMP99SourceDependentOmegaGeometry

end
end YangMills.RG
