import YangMills.RG.BalabanCMP116SourceCenteredPhysicalQuadraticResidualAEInteraction

#print axioms YangMills.RG.CMP116Eq214PhysicalContourDensity.ae_interactionExponent_le_sourcePhysicalAlpha5_of_centeredQuadraticResidual
