/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP102Eq80PropagatorDerivative
import YangMills.RG.BalabanCMP116SourcePi4RealMixedDerivativeCertificate

/-!
# Mixed weakening derivative of the literal CMP102 equation-(80) potential

The reconstructed real mixed covariance is inserted directly as the
propagator in the four-term equation-(80) functional.  Its source-produced
operator derivative certificate then gives the exact weakening derivative of
that literal potential.  The contribution of `V₀` is its actual Fréchet
derivative at the shifted physical field; no synthetic potential or derivative
bound is introduced.
-/

open scoped RealInnerProductSpace

namespace YangMills.RG

noncomputable section

private abbrev PhysicalField (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

private abbrev PhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalField M Q Nc →L[ℝ] PhysicalField M Q Nc

/-- The literal equation-(80) potential with the reconstructed real mixed
covariance as propagator. -/
noncomputable def cmp102Eq80SourcePi4RealMixedPotential
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (A : PhysicalField M Q Nc) : ℝ :=
  cmp102Eq80GlobalPotential D D₃ V₀
    (cmp116SourcePi4FullRealWeakenedCovarianceMixedDerivative
      (R := R) anchor K hc hmass hK s S)
    Δπ J A

/-- The exact equation-(80) directional derivative generated by the next
mixed physical covariance. -/
noncomputable def cmp102Eq80SourcePi4RealMixedPotentialDerivative
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (t : ℝ)
    (A : PhysicalField M Q Nc)
    (V₀' : PhysicalField M Q Nc →L[ℝ] ℝ) : ℝ :=
  cmp102Eq80PropagatorDirectionalDerivative D D₃
    (cmp116SourcePi4FullRealWeakenedCovarianceMixedDerivative
      (R := R) anchor K hc hmass hK (Function.update s d t) S)
    (cmp116SourcePi4FullRealWeakenedCovarianceMixedDerivative
      (R := R) anchor K hc hmass hK s (insert d S))
    Δπ J A V₀'

/-- Equation-(80) evaluated along the named physical covariance curve. -/
noncomputable def cmp102Eq80SourcePi4RealMixedPotentialCurve
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (A : PhysicalField M Q Nc)
    (u : ℝ) : ℝ :=
  cmp102Eq80GlobalPotential D D₃ V₀
    (cmp116SourcePi4RealMixedCovarianceOperatorCurve
      (R := R) anchor K hc hmass hK s S d u)
    Δπ J A

/-- Directional derivative of the named equation-(80) curve. -/
noncomputable def cmp102Eq80SourcePi4RealMixedPotentialCurveDerivative
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (A : PhysicalField M Q Nc)
    (t : ℝ)
    (V₀' : PhysicalField M Q Nc →L[ℝ] ℝ) : ℝ :=
  cmp102Eq80PropagatorDirectionalDerivative D D₃
    (cmp116SourcePi4RealMixedCovarianceOperatorCurve
      (R := R) anchor K hc hmass hK s S d t)
    (cmp116SourcePi4RealMixedCovarianceOperatorDerivative
      (R := R) anchor K hc hmass hK s S d)
    Δπ J A V₀'

/-- The named curve is the literal mixed potential with one coordinate
updated. -/
theorem cmp102Eq80SourcePi4RealMixedPotentialCurve_eq
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (A : PhysicalField M Q Nc)
    (u : ℝ) :
    cmp102Eq80SourcePi4RealMixedPotentialCurve
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J s S d A u =
      cmp102Eq80SourcePi4RealMixedPotential
        (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
        (Function.update s d u) S A := by
  unfold cmp102Eq80SourcePi4RealMixedPotentialCurve
    cmp102Eq80SourcePi4RealMixedPotential
  rw [cmp116SourcePi4RealMixedCovarianceOperatorCurve_eq]

/-- The named curve derivative is the literal next mixed covariance
directional derivative. -/
theorem cmp102Eq80SourcePi4RealMixedPotentialCurveDerivative_eq
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (A : PhysicalField M Q Nc)
    (t : ℝ)
    (V₀' : PhysicalField M Q Nc →L[ℝ] ℝ) :
    cmp102Eq80SourcePi4RealMixedPotentialCurveDerivative
        (R := R) anchor K hc hmass hK D D₃ Δπ J s S d A t V₀' =
      cmp102Eq80SourcePi4RealMixedPotentialDerivative
        (R := R) anchor K hc hmass hK D D₃ Δπ J s S d t A V₀' := by
  unfold cmp102Eq80SourcePi4RealMixedPotentialCurveDerivative
    cmp102Eq80SourcePi4RealMixedPotentialDerivative
  rw [cmp116SourcePi4RealMixedCovarianceOperatorCurve_eq,
    cmp116SourcePi4RealMixedCovarianceOperatorDerivative_eq]

/-- The one-coordinate derivative recurrence for the literal mixed
equation-(80) potential. -/
def CMP116SourcePi4RealMixedEq80DerivativeStatement
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (A : PhysicalField M Q Nc)
    (t : ℝ)
    (V₀' : PhysicalField M Q Nc →L[ℝ] ℝ) : Prop :=
  HasDerivAt
    (cmp102Eq80SourcePi4RealMixedPotentialCurve
      (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J s S d A)
    (cmp102Eq80SourcePi4RealMixedPotentialCurveDerivative
      (R := R) anchor K hc hmass hK D D₃ Δπ J s S d A t V₀')
    t

set_option maxHeartbeats 2500000 in
/-- The source-produced covariance recurrence differentiates the literal
equation-(80) potential in one fresh weakening coordinate. -/
theorem
    CMP116SourcePi4RealMixedDerivativeCertificate.hasDerivAt_eq80Potential
    {M Q Nc R : ℕ}
    [NeZero M] [NeZero Q] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (K : PhysicalEndomorphism M Q Nc)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (D D₃ : PhysicalField M Q Nc → PhysicalField M Q Nc)
    (V₀ : PhysicalField M Q Nc → ℝ)
    (Δπ : PhysicalEndomorphism M Q Nc)
    (J : PhysicalField M Q Nc)
    (s : FinBox 4 (2 * Q) → ℝ)
    (S : Finset (FinBox 4 (2 * Q)))
    (d : FinBox 4 (2 * Q))
    (A : PhysicalField M Q Nc)
    (t : ℝ)
    (Cert : CMP116SourcePi4RealMixedDerivativeCertificate
      (R := R) anchor K hc hmass hK s S d t)
    (V₀' : PhysicalField M Q Nc →L[ℝ] ℝ)
    (hV₀ : HasFDerivAt V₀ V₀'
      (A -
        cmp116SourcePi4RealMixedCovarianceOperatorCurve
          (R := R) anchor K hc hmass hK s S d t (D A))) :
    CMP116SourcePi4RealMixedEq80DerivativeStatement
      (R := R) anchor K hc hmass hK D D₃ V₀ Δπ J
      s S d A t V₀' := by
  unfold CMP116SourcePi4RealMixedEq80DerivativeStatement
  have hoperator := Cert.hasDerivAt_operator
  unfold cmp102Eq80SourcePi4RealMixedPotentialCurve
    cmp102Eq80SourcePi4RealMixedPotentialCurveDerivative
  exact
    hasDerivAt_cmp102Eq80GlobalPotential_propagatorCurve
      D D₃ V₀
      (cmp116SourcePi4RealMixedCovarianceOperatorCurve
        (R := R) anchor K hc hmass hK s S d)
      (cmp116SourcePi4RealMixedCovarianceOperatorDerivative
        (R := R) anchor K hc hmass hK s S d)
      Δπ J A t hoperator V₀' hV₀

end

end YangMills.RG
