import YangMills.RG.BalabanCMP99Eq359ComplexRegionalTowerPair

#print axioms YangMills.RG.CMP99Eq359ComplexRegionalTowerPair.stop
#print axioms YangMills.RG.CMP99Eq359ComplexRegionalTowerPair.step
#print axioms YangMills.RG.CMP99Eq359ComplexRegionalTowerPair.F2
#print axioms YangMills.RG.CMP99Eq359ComplexRegionalTowerPair.F2star
#print axioms YangMills.RG.CMP99Eq359ComplexRegionalTowerPair.Q1_eq_Q0_add_F2
#print axioms YangMills.RG.CMP99Eq359ComplexRegionalTowerPair.starred1_eq_starred0_add_F2star
