import YangMills.RG.BalabanCMP102Eq80SourcePi4FaaDiBrunoPhysicalDomainExpansion

#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBruno_partitionTerm_eq_sum_domainChoices
#print axioms YangMills.RG.sum_cmp102Eq80SourcePi4FaaDiBrunoPartitionDomainCoefficient
#print axioms YangMills.RG.iteratedFDeriv_cmp102Eq80SourcePi4RealPotentialVertexPolynomial_apply_coordinateBlock_eq_sum_physicalDomains
#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBrunoPartitionDomainCoefficient_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBrunoPartitionDomainCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBrunoDomainCoefficient_eq_zero_of_not_subset
#print axioms YangMills.RG.cmp102Eq80SourcePi4FaaDiBrunoDomainCoefficient_eq_zero_of_not_walkConnected
#print axioms YangMills.RG.iteratedFDeriv_cmp102Eq80SourcePi4RealPotentialVertexPolynomial_apply_coordinateBlock_eq_sum_connectedPhysicalDomains
