import YangMills.RG.BalabanCMP89SourceNeumannTwoLevelPoincareAlgebra

#print axioms YangMills.RG.le_twoLevelPoincare_of_feedback_lt_one
#print axioms YangMills.RG.norm_sq_le_twoLevelPoincare_of_derivative_feedback
