import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedFlatPhysicalGreenIdentification

#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalStep7bGreenCLM
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalStep7bGreenCLM_comp_precision
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalStabilizedAliasDenominator_ne_zero
#print axioms YangMills.RG.cmp99SourceSeparatedGeneratedFlatPhysicalStabilizedFieldCLM_eq_green_comp
