import YangMills.RG.BalabanCMP102PhysicalIntrinsicCorrectionAnalytic

#print axioms YangMills.RG.cmp102PhysicalCochainToAmbientCLM_apply
#print axioms YangMills.RG.cmp102IntrinsicAmbientCorrectionBond_physical_eq
#print axioms YangMills.RG.analyticAt_cmp102IntrinsicAmbientCorrectionBond
#print axioms YangMills.RG.cmp102IntrinsicPhysicalNonlinearCorrection_apply
#print axioms YangMills.RG.cmp102PhysicalNonlinearCorrectionOfBudget_eq_intrinsic
#print axioms YangMills.RG.contDiffAt_cmp102IntrinsicPhysicalNonlinearCorrection
