import YangMills.RG.BalabanCMP116ComplexOuterNearLog

#print axioms YangMills.RG.integral_exp_re_complexQuadratic_standardGaussianPi_le_exp_traceNearLog
#print axioms YangMills.RG.integral_exp_re_complexQuadratic_standardGaussianPi_le_of_tracePowers
