import YangMills.RG.BalabanCMP116SourceRestrictedShiftedComplexContour

#print axioms YangMills.RG.cmp116SourceRestrictedShiftedCoupling
#print axioms YangMills.RG.cmp116SourceRestrictedShiftedCoupling_card
#print axioms YangMills.RG.cmp116SourceRestrictedShiftedCoupling_zero
#print axioms YangMills.RG.cmp116SourceRestrictedShiftedCoupling_eq_one_of_not_mem
#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_sub_one_of_mem
#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_sub_one_of_not_mem
#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_sub_one_le
#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_sub_one_le_global
#print axioms YangMills.RG.norm_cmp116SourceRestrictedShiftedCoupling_le_one_add_global
#print axioms YangMills.RG.cmp116SourceRestrictedShiftedCoupling_eq_one_of_not_mem_sigmaZero
#print axioms YangMills.RG.cmp116ComplexWeakeningMonomial_restrictedShiftedCoupling
#print axioms YangMills.RG.cmp116ComplexWeakeningMonomial_restrictedShiftedCoupling_sub_one_eq_sum
#print axioms YangMills.RG.cmp116ComplexWeakeningMonomial_restrictedShiftedCoupling_sub_one_eq_zero
