import YangMills.RG.BalabanCMP99SourceGeneratedLaplacianTransitionSupport

open YangMills.RG

#print axioms cmp99ActiveRegion_restrictZero_eq_extendZero_adjoint
#print axioms cmp99GeneratedAmbientScaledCovariantLaplacian
#print axioms cmp99ActiveRegionSourceCovariantLaplacian_apply_eq_compression
#print axioms cmp99GeneratedAmbientScaledCovariantLaplacian_apply
#print axioms cmp99GeneratedAmbientScaledCovariantLaplacian_apply_eq_zero
#print axioms cmp99NestedTransitionInnerCollar
#print axioms mem_cmp99NestedTransitionInnerCollar_iff
#print axioms cmp99NestedTransition_extend_restrict_apply
#print axioms cmp99NestedLaplacianPrecisionDefect_apply_eq_zero
#print axioms cmp99NestedTransitionInnerCollarRegion
#print axioms cmp99NestedTransitionInnerCollarProjection
#print axioms cmp99NestedTransitionInnerCollarProjection_apply
#print axioms cmp99NestedTransitionInnerCollarProjection_comp_laplacianDefect
#print axioms CMP99SourceDependentOmegaGeometry.generatedTransitionInnerCollar
#print axioms CMP99SourceDependentOmegaGeometry.generatedTransitionInnerCollarProjection
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalPrecisionDefect_apply_eq_zero
#print axioms CMP99SourceDependentOmegaGeometry.generatedTransitionInnerCollarProjection_comp_precisionDefect
