import YangMills.RG.BalabanCMP99SourceFlatGeneratedTerminalComplexFieldData

#print axioms YangMills.RG.CMP99SourceGeneratedTerminalComplexFieldData.ofActiveField
#print axioms YangMills.RG.CMP99SourceGeneratedTerminalComplexFieldData.complexZeroExtension_apply_eq_complexification_realZeroExtension
#print axioms YangMills.RG.CMP99SourceGeneratedTerminalComplexFieldData.activeLaplacian_apply_eq_compression
