import YangMills.RG.BalabanCMP99SourceDisplayedSectionCSeries

#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation.source
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation.target
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation.toDependentLabel
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99DisplayedSectionCContinuationStep
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.cmp99DisplayedSectionCSuccessors
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.card_cmp99DisplayedSectionCSuccessors_le_three
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.endpoints_of_mem_cmp99DisplayedSectionCSuccessors
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation.IsTyped
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.isTyped_of_mem_cmp99DisplayedSectionCAdmissibleTails
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation.toDependentWalk
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99DisplayedSectionCContinuation.length_toDependentWalk
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99AnchoredWalk.toDisplayedSectionCDependentWalk
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99AnchoredWalk.toDisplayedSectionCDependentWalk_length
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99AnchoredWalk.toDisplayedSectionCHeadedDependentWalk_length
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.CMP99AnchoredWalk.term_const_eq
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95DisplayedSectionCHeadedWalkOperator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.norm_generatedCMP95DisplayedSectionCHeadedWalkOperator_le
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.summable_norm_generatedCMP95DisplayedSectionCHeadedWalkOperator
