import YangMills.RG.BalabanCMP99SourceActiveRegionFullCompanionAmbientPrecision


#print axioms YangMills.RG.cmp99SourceFullActiveRegionSiteEquiv
#print axioms YangMills.RG.cmp99SourceFullActiveRegion_restrictZero_eq_reindex
#print axioms YangMills.RG.cmp99SourceFullActiveRegion_extendZero_eq_reindex
#print axioms YangMills.RG.cmp99SourceActiveRegionFullCompanionAmbientPrecision
#print axioms YangMills.RG.cmp99SourceAmbientDirichletPrecision
#print axioms YangMills.RG.isCoerciveCLM_cmp99SourceAmbientDirichletPrecision
#print axioms YangMills.RG.isCoerciveCLM_cmp99SourceActiveRegionFullCompanionAmbientPrecision
#print axioms YangMills.RG.cmp99SourceAmbientDirichletPrecision_fullCompanion_eq
