import YangMills.RG.BalabanCMP99Eq359ComplexRegionalTowerPair

/-!
# CMP99 (3.60): exact analytic precision perturbation on one regional carrier

The forward perturbation `F2` and the printed starred perturbation `F2star`
are obtained from one internally constructed Eq. (3.59) tower pair.  The
three averaging terms remain literal and separate.

This is an algebraic leaf, not the source-facing producer.  It deliberately
still receives the two covariant Laplacians.  A later wrapper must construct
those Laplacians from the baseline and perturbed physical backgrounds on the
same typed source region; accepting them here does not discharge that source
dictionary, the regional inverse, or any four-action estimate.
-/

namespace YangMills.RG

noncomputable section

/-- Analytic regional precision with the printed starred synthesis kept
independent of the Hilbert adjoint away from the compact real slice. -/
def cmp99Eq360ComplexRegionalPrecision
    {E F : Type*}
    [SeminormedAddCommGroup E] [NormedSpace ℂ E]
    [SeminormedAddCommGroup F] [NormedSpace ℂ F]
    (Delta : E →L[ℂ] E) (Q : E →L[ℂ] F) (Qstar : F →L[ℂ] E)
    (a : ℂ) : E →L[ℂ] E :=
  Delta + a • Qstar.comp Q

/-- Literal analytic `V'(A)` from (3.60), using the forward and printed-star
differences generated by the common-target Eq. (3.59) pair. -/
def cmp99Eq360ComplexRegionalPrecisionPerturbation
    {d N Nc : ℕ} [NeZero N] [NeZero Nc]
    {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
    (T : CMP99Eq359ComplexRegionalTowerPair (Nc := Nc) Omega spacing)
    (Delta0 Delta1 :
      ActiveGaugeZeroCochain Omega (SUNLieComplexCoord Nc) →L[ℂ]
        ActiveGaugeZeroCochain Omega (SUNLieComplexCoord Nc))
    (a : ℂ) :
      ActiveGaugeZeroCochain Omega (SUNLieComplexCoord Nc) →L[ℂ]
        ActiveGaugeZeroCochain Omega (SUNLieComplexCoord Nc) :=
  (Delta0 - Delta1) - a • (T.F2star.comp T.Q0) -
    a • (T.starred0.comp T.F2) - a • (T.F2star.comp T.F2)

/-- Exact analytic Eq. (3.60) on the common regional carrier.  This theorem
is pure operator algebra: it assumes neither invertibility nor a norm bound,
and its starred operator is the independently constructed printed one. -/
theorem cmp99Eq360_complexRegionalPrecision_eq_sub_perturbation
    {d N Nc : ℕ} [NeZero N] [NeZero Nc]
    {Omega : ActiveGaugeRegion d N} {spacing : ℝ}
    (T : CMP99Eq359ComplexRegionalTowerPair (Nc := Nc) Omega spacing)
    (Delta0 Delta1 :
      ActiveGaugeZeroCochain Omega (SUNLieComplexCoord Nc) →L[ℂ]
        ActiveGaugeZeroCochain Omega (SUNLieComplexCoord Nc))
    (a : ℂ) :
    cmp99Eq360ComplexRegionalPrecision Delta1 T.Q1 T.starred1 a =
      cmp99Eq360ComplexRegionalPrecision Delta0 T.Q0 T.starred0 a -
        cmp99Eq360ComplexRegionalPrecisionPerturbation T Delta0 Delta1 a := by
  apply ContinuousLinearMap.ext
  intro phi
  simp only [cmp99Eq360ComplexRegionalPrecision,
    cmp99Eq360ComplexRegionalPrecisionPerturbation,
    T.Q1_eq_Q0_add_F2,
    T.starred1_eq_starred0_add_F2star,
    ContinuousLinearMap.add_apply, ContinuousLinearMap.sub_apply,
    ContinuousLinearMap.smul_apply, ContinuousLinearMap.comp_apply, map_add]
  module

end

end YangMills.RG
