import YangMills.RG.BalabanCMP99SourceSectionCSmoothHeterogeneousFactorWalk

open YangMills.RG

#print axioms norm_dependentBundledHilbertWalkOperator_map_le
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousLabelNormAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeterogeneousLabelOperator
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedCMP95SectionCHeterogeneousLabelOperator_le
#print axioms CMP99SourceDependentOmegaGeometry.norm_generatedCMP95SectionCHeterogeneousOperatorWalk_le
