import YangMills.RG.BalabanCMP99SourceSeparatedGeneratedFlatPhysicalSourceOwnerBound

#print axioms YangMills.RG.norm_cmp99SourceSeparatedGeneratedFlatPhysicalGreenQprimeStar_pointSource_apply_siteEquiv_le_sourceOwner
