import YangMills.RG.BalabanCMP99SourceGeneratedSectionCHeadedTypedWalk

#print axioms YangMills.RG.CMP99SectionCHeadedTypedLabel
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedLabelWeightedRowAmplitude
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedLabelOperator
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedLabelOperator_displayed
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedLabelOperator_head
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedLabelOperator_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedOperatorWalk_weightedRow
#print axioms YangMills.RG.CMP99SourceDependentOmegaGeometry.generatedCMP95SectionCHeadedOperatorWalk_exponential
