import YangMills.RG.BalabanCMP116ComplexR1DefectBudget

#print axioms YangMills.RG.cmp116R1TelescopeDefectBilateralBudget
#print axioms YangMills.RG.cmp116R1TelescopeBilateralSchurBudget_le_defectBudget
