import YangMills.RG.BalabanCMP99Eq337PhysicalRealPerturbationDomain

#print axioms YangMills.RG.cmp99Eq337PhysicalScaleSpacing
#print axioms YangMills.RG.cmp99Eq337PhysicalAmplitudeMajorant
#print axioms YangMills.RG.cmp99Eq337PhysicalCovariantDerivativeMajorant
#print axioms YangMills.RG.CMP99Eq337PhysicalRealPerturbationDomain
#print axioms YangMills.RG.CMP99Eq337PhysicalRealPerturbationDomain.abs_eta_mul_amplitudeMajorant_le
#print axioms YangMills.RG.CMP99Eq337PhysicalRealPerturbationDomain.amplitude_bound_at
#print axioms YangMills.RG.CMP99Eq337PhysicalRealPerturbationDomain.covariant_derivative_bound_at
