import YangMills.RG.BalabanCMP102PhysicalBackgroundCorrectionFixedPoint

#print axioms YangMills.RG.CMP102PhysicalBackgroundCorrectionBallData.mapsTo_correctionMap
#print axioms YangMills.RG.CMP102PhysicalBackgroundCorrectionBallData.contractionRate_nonneg
#print axioms YangMills.RG.CMP102PhysicalBackgroundCorrectionBallData.contractingWith_restrict
#print axioms YangMills.RG.CMP102PhysicalBackgroundCorrectionBallData.existsUnique_backgroundCorrection
#print axioms YangMills.RG.CMP102PhysicalBackgroundCorrectionBallData.exists_backgroundCorrection_physicalEquation
#print axioms YangMills.RG.CMP102PhysicalBackgroundCorrectionBallData.backgroundCorrection_physicalEquation_unique
