/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99PatchedParametrixSparseWalkBranching

/-!
# Physical summability of the sparse CMP99 patched walk

This module composes the physical ingredients already proved:

* the local-covariance head bound;
* the exponentially localized chart-continuation bound;
* exact removal of range-separated transitions;
* the source-simple-domain branching count;
* the active-carrier budget.

The terminal theorem concludes summability of the actual weakened physical
operator terms from the single scalar condition

`S * (S + 1) * Delta^(2*S) * rho * Rweak^B < 1`.

There is no independent whole-term estimate, abstract branching constant, or
ambient chart cardinal in the interface.  The remaining source obligations
are the concrete chart dictionary and active-carrier construction.
-/

namespace YangMills.RG

noncomputable section

universe u v

private abbrev PhysicalEndomorphism (d N Nc : ℕ) [NeZero N] :=
  PhysicalGaugeOneCochain d N Nc →L[ℝ]
    PhysicalGaugeOneCochain d N Nc

set_option synthInstance.maxHeartbeats 100000 in
/-- Physical factor bounds produce the geometric whole-walk estimate for
every tail generated by the exact near-range successor family. -/
theorem norm_cmp99PhysicalAnchoredPatchWalk_term_le
    {ι : Type*} [DecidableEq ι]
    {d N Nc : ℕ} [NeZero N]
    (charts : Finset ι)
    (K : PhysicalEndomorphism d N Nc)
    (enlarged core : ι → Finset (PhysicalBond d N))
    (hsub : ∀ i, i ∈ charts → core i ⊆ enlarged i)
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (hsymm : ∀ p q, dist p q = dist q p)
    (hself : ∀ p, dist p p = 0)
    (htri : ∀ x y z, dist x y ≤ dist x z + dist z y)
    {Rrange NR : ℕ} {M c mass κ σ Ssum Sdef : ℝ}
    (hM : 0 ≤ M) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ)
    (hSsum : 0 ≤ Ssum) (hSdef : 0 ≤ Sdef)
    (hsum : ∀ x,
      ∑ z : PhysicalBond d N,
        Real.exp (-(σ * (dist x z : ℝ))) ≤ Ssum)
    (hsumDef : ∀ x,
      ∑ z : PhysicalBond d N,
        Real.exp (-(((((κ - σ) - σ) - σ) * (dist x z : ℝ)))) ≤ Sdef)
    (hrange : PhysicalCovarianceFiniteRange K dist Rrange)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => M))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond d N,
      (Finset.univ.filter (fun y => dist x y ≤ Rrange)).card ≤ NR)
    (htilt :
      (M + |mass|) *
          (Real.exp (κ * (Rrange : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2)
    (left : ↥charts)
    (walk : CMP99AnchoredWalk
      (cmp99PhysicalPatchSuccessorSteps
        charts core enlarged dist Rrange) left) :
    ‖walk.term
        (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
        (fun _ => cmp99PhysicalPatchContinuation
          charts K enlarged core hc hmass hK)‖ ≤
      (min c mass)⁻¹ *
        (cmp99SingleDefectDecayAmplitude
          M κ Rrange c mass Ssum * Sdef) ^ walk.1 := by
  have hmin : 0 < min c mass := lt_min hc hmass
  have hAmp : 0 ≤ cmp99SingleDefectDecayAmplitude
      M κ Rrange c mass Ssum := by
    dsimp [cmp99SingleDefectDecayAmplitude]
    positivity
  simpa [CMP99AnchoredWalk.term,
    CMP99AnchoredWalk.toGeneralizedWalk_length] using
    (CMP99GeneralizedWalk.norm_term_le_of_factor_bounds
      (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
      (fun _ => cmp99PhysicalPatchContinuation
        charts K enlarged core hc hmass hK)
      (min c mass)⁻¹
      (cmp99SingleDefectDecayAmplitude M κ Rrange c mass Ssum * Sdef)
      (inv_nonneg.mpr hmin.le) (mul_nonneg hAmp hSdef)
      (norm_cmp99PhysicalPatchHead_le
        charts K enlarged core hc hmass hK)
      (fun _ i => norm_cmp99PhysicalPatchContinuation_le
        charts K enlarged core hsub dist hsymm hself htri hM hc hmass
        hσ h3σκ hSsum hSdef hsum hsumDef hrange hbound hK hNR htilt i)
      walk.toGeneralizedWalk)

section SimpleDomainSummability

variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]
variable {Cube : Type v} [DecidableEq Cube]

/-- Terminal physical summability theorem.  Branching and the whole-term
majorant are both generated internally from the chart geometry and physical
operator bounds. -/
theorem summable_cmp116WeakenedPhysicalPatchWalkSeries_of_simpleDomainDictionary
    {ι : Type*} [DecidableEq ι]
    {d N Nc : ℕ} [NeZero N]
    (charts : Finset ι)
    (K : PhysicalEndomorphism d N Nc)
    (enlarged core : ι → Finset (PhysicalBond d N))
    (hsub : ∀ i, i ∈ charts → core i ⊆ enlarged i)
    (dist : PhysicalBond d N → PhysicalBond d N → ℕ)
    (hsymm : ∀ p q, dist p q = dist q p)
    (hself : ∀ p, dist p p = 0)
    (htri : ∀ x y z, dist x y ≤ dist x z + dist z y)
    {Rrange NR : ℕ} {M c mass κ σ Ssum Sdef : ℝ}
    (hM : 0 ≤ M) (hc : 0 < c) (hmass : 0 < mass)
    (hσ : 0 ≤ σ) (h3σκ : 3 * σ < κ)
    (hSsum : 0 ≤ Ssum) (hSdef : 0 ≤ Sdef)
    (hsum : ∀ x,
      ∑ z : PhysicalBond d N,
        Real.exp (-(σ * (dist x z : ℝ))) ≤ Ssum)
    (hsumDef : ∀ x,
      ∑ z : PhysicalBond d N,
        Real.exp (-(((((κ - σ) - σ) - σ) * (dist x z : ℝ)))) ≤ Sdef)
    (hrange : PhysicalCovarianceFiniteRange K dist Rrange)
    (hbound : PhysicalCovarianceKernelBound K (fun _ _ => M))
    (hK : IsCoerciveCLM K c)
    (hNR : ∀ x : PhysicalBond d N,
      (Finset.univ.filter (fun y => dist x y ≤ Rrange)).card ≤ NR)
    (htilt :
      (M + |mass|) *
          (Real.exp (κ * (Rrange : ℝ)) - 1) *
            (NR : ℝ) ≤
        min c mass / 2)
    (S Δ B : ℕ) (hΔ : ∀ x, G.degree x ≤ Δ) (hΔ1 : 1 ≤ Δ)
    (domainOf : ↥charts → CMP99SimpleLocalizationDomain G S)
    (hinj : Function.Injective domainOf)
    (hnear : ∀ (left right : ↥charts),
      CMP99PhysicalPatchCanFollow core enlarged dist Rrange left right →
        (domainOf left).Meets (domainOf right))
    (domainActive : ↥charts → Finset Cube)
    (hB : ∀ X, (domainActive X).card ≤ B)
    (left : ↥charts) (s : Cube → ℝ) (Rweak : ℝ)
    (hRweak : 1 ≤ Rweak)
    (hsmall :
      ((S * (S + 1) * Δ ^ (2 * S) : ℕ) : ℝ) *
          (cmp99SingleDefectDecayAmplitude
            M κ Rrange c mass Ssum * Sdef) * Rweak ^ B < 1)
    (hs : s ∈ cmp116WeakeningPolydisc Rweak) :
    Summable fun walk : CMP99AnchoredWalk
        (cmp99PhysicalPatchSuccessorSteps
          charts core enlarged dist Rrange) left =>
      cmp116WeakeningMonomial (walk.active domainActive) s •
        walk.term
          (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
          (fun _ => cmp99PhysicalPatchContinuation
            charts K enlarged core hc hmass hK) := by
  have hmin : 0 < min c mass := lt_min hc hmass
  have hAmp : 0 ≤ cmp99SingleDefectDecayAmplitude
      M κ Rrange c mass Ssum := by
    dsimp [cmp99SingleDefectDecayAmplitude]
    positivity
  exact summable_cmp116WeakenedCMP99WalkSeries
    (cmp99PhysicalPatchSuccessorSteps
      charts core enlarged dist Rrange)
    left domainActive
    (cmp99PhysicalPatchHead charts K enlarged core hc hmass hK)
    (fun _ => cmp99PhysicalPatchContinuation
      charts K enlarged core hc hmass hK)
    s (S * (S + 1) * Δ ^ (2 * S)) B
    (min c mass)⁻¹
    (cmp99SingleDefectDecayAmplitude M κ Rrange c mass Ssum * Sdef)
    Rweak
    (fun current =>
      card_cmp99PhysicalPatchSuccessorSteps_le_simpleDomainBound
        G charts core enlarged dist Rrange S Δ hΔ hΔ1
        domainOf hinj hnear current)
    hB (inv_nonneg.mpr hmin.le) (mul_nonneg hAmp hSdef)
    hRweak hsmall
    (fun walk => norm_cmp99PhysicalAnchoredPatchWalk_term_le
      charts K enlarged core hsub dist hsymm hself htri hM hc hmass
      hσ h3σκ hSsum hSdef hsum hsumDef hrange hbound hK hNR htilt
      left walk)
    hs

end SimpleDomainSummability

end

end YangMills.RG
