import YangMills.RG.BalabanCMP99SourceGeneratedSectionCCommutatorFactorDecay

open YangMills.RG

#print axioms cmp99SourceGeneratedPhysicalCoarseCommutatorWeightedRowAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCoordinates_exponential
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalCoarseSectionCCommutatorFactorCoordinates_weightedRow
#print axioms cmp99SourceGeneratedCMP95SmoothCommutatorWeightedRowAmplitude
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_exponential
#print axioms CMP99SourceDependentOmegaGeometry.generatedCMP95SourceCenteredSectionCCommutatorFactorCoordinates_weightedRow
