import YangMills.RG.BalabanCMP116ComplexOuterLocalizedEnergy

#print axioms YangMills.RG.cmp116Eq214ComplexQuadratic_localizedOuterEnergyMatrix
#print axioms YangMills.RG.cmp116Eq214ComplexQuadratic_add_localizedOuterEnergyMatrix
#print axioms YangMills.RG.norm_trace_localizedOuterEnergyMatrix_mul_le
