import YangMills.RG.BalabanCMP99Eq360C6dSourceSeparatedAmbientGreen

#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientSiteEquiv
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientRegion
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientRegion_symm_eq
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedC6dAmbientPrecision
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientPrecision
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedRegionalDirichletPrecision_eq_ambient
#print axioms YangMills.RG.isCoerciveCLM_cmp99Eq360C6dSourceSeparatedAmbientPrecision
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedDirichletPrecision_eq_pullback
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedRegionalDirichletGreen_eq_ambient
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientPrecision_comp_green
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen_comp_precision
#print axioms YangMills.RG.norm_cmp99Eq360C6dSourceSeparatedAmbientGreen_le
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedPulledBackC6dGreen
#print axioms YangMills.RG.cmp99Eq360C6dSourceSeparatedAmbientGreen_eq_pullback
