import YangMills.RG.BalabanCMP89Eq248StabilizedGreenEndpointPeriodicity

#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointMomentumTerm_coordinateAliasPeriodShift
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointAliasTerm_eq_momentumTerm
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointIntegrand_physicalPeriodShift
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointAliasTerm_eq_stabilizedTerm
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointCentralTerm_eq_stabilized
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointIntegrand_eq_stabilized
#print axioms YangMills.RG.cmp89Eq248ComplexStabilizedGreenEndpointIntegrand_physicalPeriodShift_of_nonzero
