import YangMills.RG.BalabanCMP102Eq80CutoffCenteredResidual

#print axioms YangMills.RG.norm_sq_cmp116LocalizationDomainProjection_sourceCoordinate_le_localizedEnergy
#print axioms YangMills.RG.abs_half_inner_cmp116RadialTaylorResidualOperator_eq80DomainProjection_le_centeredEnergy_of_cutoff
#print axioms YangMills.RG.abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_centeredEnergy_of_cutoff
#print axioms YangMills.RG.abs_half_inner_cmp116RadialTaylorResidualOperator_eq80CouplingScaledDomainProjection_le_centeredEnergy_of_printedCutoff
