import YangMills.RG.BalabanCMP99SourceActiveRegionTerminalBlockDiameter

#print axioms YangMills.RG.CMP99SourceActiveRegionChain.div_pow_eq_of_sameTerminalBlock
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.sameTerminalBlock_finBoxDist_le
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.generatedCountingMass_finiteRange_terminalBlock
#print axioms YangMills.RG.CMP99SourceActiveRegionChain.QprimeMass_finiteRange_terminalBlock
