/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP99SourceRetainedPhysicalTransport

/-!
# Terminal coordinates of the retained CMP99 source tower

The source recursion prepends one fine coordinate level at every step.  Its
last retained coordinate type is therefore the site type of the original
coarse region, independently of the intermediate dependent transports.
-/

namespace YangMills.RG

open YangMills Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N] [NeZero Nc]

/-- The terminal physical coordinate type generated by the literal retained
tower is the site type of its base region. -/
theorem cmp99SourceGeneratedRetainedPhysicalTower_levelSite_last
    (hd : 2 ≤ d) (hM : 2 ≤ M) (rho : SUNAdjointModel Nc)
    (Omega : ActiveGaugeRegion d N) :
    ∀ (depth : ℕ) (spacing epsilon : ℝ)
      (background : GaugeConfig d
        (cmp99RegionalLatticeSize M N depth) (SUN Nc))
      (chain : CMP99SourceUbarRadiusChain d M Nc depth epsilon)
      (fineSmall : ∀ e : ConcreteEdge d
        (cmp99RegionalLatticeSize M N depth),
        ‖(background e : Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤ epsilon),
      (cmp99SourceGeneratedRetainedPhysicalTower hd hM rho Omega depth
        spacing epsilon background chain fineSmall).levelSite
          (Fin.last depth) = ActiveGaugeRegion.Site Omega := by
  intro depth
  induction depth with
  | zero =>
      intro spacing epsilon background chain fineSmall
      rfl
  | succ depth ih =>
      intro spacing epsilon background chain fineSmall
      let Scale : CMP99SourceNormalizedRegionalScale
          (cmp99IteratedLiftActiveRegion (M := M) Omega (depth + 1))
          background :=
        CMP99SourceNormalizedRegionalScale.ofFineSmall hd hM
          (cmp99IteratedLiftActiveRegion (M := M) Omega (depth + 1))
          background
          (cmp99IteratedLiftActiveRegion_blockSaturated Omega depth)
          epsilon chain.epsilon_nonneg chain.head_noWinding fineSmall
      have nextSmall : ∀ e : ConcreteEdge d
          (cmp99RegionalLatticeSize M N depth),
          ‖(Scale.toSourceScale.data.nextBackground e :
              Matrix (Fin Nc) (Fin Nc) ℂ) - 1‖ ≤
            cmp99SourceUbarNextFineRadius d M epsilon := by
        intro e
        simpa [Scale, CMP99SourceNormalizedRegionalScale.ofFineSmall,
          CMP99SourceRegionalScale.ofFineSmall] using
          norm_cmp99SourceRegionalScaleDataOfFineSmall_nextBackground_sub_one_le
            hd hM
            (cmp99IteratedLiftActiveRegion (M := M) Omega (depth + 1))
            background (cmp99SourceBlockAverageWeight M d) epsilon
            chain.epsilon_nonneg chain.head_noWinding chain.head_logSmall
            fineSmall e
      let Tail := cmp99SourceGeneratedRetainedPhysicalTower hd hM rho Omega
        depth ((M : ℝ) * spacing)
        (cmp99SourceUbarNextFineRadius d M epsilon)
        Scale.toSourceScale.data.nextBackground chain.tail nextSmall
      have hregion :
          cmp99ActiveCoarseRegion
              (M := M) (N' := cmp99RegionalLatticeSize M N depth)
              (cmp99IteratedLiftActiveRegion (M := M) Omega (depth + 1)) =
            cmp99IteratedLiftActiveRegion (M := M) Omega depth :=
        cmp99ActiveCoarseRegion_iteratedLift_succ_eq (M := M) Omega depth
      change ((hregion.symm ▸ Tail).levelSite (Fin.last depth)) =
        ActiveGaugeRegion.Site Omega
      rw [CMP99SourceRetainedPhysicalTower.levelSite_transport hregion Tail]
      exact ih ((M : ℝ) * spacing)
        (cmp99SourceUbarNextFineRadius d M epsilon)
        Scale.toSourceScale.data.nextBackground chain.tail nextSmall

end

end YangMills.RG
