import YangMills.RG.BalabanCMP99ComplexRectangularMinimizerDerivative

#print axioms YangMills.RG.cmp99ComplexCoarseMiddleCurve
#print axioms YangMills.RG.cmp99ComplexBackgroundMinimizerCurve
#print axioms YangMills.RG.differentiableAt_cmp99ComplexBackgroundMinimizerCurveEntry
#print axioms YangMills.RG.cmp99ComplexBackgroundMinimizerCurveDerivative
#print axioms YangMills.RG.hasDerivAt_cmp99ComplexBackgroundMinimizerCurveEntry
#print axioms YangMills.RG.cmp99SourcePi4FullComplexBackgroundMinimizerMatrixDerivative
#print axioms YangMills.RG.hasDerivAt_cmp99SourcePi4FullComplexBackgroundMinimizerMatrix_update
#print axioms YangMills.RG.hasDerivAt_cmp99SourcePi4FullComplexBackgroundMinimizerMatrix_update_of_source
