/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP116ComplexOuterTracePowers
import YangMills.RG.BalabanCMP116SourceR1CoordinatePivotTraceBound

/-!
# Global outer Gaussian bound for the physical source `R1`

The literal source-contour `R₁` is integrated over the complete outer
Gaussian space.  Its trace tests are generated internally from coordinate
pivots, so the endpoint contains neither a pointwise localization premise nor
an abstract covariance-trace estimate.
-/

namespace YangMills.RG

noncomputable section

open scoped Matrix.Norms.Operator

private abbrev PhysicalEndomorphism (M Q Nc : ℕ)
    [NeZero M] [NeZero Q] :=
  PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc →L[ℝ]
    PhysicalGaugeOneCochain 4 (M * (2 * Q)) Nc

set_option maxHeartbeats 6000000 in
/-- The exact global outer Gaussian generated by the physical source `R₁`
has a source-carrier-linear Mercator bound. -/
theorem integral_exp_re_cmp116SourcePi4FullComplexR1_le
    {q M Q Nc R Delta : ℕ}
    [NeZero M] [NeZero Q] [NeZero Nc] [NeZero (Nc ^ 2 - 1)]
    (anchor : FinBox 4 Q)
    (carrier : Finset (FinBox 4 (2 * Q)))
    (e : Fin q ≃ ↥carrier) (z : Fin q → ℂ)
    (K root : PhysicalEndomorphism M Q Nc)
    (hsourceRange : R + 1 ≤ 4 * M)
    (hfiniteRange : PhysicalCovarianceFiniteRange K physicalBondDist R)
    {c mass : ℝ} (hc : 0 < c) (hmass : 0 < mass)
    (hK : IsCoerciveCLM K c)
    (hD :
      ‖cmp99PatchedPhysicalParametrixDefect
          (cmp99SourcePi4Charts :
            Finset (CMP99SourcePi4Chart Unit Q))
          K cmp99SourcePi4ChartEnlarged
          (cmp99SourcePi4ChartCore (M := M))
          hc hmass hK‖ < 1)
    {Ahead rho rate : ℝ}
    (hAhead : 0 ≤ Ahead) (hrho : 0 ≤ rho)
    (Cert : CMP99PhysicalPatchWeightedCertificate
      (cmp99SourcePi4Charts :
        Finset (CMP99SourcePi4Chart Unit Q))
      K cmp99SourcePi4ChartEnlarged
      (cmp99SourcePi4ChartCore (M := M)) hc hmass hK
      physicalBondDist Ahead rho rate)
    (hrate : 0 < rate)
    (hgeom : ((2 ^ 4 : ℕ) : ℝ) * Real.exp (-rate) < 1)
    (htri : ∀ target source middle :
      PhysicalBond 4 (M * (2 * Q)),
      physicalBondDist target source ≤
        physicalBondDist target middle + physicalBondDist middle source)
    (hDelta : ∀ x, (cmp116CoarseFaceAdj 4 Q).degree x ≤ Delta)
    (hDelta1 : 1 ≤ Delta)
    (Z0 : Finset (FinBox 4 (2 * Q)))
    (radius Rweak : ℝ)
    (hradius : 0 ≤ radius) (hRweak : 1 ≤ Rweak)
    (hz : ∀ i, ‖z i‖ ≤ radius)
    (hcap : ∀ i, ‖1 + z i‖ ≤ Rweak)
    (hcontourSmall :
      ‖cmp116SourcePi4ComplexContourRatio Delta rho Rweak‖ < 1)
    (hneumann :
      ‖cmp116PhysicalEndomorphismComplexMatrix K‖ *
        cmp116SourcePi4PhysicalComplexContourDefectBound
          Nc Delta Ahead rho rate radius Rweak < 1)
    (hpos :
      (1 - cmp116Eq214ComplexQuadraticSymmetricRealPart
        (cmp116SourcePi4FullComplexR1Matrix
          (R := R) anchor K root hc hmass hK Z0
            (cmp116SourceRestrictedShiftedCoupling carrier e z))).PosDef)
    (hsmall :
      ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart
        (cmp116SourcePi4FullComplexR1Matrix
          (R := R) anchor K root hc hmass hK Z0
            (cmp116SourceRestrictedShiftedCoupling carrier e z))).map
              Complex.ofRealHom‖ < 1) :
    let A :=
      cmp116SourcePi4FullComplexR1Matrix
        (R := R) anchor K root hc hmass hK Z0
          (cmp116SourceRestrictedShiftedCoupling carrier e z)
    let geometricRow :=
      (((Nc ^ 2 - 1 : ℕ) : ℝ) *
        cmp99PhysicalBondGeometricRowSum 4 rate)
    let walkRatio :=
      cmp116SourcePi4ComplexContourRatio Delta rho Rweak
    let traceUnit :=
      (q : ℝ) * 625 *
        (((40000 * M ^ 4) * (Nc ^ 2 - 1) : ℕ) : ℝ) *
        (radius * Rweak ^ 10000) * geometricRow *
        (Ahead * geometricRow)
    let traceCost := traceUnit * (1 - walkRatio)⁻¹ ^ 2
    let C0 := cmp116SourcePi4PhysicalBaseCovarianceMatrix K hc hmass hK
    let C1 :=
      cmp116SourcePi4FullComplexWeakenedCovarianceMatrix
        (R := R) anchor K hc hmass hK
          (cmp116SourceRestrictedShiftedCoupling carrier e z)
    let P0 := cmp116PhysicalEndomorphismComplexMatrix K
    let P1 :=
      cmp116SourcePi4FullComplexWeakenedPrecisionMatrix
        (R := R) anchor K hc hmass hK
          (cmp116SourceRestrictedShiftedCoupling carrier e z)
    let G0 := cmp116SourcePi4PhysicalBaseGammaMatrix K root Z0
    let G1 :=
      cmp116SourcePi4FullComplexGammaMatrix
        (R := R) anchor K root hc hmass hK Z0
          (cmp116SourceRestrictedShiftedCoupling carrier e z)
    let constraint := cmp116SourcePi4ConstraintMatrix M Q Nc
    let complement :=
      cmp116SourcePi4ComplementProjectionMatrix
        (M := M) (Nc := Nc) Z0
    let rootMatrix := cmp116SourcePi4ReferenceRootMatrix root
    let U := -(constraint.transpose * P1)
    let V := P0 * (constraint * complement) * rootMatrix
    let L :=
      traceCost * Matrix.r1TraceMultiplierBudget G0 G1 C0 C1 U V
    (∫ x : CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc → ℝ,
        Real.exp ((cmp116Eq214ComplexQuadratic A x).re)
        ∂standardGaussianPi
          (CMP116PhysicalWalkCoordinate 4 (M * (2 * Q)) Nc)) ≤
      Real.exp
        ((L /
          (1 -
            ‖(-cmp116Eq214ComplexQuadraticSymmetricRealPart A).map
              Complex.ofRealHom‖)) / 2) := by
  dsimp only
  let sigma := cmp116SourceRestrictedShiftedCoupling carrier e z
  let A :=
    cmp116SourcePi4FullComplexR1Matrix
      (R := R) anchor K root hc hmass hK Z0 sigma
  let geometricRow : ℝ :=
    (((Nc ^ 2 - 1 : ℕ) : ℝ) *
      cmp99PhysicalBondGeometricRowSum 4 rate)
  let walkRatio : ℝ :=
    cmp116SourcePi4ComplexContourRatio Delta rho Rweak
  let traceUnit : ℝ :=
    (q : ℝ) * 625 *
      (((40000 * M ^ 4) * (Nc ^ 2 - 1) : ℕ) : ℝ) *
      (radius * Rweak ^ 10000) * geometricRow *
      (Ahead * geometricRow)
  let traceCost : ℝ := traceUnit * (1 - walkRatio)⁻¹ ^ 2
  let C0 := cmp116SourcePi4PhysicalBaseCovarianceMatrix K hc hmass hK
  let C1 :=
    cmp116SourcePi4FullComplexWeakenedCovarianceMatrix
      (R := R) anchor K hc hmass hK sigma
  let P0 := cmp116PhysicalEndomorphismComplexMatrix K
  let P1 :=
    cmp116SourcePi4FullComplexWeakenedPrecisionMatrix
      (R := R) anchor K hc hmass hK sigma
  let G0 := cmp116SourcePi4PhysicalBaseGammaMatrix K root Z0
  let G1 :=
    cmp116SourcePi4FullComplexGammaMatrix
      (R := R) anchor K root hc hmass hK Z0 sigma
  let constraint := cmp116SourcePi4ConstraintMatrix M Q Nc
  let complement :=
    cmp116SourcePi4ComplementProjectionMatrix
      (M := M) (Nc := Nc) Z0
  let rootMatrix := cmp116SourcePi4ReferenceRootMatrix root
  let U := -(constraint.transpose * P1)
  let V := P0 * (constraint * complement) * rootMatrix
  let L : ℝ :=
    traceCost * Matrix.r1TraceMultiplierBudget G0 G1 C0 C1 U V
  have hrow0 : 0 ≤ geometricRow := by
    dsimp [geometricRow]
    exact mul_nonneg (by positivity)
      (cmp99PhysicalBondGeometricRowSum_nonneg hgeom)
  have hunit0 : 0 ≤ traceUnit := by
    dsimp [traceUnit]
    positivity
  have hcost0 : 0 ≤ traceCost := by
    dsimp [traceCost]
    positivity
  have hbudget0 :
      0 ≤ Matrix.r1TraceMultiplierBudget G0 G1 C0 C1 U V := by
    dsimp [Matrix.r1TraceMultiplierBudget]
    positivity
  have hL : 0 ≤ L := by
    exact mul_nonneg hcost0 hbudget0
  apply
    integral_exp_re_complexQuadratic_standardGaussianPi_le_of_multiplier
      A (by simpa [A, sigma] using hpos)
      (by simpa [A, sigma] using hsmall) hL
  intro P hPt
  have htrace :=
    norm_trace_cmp116SourcePi4FullComplexR1Matrix_mul_le
      (R := R) (Delta := Delta)
      anchor carrier e z K root hsourceRange hfiniteRange hc hmass hK hD
      hAhead hrho Cert hrate hgeom htri hDelta hDelta1 Z0
      radius Rweak hradius hRweak hz hcap hcontourSmall hneumann P hPt
  simpa [A, sigma, L, traceCost, traceUnit, walkRatio, geometricRow,
    C0, C1, P0, P1, G0, G1, constraint, complement, rootMatrix, U, V,
    mul_assoc] using htrace

end

end YangMills.RG
