import YangMills.RG.BalabanCMP102Eq80PhysicalCorrectionRadial

#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalRadialOperator
#print axioms YangMills.RG.cmp102Eq80CorrectedPhysicalGlobalPotential_eq_radial_constRadii
