import YangMills.RG.BalabanCMP99Eq360C6dSourceFixedInput


namespace YangMills.RG

#print axioms cmp99Eq360C6dSourceBaselineRetainedPhysicalTower
#print axioms cmp99Eq360C6dSource_internalBonds_nearIdentity
#print axioms norm_cmp99Eq360C6dSourceLaplacianRetainedExtension_sub_one_le
#print axioms cmp99Eq360C6dSourceLaplacianRetainedPhysicalTower_terminalSpace_eq
#print axioms cmp99Eq360C6dSourceLaplacianRetainedPhysicalTower_terminalSpacing
#print axioms cmp99Eq360C6dSourcePhysicalCountingCoefficient_eq_laplacianRetained
#print axioms cmp99Eq360C6dSourceBaselineRetainedPhysicalTower_Qprime_heq_laplacianExtension
#print axioms cmp99Eq360C6dSourceBaselinePrecision_eq_laplacianRetainedPrecision
#print axioms cmp99Eq360C6dLocalizedRetainedSourceInput_a_j
#print axioms cmp99Eq360C6dSourcePhysicalCountingCoefficient_pos
#print axioms cmp99Eq360C6dSourcePhysicalCountingCoefficient_toWeighted

end YangMills.RG
