import YangMills.RG.BalabanCMP99SourceSeparatedSourceFlowFlatPhysicalGreenIdentification

open YangMills.RG

#print axioms cmp99SourceSeparatedSourceFlowFlatPhysicalStep7bGreenCLM_comp_precision
#print axioms cmp99SourceSeparatedSourceFlowFlatPhysicalStabilizedAliasDenominator_ne_zero
#print axioms cmp99SourceSeparatedSourceFlowFlatPhysicalStabilizedFieldCLM_eq_green_comp
