import YangMills.RG.BalabanCMP99SourceGeneratedRegionTransition

open YangMills.RG

#print axioms CMP99SourceDependentOmegaGeometry.operatorRegion_transition_subset
#print axioms CMP99SourceDependentOmegaGeometry.generatedTransitionRestriction
#print axioms CMP99SourceDependentOmegaGeometry.generatedTransitionExtension
#print axioms CMP99SourceDependentOmegaGeometry.generatedTransitionRestriction_comp_extension
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalGreenTransition
#print axioms CMP99SourceDependentOmegaGeometry.generatedPhysicalGreen_transition_resolvent
