/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.BalabanCMP98UbarLogAverageFDeriv
import YangMills.RG.MatrixDetExpSkewAdjoint
import YangMills.RG.SUNAdjointModelInstance

/-!
# The physical CMP98 chart remains in `SU(N)`

The ambient matrix chart used to differentiate CMP98 (118)--(125) deliberately
forgets the determinant-one certificate.  The nonlinear correction in CMP102,
however, is Lie-algebra valued.  This file restores the missing source
dictionary on genuine physical directions.

For every real physical one-cochain, its matrix exponential is packaged in
`SU(N)` from the literal skew-adjoint and trace-zero certificates.  The
resulting `SU(N)` gauge configuration has exactly the same underlying matrices
as the ambient/unitary curve already used by the calculus development.
Consequently every four-contour deviation entering the logarithmic block
average is literally `D - 1` for a concrete `D : SU(N)`.

This is a codomain theorem, not a projection of arbitrary matrices onto
`su(N)`.  No fixed-point map, contraction estimate, or CMP102 correction is
introduced here.
-/

namespace YangMills.RG

open YangMills YangMills.GaugeConfig Matrix
open scoped Matrix.Norms.L2Operator

noncomputable section

variable {d M N' Nc : ℕ}
variable [NeZero d] [NeZero M] [NeZero N'] [NeZero Nc]

/-- The literal special-unitary exponential increment generated by a physical
`su(N)` one-cochain. -/
noncomputable def cmp98PhysicalSuIncrement
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d (M * N')) (t : ℝ) : SUN Nc := by
  let X : SuLie Nc := (suLieCoordIso Nc).symm (A b)
  let Z : Matrix (Fin Nc) (Fin Nc) ℂ := t • X.toMatrix
  have hX := (mem_suMatrixSubmodule_iff X.toMatrix).mp X.property
  have hskew : Z ∈ skewAdjoint (Matrix (Fin Nc) (Fin Nc) ℂ) := by
    rw [skewAdjoint.mem_iff, Matrix.star_eq_conjTranspose]
    dsimp only [Z]
    rw [Matrix.conjTranspose_smul, star_trivial, hX.1]
    module
  have htrace : Matrix.trace Z = 0 := by
    dsimp only [Z]
    change Matrix.trace ((t : ℂ) • X.toMatrix) = 0
    rw [Matrix.trace_smul, hX.2, smul_zero]
  exact
    ⟨physicalMatrixExp Z,
      Matrix.exp_mem_specialUnitaryGroup_of_mem_skewAdjoint_of_trace_eq_zero
        Z hskew htrace⟩

@[simp] theorem cmp98PhysicalSuIncrement_coe
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d (M * N')) (t : ℝ) :
    (cmp98PhysicalSuIncrement A b t :
        Matrix (Fin Nc) (Fin Nc) ℂ) =
      physicalMatrixExp
        (t • ((suLieCoordIso Nc).symm (A b)).toMatrix) := by
  rfl

@[simp] theorem cmp98PhysicalSuIncrement_zero
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d (M * N')) :
    cmp98PhysicalSuIncrement A b 0 = 1 := by
  apply Subtype.ext
  simp

/-- The literal physical left variation, now valued in `SU(N)` rather than
only in its ambient unitary group. -/
noncomputable def cmp98PhysicalSuLeftVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (t : ℝ) : PhysicalGaugeBackground d (M * N') Nc :=
  physicalLeftVariation U (fun b t _ =>
    cmp98PhysicalSuIncrement A b t) t 0

@[simp] theorem cmp98PhysicalSuLeftVariation_zero
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc) :
    cmp98PhysicalSuLeftVariation U A 0 = U := by
  exact physicalLeftVariation_zero_zero U
    (fun b t _ => cmp98PhysicalSuIncrement A b t)
    (cmp98PhysicalSuIncrement_zero A)

/-- Forgetting the determinant certificate gives exactly the previously used
unitary physical curve. -/
theorem physicalBackgroundToUnitary_cmp98PhysicalSuLeftVariation
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (t : ℝ) :
    physicalBackgroundToUnitary (cmp98PhysicalSuLeftVariation U A t) =
      physicalSuUnitaryLeftVariation U
        (physicalCochainToSuMatrixTangent A) 0 t 0 := by
  apply gaugeConfig_ext
  intro e
  cases e with
  | mk x i sign =>
      cases sign
      · apply Subtype.ext
        have hzero : ((0 : SuLie Nc).toMatrix) = 0 := rfl
        have harg :
            t • ((suLieCoordIso Nc).symm (A (x, i))).toMatrix +
                (0 : ℝ) • (0 : Matrix (Fin Nc) (Fin Nc) ℂ) =
              t • ((suLieCoordIso Nc).symm (A (x, i))).toMatrix := by
          module
        simp [physicalBackgroundToUnitary, cmp98PhysicalSuLeftVariation,
          physicalSuUnitaryLeftVariation, physicalLeftVariation,
          gaugeConfigOfPositiveBonds, physicalCochainToSuMatrixTangent,
          physicalSuUnitaryIncrement, cmp98PhysicalSuIncrement,
          physicalBondOfEdge, hzero, harg]
      · apply Subtype.ext
        have hzero : ((0 : SuLie Nc).toMatrix) = 0 := rfl
        have harg :
            t • ((suLieCoordIso Nc).symm (A (x, i))).toMatrix +
                (0 : ℝ) • (0 : Matrix (Fin Nc) (Fin Nc) ℂ) =
              t • ((suLieCoordIso Nc).symm (A (x, i))).toMatrix := by
          module
        simp [physicalBackgroundToUnitary, cmp98PhysicalSuLeftVariation,
          physicalSuUnitaryLeftVariation, physicalLeftVariation,
          gaugeConfigOfPositiveBonds, physicalCochainToSuMatrixTangent,
          physicalSuUnitaryIncrement, cmp98PhysicalSuIncrement,
          physicalBondOfEdge, hzero, harg]

/-- Forgetting the determinant-one certificate commutes with Wilson-line
composition. -/
theorem specialUnitaryToUnitary_wilsonLine
    {N : ℕ} [NeZero N]
    (V : GaugeConfig d N (SUN Nc))
    (es : List (ConcreteEdge d N)) :
    specialUnitaryToUnitary (wilsonLine V es) =
      wilsonLine (physicalBackgroundToUnitary V) es := by
  induction es with
  | nil => rfl
  | cons e es ih =>
      rw [wilsonLine_cons, wilsonLine_cons, specialUnitaryToUnitary_mul, ih]
      rfl

/-- Every ambient CMP98 contour on a physical line is the matrix underlying
the corresponding literal `SU(N)` Wilson line. -/
theorem cmp98AmbientWilsonLineMatrix_line_eq_specialUnitaryWilsonLine
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (es : List (ConcreteEdge d (M * N'))) (t : ℝ) :
    cmp98AmbientWilsonLineMatrix U
        (t • physicalSuTangentToAmbient
          (physicalCochainToSuMatrixTangent A)) es =
      (wilsonLine (cmp98PhysicalSuLeftVariation U A t) es :
        SUN Nc).val := by
  let X : PhysicalSuMatrixTangent d (M * N') Nc :=
    physicalCochainToSuMatrixTangent A
  have htangent :
      physicalTwoParameterAmbientTangent X 0 t 0 =
        t • physicalSuTangentToAmbient X := by
    funext b
    unfold physicalTwoParameterAmbientTangent physicalSuTangentToAmbient
    change t • (X b).toMatrix +
      (0 : ℝ) • (0 : Matrix (Fin Nc) (Fin Nc) ℂ) =
        t • (X b).toMatrix
    module
  rw [← htangent,
    cmp98AmbientWilsonLineMatrix_twoParameter_eq_unitaryWilsonLine]
  have hcfg :=
    physicalBackgroundToUnitary_cmp98PhysicalSuLeftVariation U A t
  rw [← hcfg]
  exact congrArg Subtype.val
    (specialUnitaryToUnitary_wilsonLine
      (cmp98PhysicalSuLeftVariation U A t) es).symm

/-- In the defining matrix representation of `SU(N)`, group inversion is
conjugate transpose. -/
theorem coe_sun_inv_eq_conjTranspose (g : SUN Nc) :
    ((g⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) =
      Matrix.conjTranspose (g : Matrix (Fin Nc) (Fin Nc) ℂ) := by
  have hunit := su_mul_conjTranspose_self g
  have hleft :
      ((g⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) *
        (g : Matrix (Fin Nc) (Fin Nc) ℂ) = 1 := by
    change (((g⁻¹ * g : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ)) = 1
    simp
  calc
    ((g⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) =
        ((g⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) * 1 := by
          rw [mul_one]
    _ = ((g⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) *
        ((g : Matrix (Fin Nc) (Fin Nc) ℂ) *
          Matrix.conjTranspose (g : Matrix (Fin Nc) (Fin Nc) ℂ)) := by
            rw [hunit]
    _ = ((((g⁻¹ : SUN Nc) : Matrix (Fin Nc) (Fin Nc) ℂ) *
        (g : Matrix (Fin Nc) (Fin Nc) ℂ)) *
          Matrix.conjTranspose (g : Matrix (Fin Nc) (Fin Nc) ℂ)) := by
            rw [mul_assoc]
    _ = Matrix.conjTranspose (g : Matrix (Fin Nc) (Fin Nc) ℂ) := by
          rw [hleft, one_mul]

/-- The literal special-unitary four-contour element whose deviation from
one enters the local logarithm in CMP98 (121). -/
noncomputable def cmp98PhysicalUbarRelativeSUN
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    SUN Nc :=
  ((wilsonLine (cmp98PhysicalSuLeftVariation U A t)
        (cmp99SourceUbarGamma1 (G := SUN Nc) b x) *
      wilsonLine (cmp98PhysicalSuLeftVariation U A t)
        (cmp99SourceUbarGamma2 (G := SUN Nc) b x)) *
    wilsonLine (cmp98PhysicalSuLeftVariation U A t)
      (cmp99SourceUbarGamma3 (G := SUN Nc) b x)) *
    (wilsonLine (cmp98PhysicalSuLeftVariation U A t)
      (cmp98SourceCoarseBondPath (Nc := Nc) b))⁻¹

/-- Source-faithful codomain bridge: the ambient local deviation is exactly
`D - 1` for the preceding concrete special-unitary four-contour element. -/
theorem cmp98UbarAmbientDeviationMatrix_line_eq_relativeSUN_sub_one
    (U : PhysicalGaugeBackground d (M * N') Nc)
    (A : PhysicalGaugeOneCochain d (M * N') Nc)
    (b : PhysicalBond d N') (x : FinBox d (M * N')) (t : ℝ) :
    cmp98UbarAmbientDeviationMatrix U b x
        (t • physicalSuTangentToAmbient
          (physicalCochainToSuMatrixTangent A)) =
      (cmp98PhysicalUbarRelativeSUN U A b x t :
        Matrix (Fin Nc) (Fin Nc) ℂ) - 1 := by
  unfold cmp98UbarAmbientDeviationMatrix cmp98PhysicalUbarRelativeSUN
  rw [cmp98AmbientWilsonLineMatrix_line_eq_specialUnitaryWilsonLine,
    cmp98AmbientWilsonLineMatrix_line_eq_specialUnitaryWilsonLine,
    cmp98AmbientWilsonLineMatrix_line_eq_specialUnitaryWilsonLine,
    cmp98AmbientWilsonLineMatrix_line_eq_specialUnitaryWilsonLine]
  rw [← coe_sun_inv_eq_conjTranspose]
  rfl

end

end YangMills.RG
