-- Promotion import:
import YangMills.RG.BalabanCMP89Eq248GreenMassUniformHolomorphy

/-!
PRE-VALIDATION: this module's source is present, its `.olean` has not yet
been materialized, and its result has not yet been verified by the compiler.
-/

-- PRE-VALIDATION SCRATCH: intended axiom surface for Step 8b.23/Unit B.5.

#print axioms YangMills.RG.differentiableAt_cmp89Eq248ComplexStabilizedGreenEndpointIntegrand_of_commonRadius_massUniform_draft
#print axioms YangMills.RG.continuousAt_cmp89Eq248ComplexStabilizedGreenEndpointIntegrand_real_massUniform_draft
#print axioms YangMills.RG.cmp89Eq251DisplayedDomain_of_boundaryFace_massUniform_draft
#print axioms YangMills.RG.cmp89Eq248ComplexFineLatticeBareGreenMomentumFactor_draft
#print axioms YangMills.RG.cmp89Eq248ComplexFineLatticeBareGreenMomentumFactor_coordinateAliasPeriodShift_draft
#print axioms YangMills.RG.cmp89Eq248ComplexFineLatticeDisplayedGreenMomentumTerm_draft
#print axioms YangMills.RG.cmp89Eq248ComplexFineLatticeDisplayedGreenMomentumTerm_coordinateAliasPeriodShift_draft
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointAliasTerm_eq_fineLatticeMomentumTerm_draft
#print axioms YangMills.RG.cmp89Eq248ComplexDisplayedGreenEndpointIntegrand_physicalFinePeriodShift_draft
#print axioms YangMills.RG.cmp89Eq248ComplexStabilizedGreenEndpointIntegrand_physicalFinePeriodShift_of_nonzero_draft
#print axioms YangMills.RG.cmp89Eq248ComplexStabilizedGreenEndpointIntegrand_physicalFine_boundarySeam_massUniform_draft
