/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/
import YangMills.RG.CorrelatorBridge

/-!
# The RG-provenant correlator bridge (C6 phase B-1'): `Rsc` PRODUCED, not selected

`docs/C6-BRIDGE-CHARTER.md`, AMENDMENT 1 (2026-07-13).  The external audit of
phase B-1 produced a gameability counterexample: `RegimeCoherentWilsonBridge`
asks only for a scalar decomposition, a bound, and SOME nonzero `Rsc`, so it is
satisfiable by re-labeling the already-proved strong-coupling decay
(`R_{t,0} := a·e^{−t}`, rest `0`, `covIR := covPhys − a·e^{−t}`, `nsc := 1`)
with ZERO renormalization-group content.  This module implements the amended
specification: the ultraviolet remainders must be PRODUCED by an effective
family generated from the Wilson data by ONE map, never selected per scale.

* **`RGFlowFamily μ₀`** — a family of measures `mu : ℕ → Measure (GaugeConfig
  d N G)` TOGETHER WITH its generating map: `mu 0 = μ₀` and
  `mu (k+1) = step (mu k)`.  `RGFlowFamily.mu_eq_iterate` proves the family
  has NO per-scale freedom: `mu k = step^[k] μ₀`, so the whole family is the
  pair `(μ₀, step)`.  `RGFlowFamily.ofStep` builds the family of any map.
* **`truncatedPlaquetteCorrelatorOfMeasure` / `rayCorrelatorOfMeasure`** — the
  truncated two-plaquette correlator and its distance-indexed (ray) form OF AN
  ARBITRARY measure on gauge configurations: the generalization of the B-1
  Wilson anchor shape to a measure parameter (the existing Wilson definitions
  are untouched; the anchor identities below tie the two).
* **`covEff F f k t`** — the effective correlator at scale `k`: the ray
  correlator OF `F.mu k`, BY DEFINITION.  It cannot be chosen freely.
* **`provenantRsc F f t k := covEff F f k t − covEff F f (k+1) t`** and
  **`provenantCovIR F f nsc t := covEff F f (nsc t) t`** — the produced UV
  remainders and terminal IR part.  **`provenant_decomposition`** proves the
  bridge decomposition `covEff F f 0 t = provenantCovIR + covUV_concrete
  (provenantRsc)` BY TELESCOPING — a THEOREM, not a structure field.
  **`provenantBridge`** packages it as a `CorrelatorBridge (covEff F f 0)`
  whose fields are DEFINED from the family.
* **`integral_gibbsMeasure_eq_div`** and the anchor identities
  (`truncatedPlaquetteCorrelatorOfMeasure_wilsonGibbs`,
  `rayCorrelatorOfMeasure_wilsonGibbs`, `covEff_zero_eq_wilsonRayCorrelator`):
  the measure-level correlator of the ACTUAL Wilson Gibbs measure
  (`gibbsMeasure (sunHaarProb N_c) (fundamentalObservable N_c) β`, an honest
  `Measure.tilted`) EQUALS the B-1 `Z`-quotient Wilson correlator — no
  hypotheses at all (tilted-measure integral calculus).  So a family anchored
  at `wilsonGibbsMeasure` has `covEff F f 0 = wilsonRayCorrelator` exactly.
* **`RGProvenantWilsonBridge`** — THE HONEST GATE: there exists a flow family
  STARTING AT THE WILSON GIBBS MEASURE whose terminal `provenantCovIR`
  satisfies the exponential IR bound and whose `provenantRsc` satisfies
  `SingleScaleUVDecay` with a marginal flow.  NO free `Rsc` anywhere: the
  remainders are differences of correlators of measures generated by one map
  from the Wilson start.  Consumer:
  `wilson_mass_gap_of_rgProvenantBridge` (through
  `physical_mass_gap_of_bridge` via `provenantBridge`).
* **`constantFlow`** — NON-VACUITY WITHOUT GAMING: the degenerate flow
  (`step = id`) gives `provenantRsc = 0` identically and recovers the B-1
  trivial bridge field-by-field
  (`provenantBridge_constantFlow_covIR/_Rsc`); at strong coupling it
  discharges the gate (`rgProvenantWilsonBridge_strong_coupling`).
  Conversely `step_moves_of_provenantRsc_ne_zero`: ANY nonzero produced
  remainder forces the step map to genuinely move the measure — nonzero UV
  content now has provenance in an actual transformation.

**Honest scope.**  (i) No fallback was needed: the family is measure-level
(actual `Measure (GaugeConfig d N G)`), not observable-level.  (ii) `step` is
an arbitrary map of measures, NOT yet a concrete block/decimation kernel; the
Amendment-1 endgame (a DEFINED blocking transformation) is the B-2
continuation.  Consequently a residual gaming channel remains: satisfying the
gate with nonzero UV content while avoiding real RG work would require
EXHIBITING measures on the finite-torus gauge configurations whose ray
correlators realize prescribed functions — strictly harder than the scalar
re-labeling that killed the old gate, but not excluded by this module.
(iii) The gate itself is PROVED satisfiable by the zero-UV degenerate flow at
strong coupling; the open question this module isolates is therefore: satisfy
the gate with a flow whose produced `provenantRsc` is NONVANISHING — the two
bounds for THAT `Rsc` and THAT `covIR` (fluctuation integration, G5-adjacent).
(iv) The ray correlator remains a fixed-finite-torus object; "mass-gap-shaped"
is the only permitted phrasing.  No new analytic estimate is proved here.
Clay distance ~0% (<0.1%), unchanged.

Oracle target: `[propext, Classical.choice, Quot.sound]`. No sorry, no axioms.
-/

open scoped BigOperators

namespace YangMills.RG

open YangMills MeasureTheory GaugeConfig

section EffectiveFamily

variable {d N : ℕ} [NeZero d] [NeZero N] {G : Type*} [Group G] [MeasurableSpace G]

/-- **The effective family (Amendment 1, item 1).**  A scale-indexed family of
measures on gauge configurations TOGETHER WITH its generating map: `mu 0` is
the given starting measure and every successor is produced by the SAME map
`step`.  The family therefore carries no per-scale freedom
(`RGFlowFamily.mu_eq_iterate`): choosing a family means choosing the single
pair `(μ₀, step)`. -/
structure RGFlowFamily (μ₀ : Measure (GaugeConfig d N G)) where
  /-- the generating map: one transformation of measures, applied at every
  scale -/
  step : Measure (GaugeConfig d N G) → Measure (GaugeConfig d N G)
  /-- the scale-indexed family of effective measures -/
  mu : ℕ → Measure (GaugeConfig d N G)
  /-- the family starts at the given measure -/
  mu_zero : mu 0 = μ₀
  /-- every scale is produced from the previous one by the generating map -/
  mu_succ : ∀ k, mu (k + 1) = step (mu k)

/-- Every map of measures generates a flow family from any start, by
iteration. -/
def RGFlowFamily.ofStep (μ₀ : Measure (GaugeConfig d N G))
    (T : Measure (GaugeConfig d N G) → Measure (GaugeConfig d N G)) :
    RGFlowFamily μ₀ where
  step := T
  mu := fun k => T^[k] μ₀
  mu_zero := rfl
  mu_succ := fun k => Function.iterate_succ_apply' T k μ₀

/-- **No per-scale freedom.**  The family field `mu` is DETERMINED by the
generating data: `mu k = step^[k] μ₀`.  This is the structural fact that kills
the Amendment-1 counterexample's freedom to select each scale independently. -/
theorem RGFlowFamily.mu_eq_iterate {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (k : ℕ) : F.mu k = F.step^[k] μ₀ := by
  induction k with
  | zero => simpa using F.mu_zero
  | succ k ih => rw [F.mu_succ k, ih, Function.iterate_succ_apply']

/-- **The truncated two-plaquette correlator of an ARBITRARY measure** on
gauge configurations — the generalization of the B-1 Wilson anchor shape to a
measure parameter.  For the honest (probability) Gibbs measure this is the
usual connected correlator `⟨f_p f_q⟩ − ⟨f_p⟩⟨f_q⟩`. -/
noncomputable def truncatedPlaquetteCorrelatorOfMeasure
    (ν : Measure (GaugeConfig d N G)) (f : G → ℝ)
    (p q : ConcretePlaquette d N) : ℝ :=
  (∫ A, f (plaquetteHolonomy A p) * f (plaquetteHolonomy A q) ∂ν)
    - (∫ A, f (plaquetteHolonomy A p) ∂ν) * (∫ A, f (plaquetteHolonomy A q) ∂ν)

/-- **The distance-indexed (ray) correlator of an ARBITRARY measure** — the
measure-parametric form of `wilsonRayCorrelator`, with the same honest default
`0` when the finite torus realizes no pair at touch-distance `≥ 2t`. -/
noncomputable def rayCorrelatorOfMeasure
    (ν : Measure (GaugeConfig d N G)) (f : G → ℝ) (t : ℕ) : ℝ :=
  if h : ∃ pq : ConcretePlaquette d N × ConcretePlaquette d N,
      pq.1 ≠ pq.2 ∧ 2 * t ≤ (touchGraph d N).dist pq.1 pq.2 then
    truncatedPlaquetteCorrelatorOfMeasure ν f h.choose.1 h.choose.2
  else 0

/-- **The effective correlator at scale `k`** — the ray correlator OF the
scale-`k` effective measure, BY DEFINITION.  There is no freedom to choose it:
it is a function of `(μ₀, step)` alone. -/
noncomputable def covEff {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (k t : ℕ) : ℝ :=
  rayCorrelatorOfMeasure (F.mu k) f t

/-- **The PRODUCED ultraviolet remainders (Amendment 1, item 2):** the
difference of consecutive effective correlators.  Not a free field: a function
of the family. -/
noncomputable def provenantRsc {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (t k : ℕ) : ℝ :=
  covEff F f k t - covEff F f (k + 1) t

/-- **The PRODUCED infrared part:** the effective correlator at the terminal
scale `nsc t`. -/
noncomputable def provenantCovIR {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (nsc : ℕ → ℕ) (t : ℕ) : ℝ :=
  covEff F f (nsc t) t

/-- **THE TELESCOPING THEOREM (Amendment 1, item 2).**  The bridge
decomposition of the scale-zero correlator into the terminal IR part plus the
concrete UV sum of the produced remainders HOLDS — it is proved by
telescoping, not postulated as a structure field.  This is the exact identity
that the B-1 `CorrelatorBridge` carries as a field; here it has provenance. -/
theorem provenant_decomposition {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (nsc : ℕ → ℕ) (t : ℕ) :
    covEff F f 0 t
      = provenantCovIR F f nsc t + covUV_concrete (provenantRsc F f) nsc t := by
  have h : ∑ k ∈ Finset.range (nsc t),
      (covEff F f k t - covEff F f (k + 1) t)
        = covEff F f 0 t - covEff F f (nsc t) t :=
    Finset.sum_range_sub' (fun k => covEff F f k t) (nsc t)
  simp only [covUV_concrete, provenantRsc, provenantCovIR]
  rw [h]
  ring

/-- **The provenant bridge:** the `CorrelatorBridge` of the scale-zero
effective correlator whose fields are DEFINED from the flow family and whose
decomposition field IS the telescoping theorem.  Nothing in it is selected. -/
noncomputable def provenantBridge {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (nsc : ℕ → ℕ) :
    CorrelatorBridge (covEff F f 0) where
  covIR := provenantCovIR F f nsc
  Rsc := provenantRsc F f
  nsc := nsc
  decomposition := provenant_decomposition F f nsc

@[simp] theorem provenantBridge_covIR {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (nsc : ℕ → ℕ) :
    (provenantBridge F f nsc).covIR = provenantCovIR F f nsc := rfl

@[simp] theorem provenantBridge_Rsc {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (nsc : ℕ → ℕ) :
    (provenantBridge F f nsc).Rsc = provenantRsc F f := rfl

@[simp] theorem provenantBridge_nsc {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) (nsc : ℕ → ℕ) :
    (provenantBridge F f nsc).nsc = nsc := rfl

/-- **Provenance of nonzero UV content:** if any produced remainder is
nonzero, the generating map genuinely moves the corresponding effective
measure.  Nonvanishing `Rsc` can no longer be a re-labeling — it certifies an
actual transformation acting on an actual measure. -/
theorem step_moves_of_provenantRsc_ne_zero {μ₀ : Measure (GaugeConfig d N G)}
    (F : RGFlowFamily μ₀) (f : G → ℝ) {t k : ℕ}
    (h : provenantRsc F f t k ≠ 0) : F.step (F.mu k) ≠ F.mu k := by
  intro heq
  apply h
  unfold provenantRsc covEff
  rw [F.mu_succ k, heq, sub_self]

/-- **Gibbs integral in `Z`-quotient form** — with NO hypotheses: for the
tilted (Gibbs) measure of ANY base measure and ANY plaquette energy, the
integral of ANY observable equals the unnormalized Boltzmann integral divided
by the partition function.  (The pinned Mathlib `integral_tilted` is
hypothesis-free; both sides degrade consistently in pathological cases.) -/
theorem integral_gibbsMeasure_eq_div (μ : Measure G) (pe : G → ℝ) (β : ℝ)
    (h : GaugeConfig d N G → ℝ) :
    ∫ A, h A ∂(gibbsMeasure (d := d) (N := N) μ pe β)
      = (∫ A, h A * Real.exp (-β * wilsonAction pe A)
            ∂(gaugeMeasureFrom (d := d) (N := N) μ))
          / partitionFunction (d := d) (N := N) μ pe β := by
  unfold gibbsMeasure partitionFunction
  rw [MeasureTheory.integral_tilted]
  rw [← MeasureTheory.integral_div]
  congr 1
  funext A
  dsimp only
  rw [smul_eq_mul]
  ring

end EffectiveFamily

section WilsonAnchor

variable {d N : ℕ} [NeZero d] [NeZero N]

/-- **The Wilson Gibbs measure** of the SU(N_c) theory at coupling `β`: the
honest `Measure.tilted` of the product Haar measure by the Wilson Boltzmann
weight — the actual measure whose correlators the B-1 anchor computes in
`Z`-quotient form. -/
noncomputable def wilsonGibbsMeasure (N_c : ℕ) [NeZero N_c] (β : ℝ) :
    Measure (GaugeConfig d N ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ)) :=
  gibbsMeasure (d := d) (N := N) (sunHaarProb N_c) (fundamentalObservable N_c) β

/-- **Measure-level anchor, per pair:** the truncated correlator OF the Wilson
Gibbs measure equals the B-1 `Z`-quotient Wilson correlator — exactly, with no
hypotheses. -/
theorem truncatedPlaquetteCorrelatorOfMeasure_wilsonGibbs (N_c : ℕ)
    [NeZero N_c] (f : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) → ℝ) (β : ℝ)
    (p q : ConcretePlaquette d N) :
    truncatedPlaquetteCorrelatorOfMeasure
        (wilsonGibbsMeasure (d := d) (N := N) N_c β) f p q
      = wilsonTruncatedPlaquetteCorrelator (d := d) (N := N) N_c f β p q := by
  unfold truncatedPlaquetteCorrelatorOfMeasure wilsonTruncatedPlaquetteCorrelator
    wilsonGibbsMeasure
  rw [integral_gibbsMeasure_eq_div, integral_gibbsMeasure_eq_div,
    integral_gibbsMeasure_eq_div]

/-- **Measure-level anchor, ray form:** the ray correlator OF the Wilson Gibbs
measure equals the B-1 `wilsonRayCorrelator`. -/
theorem rayCorrelatorOfMeasure_wilsonGibbs (N_c : ℕ) [NeZero N_c]
    (f : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) → ℝ) (β : ℝ) (t : ℕ) :
    rayCorrelatorOfMeasure (wilsonGibbsMeasure (d := d) (N := N) N_c β) f t
      = wilsonRayCorrelator (d := d) (N := N) N_c f β t := by
  unfold rayCorrelatorOfMeasure wilsonRayCorrelator
  split_ifs with h
  · exact truncatedPlaquetteCorrelatorOfMeasure_wilsonGibbs N_c f β _ _
  · rfl

/-- **The scale-zero effective correlator of any Wilson-anchored family IS the
physical Wilson correlator** — the anchoring that the gate consumes. -/
theorem covEff_zero_eq_wilsonRayCorrelator (N_c : ℕ) [NeZero N_c] (β : ℝ)
    (F : RGFlowFamily (wilsonGibbsMeasure (d := d) (N := N) N_c β))
    (f : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) → ℝ) (t : ℕ) :
    covEff F f 0 t = wilsonRayCorrelator (d := d) (N := N) N_c f β t := by
  unfold covEff
  rw [F.mu_zero]
  exact rayCorrelatorOfMeasure_wilsonGibbs N_c f β t

/-- **THE HONEST GATE (Amendment 1, item 3).**  There EXISTS an RG flow family
STARTING AT THE WILSON GIBBS MEASURE such that (i) the terminal
`provenantCovIR` satisfies the exponential IR bound, and (ii) the PRODUCED
`provenantRsc` satisfies `SingleScaleUVDecay` with a marginal coupling flow.
NO free `Rsc` anywhere: every remainder is a difference of correlators of
actual measures generated by ONE map from the Wilson start
(`RGFlowFamily.mu_eq_iterate`), and any nonzero remainder certifies that the
map moves the measure (`step_moves_of_provenantRsc_ne_zero`).

This gate moves the open question to the two bounds for the PRODUCED `Rsc`
and the PRODUCED terminal `covIR` — establishing them for a genuine
(nonconstant) step map is the fluctuation-integration problem, G5-adjacent.
The old `RegimeCoherentWilsonBridge` remains as a NECESSARY interface only:
it is satisfiable by re-labeling known decay (Amendment 1 counterexample) and
does not certify UV provenance.

HONESTY: this Prop is still satisfiable with zero UV content — the degenerate
constant flow discharges it at strong coupling
(`rgProvenantWilsonBridge_strong_coupling` below, stated openly).  What it can
NO LONGER be satisfied by is a per-scale scalar selection: nonzero UV content
now requires an actual transformation of actual measures whose correlator
differences carry the decay.  `step` is not yet constrained to a concrete
block/decimation kernel; that strengthening is the B-2 continuation. -/
def RGProvenantWilsonBridge (N_c : ℕ) [NeZero N_c]
    (f : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) → ℝ) (β : ℝ) : Prop :=
  ∃ (F : RGFlowFamily (wilsonGibbsMeasure (d := d) (N := N) N_c β))
    (nsc : ℕ → ℕ) (g : ℕ → ℝ) (C1 C2 ε c0 βc κ₀ : ℝ),
    0 < ε ∧ 0 < c0 ∧ 0 ≤ C2 ∧ 1 < κ₀ ∧ 0 < βc ∧
    (∀ k, 0 < g k) ∧ (∀ k, βc * g k < 1) ∧
    (∀ k, g (k + 1) = g k * (1 - βc * g k)) ∧
    (∀ t : ℕ, |provenantCovIR F f nsc t| ≤ C1 * Real.exp (-(ε * (t : ℝ)))) ∧
    SingleScaleUVDecay (provenantRsc F f) g C2 c0 κ₀

/-- **Gate consumer.**  If the provenant gate holds, the PHYSICAL Wilson ray
correlator has the mass-gap-shaped exponential decay: the provenant bridge
feeds `physical_mass_gap_of_bridge`, and the scale-zero anchor identity
converts the conclusion to the Wilson correlator itself. -/
theorem wilson_mass_gap_of_rgProvenantBridge (N_c : ℕ) [NeZero N_c]
    (f : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) → ℝ) (β : ℝ)
    (hgate : RGProvenantWilsonBridge (d := d) (N := N) N_c f β) :
    ∃ C gap : ℝ, 0 < gap ∧ ∀ t : ℕ,
      |wilsonRayCorrelator (d := d) (N := N) N_c f β t|
        ≤ C * Real.exp (-(gap * (t : ℝ))) := by
  obtain ⟨F, nsc, g, C1, C2, ε, c0, βc, κ₀, hε, hc0, hC2, hκ, hβc,
    hpos, hsmall, hrec, hIR, hUV⟩ := hgate
  obtain ⟨gap, hgap, hbound⟩ :=
    physical_mass_gap_of_bridge (covEff F f 0) (provenantBridge F f nsc) g
      hε hc0 hC2 hκ hβc hpos hsmall hrec
      (by intro k; simpa using hIR k)
      (by intro t k; simpa using hUV t k)
  refine ⟨C1 + C2 * ∑' k, g k ^ κ₀, gap, hgap, fun t => ?_⟩
  rw [← covEff_zero_eq_wilsonRayCorrelator N_c β F f t]
  exact hbound t

end WilsonAnchor

section NonVacuity

variable {d N : ℕ} [NeZero d] [NeZero N] {G : Type*} [Group G] [MeasurableSpace G]

/-- **The degenerate flow:** `step = id`, every effective measure is the
start.  It generates a legitimate family — and carries, by construction, zero
ultraviolet content. -/
def constantFlow (μ₀ : Measure (GaugeConfig d N G)) : RGFlowFamily μ₀ where
  step := id
  mu := fun _ => μ₀
  mu_zero := rfl
  mu_succ := fun _ => rfl

/-- Over the constant flow every produced remainder vanishes identically:
zero UV content is exactly what the degenerate flow produces. -/
theorem provenantRsc_constantFlow (μ₀ : Measure (GaugeConfig d N G))
    (f : G → ℝ) (t k : ℕ) :
    provenantRsc (constantFlow μ₀) f t k = 0 := by
  simp [provenantRsc, covEff, constantFlow]

/-- **The B-1 trivial bridge is RECOVERED as the degenerate flow** (IR field):
the provenant bridge of the constant flow declares everything infrared, like
`trivialBridge`. -/
theorem provenantBridge_constantFlow_covIR (μ₀ : Measure (GaugeConfig d N G))
    (f : G → ℝ) (nsc : ℕ → ℕ) :
    (provenantBridge (constantFlow μ₀) f nsc).covIR
      = (trivialBridge (covEff (constantFlow μ₀) f 0)).covIR := rfl

/-- **The B-1 trivial bridge is RECOVERED as the degenerate flow** (UV field):
the produced remainders of the constant flow are the trivial bridge's zeros.
Together with `provenantBridge_constantFlow_covIR` this shows the provenant
pipeline is inhabited WITHOUT gaming — the only way this module produces the
trivial decomposition is the honestly degenerate flow, and any flow with a
nonzero produced remainder must genuinely move a measure
(`step_moves_of_provenantRsc_ne_zero`). -/
theorem provenantBridge_constantFlow_Rsc (μ₀ : Measure (GaugeConfig d N G))
    (f : G → ℝ) (nsc : ℕ → ℕ) :
    (provenantBridge (constantFlow μ₀) f nsc).Rsc
      = (trivialBridge (covEff (constantFlow μ₀) f 0)).Rsc := by
  funext t k
  simp [trivialBridge, provenantRsc_constantFlow]

/-- **NON-VACUITY OF THE GATE (degenerate, stated openly).**  In the certified
strong-coupling window the constant flow discharges every clause of
`RGProvenantWilsonBridge`: the terminal IR part IS the physical correlator
(which decays by the proved clustering), and the produced UV remainders are
identically zero.  HONESTY: this witness carries NO ultraviolet content and NO
weak-coupling progress — it shows the gate is inhabited and the consumer
fires end-to-end at the physical measure.  The open frontier is a witness
whose flow is NONCONSTANT with nonvanishing produced remainders. -/
theorem rgProvenantWilsonBridge_strong_coupling (N_c : ℕ) [NeZero N_c] :
    ∃ β₀ : ℝ, 0 < β₀ ∧ ∀ β : ℝ, |β| ≤ β₀ →
      ∀ (f : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) → ℝ),
        Measurable f → (∀ x, |f x| ≤ 1) →
      RGProvenantWilsonBridge (d := d) (N := N) N_c f β := by
  obtain ⟨β₀, hβ₀, hwin⟩ :=
    wilsonRayCorrelator_strong_coupling_decay (d := d) (N := N) N_c
  refine ⟨β₀, hβ₀, fun β hβ f hfm hf => ?_⟩
  obtain ⟨C, hC0, hIR⟩ := hwin β hβ
  obtain ⟨g, βc, hβc, hpos, hsmall, hrec⟩ := exists_marginal_coupling_flow
  refine ⟨constantFlow _, fun _ => 0, g, C, 0, 1, 1, βc, 2,
    one_pos, one_pos, le_rfl, one_lt_two, hβc, hpos, hsmall, hrec, ?_, ?_⟩
  · intro t
    have hconst : provenantCovIR
        (constantFlow (wilsonGibbsMeasure (d := d) (N := N) N_c β)) f
        (fun _ => 0) t
          = wilsonRayCorrelator (d := d) (N := N) N_c f β t := by
      show rayCorrelatorOfMeasure
          (wilsonGibbsMeasure (d := d) (N := N) N_c β) f t = _
      exact rayCorrelatorOfMeasure_wilsonGibbs N_c f β t
    rw [hconst]
    simpa using hIR f hfm hf t
  · intro t k
    simp [provenantRsc, covEff, constantFlow]

end NonVacuity

end YangMills.RG
