import YangMills.RG.FinitePiLpScalarCommutator

open YangMills.RG

#print axioms finitePiLpScalarCommutator
#print axioms finitePiLpScalarCommutator_single_apply
#print axioms finitePiLpScalarCommutator_kernelBound
#print axioms finitePiLpScalarCommutator_tensorCutoff_kernelBound
#print axioms mul_exp_neg_le_two_div_mul_exp_neg_half
#print axioms finitePiLpScalarCommutator_exponentialKernelBound_of_lipschitz
#print axioms finitePiLpScalarCommutator_tensorCutoff_exponentialKernelBound
#print axioms finitePiLpOperatorScalarCommutator
#print axioms finitePiLpOperatorScalarCommutator_eq_neg
#print axioms finitePiLpOperatorScalarCommutator_single_apply
#print axioms norm_sq_sub_sq_le_two_mul
#print axioms finitePiLpOperatorScalarCommutator_sq_exponentialKernelBound
#print axioms finitePiLpOperatorScalarCommutator_tensorCutoff_sq_exponentialKernelBound
#print axioms finitePiLpOpNorm_le_of_exponentialKernelBound
#print axioms norm_finitePiLpOperatorScalarCommutator_tensorCutoff_sq_le
