import YangMills.RG.FinitePiLpTypedKernelReindexRectangularAlgebra

#print axioms YangMills.RG.finitePiLpTypedKernelReindex_rect_comp
#print axioms YangMills.RG.finitePiLpTypedKernelReindex_adjoint
#print axioms YangMills.RG.finitePiLpTypedKernelReindex_adjoint_comp_self
