import YangMills.RG.FinitePiLpCanonicalComplexification

#print axioms YangMills.RG.finitePiLpComplexRealPart
#print axioms YangMills.RG.finitePiLpComplexImagPart
#print axioms YangMills.RG.finitePiLpComplexOfReal
#print axioms YangMills.RG.finitePiLpComplexOfReal_zero
#print axioms YangMills.RG.finitePiLpComplexOfReal_real_add_I_smul_imag
#print axioms YangMills.RG.finitePiLpComplexRealPart_ofReal
#print axioms YangMills.RG.finitePiLpComplexImagPart_ofReal
#print axioms YangMills.RG.finitePiLpCanonicalComplexificationLM
#print axioms YangMills.RG.finitePiLpCanonicalComplexificationCLM
#print axioms YangMills.RG.finitePiLpComplexRealPart_complexification
#print axioms YangMills.RG.finitePiLpComplexImagPart_complexification
#print axioms YangMills.RG.finitePiLpCanonicalComplexificationCLM_ofReal
#print axioms YangMills.RG.finitePiLpCanonicalComplexificationCLM_comp
#print axioms YangMills.RG.finitePiLpCanonicalComplexificationCLM_id
