/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under the GNU Affero General Public License v3.0
as described in the file LICENSE.
Authors: Lluis Eriksson -/

import YangMills.RG.AnalyticThirdDerivativeChangeOriginBound
import YangMills.RG.NearLogAnalytic
import Mathlib.Analysis.Normed.Algebra.Exponential

/-!
# Third jets of the noncommutative logarithm and exponential

The analytic series themselves generate the third changed-origin
coefficient.  Hence the resulting third-jet budgets are concrete functions
of the physical base point, not free derivative hypotheses.
-/

namespace YangMills.RG

open scoped ENNReal

noncomputable section

variable {A : Type*}
variable [NormedRing A] [NormedAlgebra ℝ A] [CompleteSpace A]
  [NormOneClass A]

/-- The pointwise third-jet budget generated by the Mercator series. -/
def nearLogThirdDerivativeChangeOriginBudget (Y : A) : ℝ :=
  6 * ‖(nearLogFPowerSeries (𝔸 := A)).changeOrigin Y 3‖

/-- The pointwise third-jet budget generated by the exponential series. -/
def expThirdDerivativeChangeOriginBudget (Y : A) : ℝ :=
  6 * ‖(NormedSpace.expSeries ℝ A).changeOrigin Y 3‖

/-- Uniform third-jet budget for `nearLog` on a strict closed Mercator
sub-ball. -/
def nearLogThirdDerivativeBallBudget (r : NNReal) : ℝ :=
  thirdDerivativeChangeOriginBallBudget
    (nearLogFPowerSeries (𝔸 := A)) r

/-- Uniform third-jet budget for the exponential on a closed norm ball. -/
def expThirdDerivativeBallBudget (r : NNReal) : ℝ :=
  thirdDerivativeChangeOriginBallBudget
    (NormedSpace.expSeries ℝ A) r

omit [CompleteSpace A] [NormOneClass A] in
theorem nearLogThirdDerivativeChangeOriginBudget_nonneg (Y : A) :
    0 ≤ nearLogThirdDerivativeChangeOriginBudget Y := by
  unfold nearLogThirdDerivativeChangeOriginBudget
  positivity

omit [CompleteSpace A] [NormOneClass A] in
theorem expThirdDerivativeChangeOriginBudget_nonneg (Y : A) :
    0 ≤ expThirdDerivativeChangeOriginBudget Y := by
  unfold expThirdDerivativeChangeOriginBudget
  positivity

omit [CompleteSpace A] [NormOneClass A] in
theorem nearLogThirdDerivativeBallBudget_nonneg (r : NNReal) :
    0 ≤ nearLogThirdDerivativeBallBudget (A := A) r :=
  thirdDerivativeChangeOriginBallBudget_nonneg _ _

omit [CompleteSpace A] [NormOneClass A] in
theorem expThirdDerivativeBallBudget_nonneg (r : NNReal) :
    0 ≤ expThirdDerivativeBallBudget (A := A) r :=
  thirdDerivativeChangeOriginBallBudget_nonneg _ _

/-- The actual third derivative of `nearLog` is bounded by its generated
third changed-origin coefficient at every point of the Mercator ball. -/
theorem norm_iteratedFDeriv_three_nearLog_le_changeOriginBudget
    {Y : A} (hY : ‖Y‖ < 1) :
    ‖iteratedFDeriv ℝ 3 (nearLog : A → A) Y‖ ≤
      nearLogThirdDerivativeChangeOriginBudget Y := by
  have hY' :
      (‖Y‖₊ : ℝ≥0∞) <
        (nearLogFPowerSeries (𝔸 := A)).radius := by
    have hYone : (‖Y‖₊ : ℝ≥0∞) < 1 := by
      exact_mod_cast hY
    exact hYone.trans_le nearLogFPowerSeries_radius_ge_one
  simpa [nearLogThirdDerivativeChangeOriginBudget] using
    norm_iteratedFDeriv_three_le_six_mul_changeOrigin
      (nearLog : A → A) (nearLogFPowerSeries (𝔸 := A))
      hasFPowerSeriesOnBall_nearLog Y hY'

/-- Uniform third derivative of `nearLog` on a strict closed Mercator
sub-ball, generated by the literal Mercator coefficients. -/
theorem norm_iteratedFDeriv_three_nearLog_le_ballBudget
    (r : NNReal) (hr : (r : ℝ) < 1)
    {Y : A} (hY : ‖Y‖₊ ≤ r) :
    ‖iteratedFDeriv ℝ 3 (nearLog : A → A) Y‖ ≤
      nearLogThirdDerivativeBallBudget (A := A) r := by
  have hr' :
      (r : ℝ≥0∞) < (nearLogFPowerSeries (𝔸 := A)).radius := by
    have hrone : (r : ℝ≥0∞) < 1 := by
      exact_mod_cast hr
    exact hrone.trans_le nearLogFPowerSeries_radius_ge_one
  simpa [nearLogThirdDerivativeBallBudget] using
    norm_iteratedFDeriv_three_le_changeOriginBallBudget
      (nearLog : A → A) (nearLogFPowerSeries (𝔸 := A))
      hasFPowerSeriesOnBall_nearLog r hr' le_rfl hY

omit [NormOneClass A] in
/-- The actual third derivative of the noncommutative exponential is
bounded by its generated third changed-origin coefficient at every point. -/
theorem norm_iteratedFDeriv_three_exp_le_changeOriginBudget
    (Y : A) :
    ‖iteratedFDeriv ℝ 3 (NormedSpace.exp : A → A) Y‖ ≤
      expThirdDerivativeChangeOriginBudget Y := by
  simpa [expThirdDerivativeChangeOriginBudget] using
    norm_iteratedFDeriv_three_le_six_mul_changeOrigin
      (NormedSpace.exp : A → A) (NormedSpace.expSeries ℝ A)
      NormedSpace.exp_hasFPowerSeriesOnBall Y ENNReal.coe_lt_top

omit [NormOneClass A] in
/-- Uniform third derivative of the noncommutative exponential on a
closed norm ball, generated by the literal factorial coefficients. -/
theorem norm_iteratedFDeriv_three_exp_le_ballBudget
    (r : NNReal) {Y : A} (hY : ‖Y‖₊ ≤ r) :
    ‖iteratedFDeriv ℝ 3 (NormedSpace.exp : A → A) Y‖ ≤
      expThirdDerivativeBallBudget (A := A) r := by
  have hr' :
      (r : ℝ≥0∞) < (NormedSpace.expSeries ℝ A).radius := by
    rw [NormedSpace.expSeries_radius_eq_top]
    exact ENNReal.coe_lt_top
  simpa [expThirdDerivativeBallBudget] using
    norm_iteratedFDeriv_three_le_changeOriginBallBudget
      (NormedSpace.exp : A → A) (NormedSpace.expSeries ℝ A)
      NormedSpace.exp_hasFPowerSeriesOnBall r hr' le_top hY

end

end YangMills.RG
