/-
Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cowork agent (Claude), under supervision of Lluis Eriksson
-/
import Mathlib

/-!
# Multiscale σ-algebra chain (Bloque-4 §6 step 1)

This module formalises the **σ-algebra chain** underlying the
multiscale correlator decoupling of Eriksson's Bloque-4 paper §6.

The chain represents block-spin coarsenings of a lattice gauge
configuration at successive scales `a_0 < a_1 < ⋯ < a_*`:

```
σ_{a_0}    ⊃    σ_{a_1}    ⊃    ⋯    ⊃    σ_{a_*}
(finest)        (coarser)              (terminal/coarsest)
```

Each `σ_{a_k}` is the σ-algebra generated by gauge-field block-spin
variables at scale `a_k`. The full ambient σ-algebra `m₀` (e.g., of
the original lattice `Λ_η`) sits above `σ_{a_0}`.

## Strategic placement

This is **Phase 93** of the L7_Multiscale block (Phases 93-97),
realising the blueprint from `BLUEPRINT_MultiscaleDecoupling.md`
(Phase 84).

This file provides the bare data structure; Phase 94 defines the
single-scale UV error bound on it; Phase 95 the telescoping
identity; Phase 96 the geometric summation; Phase 97 the
endpoint theorem.

## Oracle target

`[propext, Classical.choice, Quot.sound]`.

-/

namespace YangMills.L7_Multiscale

open MeasureTheory

variable {Ω : Type*} [m₀ : MeasurableSpace Ω]

/-! ## §1. The σ-algebra chain structure -/

/-- A **descending chain of σ-algebras** representing block-spin
    coarsenings at scales `a_0 < a_1 < ⋯ < a_{k_star}`.

    Mathematically, `σ k.castSucc ⊇ σ k.succ` for each `k : Fin k_star`.

    All σ-algebras are sub-σ-algebras of the ambient `m₀`. -/
structure MultiscaleSigmaAlgebraChain
    (Ω : Type*) [m₀ : MeasurableSpace Ω] (k_star : ℕ) where
  /-- The σ-algebra at scale `k`, indexed `0 ≤ k ≤ k_star`. -/
  σ : Fin (k_star + 1) → MeasurableSpace Ω
  /-- The chain is descending: σ at successor is coarser than at predecessor. -/
  σ_descending : ∀ k : Fin k_star,
    σ k.succ ≤ σ k.castSucc
  /-- Each σ-algebra is below the ambient. -/
  σ_below_top : ∀ k, σ k ≤ m₀

/-! ## §2. Basic operations -/

/-- The **first** σ-algebra in the chain (finest, scale `a_0`). -/
def MultiscaleSigmaAlgebraChain.σ_first
    {k_star : ℕ} (chain : MultiscaleSigmaAlgebraChain Ω k_star) :
    MeasurableSpace Ω :=
  chain.σ 0

/-- The **last** σ-algebra in the chain (coarsest, terminal scale `a_*`). -/
def MultiscaleSigmaAlgebraChain.σ_last
    {k_star : ℕ} (chain : MultiscaleSigmaAlgebraChain Ω k_star) :
    MeasurableSpace Ω :=
  chain.σ (Fin.last k_star)

/-- The chain is **transitively descending**: any later σ-algebra is
    coarser than any earlier one. -/
theorem MultiscaleSigmaAlgebraChain.σ_descending_trans
    {k_star : ℕ} (chain : MultiscaleSigmaAlgebraChain Ω k_star)
    (i j : Fin (k_star + 1)) (hij : i ≤ j) :
    chain.σ j ≤ chain.σ i := by
  -- Induction on the gap j - i.
  obtain ⟨n, hn⟩ : ∃ n, j.val = i.val + n := ⟨j.val - i.val, by omega⟩
  -- We need to show σ j ≤ σ i. Use induction on n.
  induction n with
  | zero =>
    -- j = i, so the inequality is trivial.
    have : j = i := Fin.eq_of_val_eq (by omega)
    rw [this]
  | succ n ih =>
    -- Use the descending step: σ (i+n+1) ≤ σ (i+n) ≤ σ i (by IH).
    -- For this we need to construct the right Fin elements carefully.
    -- Skip the detailed induction for now; use the abstract result.
    -- The chain is descending step-by-step via σ_descending; transitivity
    -- follows by composition. A cleaner Lean proof would use a helper
    -- structuring the iteration. We expose the abstract claim here.
    have h_transitivity : ∀ k : Fin (k_star + 1),
        ∀ m : ℕ, ∀ (h : k.val + m ≤ k_star),
          chain.σ ⟨k.val + m, by omega⟩ ≤ chain.σ k := by
      intro k m
      induction m with
      | zero => intro _; simp
      | succ p ih_p =>
        intro h
        have hp : k.val + p ≤ k_star := by omega
        specialize ih_p hp
        have h_step : chain.σ ⟨k.val + p + 1, by omega⟩ ≤
                      chain.σ ⟨k.val + p, by omega⟩ := by
          have : ⟨k.val + p + 1, by omega⟩ =
                 (⟨k.val + p, by omega⟩ : Fin k_star).succ ∧
                 (⟨k.val + p, by omega⟩ : Fin k_star).castSucc =
                 ⟨k.val + p, by omega⟩ := by
            refine ⟨?_, ?_⟩ <;> rfl
          exact chain.σ_descending ⟨k.val + p, by omega⟩
        calc chain.σ ⟨k.val + (p + 1), by omega⟩
            = chain.σ ⟨k.val + p + 1, by omega⟩ := by
              congr 1; ext; omega
          _ ≤ chain.σ ⟨k.val + p, by omega⟩ := h_step
          _ ≤ chain.σ k := ih_p
    have hj_eq : j = ⟨i.val + n.succ, by omega⟩ := Fin.eq_of_val_eq hn
    rw [hj_eq]
    exact h_transitivity i n.succ (by omega)

#print axioms MultiscaleSigmaAlgebraChain.σ_descending_trans

/-! ## §3. Trivial chain (existence + sanity) -/

/-- A **trivial multiscale chain** of length `k_star` where every
    σ-algebra equals the ambient `m₀`. Used as a sanity-check
    inhabitant of the structure (and the `k_star = 0` degenerate case). -/
def trivialMultiscaleChain
    (Ω : Type*) [m₀ : MeasurableSpace Ω] (k_star : ℕ) :
    MultiscaleSigmaAlgebraChain Ω k_star where
  σ := fun _ => m₀
  σ_descending := fun _ => le_refl m₀
  σ_below_top := fun _ => le_refl m₀

#print axioms trivialMultiscaleChain

/-! ## §4. Coordination note -/

/-
This file is **Phase 93** of the L7_Multiscale block (Phases 93-97).

## What's done

* `MultiscaleSigmaAlgebraChain` data structure: chain of σ-algebras
  with descending property + below-ambient property.
* Operations `σ_first`, `σ_last`.
* Theorem `σ_descending_trans` (transitivity of the descending
  property).
* `trivialMultiscaleChain` (sanity-check inhabitant).

## What's NOT done

* Concrete chains for the Yang-Mills application (block-spin σ-algebras
  at scales `a_k`). These come from Codex's `BalabanRG/` infrastructure
  and would use lattice-specific coarsening operators.

## Strategic value

Phase 93 establishes the **abstract carrier** for Branch VIII (the
multiscale correlator decoupling). Phases 94-97 build on it.

Cross-references:
- `BLUEPRINT_MultiscaleDecoupling.md` (Phase 84) — overall blueprint.
- `CREATIVE_ATTACKS_OPENING_TREE.md` Branch VIII (Phase 87).
- Mathlib's `MeasurableSpace`, `MeasurableSpace.le` — foundation.
-/

end YangMills.L7_Multiscale
