/- Copyright (c) 2026 Lluis Eriksson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lluis Eriksson -/
import YangMills.ClayCore.SchurTracePow

/-!
# Bilinear trace-power vanishing on SU(N_c)

Companion to `SchurTracePow.lean` (step 3a) and `SchurTraceUPow.lean` (step 3c).
Where those files prove *single-integrand* vanishings
(`∫ (tr U)^k dμ = 0`, `∫ tr(U^k) dμ = 0`), this file proves the *bilinear*
family:

  `∫ (tr U)^j · (star (tr U))^k dHaar = 0`  when  `k ≤ j`  and  `N_c ∤ (j - k)`.

Representation-theoretically this is `⟨(tr U)^j, (tr U)^k⟩_{L²(SU(N_c), μ_Haar)}`
— the character inner product of two tensor powers of the fundamental
representation.  Its vanishing at `j ≢ k (mod N_c)` (with `j ≥ k`) witnesses
Peter–Weyl orthogonality restricted to the subalgebra of class functions
generated by the first power sum.

## Proof

Same central-element technique, extended to the bilinear case.  With
`Ω := ω·I ∈ SU(N_c)` and `x := tr U`:

- `tr(Ω·U) = ω · x`  (from `trace_scalarCenter_mul`),
- `(ω · x)^j · (star (ω · x))^k = ω^j · (star ω)^k · (x^j · (star x)^k)`
  (via `mul_pow`, `star_mul`, `mul_pow` in sequence),
- `ω^j · (star ω)^k = ω^{j-k}`  (helper `rootOfUnity_pow_mul_star_pow`,
  from `ω · star ω = 1` and `(ω · star ω)^k = 1^k = 1`).

Haar left-invariance gives `J = ω^{j-k} · J`, hence `(1 - ω^{j-k}) · J = 0`;
when `N_c ∤ (j - k)`, `ω^{j-k} ≠ 1` forces `J = 0` via `rootOfUnity_pow_ne_one`.

## Asymmetry note

This file states only the `k ≤ j` case (natural-number difference).  The
symmetric case `j ≤ k` follows by taking complex conjugates of both sides:
`MeasureTheory.integral_conj` pushes `star` inside the integral, and the
bilinear integrand swaps into the `k ≥ j` orientation.  We do not package
that wrapper here; any downstream consumer can derive it in one line.

## Representation-theoretic meaning

In Peter–Weyl language, `(tr U)^j` is the character of `V^{⊗ j}` where `V`
is the fundamental representation.  By Schur–Weyl duality,

  `V^{⊗ j} = ⊕_{λ ⊢ j, ℓ(λ) ≤ N_c} V_λ ⊗ S^λ`,

a direct sum of Schur functors indexed by Young diagrams.  Character
orthogonality picks out the trivial summand; when `N_c ∤ (j - k)` (and
`j ≥ k`), no common irreducible summand appears in `V^{⊗ j}` and `V^{⊗ k}`
that also contains the trivial representation after tensoring — equivalently,
no diagram `λ ⊢ (j - k)` is a multiple of the single-column "determinant"
Young diagram `[1^{N_c}]`.  Hence the inner product vanishes.

## Corollaries

- `j = 1, k = 0, N_c ≥ 2`:  `∫ tr U dHaar = 0` (degenerate bilinear case,
  recovers the L2.6 step-0 witness).
- `j = 2, k = 1, N_c ≥ 2`:  `∫ (tr U)^2 · star(tr U) dHaar = 0`.
- `j = 3, k = 1, N_c ≥ 3`:  `∫ (tr U)^3 · star(tr U) dHaar = 0`.

A variant `sunHaarProb_trace_pow_bilinear_integral_zero'` is provided with
`star ((tr U)^k)` (star applied to the whole power) in place of
`(star (tr U))^k` — equivalent by `star_pow`, but sometimes the more natural
form for character inner products.

Oracle target: `[propext, Classical.choice, Quot.sound]`.
No sorry.  No new axioms.
-/

namespace YangMills

open MeasureTheory Matrix Complex

noncomputable section

/-! ## Algebraic helper: ω^j · (star ω)^k = ω^(j-k) for k ≤ j -/

/-- `ω^j · (star ω)^k = ω^{j-k}` whenever `k ≤ j`.  Follows from
`ω · star ω = 1` (via `star_rootOfUnity_mul_self` + `mul_comm`) and
`(ω · star ω)^k = 1^k = 1`. -/
theorem rootOfUnity_pow_mul_star_pow (N_c : ℕ) [NeZero N_c] {j k : ℕ} (hjk : k ≤ j) :
    rootOfUnity N_c ^ j * (star (rootOfUnity N_c)) ^ k =
    rootOfUnity N_c ^ (j - k) := by
  have hstar_cancel : rootOfUnity N_c * star (rootOfUnity N_c) = 1 := by
    rw [mul_comm]; exact star_rootOfUnity_mul_self N_c
  have hjeq : j = (j - k) + k := (Nat.sub_add_cancel hjk).symm
  calc rootOfUnity N_c ^ j * (star (rootOfUnity N_c)) ^ k
      = rootOfUnity N_c ^ ((j - k) + k) * (star (rootOfUnity N_c)) ^ k := by
          rw [← hjeq]
    _ = rootOfUnity N_c ^ (j - k) *
        (rootOfUnity N_c ^ k * (star (rootOfUnity N_c)) ^ k) := by
          rw [pow_add]; ring
    _ = rootOfUnity N_c ^ (j - k) *
        (rootOfUnity N_c * star (rootOfUnity N_c)) ^ k := by
          rw [← mul_pow]
    _ = rootOfUnity N_c ^ (j - k) * 1 ^ k := by rw [hstar_cancel]
    _ = rootOfUnity N_c ^ (j - k) := by rw [one_pow, mul_one]

/-! ## Trace of (Ω·U), bilinear form -/

/-- `(tr(Ω·U))^j · (star (tr(Ω·U)))^k = ω^{j-k} · ((tr U)^j · (star (tr U))^k)`
for `k ≤ j`.  Chains `trace_scalarCenter_mul` with `star_mul`, `mul_pow`,
`mul_pow`, then `rootOfUnity_pow_mul_star_pow` via `linear_combination`. -/
theorem trace_scalarCenter_mul_pow_bilinear (N_c : ℕ) [NeZero N_c]
    (U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ)) {j k : ℕ} (hjk : k ≤ j) :
    ((scalarCenterElement N_c * U).val.trace) ^ j *
      (star ((scalarCenterElement N_c * U).val.trace)) ^ k =
    rootOfUnity N_c ^ (j - k) *
      ((U.val.trace) ^ j * (star (U.val.trace)) ^ k) := by
  rw [trace_scalarCenter_mul, star_mul', mul_pow, mul_pow]
  linear_combination
    ((U.val.trace) ^ j * (star (U.val.trace)) ^ k) *
      rootOfUnity_pow_mul_star_pow N_c hjk

/-! ## Main theorem -/

/-- **Main theorem — bilinear trace-power vanishing.**  For `k ≤ j : ℕ` with
`¬ N_c ∣ (j - k)`, the Haar integral of `(tr U)^j · (star (tr U))^k` over
SU(N_c) vanishes.

Specializes at `(j, k) = (1, 0)` with `N_c ≥ 2` to recover the degree-1
zero-mean theorem. -/
theorem sunHaarProb_trace_pow_bilinear_integral_zero (N_c : ℕ) [NeZero N_c]
    {j k : ℕ} (hjk : k ≤ j) (hdiff : ¬ N_c ∣ (j - k)) :
    ∫ U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ),
      (U.val.trace) ^ j * (star (U.val.trace)) ^ k ∂(sunHaarProb N_c) = 0 := by
  set J : ℂ := ∫ U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ),
      (U.val.trace) ^ j * (star (U.val.trace)) ^ k ∂(sunHaarProb N_c) with hJdef
  -- Step 1: Haar left-invariance with Ω = ω·I
  have hinv : J = ∫ U, ((scalarCenterElement N_c * U).val.trace) ^ j *
                       (star ((scalarCenterElement N_c * U).val.trace)) ^ k
                       ∂(sunHaarProb N_c) := by
    rw [hJdef]; symm
    exact MeasureTheory.integral_mul_left_eq_self
          (fun U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) =>
              (U.val.trace) ^ j * (star (U.val.trace)) ^ k)
          (scalarCenterElement N_c)
  -- Step 2: pointwise rewrite
  have heq : (fun U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ) =>
               ((scalarCenterElement N_c * U).val.trace) ^ j *
               (star ((scalarCenterElement N_c * U).val.trace)) ^ k) =
             (fun U => rootOfUnity N_c ^ (j - k) *
                       ((U.val.trace) ^ j * (star (U.val.trace)) ^ k)) := by
    funext U; exact trace_scalarCenter_mul_pow_bilinear N_c U hjk
  -- Step 3: pull ω^(j-k) out of the integral
  have hmul : (∫ U, ((scalarCenterElement N_c * U).val.trace) ^ j *
                    (star ((scalarCenterElement N_c * U).val.trace)) ^ k
                    ∂(sunHaarProb N_c)) =
              rootOfUnity N_c ^ (j - k) * J := by
    calc ∫ U, ((scalarCenterElement N_c * U).val.trace) ^ j *
              (star ((scalarCenterElement N_c * U).val.trace)) ^ k
              ∂(sunHaarProb N_c)
        = ∫ U, rootOfUnity N_c ^ (j - k) *
              ((U.val.trace) ^ j * (star (U.val.trace)) ^ k) ∂(sunHaarProb N_c) := by
          rw [heq]
      _ = rootOfUnity N_c ^ (j - k) *
          ∫ U, (U.val.trace) ^ j * (star (U.val.trace)) ^ k ∂(sunHaarProb N_c) :=
          MeasureTheory.integral_const_mul _ _
      _ = rootOfUnity N_c ^ (j - k) * J := by rw [← hJdef]
  -- Step 4: (1 - ω^(j-k))·J = 0, and ω^(j-k) ≠ 1 forces J = 0
  rw [hmul] at hinv
  have hfactor : (1 - rootOfUnity N_c ^ (j - k)) * J = 0 := by
    linear_combination hinv
  rcases mul_eq_zero.mp hfactor with h1 | h2
  · exact absurd (sub_eq_zero.mp h1).symm (rootOfUnity_pow_ne_one N_c hdiff)
  · exact h2

/-! ## Variant: star of the whole power -/

/-- `∫ (tr U)^j · star((tr U)^k) dHaar = 0` — star applied to the whole
`k`-th power rather than per-factor.  Equivalent to the main theorem by
`star_pow`. -/
theorem sunHaarProb_trace_pow_bilinear_integral_zero'
    (N_c : ℕ) [NeZero N_c] {j k : ℕ} (hjk : k ≤ j) (hdiff : ¬ N_c ∣ (j - k)) :
    ∫ U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ),
      (U.val.trace) ^ j * star ((U.val.trace) ^ k) ∂(sunHaarProb N_c) = 0 := by
  simp only [star_pow]
  exact sunHaarProb_trace_pow_bilinear_integral_zero N_c hjk hdiff

/-! ## Concrete low-degree corollaries -/

/-- `∫ (tr U)^2 · star(tr U) dHaar = 0` on SU(N_c) for every `N_c ≥ 2`. -/
theorem sunHaarProb_trace_sq_mul_star_trace_integral_zero
    (N_c : ℕ) [NeZero N_c] (hN : 2 ≤ N_c) :
    ∫ U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ),
      (U.val.trace) ^ 2 * star (U.val.trace) ∂(sunHaarProb N_c) = 0 := by
  have hbase := sunHaarProb_trace_pow_bilinear_integral_zero
    (j := 2) (k := 1) N_c (by norm_num) (by
      intro h
      have hle : N_c ≤ 1 := Nat.le_of_dvd (by norm_num) (by simpa using h)
      omega)
  simpa [pow_one] using hbase

/-- `∫ (tr U)^3 · star(tr U) dHaar = 0` on SU(N_c) for every `N_c ≥ 3`. -/
theorem sunHaarProb_trace_cube_mul_star_trace_integral_zero
    (N_c : ℕ) [NeZero N_c] (hN : 3 ≤ N_c) :
    ∫ U : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ),
      (U.val.trace) ^ 3 * star (U.val.trace) ∂(sunHaarProb N_c) = 0 := by
  have hbase := sunHaarProb_trace_pow_bilinear_integral_zero
    (j := 3) (k := 1) N_c (by norm_num) (by
      intro h
      have hle : N_c ≤ 2 := Nat.le_of_dvd (by norm_num) (by simpa using h)
      omega)
  simpa [pow_one] using hbase

/-! ## Non-triviality witness -/

/-- At `1 ∈ SU(N_c)`, the bilinear integrand evaluates to `(N_c : ℂ)^{j+k}`:
`tr(1) = N_c`, `star (N_c : ℂ) = (N_c : ℂ)` (natural-cast self-conjugate),
and powers add via `← pow_add`. -/
theorem sunHaarProb_trace_pow_bilinear_at_one (N_c : ℕ) [NeZero N_c] (j k : ℕ) :
    ((1 : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ)).val.trace) ^ j *
      (star ((1 : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ)).val.trace)) ^ k =
    (N_c : ℂ) ^ (j + k) := by
  have hval : (1 : ↥(Matrix.specialUnitaryGroup (Fin N_c) ℂ)).val =
      (1 : Matrix (Fin N_c) (Fin N_c) ℂ) := rfl
  rw [hval, Matrix.trace_one, Fintype.card_fin, star_natCast, ← pow_add]

end

end YangMills
