import YangMills.RG.PhysicalCoerciveCombesThomasInverse
import YangMills.RG.CoerciveCovariancePositiveSqrt
import YangMills.RG.PhysicalGaugeCovariancePositiveRoot
import YangMills.RG.StieltjesKernelIntegration

/-!
Focused axiom audit for the eighteen declarations claimed as formalized in
`shift_uniform_combes_thomas.tex`.
-/

#print axioms YangMills.RG.physicalTiltConjCLM_id
#print axioms YangMills.RG.physicalTiltConjCLM_add_smul_id_sub
#print axioms YangMills.RG.isCoerciveCLM_add_smul_id
#print axioms YangMills.RG.norm_physicalTiltConj_add_smul_id_sub_le
#print axioms YangMills.RG.isCoerciveCLM_physicalTiltConj_add_smul_id
#print axioms YangMills.RG.isCoerciveCLM_physicalTiltConj_add_smul_id_half
#print axioms YangMills.RG.physicalCovariance_exponentialKernelBound_of_coercive_add_smul_id
#print axioms YangMills.RG.finiteDimensionalRealPositiveSqrt_comp_self
#print axioms YangMills.RG.finiteDimensionalRealPositiveSqrt_isPositive
#print axioms YangMills.RG.covarianceSqrtOfIsCoerciveCLM_comp_self
#print axioms YangMills.RG.covarianceSqrtOfIsCoerciveCLM_isPositive
#print axioms YangMills.RG.physicalLocalizedCovarianceRootCertificate_of_positive_covariance
#print axioms YangMills.RG.norm_covarianceSqrtOfIsCoerciveCLM_le
#print axioms YangMills.RG.physicalLocalizedCovarianceRootCertificate_of_coercive_precision
#print axioms YangMills.RG.integrableOn_Ioi_inv_add_sq
#print axioms YangMills.RG.integral_Ioi_inv_add_sq
#print axioms YangMills.RG.physicalCovarianceKernelBound_stieltjesIntegralOperator
#print axioms YangMills.RG.physicalCovariance_exponentialKernelBound_stieltjesIntegralOperator
